### ISSUE TITLE
csi-rbd provisioner resources

### ISSUE THREAD

**Issue by kfox1111** [ceph/ceph-csi#1001]
The helm chart does not allow you to independently set resources for the csi-rbdplugin in the provisioner separately from the node. We are finding that the mememory uses are different for each. The node is how many parallel mounts need to happen at once. The provisioner needs more memory to cover all the creates/deletes that can happen in parallel.

**Comment by nixpanic** [comment]
@Madhu-1 or @leseb were you not looking into this for Rook?

**Comment by Madhu-1** [comment]
this is already fixed in rook

**Comment by Madhu-1** [comment]
here it is https://github.com/rook/rook/pull/5287

**Comment by nixpanic** [comment]
Should this not also get added to the Helm charts and examples we maintain in this repository?

**Comment by Madhu-1** [comment]
yes, these changes we need in helm charts, its kind of refactoring the helm value.yaml files.
