### ISSUE TITLE
CephFS CSI driver not update quota when pvc request size resized

### ISSUE THREAD

**Issue by LuckySB** [ceph/ceph-csi#1002]
# Describe the bug #
Change in pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileshare
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: csi-cephfs-sc
```
storage: 20Mi

pv and pvc object in kubernetes changed
```
k get pv
pvc-60f6f968-050b-4a28-9112-db8de1747e6b   20Mi       RWX            Delete           Bound       default/fileshare                               csi-cephfs-sc            120m
k get pvc
fileshare        Bound    pvc-60f6f968-050b-4a28-9112-db8de1747e6b   20Mi       RWX            csi-cephfs-sc   121m
```

but quota on cephfs directory not changed
```
getfattr -n ceph.quota.max_bytes 5f858910-7fcf-408d-a14b-4c192aaa546e/
# file: 5f858910-7fcf-408d-a14b-4c192aaa546e/
ceph.quota.max_bytes="10485760"

```
# Environment details #

- Image/version of Ceph CSI driver
2.1.0
- helm chart version
- Kubernetes cluster version
1.16.9
- Logs
`k logs ceph-csi-cephfs-provisioner-6d7cb9978b-b58nh -c csi-resizer`
```
I0502 15:37:39.591857       1 controller.go:225] Started PVC processing "default/fileshare"
I0502 15:37:39.612923       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"fileshare", UID:"60f6f968-050b-4a28-9112-db8de1747e6b", APIVersion:"v1", ResourceVersion:"79966", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-60f6f968-050b-4a28-9112-db8de1747e6b
I0502 15:37:39.622313       1 connection.go:182] GRPC call: /csi.v1.Controller/ControllerExpandVolume
I0502 15:37:39.622335       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":20971520},"secrets":"***stripped***","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["debug"]}},"access_mode":{"mode":5}},"volume_id":"0001-0024-bcd0d202-fba8-4352-b25d-75c89258d5ab-0000000000000001-22b377c5-8c7b-11ea-b1ba-ea0c41f9366d"}
I0502 15:37:41.505427       1 connection.go:185] GRPC response: {"capacity_bytes":20971520}
I0502 15:37:41.506125       1 connection.go:186] GRPC error: <nil>
I0502 15:37:41.506139       1 controller.go:364] Resize volume succeeded for volume "pvc-60f6f968-050b-4a28-9112-db8de1747e6b", start to update PV's capacity
I0502 15:37:41.543608       1 controller.go:370] Update capacity of PV "pvc-60f6f968-050b-4a28-9112-db8de1747e6b" to 20Mi succeeded
I0502 15:37:41.551288       1 controller.go:399] Resize PVC "default/fileshare" finished
I0502 15:37:41.551661       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"fileshare", UID:"60f6f968-050b-4a28-9112-db8de1747e6b", APIVersion:"v1", ResourceVersion:"79966", FieldPath:""}): type: 'Normal' reason: 'VolumeResizeSuccessful' Resize volume succeeded

```
# Steps to reproduce #

install csi cephfs driver from helm chart 2.1.0
config storage class
create pvc, wait for pv
change request storage size in pvc - look on cephfs quotas

**Comment by Madhu-1** [comment]
on which directory you checked the PVC size?

i suggest you mount the PVC to an app and check the directory size. if the size is not reflected please let us know

**Comment by LuckySB** [comment]
```
k exec -it pod-name bash

mount | grep csi
172.18.8.15:6789,172.18.8.16:6789,172.18.8.17:6789:/volumes/csi/csi-vol-22b377c5-8c7b-11ea-b1ba-ea0c41f9366d/5f858910-7fcf-408d-a14b-4c192aaa546e on /data type ceph (rw,relatime,name=admin,secret=<hidden>,acl,mds_namespace=cephfs)

df -h
172.18.8.15:6789,172.18.8.16:6789,172.18.8.17:6789:/volumes/csi/csi-vol-22b377c5-8c7b-11ea-b1ba-ea0c41f9366d/5f858910-7fcf-408d-a14b-4c192aaa546e  8.0M  8.0M     0 100% /data

cd /data
du -h
17M     .

# try to copy file with size = 1mb

cp file3 file345
cp: error writing 'file345': Disk quota exceeded
```

mount cephfs to external server and check
```
getfattr -n ceph.quota.max_bytes csi-vol-22b377c5-8c7b-11ea-b1ba-ea0c41f9366d/5f858910-7fcf-408d-a14b-4c192aaa546e/
# file: 5f858910-7fcf-408d-a14b-4c192aaa546e/
ceph.quota.max_bytes="10485760"
```
getfattr inside pod
```
root@fileshare-767f6f8998-8jh9j:/data# getfattr -n ceph.quota.max_bytes  /data
getfattr: Removing leading '/' from absolute path names
# file: data
ceph.quota.max_bytes="10485760"
```

size in manifests changed, but aatribute with quota not increased

**Comment by Madhu-1** [comment]
@humblec PTAL

**Comment by humblec** [comment]
@LuckySB can you please let us know the ceph cluster version running in the backend ?

**Comment by humblec** [comment]
@kotreshhr can you please check why the quota didnt get adjusted here ?

**Comment by humblec** [comment]
@joscollin any idea why quota resize is not happening in this cluster?

**Comment by joscollin** [comment]
@humblec @LuckySB Hold on for resizing the quota. First of all, check if quota is available or not.
Which mounting method you use? Do you have kernel client >= 4.17? Do you have mimic+ cluster (mimic or later versions)?

**Comment by joscollin** [comment]
You will fail to handle quotas on older clusters(older than mimic), even if you may be able to set the quotas.

**Comment by Madhu-1** [comment]
> You will fail to handle quotas on older clusters(older than mimic), even if you may be able to set the quotas.

@joscollin 
this should not be a cluster issue as the subvolume is already supported (means the user is able to create the PVC), the issue can be the mounter, checking kernel version can help us. but if the kernel version is less than 4.17 the fuse will be used as the default, unless its overridden in storage-class or deployment(i don't think kernel version is helpful here)

Is anything helpful if we get `mds` logs?

**Comment by joscollin** [comment]
I repeat:
Which mounting method you use? Do you have kernel client >= 4.17? Do you have mimic+ cluster (mimic or later versions)? 

Else forget about quotas.

**Comment by LuckySB** [comment]
> @LuckySB can you please let us know the ceph cluster version running in the backend? because the E2E test is passing for resize. It looks like something on the backend cluster.

ceph nautilus 14.2.9 on centos from community repo
installed via ceph-ansible  https://github.com/ceph/ceph-ansible

**Comment by LuckySB** [comment]
> @humblec @LuckySB Hold on for resizing the quota. First of all, check if quota is available or not.
> Which mounting method you use? Do you have kernel client >= 4.17? Do you have mimic+ cluster (mimic or later versions)?
kernel version 4.20.13-1.el7.elrepo.x86_64
ceph nautilus 14.2.9

**Comment by LuckySB** [comment]
> > You will fail to handle quotas on older clusters(older than mimic), even if you may be able to set the quotas.
> 
> @joscollin
> this should not be a cluster issue as the subvolume is already supported (means the user is able to create the PVC), the issue can be the mounter, checking kernel version can help us. but if the kernel version is less than 4.17 the fuse will be used as the default, unless its overridden in storage-class or deployment(i don't think kernel version is helpful here)
> 
> Is anything helpful if we get `mds` logs?

mds log: https://pastebin.com/pTr2Vygb
mgr log: https://pastebin.com/JAAMfur0  (without log_channel(cluster) log [DBG] line)

**Comment by LuckySB** [comment]
```
cd /mnt/cephfs/volumes/csi/csi-vol-a99f065c-8ed6-11ea-b2e8-562b53eb6d09/e16fe4da-0dfd-43ef-9650-c50fd3028af7
getfattr -n ceph.quota.max_bytes .

# file: .
ceph.quota.max_bytes="10485760"
```
```
k get pvc
NAME        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
fileshare   Bound    pvc-194b0216-fb57-4a8a-8852-07409876bf8c   524Mi      RWX            csi-cephfs-sc   5m9s
```
```
k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                STORAGECLASS    REASON   AGE
pvc-194b0216-fb57-4a8a-8852-07409876bf8c   524Mi      RWX            Delete           Bound       default/fileshare    csi-cephfs-sc            5m11s
```

**Comment by kotreshhr** [comment]
@LuckySB We would need mds logs from all the nodes during the operation.

**Comment by LuckySB** [comment]
> @LuckySB We would need mds logs from all the nodes during the operation.

node-1: https://pastebin.com/Gq8QwwDH
node-2: https://pastebin.com/7EC0AKn1
ingress-1: https://pastebin.com/pTr2Vygb

**Comment by LuckySB** [comment]
```
172.17.213.55:6789,172.17.213.56:6789,172.17.213.57:6789:/volumes/csi/csi-vol-a99f065c-8ed6-11ea-b2e8-562b53eb6d09/e16fe4da-0dfd-43ef-9650-c50fd3028af7  8.0M     0  8.0M   0% /data
```

**Comment by donggyupark** [comment]
I also had the same issue.
In my case, I had deployed ceph csi v2.0 using rook v1.2.7 (kubernetes v1.18)
As a result of testing in various ceph versions, it worked normally in ceph v14.2.2 and v14.2.7, but not in ceph v14.2.8.

In ceph v14.2.8, `cephfs subvolume resize command` has appeared. ( cephfs: mgr/volumes: fs subvolume resize command [pr#31332](https://github.com/ceph/ceph/pull/31332) )

However, ceph-csi code still uses `ceph fs subvolume create` command when resizing cephfs volume.
https://github.com/ceph/ceph-csi/blob/0ca07e465776a656c52e9d51dddd690a292d5fd2/internal/cephfs/controllerserver.go#L364-L367

In ceph v14.2.8, I tried resizing cephFS volume created with ceph-csi using `ceph fs subvolume create` command and `ceph fs subvolume reisze` command via ceph-client.

As a result, the `ceph fs subvolume create` command did not change the quota, but the `ceph fs subvolume resize` command changed the quota.
```shell
# try to cephFS subvolume resize (100MiB -> 2GiB)
# ceph fs subvolume create command
$ ceph fs subvolume create myfs csi-vol-da1a12e5-85ca-11ea-8eb5-0242ac110008 2147483648 --group_name csi --mode 777
$ getfattr -n ceph.quota.max_bytes  /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f8c257fe-b0e8-4bfa-828c-86085f262136/globalmount
getfattr: Removing leading '/' from absolute path names
# file: var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f8c257fe-b0e8-4bfa-828c-86085f262136/globalmount
ceph.quota.max_bytes="104857600"

# ceph fs subvolume resize command
$ ceph fs subvolume resize myfs csi-vol-da1a12e5-85ca-11ea-8eb5-0242ac110008 2147483648 --group_name csi --no_shrink
$ getfattr -n ceph.quota.max_bytes  /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f8c257fe-b0e8-4bfa-828c-86085f262136/globalmount
getfattr: Removing leading '/' from absolute path names
# file: var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f8c257fe-b0e8-4bfa-828c-86085f262136/globalmount
ceph.quota.max_bytes="2147483648"
```

I think it seems that `ceph fs subvolume create` command doesn't work anymore for resizing as ceph version goes up

**Comment by Madhu-1** [comment]
> I also had the same issue.
> In my case, I had deployed ceph csi v2.0 using rook v1.2.7 (kubernetes v1.18)
> As a result of testing in various ceph versions, it worked normally in ceph v14.2.2 and v14.2.7, but not in ceph v14.2.8.
> 
> In ceph v14.2.8, `cephfs subvolume resize command` has appeared. ( cephfs: mgr/volumes: fs subvolume resize command [pr#31332](https://github.com/ceph/ceph/pull/31332) )
> 
> However, ceph-csi code still uses `ceph fs subvolume create` command when resizing cephfs volume.
> https://github.com/ceph/ceph-csi/blob/0ca07e465776a656c52e9d51dddd690a292d5fd2/internal/cephfs/controllerserver.go#L364-L367
> 
> In ceph v14.2.8, I tried resizing cephFS volume created with ceph-csi using `ceph fs subvolume create` command and `ceph fs subvolume reisze` command via ceph-client.
> 
> As a result, the `ceph fs subvolume create` command did not change the quota, but the `ceph fs subvolume resize` command changed the quota.
> 
> ```shell
> # try to cephFS subvolume resize (100MiB -> 2GiB)
> # ceph fs subvolume create command
> $ ceph fs subvolume create myfs csi-vol-da1a12e5-85ca-11ea-8eb5-0242ac110008 2147483648 --group_name csi --mode 777
> $ getfattr -n ceph.quota.max_bytes  /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f8c257fe-b0e8-4bfa-828c-86085f262136/globalmount
> getfattr: Removing leading '/' from absolute path names
> # file: var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f8c257fe-b0e8-4bfa-828c-86085f262136/globalmount
> ceph.quota.max_bytes="104857600"
> 
> # ceph fs subvolume resize command
> $ ceph fs subvolume resize myfs csi-vol-da1a12e5-85ca-11ea-8eb5-0242ac110008 2147483648 --group_name csi --no_shrink
> [
>     {
>         "bytes_used": 119537664
>     },
>     {
>         "bytes_quota": 2147483648
>     },
>     {
>         "bytes_pcent": "5.57"
>     }
> ]
> $ getfattr -n ceph.quota.max_bytes  /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f8c257fe-b0e8-4bfa-828c-86085f262136/globalmount
> getfattr: Removing leading '/' from absolute path names
> # file: var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f8c257fe-b0e8-4bfa-828c-86085f262136/globalmount
> ceph.quota.max_bytes="2147483648"
> ```
> 
> I think it seems that `ceph fs subvolume create` command doesn't work anymore for resizing as ceph version goes up

@joscollin @kotreshhr is this the issue? why ceph fs subvolume is not resizing the subvolume if the ceph version is greater?

**Comment by joscollin** [comment]
@Madhu-1 I would simply ignore @donggyupark comment, as this is an over-post. It doesn't matter if it is a similar issue or not. Let's continue with the original issue without deviating from it.

@donggyupark Please create a new github issue for your problem and link to #1002.

**Comment by Madhu-1** [comment]
I just verified it the ceph fs subvolume create is not actually resizing the PVC in my cluster ie `15.2.1`

**Comment by Madhu-1** [comment]
this looks to a regression on the CSI side, irrespective or ceph cluster it's connecting to, the cephcsi should be able to resize the PVC, it has to be fixed in CSI layer as to use `ceph fs subvolume resize` for particular ceph versions ie greater than 14.2.8. created https://tracker.ceph.com/issues/45398 for tracking this in ceph

**Comment by joscollin** [comment]
> it has to be fixed in CSI layer as to use `ceph fs subvolume resize` for particular ceph versions ie greater than 14.2.8

Yeah, that's pending on CSI side.

**Comment by LuckySB** [comment]
@joscollin csi call `fs subvolume create` for resize

```
2020-05-05 16:50:27.168 7fb06a20c700  0 log_channel(audit) log [DBG] : from='client.14558 -' entity='client.admin' cmd=[{"prefix": "fs subvolume create", "vol_name": "cephfs", "sub_name": "csi-vol-a99f065c-8ed6-11ea-b2e8-562b53eb6d09", "size": 549453824, "group_name": "csi", "mode": "777", "target": ["mon-mgr", ""]}]: dispatch
```

**Comment by LuckySB** [comment]
https://github.com/ceph/ceph/blob/a96f9583f4f9d2552e0d326bdac31373faaa0b3e/src/pybind/mgr/volumes/fs/volume.py#L130-L142

if volume open - do nothing with when try to create existings volume
