### ISSUE TITLE
Cannot run cephcsi on multi arch (amd64,arm64) kubernetes cluster

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1003]
If the kubernetes nodes in a cluster are having both amd64 and arm64 nodes, cephcsi cannot be utilized, In node plugin, you can specify either arm64 or amd64 image, not both,.
we have restrictions in quay.io as quay does not support multi-architecture images. you need to move to dockerhub for our official images or get the support from quay.io(am not sure it's possible)

**Comment by nixpanic** [comment]
Can Rook have a variable that it substitutes when using the name of the image?

Does Ceph support a mix of architectures in the same cluster?

**Comment by Madhu-1** [comment]
> Can Rook have a variable that it substitutes when using the name of the image?
> 
> Does Ceph support a mix of architectures in the same cluster?

not always required. cephcsi can use the external ceph cluster. this is not specific to ceph or rook I believe

**Comment by nixpanic** [comment]
> > Can Rook have a variable that it substitutes when using the name of the image?
> 
> yes currently we have an ENV to specify the image

I do not mean an environment variable, but wanted to know if Rook can adapt the envionement variable for deployments, and separate them out per architecture. Like passing
```
image: ceph/cephcsi-${ARCH}:v2.1
```
but I guess not, as Docker Hub supports multi-arch container images...

> > Does Ceph support a mix of architectures in the same cluster?
> 
> not always required. cephcsi can use the external ceph cluster. this is not specific to ceph or rook I believe

Ceph clients (provisioner, attacher) and MONs, OSDs, ... are all part of the same Ceph cluster. Can these run on a mix of architectures? It does not matter if the cluster is "external" or not, Ceph-CSI will interact with it.

**Comment by Madhu-1** [comment]
> > > Can Rook have a variable that it substitutes when using the name of the image?
> > 
> > 
> > yes currently we have an ENV to specify the image
> 
> I do not mean an environment variable, but wanted to know if Rook can adapt the envionement variable for deployments, and separate them out per architecture. Like passing
> 
> ```
> image: ceph/cephcsi-${ARCH}:v2.1
> ```
> 
i don't think its possible, as the daemonset need to be run on different arch, the rook cannot control it
> but I guess not, as Docker Hub supports multi-arch container images...
> 
> > > Does Ceph support a mix of architectures in the same cluster?
> > 
> > 
> > not always required. cephcsi can use the external ceph cluster. this is not specific to ceph or rook I believe
> 
> Ceph clients (provisioner, attacher) and MONs, OSDs, ... are all part of the same Ceph cluster. Can these run on a mix of architectures? It does not matter if the cluster is "external" or not, Ceph-CSI will interact with it.

provisioner and attacher are CSI components, they should be able to run on the different arch, let's just keep rook aside now. cephcsi should be able to consume the ceph cluster. i don't think ceph won't work in such environment
cc @dillaman @travisn

**Comment by travisn** [comment]
@Madhu-1 Ceph and Rook both have multi-arch images today, which has allowed Rook to run in the multi-arch environments. I haven't heard any issues of the multi-arch clusters about incompatibility for Ceph. We need the CSI driver to also have multi-arch images since the only alternative in those environments is to use the flex driver.

**Comment by nixpanic** [comment]
Are the side cars that we need available as multi-arch image yet? That was an issue earlier, and some users built their own side-cars for non x86_64 architectures.

**Comment by Madhu-1** [comment]
> Are the side cars that we need available as multi-arch image yet? That was an issue earlier, and some users built their own side-cars for non x86_64 architectures.

Yes kubernetes CSI team is working on providing the multi arch images for sidecar containers

**Comment by Madhu-1** [comment]
> @Madhu-1 Ceph and Rook both have multi-arch images today, which has allowed Rook to run in the multi-arch environments. I haven't heard any issues of the multi-arch clusters about incompatibility for Ceph. We need the CSI driver to also have multi-arch images since the only alternative in those environments is to use the flex driver.

Yes, that was my assumption as well, we need to move to dockerhub as its supports multi arch now as quay.io currently not supporting it for free account AFAIK.

**Comment by nixpanic** [comment]
This depends on the availability of multi-arch sidecar images from the Kubernetes CSI projects

**Comment by jamesorlakin** [comment]
I came across this comment recently: https://github.com/moby/moby/issues/39220#issuecomment-492773638. It seems Quay may experimentally support multi-architecture manifests if you request it. I can't find anything official on the matter though, but Prometheus' images are [indeed multiarch](https://quay.io/repository/prometheus/prometheus?tab=tags).

**Comment by dkrizic** [comment]
Here is a very nice example of a quay image with multi arch support:

https://quay.io/repository/jetstack/cert-manager-controller?tab=tags

I have a hybrid cluster as well (3 x amd64, 5 x arm64) and can use Ceph-CSI only if there is support for multi arch image. 

For those who don't know: If I pull a docker image which is multi arch, the local docker will pull the appropriate image for the local architecture. In case of a daemonset the amd64 nodes receive amd64 image, same for the arm64 machines.

**Comment by travisn** [comment]
@humblec Since quay 3.0 (about a year ago) the [multi-arch images](https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/red_hat_quay_release_notes/index#multi_architecture_container_image_support) are supported. This is really a blocker for multi-arch clusters and [workarounds](https://github.com/rook/rook/issues/4051#issuecomment-643782302) are also popping up. Are you working on this, or who can take it on? thanks

**Comment by humblec** [comment]
> @humblec Since quay 3.0 (about a year ago) the [multi-arch images](https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/red_hat_quay_release_notes/index#multi_architecture_container_image_support) are supported. This is really a blocker for multi-arch clusters and [workarounds](https://github.com/rook/rook/issues/4051#issuecomment-643782302) are also popping up. Are you working on this, or who can take it on? thanks!

@travisn from previous responses, I was in an impression that quay.io multiarch support was coming in recently and experimental, so the delay. I am checking on this and will also take help from @leseb if needed.

**Comment by Madhu-1** [comment]
> > @humblec Since quay 3.0 (about a year ago) the [multi-arch images](https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/red_hat_quay_release_notes/index#multi_architecture_container_image_support) are supported. This is really a blocker for multi-arch clusters and [workarounds](https://github.com/rook/rook/issues/4051#issuecomment-643782302) are also popping up. Are you working on this, or who can take it on? thanks!
> 
> @travisn from previous responses, I was in an impression that quay.io multiarch support was coming in recently and experimental, so the delay. I am checking on this and will also take help from @leseb if needed.

even if the support is not available in quay.io we don't need to wait, we can move to dockerhub as it already supports multi-arch.

**Comment by humblec** [comment]
> > > @humblec Since quay 3.0 (about a year ago) the [multi-arch images](https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/red_hat_quay_release_notes/index#multi_architecture_container_image_support) are supported. This is really a blocker for multi-arch clusters and [workarounds](https://github.com/rook/rook/issues/4051#issuecomment-643782302) are also popping up. Are you working on this, or who can take it on? thanks!
> > 
> > 
> > @travisn from previous responses, I was in an impression that quay.io multiarch support was coming in recently and experimental, so the delay. I am checking on this and will also take help from @leseb if needed.
> 
> even if the support is not available in quay.io we don't need to wait, we can move to dockerhub as it already supports multi-arch.

Yeah, more or less we have to see the quay.io support is on `Paid Vs Free` account.

**Comment by Madhu-1** [comment]
when we tested last time the quay.io was not supporting multi arch more info at https://github.com/ceph/ceph-csi/pull/707#discussion_r358246360 https://github.com/ceph/ceph-csi/pull/707#issuecomment-571400449 https://github.com/ceph/ceph-csi/pull/707#issuecomment-572088862. @humblec may be you can test it again with the steps mentioned in https://github.com/ceph/ceph-csi/pull/707#discussion_r358278583

**Comment by humblec** [comment]
Yeah. Indeed we had tried in recent past as in https://github.com/ceph/ceph-csi/pull/707. But I am confused with @travisn's comment saying it's available for more than a year.

**Comment by travisn** [comment]
@humblec It was in the quay.io release notes from 3.0, although I was not clear about whether it requires a paid account either.
