### ISSUE TITLE
In case mounting fails, log a recommendation to check the kernel logs

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1006]
In case mounting of an RBD-image or CephFS-volume fails, the error reported by the `mount` command (for kernel clients) is probably not sufficient to identify the issue. Users that hit problems while mounting should also look in the kernel logs (`dmesg` command).

When mounting fails, the node-plugin should give a suggestion to check the kernel logs, so that users can report problems better.

**Comment by Madhu-1** [comment]
we need to update the github issue template for the user to include the logs. let me add more details to issue template

**Comment by nixpanic** [comment]
Yes, that would be a good addition as well.

**Comment by Madhu-1** [comment]
@agarwal-mudit would you like to take this up?

**Comment by Madhu-1** [comment]
> we need to update the github issue template for the user to include the logs. let me add more details to issue template

i will update the issue template

**Comment by agarwal-mudit** [comment]
> @agarwal-mudit would you like to take this up?

Sure, assign please.

**Comment by Madhu-1** [comment]
need code changes in https://github.com/ceph/ceph-csi/blob/master/internal/rbd/nodeserver.go and https://github.com/ceph/ceph-csi/blob/master/internal/cephfs/volumemounter.go
