### ISSUE TITLE
Add support for rbd volume resizing

### ISSUE THREAD

**Issue by JrCs** [ceph/ceph-csi#101]
Can you add support for rbd volume resizing ?
See https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/

**Comment by rootfs** [comment]
that has to wait till kubernetes csi volume plugin supports expandable volume, something like [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/rbd/rbd.go#L62)

**Comment by abrden** [comment]
CSI seems to be supporting volume expansion now:
https://github.com/container-storage-interface/spec/blob/master/spec.md#controllerexpandvolume
https://github.com/container-storage-interface/spec/blob/master/spec.md#nodeexpandvolume
Is anything else needed on the k8s side in order to implement this feature?

**Comment by gman0** [comment]
@abrden yes, something (external-provisioner) needs to implement the controller for expansion.

**Comment by rootfs** [comment]
now [external-resize ](https://github.com/kubernetes-csi/external-resizer/) supports csi resize, we should pick it here.

cc @Madhu-1 @gman0 @humblec @j-griffith

**Comment by Madhu-1** [comment]
@rootfs does kube latest version supports volume expansion? , if yes i think we can take it, i was waiting for kube 1.14 release (i think it supports volume expansion) correct me if am wrong.

**Comment by rootfs** [comment]
yes, k8s csi volume volume expansion is scheduled for k8s 1.14
https://github.com/kubernetes/kubernetes/pull/74863

**Comment by humblec** [comment]
@rootfs sure, we will take care of it.. @Madhu-1 lets sync up ..

**Comment by sandromodarelli** [comment]
any news about this issue? plans of release?

**Comment by Madhu-1** [comment]
as humble is working on this one. assigning to humble
https://github.com/ceph/ceph-csi/pull/331

**Comment by wavezhang** [comment]
Any progress on this?

**Comment by davi5e** [comment]
Besides any updates on the progress status, which would be the Kubernetes version this is being developed for? 1.14? 1.15?

**Comment by humblec** [comment]
> Besides any updates on the progress status, which would be the Kubernetes version this is being developed for? 1.14? 1.15?

@wavezhang @davi5e we have a prototype on resize  here #331, but has not completed as there were various changes happening on rbd code with other bug fixes and enhancements. This feature was planned for #393 , however deferred to `v2.0.0` which is planned at 3rd week of September.

**Comment by l0nax** [comment]
@humblec Any updates?

**Comment by Madhu-1** [comment]
closing this one as this is implemented in #331
