### ISSUE TITLE
GitHub should not report all tests as passed when parsing .travis.yaml fails

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1011]
# Describe the bug #

When there is an error in the `.travis.yaml` file, Travis CI does not run. The checks in the PR are green, as everything (mergify only) passed. There should be a check in the mergify configuration that highlights the not-passing of Travis CI.

**Comment by Madhu-1** [comment]
@agarwal-mudit would you like to take this up?

**Comment by agarwal-mudit** [comment]
> @agarwal-mudit would you like to take this up?

Sure, please assign.

**Comment by nixpanic** [comment]
This might be a problem on the Travis CI side. In case `.travis.yaml` can not be parsed (invalid formatting or typo), the state of the PR  should not marked 'passed'.

**Comment by Madhu-1** [comment]
the mergify won't merge the PR if there is an issue with travis yaml file as the build won't be successes you can check the status here https://github.com/ceph/ceph-csi/pull/1028/checks?check_run_id=654968919 for PR https://github.com/ceph/ceph-csi/pull/1028. it is behaving as intended i believe. i don't think travis CI will show as failed as the file is not proper.

**Comment by Madhu-1** [comment]
if required we can file a bug in travis CI to show failure if the yaml is not proper or configuration is not proper

**Comment by agarwal-mudit** [comment]
I have corrected the title of the commit and now it is showing that all checks have passed but if you go to mergify checks (https://github.com/ceph/ceph-csi/pull/1028/checks?check_run_id=655286102)  you can see that the checkbox against **status-success=continuous-integration/travis-ci/pr** is not marked check which means that **ci never ran** so I don't think mergify will go ahead with auto merging such PR.

**Comment by nixpanic** [comment]
Yes, there is an additional check in mergify to prevent merging. However the PR in github will have a green :heavy_check_mark: even if the `.travis.yaml` is incorrect. I expect that this is something Travis CI should be able to report back to the PR. It may be a configuration option somewhere in the Travis UI, or maybe a setting in the GitHub repository itself.
