### ISSUE TITLE
cephcsi v2.1.0 image build failed: error: rados/librados.h: No such file or directory

### ISSUE THREAD

**Issue by olivejing** [ceph/ceph-csi#1022]
# Describe the bug #
vendor/github.com/ceph/go-ceph/rados/conn.go:5:29: fatal error: rados/librados.h: No such file or directory
 // #include <rados/librados.h>
                             ^
compilation terminated.
make: *** [cephcsi] Error 2

# Environment details #
go version
go version go1.13.9 linux/amd64

# Steps to reproduce #

run make command to build cephcsi:
`
if [ ! -d ./vendor ]; then (go mod tidy && go mod vendor); fi
GOOS=linux GOARCH=amd64 go build -mod vendor -a -ldflags ' -X github.com/ceph/ceph-csi/pkg/util.GitCommit= -X github.com/ceph/ceph-csi/pkg/util.DriverVersion=v2.1.0' -o _output/cephcsi ./cmd/
github.com/ceph/go-ceph/rados
vendor/github.com/ceph/go-ceph/rados/conn.go:5:29: fatal error: rados/librados.h: No such file or directory
 // #include <rados/librados.h>
                             ^
compilation terminated.
make: *** [cephcsi] Error 2
`

tried to install libcephfs-devel librbd-devel librados-devel before run make, but still failed:
`# yum install libcephfs-devel librbd-devel librados-devel
Loaded plugins: fastestmirror
Determining fastest mirrors
Ceph                                                                     | 1.5 kB  00:00:00
Ceph-noarch                                                              | 1.5 kB  00:00:00
ceph-aarch64                                                             | 1.5 kB  00:00:00
ceph-source                                                              | 1.5 kB  00:00:00
ceph-x86-64                                                              | 1.5 kB  00:00:00
(1/5): ceph-source/primary                                               | 3.1 kB  00:00:00
(2/5): Ceph-noarch/primary                                               | 4.4 kB  00:00:00
(3/5): Ceph/x86_64/primary                                               |  12 kB  00:00:00
(4/5): ceph-aarch64/primary                                              |  12 kB  00:00:00
(5/5): ceph-x86-64/primary                                               |  12 kB  00:00:00
Ceph                                                                                      39/39
Ceph-noarch                                                                               25/25
ceph-aarch64                                                                              39/39
ceph-source                                                                               18/18
ceph-x86-64                                                                               39/39
Resolving Dependencies
--> Running transaction check
---> Package libcephfs-devel.x86_64 2:15.2.1-0.el7 will be installed
--> Processing Dependency: libcephfs2 = 2:15.2.1-0.el7 for package: 2:libcephfs-devel-15.2.1-0.el7.x86_64
--> Processing Dependency: libcephfs.so.2()(64bit) for package: 2:libcephfs-devel-15.2.1-0.el7.x86_64
---> Package librados-devel.x86_64 2:15.2.1-0.el7 will be installed
--> Processing Dependency: librados2 = 2:15.2.1-0.el7 for package: 2:librados-devel-15.2.1-0.el7.x86_64
--> Processing Dependency: librados.so.2()(64bit) for package: 2:librados-devel-15.2.1-0.el7.x86_64
--> Processing Dependency: librados_tp.so.2()(64bit) for package: 2:librados-devel-15.2.1-0.el7.x86_64
---> Package librbd-devel.x86_64 2:15.2.1-0.el7 will be installed
--> Processing Dependency: librbd1 = 2:15.2.1-0.el7 for package: 2:librbd-devel-15.2.1-0.el7.x86_64
--> Processing Dependency: libradospp-devel = 2:15.2.1-0.el7 for package: 2:librbd-devel-15.2.1-0.el7.x86_64
--> Processing Dependency: librbd.so.1()(64bit) for package: 2:librbd-devel-15.2.1-0.el7.x86_64
--> Processing Dependency: librbd_tp.so.1()(64bit) for package: 2:librbd-devel-15.2.1-0.el7.x86_64
--> Running transaction check
---> Package libcephfs2.x86_64 2:15.2.1-0.el7 will be installed
--> Processing Dependency: librdmacm.so.1()(64bit) for package: 2:libcephfs2-15.2.1-0.el7.x86_64
--> Processing Dependency: libibverbs.so.1()(64bit) for package: 2:libcephfs2-15.2.1-0.el7.x86_64
---> Package librados2.x86_64 2:15.2.1-0.el7 will be installed
--> Processing Dependency: librdmacm.so.1(RDMACM_1.0)(64bit) for package: 2:librados2-15.2.1-0.el7.x86_64
--> Processing Dependency: libibverbs.so.1(IBVERBS_1.0)(64bit) for package: 2:librados2-15.2.1-0.el7.x86_64
--> Processing Dependency: libibverbs.so.1(IBVERBS_1.1)(64bit) for package: 2:librados2-15.2.1-0.el7.x86_64
--> Processing Dependency: librdmacm.so.1()(64bit) for package: 2:librados2-15.2.1-0.el7.x86_64
--> Processing Dependency: libibverbs.so.1()(64bit) for package: 2:librados2-15.2.1-0.el7.x86_64
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librados2-15.2.1-0.el7.x86_64
---> Package libradospp-devel.x86_64 2:15.2.1-0.el7 will be installed
---> Package librbd1.x86_64 2:15.2.1-0.el7 will be installed
--> Processing Dependency: librdmacm.so.1()(64bit) for package: 2:librbd1-15.2.1-0.el7.x86_64
--> Processing Dependency: libibverbs.so.1()(64bit) for package: 2:librbd1-15.2.1-0.el7.x86_64
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librbd1-15.2.1-0.el7.x86_64
--> Finished Dependency Resolution
Error: Package: 2:librbd1-15.2.1-0.el7.x86_64 (Ceph)
           Requires: liblttng-ust.so.0()(64bit)
Error: Package: 2:librados2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: librdmacm.so.1(RDMACM_1.0)(64bit)
Error: Package: 2:librbd1-15.2.1-0.el7.x86_64 (Ceph)
           Requires: libibverbs.so.1()(64bit)
Error: Package: 2:librbd1-15.2.1-0.el7.x86_64 (Ceph)
           Requires: librdmacm.so.1()(64bit)
Error: Package: 2:librados2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: librdmacm.so.1()(64bit)
Error: Package: 2:libcephfs2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: libibverbs.so.1()(64bit)
Error: Package: 2:libcephfs2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: librdmacm.so.1()(64bit)
Error: Package: 2:librados2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: libibverbs.so.1(IBVERBS_1.0)(64bit)
Error: Package: 2:librados2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: liblttng-ust.so.0()(64bit)
Error: Package: 2:librados2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: libibverbs.so.1(IBVERBS_1.1)(64bit)
Error: Package: 2:librados2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: libibverbs.so.1()(64bit)
`

# Expected behavior #

build cephcsi v2.1.0 successfully

please help to resolve this issue, thanks a lot.

**Comment by Madhu-1** [comment]
@olivejing on which environment you are building cephcsi? you can make use of containerized build `make containerized-build`  to avoid this issue.

**Comment by olivejing** [comment]
I build it on one host:
# go version
go version go1.13.9 linux/amd64
# uname -a
Linux olive-deploy 3.10.0-957.21.3.el7.x86_64 #1 SMP Fri Jun 14 02:54:29 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nixpanic** [comment]
Have a look at the [Workspace and repository setup](https://github.com/ceph/ceph-csi/blob/master/docs/development-guide.md#workspace-and-repository-setup). It mentions to install the development packages for Ceph (librbd and cephfs).

When you build with the provided `make containerized-build` command, all dependencies will be installed inside a container and you do not need to install the dependencies on your development environment.

**Comment by olivejing** [comment]
Thanks for your quickly responce, i tried to to install libcephfs-devel librados-devel librbd-devel, but failed:
`
yum install libcephfs-devel librados-devel librbd-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package libcephfs-devel.x86_64 2:15.2.1-0.el7 will be installed
--> Processing Dependency: libcephfs2 = 2:15.2.1-0.el7 for package: 2:libcephfs-devel-15.2.1-0.el7.x86_64
--> Processing Dependency: libcephfs.so.2()(64bit) for package: 2:libcephfs-devel-15.2.1-0.el7.x86_64
---> Package librados-devel.x86_64 2:15.2.1-0.el7 will be installed
--> Processing Dependency: librados2 = 2:15.2.1-0.el7 for package: 2:librados-devel-15.2.1-0.el7.x86_64
--> Processing Dependency: librados.so.2()(64bit) for package: 2:librados-devel-15.2.1-0.el7.x86_64
--> Processing Dependency: librados_tp.so.2()(64bit) for package: 2:librados-devel-15.2.1-0.el7.x86_64
---> Package librbd-devel.x86_64 2:15.2.1-0.el7 will be installed
--> Processing Dependency: librbd1 = 2:15.2.1-0.el7 for package: 2:librbd-devel-15.2.1-0.el7.x86_64
--> Processing Dependency: libradospp-devel = 2:15.2.1-0.el7 for package: 2:librbd-devel-15.2.1-0.el7.x86_64
--> Processing Dependency: librbd.so.1()(64bit) for package: 2:librbd-devel-15.2.1-0.el7.x86_64
--> Processing Dependency: librbd_tp.so.1()(64bit) for package: 2:librbd-devel-15.2.1-0.el7.x86_64
--> Running transaction check
---> Package libcephfs2.x86_64 2:15.2.1-0.el7 will be installed
--> Processing Dependency: librdmacm.so.1()(64bit) for package: 2:libcephfs2-15.2.1-0.el7.x86_64
--> Processing Dependency: libibverbs.so.1()(64bit) for package: 2:libcephfs2-15.2.1-0.el7.x86_64
---> Package librados2.x86_64 2:15.2.1-0.el7 will be installed
--> Processing Dependency: librdmacm.so.1(RDMACM_1.0)(64bit) for package: 2:librados2-15.2.1-0.el7.x86_64
--> Processing Dependency: libibverbs.so.1(IBVERBS_1.0)(64bit) for package: 2:librados2-15.2.1-0.el7.x86_64
--> Processing Dependency: libibverbs.so.1(IBVERBS_1.1)(64bit) for package: 2:librados2-15.2.1-0.el7.x86_64
--> Processing Dependency: librdmacm.so.1()(64bit) for package: 2:librados2-15.2.1-0.el7.x86_64
--> Processing Dependency: libibverbs.so.1()(64bit) for package: 2:librados2-15.2.1-0.el7.x86_64
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librados2-15.2.1-0.el7.x86_64
---> Package libradospp-devel.x86_64 2:15.2.1-0.el7 will be installed
---> Package librbd1.x86_64 2:15.2.1-0.el7 will be installed
--> Processing Dependency: librdmacm.so.1()(64bit) for package: 2:librbd1-15.2.1-0.el7.x86_64
--> Processing Dependency: libibverbs.so.1()(64bit) for package: 2:librbd1-15.2.1-0.el7.x86_64
--> Processing Dependency: liblttng-ust.so.0()(64bit) for package: 2:librbd1-15.2.1-0.el7.x86_64
--> Finished Dependency Resolution
Error: Package: 2:librbd1-15.2.1-0.el7.x86_64 (Ceph)
           Requires: liblttng-ust.so.0()(64bit)
Error: Package: 2:librados2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: librdmacm.so.1(RDMACM_1.0)(64bit)
Error: Package: 2:librbd1-15.2.1-0.el7.x86_64 (Ceph)
           Requires: libibverbs.so.1()(64bit)
Error: Package: 2:librbd1-15.2.1-0.el7.x86_64 (Ceph)
           Requires: librdmacm.so.1()(64bit)
Error: Package: 2:librados2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: librdmacm.so.1()(64bit)
Error: Package: 2:libcephfs2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: libibverbs.so.1()(64bit)
Error: Package: 2:libcephfs2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: librdmacm.so.1()(64bit)
Error: Package: 2:librados2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: libibverbs.so.1(IBVERBS_1.0)(64bit)
Error: Package: 2:librados2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: liblttng-ust.so.0()(64bit)
Error: Package: 2:librados2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: libibverbs.so.1(IBVERBS_1.1)(64bit)
Error: Package: 2:librados2-15.2.1-0.el7.x86_64 (Ceph)
           Requires: libibverbs.so.1()(64bit)

`
the repo:
`cat ceph.repo
[Ceph]
name=Ceph packages for $basearch
baseurl=http://download.ceph.com/rpm-nautilus/el7/$basearch
enabled=1
gpgcheck=0
type=rpm-md
gpgkey=https://download.ceph.com/keys/release.asc

[Ceph-noarch]
name=Ceph noarch packages
baseurl=http://download.ceph.com/rpm-nautilus/el7/noarch
enabled=1
gpgcheck=0
type=rpm-md
gpgkey=https://download.ceph.com/keys/release.asc

[ceph-source]
name=Ceph source packages
baseurl=http://download.ceph.com/rpm-nautilus/el7/SRPMS
enabled=1
gpgcheck=0
type=rpm-md

`

**Comment by nixpanic** [comment]
Installing Ceph packages is not really part of this project, you are better of asking on a Ceph users/developers forum. My guess is that you are missing some other repository, and which one(s) may well be explained in some Ceph documentation.

**Comment by olivejing** [comment]
Thanks, i will try to change my config.

**Comment by Madhu-1** [comment]
closing this as nothing need to be fixed on cephcsi side for this one
