### ISSUE TITLE
Remove unmaintained kubernetes versions from testing

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1023]
Kubernetes maintains the latest minor version, and the two before it. That means with the release of Kubernetes 1.18, version 1.17 and 1.16 are still maintained. Deployments should not use unmaintained versions, so there is no need to test on older versions either.

See [supported versions in the k8s documentation](https://kubernetes.io/docs/setup/release/version-skew-policy/#supported-versions).

**Comment by humblec** [comment]
@nixpanic are you working on the PR ?
