### ISSUE TITLE
Travis CI should run e2e tests with Kubernetes 1.18.2

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1027]
Kubernetes 1.18.2 has been released as last patch update for version 1.18. The e2e tests should run with a 1.18.x version too.

Initial tries with [minikube and installing Kubernetes 1.18.2 failed](https://travis-ci.org/github/ceph/ceph-csi/jobs/684226855#L581). Needs some investigation and more testing, maybe an update of minikube as is in progress in PR #868.

**Comment by Madhu-1** [comment]
@nixpanic we need to upgrade minikube first for that one, am tracking this one, will update kube version once this is fixed in minikube

**Comment by Madhu-1** [comment]
closing this as a duplicate of https://github.com/ceph/ceph-csi/issues/963. @nixpanic feel free to reopen if both are different
