### ISSUE TITLE
Document RBAC/PSP required namespace changes

### ISSUE THREAD

**Issue by Tatsu-Kishi** [ceph/ceph-csi#1030]
# Describe the bug #

When deploying manually from deploy/rbd/kubernetes manifests into a dedicated namespace (ie. not default), the rbac and psp files require the namespaces for references to be updated.
This is nowhere documented outside of those files.

https://github.com/ceph/ceph-csi/blob/master/docs/deploy-rbd.md

# Environment details #
- Image/version of Ceph CSI driver: 2.1.1

# Steps to reproduce #

1. Install ceph-csi from deploy yamls in ie. "ceph-csi" namespace: kubectl apply -n ceph-csi -f deploy/rbd/kubernetes/
2. Some containers don't start due to missing API privileges

# Expected behavior #

Documentation to mention required changes for a sensible deployment

# Additional context #

It might be worth considering hardcoding "ceph-csi" instead as it's probably what a lot of people use or using an invalid value to make users aware of required changes.

**Comment by Madhu-1** [comment]
@Tatsu-Kishi you need to change the namespace if you want to run in a different namespace, we have added a comment for replacing the namespace where you want to replace it

example https://github.com/ceph/ceph-csi/blob/master/deploy/rbd/kubernetes/csi-nodeplugin-psp.yaml#L51-L52 
best option is to run some shell script to replace `namespace: default` with required values and then deploy the cephcsi in a different namespace.
