### ISSUE TITLE
Add support for ReadWriteMany (RWX) for rbd

### ISSUE THREAD

**Issue by discostur** [ceph/ceph-csi#1038]
# Describe the feature you'd like to have #

Regarding the ceph-csi / rbd-kubernetes documentation (https://docs.ceph.com/docs/master/rbd/rbd-kubernetes/) you are able to mount a rbd device in "block" mode RWX. If you choose the default filesystem mode, you are only able to mount it in "RWO" mode. 

If it is possible it would be helpful if you can mount an rbd image in filesystem mode RWX.

# What is the value to the end user? (why is it a priority?) #

You don't need ceph-fs to support RWX - you can also do it with rbd.

PS: not shure if it is even possible by design ...

**Comment by dillaman** [comment]
ext4 and XFS are not cluster-aware file systems and therefore cannot operate in RWX mode (w/o massive data corruption). If you want to use RBD in RWX mode, you need to use block and install your own cluster-aware file system on top (i.e. GFS2)

**Comment by discostur** [comment]
@dillaman ok thanks for the explanation
