### ISSUE TITLE
csi-rbdplugin causes kubelet to die

### ISSUE THREAD

**Issue by isehgu** [ceph/ceph-csi#1040]
# Describe the bug #

When csi-rdbplugin pod is running on the node, kubelet keeps dying.

# Environment details #

- Image/version of Ceph CSI driver : quay.io/cephcsi/cephcsi:v1.2.2
- Helm chart version : rook-ceph 1.2.6
- Kernel version : 4.19.106 (Coreos 2345.3.0)
- Kubernetes cluster version : 1.17.4
- Ceph cluster version : 14.2.8

# Steps to reproduce #

1. Make sure csi-rbdplugin pod is running on the node
1. `systemctl restart kubelet`

# Actual results #

When csi-rdbplugin container is running on the node, kubelet will die.
The key error in the kubelet log is 
`Failed to start ContainerManager failed to initialize top level QOS containers: root container [kubepods] doesn't exist`.

Base on that error, I found an old issue with kubernetes that was patched 1 or 2 years ago. But in order for kubelet to stay alive I had to apply the same workaround for that old issue in kubelet.

`--cgroups-per-qos=false`
`--enforce-node-allocatable="" `

# Expected behavior #

Kubelet should stay running without applying the workaround.

# Logs #

[kubelet.log](https://github.com/ceph/ceph-csi/files/4612379/kubelet.log)

# Additional context #

We use rook-ceph operator to manage ceph. I opened an issue on rook https://github.com/rook/rook/issues/5454, and was directed here.

**Comment by Madhu-1** [comment]
>21726 docker_sandbox.go:394] failed to read pod IP from plugin/docker: networkPlugin cni failed on the status hook for pod "runner-textdjzt-project-2739-concurrent-0dqfmt_gitlab": CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "12698ef2dd42c84a8f8a38847ea2717d47769ad63f20321c7c26c2050a5c835e"
Apr 22 18:55:02 worker22 rkt[21726]: E0422 22:55:02.962109   21726 kubelet.go:1844] skipping pod synchronization - container runtime status check may not have completed yet
Apr 22 18:55:03 worker22 rkt[21726]: I0422 22:55:03.102293   21726 cpu_manager.go:173] [cpumanager] starting with none policy
Apr 22 18:55:03 worker22 rkt[21726]: I0422 22:55:03.102352   21726 cpu_manager.go:174] [cpumanager] reconciling every 10s
Apr 22 18:55:03 worker22 rkt[21726]: I0422 22:55:03.102374   21726 policy_none.go:43] [cpumanager] none policy: Start
Apr 22 18:55:03 worker22 rkt[21726]: F0422 22:55:03.118465   21726 kubelet.go:1380] Failed to start ContainerManager failed to initialize top level QOS containers: root container [kubepods] doesn't exist

looking at the logs I don't think this is something to do with cephcsi. this is something related to core kubernetes

To double confirm can you deploy rook without cephcsi and restart kubelet and check the issue persists?

**Comment by isehgu** [comment]
So here's what I did.
Starting from a clean node with only pods from kube-system are running --

- Put back each ds (except rook-ceph) and then restart kubelet after each. (without the workaround)
  - promtail
  - node-problem-detector
  - monitoring-prometheus-node-exporter
  - sysdig
  - metallb-speaker
- When all other ds are back on the node.
  - Reboot
- Restart kubelet again to verify it can still come up
- Put back rook-ceph one at a time
  - rook-discover
    - restart kubelet -- no issue
  - csi-rbdplugin — This is where kubelet started dying

**Comment by isehgu** [comment]
Any suggestions?

**Comment by Madhu-1** [comment]
@agarwal-mudit can you try to reproduce and see what happens?

**Comment by agarwal-mudit** [comment]
Sure, let me check.

**Comment by agarwal-mudit** [comment]
Not happening on my local minikube setup where only csi plugins are running, have to check on multi node cluster also.

muagarwa@dhcp53-217 rbd]$ kubectl get pods
NAME                                         READY   STATUS    RESTARTS   AGE
csi-rbdplugin-fqq84                          3/3     Running   0          26m
csi-rbdplugin-provisioner-7b4b98b96f-kjbdw   6/6     Running   0          26m
csi-rbdplugin-provisioner-7b4b98b96f-l2lc9   6/6     Running   0          26m
csi-rbdplugin-provisioner-7b4b98b96f-sgb98   6/6     Running   0          26m
[muagarwa@dhcp53-217 rbd]$ 


$ systemctl restart kubelet
$ systemctl status kubelet -l
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; disabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Tue 2020-05-26 11:07:16 UTC; **1s ago**
     Docs: http://kubernetes.io/docs/
 Main PID: 15663 (kubelet)
    Tasks: 10 (limit: 3147)
   Memory: 13.7M
   CGroup: /system.slice/kubelet.service
           └─15663 /var/lib/minikube/binaries/v1.17.0/kubelet --authorization-mode=Webhook --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --cgroup-driver=systemd --client-ca-file=/var/lib/minikube/certs/ca.crt --cluster-domain=cluster.local --config=/var/lib/kubelet/config.yaml --container-runtime=docker --fail-swap-on=false --feature-gates=BlockVolume=true,CSIBlockVolume=true,VolumeSnapshotDataSource=true,ExpandCSIVolumes=true --hostname-override=minikube --kubeconfig=/etc/kubernetes/kubelet.conf --node-ip=192.168.39.65 --pod-manifest-path=/etc/kubernetes/manifests
$ 

May 26 11:07:16 minikube systemd[1]: Stopping kubelet: The Kubernetes Node Agent...
May 26 11:07:16 minikube systemd[1]: kubelet.service: Succeeded.
May 26 11:07:16 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
May 26 11:07:16 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.

**Comment by isehgu** [comment]
I just tried it on a different kernel -- 4.19.68-coreos
Same thing, kubelet kept dying. Kubelet log is attached.
[4.19.68-coreos.log](https://github.com/ceph/ceph-csi/files/4683204/4.19.68-coreos.log)

**Comment by agarwal-mudit** [comment]
Hi @isehgu ,
I am still not able to repro it on a multinode minikube setup, but as @Madhu-1 pointed out, to me also this looks like a broader issue. 
Can you please check this [issue](https://github.com/kubernetes/kubernetes/issues/91023), looks very similar but with a different csi driver? 
Meanwhile I will try to repro it on a real setup.

**Comment by isehgu** [comment]
Hi @agarwal-mudit 
What os, and kernel version did you try it on?

**Comment by agarwal-mudit** [comment]
$ cat /etc/os-release 
NAME=Buildroot
VERSION=2019.02.10
ID=buildroot
VERSION_ID=2019.02.10
PRETTY_NAME="Buildroot 2019.02.10"

$ uname -a
Linux minikube-m02 4.19.107 #1 SMP Mon May 11 14:51:04 PDT 2020 x86_64 GNU/Linux
$ 

Host is running Fedora 32

**Comment by isehgu** [comment]
@agarwal-mudit you are correct. It is due to leaked mount info from containers for some reason. Once I `umount` the extra mounts, kubelet was able to come up with no issue. I will follow that thread. Although it's unclear to me why it's only the csi plugins having this leaking mount info issue. Any theories?
