### ISSUE TITLE
Check for available Ceph development headers

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1042]
# Describe the feature you'd like to have #

The `scripts/check-env.sh` script should verify that the Ceph development headers are available and fail with a useful error when they are missing.

# What is the value to the end user? (why is it a priority?) #

New developers that run `make` will get useful error messages, and a hint to install additional tools, libraries or make other changes to their environment.

# How will we know we have a good solution? (acceptance criteria) #

When the development headers are not available, an error message is printed.

# Additional context #

Maybe also add a suggestion in case of failure, to run `make containerized-build` instead.

See-also: #1005

**Comment by Madhu-1** [comment]
@Yuggupta27 would you like to take this one?

**Comment by Yuggupta27** [comment]
Sure. Please assign.
