### ISSUE TITLE
Remove unwanted branches in ceph-csi  repo

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1050]
currently, we have below branches in the repo

```text
  ci/centos
  csi-v0.3
  csi-v1.0
  grpc-vendor
  humblec-patch-1
  originkube-v1.18.0
  master
  release-4.2
  release-v1.1.0
  release-v1.2.0
  release-v1.2.1
  release-v2.0
  release-v2.1
  revert-1044-fs-resize
  stale
  v0.1.0
```
we need to remove the unwanted branches from the ceph-csi repo

**Comment by nixpanic** [comment]
These should be kept:

- ci/centos
- master
- release-v1.1.0
- release-v1.2.0
- release-v1.2.1
- release-v2.0
- release-v2.1

Not sure about the `csi-*` or others.

You can delete the branches by pushing like this (may need `--force`?):
```
$ git push git@github.com:ceph/ceph-csi :revert-1044-fs-resize
```

**Comment by humblec** [comment]
@Madhu-1 can you revisit?
the branches I see are these:
`csi-*` are for legacy reasons.

**Comment by Madhu-1** [comment]
now unwanted branches are deleted.
but do we need to keep release-* in upstream to track downstream releases? can that be moved to openshift org?

**Comment by Madhu-1** [comment]
just to add only release-v4.2 is for downstream, not other release-v1.2 or release-v2.1, etc

**Comment by humblec** [comment]
yeah only one branch is there for downstream. So, are you saying we will delete other 2 upstream `release-` branches?

**Comment by Madhu-1** [comment]
not upstream branch, the downstream branch (release-4.2) from ceph/ceph-csi repo. and use openshift/cephcsi for downstream builds

**Comment by nixpanic** [comment]
>  `release-*` are for tracking `downstream` releases.

There should not be any downstream branches in an upstream project?! Use a downstream fork of the git repository for that.

**Comment by Madhu-1** [comment]
@humblec anything pending here?

**Comment by Madhu-1** [comment]
@humblec i see cephfs-clone and more named branch in ceph/ceph-csi repo. can you please remove it?

**Comment by humblec** [comment]
> @humblec i see cephfs-clone and more named branch in ceph/ceph-csi repo. can you please remove it?

sure @Madhu-1

**Comment by humblec** [comment]
> > @humblec i see cephfs-clone and more named branch in ceph/ceph-csi repo. can you please remove it?
> 
> sure @Madhu-1

cleaned up those @Madhu-1 :+1:

**Comment by humblec** [comment]
This can be closed now.

**Comment by Madhu-1** [comment]
Reopening as release-4.2 downstream branch is not removed yet

**Comment by humblec** [comment]
> Reopening as release-4.2 downstream branch is not removed yet

that was actually referred to downstream release once. ideally we are out of it, we could delete. But I kept it in case if we want it. Ideally we shouldnt have been referred anytign about downstream here . But, let me recheck once again.

**Comment by nixpanic** [comment]
@humblec can the release-4.2 branch be deleted now?
