### ISSUE TITLE
Add make-containerized-test job for CentOS CI

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1055]
... or include it in the make-containerized-build job like it is currently done with Travis CI.

**Comment by Madhu-1** [comment]
@nixpanic what are the jobs we are planning to  test in centos CI?
i was think we can  run E2E testing in centos CI and other small  jobs can be run on Travis CI. any thoughts?

**Comment by Yuggupta27** [comment]
I would love to work on it!

**Comment by Yuggupta27** [comment]
Since #1068 is merged, anything else is required or can we close this issue?

**Comment by nixpanic** [comment]
Yes, as we noticed there needs to be a re-try in case the reserving of a bare-metal machine fails.

Also, both containerized-test and containerized-build stages could be run in parallel (nice enhancement, not urgent)

**Comment by Madhu-1** [comment]
closing this one as this job is already added to centos CI. @nixpanic @Yuggupta27 Thanks
