### ISSUE TITLE
Replace unmaintained commitlint by confgurable CI job

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1057]
# Describe the bug #

[commitlint](https://github.com/z0al/commitlint-bot) is not maintained and the Semantic Pull Request bot is not a suitable replacement (#1053).

We need a functional bot or CI job that can be configured for the use in Ceph-CSI.

# Additional context #

A Travis CI job with [conventional-changelog/commitlint](https://commitlint.js.org/#/guides-ci-setup) should be simple to setup. Or this can be run on the CentOS CI as well.
It seems possible to include a [`.commitlintrc.yml`](https://github.com/conventional-changelog/commitlint#config) that contains the rules for commits.

The `make containerized-test TARGET=commitlint` command should also work, so that developers can run the tests locally before posting a PR.

**Comment by Madhu-1** [comment]
@nixpanic hope this can be closed once we add commilint to Travis CI
