### ISSUE TITLE
Add mergify rule to merge PRs with a single positive review and special label

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1065]
In todays call we discussed about the difficultie of reviewers keeping up with the number of new and updated PRs. There are many PRs that have been reviewed by a single reviewer, and are waiting for a 2nd one.

In order to speed up the development of Ceph-CSI, we decided that there can be a label that indicates a 2nd review is not needed (or the opposite, implementation does not matter).

The suggestion is as follows:

1. always merge when two reviewers left a positive review (current state, should be default)
1. add a new label `[lgtm]` - looks good to me me
1. add a new mergify rule, that checks for a positive review AND the `[lgtm]` label
  have mergify merge the PR if the result of the rule is true
1. if a **reviewer** is confident the change can be merged without a 2nd review, the reviewer can leave a positive review AND add the `[lgtm]` label
  **ONLY THE REVIEWER** should add the label, not the author of the PR

This process should get documented in the developers guide, or maybe we should start a maintainers guide.

**Comment by Madhu-1** [comment]
@nixpanic i have sent a PR with slightly different approach PTAL if that works out https://github.com/ceph/ceph-csi/pull/1064

**Comment by Madhu-1** [comment]
Fixed in #1064 closing
