### ISSUE TITLE
Update helm chart documentations

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1076]
Current helm chart Readme https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-cephfs/README.md and https://github.com/ceph/ceph-csi/tree/master/charts/ceph-csi-rbd  will talk about only on how to install and uninstall cephfs and rbd csi driver. we need to document all the available options when deploying these helm charts, This will help users to understand available options which they need to pass when there are installing helm charts

**Comment by humblec** [comment]
@yati1998 is it something you are interested to work on ?

**Comment by yati1998** [comment]
@humblec sure I will take a look into this.

**Comment by yati1998** [comment]
@humblec or @Madhu-1 can you please give me some more details on the other options available when deploying the helm charts? Or if there are any reference for this that can help me in the documentation.

**Comment by Madhu-1** [comment]
the configuration we need to documents are https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-cephfs/values.yaml and https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-rbd/values.yaml https://github.com/rook/rook/blob/master/Documentation/helm-operator.md is an example you can follow

**Comment by yati1998** [comment]
@Madhu-1 thanks for the insights.

**Comment by Madhu-1** [comment]
We also need to add helm upgrade also which is missing currently.
