### ISSUE TITLE
HELM install failed with Azure RedHat Openshift

### ISSUE THREAD

**Issue by ezYakaEagle442** [ceph/ceph-csi#1077]
# Describe the bug #

CEPH HELM chart  installation failed with Azure RedHat Openshift 4.3.
The security context looked correctly set both in [yaml ](https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-cephfs/templates/provisioner-deployment.yaml#L117) and [HELM chart](https://github.com/ceph/ceph-csi/blob/master/deploy/cephfs/kubernetes/csi-cephfsplugin.yaml#L25) , the issue is that the HELM deployment fails to deploys the CEPH deployment as it does create the SA without the ARO Security Context Constraint , there is an example [here](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator-openshift.yaml#L54)

oc adm policy add-scc-to-user privileged system:serviceaccount:"ceph-csi-cephfs":"cephfs-csi-nodeplugin"
oc describe scc privileged

# Environment details #

- Image/version of Ceph CSI driver :
- Helm chart version : ceph-csi-cephfs-2.1.1
- Kernel version :
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
- Kubernetes cluster version : ARO 4.3.18 ==> k8s v1.16.2
- Ceph cluster version :

# Steps to reproduce #

See my [git repo](https://github.com/ezYakaEagle442/aro-pub-storage/blob/master/setup-store-CSI-driver.md#install-ceph-driver)

```sh
# https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-cephfs/README.md
# https://hub.helm.sh/charts/ceph-csi/ceph-csi-cephfs
helm repo add ceph-csi https://ceph.github.io/csi-charts

helm install --namespace "ceph-csi-cephfs" "ceph-csi-cephfs" ceph-csi/ceph-csi-cephfs
    #--set ceph-csi-cephfs.serviceAccountName.nodeplugin="" \
    #--set ceph-csi-cephfs.serviceAccountName.provisioner="" 

helm ls -n "ceph-csi-cephfs" 
helm status "ceph-csi-cephfs" -n "ceph-csi-cephfs"
 oc get events -n "ceph-csi-cephfs" | grep -i "Error"
```

# Actual results #

Describe what happened

# Expected behavior #

# Logs #

Warning   FailedCreate        daemonset/ceph-csi-cephfs-nodeplugin                Error creating: pods "ceph-csi-cephfs-nodeplugin-" is forbidden: unable to validate against any security context constraint: [provider restricted: **.spec.securityContext.hostNetwork: Invalid value: true**: Host network is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[4]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[5]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[6]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[7]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: **Privileged containers are not allowed spec.containers[0].securityContext.hostNetwork**: Invalid value: true: Host network is not allowed to be used spec.containers[1].**securityContext.privileged: Invalid value: true: Privileged containers are not allowed capabilities.add: Invalid value: "SYS_ADMIN"**: capability may not be added spec.containers[1].securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[2].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[2].securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used]
1s          Warning   FailedCreate        replicaset/ceph-csi-cephfs-provisioner-678689b5b7   Error creating: pods "ceph-csi-cephfs-provisioner-678689b5b7-" is forbidden: unable to validate against any security context constraint: [spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[3].securityContext.privileged: Invalid value: true: Privileged containers are not allowed capabilities.add: Invalid value: "SYS_ADMIN": capability may not be added]

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC resize please attach complete logs of below containers.

- csi-resizer and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in snapshot creation and deletion please attach complete logs
of below containers.

- csi-snapshotter and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC mounting please attach complete logs of below containers.

- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
  plugin pod from the node where the mount is failing.

- if required attach dmesg logs.

**Note:-** If its a rbd issue please provide only rbd related logs, if its a
cephfs issue please provide cephfs logs.

**Comment by ezYakaEagle442** [comment]
```sh
export CSI_NAMESPACE="ceph-csi-cephfs"
oc create namespace $CSI_NAMESPACE

envsubst < ./cnf/ceph/csi-provisioner-rbac.yaml > deploy/csi-provisioner-rbac.yaml
cat deploy/csi-provisioner-rbac.yaml
oc create -f deploy/csi-provisioner-rbac.yaml -n $CSI_NAMESPACE

oc get clusterrolebindings -n $CSI_NAMESPACE | grep -i "ceph"
oc get clusterroles -n $CSI_NAMESPACE | grep -i "ceph"

envsubst < ./cnf/ceph/csi-nodeplugin-rbac.yaml > deploy/csi-nodeplugin-rbac.yaml
cat deploy/csi-nodeplugin-rbac.yaml
oc create -f deploy/csi-nodeplugin-rbac.yaml -n $CSI_NAMESPACE

envsubst < ./cnf/ceph/csi-provisioner-psp.yaml > deploy/csi-provisioner-psp.yaml
cat deploy/csi-provisioner-psp.yaml
oc create -f deploy/csi-provisioner-psp.yaml -n $CSI_NAMESPACE

envsubst < ./cnf/ceph/csi-nodeplugin-psp.yaml > deploy/csi-nodeplugin-psp.yaml
cat deploy/csi-nodeplugin-psp.yaml
oc create -f deploy/csi-nodeplugin-psp.yaml -n $CSI_NAMESPACE

oc get psp

oc create -f ./cnf/ceph/csi-config-map.yaml -n $CSI_NAMESPACE

envsubst < ./cnf/ceph/csi-aro-scc.yaml > deploy/csi-aro-scc.yaml
cat deploy/csi-aro-scc.yaml
oc create -f deploy/csi-aro-scc.yaml

oc get scc -o wide
oc describe scc privileged
# oc adm policy add-scc-to-user privileged system:serviceaccount:ceph-csi-cephfs:cephfs-csi-nodeplugin
oc describe scc cephfs-csi-provisioner-scc

oc create -f ./cnf/ceph/csi-cephfsplugin-provisioner.yaml -n $CSI_NAMESPACE
oc create -f ./cnf/ceph/csi-cephfsplugin.yaml -n $CSI_NAMESPACE


oc get events -n $CSI_NAMESPACE | grep -i "Error" 

oc get ds -n $CSI_NAMESPACE
oc get deploy -n $CSI_NAMESPACE
oc get rs -n $CSI_NAMESPACE
oc get svc -n $CSI_NAMESPACE
oc get cm -n $CSI_NAMESPACE
oc get psp -n $CSI_NAMESPACE
oc get rolebinding -n $CSI_NAMESPACE
oc get role -n $CSI_NAMESPACE
oc get ClusterRoleBinding | grep -i "ceph"
oc get ClusterRole | grep -i "ceph"
oc get sa -n $CSI_NAMESPACE
oc get po -n $CSI_NAMESPACE
```

but the deployment fails with the same error : 

12s         Warning   FailedCreate        replicaset/csi-cephfsplugin-provisioner-54d955869d   Error creating: pods "csi-cephfsplugin-provisioner-54d955869d-" is forbidden: unable to validate against any security context constraint: [spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[3].securityContext.privileged: Invalid value: true: Privileged containers are not allowed capabilities.add: Invalid value: "SYS_ADMIN": capability may not be added]

**Comment by Madhu-1** [comment]
@ezYakaEagle442 Thanks for reporting the issue the deployment files and helm charts what we have now is only tested with upstream kubernetes not openshift, PR's are welcome to update required templates and documentation to deploy cephcsi  on OCP

**Comment by ezYakaEagle442** [comment]
I was wrong to create a new SCC as the pods are configured with the existing privileged one, so it looks like that was just need was :
**oc adm policy add-scc-to-user privileged system:serviceaccount:$CSI_NAMESPACE:cephfs-csi-nodeplugin**

```sh
# envsubst < ./cnf/ceph/csi-aro-scc.yaml > deploy/csi-aro-scc.yaml
# cat deploy/csi-aro-scc.yaml
# oc create -f deploy/csi-aro-scc.yaml
# oc describe scc cephfs-csi-provisioner-scc
oc adm policy add-scc-to-user privileged system:serviceaccount:$CSI_NAMESPACE:cephfs-csi-nodeplugin
oc get scc -o wide
oc describe scc privileged

oc create -f ./cnf/ceph/csi-cephfsplugin-provisioner.yaml -n $CSI_NAMESPACE
oc create -f ./cnf/ceph/csi-cephfsplugin.yaml -n $CSI_NAMESPACE

oc get events -n $CSI_NAMESPACE | grep -i "Error" 

oc get rolebinding -n $CSI_NAMESPACE
oc get role -n $CSI_NAMESPACE
oc get ClusterRoleBinding | grep -i "ceph"
oc get ClusterRole | grep -i "ceph"
oc get cm -n $CSI_NAMESPACE
oc get sa -n $CSI_NAMESPACE
oc get svc -n $CSI_NAMESPACE
oc get psp
oc get ds -n $CSI_NAMESPACE
oc get deploy -n $CSI_NAMESPACE
oc get rs -n $CSI_NAMESPACE
oc get po -n $CSI_NAMESPACE
```

**Comment by ezYakaEagle442** [comment]
repo updated at [https://github.com/ezYakaEagle442/aro-pub-storage/blob/master/setup-store-CSI-driver-ceph.md](https://github.com/ezYakaEagle442/aro-pub-storage/blob/master/setup-store-CSI-driver-ceph.md)

**Comment by Madhu-1** [comment]
@ezYakaEagle442 Thanks for opening the issue and providing pointers on how to install cephcsi in openshift closing this one as this will be covered in https://github.com/ceph/ceph-csi/issues/1088
