### ISSUE TITLE
Explain how to get User ID & Key + admin ID & Key

### ISSUE THREAD

**Issue by ezYakaEagle442** [ceph/ceph-csi#1082]
# Describe the feature you'd like to have #

Following [this guideline](https://github.com/ceph/ceph-csi/tree/master/examples) , I wanted to test the CEPH CSI driver but I do not know how to get the here under values to set in the secret.yaml file 
-userID
- userKey
- adminID
- adminKey

```sh
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ${CSI_NAMESPACE}
stringData:
  # Required for statically provisioned volumes
  userID: <plaintext ID>
  userKey: <Ceph auth key corresponding to ID above>

  # Required for dynamically provisioned volumes
  adminID: <plaintext ID>
  adminKey: <Ceph auth key corresponding to ID above>
```

# What is the value to the end user? (why is it a priority?) #

At this stage I have used Rook to install CEPH, but I am not able to run the above test through CEPH CSI driver.

**Comment by Madhu-1** [comment]
rook already provides its own CSI driver for the ceph cluster its managing you can make use of it here is the info about CSI driver on rook https://rook.io/docs/rook/master/ceph-csi-drivers.html

@agarwal-mudit would you like to add documentation about cephfs and rbd user required for cephcsi?

this will be covered in https://github.com/ceph/ceph-csi/issues/360

**Comment by Madhu-1** [comment]
closing this one as this need to be covered in #360
