### ISSUE TITLE
Add documentation or support matrix we use for csi release or master branch

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1095]
At present its very difficult to assume which sidecar versions are used in this repo and branches. We could add a matrix or update existing support matrix to include this information and it will be really handy.

**Comment by humblec** [comment]
@Madhu-1 fyi

**Comment by Madhu-1** [comment]
Thanks for opening this issue humble, we need to document min and Max supported version of kubernetes sidecar
