### ISSUE TITLE
when i create a Job pod，found pvc do not mount pvc 

### ISSUE THREAD

**Issue by luhailiang0527** [ceph/ceph-csi#1105]
kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name rbd.csi.ceph.com not found in the list of registered CSI drivers

**Comment by Madhu-1** [comment]
@luhailiang0527 can you restart rbd-plugin pod, that should fix the issue.

**Comment by luhailiang0527** [comment]
thank you very much，i had fix the issue，so ，i close this issue

**Comment by Madhu-1** [comment]
@luhailiang0527 Thanks for the confirmation, closing this issue
