### ISSUE TITLE
Add support to create multiple subvolume groups 

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1123]
in https://github.com/ceph/ceph-csi/pull/931 we have added support to have subvolumegroup configurable(which means we can have more than one subvolume group in cephcsi). with the current code base the subvolumegroup will be created once ie https://github.com/ceph/ceph-csi/blob/44da7ffb4e4d8861265f3ecd421cd06dfce9f34a/internal/cephfs/volume.go#L90 we need to make changes to support the creation of multiple subvolumegroups.

**Comment by Madhu-1** [comment]
@Yuggupta27 would you like to give a  try for this one, I can help you out if you need anything

**Comment by Yuggupta27** [comment]
> @Yuggupta27 would you like to give a try for this one, I can help you out if you need anything

Sure. Please Assign.

**Comment by ShyamsundarR** [comment]
Something to think about would be, when a subvolumegroup and the cephx credentials for the same are pre-created, to restrict access just to that subvolume group, would the called out function still work?

IOW, we started out with creating the subvolume group in CSI, but it may so happen that for security reasons, these are pre-created and the credentials for CSI are restricted to this subvolumegroup. In such cases, it would help to understand if the `create` command above still works, or would error out.

**Comment by Madhu-1** [comment]
we need to check what if the subvolume is already created, and the csi user doesn't have the permission to create it, how we can check this if the create subvolume group fails in this case and on what basis we need to continue with creating subvolumes etc.
 we need to create a user who is having access to create subvolume, not the subvolume group and test this out,  the caps can be found in this comment https://github.com/ceph/ceph-csi/pull/437#issuecomment-511460712 need to modify the path according to our requirement. 

can we have a user who is not having any read and write permission or only read permission to subvolume groups. if someone can provide the caps it would be useful to test it out.
cc @ShyamsundarR @kotreshhr @joscollin

**Comment by joscollin** [comment]
> can we have a user who is not having any read and write permission or only read permission to subvolume groups.

There is a `--mode` parameter for subvolumegroup create command. 

From your description, I don't quiet understand what you are trying to achieve.

**Comment by ShyamsundarR** [comment]
> > can we have a user who is not having any read and write permission or only read permission to subvolume groups.
> 
> There is a `--mode` parameter for subvolumegroup create command.
> 
> From your description, I don't quiet understand what you are trying to achieve.

Pasting from #437 on caps required to work with a subvolume group,
```
The auth IDs capabilities would be,

caps mon = "allow r"
caps mgr = "allow rw"
caps mds = "allow rw path=/volumes/csi"
caps osd = "allow rw tag cephfs data=cephfs "

assuming the ceph volume/filesystem name is cephfs.
```

I would assume as long as rw caps are provided for `caps mds = "allow rw path=/volumes/csi"` a `ceph fs subvolumegroup create cephfs csi` would return a success and is idempotent (this is how ceph-csi works at present)

The question is,
- Can subvolume lifecycle operations work if caps are instead only "r" for the subvolumegroup, like so `caps mds = "allow r path=/volumes/csi"`, with any additional caps for subvolume lifecycle operations within the subvolumegroup?
- If the above is true then invoking `ceph fs subvolumegroup create cephfs csi` would most probably return an error as "w" caps are not provided for the subvolumegroup itself

The use-case for subvolumegroup to be redable only would be where, a tenant kubernetes cluster should not be able to modify the subvolumegroups quota or attributes, where the cephfs instance is shared across multiple such tenants, and hence break tenant allocated limits or attributes.
