### ISSUE TITLE
Make scripts/install-snapshot.sh easier to re-use

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1139]
# Describe the feature you'd like to have #

Currently the `scripts/install-snapshot.sh` script needs to be called depending on the Kubernetes version. It would be much easier to use the script if it is intelligent enough to decide itself what version of the snapshot components to install (or none at all).

# What is the value to the end user? (why is it a priority?) #

- manually deploying ceph-csi will be easier
- CI environments do not need to detect the Kubernetes version and conditionally run the script

# How will we know we have a good solution? (acceptance criteria) #

The `scripts/travis-functest.st` does not need to check for the Kubernetes version anymore. And neither do any other scripts (like the multi-node e2e introduced through #1083).

# Additional context #

Parsing the version can be done with `jq`:
```shell
# K_MAJOR=$(kubectl version -ojson | jq '.serverVersion.major' | tr -d \")
# K_MINOR=$(kubectl version -ojson | jq '.serverVersion.minor' | tr -d \")
# echo "major: ${K_MAJOR}, minor: ${K_MINOR}"
```

**Comment by Madhu-1** [comment]
still need to fix this one

**Comment by pkalever** [comment]
@Madhu-1 assign this to me.

**Comment by Madhu-1** [comment]
> @Madhu-1 assign this to me.

done. Thank you
