### ISSUE TITLE
Remove non-release branches from the repo

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1148]
There are again more branches than expected. @humblec seems to have pushed branches for PRs to the main repository, not his personal fork. Once the PRs have been closed, the branches should get deleted.

From the [active branches](https://github.com/ceph/ceph-csi/branches/active):
- [ ] config #1147
- [ ] go-update #1145 
- [ ] node-rbac #1142
- [ ] readmdlint #1146 

See-also: #1050

**Comment by humblec** [comment]
Yeah. .it was my mistake..  I am closing those PRs for now.

**Comment by humblec** [comment]
This is taken care now. Closing this issue.

**Comment by nixpanic** [comment]
Reopening.

The `more` and `more-1` branches have been added.

**Comment by nixpanic** [comment]
I still see a `more` branch, please cleanup.

**Comment by Madhu-1** [comment]
closing this one as there is no unwanted branches.
