### ISSUE TITLE
Come up with a documentation on review process by also making use of Owners file

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1155]
# Describe the feature you'd like to have #
Considering we have approvers and reviewers in the repo, we should come up with a process and auto handling of much tasks via OWNERS file. We also need to define the process around this 

What new functionality do you want?

# What is the value to the end user? (why is it a priority?) #

The documented process will help many community users to get proper attention over the PRs , Designs..etc .

**Comment by humblec** [comment]
The first step is taken here https://github.com/ceph/ceph-csi/pull/1150

**Comment by Madhu-1** [comment]
@humblec is working on this one. removing stalebot label
