### ISSUE TITLE
Failed to load cephfs kernel mounter even if kernel>4.17

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1167]
The cephfs plugin container is failed to load the kernel mounter even if the kernel is higher than the 4.17, this issue can be reproducible if we created kubernetes cluster with minikube VM(vm_driver=kvm2)

Logs from cephfsplugin
```text
E0616 05:21:30.439584       1 volumemounter.go:101] failed to parse sublevel from 4.19.107: strconv.Atoi: parsing "107\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00": invalid syntax
I0616 05:21:30.439640       1 volumemounter.go:165] kernel version < 4.17 might not support quota feature, hence not loading kernel client
```

the kernel version on minikube node
```console
$ uname -a
Linux minikube 4.19.107 #1 SMP Mon May 11 14:51:04 PDT 2020 x86_64 GNU/Linux
$ uname -r
4.19.107
```

Note:  we need to discard `0` in bytes  at https://github.com/ceph/ceph-csi/blob/master/internal/cephfs/volumemounter.go#L159

**Comment by nixpanic** [comment]
That looks weird. What version of Golang are you using? I would expect that a `\x00` byte is a marker for the end of a string. Maybe there is a cleaner way to convert a byte-array to a string?

**Comment by Madhu-1** [comment]
> That looks weird. What version of Golang are you using? I would expect that a `\x00` byte is a marker for the end of a string. Maybe there is a cleaner way to convert a byte-array to a string?

go version go1.13.10 linux/amd64. 

```bash
-               release := string(utsname.Release[:64])
 
+               // Remove the \x00 from the release for Atoi to parse correctly
+               release := string(utsname.Release[:bytes.IndexByte(utsname.Release[:], 0)])
+               fmt.Printf("the final release is %v\n", release)
```
the above change should fix the issue, we need to discard the 0's  in the byte array, just need testing and e2e

**Comment by nixpanic** [comment]
I do not think using `bytes.IndexByte()` is a clean approach, there should be a way to convert a byte array ending with `0x00` to a string without manual stripping the end-of-string-characters.

**Comment by Madhu-1** [comment]
> I do not think using `bytes.IndexByte()` is a clean approach, there should be a way to convert a byte array ending with `0x00` to a string without manual stripping the end-of-string-characters.

that's the one I can think of, if we can get a better approach it will great

**Comment by Madhu-1** [comment]
one other thing is we can use bytes.Trim functions

**Comment by phlogistonjohn** [comment]
> That looks weird. What version of Golang are you using? I would expect that a `\x00` byte is a marker for the end of a string. Maybe there is a cleaner way to convert a byte-array to a string?

Just a reminder that native Go strings are pascal style and do not have trailing nulls like C-strings. 

> one other thing is we can use bytes.Trim functions

Yeah. TrimRight is probably  closest to what you want.
