### ISSUE TITLE
Use a single file with versions and parameters for building, CI and deployment

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1180]
Currently versions of different components and tools are listed in several places. Including `Makefile`, `.travis.yml` and several of the `Dockerfile`s. When updating a version of a tool or component, the change needs to get done everywhere.

Instead, all versions should be stored in `build.env` (or other filename) that can be consumed everywhere.

**Comment by humblec** [comment]
This is much required one! the current way of env handling is a mess.
