### ISSUE TITLE
ceph-csi-driver provisioner volume must use  ceph admin user and adminkeyring?

### ISSUE THREAD

**Issue by jianglingxia** [ceph/ceph-csi#1181]
# Describe the bug #
I found the ceph-csi-driver provisioner volume and pv create the secret must use the adminID and adminKey

the secret yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: {{fssecret}}
  namespace: {{ns}}
stringData:
  # Required for statically provisioned volumes
  #userID: <plaintext ID>
  #userKey: <Ceph auth key corresponding to ID above>

  # Required for dynamically provisioned volumes
  adminID: {{adminID}}
  adminKey: {{adminKey}}

i found the code cephfs 
`if volOptions.ProvisionVolume {
		// The volume is provisioned dynamically, use passed in admin credentials

		cr, err = util.NewAdminCredentials(secrets)
		if err != nil {
			return nil, fmt.Errorf("failed to get admin credentials from node stage secrets: %v", err)
		}
	} else {
		// The volume is pre-made, credentials are in node stage secrets

		cr, err = util.NewUserCredentials(req.GetSecrets())
		if err != nil {
			return nil, fmt.Errorf("failed to get user credentials from node stage secrets: %v", err)
		}
	}`

# Environment details #

- Image/version of Ceph CSI driver :v1.2.0
- Helm chart version :
- Kernel version :
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : cephfs fuse
- Kubernetes cluster version :v1.17
- Ceph cluster version :

# Steps to reproduce #

1. Setup details: '...'
1. Deployment to trigger the issue '....'
1. See error

# Actual results #

Describe what happened
why volume provisioner must use the adminID and adminkey?can use the userID and userKey?
# Expected behavior #

# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC resize please attach complete logs of below containers.

- csi-resizer and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in snapshot creation and deletion please attach complete logs
of below containers.

- csi-snapshotter and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC mounting please attach complete logs of below containers.

- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
  plugin pod from the node where the mount is failing.

- if required attach dmesg logs.

**Note:-** If its a rbd issue please provide only rbd related logs, if its a
cephfs issue please provide cephfs logs.

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by jianglingxia** [comment]
@Madhu-1  can you help the issue ?thanks

**Comment by Madhu-1** [comment]
Its Just name naming convention, it doesnt need to be admin user and its creads,
the user should have the access to create subvolume and to mount subvolume

an example caps like below
```bash
"mon", "allow r",
"mgr", "allow rw",
"osd", "allow rw tag cephfs *=*",
"mds", "allow rw",
```

**Comment by nixpanic** [comment]
@Madhu-1 are the required caps documented somewhere? If not, we should really do so.

**Comment by Madhu-1** [comment]
> @Madhu-1 are the required caps documented somewhere? If not, we should really do so.

https://github.com/ceph/ceph-csi/issues/360 issue already exists to document these caps

**Comment by Madhu-1** [comment]
@jianglingxia if above answers your question, can this be closed?

**Comment by jianglingxia** [comment]
really thanks for your repliy, is mean that user can use plain user and userkey?
but the code when provisioner volume get the secret resource by adminID value and adminKey value

cr, err := util.NewAdminCredentials(secret)
	if err != nil {
		return nil, err
	}
	defer cr.DeleteCredentials()

you mean provisioner volume the secret yaml use the adminID and adminKey but the value use plain user have access ceph cluster?

**Comment by Madhu-1** [comment]
Yes you are correct.

**Comment by jianglingxia** [comment]
thanks all

**Comment by deadjoker** [comment]
I use ceph-csi 3.2.0 and k8s 1.2.0 and when I create cephfs pvc, the provisioner logs tells `operation not permitted`.
I use the user caps:
```
client.k8sfs
	key: AQDuM+xfXz0zNRAAnxeJaWdmR2J5I/QxMR9gLQ==
	caps: [mds] allow rwps
	caps: [mgr] allow rw
	caps: [mon] allow r
	caps: [osd] allow rw tag cephfs data=cephfs
```
It succeeds if I use admin keyring.
Does ceph-csi need more permission in version 3.2.0?
