### ISSUE TITLE
Volumes created from a snapshot/volume may have non-accessible content

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1183]
There are places in the VolumeStage path where the permissions of the contents on the volume get modified. This is mainly important for new volume creations, so that the volume becomes writable for the users (`chmod 0777` on the root of the volume). See `internal/cephfs/nodeserver.go:mount()` for an example.

This works fine for volumes that do not have any content yet. However, when creating a volume from a snapshot or other volume, the contents may not be writable by the user/process in the container. Only changing permissions of the root of the volume is not sufficient.

CephFS and RBD provisioning most likely needs some adaptations for this.

**Comment by Madhu-1** [comment]
@nixpanic can you please provide the steps to reproduce this issue? so that we can fix it in this release.
