### ISSUE TITLE
Update golangci to v1.27.0 (or current latest version)

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1184]
We are testing with golangci v1.21.0, while v1.27.0 is [currently the latest version](https://github.com/golangci/golangci-lint/tags).

Several new linters have been added since. Our codebase is not following best practices, so the new golangci linters report errors.

This issue is a tracker for how to run with the new linter version, and which PRs address code cleanups (or linter configuration tuning) to move towards making the new version the default for the project.

## Usage

1. edit `build.env` (or `scripts/Dockerfile.test` in case #1182 is not merged yet)
1. replace `GOLANGCI_VERSION=v1.21.0` with `GOLANGCI_VERSION=v1.27.0`
1. run `make containerized-test TARGET=go-lint`
1. pick a series of warnings that you want to address, copy/paste the warning somewhere (you'll need it later)
1. address the warning in the source file
1. run `make containerized-test TARGET=go-lint` again to verify that the warning is fixed an no new ones introduced
1. commit the source changes only (not `build.env` or `scripts/Dockerfile.test`), use a commit message like
    ```
    cleanup: address <linter/warning> in <function/file>
    
    kubernetes/go-client was imported twice in the <file>. Make sure it is only imported once.
    The DupImport linter reported this issue as:
    
    <paste the copied original warning, don't add additional linebreaks, lines can be long>

    Signed-off-by: Your Real Name <email@example.net>
    ```
1. push the commit to your GitHub fork of the project
1. create a new PR and mention `Updates: #1184` so that this issue gets linked

**Comment by ansiwen** [comment]
I have to run the test with `CPUSET= make containerized-test TARGET=go-lint`, because I use root-less podman. Is this a known issue?
