### ISSUE TITLE
Breaking metadatastorage change in quay.io/cephcsi/cephfsplugin:v0.3.0

### ISSUE THREAD

**Issue by UrbanWizardry** [ceph/ceph-csi#119]
A change has been made in `master` concerning the following files:

deploy/cephfs/kubernetes/csi-cephfsplugin.yaml: 52
`     - "--metadatastorage=k8s_configmap"`

pkg/util/cachepersister.go: 38:52
```
    if metadataStore == "k8s_configmap" {
		glog.Infof("cache-perister: using kubernetes configmap as metadata cache persister")
		k8scm := &K8sCMCache{}
		k8scm.Client = NewK8sClient()
		k8scm.Namespace = GetK8sNamespace()
		return k8scm, nil
	} else if metadataStore == "node" {
		glog.Infof("cache-persister: using node as metadata cache persister")
		nc := &NodeCache{}
		nc.BasePath = PluginFolder + "/" + driverName
		return nc, nil
	}
    return nil, errors.New("cache-persister: couldn't parse metadatastorage flag")
```
    
`cachepersister.go` now explicitly requires the --metadatastorage flag to be passed in.

However, the Docker image build has been updated with the new code, but the tag has *remained* v0.3.0. This means that an existing deployment of the csi-cephfsplugin DaemonSet, which does not have the `"--metadatastorage=k8s_configmap"` argument in `csi-cephfsplugin.yaml`, will begin to break as new nodes are added to the k8s cluster and the new nodes download the latest copy of the Docker image.

This breaking change should be tagged as either v0.3.1 or v0.4.0, depending on your philosophy of SemVer

**Comment by rootfs** [comment]
fixing in progress...
