### ISSUE TITLE
ceph-csi-driver pod used cephfs pvc exec controllerPublishVolume(attach volume)?

### ISSUE THREAD

**Issue by jianglingxia** [ceph/ceph-csi#1190]
# Describe the bug #
the kubelet log is Volume not attached according to node status for volume \"pvc-68e8f364-7b51-461b-8cc2-ec2ef766c0fa\" 

i found the cephfs csi-cephfs-driver code not found the method ControllerPlublishVolume，is mean the pod used cephfs pvc maybe no need exec attached ,is right?
so the attacher sidecar watch the volumeattachment,the csi driver do nothing then the k8s will modify the node spec the 
volumesAttached and volumesInUse?
thanks 

I0624 15:24:07.813439  111112 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-68e8f364-7b51-461b-8cc2-ec2ef766c0fa" (UniqueName: "kubernetes.io/csi/ceph1.cephfs.csi.ceph.com^0001-0024-2a3ca00e-8585-427d-879a-ef3e5a621208-0000000000000001-3ab2a829-b097-11ea-ba7d-0a33e178dd12") pod "ldapserver-35af9c6b-e21a-4098-8fcb-f2a152961f69-0" (UID: "6f3c8374-4b00-4d8e-90d6-27511cd737c7")
E0624 15:24:07.816186  111112 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/csi/ceph1.cephfs.csi.ceph.com^0001-0024-2a3ca00e-8585-427d-879a-ef3e5a621208-0000000000000001-3ab2a829-b097-11ea-ba7d-0a33e178dd12\"" failed. No retries permitted until 2020-06-24 15:26:09.816153805 +0800 CST m=+105523.191797241 (durationBeforeRetry 2m2s). Error: "Volume not attached according to node status for volume \"pvc-68e8f364-7b51-461b-8cc2-ec2ef766c0fa\" (UniqueName: \"kubernetes.io/csi/ceph1.cephfs.csi.ceph.com^0001-0024-2a3ca00e-8585-427d-879a-ef3e5a621208-0000000000000001-3ab2a829-b097-11ea-ba7d-0a33e178dd12\") pod \"ldapserver-35af9c6b-e21a-4098-8fcb-f2a152961f69-0\" (UID: \"6f3c8374-4b00-4d8e-90d6-27511cd737c7\") "
E0624 15:26:08.765826  111112 kubelet.go:1717] Unable to attach or mount volumes for pod "ldapserver-35af9c6b-e21a-4098-8fcb-f2a152961f69-0_opcs(6f3c8374-4b00-4d8e-90d6-27511cd737c7)": unmounted volumes=[share-pvc], unattached volumes=[share-pvc openjdk-path logpath secret-app default-token-2wtp2]: timed out waiting for the condition; skipping pod
E0624 15:26:08.765852  111112 pod_workers.go:191] Error syncing pod 6f3c8374-4b00-4d8e-90d6-27511cd737c7 ("ldapserver-35af9c6b-e21a-4098-8fcb-f2a152961f69-0_opcs(6f3c8374-4b00-4d8e-90d6-27511cd737c7)"), skipping: unmounted volumes=[share-pvc], unattached volumes=[share-pvc openjdk-path logpath secret-app default-token-2wtp2]: timed out waiting for the condition

# Environment details #

- Image/version of Ceph CSI driver :v1.2.0
- Helm chart version :
- Kernel version :
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :fuse
- Kubernetes cluster version :v1.17.6
- Ceph cluster version :

# Steps to reproduce #

1. Setup details: '...'
1. Deployment to trigger the issue '....'
1. See error

# Actual results #

Describe what happened

# Expected behavior #

# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC resize please attach complete logs of below containers.

- csi-resizer and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in snapshot creation and deletion please attach complete logs
of below containers.

- csi-snapshotter and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC mounting please attach complete logs of below containers.

- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
  plugin pod from the node where the mount is failing.

- if required attach dmesg logs.

**Note:-** If its a rbd issue please provide only rbd related logs, if its a
cephfs issue please provide cephfs logs.

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by jianglingxia** [comment]
@nixpanic   @Madhu-1 

really thanks

**Comment by Madhu-1** [comment]
cephfs does not support ControllerPublishVolume

**Comment by jianglingxia** [comment]
yeah,the attach in sidecar external-attacher used trivialHandler markAsAttached
but cephfs if not attached can create the CSIDriver resource in k8s  like this 

apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: csi-cephfs-sc
spec:
  attachRequired: false     //marked false then the k8s no need create volumeattachment resource because there have some problem when volumeattachment has more the kube-controller-manager maybe have some delay 
the pr: https://github.com/kubernetes/kubernetes/pull/91307/
  podInfoOnMount: true
  volumeLifecycleModes:
  - Persistent
  - Ephemeral

**Comment by Madhu-1** [comment]
Attach is required or else we may face issue with rwo pvc it's not a good idea to disable it. Closing this one
