### ISSUE TITLE
Rename the "master" branch to "devel" or similar

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1193]
The name of the `master` branch in git has associations with slavery and can make contributors feel less welcome. Instead of being triggering emotional reactions while developing software, it would be preferred to rename the main working branch to `devel` or something like that.

My opinion is that `main` is not specific enough, users could consider it as a stable release. Hence `devel` is my suggestion.

- https://www.theregister.com/2020/06/08/developers_renew_push_to_get/
- https://www.theregister.com/2020/06/15/github_replaces_master_with_main/

**Comment by mykaul** [comment]
+1 for devel.

**Comment by Madhu-1** [comment]
+1 for devel

**Comment by Madhu-1** [comment]
@humblec @ShyamsundarR @Yuggupta27 @agarwal-mudit any suggestion.

**Comment by Yuggupta27** [comment]
I'm fine with both devel and main. Both are better than master anyways :)

**Comment by Yuggupta27** [comment]
@nixpanic https://eyqs.ca/tools/rename/ might help.

**Comment by humblec** [comment]
Yeah, lets use `devel` instead of `master.

**Comment by agarwal-mudit** [comment]
devel is better than main

**Comment by agarwal-mudit** [comment]
@phlogistonjohn @nixpanic I guess same is required for go-ceph also?

**Comment by Madhu-1** [comment]
the master branch is renamed as the devel
