### ISSUE TITLE
containerized test fails on multiple re-runs.

### ISSUE THREAD

**Issue by Yuggupta27** [ceph/ceph-csi#1197]
# Describe the bug #

Re-running containerized test fails with an error.
Container Runtime: Docker

# Steps to reproduce #

` make containerized-test TARGET=go-lint`
and re-run multiple times.

# Actual results #

```
cephcsi image settings: quay.io/cephcsi/cephcsi version canary
docker run --rm -v /home/ygupta/go/src/github.com/ceph-csi:/go/src/github.com/ceph/ceph-csi quay.io/cephcsi/cephcsi:test make test GIT_SINCE=origin/master
Unable to find image 'quay.io/cephcsi/cephcsi:test' locally
docker: Error response from daemon: manifest for quay.io/cephcsi/cephcsi:test not found: manifest unknown: manifest unknown.
See 'docker run --help'.
make: *** [Makefile:137: containerized-test] Error 125
```

# Expected behavior #

re-running the command starts a new test.

# Additional context #

Workaround is deleting .test-container-id manually.

**Comment by nixpanic** [comment]
Could it be that the `quay.io/cephcsi/cephcsi:test` container image was removed in a different way than running `make clean` in the repository?

**Comment by Yuggupta27** [comment]
Are images being deleted automatically due to low disk space?

**Comment by Yuggupta27** [comment]
I cleared up space and still, the image seems to be gone after some time... I need to check what makes the image gets deleted...

**Comment by Yuggupta27** [comment]
Docker images get deleted automatically when sufficient free space is not present. If anyone else faces this issue, make sure you have enough free space on your disk, especially where you store the Docker images.
Closing this as it is not a ceph-csi issue.
