### ISSUE TITLE
Error in pod "csi-rbdplugin-provisioner"  Still connecting to unix:///csi/csi-provisioner.sock

### ISSUE THREAD

**Issue by jpsaneesh** [ceph/ceph-csi#1199]
# Describe the bug #

```
pod/csi-rbdplugin-provisioner-b96f6986-dmvpc   5/6     CrashLoopBackOff   16         59
m
pod/csi-rbdplugin-provisioner-b96f6986-jfzcj   5/6     CrashLoopBackOff   16         59
m
pod/csi-rbdplugin-provisioner-b96f6986-qjxhz   5/6     CrashLoopBackOff   16         59
m
```
On checking logs of the  pods, we see the following messages on repeat

W0702 14:07:56.018101       1 connection.go:172] Still connecting to unix:///csi/csi-provisioner.sock
W0702 14:08:06.018139       1 connection.go:172] Still connecting to unix:///csi/csi-provisioner.sock
W0702 14:08:16.018104       1 connection.go:172] Still connecting to unix:///csi/csi-provisioner.sock
.
.

**We observed this error on v2.1.2 and below while it worked fine on canary version of the same.**
# Environment details #

- Image/version of Ceph CSI driver : quay.io/cephcsi/cephcsi:v2.1.2
- Helm chart version : n/a (deployed using deploy folder of this repository)
- Kernel version :  3.10.0-514.el7.x86_64
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : 
- Kubernetes cluster version : v1.16.1
- Ceph cluster version : ceph version 14.2.10 (b340acf629a010a74d90da5782a2c5fe0b54ac20) nautilus (stable)

# Steps to reproduce #

1. Setup details: 
We deployed using files from this path : https://github.com/ceph/ceph-csi/tree/master/deploy/rbd/kubernetes

1. Deployment to trigger the issue '....'
kubectl apply -f csi-rbdplugin-provisioner.yaml with image tag changed to quay.io/cephcsi/cephcsi:v2.1.2 from canary.

1. See error
pod/csi-rbdplugin-provisioner-b96f6986-qjxhz   5/6     CrashLoopBackOff   16         59
m

# Actual results #

Describe what happened

# Expected behavior #

pod/csi-rbdplugin-provisioner-b96f6986-qjxhz   6/6     Running   0         59
m

# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC resize please attach complete logs of below containers.

- csi-resizer and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in snapshot creation and deletion please attach complete logs
of below containers.

- csi-snapshotter and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC mounting please attach complete logs of below containers.

- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
  plugin pod from the node where the mount is failing.

- if required attach dmesg logs.

**Note:-** If its a rbd issue please provide only rbd related logs, if its a
cephfs issue please provide cephfs logs.

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by Madhu-1** [comment]
Please use templates from release v2.1.2 branch not from master.

**Comment by nixpanic** [comment]
> Please use templates from release v2.1.2 branch not from master.

@jpsaneesh were you able to resolve the issue?

**Comment by jpsaneesh** [comment]
@Madhu-1 
Image quay.io/cephcsi/cephcsi:v2.1-canary worked for us in branch "release-v2.1".

I hope this docker image is stable?

**Comment by Madhu-1** [comment]
better to use `https://github.com/ceph/ceph-csi/tree/v2.1.2`  and `quay.io/cephcsi/cephcsi:v2.1.2`, closing this one as it works
