### ISSUE TITLE
 Add workload test: Velero

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1222]
# Describe the feature you'd like to have #

[Velero](https://velero.io) is a project that can work with CSI drivers. It is a straight forward workload that exercises many features of Ceph-CSI. In case a change breaks an external consumer like Velero, developers working on Ceph-CSI need to have a look at the cause and address it.

# What is the value to the end user? (why is it a priority?) #

Less chance on regressions for common consumers.

# How will we know we have a good solution? (acceptance criteria) #

There should be a CI job that runs the Velero smoke/happy-path tests regularly, possibly for each PR.

**Comment by Madhu-1** [comment]
ceph-csi upstream testing becomes heavy if we keep adding tests for the consumers. if we can validate the normal functional testing works fine from kubernetes point of view it should be fine I believe.

**Comment by nixpanic** [comment]
> ceph-csi upstream testing becomes heavy if we keep adding tests for the consumers. if we can validate the normal functional testing works fine from kubernetes point of view it should be fine I believe.

Although that is true, testing with real-world applications in addition to the expected-functionality tests is important. This is a little similar to adding tests like #250. We just do not know if functional tests are sufficiently complete. Proving functionality through workload (smoke/happy-path) tests gives better assurance that we do not break things.

**Comment by humblec** [comment]
> ceph-csi upstream testing becomes heavy if we keep adding tests for the consumers. if we can validate the normal functional testing works fine from kubernetes point of view it should be fine I believe.

agree. I am not in favor of adding tests for consumers in this repo or project. We should stick to the minimum app/workload e2e testing and that should be it.  As an extension to this, we could also add csi sanity tests to make sure we are in parity with the spec.

**Comment by nixpanic** [comment]
I think there should be real workload tests, and not only synthetic functional tests. We can run them nightly/weekly and not for every PR if that is preferable.

**Comment by humblec** [comment]
@nixpanic as an overall thought, may be we could close this?
