### ISSUE TITLE
Address goerr113 warnings 

### ISSUE THREAD

**Issue by Yuggupta27** [ceph/ceph-csi#1227]
`goerr113` is a golang linter to check the errors handling expressions.
It warns about using wrapped static errors in place of dynamic at multiple places.
Issue reported:  `err113: do not define dynamic errors, use wrapped static errors instead` 

Steps:
1. Enable `goerr113` linter from `scripts/golangci.yml.in` (if #1157 is merged)
2. Run `make containerized-test TARGET=go-lint`

# How will we know we have a good solution? (acceptance criteria) #

goerr133 doesn't report any more warnings.

Also, see : #1157

**Comment by humblec** [comment]
Isnt this already taken care @Yuggupta27

**Comment by Madhu-1** [comment]
This is not fixed, there is a todo present and it's currently disabled at   https://github.com/ceph/ceph-csi/blob/02b4a7175c4679466fdc6eab6674ef84525351ee/scripts/golangci.yml.in#L170

**Comment by humblec** [comment]
@Yuggupta27 can you please revisit this issue ? and take care pending items if any?

**Comment by yati1998** [comment]
enabling goerr113 from the e2e requires the addition of too many extra lines of code which is not required. To resolve this we need to create a type for all the errors individually. This doesn't seem to be the way to resolve this linter. Hence, disabling this linter, for now, will be a better idea.
Adding link to the PR with more detailed discussion: https://github.com/ceph/ceph-csi/pull/1977
