### ISSUE TITLE
Refactor deeply nested if statements

### ISSUE THREAD

**Issue by Yuggupta27** [ceph/ceph-csi#1229]
`nestif` reports deeply nested if statements in the codebase.
Issue reported: `... is deeply nested (complexity: X) (nestif)`

Steps:
1. Enable `nestif` linter from scripts/golangci.yml.in (if #1157  is merged)
2. Run `make containerized-test TARGET=go-lint`

# What is the value to the end user? (why is it a priority?) #
Improve understandability and reduce Cognitive Complexity.

# How will we know we have a good solution? (acceptance criteria) #
`nestif` linter does not show any more warnings.

# Additional context #

Works something like...
```
if condition1 { // total: 3
    if condition2 { // +1
    }
    if condition3 { // +1
    }
    if condition4 { // +1
    }
}
```

**Comment by humblec** [comment]
@Yuggupta27 isnt this taken care already?

**Comment by Madhu-1** [comment]
This is not fixed, there is a todo present and it's currently disabled at https://github.com/ceph/ceph-csi/blob/02b4a7175c4679466fdc6eab6674ef84525351ee/scripts/golangci.yml.in#L169

**Comment by humblec** [comment]
@Yuggupta27 can you revisit this?

**Comment by Yuggupta27** [comment]
@Rakshith-R is working on this now.
