### ISSUE TITLE
Provide secrets to the provisioner/nodeplugin pods directly, rather than rely on secrets via the CSI requests

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#1239]
Branching off from this comment: https://github.com/ceph/ceph-csi/issues/578#issuecomment-583501921

This issue to track specifically, the ability to provide the CSI pods with cluster secrets for use as below,

To overcome lack of secrets for any required solution in NodeUnstageVolume request, it is proposed that we can add secrets (name/namespace data) to the clusterID configuration, and read/watch said kubernetes secrets.

- This separates the secrets into their own namespaces (a requirement when different users administer the different ceph clusters), and needs required RBACs for pods in the CSI namespace to read the same
- Provides the secrets for all calls that CSI may want to make (now and in the future)
- Brings us closer to cloud provider implementations, where ability to access secrets by the CSI driver is assumed in such environments

Further as more RPCs are added (expand requests as an example) the StorageClass need not be recreated to add the said secret, rather secrets present with the CSI pods can be leveraged to perform the required operations.

**Comment by Madhu-1** [comment]
@ShyamsundarR Thanks for creating the issue. We need to do this enhancement to overcome some limitations. This is a good candidate for next release after 3.0.0

**Comment by humblec** [comment]
This enhancement also help to overcome some validation and failure in CSI driver to perform some operations. One example would be expansion of the PVs which does not carry the expansion secret..etc.

**Comment by Madhu-1** [comment]
Closing this one as we dont have any plan to support it now.
