### ISSUE TITLE
CephFS cloned volume size has to be explictly adjusted for the parent volume size.

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1254]
# Describe the bug #

The CephFS snapshot size is not reflected correctly and while cloning from this snapshot we have to adjust the size of the cloned volume by an explicit call to `resizeVolume` to be in parity with the parent volume. This issue track the same.
Refer# https://github.com/ceph/ceph-csi/pull/394#discussion_r457051688

**Comment by Madhu-1** [comment]
reopening as it still required with https://github.com/ceph/ceph-csi/pull/2730
