### ISSUE TITLE
Support Ceph msgr2 protocol

### ISSUE THREAD

**Issue by walkamongus** [ceph/ceph-csi#1258]
# Describe the feature you'd like to have #
Support msgr2 enabled communication

# What new functionality do you want?
The messenger v2 protocol supports a secure mode for encrypting all data passing over the network (as well as other benefits). User should be able to use the new msgr2 protocol and settings with the K8s Ceph drivers.

# What is the value to the end user? (why is it a priority?) #
All data would be encrypted over the network without end-users having to manage keys or per-volume encryption.

How would the end user gain value from having this feature?
Users could enable encryption-in-transit, gaining a good amount of security with very little effort.

# How will we know we have a good solution? (acceptance criteria) #
ceph-csi and associated drivers can establish msgr2-based client connections to ceph daemons

Add a list of criteria that should be met for this feature to be useful
msgr2 client connections can be made to ceph and msgr2 secure mode can be used

# Additional context #

https://docs.ceph.com/docs/master/rados/configuration/msgr2/

**Comment by dillaman** [comment]
Note that there is zero support for msgr2 in any Linux kernel at the moment.

**Comment by riccardo32** [comment]
Linux kernel  via rbd now has support  for this, will this now be extended to the CSI ?
https://docs.ceph.com/en/nautilus/man/8/rbd/#kernel-rbd-krbd-options

**Comment by Madhu-1** [comment]
> Linux kernel via rbd now has support for this, will this now be extended to the CSI ? https://docs.ceph.com/en/nautilus/man/8/rbd/#kernel-rbd-krbd-options

What extra support is required from cephcsi? if you specify the mon V2 IP:PORT in the cephcsi configmap cephcsi will use it to for communication with ceph.

**Comment by riccardo32** [comment]
We want to be able to set the ms_mode=secure option to encrypt data

**Comment by Madhu-1** [comment]
You can set the map option here https://github.com/ceph/ceph-csi/blob/4a1591236d80654a178bc3c127e6374d303f323a/examples/rbd/storageclass.yaml#L55. is this what you are looking for?

**Comment by riccardo32** [comment]
Great Thank you this works!! might be worth updating https://docs.ceph.com/en/latest/rbd/rbd-kubernetes/#configure-ceph-csi

thanks for the prompt assistance

**Comment by kub3let** [comment]
I defined my monitors with port 3000 but dmesg still shows libceph is using port 6789

This is a fresh install so port 6789 is never mentioned and seems to be automatically used by ceph

Is it the debian kernel not supporting it ? 

---

k3s v1.24.7
ceph csi v3.7.1
kernel: Debian 5.10.149-2 (2022-10-21) x86_64

ceph server: 17.2.4

```
root@worker2:/# dmesg -T
[Sun Oct 30 12:44:37 2022] libceph: mon1 (1)192.168.1.232:6789 session established
[Sun Oct 30 12:44:37 2022] libceph: mon1 (1)192.168.1.232:6789 socket closed (con state OPEN)
[Sun Oct 30 12:44:37 2022] libceph: mon1 (1)192.168.1.232:6789 session lost, hunting for new mon
[Sun Oct 30 12:44:37 2022] libceph: mon2 (1)192.168.1.233:6789 session established
[Sun Oct 30 12:44:37 2022] libceph: client2926138 fsid 2b24beff-c31f-43b0-b0f5-c0f4fb32ea37
[Sun Oct 30 12:44:37 2022] rbd: rbd0: capacity 34359738368 features 0x1
```

```
root@master1:/# kubectl describe -n ceph-csi-rbd configmaps/ceph-csi-config
Name:         ceph-csi-config
Namespace:    ceph-csi-rbd
Labels:       app=ceph-csi-rbd
              app.kubernetes.io/managed-by=Helm
              chart=ceph-csi-rbd-3.7.1
              component=nodeplugin
              heritage=Helm
              release=ceph-csi
Annotations:  meta.helm.sh/release-name: ceph-csi
              meta.helm.sh/release-namespace: ceph-csi-rbd

Data
====
cluster-mapping.json:
----
[]
config.json:
----
[{"clusterID":"2b24beff-c31f-43b0-b0f5-c0f4fb32ea37","monitors":["192.168.1.231:3300","192.168.1.232:3300","192.168.1.233:3300"]}]

BinaryData
====

Events:  <none>
```

**Comment by sshambar** [comment]
How to configure for msgr2 should really be documented, but as a reference for others this worked for me in my csi-config-map config.json:
`"monitors": [  "<mon1-ip>:3300", "<mon2-ip>:3300",  "<mon3-ip>:3300" ],
  "cephFS": { "kernelMountOptions": "ms_mode=secure" }                                                             
`
