### ISSUE TITLE
RBD: implement rbd.updateVolWithImageInfo() with go-ceph

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1260]
# Describe the feature you'd like to have #

`updateVolWithImageInfo()` is currently executing an `rbd` command to get details about an RBD image.

Fetching the needed timestamps it not possible with a released version of go-ceph yet, PR ceph/go-ceph#310 is only available in the master branch.

Once go-ceph v0.5 has been released, this issue can get addressed.

**Comment by agarwal-mudit** [comment]
Please assign to me if no one has planned yet to work on it.
