### ISSUE TITLE
cephfs: pvc mount fails after csi upgrade

### ISSUE THREAD

**Issue by Yuggupta27** [ceph/ceph-csi#1261]
# Describe the bug #

A PVC created in CSI v2.0.0 is unable to get mounted after upgrading to the latest release.

# Steps to reproduce #

1. Create a pvc in v2.0.0
1. upgrade to master
1. Bind the existing pvc to a pod.

# Actual results #
```
FailedMount: Unable to attach or mount volumes: unmounted volumes=[mypvc], unattached volumes=[mypvc default-token-2f2g4]: timed out waiting for the condition
```
# Expected behavior #

The pvc gets bound seamlessly.

# Logs #

cephfs plugin logs: https://termbin.com/z8wm
cephfs attacher logs: https://termbin.com/wtt0

# Additional context #

Also see: https://github.com/ceph/ceph-csi/pull/1243

**Comment by Yuggupta27** [comment]
The Default Subvolumegroup name is `csi` in v2.0.0 and `e2e` now for the end to end testing.

**Comment by Madhu-1** [comment]
This is really good Catch Thanks for catching this one, or else we would have introduced a regression for subvolumes groups

**Comment by Madhu-1** [comment]
This issue exists for Expand or Deleting the older PVC,

**Comment by Madhu-1** [comment]
CC @madddi The subvolumegroup is not backward compatible after upgrading the ceph-csi to lastest version if the user updates the current configmap with subvolume group name

**Comment by Madhu-1** [comment]
This won't be a regression, This is working properly and we need to document that the user should not update the information for the current clusterID. for the clusterID which are used by the ceph-csi driver(<3.0.0 which is master) the subvolume should remain as it is, **we just need to document it in upgrade procedure and also we need to extend the documentation on how to configure a subvolume**, we should mention that the user **shouldnot/never** update the clusterID configuration(for subvolumegoup name) he should always create a new one.

**Comment by Madhu-1** [comment]
@Yuggupta27 can you please take care of it in your E2E upgrade testing. and also please send a documentation update for this one.

**Comment by Yuggupta27** [comment]
> @Yuggupta27 can you please take care of it in your E2E upgrade testing. and also please send a documentation update for this one.

Sure. I'll do that. Thanks for looking into it.

**Comment by humblec** [comment]
@Yuggupta27 isnt this solved already ?

**Comment by Madhu-1** [comment]
This is not fixed yet, we need to update the documentation
