### ISSUE TITLE
Ceph Mimic is deprecated, no need to support it with Ceph-CSI v3.x

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1264]
Mimic has been retired as of today:
- https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/X5IUICDEM4IVVWTMUTSSNEU424MB6WL7/
- https://ceph.io/releases/mimic-is-retired/

There should be no need to test the upcoming Ceph-CSI v3 releases with Mimic anymore. Users that have not migrated from Mimic to Nautilus or Octopus can use older Ceph-CSI releases (v2.x is still maintained) until they upgraded their Ceph cluster.

Note that Mimic has been part of the CI during the majority of the Ceph-CSI v3 development cycle, so it most likely will still function as expected. However the Ceph version will be removed from the CI, so developers are not notified about any breakage any longer.

Changes required:
- [ ] documentation update
- [ ] drop Mimic from the CI

**Comment by Madhu-1** [comment]
@dillaman @kotreshhr @ShyamsundarR @travisn can you get an ack from core side to deprecate the support for Mimic

**Comment by dillaman** [comment]
> can you get an ack from core side to deprecate the support for Mimic

@Madhu-1 I am not sure I understand what you are asking for

**Comment by Madhu-1** [comment]
> > can you get an ack from core side to deprecate the support for Mimic
> 
> @Madhu-1 I am not sure I understand what you are asking for

just checking with you guys is it good to remove Mimic support from ceph-csi v3.0.0(we need to update README for the same) as Mimic is deprecated in ceph

**Comment by travisn** [comment]
@Madhu-1 Rook already removed support for mimic in v1.3, so it's fine from Rook's perspective.

**Comment by dillaman** [comment]
@Madhu-1 Yup -- sounds good to me.
