### ISSUE TITLE
implement CephFS volume management with go-ceph

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1265]
CephFS provisioning and other volume management operations call out to the `ceph` executable. To enhance performance, it is desired to rewrite these functions to use go-ceph instead.

PRs that implement a function with go-ceph, should add `Updates: #1265` to the comment so that tracking progress is easy.

**Comment by nixpanic** [comment]
@phlogistonjohn is this something you want to take on? Or, at least pass pointers to how the JSON commands need to be structured?

**Comment by phlogistonjohn** [comment]
I am interested in this topic, yes.  I had previously meant to do more in this area but my time has been consumed with other (non-ceph-csi) topics.

**Comment by nixpanic** [comment]
I'm proposing this for the 3.1 release (no due date at the moment).

**Comment by agarwal-mudit** [comment]
Happy to participate in this if required.

**Comment by nixpanic** [comment]
Current `ceph fs` commands that need replacing:
- `getFscID()` calls `ceph fs get myfs` to get the ID of the filesystem
- `getMetadataPool()` calls `ceph fs ls` and filters on the name of the filesystem to return the metadata-pool
- `getFsName()` calls `ceph fs dump` to convert a filesystem-ID to the name of the filesystem
- `getVolumeRootPathCeph()` calls `ceph fs subvolume getpath <fs-name> <fs-id> --group_name <subvol-group>`
- `createVolume()` calls `ceph fs subvolumegroup create <fs-name> <subvol-group>` and `ceph fs subvolume create <fs-name> <fs-id> <quota> --group_name <subvol-group> --mode 777`
- `resizeVolume()` calls `ceph fs subvolume resize <fs-name> <fs-id> <quota>`
- `purgeVolume()` calls `ceph fs subvolume rm <fs-name> <fs-id> --group_name <subvol-group>`

In addition to replacing these commands with a go-ceph equivalent, it will be needed to use `util.ClusterConnection` to connect to the Ceph cluster. With that the connection cache/pool is utilized so that each function does not need to connect from the start.

**Comment by Madhu-1** [comment]
you may need to add snapshot, clone and restore commands also.

**Comment by humblec** [comment]
> you may need to add snapshot, clone and restore commands also.

Yeah, we need to add ceph fs snapshot and clone commands to complete the list.

**Comment by Madhu-1** [comment]
@nixpanic @phlogistonjohn can this be done in 3.1.0? or do we need to move it out to the next release?

**Comment by phlogistonjohn** [comment]
I'm sorry that I don't follow ceph-cis's release process well enough to to know when that is expected. If you gave an estimated date I can suggest if that falls before or after the first go-ceph release that is expected to have the new cephfs admin package.

**Comment by Madhu-1** [comment]
Thanks for the update @phlogistonjohn , had a discussion with @nixpanic in todays meeting will be moving this for next release.

**Comment by Madhu-1** [comment]
@nixpanic anything pending here?

**Comment by nixpanic** [comment]
This is all done!
