### ISSUE TITLE
RBD: implement volume resizing with go-ceph

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1269]
The `resizeRBDimage()` function (to be renamed to `rbdVolume.resize()`) still calls out to the `rbd` command. go-ceph supports image resizing, so that should be used instead.

**Comment by agarwal-mudit** [comment]
@nixpanic I can pick it up

**Comment by nixpanic** [comment]
This can be worked on once #1262 has been merged (contains the rename of `resizeRBDimage()` to `rbdVolume.resize()`).

**Comment by nixpanic** [comment]
#1262 has been merged. The `rbdVolume.resize()` function can now be implemented with go-ceph.

While doing so, it is probably a good idea  to pass the new size as a parameter to the `resize(newSize)` function, instead of updating the member of the `rbdVolume` object and hoping that resize does not return an error. After successful resize the  `resize()` method should update the member of the object, of course.
