### ISSUE TITLE
Release 3.1.0 of Ceph CSI Driver

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1272]
- [x] **Define release process**
  - Release doc would be a good start
- [x] **Define release deadlines**
  - Code Freeze : 08-Aug-2020
  - RC : 10-Aug-2020
  - GA : 12-Aug-2020

- [x] **Define/list roadmap for v3.1.0**
  - Proposed contents for v3.1.0 release
  - The release blockers (issues/PRs) are attached to [the `release-3.1.0` milestone](https://github.com/ceph/ceph-csi/milestone/6)

- [x] Snapshot/Cloning support for CephFS. ( For further details refer https://github.com/ceph/ceph-csi/pull/394#issuecomment-663356855)    #394 
- Snapshot creation/deletion (:+1: ) : Status: Done
- Restore snapshot to a new PV ( :+1: ): Status: Done
- Cloning PVC from PVC( :+1: ) : Status : Done

- [x] Add RADOS namespace support to RBD plugin
- #1035 :+1:  Status: Ready to Merge
 
 - [x] Enablement of CentOS CI
- CentOS  CI enablement for E2E (  :+1: ) : Status : Done
- CentOS CI enablement for conternarized tests(  :+1: ) : Status : Done
- CentOS CI enablement for helm deployment(  :+1: ) : Status : Done

 - [x] Consumption of latest Rook Release 1.4 ? 

 
  
  
- [x] **Release Team**:
 @Madhu-1
 @humblec 

- [x] **Document features and announce the release.**

**Comment by humblec** [comment]
[update]
On track for GA on 12-Aug-2020.

**Comment by Madhu-1** [comment]
closing this one as the release is available https://github.com/ceph/ceph-csi/releases/tag/v3.1.0
