### ISSUE TITLE
Volumes are not deleted

### ISSUE THREAD

**Issue by karibertils** [ceph/ceph-csi#1284]
# Describe the bug #

Volumes are not deleted

# Environment details #

- Image/version of Ceph CSI driver : v3.0.0
- Helm chart version : v3.0.0
- Kernel version for ceph cluster : 5.4.44 
- Kernel version for kubernetes cluster : 5.4.19
- Mounter used for mounting PVC: krbd
- Kubernetes cluster version : 1.18.6-00
- Ceph cluster version : 15.2.4

# Steps to reproduce #

1. Create pvc.yaml
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rbd
```

2. kubectl apply -f pvc.yaml

2. Verify volume was created and bound: kubectl get pvc
```
NAME       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-test   Bound    pvc-a02951dd-f2a7-40be-8a10-17c96b4d0477   1Gi        RWO            rbd            2s
```

3. kubectl delete pvc pvc-test

4. Verify rbd volume has not been deleted with: rbd ls pool

# Actual results #

Volume is not deleted

# Expected behavior #

I expected the volume to be deleted

# Logs #

[Logs for csi-provisioner and csi-rbdplugin](https://github.com/ceph/ceph-csi/files/4982456/volume_delete_failure.txt)

# Additional context #

Running on brand new kubernetes cluster installed with kubeadm on debian vms.
Ceph is running with cephx disabled for performance reasons. I saw there is no option to skip the secret and am using secret with the admin keyring from before i disabled cephx.

Running the rbd command that fails in the logs works fine on the ceph nodes.
```
$ rbd -m 192.168.0.1,192.168.0.2,192.168.0.3 --id admin --keyfile=admin.keyring -c /etc/ceph/ceph.conf --format=json info kube/csi-vol-151e7bb5-d017-11ea-80e0-8603e2110b8f
{"name":"csi-vol-151e7bb5-d017-11ea-80e0-8603e2110b8f","id":"5d9b2d0adc6f0a","size":1073741824,"objects":256,"order":22,"object_size":4194304,"snapshot_count":0,"block_name_prefix":"rbd_data.5d9b2d0adc6f0a","format":2,"features":["layering"],"op_features":[],"flags":[],"create_timestamp":"Mon Jul 27 14:40:15 2020","access_timestamp":"Mon Jul 27 14:40:15 2020","modify_timestamp":"Mon Jul 27 14:40:15 2020"}
```

**Comment by Madhu-1** [comment]
>[ceph-csi-rbd-provisioner-dfd44c7b6-vcl5n csi-rbdplugin] E0727 14:00:27.108080       1 rbd_util.go:885] failed getting information for image (kube/csi-vol-7fc00d7b-d011-11ea-a9ed-56fa30a5bd9f): (an error (exit status 95) occurred while running rbd args: [-m 192.168.0.1,192.168.0.2,192.168.0.3 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf --format=json info kube/csi-vol-7fc00d7b-d011-11ea-a9ed-56fa30a5bd9f]) 

for the logs the rbd image info is failing. can you please execute same command from the  csi-rbdplugin container of provisioner pod?

**Comment by karibertils** [comment]
Just tried it and I got:
```
2020-07-30T12:35:45.433+0000 7f005d8dd700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [1] but i only support [2]
```

I then did sed -i 's/cephx/none/g' /etc/ceph/ceph.conf inside the container so the file looks like this:
```
[global]
auth_cluster_required = none
auth_service_required = none
auth_client_required = none
```

The previous command worked afterwards and all the stale volumes were deleted immediately.

So this clearly happens because i am running deployment with disabled cephx even though the plugin is able to create and mount the volumes successfully.

Performance tuning guides recommend disabling cephx to maximize IOPS on pure flash deployments when network is protected. And I saw a great increase in IOPS and lower CPU usage after disabling cephx so i think it's a valid use case that should be supported ?

**Comment by Madhu-1** [comment]
currently, this use-case is not supported as ceph-csi. please open a feature request so that we can have more discussions
