### ISSUE TITLE
Unable to mount PVC using nodeplugin v3.0.0

### ISSUE THREAD

**Issue by fad3t** [ceph/ceph-csi#1293]
Hello all,

I have installed the Ceph CSI plugin using the Helm chart. I was able to create a PVC however my pod is unable to mount it.
I've noticed that switching to the `cephcsi:canary` image resolves the issue (the Helm chart uses `v3.0.0` by default).

# Environment details #

- Image/version of Ceph CSI driver : `cephcsi:v3.0.0`
- Helm chart version : `latest`
- Kernel version : `3.10.0-957.10.1.el7.x86_64`
- Mounter used for mounting PVC: unsure
- Kubernetes cluster version : `1.18.6`
- Ceph cluster version : `14`

# Steps to reproduce #

* Install the CSI plugin using the latest Helm chart (with PSP enabled).
* Deploy the resources (`secret`, `storageclass`, `pvc` and `pvc`) from the example directory.

# Actual results #

The PVC is successfully created, however the pod cannot mount it.

# Expected behavior #

The pod should be able to mount the PVC.

# Logs #
```
I0729 09:37:59.135747   73544 utils.go:160] ID: 18 GRPC request: {}
I0729 09:37:59.138122   73544 utils.go:165] ID: 18 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}}]}
I0729 09:37:59.149231   73544 utils.go:159] ID: 19 Req-ID: 0001-0024-33b747ab-e357-445f-b30d-b667a18b4392-000000000000000e-4a926342-d176-11ea-9907-0218dcc4339f GRPC call: /csi.v1.Node/NodeStageVolume
I0729 09:37:59.152043   73544 utils.go:160] ID: 19 Req-ID: 0001-0024-33b747ab-e357-445f-b30d-b667a18b4392-000000000000000e-4a926342-d176-11ea-9907-0218dcc4339f GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-630c6163-b1dd-4d84-8dbf-5516377dc507/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["discard"]}},"access_mode":{"mode":1}},"volume_context":{"clusterID":"33b747ab-e357-445f-b30d-b667a18b4392","imageName":"csi-vol-4a926342-d176-11ea-9907-0218dcc4339f","journalPool":"rbd_k8s_rancher","pool":"rbd_k8s_rancher","storage.kubernetes.io/csiProvisionerIdentity":"1595965171867-8081-rbd.csi.ceph.com"},"volume_id":"0001-0024-33b747ab-e357-445f-b30d-b667a18b4392-000000000000000e-4a926342-d176-11ea-9907-0218dcc4339f"}
I0729 09:37:59.152287   73544 rbd_util.go:722] ID: 19 Req-ID: 0001-0024-33b747ab-e357-445f-b30d-b667a18b4392-000000000000000e-4a926342-d176-11ea-9907-0218dcc4339f setting disableInUseChecks on rbd volume to: false
I0729 09:37:59.153600   73544 omap.go:74] ID: 19 Req-ID: 0001-0024-33b747ab-e357-445f-b30d-b667a18b4392-000000000000000e-4a926342-d176-11ea-9907-0218dcc4339f got omap values: (pool="rbd_k8s_rancher", namespace="", name="csi.volume.4a926342-d176-11ea-9907-0218dcc4339f"): map[csi.imageid:45f926e0e158e csi.imagename:csi-vol-4a926342-d176-11ea-9907-0218dcc4339f csi.volname:pvc-630c6163-b1dd-4d84-8dbf-5516377dc507]
E0729 09:37:59.153952   73544 util.go:236] kernel 3.10.0-957.10.1.el7.x86_64 does not support required features
I0729 09:37:59.247300   73544 rbd_util.go:304] ID: 19 Req-ID: 0001-0024-33b747ab-e357-445f-b30d-b667a18b4392-000000000000000e-4a926342-d176-11ea-9907-0218dcc4339f executing [rbd task add flatten rbd_k8s_rancher/csi-vol-4a926342-d176-11ea-9907-0218dcc4339f --id k8s_rancher --keyfile=/tmp/csi/keys/keyfile-957865034 -m 10.244.246.196:3300,10.244.246.197:3300,10.244.246.198:3300] for image (csi-vol-4a926342-d176-11ea-9907-0218dcc4339f) using mon 10.244.246.196:3300,10.244.246.197:3300,10.244.246.198:3300, pool rbd_k8s_rancher
I0729 09:37:59.671929   73544 cephcmds.go:54] ID: 19 Req-ID: 0001-0024-33b747ab-e357-445f-b30d-b667a18b4392-000000000000000e-4a926342-d176-11ea-9907-0218dcc4339f an error (exit status 2) occurred while running ceph args: [rbd task add flatten rbd_k8s_rancher/csi-vol-4a926342-d176-11ea-9907-0218dcc4339f --id k8s_rancher --keyfile=***stripped*** -m 10.244.246.196:3300,10.244.246.197:3300,10.244.246.198:3300]
W0729 09:37:59.671955   73544 rbd_util.go:318] ID: 19 Req-ID: 0001-0024-33b747ab-e357-445f-b30d-b667a18b4392-000000000000000e-4a926342-d176-11ea-9907-0218dcc4339f uncaught error while scheduling a task: an error (exit status 2) occurred while running ceph args: [rbd task add flatten rbd_k8s_rancher/csi-vol-4a926342-d176-11ea-9907-0218dcc4339f --id k8s_rancher --keyfile=***stripped*** -m 10.244.246.196:3300,10.244.246.197:3300,10.244.246.198:3300]
E0729 09:37:59.671966   73544 rbd_util.go:452] ID: 19 Req-ID: 0001-0024-33b747ab-e357-445f-b30d-b667a18b4392-000000000000000e-4a926342-d176-11ea-9907-0218dcc4339f failed to add task flatten for rbd_k8s_rancher/csi-vol-4a926342-d176-11ea-9907-0218dcc4339f : an error (exit status 2) occurred while running ceph args: [rbd task add flatten rbd_k8s_rancher/csi-vol-4a926342-d176-11ea-9907-0218dcc4339f --id k8s_rancher --keyfile=***stripped*** -m 10.244.246.196:3300,10.244.246.197:3300,10.244.246.198:3300]
E0729 09:37:59.672084   73544 utils.go:163] ID: 19 Req-ID: 0001-0024-33b747ab-e357-445f-b30d-b667a18b4392-000000000000000e-4a926342-d176-11ea-9907-0218dcc4339f GRPC error: rpc error: code = Internal desc = an error (exit status 2) occurred while running ceph args: [rbd task add flatten rbd_k8s_rancher/csi-vol-4a926342-d176-11ea-9907-0218dcc4339f --id k8s_rancher --keyfile=***stripped*** -m 10.244.246.196:3300,10.244.246.197:3300,10.244.246.198:3300]
I0729 09:38:15.249855   73544 utils.go:159] ID: 20 GRPC call: /csi.v1.Identity/Probe
I0729 09:38:15.250340   73544 utils.go:160] ID: 20 GRPC request: {}
I0729 09:38:15.250767   73544 utils.go:165] ID: 20 GRPC response: {}
```

# Additional context #

Mounting of the PVC works when the nodeplugin image tag (`nodeplugin.plugin.image.tag`) is explicitly set to `canary`.

**Comment by Madhu-1** [comment]
@fad3t there is no code changes when compare to canary and v3.0.0 can you please provide rbd info of the image?

**Comment by Madhu-1** [comment]
and also please provide ceph user caps

**Comment by fad3t** [comment]
Hi @Madhu-1,

I'll ask about the rbd info -- I'm not admin of the Ceph cluster.
Regarding the caps, is this enough?
`ceph auth get-or-create client.k8s_rancher mon 'profile rbd' osd 'profile rbd pool=rbd_k8s_rancher' mgr 'profile rbd pool=rbd_k8s_rancher'`

Note that it is working with this user (and the same RBD image) when using the canary tag, but also when using the native Kubernetes RBD provisioner (kubernetes.io/rbd) so permissions should be OK there.

Thanks,
Fred.

**Comment by Madhu-1** [comment]
> Hi @Madhu-1,
> 
> I'll ask about the rbd info -- I'm not admin of the Ceph cluster.
> Regarding the caps, is this enough?
> `ceph auth get-or-create client.k8s_rancher mon 'profile rbd' osd 'profile rbd pool=rbd_k8s_rancher' mgr 'profile rbd pool=rbd_k8s_rancher'`
> 
> Note that it is working with this user (and the same RBD image) when using the canary tag, but also when using the native Kubernetes RBD provisioner (kubernetes.io/rbd) so permissions should be OK there.
> 
> Thanks,
> Fred.

caps looks good. lets get the image info and see( the flattening task will be started only if the image has the deep flatten feature)

**Comment by Madhu-1** [comment]
@Yuggupta27 can you please try to reproduce this one and see?

**Comment by fad3t** [comment]
Indeed, I re-did the whole setup again - using image tag v3.0.0 - and everything is OK.

I noticed that using the StorageClass manifest from the doc (https://docs.ceph.com/docs/master/rbd/rbd-kubernetes/) is causing the issue. There are a few differences with the StorageClass manifest from the examples directory:
* `csi.storage.k8s.io/controller-expand-secret-name` is not set
* `csi.storage.k8s.io/controller-expand-secret-namespace` is not set
* `csi.storage.k8s.io/fstype` is not set (although default is supposed to be `ext4`)
* `imageFeatures` is not set
* `allowVolumeExpansion` is not set

Any idea which one could be causing the issue? I could test them one by one but that'd take some time :P

**Comment by Madhu-1** [comment]
Yeah if you don't mention the imageFeatues in some version the mounting fails. closing  this one,  Thanks for the confirmation
