### ISSUE TITLE
ceph mon list doc

### ISSUE THREAD

**Issue by kfox1111** [ceph/ceph-csi#13]
The ceph mon list is currently included in every pv created. This can be annoying to fix if you add a new mon and remove an old mon but don't maintain the old ip's.

Feature request: allow specifying a configmap (or crd) instead of a mon list. This document will have the list of mons in it. This will allow much more easily switching mons out as you will only have to go to one place to do so.

**Comment by rootfs** [comment]
@kfox1111 alternatively, if you have DNS entries for your mon hosts, you can use the hostnames
also see https://github.com/kubernetes-incubator/external-storage/pull/537

**Comment by kfox1111** [comment]
That does help. But wouldn't address scaling a mon cluster from 3 to 5 for example.

**Comment by sbezverk** [comment]
@kfox1111 if you use a single dns name entry for your monitors, would it not do round-robin between ip addresses of your monitors  as a result helping in scaling?

**Comment by kfox1111** [comment]
I have never seen a ceph.conf configured in that way before. No idea if it would work or not. Typically though I've seen ceph used in environments so low level and detached that dns isn't used at all for it. Like, your dns infra might be hosted out of ceph, so you don't use it to configure ceph.

**Comment by sbezverk** [comment]
@kfox1111 good point about dns, there is a definitely assumption (right or wrong not sure) that there is dns service available.

**Comment by kfox1111** [comment]
With it in its own crd, it would be easy to make a little ceph watcher deployment that asks ceph what its current mons are and keeps the crd up to date.

**Comment by sbezverk** [comment]
@kfox1111 if you can formulate a more detailed proposal, I would be happy to work with you to program it.

**Comment by sbezverk** [comment]
@kfox1111 @rootfs Please correct me if I ma wrong, but I think all these problems (need for ceph cluster specific info) will go away if we build native rbd-go api library. In this case things like monitors and other ceph cluster specific info will not be needed. All a client would need is api endpoint and credentials.
If you agree that this approach is more efficient, then maybe we do not need dns/monitor change as it does not cover ALL possible cases, maybe it would be worth investing time in api client library?

**Comment by kfox1111** [comment]
still gotta feed the rbd-go library a mon list I believe?

**Comment by sbezverk** [comment]
@kfox1111 I am not sure, what I find strange is that I do not see user credentials being passed in API calls, it seems API server uses credentials which it was started with to run client's request. I hope I am missing something.

**Comment by dillaman** [comment]
rbd-go depends upon rados-go -- so you would provide all those details to the rados-go API prior to attempting the connection. I think the rados-go API needs a little bit of extra fleshing out in order to cleanly provide the monitor IP list and keyring, but you technically should be able to do that w/ the existing API via ```SetConfigOption``` prior to issuing a ```Connect```

**Comment by dillaman** [comment]
... the monitors can be set via ```mon_host``` config option [1] and the key can be set via the ```key``` config option [2].

[1] https://github.com/ceph/ceph/blob/v12.2.2/src/common/options.cc#L192
[2] https://github.com/ceph/ceph/blob/v12.2.2/src/common/options.cc#L538

**Comment by ShyamsundarR** [comment]
This issue is now resolved using a [config map](https://github.com/ceph/ceph-csi/blob/master/examples/README.md#creating-csi-configuration) provided to the CSI plugin that can take the required monitor information and also be used to keep it updated.

Closing this based on the provided details as above.
