### ISSUE TITLE
redeploy ceph-csi error

### ISSUE THREAD

**Issue by HackerDotCN** [ceph/ceph-csi#1334]
# Describe the bug #

I deploy the cephfs csi plugin as the instruction, then create storageclass/pvc/pod, all is normal.
but when I delete the resource to redeploy them, then comes the following error: 
`  Warning  Failed     39m                   kubelet, k8s-robin-rancher-1-1f0b05347-6  Error: failed to start container "csi-cephfsplugin": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/var/lib/kubelet/pods/e0978b0d-7b3e-4956-b2ba-0b9fa5ad09fc/containers/csi-cephfsplugin/011135c2\\\" to rootfs \\\"/data/docker_overlay/overlay/e944fc26edcfc392bdef80e30ba5b36e2125406cde883d650425aa0ec5f479ec/merged\\\" at \\\"/data/docker_overlay/overlay/e944fc26edcfc392bdef80e30ba5b36e2125406cde883d650425aa0ec5f479ec/merged/dev/termination-log\\\" caused \\\"no such file or directory\\\"\""
`

# Environment details #

- Image/version of Ceph CSI driver : 2.1
- Kernel version : 3.10.0-957.el7.x86_64
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : cephfs kernal
- Kubernetes cluster version : v1.17.4
- Ceph cluster version : 14.2.9

# Steps to reproduce #

purge and redeploy the csi plugin can definitely reproduce

**Comment by Madhu-1** [comment]
@HackerDotCN have you used helm or kubernetes templates?

**Comment by HackerDotCN** [comment]
> @HackerDotCN have you used helm or kubernetes templates?

I used the k8s template by the plugin-deploy.sh in the example folder

**Comment by Madhu-1** [comment]
@Yuggupta27 can you please try to reproduce this one?

**Comment by Madhu-1** [comment]
AFAIK this is not an issue with ceph-csi rather looks to be an issue in kubernetes cluster but let @Yuggupta27 confirm

**Comment by Yuggupta27** [comment]
Hi @HackerDotCN , I tried to reproduce this issue locally using the ceph-csi version v2.1.1. As the steps mentioned by you to reproduce, redeploying the driver again does not raise any red flags for me locally.

**Comment by Madhu-1** [comment]
> Hi @HackerDotCN , I tried to reproduce this issue locally using the ceph-csi version v2.1.1. As the steps mentioned by you to reproduce, redeploying the driver again does not raise any red flags for me locally.

Thanks for trying to reproduce @Yuggupta27 , @HackerDotCN looks to be an issue on kubernetes side, please check

**Comment by Yuggupta27** [comment]
As @Madhu-1 mentioned, the issue doesn't seem to be from ceph-csi side to me too. Let me know if we can help you with anything else :)

**Comment by Madhu-1** [comment]
closing this one as its not an issue from ceph-csi side
