### ISSUE TITLE
Accomodate `--retain-snaps` and `auto-protect` functionalities to CephFS CSI snapshot operations.

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1338]
# Describe the bug #

There were some good enhancements in CephFS ( :+1: ) recently to support snapshot and clone workflow.

Decoupling of snapshot from parent subvol: https://github.com/ceph/ceph/pull/35647

Protect and unprotect deprecation : https://github.com/ceph/ceph/pull/35755

As part of the decoupling work of snapshot and parent sub volume, and deprecation of protect and unprotect, couple of new flags has been added to the subvolume management. 

For ex: `--retain-snaps` flag and an additional feature `autoproect`...etc.

We have to accommodate these changes here in this repo so that we are in parity with upstream cephfs and moving along. The current code wont break but we should consume this for smooth operation snapshot managment. 

Cc @ShyamsundarR

**Comment by humblec** [comment]
https://docs.ceph.com/docs/master/cephfs/fs-volumes/ 

So we have to make use of `features` field in subvol info and operate accordingly.

**Comment by humblec** [comment]
As discussed last week , I am assigning to you @agarwal-mudit

**Comment by agarwal-mudit** [comment]
Hi @ShyamsundarR,

Just a couple of questions for clarification:

-  --retain-snaps is a flag while auto-protect is a subvolume feature?
- Both should be used while creating a subvolume not later or before?
- What about the existing subvolumes, pardon me if that is already discussed 

If we already have a pvc based on subvolume which was not created using these feature/flag then we have a problem.
And, because of such cases we can't remove protect/unprotect completely but have to add check and call protect/unprotect
only for such vols which were not created using these feature/flag.
 
And I guess retain-snaps shouldn't be a big problem in such case because if there is a volume without the --retain-snaps flag, worst case we won't be able to delete it without deleting the snapshots. And we can document the same.

Please correct me if I am wrong or if I have missed anything relevant here.

**Comment by Madhu-1** [comment]
What is the minimum required ceph version for this one?

the changes we do should be backward compatible for older volumes (we should be able to do all operation on older subvolumes and snapshots)

**Comment by agarwal-mudit** [comment]
@ShyamsundarR 
I just realized that --retain-snaps needs to be provided while deleting a subvolume not while creating it, so in that case will it work with a subvolume which was created in a release where this feature was not present?

**Comment by Yuggupta27** [comment]
Afaik, the user will not be able to ` --retain-snapshots` on subvolume removal of older subvolumes. Also, If snapshots are not present, the subvolume can be automatically upgraded.

**Comment by Yuggupta27** [comment]
Though, v1 subvolumes with snapshots, are not upgraded.

**Comment by Yuggupta27** [comment]
Hi @ShyamsundarR , which Octopus release has the snapshot retention feature? Rook `1.4.2` uses Ceph `15.2.4` where I couldn't test the same.

**Comment by ShyamsundarR** [comment]
> Hi @ShyamsundarR,
> 
> Just a couple of questions for clarification:
> 
>     * --retain-snaps is a flag while auto-protect is a subvolume feature?

Yes

> 
>     * Both should be used while creating a subvolume not later or before?

As answered later, the --retain-snapshots is to be used while deleting a subvolume, the auto-protection is a feature of the subvolume, based on the version of Ceph in use.

> 
>     * What about the existing subvolumes, pardon me if that is already discussed

For existing subvolumes (again as covered in later comments), if the features state `snapshot-retention` then removal of the subvolume retaining snapshots is possible. IOW, this is another feature of the subvolume based on its version.

If v1 subvolumes were created, and already have snapshots, then these will not be auto upgraded to v2 subvolumes (which provide the `snapshot-retention` feature).

> 
> 
> If we already have a pvc based on subvolume which was not created using these feature/flag then we have a problem.
> And, because of such cases we can't remove protect/unprotect completely but have to add check and call protect/unprotect
> only for such vols which were not created using these feature/flag.

Yes

> 
> And I guess retain-snaps shouldn't be a big problem in such case because if there is a volume without the --retain-snaps flag, worst case we won't be able to delete it without deleting the snapshots. And we can document the same.

Yes

> 
> Please correct me if I am wrong or if I have missed anything relevant here.
> 
> cc @Yuggupta27

So here is how I would look at it,
- Snapshot retention and auto-protect/unprotect are not related features
- Snapshot protect/unprotect can be dropped if the subvolume features contain `snapshot-autoprotect`
- Snapshots can be retained (via --retain-snapshots option while removing a subvolume) if the features contain `snapshot-retention`
- Subvolume features are fetched using the `ceph fs subvolume info <vol_name> <subvol_name> [--group_name <subvol_group_name>]` command
  - For older Ceph versions where 'features' was not returned in the info output, it is assumed that these do not support any of the above features (IOW, protect/unprotect is required, and volumes cannot be deleted if snapshots are present)
  - For Ceph versions that do return the `features` information in the info output, it can be used to determine which features (as above) are supported and hence can be leveraged appropriately
