### ISSUE TITLE
Release 3.3.0 ( Planning Doc) 

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1340]
# Describe the feature you'd like to have #

The idea here is to capture the `wishlist` from  Ceph CSI community which they would like to see in this release. We could capture this in a google doc or in form of comments on the issue. However the format should not be a blocker for capturing this info, thus tracking it for the next release. 

[update] Wish list:
https://hackmd.io/8OqCr1mrTMGtBcJ7XNdDBg

Additionally having a `planning call` for an upcoming release would help the users to discuss about the use case and priority for a feature.

# What is the value to the end user? (why is it a priority?) #

User get a chance to come up with their own `wishlist` for the upcoming release. It will also help the CSI community to do some planning based on the priority, owning the features , driving to the release ..etc. 

We could also rotate the responsibilities among the community for various release tasks.

@ShyamsundarR @Madhu-1 @nixpanic @Yuggupta27 @phlogistonjohn @agarwal-mudit inviting you for the thoughts , suggestions..etc.

**Comment by 0x4139** [comment]
I think it would be nice to have:

-  Updated docs, at this moment some pieces of getting up and running with `ceph-csi` are not complete and might cause confusion 
- A helm chart maybe, that will work with external clusters while just setting `clusterid, monitors, pool, and client data`
- A comparison of why would one opt in for `ceph-csi` instead of the old `ceph-rbd` provisioner

**Comment by msfrucht** [comment]
Speaking of documentation. A table of the meaning of the elements of values.yaml table would be ideal. Seen that in a lot of other helm charts. As well as an example of volume resizing would be helpful.

As for:

> A helm chart maybe, that will work with external clusters while just setting clusterid, monitors, pool, and client data

My organization has been using ceph-csi-rbd exclusively with external clusters rather than rook.io or OCS. The only thing missing from the helm chart is the required authentication secrets from what I can tell.

**Comment by humblec** [comment]
> Speaking of documentation. A table of the meaning of the elements of values.yaml table would be ideal. Seen that in a lot of other helm charts. 

Sure. !
>As well as an example of volume resizing would be helpful.
> 

Sure. I can take an AI on it. 
> As for:
> 
> > A helm chart maybe, that will work with external clusters while just setting clusterid, monitors, pool, and client data
> 
> My organization has been using ceph-csi-rbd exclusively with external clusters rather than rook.io or OCS. The only thing missing from the helm chart is the required authentication secrets from what I can tell.

Lets revisit this and also add missing details accordingly. 

Thanks @msfrucht for the suggestions.

**Comment by humblec** [comment]
So far we got 

```
# [Ceph-CSI ] v3.2.0 -  Wishlist

User: https://github.com/0x4139:

*)    Updated docs, at this moment some pieces of getting up and running with ceph-csi are not complete and might cause confusion
*)    A helm chart maybe, that will work with external clusters while just setting clusterid, monitors, pool, and client data
*)    A comparison of why would one opt in for ceph-csi instead of the old ceph-rbd provisioner
    
User: https://github.com/humblec

*) Adoption of CSI spec 1.3 & Kube 1.19
*) VolumeCondition support for the PV
*) Go Ceph Binding support for CephFS
*) RBD mirroring
*) Design/implementation of Controller publish and Unpublish 
*) Design/framework for Backend Cluster Operation by avoiding the credential usage in each request
*) Allow volume expansion on encrypted volumes
*) Allow volume snapshotting on encrypted volumes
*) Allow Token based authentication for Vault KMS


 User: https://github.com/msfrucht 
*)  A table of the meaning of the elements of values.yaml table would be ideal. 
*)  Example of volume resizing would be helpful.
```

Planning to close the 3.2.0 items this week, so please chime in if you want to target any extra features for the release.

**Comment by 0x4139** [comment]
anything i can help with?

**Comment by tux-o-matic** [comment]
What's the effort for taking volume resizing from being flagged as Beta to GA?

**Comment by Madhu-1** [comment]
@tux-o-matic resizing is still not supported for filesystem pvc created from clone and snapshot (the work is still in progress in upstream Kubernetes-csi)

**Comment by humblec** [comment]
> What's the effort for taking volume resizing from being flagged as Beta to GA?

@tux-o-matic mostly we will be able to take it to GA with 1.20. As soon as upstream take it to GA, we will also move to GA. hope it helps.

**Comment by humblec** [comment]
> anything i can help with?

@0x4139  Thanks for asking! Sure, lets triage and get back to you. May be we will tag the issues with `help wanted` or similar , so that we can easily fetch the items.

**Comment by msfrucht** [comment]
Will 3.2 recognize v1 snapshot objects for 1.20? If so, will it still include recognition of v1beta1 for some limited time?

**Comment by Madhu-1** [comment]
> Will 3.2 recognize v1 snapshot objects for 1.20? If so, will it still include recognition of v1beta1 for some limited time?

@msfrucht this is no dependency with cephcsi here. if you are using v4.x CRD and controller and the snapshotter sidecar things should work with v1 snapshots.

**Comment by msfrucht** [comment]
@Madhu-1 Thanks. 

I installed the 4.x external-snapshotter and updated the snapshot CRDs. 

VolumeSnapshot/v1 objects work just fine with ceph-csi-3.2.1.

**Comment by msfrucht** [comment]
@Madhu-1 

I have another request.

After using IBM Virtualize, IBM Scale, and Openshift Cluster Storage CSI drivers I noticed all of them add a CSIDriver object for easy lookup of which drivers exists. The existing YAMLs and helm charts of ceph-csi do not. 

And while the helm charts has them as an option, they are CSIDriver/v1beta1 in 3.2.1 when this object went v1 in 1.18. And only gets created when provisioner.attacher.enabled is set to false. So clearly this is both somewhat old and never implemented.

Can the ceph-csi-rbd and ceph-csi-cephfs had an appropriate CSIDriver object for each driver for 3.3 or a later release?

**Comment by Madhu-1** [comment]
@msfrucht https://github.com/ceph/ceph-csi/pull/1945 will add CSIDriver objects for both cephfs and rbd.

**Comment by Madhu-1** [comment]
as https://github.com/ceph/ceph-csi/releases/tag/v3.3.0 3.3.0 release is out. Closing this one.
