### ISSUE TITLE
Missing  cephfs volume metrics

### ISSUE THREAD

**Issue by eachirei** [ceph/ceph-csi#1352]
# Describe the bug #

I am not able to see usage stats for cephfs volumes, only those for rbd - `kubelet_volume_stats_used_bytes`.

# Environment details #

- Image/version of Ceph CSI driver : 3.0
- Helm chart version : not installed via helm
- Kernel version : 4.15.0-112-generic
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : fuse
- Kubernetes cluster version : 1.18.5
- Ceph cluster version : 15.2.4

# Actual results #

Metrics only available for rbd volumes.
```
kubelet_volume_stats_used_bytes{endpoint="https-metrics",instance="X.X.X.131:10250",job="kubelet",namespace="my_ns",node="node-01",persistentvolumeclaim="pvc0",service="prometheus-operator-kubelet"} | 46190592
kubelet_volume_stats_used_bytes{endpoint="https-metrics",instance="X.X.X.73:10250",job="kubelet",namespace="my_ns",node="node-06",persistentvolumeclaim="pvc1",service="prometheus-operator-kubelet"} | 46182400
kubelet_volume_stats_used_bytes{endpoint="https-metrics",instance="X.X.X.216:10250",job="kubelet",namespace="my_ns",node="node-03",persistentvolumeclaim="pvc2",service="prometheus-operator-kubelet"} | 46534656
kubelet_volume_stats_used_bytes{endpoint="https-metrics",instance="X.X.X.201:10250",job="kubelet",namespace="my_ns",node="node-2",persistentvolumeclaim="pvc3",service="prometheus-operator-kubelet"} | 7071977472
kubelet_volume_stats_used_bytes{endpoint="https-metrics",instance="X.X.X.201:10250",job="kubelet",namespace="my_ns",node="node-2",persistentvolumeclaim="pvc4",service="prometheus-operator-kubelet"} | 2629632
```

# Expected behavior #

Metrics available for ceph volumes as well.

**Comment by humblec** [comment]
@eachirei I tried to reproduce this issue in my setup and I could see the metrics getting emitted from the driver.

My setup details:

Ceph CSI version:
         3.0.0
Ceph Version : 
          ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)
Kube: 
      Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Mounter: Kernel mount . iic, you have `fuse` in your setup.

Both RBD and CephFS metrics are getting emitted from the driver. 

I would like to increase the log level to `-v=5` in the cephfs driver plugin and get the logs when this happens for further checking on this issue. Can you provide the same?

**Comment by eachirei** [comment]
Hello! How can I be sure which mounter I'm using? I haven't configured anything special, so I'd say it's the default one in use.

Just to make sure, do you require the logs from the `driver-registrar` container?

**Comment by Madhu-1** [comment]
> @eachirei I tried to reproduce this issue in my setup and I could see the metrics getting emitted from the driver.
> 
> My setup details:
> 
> Ceph CSI version:
> 3.0.0
> Ceph Version :
> ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)
> Kube:
> Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
> 
> Mounter: Kernel mount . iic, you have `fuse` in your setup.
>

@humblec if we use `fuse` metrics won't work?
 
> Both RBD and CephFS metrics are getting emitted from the driver at my end.
> 
> I would like to increase the log level to `-v=5` in the cephfs driver plugin and get the logs when this happens for further checking on this issue. Can you provide the same?

**Comment by Madhu-1** [comment]
> Hello! How can I be sure which mounter I'm using? I haven't configured anything special, so I'd say it's the default one in use.
> 
> Just to make sure, do you require the logs from the `driver-registrar` container?
> 
> ```
> ➜ k logs csi-cephfsplugin-45jlf -c driver-registrar
> I0730 15:02:49.843954       1 main.go:110] Version: v1.3.0-0-g6e9fff3e
> I0730 15:02:49.844063       1 main.go:120] Attempting to open a gRPC connection with: "/csi/csi.sock"
> I0730 15:02:49.844090       1 connection.go:151] Connecting to unix:///csi/csi.sock
> I0730 15:02:50.845170       1 main.go:127] Calling CSI driver to discover driver name
> I0730 15:02:50.845203       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
> I0730 15:02:50.845212       1 connection.go:181] GRPC request: {}
> I0730 15:02:50.854501       1 connection.go:183] GRPC response: {"name":"cephfs.csi.ceph.com","vendor_version":"v3.0-canary"}
> I0730 15:02:50.855430       1 connection.go:184] GRPC error: <nil>
> I0730 15:02:50.855443       1 main.go:137] CSI driver name: "cephfs.csi.ceph.com"
> I0730 15:02:50.855521       1 node_register.go:51] Starting Registration Server at: /registration/cephfs.csi.ceph.com-reg.sock
> I0730 15:02:50.855726       1 node_register.go:60] Registration Server started at: /registration/cephfs.csi.ceph.com-reg.sock
> I0730 15:02:52.270402       1 main.go:77] Received GetInfo call: &InfoRequest{}
> I0730 15:02:52.320127       1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
> ```

@eachirei have you specified any mounter is storage-class? if you have not specified and the kernel is less than 4.17 on nodes fuse mount will be used by default.

**Comment by eachirei** [comment]
@Madhu-1 
This is one of our storage classes:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-01
mountOptions:
- debug
parameters:
  clusterID: 1234
  csi.storage.k8s.io/controller-expand-secret-name: secret-01
  csi.storage.k8s.io/controller-expand-secret-namespace: ceph-csi
  csi.storage.k8s.io/node-stage-secret-name: secret-01
  csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi
  csi.storage.k8s.io/provisioner-secret-name: secret-01
  csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi
  fsName: data_fs
  pool: data_pool
provisioner: cephfs.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Comment by Madhu-1** [comment]
@eachirei can you please try out with kernel mounter in storage-class example is present at https://github.com/ceph/ceph-csi/blob/master/examples/cephfs/storageclass.yaml#L43

**Comment by eachirei** [comment]
Just tested, kernel mounter provides metrics, thank you!
Unfortunately, we have a lot of volumes and the storage class cannot be edited.
So will there be metrics support for fuse or do you have a recommendation to migrate existing volumes from a storage class to another without data loss?

**Comment by Madhu-1** [comment]
> Just tested, kernel mounter provides metrics, thank you!
> Unfortunately, we have a lot of volumes and the storage class cannot be edited.
> So will there be metrics support for fuse or do you have a recommendation to migrate existing volumes from a storage class to another without data loss?

I don't have any recommendations for migration.

@humblec this need to be documented in ceph-csi that metrics are not available for Fuse.

**Comment by humblec** [comment]
> Just tested, kernel mounter provides metrics, thank you!
:+1: 
> Unfortunately, we have a lot of volumes and the storage class cannot be edited.
> So will there be metrics support for fuse or do you have a recommendation to migrate existing volumes from a storage class to another without data loss?

Cant we just recreate the SC with same name but a different mounter? I havent tried though.

**Comment by eachirei** [comment]
So, initially I created a new storage class using same cephfs parameters, with kernel mounter and I got metrics.
Now I recreated the storage classes in use, but I'm still not getting any metrics.
What logs should I provide?

**Comment by eachirei** [comment]
Looking in the logs, for some reason the cephfsplugin still loads the fuse mounter:
```➜ k logs -f csi-cephfsplugin-7qfb9 -c csi-cephfsplugin
I0813 09:49:02.942480       1 cephcsi.go:123] Driver version: v3.0-canary and Git version: 2713a902c5c5fb657c356f3120d54221fe6406af
I0813 09:49:02.942599       1 cephcsi.go:169] Starting driver type: cephfs with name: cephfs.csi.ceph.com
E0813 09:49:02.955929       1 util.go:236] kernel 4.15.0-112-generic does not support required features
I0813 09:49:02.955969       1 volumemounter.go:92] kernel version < 4.17 might not support quota feature, hence not loading kernel client
I0813 09:49:02.968745       1 volumemounter.go:100] loaded mounter: fuse
I0813 09:49:02.969524       1 server.go:118] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
I0813 09:49:03.589824       1 utils.go:159] ID: 1 GRPC call: /csi.v1.Identity/GetPluginInfo
I0813 09:49:03.593134       1 utils.go:160] ID: 1 GRPC request: {}
I0813 09:49:03.593154       1 identityserver-default.go:36] ID: 1 Using default GetPluginInfo
I0813 09:49:03.593999       1 utils.go:165] ID: 1 GRPC response: {"name":"cephfs.csi.ceph.com","vendor_version":"v3.0-canary"}
I0813 09:49:05.408463       1 utils.go:159] ID: 2 GRPC call: /csi.v1.Node/NodeGetInfo
I0813 09:49:05.409116       1 utils.go:160] ID: 2 GRPC request: {}
I0813 09:49:05.409129       1 nodeserver-default.go:57] ID: 2 Using default NodeGetInfo
I0813 09:49:05.410315       1 utils.go:165] ID: 2 GRPC response: {"accessible_topology":{},"node_id":"node-01"}

I0813 09:50:03.261264       1 utils.go:159] ID: 3 GRPC call: /csi.v1.Identity/Probe
I0813 09:50:03.261984       1 utils.go:160] ID: 3 GRPC request: {}
I0813 09:50:03.262731       1 utils.go:165] ID: 3 GRPC response: {}```

**Comment by Madhu-1** [comment]
you may need to set https://github.com/ceph/ceph-csi/blob/master/cmd/cephcsi.go#L66 `forcecephkernelclient=true` on your node plugins and also am not sure  recreating storage-class helps here

**Comment by eachirei** [comment]
Setting `forcecephkernelclient` doesn't seem to do the trick. The kernel mounter is loaded, but it doesn't seem to do much.
```
➜ k logs -f csi-cephfsplugin-z7jzb -c csi-cephfsplugin
I0813 10:07:52.881601       1 cephcsi.go:123] Driver version: v3.0-canary and Git version: 2713a902c5c5fb657c356f3120d54221fe6406af
I0813 10:07:52.881718       1 cephcsi.go:169] Starting driver type: cephfs with name: cephfs.csi.ceph.com
I0813 10:07:52.898148       1 volumemounter.go:89] loaded mounter: kernel
I0813 10:07:52.913960       1 volumemounter.go:100] loaded mounter: fuse
I0813 10:07:52.922308       1 server.go:118] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
I0813 10:07:53.528830       1 utils.go:159] ID: 1 GRPC call: /csi.v1.Identity/GetPluginInfo
I0813 10:07:53.532413       1 utils.go:160] ID: 1 GRPC request: {}
I0813 10:07:53.532439       1 identityserver-default.go:36] ID: 1 Using default GetPluginInfo
I0813 10:07:53.533241       1 utils.go:165] ID: 1 GRPC response: {"name":"cephfs.csi.ceph.com","vendor_version":"v3.0-canary"}
I0813 10:07:54.618207       1 utils.go:159] ID: 2 GRPC call: /csi.v1.Node/NodeGetInfo
I0813 10:07:54.618996       1 utils.go:160] ID: 2 GRPC request: {}
I0813 10:07:54.619013       1 nodeserver-default.go:57] ID: 2 Using default NodeGetInfo
I0813 10:07:54.620333       1 utils.go:165] ID: 2 GRPC response: {"accessible_topology":{},"node_id":"playground-node-hgpu-06"}
```
Why do you say recreating the storage-class doesn't help? What should be the procedure to preserve the data but also have metrics available?

**Comment by Madhu-1** [comment]
can you provide the logs after restarting the nodeplugin pod? i want to see the mounter  is sent in a request for mounting PVC?

**Comment by eachirei** [comment]
I'm not sure which logs are you referring to: `csi-cephfsplugin-2l46q [driver-registrar, csi-cephfsplugin, liveness-prometheus]` or `csi-cephfsplugin-provisioner-585b4f6947-97kcf [csi-provisioner, csi-resizer, csi-cephfsplugin-attacher, csi-cephfsplugin, liveness-prometheus]`?
I created a new volume and got some logs for both pods mentioned above from the cephfsplugin container.
```
I0813 10:23:39.298110       1 utils.go:159] ID: 100 Req-ID: pvc-274bb494-78f9-4849-b836-a99be7b9b974 GRPC call: /csi.v1.Controller/CreateVolume
I0813 10:23:39.301138       1 utils.go:160] ID: 100 Req-ID: pvc-274bb494-78f9-4849-b836-a99be7b9b974 GRPC request: {"capacity_range":{"required_bytes":4294967296},"name":"pvc-274bb494-78f9-4849-b836-a99be7b9b974","parameters":{"clusterID":"172ca873-83b1-4558-a6ad-20bd1b60b20a","fsName":"data_fs","mounter":"kernel","pool":"data_pool"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["debug"]}},"access_mode":{"mode":5}}]}
I0813 10:23:39.683919       1 cephcmds.go:60] ID: 100 Req-ID: pvc-274bb494-78f9-4849-b836-a99be7b9b974 command succeeded: ceph [-m 10.0.0.10 --id user --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs get data_fs --format=json]
I0813 10:23:40.105004       1 cephcmds.go:60] ID: 100 Req-ID: pvc-274bb494-78f9-4849-b836-a99be7b9b974 command succeeded: ceph [-m 10.0.0.10 --id user --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs ls --format=json]
I0813 10:23:40.127280       1 omap.go:74] ID: 100 Req-ID: pvc-274bb494-78f9-4849-b836-a99be7b9b974 got omap values: (pool="data_metadata", namespace="csi", name="csi.volumes.default"): map[]
I0813 10:23:40.137653       1 omap.go:140] ID: 100 Req-ID: pvc-274bb494-78f9-4849-b836-a99be7b9b974 set omap keys (pool="data_metadata", namespace="csi", name="csi.volumes.default"): map[csi.volume.pvc-274bb494-78f9-4849-b836-a99be7b9b974:0e5bd53a-dd4f-11ea-b1a0-ea43210237d2])
I0813 10:23:40.139706       1 omap.go:140] ID: 100 Req-ID: pvc-274bb494-78f9-4849-b836-a99be7b9b974 set omap keys (pool="data_metadata", namespace="csi", name="csi.volume.0e5bd53a-dd4f-11ea-b1a0-ea43210237d2"): map[csi.imagename:csi-vol-0e5bd53a-dd4f-11ea-b1a0-ea43210237d2 csi.volname:pvc-274bb494-78f9-4849-b836-a99be7b9b974])
I0813 10:23:40.139762       1 fsjournal.go:177] ID: 100 Req-ID: pvc-274bb494-78f9-4849-b836-a99be7b9b974 Generated Volume ID (0001-0024-172ca873-83b1-4558-a6ad-20bd1b60b20a-0000000000000002-0e5bd53a-dd4f-11ea-b1a0-ea43210237d2) and subvolume name (csi-vol-0e5bd53a-dd4f-11ea-b1a0-ea43210237d2) for request name (pvc-274bb494-78f9-4849-b836-a99be7b9b974)
I0813 10:23:40.592831       1 cephcmds.go:60] ID: 100 Req-ID: pvc-274bb494-78f9-4849-b836-a99be7b9b974 command succeeded: ceph [fs subvolumegroup create data_fs csi -m 10.0.0.10 -c /etc/ceph/ceph.conf -n client.user --keyfile=***stripped***]
I0813 10:23:40.592876       1 volume.go:114] ID: 100 Req-ID: pvc-274bb494-78f9-4849-b836-a99be7b9b974 cephfs: created subvolume group csi
I0813 10:23:41.547256       1 cephcmds.go:60] ID: 100 Req-ID: pvc-274bb494-78f9-4849-b836-a99be7b9b974 command succeeded: ceph [fs subvolume create data_fs csi-vol-0e5bd53a-dd4f-11ea-b1a0-ea43210237d2 4294967296 --group_name csi --mode 777 -m 10.0.0.10 -c /etc/ceph/ceph.conf -n client.user --keyfile=***stripped*** --pool_layout data_pool]
I0813 10:23:41.547338       1 controllerserver.go:133] ID: 100 Req-ID: pvc-274bb494-78f9-4849-b836-a99be7b9b974 cephfs: successfully created backing volume named csi-vol-0e5bd53a-dd4f-11ea-b1a0-ea43210237d2 for request name pvc-274bb494-78f9-4849-b836-a99be7b9b974
I0813 10:23:41.548826       1 utils.go:165] ID: 100 Req-ID: pvc-274bb494-78f9-4849-b836-a99be7b9b974 GRPC response: {"volume":{"capacity_bytes":4294967296,"volume_context":{"clusterID":"172ca873-83b1-4558-a6ad-20bd1b60b20a","fsName":"data_fs","mounter":"kernel","pool":"data_pool","subvolumeName":"csi-vol-0e5bd53a-dd4f-11ea-b1a0-ea43210237d2"},"volume_id":"0001-0024-172ca873-83b1-4558-a6ad-20bd1b60b20a-0000000000000002-0e5bd53a-dd4f-11ea-b1a0-ea43210237d2"}}
```
Now I got metrics, but unfortunately they represent stats of the whole ceph pool I think (for example I created a 1Gi file, but it shows 1Ti used).

**Comment by Madhu-1** [comment]
this might be due to  quota is not supported in older kernel  version(the kernel you are using)

**Comment by eachirei** [comment]
Okay, but in the initial setup I got correct metrics. The initial setup means: a copy of one of the current storage classes, modified to specify the kernel mounter.
I noticed the kernel warnings, but how come it worked in the first place and what could I do to achieve the same results now?

**Comment by Madhu-1** [comment]
it could be a bug let someone reproduce  it

**Comment by eachirei** [comment]
Can I provide any more information to help fixing this?

**Comment by Madhu-1** [comment]
@eachirei if anything is required we will update this issue.

**Comment by nixpanic** [comment]
@eachirei metrics like `kubelet_volume_stats_*` are only available if the volume is in use by a Pod. Kubelet gathers these metrics, and can only access the Volume when it is in use/mounted.

Could you let us know if this additional detail helps?

**Comment by nixpanic** [comment]
Re-triaging, as the problem is not clear enough. Sometimes it worked, sometimes it didnt. As I've been working on #1831 , I now have a better understanding of how metrics work, the question in https://github.com/ceph/ceph-csi/issues/1352#issuecomment-769687644 is key to make progress.

**Comment by weibeld** [comment]
Having the same problem with the CephFS driver, there are no `kubelet_volume_*` metrics. The driver seems to use the kernel mounter:

```bash
$ kubectl logs csi-cephfsplugin-6b9xj -c csi-cephfsplugin | head -n 15
I0125 15:01:05.162488       1 cephcsi.go:113] Driver version: v2.0.1 and Git version: be6318716e08f6307206508d41a63eaa3781d408
I0125 15:01:05.172196       1 cachepersister.go:45] cache-perister: using kubernetes configmap as metadata cache persister
I0125 15:01:05.185679       1 cephcsi.go:140] Initial PID limit is set to 4915
I0125 15:01:05.185760       1 cephcsi.go:149] Reconfigured PID limit to -1 (max)
I0125 15:01:05.185768       1 cephcsi.go:168] Starting driver type: cephfs with name: rook-ceph.cephfs.csi.ceph.com
I0125 15:01:05.235563       1 volumemounter.go:160] loaded mounter: kernel
I0125 15:01:05.276679       1 volumemounter.go:168] loaded mounter: fuse
I0125 15:01:05.288221       1 mountcache.go:59] mount-cache: name: rook-ceph.cephfs.csi.ceph.com, version: v2.0.1, mountCacheDir: /mount-cache-dir
I0125 15:01:05.288402       1 mountcache.go:99] mount-cache: successfully remounted 0 volumes
I0125 15:01:05.291130       1 server.go:116] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
I0219 08:13:50.359136       1 volumemounter.go:203] requested mounter: , chosen mounter: kernel
I0219 08:13:50.359499       1 volumemounter.go:203] requested mounter: , chosen mounter: kernel
I0219 08:13:50.455277       1 nodeserver.go:129] ID: 35598 Req-ID: 0001-0009-rook-ceph-0000000000000001-74d27e08-28bf-11eb-bd9e-96caed955799 cephfs: successfully mounted volume 0001-0009-rook-ceph-0000000000000001-74d27e08-28bf-11eb-bd9e-96caed955799 to /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8f427980-800f-4ff7-9417-5344e39fbb35/globalmount
I0219 08:13:50.455560       1 nodeserver.go:129] ID: 35599 Req-ID: 0001-0009-rook-ceph-0000000000000001-74ddb5c2-28bf-11eb-bd9e-96caed955799 cephfs: successfully mounted volume 0001-0009-rook-ceph-0000000000000001-74ddb5c2-28bf-11eb-bd9e-96caed955799 to /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-79c16d07-6981-4754-92a1-ad42246c8641/globalmount
I0219 08:13:50.498812       1 mountcache.go:299] ID: 35602 Req-ID: 0001-0009-rook-ceph-0000000000000001-74ddb5c2-28bf-11eb-bd9e-96caed955799 mount-cache: metadata not found, delete mount cache failed for volume 0001-0009-rook-ceph-0000000000000001-74ddb5c2-28bf-11eb-bd9e-96caed955799
```

However, throughout the lifetime of the driver, I also have these logs:

```bash
$ kubectl logs csi-cephfsplugin-6b9xj -c csi-cephfsplugin
E0330 21:21:29.664679       1 utils.go:161] ID: 244189 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/55f765f1-da16-441c-98a3-7e2cb89aa60c/volumes/kubernetes.io~csi/pvc-8f427980-800f-4ff7-9417-5344e39fbb35/mount: permission denied
E0330 21:21:29.666824       1 utils.go:161] ID: 244191 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/55f765f1-da16-441c-98a3-7e2cb89aa60c/volumes/kubernetes.io~csi/pvc-79c16d07-6981-4754-92a1-ad42246c8641/mount: permission denied
E0330 21:22:41.228784       1 utils.go:161] ID: 244194 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/55f765f1-da16-441c-98a3-7e2cb89aa60c/volumes/kubernetes.io~csi/pvc-79c16d07-6981-4754-92a1-ad42246c8641/mount: permission denied
E0330 21:22:41.231026       1 utils.go:161] ID: 244196 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/55f765f1-da16-441c-98a3-7e2cb89aa60c/volumes/kubernetes.io~csi/pvc-8f427980-800f-4ff7-9417-5344e39fbb35/mount: permission denied
E0330 21:24:22.951218       1 utils.go:161] ID: 244200 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/55f765f1-da16-441c-98a3-7e2cb89aa60c/volumes/kubernetes.io~csi/pvc-79c16d07-6981-4754-92a1-ad42246c8641/mount: permission denied
E0330 21:24:22.953528       1 utils.go:161] ID: 244202 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/55f765f1-da16-441c-98a3-7e2cb89aa60c/volumes/kubernetes.io~csi/pvc-8f427980-800f-4ff7-9417-5344e39fbb35/mount: permission denied
E0330 21:25:56.227717       1 utils.go:161] ID: 244205 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/55f765f1-da16-441c-98a3-7e2cb89aa60c/volumes/kubernetes.io~csi/pvc-8f427980-800f-4ff7-9417-5344e39fbb35/mount: permission denied
E0330 21:25:56.230379       1 utils.go:161] ID: 244207 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/55f765f1-da16-441c-98a3-7e2cb89aa60c/volumes/kubernetes.io~csi/pvc-79c16d07-6981-4754-92a1-ad42246c8641/mount: permission denied
E0330 21:27:25.064873       1 utils.go:161] ID: 244211 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/55f765f1-da16-441c-98a3-7e2cb89aa60c/volumes/kubernetes.io~csi/pvc-8f427980-800f-4ff7-9417-5344e39fbb35/mount: permission denied
E0330 21:27:25.067738       1 utils.go:161] ID: 244213 GRPC error: rpc error: code = Internal desc = stat /var/lib/kubelet/pods/55f765f1-da16-441c-98a3-7e2cb89aa60c/volumes/kubernetes.io~csi/pvc-79c16d07-6981-4754-92a1-ad42246c8641/mount: permission denied
```

There are two PVCs being used on this specific node (by the same pod). The logs are recent and the error occurs roughly every 1.5 minutes. However, the PVs are mounted and work correctly.

Could this have anything to do that the CSI driver is not able to execute the [`NodeGetVolumeStats`](https://github.com/container-storage-interface/spec/blob/master/spec.md#nodegetvolumestats) RPC calls from the kubelet and that's why the metrics are not exposed?
