### ISSUE TITLE
Ceph CSI Release 3.3.0 

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1353]
Release 3.3.0 planning :+1: 

_Wishlist from community_ 
#1340 

Release Timeline:

Release Team:

**Comment by Madhu-1** [comment]
As the wishlist is having a good number of items and most of them are not covered. am update the issue title to reflect the next release.

**Comment by Madhu-1** [comment]
As we have 3.3.0 release https://github.com/ceph/ceph-csi/releases/tag/v3.3.0  closing this one
