### ISSUE TITLE
Switch driver-registrar canary image to other releases

### ISSUE THREAD

**Issue by rootfs** [ceph/ceph-csi#138]
currently csi-v1.0 uses `quay.io/k8scsi/driver-registrar:canary`, since there is no 1.0 image yet.

Create an issue to track upstream release and make a switch once 1.0 tag is there.

**Comment by Madhu-1** [comment]
@rootfs any idea when we will be switching to node-driver-registrar and cluster-driver-registrar as driver-registrar is deprecated?

**Comment by rootfs** [comment]
@Madhu-1 make a PR :)

**Comment by Madhu-1** [comment]
@rootfs can we close this one?
