### ISSUE TITLE
Update docs to reference Nomad Deployment Configuration

### ISSUE THREAD

**Issue by ryanmickler** [ceph/ceph-csi#1381]
Recently, I commited an example configuration of using the ceph-csi (rbd) plugin with Nomad, instead of K8S, see **https://github.com/hashicorp/nomad/pull/8664**.

Perhaps we could link somewhere in the Readme to this **https://github.com/hashicorp/nomad/tree/master/demo/csi/ceph-csi-plugin**.

**Comment by humblec** [comment]
@ryanmickler  thats great. :+1: . Documentation can be done. May be we could keep a document for `integrations` in general, have to think through it thogh. Also, if possible some article about this integration could also help!

**Comment by humblec** [comment]
@ryanmickler one suggestion here is, may be instead of using `2.1.0` version of Ceph CSI , I would recommend to use `3.1.0` or `3.0.0`
