### ISSUE TITLE
Maybe it is possible to add some command line examples to test the driver?

### ISSUE THREAD

**Issue by f1-outsourcing** [ceph/ceph-csi#1424]
If I run the csi plugin like

`/usr/libexec/csi/csiceph --endpoint $CSI_ENDPOINT --type rbd --drivername rbd.csi.ceph.com --nodeid test`

I can get some plugin info
```
[@ ]# csc identity plugin-info
"rbd.csi.ceph.com"    "canary"
```

But of course this command listing the rbd images fails, because I am not specifying any pool, clusterid or credentials.

```
[@]# csc controller list-volumes


Please use -h,--help for more information
```

I am testing also with a local lvm csi plugin which has only a few command line parameters that allow listing of volumes.

```
./csilvm -unix-addr-env CSI_ENDPOINT -volume-group VGtest -devices Vtestman1,LVtestman2,LVtestman3

[@~]# csc controller list-volumes
"LVtestman1"    104857600
"LVtestman2"    104857600
"LVtestman3"    104857600
"csilv1r6pyrrohd7kr"    12582912        "tags"="WyJWTi5jc2N2b2wiXQ"
```

Would be nice to be able to know how to list rbd images and configure auth credentials

**Comment by nixpanic** [comment]
It would be nice to have some CI jobs that run the `csc` command to do basic CSI operations.
