### ISSUE TITLE
Skip E2E tests if the PR is trivial 

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1427]
We need to skip the E2E tests if the PR is making trivial changes. as it doesn't make sense to run complete E2E tests for Doc or some script changes. we need to Skip E2E tests based on the PR comment like adding `[skip ci] or based on the PR label.

**Comment by Madhu-1** [comment]
cc @nixpanic

**Comment by nixpanic** [comment]
I'd like to start with a `[ci/skip/e2e]` label, so that the **ci/centos/mini-e2e** and **ci/centos/mini-e2e-helm** jobs can be skipped.

**Comment by nixpanic** [comment]
#1428 got merged, this issue should have been closed.
