### ISSUE TITLE
static manifests from helm chart

### ISSUE THREAD

**Issue by kfox1111** [ceph/ceph-csi#143]
Currently we have two different implementations of the driver plumbing. The helm chart and the static manifests. They can and do get out of sync. We could generate the static manifests as part of the release process by running 'helm template' on the chart. Then there would only be one set of templates to update for both use cases.

**Comment by mcronce** [comment]
+1

**Comment by kfox1111** [comment]
Question. should we just have it upload the generated objects somewhere on release, like at https://github.com/ceph/ceph-csi/releases and remove the static version from git entirely, or should we try and get a hook to have it happen at contribute time back to git? @rootfs

**Comment by humblec** [comment]
@Madhu-1 @wilmardo any thoughts here ?

**Comment by Madhu-1** [comment]
> @Madhu-1 @wilmardo any thoughts here ?

this is one of the good feature to have it

**Comment by wilmardo** [comment]
Started this in #604 and I am willing to pick this backup. I will make some time coming Friday :)

**Comment by wilmardo** [comment]
#604 is still open and this issue hasn't been resolved just yet :'(

**Comment by Madhu-1** [comment]
can we check if we can use https://github.com/arttor/helmify to generate the helm charts from kubernetes objects?
