### ISSUE TITLE
./scripts/minikube sh is failing

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1431]
./scripts/minikube.sh up
minikube already installed with v1.12.0
Installing minikube. Version: v1.12.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 55.9M  100 55.9M    0     0  6834k      0  0:00:08  0:00:08 --:--:-- 8746k
mv: cannot create regular file '/usr/local/bin/minikube': Permission denied

as the minikube version is already present it should not try to update the latest version. if there is any bugs in the latest version we don't get an option to use the known version as it always tries to update to the latest.

**Comment by nixpanic** [comment]
`minikube.sh install` should be run as root. Other actions should not try to install minikube (or kubectl).

**Comment by Madhu-1** [comment]
just a minor correction we don't have `minikube install` we have `minikube up` still we should not update to the latest minikube version without user concern. (I would suggest just to install the minikube version which is specified in build.env which can  be overridden from MINIKUBE_VERSION env)

**Comment by pkalever** [comment]
@Madhu-1 I can look at this issue. Feel free to assign it to me. Thanks!
