### ISSUE TITLE
Restore/ PVC-PVC clone to a bigger size is allowed for cephfs PVC

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1435]
Currently, snapshot Restore/PVC-PVC to a bigger size is not allow for rbd volume and it got disabled in https://github.com/ceph/ceph-csi/pull/1244. for now, this is supported for cephfs due to the workaround we are doing in cephfs for volume size in https://github.com/ceph/ceph-csi/issues/1254

**Comment by nixpanic** [comment]
Duplicated by #1438 and #1439?

**Comment by Madhu-1** [comment]
closing as duplicate
