### ISSUE TITLE
Verify snapshot and pvc cloning functionalities as a part of upgrade testing 

### ISSUE THREAD

**Issue by Yuggupta27** [ceph/ceph-csi#1437]
Adding upgrade testing for snapshot and clone functionalities will 
enable us to validate backward compatibility of the same.

Steps to follow: 
1. Deploy ceph-csi `v3.1.0`
2. Create PVC.
2. Create a snapshot of the PVC.
3. Upgrade ceph-csi to `master/canary` release
4. Restore snapshot
5. Clone a new PVC from the existing one. 
6. Create a Snapshot from PVC created in step 2 (just to validate we are able to create snapshot from old PVC)

the same need to be done for cephfs and rbd  

Also see: #696 #1243

**Comment by Yuggupta27** [comment]
Please assign @Madhu-1

**Comment by humblec** [comment]
>Deploy ceph-csi v3.10

3.1.0 @Yuggupta27

**Comment by Madhu-1** [comment]
Note: Upgrade testing need to be moved to centos CI, currently we are running upgrade tests on Travis CI which doesn't support cephfs snapshot

**Comment by Yuggupta27** [comment]
Closing this issue as #1464 is merged.
