### ISSUE TITLE
Allow bigger size restore/clone for CephFS

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1439]
# Describe the bug #
CSI spec allows a user to create bigger volumes at restore/clone path. Ideally we should enable it in our driver too. This issue tracks the requirement for CephFS

Eventhough its allowed in today's code, we have to revisit this path with the fix present in CephFS for snapshot size.

**Comment by Madhu-1** [comment]
@pkalever can we target this one 3.4.1 or 3.4.2?
