### ISSUE TITLE
[Question] Maximum number of volumes supported

### ISSUE THREAD

**Issue by andrewsali** [ceph/ceph-csi#1447]
# Describe the feature you'd like to have #

This is more of a request for documenting known limits (if any) - is there any known limit on the maximum number of CSI volumes (CephFS subvolumes) supported for a single filesystem?

For example, for snapshots, there is currently a global limit of 400 for a single CephFS filesystem if using the kernel driver: https://github.com/ceph/ceph-csi/issues/1133 

It would be useful to know if there are any other known limits in terms of CephFS-CSI volumes.

# What is the value to the end user? (why is it a priority?) #

Better planning of the architecture when using Ceph-CSI as persistent storage in k8s.

# How will we know we have a good solution? (acceptance criteria) #

There is some publicly available information on known limits (if any).

# Additional context #

**Comment by batrick** [comment]
> For example, for snapshots, there is currently a global limit of 400 for a single CephFS filesystem if using the kernel driver: #1133

This is no longer true as of v14.2.12 (to be released). There will be no snapshot limit globally for subvolumes.  Each subvolume is limited to 100 snapshots however.

**Comment by batrick** [comment]
> It would be useful to know if there are any other known limits in terms of CephFS-CSI volumes.

There is no subvolume count limit.

**Comment by andrewsali** [comment]
Thank you all for the insights!

**Comment by andrewsali** [comment]
Regarding the snapshot limit addressed in v14.2.12 - is there any
information if it will be backported to octopus v15.2.6? With the global
400 limit, snapshot usability is unfortunately significantly impacted in
CSI.
