### ISSUE TITLE
PVC hangs in "Pending" status

### ISSUE THREAD

**Issue by ep4eg** [ceph/ceph-csi#1449]
# Describe the bug #

There are no meaningful error messages available. Just trying to deploy csi-rbd-provisioner.

# Environment details #

- Image/version of Ceph CSI driver : https://github.com/ceph/ceph-csi/tree/master/deploy/rbd/kubernetes as is.
- Helm chart version : - 
- Kernel version : 3.10.0-862.el7.x86_64
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : -
- Kubernetes cluster version : v1.18.2
- Ceph cluster version : 14.2.11

# Steps to reproduce #

Steps are described here: https://docs.ceph.com/docs/master/rbd/rbd-kubernetes/

# Actual results #

PVC hangs in 'Pending' state

# Expected behavior #

Provisioned volume
# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

csi-provisioner
```
I0829 23:16:16.808022       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
I0829 23:16:16.808034       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-9fee2a2f-6c88-4ee4-9a67-393d05a4992b","parameters":{"clusterID":"<cluster_id>","pool":"k8s-csi-rbd"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
I0829 23:16:16.813020       1 connection.go:185] GRPC response: {}
I0829 23:16:16.813415       1 connection.go:186] GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-9fee2a2f-6c88-4ee4-9a67-393d05a4992b already exists
I0829 23:16:16.813452       1 controller.go:634] CreateVolume failed, supports topology = true, node selected false => may reschedule = false => state = Background: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-9fee2a2f-6c88-4ee4-9a67-393d05a4992b already exists
```

csi-rbdplugin
```
1 utils.go:163] ID: 8255 Req-ID: pvc-7273569d-541d-4b82-b9cc-9a194caa0d22 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-7273569d-541d-4b82-b9cc-9a194caa0d22 already exists
```
# Additional context #

Network connectivity is fine, native k8s provisioner works just fine.

**Comment by Yuggupta27** [comment]
Hi @ep4eg , can you please check if the `clusterID` provided in the csi-configmap matches the one in the storage class (`csi-rbd-sc.yaml` in your case)?

**Comment by ep4eg** [comment]
I confirm it's the same ID

**Comment by Yuggupta27** [comment]
Can you please check if any command is stuck, For that you need to exec into csi-rbdplugin of the provisioner pod and run 
```
# ps -ef | grep rados
# ps -ef | grep rbd
```

**Comment by ep4eg** [comment]
Nothing interesting here
```
$ kubectl exec -it csi-rbdplugin-provisioner-7dfbc5fc7d-tgbrh -c csi-rbdplugin -- ps -ef | grep -cE '(rados|rbd)'
0
```

**Comment by humblec** [comment]
@ep4eg can you also check the other provisioner pod ?

**Comment by IsaackRasmussen** [comment]
I have the same issue and all my pods do not have any stuck commands

**Comment by ep4eg** [comment]
@humblec there's only 1, I set the number of replicas to 1. Also, kernel was updated to 5.8.1-1.el7.elrepo.x86_64 - not the case.

**Comment by humblec** [comment]
@ep4eg how did you deploy this cluster ? if you have a different kubelet path you have to configure accordingly. We should have used "/var/lib/kubelet" instead of "/my_not_var_dir//kubelet" or should have changed `rook-ceph-csi-config` configmap.

**Comment by ep4eg** [comment]
With my hands apparently. There's a symlink from default kubelet data-dir to the custom one so you can access the socket through `/var/lib/kubelet` . Can't see any problem with this, fix me If I'm wrong. Is there a way to see any meaningful logs?

**Comment by Madhu-1** [comment]
you cannot use `ps` output to identify the hang commands in recent cephcsi release as we moved to go-ceph bindings. @ep4eg can you please provide the complete `csi-rbdplugin` container logs to check whats wrong

**Comment by ep4eg** [comment]
Hey @Madhu-1  here's the entire log file - https://pastebin.pl/view/d758038c

**Comment by Madhu-1** [comment]
```
I0902 13:54:08.698276       1 utils.go:159] ID: 17 Req-ID: pvc-9fee2a2f-6c88-4ee4-9a67-393d05a4992b GRPC call: /csi.v1.Controller/CreateVolume
I0902 13:54:08.699936       1 utils.go:160] ID: 17 Req-ID: pvc-9fee2a2f-6c88-4ee4-9a67-393d05a4992b GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-9fee2a2f-6c88-4ee4-9a67-393d05a4992b","parameters":{"clusterID":"<ceph_cluster_id>","pool":"k8s-csi-rbd"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
I0902 13:54:08.700137       1 rbd_util.go:771] ID: 17 Req-ID: pvc-9fee2a2f-6c88-4ee4-9a67-393d05a4992b setting disableInUseChecks on rbd volume to: false
[🎩︎]mrajanna@localhost ceph-csi $]cat a|grep -i "ID: 20"
I0902 13:56:39.202080       1 utils.go:159] ID: 20 Req-ID: pvc-9fee2a2f-6c88-4ee4-9a67-393d05a4992b GRPC call: /csi.v1.Controller/CreateVolume
I0902 13:56:39.203702       1 utils.go:160] ID: 20 Req-ID: pvc-9fee2a2f-6c88-4ee4-9a67-393d05a4992b GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-9fee2a2f-6c88-4ee4-9a67-393d05a4992b","parameters":{"clusterID":"<ceph_cluster_id>","pool":"k8s-csi-rbd"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":1}}]}
I0902 13:56:39.203834       1 rbd_util.go:771] ID: 20 Req-ID: pvc-9fee2a2f-6c88-4ee4-9a67-393d05a4992b setting disableInUseChecks on rbd volume to: false
E0902 13:56:39.203848       1 controllerserver.go:232] ID: 20 Req-ID: pvc-9fee2a2f-6c88-4ee4-9a67-393d05a4992b an operation with the given Volume ID pvc-9fee2a2f-6c88-4ee4-9a67-393d05a4992b already exists
E0902 13:56:39.203866       1 utils.go:163] ID: 20 Req-ID: pvc-9fee2a2f-6c88-4ee4-9a67-393d05a4992b GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-9fee2a2f-6c88-4ee4-9a67-393d05a4992b already exists
```

just went through the log it looks to be a connectivity issue. can you please provide the configmap you have created for mon configuration and also can you run `ceph -s` from the csi-rbdplugin container of the provisioner pod. **Note** you need to provide user id and userkey and mon IP when running the `ceph -s` command manually inside the csi-rbdplugin container.

**Comment by ep4eg** [comment]
Well, there's no access to `3300` ( which is supposed to be for `v2` protocol requests). Is this the root cause? I thought ceph-csi supports `v1` only. Would be nice to have timeouts and corresponding log messages on it.

**Comment by Madhu-1** [comment]
Cephcsi is mostly tested with v1 monitor. It could be the issue. can you change the mon port and check things are working fine?

**Comment by ep4eg** [comment]
Access to `3300` solved the issue, however, I'd like to see such things in the logs. Thank you, guys!

**Comment by Madhu-1** [comment]
> Access to `3300` solved the issue, however, I'd like to see such things in the logs. Thank you, guys!

as ceph, as not returned any error we cannot log such things in cephcsi. As its working now closing this one
