### ISSUE TITLE
 error getting secret csi-rbd-secret in namespace default

### ISSUE THREAD

**Issue by duxvfeng** [ceph/ceph-csi#1455]
# Describe the bug #

   Warning  ProvisioningFailed    0s (x5 over 7s)  rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-5f49d658bf-5gcbl_63f651c5-8a6a-4600-b930-24eaeee2f078  failed to provision volume with StorageClass "csi-cephfs-sc": error getting secret csi-rbd-secret in namespace default: secrets "csi-rbd-secret" not found
[root@k8s-master ~]# kubectl delete -f pvc-db.yaml   
 

# Environment details #

- Image/version of Ceph CSI driver :
- Helm chart version :
- Kernel version :
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
- Kubernetes cluster version : 1.15.8
- Ceph cluster version :  v.1.2

# Steps to reproduce #

1. kubectl create -f  storageclass.yaml
2. kubectl patch storageclass csi-cephfs-sc -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'  
3. kubectl creater -f pvc.yaml

# Actual results #
Name:          pvc-db
Namespace:     hyperdata
StorageClass:  csi-cephfs-sc
Status:        Pending
Volume:        
Labels:        app=hd
Annotations:   volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason                Age              From                                                                                                              Message
  ----     ------                ----             ----                                                                                                              -------
  Normal   ExternalProvisioning  1s (x2 over 7s)  persistentvolume-controller                                                                                       waiting for a volume to be created, either by external provisioner "rook-ceph.cephfs.csi.ceph.com" or manually created by system administrator
  Normal   Provisioning          0s (x5 over 7s)  rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-5f49d658bf-5gcbl_63f651c5-8a6a-4600-b930-24eaeee2f078  External provisioner is provisioning volume for claim "hyperdata/pvc-db"
  Warning  ProvisioningFailed    0s (x5 over 7s)  rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-5f49d658bf-5gcbl_63f651c5-8a6a-4600-b930-24eaeee2f078  failed to provision volume with StorageClass "csi-cephfs-sc": error getting secret csi-rbd-secret in namespace default: secrets "csi-rbd-secret" not found

**Comment by Madhu-1** [comment]
>5gcbl_63f651c5-8a6a-4600-b930-24eaeee2f078 failed to provision volume with StorageClass "csi-cephfs-sc": error getting secret csi-rbd-secret in namespace default: secrets "csi-rbd-secret" not found

as you are using cephfs provisioner why you are mentioning `csi-rbd-secret`?

>rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-5f49d658bf-5gcbl_63f651c5-8a6a-4600-b930-24eaeee2f078

and also you are using cephcsi with the rook. please refer to rook examples at https://github.com/rook/rook/tree/master/cluster/examples/kubernetes/ceph/csi/cephfs

Closing this one as this is completely miss-configuration.
