### ISSUE TITLE
[Question] Restoring PersistentVolumeClaims and VolumeSnapshots after failure

### ISSUE THREAD

**Issue by tamas-ac** [ceph/ceph-csi#1459]
### Managing critical failures with Ceph-CSI

We plan to use CephFS as out persistent storage in Kubernetes with Ceph-CSI, so we want to create PersistentVolumeClaims and VolumeSnapshots and let the CSI driver handle the rest on the Ceph side.

Now let's assume there is a critical Ceph failure, and we are able to restore the Ceph cluster to an earlier state. However, now probably some of the PersistentVolumes/VolumeSnapshotsContents are inconsistent with Ceph subvolumes and subvolumesnapshots. What is the recommended way to reconcile the kubernetes objects? Are there some tools for this?

**Comment by tamas-ac** [comment]
I'll be a bit more specific.

I experimented with the following scenario: created manually using ceph commands a subvolume /volume/csi/restore-test,
and then tried to create a PVC and PV that would point to this manually created subvolume. This is to emulate disaster recovery of a CephFS state where the subvolume still existed but the corresponding PVC and PV has been removed from kubernetes.

The used manifests:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph.cephfs.csi.ceph.com
  name: test-restore-dynamic-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test-restore-dynamic-pvc
    namespace: nv-apps
  csi:
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
    driver: rook-ceph.cephfs.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      fsName: cephfs
      mounter: fuse
      pool: cephfs-data0
      provisionVolume: "true"
      storage.kubernetes.io/csiProvisionerIdentity: 1598689805089-8081-rook-ceph.cephfs.csi.ceph.com
      subvolumeName: restore-test
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-restore-test
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
  name: test-restore-dynamic-pvc
  namespace: nv-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  volumeName: test-restore-dynamic-pv
```

I obtained the above yamls by editing a working PVC & PV setup. After applying them, this is their state:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{"pv.kubernetes.io/provisioned-by":"rook-ceph.cephfs.csi.ceph.com"},"name":"test-restore-dynamic-pv"},"spec":{"accessModes":["ReadWriteMany"],"capacity":{"storage":"50Gi"},"claimRef":{"apiVersion":"v1","kind":"PersistentVolumeClaim","name":"test-restore-dynamic-pvc","namespace":"nv-apps"},"csi":{"controllerExpandSecretRef":{"name":"rook-csi-cephfs-provisioner","namespace":"rook-ceph"},"driver":"rook-ceph.cephfs.csi.ceph.com","fsType":"ext4","nodeStageSecretRef":{"name":"rook-csi-cephfs-node","namespace":"rook-ceph"},"volumeAttributes":{"clusterID":"rook-ceph","fsName":"cephfs","mounter":"fuse","pool":"cephfs-data0","provisionVolume":"true","storage.kubernetes.io/csiProvisionerIdentity":"1598689805089-8081-rook-ceph.cephfs.csi.ceph.com","subvolumeName":"restore-test"},"volumeHandle":"0001-0009-rook-ceph-0000000000000001-restore-test"},"persistentVolumeReclaimPolicy":"Delete","storageClassName":"rook-cephfs","volumeMode":"Filesystem"}}
    pv.kubernetes.io/provisioned-by: rook-ceph.cephfs.csi.ceph.com
  creationTimestamp: "2020-09-10T11:44:15Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: test-restore-dynamic-pv
  resourceVersion: "10847315"
  selfLink: /api/v1/persistentvolumes/test-restore-dynamic-pv
  uid: 909e8d9d-dfd3-4e4f-8738-4548266d4695
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test-restore-dynamic-pvc
    namespace: nv-apps
    resourceVersion: "10847313"
    uid: 65c65cfa-6bf3-4b8d-8abc-c9a068cabb5a
  csi:
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
    driver: rook-ceph.cephfs.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      fsName: cephfs
      mounter: fuse
      pool: cephfs-data0
      provisionVolume: "true"
      storage.kubernetes.io/csiProvisionerIdentity: 1598689805089-8081-rook-ceph.cephfs.csi.ceph.com
      subvolumeName: restore-test
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-restore-test
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rook-cephfs
  volumeMode: Filesystem
status:
  phase: Bound
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"volume.beta.kubernetes.io/storage-provisioner":"rook-ceph.cephfs.csi.ceph.com"},"name":"test-restore-dynamic-pvc","namespace":"nv-apps"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"50Gi"}},"storageClassName":"rook-cephfs","volumeMode":"Filesystem","volumeName":"test-restore-dynamic-pv"}}
    pv.kubernetes.io/bind-completed: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
  creationTimestamp: "2020-09-10T11:44:15Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: test-restore-dynamic-pvc
  namespace: nv-apps
  resourceVersion: "10847363"
  selfLink: /api/v1/namespaces/nv-apps/persistentvolumeclaims/test-restore-dynamic-pvc
  uid: 65c65cfa-6bf3-4b8d-8abc-c9a068cabb5a
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  volumeName: test-restore-dynamic-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  phase: Bound
```

This looks good, but when trying to mount the PVC, I get the below error message in csi-cephfsplugin:
```
E0910 10:57:45.048625 1 utils.go:163] ID: 1373 Req-ID: 0001-0009-rook-ceph-0000000000000001-restore-test GRPC error: rpc error: code = Internal desc = missing required field monitors
```

**Comment by Madhu-1** [comment]
@tamas-ac resize/ snapshot on static PVC  is not supported in cephcsi as of now.

**Comment by Madhu-1** [comment]
> ### Managing critical failures with Ceph-CSI
> We plan to use CephFS as out persistent storage in Kubernetes with Ceph-CSI, so we want to create PersistentVolumeClaims and VolumeSnapshots and let the CSI driver handle the rest on the Ceph side.
> 

> Now let's assume there is a critical Ceph failure, and we are able to restore the Ceph cluster to an earlier state. However, now probably some of the PersistentVolumes/VolumeSnapshotsContents are inconsistent with Ceph subvolumes and subvolumesnapshots. What is the recommended way to reconcile the kubernetes objects? Are there some tools for this?

if have restored the ceph cluster and the ceph cluster is having rbd images/cephfs subvolumes with the same names as before everything works smoothly,  if names are different, the best options would be renaming the subvolumes to match the earlier names

**Comment by tamas-ac** [comment]
@Madhu-1 thanks for the heads up on expand/delete and snapshots for static PVC!

I assumed that if the ceph cluster can be restored, the existing PVCs should work. I'm concerned about subvolumes where the PVC is no longer there.

Example:
1.  Create a dynamic PVC 'pvc-1'. Kubernetes provisions a PV 'pv-<uuid>', binds it to 'pvc-1' and everything works. 
1.  The entire Ceph cluster is backed up, let's call this state "ceph-bckp"
1.  PVC 'pvc-1' is deleted. As the reclaimPolicy is Delete, the corresponding subvolume is removed from CephFS
1.  Critical failure happens, Ceph cluster is restored to "ceph-bckp"
1.  Now the subvolume behind 'pv-<uuid>' exists again, but the kubernetes objects 'pvc-1' and 'pv-<uuid>' don't

The above scenario is relevant also in case there is no critical failure, only 'pvc-1' is deleted by mistake and should be restored from backup.

I'd like to figure out if it's possible to recreate the 'pvc-1' and 'pv-<uuid>' kubernetes objects in this case so that they work again.

**Comment by Madhu-1** [comment]
> @Madhu-1 thanks for the heads up on expand/delete and snapshots for static PVC!
> 
> I assumed that if the ceph cluster can be restored, the existing PVCs should work. I'm concerned about subvolumes where the PVC is no longer there.
> 
> Example:
> 
> 1. Create a dynamic PVC 'pvc-1'. Kubernetes provisions a PV 'pv-', binds it to 'pvc-1' and everything works.
> 2. The entire Ceph cluster is backed up, let's call this state "ceph-bckp"
> 3. PVC 'pvc-1' is deleted. As the reclaimPolicy is Delete, the corresponding subvolume is removed from CephFS
> 4. Critical failure happens, Ceph cluster is restored to "ceph-bckp"
> 5. Now the subvolume behind 'pv-' exists again, but the kubernetes objects 'pvc-1' and 'pv-' don't
> 
> The above scenario is relevant also in case there is no critical failure, only 'pvc-1' is deleted by mistake and should be restored from backup.
> 

I think if you periodically back up the kubernetes objects, you can recreate it back 

in  PV output the CSI part is the main for CSI, if you can add the CSI section as before in think you can reuse things

this example is for rbd
```yaml
csi:
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
    driver: rook-ceph.rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      imageFeatures: layering
      imageFormat: "2"
      imageName: csi-vol-17382c21-f35a-11ea-9abc-0242ac110008
      journalPool: replicapool
      pool: replicapool
      radosNamespace: ""
      storage.kubernetes.io/csiProvisionerIdentity: 1599737796781-8081-rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-0009-rook-ceph-0000000000000002-17382c21-f35a-11ea-9abc-0242ac110008
```

`volumeHandle: 0001-0009-rook-ceph-0000000000000002-17382c21-f35a-11ea-9abc-0242ac110008`  is important for use its encoded one and  its container ceph pool, clusterid and subvolume/rbd name to easily identify the backend image.

> I'd like to figure out if it's possible to recreate the 'pvc-1' and 'pv-' kubernetes objects in this case so that they work again.

**Comment by tamas-ac** [comment]
Thanks @Madhu-1, indeed restoring PVCs and PVs works if I use a volumeHandle that was generated by the CSI driver.

Is the same expected to work with VolumeSnapshots? I tried a similar method for restoring together the VolumeSnapshot and VolumeSnapshotContents:

```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotContent
metadata:
  annotations:
    snapshot.storage.kubernetes.io/deletion-secret-name: rook-csi-cephfs-provisioner
    snapshot.storage.kubernetes.io/deletion-secret-namespace: rook-ceph
  generation: 1
  name: snapcontent-48ac51de-07c2-4bcb-8b5b-813ac290d492
spec:
  deletionPolicy: Delete
  driver: rook-ceph.cephfs.csi.ceph.com
  source:
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-27ddbf75-f362-11ea-a532-0a2b3642575d
  volumeSnapshotClassName: ceph-snapclass
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1beta1
    kind: VolumeSnapshot
    name: snapshot-4333-staging
    namespace: nv-apps
status:
  creationTime: 1599742175127236000
  readyToUse: true
  restoreSize: 53687091200
  snapshotHandle: 0001-0009-rook-ceph-0000000000000001-141538e8-f364-11ea-a532-0a2b3642575d
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  generation: 1
  name: snapshot-4333-staging
  namespace: nv-apps
spec:
  source:
    persistentVolumeClaimName: instance-2067-staging
  volumeSnapshotClassName: ceph-snapclass
status:
  boundVolumeSnapshotContentName: snapcontent-48ac51de-07c2-4bcb-8b5b-813ac290d492
  readyToUse: true
  restoreSize: 50Gi
```

However, I encountered here
```
Failed to check and update snapshot content: failed to take snapshot
of the volume, 0001-0009-rook-ceph-0000000000000001-27ddbf75-f362-11ea-a532-0a2b3642575d:
"cannot create snapshot. Snapshot content snapcontent-48ac51de-07c2-4bcb-8b5b-813ac290d492
not bound to a snapshot"
```

Also found a new VolumeSnapshotContent object being created - seem like the VolumeSnapshot controller insists on creating  a new snapshot.

I managed to create the VolumeSnapshot and VolumeSnapshotContent as pre-provisioned, but in that case deleting the VolumeSnapshotContent does not trigger the deletion of the subvolume, and this defeats the purpose of using kubernetes objects to manage snapshots on CephFS.

**Comment by Madhu-1** [comment]
Deleting the snapshotcontent wont trigger any CSI calls, if you delete the volumesnapshot object it should trigger the DeleteSnapshot Request can you please check.

**Comment by Madhu-1** [comment]
I hope most of the questions are answered, closing this one

**Comment by tamas-ac** [comment]
Thanks for the help, I'm not sure VolumeSnapshots work according to the same logic as PVCs but I'll need to do some more testing.

**Comment by Madhu-1** [comment]
@tamas-ac Please feel free to reopen  if you need any help
