### ISSUE TITLE
make use of configurable fsType in the templates.

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1473]
With latest version (v2.0.1) of external provisioner, its now possible to configure `fstype` . The fstype on provisioned PVs no longer defaults to "ext4". A `defaultFStype` arg is added to the provisioner. Admins can also specify this `fstype` via storage class parameter. If `fstype` is set in storage class parameter, it will be used. The sidecar arg is only checked if fstype is not set in the SC param

Reference # https://github.com/kubernetes-csi/external-provisioner/pull/400

We could change our deployment template to have this in the examples and can also adjust the sidecar arg accordingly.

**Comment by Madhu-1** [comment]
this should be fixed in https://github.com/ceph/ceph-csi/pull/1653 reassigning to @agarwal-mudit  as he is working on his one.
