### ISSUE TITLE
Chart: Make nodeplugin mount points configurable

### ISSUE THREAD

**Issue by WolfspiritM** [ceph/ceph-csi#1475]
# Describe the feature you'd like to have #
Currently the mountPath for plugin-dir and mountpoint-dir for the nodeplugin is hardcoded to `/var/lib/kubelet/plugins` and `/var/lib/kubelet/pods`. When installing k8s via microk8s then that needs to be changed to `/var/snap/microk8s/common/var/lib/kubelet/...` otherwise mounting will fail. See #1067 

I'd like to have a setting for helm to set the required path. Currently I'm using:
```
helm install --namespace "ceph-csi-rbd" "ceph-csi-rbd" ceph-csi/ceph-csi-rbd /
--set "registrationDir=/var/snap/microk8s/common/var/lib/kubelet/plugins_registry" /
--set "pluginDir=/var/snap/microk8s/common/var/lib/kubelet/plugins" /
--set "socketDir=/var/snap/microk8s/common/var/lib/kubelet/plugins/rbd.csi.ceph.com"
```

NodePlugin doesn't care about the "pluginDir" yet which should be changed and also the "mountPointDir" should be available there, too.
```
helm install --namespace "ceph-csi-rbd" "ceph-csi-rbd" ceph-csi/ceph-csi-rbd /
--set "registrationDir=/var/snap/microk8s/common/var/lib/kubelet/plugins_registry" /
--set "pluginDir=/var/snap/microk8s/common/var/lib/kubelet/plugins" /
--set "socketDir=/var/snap/microk8s/common/var/lib/kubelet/plugins/rbd.csi.ceph.com" /
--set "mountPointDir=/var/snap/microk8s/common/var/lib/kubelet/pods"
```

For rbd for example change would be required here: https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml#L109
And here (including values.yaml): 
https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml#L112
https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml#L159

# What is the value to the end user? (why is it a priority?) #
Installing on microk8s for example doesn't work out of the box right now. This will allow it to work out of the box.

# How will we know we have a good solution? (acceptance criteria) #
Installing via helm will work for microk8s out of the box (by setting some additional values via helm parameters).

**Comment by Madhu-1** [comment]
The above mentioned is a volume mounts which will be mounted inside the container  not the actual volumes for volumes refer https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml#L144-L187

@Yuggupta27 or @pkalever can you please try to reproduce the issue and see if we need to fix anything? May be we may need to fix pods path as its hardcoded here https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml#L157-L160

can you please provide the logs and deployment templates if case if you are seeing any errors?

**Comment by chris-sanders** [comment]
Any progress/updates on this bug? I'm currently carrying a patch locally to make this work and would like to be able to follow upstream.

**Comment by Madhu-1** [comment]
@chris-sanders I will fix it and will make it to next release

**Comment by nixpanic** [comment]
@WolfspiritM @chris-sanders care to review and/or test  #1736?
