### ISSUE TITLE
Add storageclass definition and secret on file values

### ISSUE THREAD

**Issue by gabrilabs75** [ceph/ceph-csi#1483]
Hi all,
I would like to bring to your attention an helpful improvment giving the possibility to set the storageclass definition and the secret directly on file values.
In our case we need to create sc definition and secret applying custom yaml files after the installation of ceph-csi-rbd by helm chart.

Below are the versions of chart and appl. used in our environment based on k8s 1.9.1:
appl.: v3.1.0
chart: ceph-csi-rbd-3.1.0

**Comment by Madhu-1** [comment]
Good to have a single storageclass and secret in helm templates

**Comment by gabrilabs75** [comment]
Hi all,
any news about this request of improvment?

Regards,
Gabriele

**Comment by Madhu-1** [comment]
@yati1998 @Yuggupta27  can I assign this to you?

**Comment by Yuggupta27** [comment]
> @yati1998 @Yuggupta27 can I assign this to anyone of you?

Sure Madhu :)
