### ISSUE TITLE
ceph-fuse fails when FuseMountOptions is set

### ISSUE THREAD

**Issue by flarno11** [ceph/ceph-csi#1485]
# Describe the bug #

When setting `fuseMountOptions` (e.g. to "debug") in the storageClass, ceph-fuse fails with 
```
MountVolume.MountDevice failed for volume "pvc-xxx" : rpc error: code = Internal desc = an error (exit status 22) occurred while running ceph-fuse args: [/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-xxx/globalmount -m v2:xxx:3300,v2:yyy:3300,v2:1zzz:3300 -c /etc/ceph/ceph.conf -n client.csi-cephfs-node --keyfile=***stripped*** -r /volumes/csi/csi-vol-yyy/xxx -o nonempty ,debug --client_mds_namespace=sbdfs]
```

# Environment details #

- Image/version of Ceph CSI driver : 3.1.0
- Helm chart version : no helm in use
- Kernel version : 3.10.0
- Mounter used for mounting PVC : fuse
- Kubernetes cluster version : 1.17.5
- Ceph cluster version : 15.2.4

# Steps to reproduce #

1. Setup details: create storageClass with `fuseMountOptions: debug`
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: {{ ceph_csi__cluster_id }}
  fsName: {{ ceph_csi__ceph_fs_name }}
  pool: {{ ceph_cluster__osd_data_pool_name }}
  fuseMountOptions: debug
  ...
```

2. Deployment to trigger the issue: create a PVC and bind it to a POD
3. See error

# Actual results #

See error.

I suspect the error comes from the additional space between `-o nonempty` and ` ,debug` because `FuseMountOptions` is appended to `args` and not to the string "nonempty" in:
https://github.com/ceph/ceph-csi/blob/master/internal/cephfs/volumemounter.go#L161

# Expected behavior #

ceph-fuse command to success with mount options `-o nonempty,debug` (and not `-o nonempty, debug`).

# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

Logs of csi-cephfsplugin:
```
E0916 14:51:59.435354       1 nodeserver.go:175] ID: 47 Req-ID: 0001-0024-53231236-928f-474d-af5f-bd2a515acb86-0000000000000005-eec08d66-f828-11ea-8aa9-1e1c3ba5c902 failed to mount volume 0001-0024-53231236-928f-474d-af5f-bd2a515acb86-0000000000000005-eec08d66-f828-11ea-8aa9-1e1c3ba5c902: an error (exit status 22) occurred while running ceph-fuse args: [/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-cb090467-3469-4500-97c4-8a41d17a1678/globalmount -m v2:xxx:3300,v2:yyy:3300,v2:zzz:3300 -c /etc/ceph/ceph.conf -n client.csi-cephfs-node --keyfile=***stripped*** -r /volumes/csi/csi-vol-eec08d66-f828-11ea-8aa9-1e1c3ba5c902/68eee830-8ca1-4cbe-95e4-a9ea655ce095 -o nonempty ,debug --client_mds_namespace=sbdfs] Check dmesg logs if required.
E0916 14:51:59.435418       1 utils.go:163] ID: 47 Req-ID: 0001-0024-53231236-928f-474d-af5f-bd2a515acb86-0000000000000005-eec08d66-f828-11ea-8aa9-1e1c3ba5c902 GRPC error: rpc error: code = Internal desc = an error (exit status 22) occurred while running ceph-fuse args: [/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-cb090467-3469-4500-97c4-8a41d17a1678/globalmount -m v2:xxx:3300,v2:yyy:3300,v2:zzz:3300 -c /etc/ceph/ceph.conf -n client.csi-cephfs-node --keyfile=***stripped*** -r /volumes/csi/csi-vol-eec08d66-f828-11ea-8aa9-1e1c3ba5c902/68eee830-8ca1-4cbe-95e4-a9ea655ce095 -o nonempty ,debug --client_mds_namespace=sbdfs]
```

**Comment by Madhu-1** [comment]
@nixpanic can you please take a look at it?

**Comment by nixpanic** [comment]
> I suspect the error comes from the additional space between -o nonempty and ,debug because FuseMountOptions is appended to args and not to the string "nonempty" in:
> https://github.com/ceph/ceph-csi/blob/master/internal/cephfs/volumemounter.go#L161

Yes, that definitely is the problem.
