### ISSUE TITLE
ceph permissions

### ISSUE THREAD

**Issue by kfox1111** [ceph/ceph-csi#1488]
the docs at:
* https://github.com/ceph/ceph-csi/blob/master/docs/capabilities.md

Are very useful, but can be tightened further. There are some additional restrictions listed in these pages that could be applied:

* https://docs.ceph.com/en/latest/rbd/rbd-kubernetes/
* https://docs.ceph.com/en/latest/cephfs/client-auth/

**Comment by Madhu-1** [comment]
@kfox1111 can you please specify the additional caps you would like to see in cephcsi doc?

@yati1998 PTAL

**Comment by kfox1111** [comment]
I need to go through the other docs and create a more restricted account. Planning on doing that in the next couple of weeks so I'll get back to you. Just off the bat, it looks a little weird the cephfs node secret is recommended to get "mgr", "allow rw".
