### ISSUE TITLE
Why not implement NodeStageVolume/NodeUnstageVolume?

### ISSUE THREAD

**Issue by kindule** [ceph/ceph-csi#153]
Hi, all

I've read the code of [ceph-csi/pkg/rbd/nodeserver.go](https://github.com/ceph/ceph-csi/blob/master/pkg/rbd/nodeserver.go). And wonder why NodeStageVolume/NodeUnstageVolume not implemented. In my opinion, NodeStageVolume is responsible for mkfs/mount rbd to global path of the node and NodeUnstageVolume is responsible for umount rbd from global path of the node, which currently is the part of the NodePublishVolume/NodeUnpublishVolume. And that's make some complex flow in the NodePublishVolume/NodeUnpublishVolume.

If that need some contributor to fix it, I can make my best effort.

```go
// NodeStageVolume returns unimplemented response
func (ns *NodeServer) NodeStageVolume(ctx context.Context, req *csi.NodeStageVolumeRequest) (*csi.NodeStageVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "")
}

// NodeUnstageVolume returns unimplemented response
func (ns *NodeServer) NodeUnstageVolume(ctx context.Context, req *csi.NodeUnstageVolumeRequest) (*csi.NodeUnstageVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "")
}
```

**Comment by rootfs** [comment]
sure, PR is always welcome 👍

**Comment by Madhu-1** [comment]
@kindule are you working on this issue?

**Comment by Madhu-1** [comment]
during the `NodeStageVolume` the stagingPath is a directory, not file (this directory is created by kube not by csi driver). can we bind a /dev/rbdx` to the directory and again bind that directory to a file in nodePublish volume?

@j-griffith @dillaman @humblec @nixpanic  any idea how to solve this.

**Comment by obnoxxx** [comment]
In the block type case, can't we create a device file inside the stagingPath and map that into the container at publish?
