### ISSUE TITLE
Move RBD snapshot to a new document

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1533]
currently, RBD snapshot doc is part for the main example README file. https://github.com/ceph/ceph-csi/tree/master/examples#how-to-test-rbd-snapshot-feature. this need to be moved to a new file

**Comment by Madhu-1** [comment]
need to add a document for RBD cloning also it can be part of the same document

**Comment by yati1998** [comment]
@Madhu-1 is there any document already written for rbd clonning, or I need write myself. Let me know if you have any resource for that.

**Comment by Madhu-1** [comment]
@yati1998 nothing is there yet, you need to write new one

**Comment by yati1998** [comment]
@Madhu-1 okay sure.

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/blob/master/docs/cephfs-snap-clone.md rename this to snapshot-clone.md and add both cephfs and rbd inside this doc. it should be the same as expand, static pvc etc (refer doc folder)

**Comment by yati1998** [comment]
okay sure.
