### ISSUE TITLE
Enable Per PV unique key encryption when using "secret" based encryption for RBD 

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1537]
# Describe the feature you'd like to have #

While using secret based encryption at present, the PVCs are encrypted with a single passphrase which is in nodestage/provisioner secret. All the PVCs created on top of this sc will be encrypted with the same key/passphrase. The request here is to enable the encryption on this method with different keys. 

I could think of few solutions as below, but I dont see this as an proper solution to sort this issue out:

1) Create Secrets per PV by the CSI driver -> Not possible as CSI driver don't talk to the API server directly.
2) Update existing secret for PV in nodestage and nodeprovisioner secret -> Not possible as CSI driver don't talk to the API server directly.
3) Generate and Store it in PV volume context -> Not recommended as it should not contain sensitive information.
4) Generate and Store it in OMAP -> Whoever got access to ceph pool got complete access so this is not a recommended solution.
5) Generate and Store it in RBD image metadata -> whoever got access to the ceph pool or image got complete access, again this is not a recommended solution.
6) One other solution would be having a brand new sidecar or controller which does the secret injection, but this needs heavy thought and may not want to be considered in this repo.

Inviting thoughts if any.

@vasyl-purchel @dillaman @JohnStrunk @ShyamsundarR

**Comment by Madhu-1** [comment]
isn't it almost same as https://github.com/ceph/ceph-csi/issues/826

**Comment by nixpanic** [comment]
The new SecretsMetadataKMS provider that was added for testing #1908 should implement this.
