### ISSUE TITLE
ceph-cluster report client version is jewel when using rbd-csi.

### ISSUE THREAD

**Issue by taozix** [ceph/ceph-csi#1539]
# Describe the bug #
ceph-cluster will report client version is jewel when using rbd-csi.

# Environment details #

- Image/version of Ceph CSI driver :
  ceph-csi-2.1.0
- Kernel version :
  4.15.18-041518-generic
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
   krbd
- Kubernetes cluster version :
  v1.15.2
- Ceph cluster version :
  14.2.9

# Steps to reproduce #

1. Setup details: 
   Init k8s cluster, csi-rbd driver.
1. Deployment to trigger the issue '....'
   Create a deploy/sts, mounted with rbd using pvc.
1. See error
   on ceph cluster site:
   #: ceph daemon mon.ceph-XXX sessions

# Actual results #
   "MonSession(client.1083423 v1:192.168.159.100:0/2176455101 is open allow *, features 0x7018fb86aa42ada (**jewel**))",
Describe what happened

# Expected behavior #
  using ceph client luminous or higher version, rather jewel.

**Comment by Madhu-1** [comment]
duplicate of https://github.com/ceph/ceph-csi/issues/1462, updating the kernel version should fix it

**Comment by taozix** [comment]
thanks.
