### ISSUE TITLE
Record POOL information in Volume snapshot/content object,

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1540]
# Describe the bug #

While restoring a PVC from snapshot , this information come handy. Also in future we will have restore between pools ..etc supported/qualified. 

This is a request to record `pool` for other consumers and may not help CSI driver with the present scenario as we can derive the pool information from volume handle. However if the volume handle is taking another format this could be handy for CSI drivers too.

**Comment by Madhu-1** [comment]
```go
message CreateSnapshotResponse {
  // Contains all attributes of the newly created snapshot that are
  // relevant to the CO along with information required by the Plugin
  // to uniquely identify the snapshot. This field is REQUIRED.
  Snapshot snapshot = 1;
}

// Information about a specific snapshot.
message Snapshot {
  // This is the complete size of the snapshot in bytes. The purpose of
  // this field is to give CO guidance on how much space is needed to
  // create a volume from this snapshot. The size of the volume MUST NOT
  // be less than the size of the source snapshot. This field is
  // OPTIONAL. If this field is not set, it indicates that this size is
  // unknown. The value of this field MUST NOT be negative and a size of
  // zero means it is unspecified.
  int64 size_bytes = 1;

  // The identifier for this snapshot, generated by the plugin.
  // This field is REQUIRED.
  // This field MUST contain enough information to uniquely identify
  // this specific snapshot vs all other snapshots supported by this
  // plugin.
  // This field SHALL be used by the CO in subsequent calls to refer to
  // this snapshot.
  // The SP is NOT responsible for global uniqueness of snapshot_id
  // across multiple SPs.
  string snapshot_id = 2;

  // Identity information for the source volume. Note that creating a
  // snapshot from a snapshot is not supported here so the source has to
  // be a volume. This field is REQUIRED.
  string source_volume_id = 3;

  // Timestamp when the point-in-time snapshot is taken on the storage
  // system. This field is REQUIRED.
  .google.protobuf.Timestamp creation_time = 4;

  // Indicates if a snapshot is ready to use as a
  // `volume_content_source` in a `CreateVolumeRequest`. The default
  // value is false. This field is REQUIRED.
  bool ready_to_use = 5;
}
```
This cannot be done as there is no context to set in CreateSnapshotResponse 
https://github.com/container-storage-interface/spec/blob/master/spec.md

We have to make the pool as a parameter in snapshotclass

cc @dillaman @ShyamsundarR

**Comment by humblec** [comment]
Marking/recording the `pool` information in the `SnapshotClass` may not be the correct choice here. Because/by design the snapshotclass got a totally different lifecycle than the snapshot/content object. I have opened an upstream issue to get something similar to the PV volumeattribute in snapshotcontent object here https://github.com/kubernetes-csi/external-snapshotter/issues/379 and I believe that should be the ideal way of solving it.

**Comment by Madhu-1** [comment]
As we are planning to support the creation of a snapshot in a different pool, we need to take the pool parameter from the snapshot class.

**Comment by Madhu-1** [comment]
@humblec do we still need this issue or can we close this one?

**Comment by Madhu-1** [comment]
Closing this one as it's not possible without a change in CSI spec.
