### ISSUE TITLE
Support Restore or snapshot and clone operation between different Pools

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1541]
# Describe the feature you'd like to have #

Ceph allows to take snapshots in different pool and it also allow restore and clone operation in different pool. CSI driver could make use of this and allow the operations from our end too.

This issue track it.

**Comment by Madhu-1** [comment]
isn't it a duplicate of https://github.com/ceph/ceph-csi/issues/560?

**Comment by humblec** [comment]
yeah, let me close this.
