### ISSUE TITLE
Enable SC based passphrase while KMS is in use

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1562]
# Describe the feature you'd like to have #

At present, we create or generate passphrase for each and every request of PVC when KMS is in use. However at times, it comes handy ( may be to satisfy multi tenancy use case) that having a single `passphrase` for a group of PVCs ( SC based) . This issue track this feature request.

**Comment by humblec** [comment]
@vasyl-purchel please share your thought :+1:

**Comment by vasyl-purchel** [comment]
It shouldn't be hard to implement I believe (just use pvc id instead of volume id I guess) but I'm not entirely sure what benefit would it give.
Re-using same passphrase for many volumes is not recommended since it opens it to brute force attack on the passphrase... (i.e. you can guess it if you have enough of data) and not sure why it would be needed instead of passphrase per volume...

**Comment by humblec** [comment]
> It shouldn't be hard to implement I believe (just use pvc id instead of volume id I guess) but I'm not entirely sure what benefit would it give.

Indeed implementation side we could achieve or I am confident. :+1: 

> Re-using same passphrase for many volumes is not recommended since it opens it to brute force attack on the passphrase... (i.e. you can guess it if you have enough of data) and not sure why it would be needed instead of passphrase per volume...

I was trying to understand do we see  a use case for this requirement?  But from above, I interpret that, we dont see much value in that. I want to open this for further discussions or invite use cases from the community. 
Will keep it open for others to chime in with their thoughts too .

@dillaman @ShyamsundarR @Madhu-1

**Comment by nixpanic** [comment]
Is this not what is already available by setting the `encryptionPassphrase` in the Secret that is referred from the StorageClass? This was added with commit 166eaf700f8589536bb64709f9c9e0838ebdadd8 and works without a KMS.

**Comment by Madhu-1** [comment]
I don't see any value in implementing this feature with KMS. currently, we are generating a unique Key for each volume encryption. and it's a very secured one compared to use the same passphrase to encrypt multiple volumes.
