### ISSUE TITLE
question cephfs: What is the recommneded way of detecting issue with a mount?

### ISSUE THREAD

**Issue by strigazi** [ceph/ceph-csi#1583]
If I have a mounted a cephfs volume and it stops being accessible for any reason (eg I use ceph-fuse and the mount fails), it would be nice if something triggered the plugin to redo the mount.

I tried to add a liveness probe in my app that just does an ls in the mountpoint but the restart of the container is not setting up he mount again.

Any recommendations?

**Comment by strigazi** [comment]
We have cases where the client is evicted from the cluster and csi_liveness still returns 1.

I think a good metric could be a check per mount on the node, and either return a value per mount or a boolean for the whole node as it is now. If any of the mounts is not responding, return 0. Then we could have optionally nodeProblemDetector to mark the node as NotReady.

**Comment by strigazi** [comment]
ATM the liveness check only of the plugin is up https://github.com/ceph/ceph-csi/blob/master/internal/liveness/liveness.go#L40

**Comment by Madhu-1** [comment]
@strigazi currently ceph-fuse is having known issue when the plugin restarts we are investigating on the issue on how to solve the fuse client issue when plugin pod restarts. the liveness was not meant to solve this issue.

**Comment by strigazi** [comment]
@Madhu-1 Is this the known issue? https://github.com/ceph/ceph-csi/issues/792

Is there an open PR or issue about it?
