### ISSUE TITLE
failed to acquire lease cephfs-csi-ceph-com

### ISSUE THREAD

**Issue by Macrame** [ceph/ceph-csi#1592]
# Describe the bug #

Fail to start csi-cephfsplugin-provisioner. csi-provisioner prints log 
```
I1017 07:46:10.890075       1 controller.go:709] Using saving PVs to API server in background
I1017 07:46:10.890156       1 leaderelection.go:242] attempting to acquire leader lease  mars/cephfs-csi-ceph-com...
I1017 07:46:10.892571       1 leaderelection.go:352] lock is held by csi-cephfsplugin-provisioner-7b9c4677c-x9v7p and has not yet expired
I1017 07:46:10.892586       1 leaderelection.go:247] failed to acquire lease mars/cephfs-csi-ceph-com
I1017 07:46:10.892597       1 leader_election.go:172] new leader detected, current leader: csi-cephfsplugin-provisioner-7b9c4677c-x9v7p
I1017 07:46:21.537735       1 leaderelection.go:352] lock is held by csi-cephfsplugin-provisioner-7b9c4677c-x9v7p and has not yet expired
I1017 07:46:21.537750       1 leaderelection.go:247] failed to acquire lease mars/cephfs-csi-ceph-com
I1017 07:46:30.527751       1 leaderelection.go:352] lock is held by csi-cephfsplugin-provisioner-7b9c4677c-x9v7p and has not yet expired
...
```
# Environment details #

- Image/version of Ceph CSI driver : canary
- Helm chart version :
- Kernel version : 4.18.0-147.8.1.el8_1.x86_64 
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
- Kubernetes cluster version : v1.19.3
- Ceph cluster version : 15.2.4

**Comment by Macrame** [comment]
The PVC get Pending for ever. There is the description:
```
Events:
  Type    Reason                Age                  From                         Message
  ----    ------                ----                 ----                         -------
  Normal  ExternalProvisioning  4m5s (x62 over 19m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "ceph.com/cephfs" or manually created by system administrator

```

**Comment by Madhu-1** [comment]
cehpcsi provisioner works with leader election (3 pods will be running), to check leader please run `kubectl get leases -n <namespace>` ,once you find the leader (in your case its `csi-cephfsplugin-provisioner-7b9c4677c-x9v7p`  pod is the leader) please check csi-cephfsplugin  and csi-provisioner or csi-snapshotter logs of leader pod

**Comment by Madhu-1** [comment]
`ceph.com/cephfs` is not the proper provisioner cephfs provisioner name is `cephfs.csi.ceph.com` , are you sure you are using the correct storageclass?

**Comment by Macrame** [comment]
Sorry, I used the old [cephfs provisioner](https://github.com/kubernetes-retired/external-storage/tree/master/ceph/cephfs/deploy/rbac) in the last year. I am aware that repository became archived so I changed to use this [official one](https://github.com/ceph/ceph-csi/tree/master/deploy/cephfs/kubernetes) but forgot to modify the provisioner name.
My fault. You are so kind and professional!
