### ISSUE TITLE
Restore from snapshot

### ISSUE THREAD

**Issue by rollandf** [ceph/ceph-csi#163]
Hi,

I am trying to test the snapshot feature with RBD.
I am working with kubeadm, with k8s version 1.13.

Everything is fine while following the examples.
However, creating a PVC from a snapshot is not working from me.
The PVC is in pending state and I could not see anything in the logs.

Here is the yaml I tried:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-from-snap
spec:
  storageClassName: csi-rbd
  dataSource:
    name: rbd-pvc-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

**Comment by rootfs** [comment]
can you post logs from rbd provisioner, snapshotter and plugin containers?

**Comment by rollandf** [comment]
Here are the logs:

https://gist.github.com/rollandf/c00fade2ab8fb1af30f86ec66bd3d363

Tell if I missed something

**Comment by rootfs** [comment]
I see, you are using 0.3 images. 

For k8s 1.13+, you need csi-v1.0 images
https://github.com/ceph/ceph-csi/tree/csi-v1.0/deploy/rbd/kubernetes

**Comment by rollandf** [comment]
Thanks for updating the documentation, I will try with csi-v1.0 images.
Closing this issue.
