### ISSUE TITLE
Deploying Rook sometimes fails in the CI

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1636]
Sometimes deploying Rook fails, but no errors are available. The output looks like this:

```
...
configmap/rook-ceph-operator-config created
deployment.apps/rook-ceph-operator created
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1187  100  1187    0     0  21196      0 --:--:-- --:--:-- --:--:-- 21196
[Pipeline] }
```

and also
```
...
cephfilesystem.ceph.rook.io/myfs created
cephblockpool.ceph.rook.io/replicapool created
Wait for rook deploy... 0s
...
Checking CEPH cluster state: []
Wait for rook deploy... 45s
The connection to the server 192.168.39.248:8443 was refused - did you specify the right host or port?
error executing jsonpath "{.items[0].status.state}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].status.state}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```

More logging when deploying Rook is needed before this problem can be addressed.

**Comment by Madhu-1** [comment]
>Warning Failed 24s kubelet Error: ImagePullBackOff
Normal Pulling 10s (x2 over 25s) kubelet Pulling image "docker.io/ceph/ceph:v14.2.12
Warning Failed 10s (x2 over 25s) kubelet Failed to pull image "docker.io/ceph/ceph:v14.2.12": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
Warning Failed 10s (x2 over 25s) kubelet Error: ErrImagePull

Hitting the rook deployment issue at https://github.com/ceph/ceph-csi/pull/1924

**Comment by Rakshith-R** [comment]
> 2021-04-06 10:45:08.684883 E | ceph-cluster-controller: failed to reconcile. failed to reconcile cluster "my-cluster": failed to configure local ceph cluster: failed to create cluster: failed to start ceph monitors: failed to initialize ceph cluster info: failed to save mon keyring secret: failed to create secret for rook-ceph-mons-keyring: etcdserver: request timed out

> Error from server: error when creating "https://raw.githubusercontent.com/rook/rook/v1.4.9/cluster/examples/kubernetes/ceph/toolbox.yaml": etcdserver: request timed out

Multiple ci rook deployment fails at #1229

**Comment by nixpanic** [comment]
Failed again with [logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.19/detail/mini-e2e_k8s-1.19/2304/pipeline):
```
Loaded image: ceph/ceph:v16
deploy rook
Error from server: error when creating "https://raw.githubusercontent.com/rook/rook/v1.6.2/cluster/examples/kubernetes/ceph/common.yaml": etcdserver: request timed out
kubectl_retry -f https://raw.githubusercontent.com/rook/rook/v1.6.2/cluster/examples/kubernetes/ceph/common.yaml failed, will retry in 10 seconds
+++ kubectl get nodes
+++ kubectl -n rook-ceph get events
No resources found in rook-ceph namespace.
+++ kubectl -n rook-ceph describe pods
No resources found in rook-ceph namespace.
+++ kubectl -n rook-ceph logs -l app=rook-ceph-operator
+++ kubectl -n rook-ceph get CephClusters -oyaml
error: the server doesn't have a resource type "CephClusters"
+++ kubectl -n rook-ceph get CephFilesystems -oyaml
error: the server doesn't have a resource type "CephFilesystems"
+++ kubectl -n rook-ceph get CephBlockPools -oyaml
error: the server doesn't have a resource type "CephBlockPools"
+++ exit 1
++ kubectl get nodes
NAME       STATUS   ROLES    AGE     VERSION
minikube   Ready    master   7m52s   v1.19.13
++ kubectl -n rook-ceph get events
No resources found in rook-ceph namespace.
++ kubectl -n rook-ceph describe pods
No resources found in rook-ceph namespace.
++ kubectl -n rook-ceph logs -l app=rook-ceph-operator
++ kubectl -n rook-ceph get CephClusters -oyaml
error: the server doesn't have a resource type "CephClusters"
++ kubectl -n rook-ceph get CephFilesystems -oyaml
error: the server doesn't have a resource type "CephFilesystems"
++ kubectl -n rook-ceph get CephBlockPools -oyaml
error: the server doesn't have a resource type "CephBlockPools"
++ exit 1
script returned exit code 1
```

**Comment by nixpanic** [comment]
A similar problem happened at https://github.com/ceph/ceph-csi/pull/2322#issuecomment-892769083 ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.21/detail/mini-e2e_k8s-1.21/615/pipeline))
