### ISSUE TITLE
Missing doc about snapshots in CSI-v1.0 branch

### ISSUE THREAD

**Issue by rollandf** [ceph/ceph-csi#164]
Missing doc and snapshotter yaml files in CSI-v1.0 branch in examples directory.

**Comment by Madhu-1** [comment]
@rollandf we have yaml files for snapshot https://github.com/ceph/ceph-csi/blob/csi-v1.0/examples/rbd/snapshot.yaml

**Comment by rollandf** [comment]
I can do it if you want

**Comment by Madhu-1** [comment]
@rollandf sure PR's are most welcome :)

**Comment by Madhu-1** [comment]
Fixed by #170 

@rootfs can we close this one?
