### ISSUE TITLE
Feature request: grafana dashboard for metrics visualization

### ISSUE THREAD

**Issue by jisnardo** [ceph/ceph-csi#1642]
# Describe the feature you'd like to have #

What new functionality do you want?

> Grafana dashboard for metrics visualization.

# What is the value to the end user? (why is it a priority?) #

How would the end user gain value from having this feature?

> Add value information for monitoring.

# How will we know we have a good solution? (acceptance criteria) #

Add a list of criteria that should be met for this feature to be useful.

> A minimal dashboard would be enough to start like a template.

# Additional context #

> nodeplugin : https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-rbd/values.yaml#L127

> provisioner : https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-rbd/values.yaml#L54

> provisioner : https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-rbd/values.yaml#L127

Thanks.

**Comment by Madhu-1** [comment]
more metrics will be provided with https://github.com/ceph/ceph-csi/pull/1086
