### ISSUE TITLE
Cephfs: Failed to Delete snapshot when backend subvolume and snapshot is deleted

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1647]
## Describe the bug 

Failed to delete voluesnapshot when backend subvolume (pvc) and ceph fs subvolume snapshot is deleted

## steps to reproduce it
* Install ceph cluster which doesn't have the snapshot-retention feature (install rook+ceph from master branch)
* Create PVC
* Create snapshot
* Delete PVC ---> Here PVC deletion fails (as its having snapshots)
* Now go and delete the snapshot and subvolume manually
* Now check is PV delete after sometime
* Now try to delete volumesnapshot with kubectl (snapshot deletion will fail)

## Expected result

As the backend resources are deleted we need to return success to the user

```Logs
I1030 08:34:06.316306       1 utils.go:132] ID: 97 Req-ID: 0001-0009-rook-ceph-0000000000000001-911e53f0-1a81-11eb-911f-0242ac110007 GRPC call: /csi.v1.Controller/DeleteSnapshot
I1030 08:34:06.317052       1 utils.go:133] ID: 97 Req-ID: 0001-0009-rook-ceph-0000000000000001-911e53f0-1a81-11eb-911f-0242ac110007 GRPC request: {"secrets":"***stripped***","snapshot_id":"0001-0009-rook-ceph-0000000000000001-911e53f0-1a81-11eb-911f-0242ac110007"}
I1030 08:34:06.324740       1 omap.go:72] ID: 97 Req-ID: 0001-0009-rook-ceph-0000000000000001-911e53f0-1a81-11eb-911f-0242ac110007 got omap values: (pool="myfs-metadata", namespace="csi", name="csi.snap.911e53f0-1a81-11eb-911f-0242ac110007"): map[csi.imagename:csi-snap-911e53f0-1a81-11eb-911f-0242ac110007 csi.snapname:snapshot-bbaca9ef-2a37-4581-ba56-92c18fb22ad0 csi.source:csi-vol-8a672fe1-1a81-11eb-911f-0242ac110007]
E1030 08:34:06.330559       1 volume.go:95] ID: 97 Req-ID: 0001-0009-rook-ceph-0000000000000001-911e53f0-1a81-11eb-911f-0242ac110007 failed to get subvolume info for the vol csi-vol-8a672fe1-1a81-11eb-911f-0242ac110007: rados: ret=-2, No such file or directory: "subvolume 'csi-vol-8a672fe1-1a81-11eb-911f-0242ac110007' does not exist"
E1030 08:34:06.331019       1 utils.go:136] ID: 97 Req-ID: 0001-0009-rook-ceph-0000000000000001-911e53f0-1a81-11eb-911f-0242ac110007 GRPC error: rpc error: code = Internal desc = invalid command

```

**Comment by yati1998** [comment]
Hi,
I worked on reproducing the issue as mentioned in the description. And Below is the result that I got:
[yatipadia@localhost cephfs]$ kubectl get pvc
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
csi-cephfs-pvc   Bound    pvc-ca176a5a-08b3-4b9c-86e8-726b6aacaf94   1Gi        RWX            csi-cephfs-sc   5s
[yatipadia@localhost cephfs]$ kubectl delete pvc csi-cephfs-pvc
persistentvolumeclaim "csi-cephfs-pvc" deleted

The PVC is getting deleted as expected.

**Comment by Madhu-1** [comment]
@yati1998 this issue still exists. PTAL

**Comment by yati1998** [comment]
Sure @Madhu-1

**Comment by agarwal-mudit** [comment]
I guess we can't reproduce this bug the reason is,
1. If we use the latest rook-ceph version snapshot retention feature is enabled by default and thus pvc deletion will not fail.
2. If we don't use the latest version then snapshot creation itself will fail with this error:
< fs myfs with error API call not implemented server-side: No handler found for 'fs subvolume snapshot info'>

I guess we can simulate it only with older volumes. or I am missing something here? @Madhu-1

**Comment by Madhu-1** [comment]
> I guess we can't reproduce this bug the reason is,
> 
> 1. If we use the latest rook-ceph version snapshot retention feature is enabled by default and thus pvc deletion will not fail.
> 2. If we don't use the latest version then snapshot creation itself will fail with this error:
>    < fs myfs with error API call not implemented server-side: No handler found for 'fs subvolume snapshot info'>
> 
> I guess we can simulate it only with older volumes. or I am missing something here? @Madhu-1

@agarwal-mudit Yes in the Issue description I clearly mention that to reproduce the issue we need to **Install ceph cluster which doesn't have the snapshot-retention feature**
