### ISSUE TITLE
Add support to pass client certificates for KMS

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1648]
# Describe the feature you'd like to have #

What new functionality do you want?

Currently, we don't have any option to pass the client certificates when we are authenticating with the vault server. We need to provide an option for the admin to pass the client certificates which cephcsi can use for authentication.

# What is the value to the end user? (why is it a priority?) #

More secured way of communication with an external entity

**Comment by Madhu-1** [comment]
cc @vasyl-purchel @leseb

**Comment by leseb** [comment]
Client certificate and Client private key 👍

**Comment by vasyl-purchel** [comment]
hm... isn't CA enough in the secrets that is already available to have a TLS to KMS? or maybe I'm not getting the issue right...

**Comment by leseb** [comment]
> hm... isn't CA enough in the secrets that is already available to have a TLS to KMS? or maybe I'm not getting the issue right...

This is for the TLS listener, see the following options:

```
tls_require_and_verify_client_cert (string: "false") – Turns on client authentication for this listener; the listener will require a presented client cert that successfully validates against system CAs.

tls_client_ca_file (string: "") – PEM-encoded Certificate Authority file used for checking the authenticity of client.
```

From https://www.vaultproject.io/docs/configuration/listener/tcp.html#tls_disable_client_certs

**Comment by nixpanic** [comment]
#1694 rewrites the communication with Vault to use the [libopenstorage/secrets API](https://github.com/libopenstorage/secrets/). Hopefully this makes it easier to add support for the client certificate and key.
