### ISSUE TITLE
After reboot host, FailedMount PersistentVolumeClaim (CSI)

### ISSUE THREAD

**Issue by denitol** [ceph/ceph-csi#165]
After rebooting host, my POD doesn't mount PVC 

I saw, logs:
`rpc error: code = DeadlineExceeded desc = context deadline exceeded`

and logs docker:
`kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded`

Helps, service docker restart

**Comment by rootfs** [comment]
can you post the rbd (or cephfs) plugin logs?

**Comment by denitol** [comment]
-c driver-registrar                     
`                                                                                                                                              I0205 11:54:06.175695    3621 main.go:120] Version: v0.3.0-0-g8dd4550d
I0205 11:54:06.183084    3621 main.go:135] Attempting to open a gRPC connection with: "/var/lib/kubelet/plugins/csi-rbdplugin/csi.sock"
I0205 11:54:06.183094    3621 connection.go:68] Connecting to /var/lib/kubelet/plugins/csi-rbdplugin/csi.sock
I0205 11:54:06.211846    3621 connection.go:95] Still trying, connection is CONNECTING
I0205 11:54:06.211978    3621 connection.go:95] Still trying, connection is TRANSIENT_FAILURE
I0205 11:54:07.219463    3621 connection.go:95] Still trying, connection is TRANSIENT_FAILURE
I0205 11:54:08.268501    3621 connection.go:92] Connected
I0205 11:54:08.268523    3621 main.go:143] Calling CSI driver to discover driver name.
I0205 11:54:08.268555    3621 connection.go:136] GRPC call: /csi.v0.Identity/GetPluginInfo
I0205 11:54:08.268561    3621 connection.go:137] GRPC request:
I0205 11:54:08.288980    3621 connection.go:139] GRPC response: name:"csi-rbdplugin" vendor_version:"0.3.0"
I0205 11:54:08.289033    3621 connection.go:140] GRPC error: <nil>
I0205 11:54:08.289040    3621 main.go:151] CSI driver name: "csi-rbdplugin"
I0205 11:54:08.289046    3621 main.go:154] Calling CSI driver to discover node ID.
I0205 11:54:08.289058    3621 connection.go:136] GRPC call: /csi.v0.Node/NodeGetId
I0205 11:54:08.289062    3621 connection.go:137] GRPC request:
I0205 11:54:08.289451    3621 connection.go:139] GRPC response: node_id:"master"
I0205 11:54:08.289486    3621 connection.go:140] GRPC error: <nil>
I0205 11:54:08.289492    3621 main.go:162] CSI driver node ID: "master"
I0205 11:54:08.289536    3621 main.go:185] Starting Registration Server at: /registration/csi-rbdplugin-reg.sock
I0205 11:54:08.289578    3621 main.go:192] Registration Server started at: /registration/csi-rbdplugin-reg.sock
I0205 11:54:08.290922    3621 main.go:93] Received GetInfo call: &InfoRequest{}
I0205 11:54:08.593231    3621 main.go:103] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
`

-c csi-rbdplugin
`
Watchers:
	watcher=10.16.184.2:0/3356087603 client.335848 cookie=2
I0205 12:10:38.160174    4024 rbd_util.go:170] rbd: status pvc-9eecb201289e11e9 using mon 192.168.1.1:6789,192.168.1.2:6789,192.168.1.3:6789, pool rbd id admin key *
I0205 12:10:38.240097    4024 rbd_util.go:189] rbd: watchers on pvc-9eecb201289e11e9: 2019-02-05 12:10:38.174194 7fcf99b71d40 -1 did not load config file, using default settings.
2019-02-05 12:10:38.179275 7fcf99b71d40 -1 Errors while parsing config file!
2019-02-05 12:10:38.179284 7fcf99b71d40 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory
2019-02-05 12:10:38.179285 7fcf99b71d40 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory
2019-02-05 12:10:38.179286 7fcf99b71d40 -1 parse_file: cannot open ceph.conf: (2) No such file or directory
2019-02-05 12:10:38.180714 7fcf99b71d40 -1 Errors while parsing config file!
2019-02-05 12:10:38.180724 7fcf99b71d40 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory
2019-02-05 12:10:38.180725 7fcf99b71d40 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory
2019-02-05 12:10:38.180726 7fcf99b71d40 -1 parse_file: cannot open ceph.conf: (2) No such file or directory
2019-02-05 12:10:38.206468 7fcf99b71d40 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
Watchers:
	watcher=10.16.184.2:0/3356087603 client.335848 cookie=1
I0205 12:10:38.240129    4024 keymutex.go:59] UnlockKey(...) called for id "rbd/pvc-9eecb201289e11e9"
I0205 12:10:38.240147    4024 keymutex.go:66] UnlockKey(...) for id. Mutex found, trying to unlock it. "rbd/pvc-9eecb201289e11e9"
I0205 12:10:38.240154    4024 keymutex.go:69] UnlockKey(...) for id "rbd/pvc-9eecb201289e11e9" completed.
I0205 12:10:38.240160    4024 keymutex.go:59] UnlockKey(...) called for id "/var/lib/kubelet/pods/d0a45204-2923-11e9-8dbe-0050562b002b/volumes/kubernetes.io~csi/pvc-9eecb201289e11e9/mount"
I0205 12:10:38.240171    4024 keymutex.go:66] UnlockKey(...) for id. Mutex found, trying to unlock it. "/var/lib/kubelet/pods/d0a45204-2923-11e9-8dbe-0050562b002b/volumes/kubernetes.io~csi/pvc-9eecb201289e11e9/mount"
I0205 12:10:38.240178    4024 keymutex.go:69] UnlockKey(...) for id "/var/lib/kubelet/pods/d0a45204-2923-11e9-8dbe-0050562b002b/volumes/kubernetes.io~csi/pvc-9eecb201289e11e9/mount" completed.
E0205 12:10:38.240187    4024 utils.go:100] GRPC error: rbd image rbd/pvc-9eecb201289e11e9 is still being used
I0205 12:10:42.915961    4024 rbd_util.go:170] rbd: status pvc-11589d68286911e9 using mon 192.168.1.1:6789,192.168.1.2:6789,192.168.1.3:6789, pool rbd id admin key *
I0205 12:10:42.986794    4024 rbd_util.go:189] rbd: watchers on pvc-11589d68286911e9: 2019-02-05 12:10:42.930796 7f6cf58b2d40 -1 did not load config file, using default settings.
2019-02-05 12:10:42.935513 7f6cf58b2d40 -1 Errors while parsing config file!
2019-02-05 12:10:42.935522 7f6cf58b2d40 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory
2019-02-05 12:10:42.935523 7f6cf58b2d40 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory
2019-02-05 12:10:42.935524 7f6cf58b2d40 -1 parse_file: cannot open ceph.conf: (2) No such file or directory
2019-02-05 12:10:42.937417 7f6cf58b2d40 -1 Errors while parsing config file!
2019-02-05 12:10:42.937425 7f6cf58b2d40 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory
2019-02-05 12:10:42.937425 7f6cf58b2d40 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory
2019-02-05 12:10:42.937426 7f6cf58b2d40 -1 parse_file: cannot open ceph.conf: (2) No such file or directory
2019-02-05 12:10:42.962895 7f6cf58b2d40 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
Watchers:
	watcher=10.16.184.2:0/3356087603 client.335848 cookie=2
I0205 12:10:57.744845    4024 rbd_util.go:170] rbd: status pvc-11589d68286911e9 using mon 192.168.1.1:6789,192.168.1.2:6789,192.168.1.3:6789, pool rbd id admin key *
I0205 12:10:57.815428    4024 rbd_util.go:189] rbd: watchers on pvc-11589d68286911e9: 2019-02-05 12:10:57.758475 7f3817cd3d40 -1 did not load config file, using default settings.
2019-02-05 12:10:57.763387 7f3817cd3d40 -1 Errors while parsing config file!
2019-02-05 12:10:57.763396 7f3817cd3d40 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory
2019-02-05 12:10:57.763397 7f3817cd3d40 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory
2019-02-05 12:10:57.763398 7f3817cd3d40 -1 parse_file: cannot open ceph.conf: (2) No such file or directory
2019-02-05 12:10:57.764948 7f3817cd3d40 -1 Errors while parsing config file!
2019-02-05 12:10:57.764956 7f3817cd3d40 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory
2019-02-05 12:10:57.764956 7f3817cd3d40 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory
2019-02-05 12:10:57.764957 7f3817cd3d40 -1 parse_file: cannot open ceph.conf: (2) No such file or directory
2019-02-05 12:10:57.791878 7f3817cd3d40 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
Watchers:
	watcher=10.16.184.2:0/3356087603 client.335848 cookie=2
I0205 12:10:57.815449    4024 keymutex.go:59] UnlockKey(...) called for id "rbd/pvc-11589d68286911e9"
I0205 12:10:57.815474    4024 keymutex.go:66] UnlockKey(...) for id. Mutex found, trying to unlock it. "rbd/pvc-11589d68286911e9"
I0205 12:10:57.815480    4024 keymutex.go:69] UnlockKey(...) for id "rbd/pvc-11589d68286911e9" completed.
I0205 12:10:57.815486    4024 keymutex.go:59] UnlockKey(...) called for id "/var/lib/kubelet/pods/656fdb80-293e-11e9-b9bd-0050562b002b/volumes/kubernetes.io~csi/pvc-11589d68286911e9/mount"
I0205 12:10:57.815497    4024 keymutex.go:66] UnlockKey(...) for id. Mutex found, trying to unlock it. "/var/lib/kubelet/pods/656fdb80-293e-11e9-b9bd-0050562b002b/volumes/kubernetes.io~csi/pvc-11589d68286911e9/mount"
I0205 12:10:57.815505    4024 keymutex.go:69] UnlockKey(...) for id "/var/lib/kubelet/pods/656fdb80-293e-11e9-b9bd-0050562b002b/volumes/kubernetes.io~csi/pvc-11589d68286911e9/mount" completed.
E0205 12:10:57.815514    4024 utils.go:100] GRPC error: rbd image rbd/pvc-11589d68286911e9 is still being used
I0205 12:10:57.815547    4024 keymutex.go:53] LockKey(...) for id "/var/lib/kubelet/pods/656fdb80-293e-11e9-b9bd-0050562b002b/volumes/kubernetes.io~csi/pvc-11589d68286911e9/mount" completed.
I0205 12:10:57.815578    4024 nsenter_mount.go:166] findmnt: directory /var/lib/kubelet/pods/656fdb80-293e-11e9-b9bd-0050562b002b/volumes/kubernetes.io~csi/pvc-11589d68286911e9/mount does not exist
I0205 12:10:57.815666    4024 keymutex.go:50] LockKey(...) called for id "rbd/pvc-11589d68286911e9"
I0205 12:10:57.815674    4024 keymutex.go:53] LockKey(...) for id "rbd/pvc-11589d68286911e9" completed.
I0205 12:10:57.817341    4024 rbd_util.go:170] rbd: status pvc-11589d68286911e9 using mon 192.168.1.1:6789,192.168.1.2:6789,192.168.1.3:6789, pool rbd id admin key *
I0205 12:10:57.897885    4024 rbd_util.go:189] rbd: watchers on pvc-11589d68286911e9: 2019-02-05 12:10:57.841254 7fe75cb23d40 -1 did not load config file, using default settings.
`

**Comment by denitol** [comment]
log in messages
```
 kubelet: E0205 18:02:36.299719 1579277 kubelet_volumes.go:154] Orphaned pod "6fc1e414-2930-11e9-907f-0050562c0156" found, but volume paths are still present on disk : There were a total of 15 errors similar to this. Turn up verbosity to see them.
```

I tried remove /var/lib/kubelet/pods/6fc1e414-2930-11e9-907f-0050562c0156  and restart kubelet 

but still not helps

**Comment by rootfs** [comment]
cc @dillaman, will the watcher go away, eventually?

**Comment by lelvisl** [comment]
Any updates?

**Comment by Madhu-1** [comment]
after rebooting node (used minikube  for testing) not able to ssh  to the machine getting below  logs

```
[ 4092.107545] libceph: mon0 10.99.220.223:6789 connect error
[ 4106.149074] libceph: connect 10.100.166.145:6789 error -101
[ 4106.155752] libceph: mon1 10.100.166.145:6789 connect error
[ 4107.094929] libceph: connect 10.100.166.145:6789 error -101
[ 4107.100700] libceph: mon1 10.100.166.145:6789 connect error
[ 4108.095015] libceph: connect 10.100.166.145:6789 error -101
[ 4108.100871] libceph: mon1 10.100.166.145:6789 connect error
[ 4110.096731] libceph: connect 10.100.166.145:6789 error -101
[ 4110.098049] libceph: mon1 10.100.166.145:6789 connect error
[ 4114.101033] libceph: connect 10.100.166.145:6789 error -101
[ 4114.105468] libceph: mon1 10.100.166.145:6789 connect error
[ 4122.116812] libceph: connect 10.100.166.145:6789 error -101
[ 4122.120847] libceph: mon1 10.100.166.145:6789 connect error
[ 4136.164964] libceph: connect 10.111.180.253:6789 error -101
[ 4136.171956] libceph: mon2 10.111.180.253:6789 connect error
[ 4137.094630] libceph: connect 10.111.180.253:6789 error -101
[ 4137.100686] libceph: mon2 10.111.180.253:6789 connect error
[ 4138.094736] libceph: connect 10.111.180.253:6789 error -101
[ 4138.101876] libceph: mon2 10.111.180.253:6789 connect error
[ 4140.096610] libceph: connect 10.111.180.253:6789 error -101
[ 4140.102384] libceph: mon2 10.111.180.253:6789 connect error
[ 4144.100727] libceph: connect 10.111.180.253:6789 error -101
[ 4144.105774] libceph: mon2 10.111.180.253:6789 connect error
[ 4152.100483] libceph: connect 10.111.180.253:6789 error -101
[ 4152.104945] libceph: mon2 10.111.180.253:6789 connect error
[ 4166.116137] libceph: connect 10.100.166.145:6789 error -101
[ 4166.116915] libceph: mon1 10.100.166.145:6789 connect error
[ 4167.094235] libceph: connect 10.100.166.145:6789 error -101
[ 4167.098771] libceph: mon1 10.100.166.145:6789 connect error
[ 4168.094108] libceph: connect 10.100.166.145:6789 error -101
[ 4168.094857] libceph: mon1 10.100.166.145:6789 connect error
[ 4170.096122] libceph: connect 10.100.166.145:6789 error -101
[ 4170.096896] libceph: mon1 10.100.166.145:6789 connect error
[ 4174.100281] libceph: connect 10.100.166.145:6789 error -101
[ 4174.104651] libceph: mon1 10.100.166.145:6789 connect error
[ 4182.116478] libceph: connect 10.100.166.145:6789 error -101
[ 4182.123448] libceph: mon1 10.100.166.145:6789 connect error
[ 4196.195913] libceph: connect 10.99.220.223:6789 error -101
[ 4196.196726] libceph: mon0 10.99.220.223:6789 connect error
[ 4197.093842] libceph: connect 10.99.220.223:6789 error -101
[ 4197.095004] libceph: mon0 10.99.220.223:6789 connect error
[ 4198.093989] libceph: connect 10.99.220.223:6789 error -101
[ 4198.099234] libceph: mon0 10.99.220.223:6789 connect error
[ 4200.096065] libceph: connect 10.99.220.223:6789 error -101
[ 4200.099809] libceph: mon0 10.99.220.223:6789 connect error
[ 4200.503967] INFO: task umount:4537 blocked for more than 120 seconds.
[ 4200.508603] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 4200.514909] umount          D ffff8aabbb2f8000     0  4537      1 0x00000084
[ 4200.520282] Call Trace:
[ 4200.522447]  [<ffffffffbe54e730>] ? __blk_mq_delay_run_hw_queue+0xa0/0x110
[ 4200.527958]  [<ffffffffbe965d60>] ? bit_wait+0x50/0x50
[ 4200.535069]  [<ffffffffbe967c49>] schedule+0x29/0x70
[ 4200.537018]  [<ffffffffbe965721>] schedule_timeout+0x221/0x2d0
[ 4200.538911]  [<ffffffffbe26a0ce>] ? kvm_clock_get_cycles+0x1e/0x20
[ 4200.541102]  [<ffffffffbe965d60>] ? bit_wait+0x50/0x50
[ 4200.542906]  [<ffffffffbe9672ed>] io_schedule_timeout+0xad/0x130
[ 4200.544419]  [<ffffffffbe967388>] io_schedule+0x18/0x20
[ 4200.545646]  [<ffffffffbe965d71>] bit_wait_io+0x11/0x50
[ 4200.546616]  [<ffffffffbe965897>] __wait_on_bit+0x67/0x90
[ 4200.547647]  [<ffffffffbe965d60>] ? bit_wait+0x50/0x50
[ 4200.548619]  [<ffffffffbe965a01>] out_of_line_wait_on_bit+0x81/0xb0
[ 4200.549745]  [<ffffffffbe2c2dc0>] ? wake_bit_function+0x40/0x40
[ 4200.550776]  [<ffffffffbe47c658>] __sync_dirty_buffer+0xb8/0xe0
[ 4200.551865]  [<ffffffffbe47c693>] sync_dirty_buffer+0x13/0x20
[ 4200.552934]  [<ffffffffc0399020>] ext4_commit_super+0x1c0/0x270 [ext4]
[ 4200.554054]  [<ffffffffc039a16d>] ext4_put_super+0x30d/0x3e0 [ext4]
[ 4200.555318]  [<ffffffffbe443dbd>] generic_shutdown_super+0x6d/0x100
[ 4200.556468]  [<ffffffffbe444227>] kill_block_super+0x27/0x70
[ 4200.557542]  [<ffffffffbe44456e>] deactivate_locked_super+0x4e/0x70
[ 4200.558789]  [<ffffffffbe444cf6>] deactivate_super+0x46/0x60
[ 4200.560001]  [<ffffffffbe46326f>] cleanup_mnt+0x3f/0x80
[ 4200.561029]  [<ffffffffbe463302>] __cleanup_mnt+0x12/0x20
[ 4200.562117]  [<ffffffffbe2be79b>] task_work_run+0xbb/0xe0
[ 4200.563170]  [<ffffffffbe22bc65>] do_notify_resume+0xa5/0xc0
[ 4200.564232]  [<ffffffffbe975124>] int_signal+0x12/0x17
[ 4204.099789] libceph: connect 10.99.220.223:6789 error -101
[ 4204.100823] libceph: mon0 10.99.220.223:6789 connect error
[ 4212.099762] libceph: connect 10.99.220.223:6789 error -101
[ 4212.102726] libceph: mon0 10.99.220.223:6789 connect error
```

@rootfs ^^

**Comment by Madhu-1** [comment]
some more logs

```
[ 4294.099400] libceph: connect 10.111.180.253:6789 error -101
[ 4294.105922] libceph: mon2 10.111.180.253:6789 connect error
[ 4295.884617] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[ 4295.915012] systemd-shutdown[1]: Sending SIGKILL to PID 4537 (umount).
[ 4295.919393] systemd-shutdown[1]: Sending SIGKILL to PID 4558 (systemd-shutdow).
[ 4302.114901] libceph: connect 10.111.180.253:6789 error -101
[ 4302.116325] libceph: mon2 10.111.180.253:6789 connect error
[ 4305.924533] systemd-shutdown[1]: Unmounting file systems.
[ 4305.933232] systemd-shutdown[4559]: Remounting '/' read-only in with options 'seclabel,data=ordered'.
[ 4306.016285] EXT4-fs (vda1): re-mounted. Opts: data=ordered
[ 4306.047002] systemd-shutdown[1]: All filesystems unmounted.
[ 4306.048051] systemd-shutdown[1]: Deactivating swaps.
[ 4306.049193] systemd-shutdown[1]: All swaps deactivated.
[ 4306.050320] systemd-shutdown[1]: Detaching loop devices.
[ 4306.052627] systemd-shutdown[1]: All loop devices detached.
[ 4306.053958] systemd-shutdown[1]: Detaching DM devices.
[ 4306.055218] systemd-shutdown[1]: All DM devices detached.
[ 4306.058699] systemd-shutdown[1]: Syncing filesystems and block devices.
[ 4316.130756] libceph: connect 10.99.220.223:6789 error -101
[ 4316.132839] libceph: mon0 10.99.220.223:6789 connect error
[ 4317.092895] libceph: connect 10.99.220.223:6789 error -101
[ 4317.099828] libceph: mon0 10.99.220.223:6789 connect error
[ 4318.092889] libceph: connect 10.99.220.223:6789 error -101
[ 4318.098432] libceph: mon0 10.99.220.223:6789 connect error
[ 4320.094957] libceph: connect 10.99.220.223:6789 error -101
[ 4320.103035] libceph: mon0 10.99.220.223:6789 connect error
[ 4320.563697] INFO: task umount:4537 blocked for more than 120 seconds.
[ 4320.565824] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 4320.569170] umount          D ffff8aabbb2f8000     0  4537      1 0x00000084
[ 4320.572328] Call Trace:
[ 4320.573616]  [<ffffffffbe54e730>] ? __blk_mq_delay_run_hw_queue+0xa0/0x110
[ 4320.576436]  [<ffffffffbe965d60>] ? bit_wait+0x50/0x50
[ 4320.578414]  [<ffffffffbe967c49>] schedule+0x29/0x70
[ 4320.580269]  [<ffffffffbe965721>] schedule_timeout+0x221/0x2d0
[ 4320.582080]  [<ffffffffbe26a0ce>] ? kvm_clock_get_cycles+0x1e/0x20
[ 4320.584407]  [<ffffffffbe965d60>] ? bit_wait+0x50/0x50
[ 4320.585894]  [<ffffffffbe9672ed>] io_schedule_timeout+0xad/0x130
[ 4320.587603]  [<ffffffffbe967388>] io_schedule+0x18/0x20
[ 4320.589398]  [<ffffffffbe965d71>] bit_wait_io+0x11/0x50
[ 4320.591384]  [<ffffffffbe965897>] __wait_on_bit+0x67/0x90
[ 4320.592984]  [<ffffffffbe965d60>] ? bit_wait+0x50/0x50
[ 4320.594975]  [<ffffffffbe965a01>] out_of_line_wait_on_bit+0x81/0xb0
[ 4320.597214]  [<ffffffffbe2c2dc0>] ? wake_bit_function+0x40/0x40
[ 4320.598905]  [<ffffffffbe47c658>] __sync_dirty_buffer+0xb8/0xe0
[ 4320.601482]  [<ffffffffbe47c693>] sync_dirty_buffer+0x13/0x20
[ 4320.603259]  [<ffffffffc0399020>] ext4_commit_super+0x1c0/0x270 [ext4]
[ 4320.605389]  [<ffffffffc039a16d>] ext4_put_super+0x30d/0x3e0 [ext4]
[ 4320.607285]  [<ffffffffbe443dbd>] generic_shutdown_super+0x6d/0x100
[ 4320.608968]  [<ffffffffbe444227>] kill_block_super+0x27/0x70
[ 4320.610252]  [<ffffffffbe44456e>] deactivate_locked_super+0x4e/0x70
[ 4320.612027]  [<ffffffffbe444cf6>] deactivate_super+0x46/0x60
[ 4320.613608]  [<ffffffffbe46326f>] cleanup_mnt+0x3f/0x80
[ 4320.614914]  [<ffffffffbe463302>] __cleanup_mnt+0x12/0x20
[ 4320.616565]  [<ffffffffbe2be79b>] task_work_run+0xbb/0xe0
[ 4320.617928]  [<ffffffffbe22bc65>] do_notify_resume+0xa5/0xc0
[ 4320.619275]  [<ffffffffbe975124>] int_signal+0x12/0x17
[ 4324.098719] libceph: connect 10.99.220.223:6789 error -101
[ 4324.100981] libceph: mon0 10.99.220.223:6789 connect error
[ 4332.098988] libceph: connect 10.99.220.223:6789 error -101
[ 4332.105384] libceph: mon0 10.99.220.223:6789 connect error
[ 4336.064359] systemd-shutdown[1]: Syncing filesystems and block devices - timed out, issuing SIGKILL to PID 4561.
[ 4336.076287] systemd-shutdown[1]: Rebooting.
[ 4336.080817] Unregister pv shared memory for cpu 2
[ 4336.080828] Unregister pv shared memory for cpu 3
[ 4336.080935] Unregister pv shared memory for cpu 0
[ 4336.095831] Unregister pv shared memory for cpu 1
[ 4336.102225] kvm: exiting hardware virtualization
[ 4336.120057] Restarting system.
[ 4336.124212] reboot: machine restart
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 3.10.0-957.1.3.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 29 14:49:43 UTC 2018
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-3.10.0-957.1.3.el7.x86_64 root=UUID=a7d2bb19-cbc9-415f-b55b-f94aec100256 ro no_timer_check console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 elevator=noop crashkernel=auto LANG=en_US.UTF-8
[    0.000000] e820: BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
[    0.000000] BIOS-e820: [mem 0x000000000009fc00-0x000000000009ffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000000f0000-0x00000000000fffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x00000000bffd3fff] usable
[    0.000000] BIOS-e820: [mem 0x00000000bffd4000-0x00000000bfffffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000feffc000-0x00000000feffffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000fffc0000-0x00000000ffffffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000100000000-0x000000013f5fffff] usable
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] SMBIOS 2.8 present.
```

**Comment by Madhu-1** [comment]
after few minutes of waiting all pods came  into running state

```
kubectl get  po
NAME                          READY   STATUS    RESTARTS   AGE
csi-rbdplugin-attacher-0      1/1     Running   1          21m
csi-rbdplugin-gbxt2           2/2     Running   3          21m
csi-rbdplugin-provisioner-0   3/3     Running   3          21m
csirbd-demo-pod               1/1     Running   1          10m
```

note: used  csi v1.0.0 images

**Comment by yanchicago** [comment]
Any workaround?

**Comment by humblec** [comment]
> after few minutes of waiting all pods came into running state
> 
> ```
> kubectl get  po
> NAME                          READY   STATUS    RESTARTS   AGE
> csi-rbdplugin-attacher-0      1/1     Running   1          21m
> csi-rbdplugin-gbxt2           2/2     Running   3          21m
> csi-rbdplugin-provisioner-0   3/3     Running   3          21m
> csirbd-demo-pod               1/1     Running   1          10m
> ```
> 
> note: used csi v1.0.0 images

Closing this one as this is no longer an issue. Please feel free to reopen if the issue persists.
