### ISSUE TITLE
rook ceph hang on reboot, fails to mount CephFS volume

### ISSUE THREAD

**Issue by ttulong** [ceph/ceph-csi#1650]
# Describe the bug #

System hang on reboot when it is  consuming the PVC created by rook-ceph
# Environment details #

- Image/version of Ceph CSI driver : 3.1.0
- Helm chart version : n/a
- Kernel version : Sles 12.3 (4.4) Redhat 7.8 (3.10)
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : kernel
- Kubernetes cluster version : 1.17
- Ceph cluster version : 15.2.4

# Steps to reproduce #

1. Setup details: '...'
1.2.5, having the same issue. 
```
kubectl apply -f common.yaml
kubectl apply -f operator.yaml
kubectl apply -f cluster.yaml
```
Follow guide line to upgrade to 1.4.2 and still seeing the hang issue.

1. Deployment to trigger the issue '....'
no issue
1. See error
no error on the deployment,

# Actual results #

Describe what happened
System hang and on reboot when VM is consuming PVC created by rook-ceph

# Expected behavior #

VM reboot normally

# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC resize please attach complete logs of below containers.

- csi-resizer and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in snapshot creation and deletion please attach complete logs
of below containers.

- csi-snapshotter and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC mounting please attach complete logs of below containers.

- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
  plugin pod from the node where the mount is failing.

- if required attach dmesg logs.

```
Oct 29 22:42:08 nodename kernel: libceph: mon1 10.43.175.61:6789 connect error
Oct 29 22:42:08 nodename kernel: libceph: connect 10.43.175.61:6789 error -101
Oct 29 22:42:04 nodename kernel: libceph: mon1 10.43.175.61:6789 connect error
Oct 29 22:42:04 nodename kernel: libceph: connect 10.43.175.61:6789 error -101
Oct 29 22:42:02 nodename kernel: libceph: mon1 10.43.175.61:6789 connect error
Oct 29 22:42:02 nodename kernel: libceph: connect 10.43.175.61:6789 error -101
Oct 29 22:42:01 nodename kernel: libceph: mon1 10.43.175.61:6789 connect error
Oct 29 22:42:01 nodename kernel: libceph: connect 10.43.175.61:6789 error -101
Oct 29 22:42:00 nodename kernel: libceph: mon1 10.43.175.61:6789 connect error
Oct 29 22:42:00 nodename kernel: libceph: connect 10.43.175.61:6789 error -101
```

**Note:-** If its a rbd issue please provide only rbd related logs, if its a
cephfs issue please provide cephfs logs.

# Additional context #

```
mount|grep ceph

10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-c47b676c-f2df-11ea-9dcc-0a580a2a0bae/637920ff-bb45-4d4a-9bb6-2757fdff09e6 on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e34048d4-adae-4999-834f-06f64fd770d7/globalmount type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cep fs,wsize=33554432,_netdev)
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-c47f5490-f2df-11ea-9dcc-0a580a2a0bae/2278e388-c7bb-4a76-8e6e-5651d6a3bb69 on /var/lib/kubelet/pods/8c50c066-1ed4-47b4-b746-7500acfaddb3/volumes/kubernetes.io~csi/pvc-3f933360-34e4-43bf-bcd6-5bd1d566f4b9/mount type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432,_netdev)
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-c47b676c-f2df-11ea-9dcc-0a580a2a0bae/637920ff-bb45-4d4a-9bb6-2757fdff09e6 on /var/lib/kubelet/pods/8c50c066-1ed4-47b4-b746-7500acfaddb3/volumes/kubernetes.io~csi/pvc-e34048d4-adae-4999-834f-06f64fd770d7/mount type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432,_netdev)
```

For example:

Any existing bug report which describe about the similar issue/behavior

We though this issue will be fixed after upgraded to 1.3.1+

**Comment by nixpanic** [comment]
Hi,

The error that is logged by the kernel:
```
Oct 29 22:42:08 nodename kernel: libceph: connect 10.43.175.61:6789 error -101
```
translates to `errno 101`: **ENETUNREACH: Network is unreachable**

So, this suggests that there are network restrictions in place, the node that is mounting the CephFS volume does not seem to be able to connect to the Ceph cluster.

In the **additional context**, you do list mounted CephFS volumes, so at least that particular system can reach the Ceph cluster. Could you explain what the differences are between these two systems?

**Comment by ttulong** [comment]
Hi Nixpaic,
Actually those are on the same system. The error 101 occurred when we restarting the system by using "reboot" or "shutdown -r" command without drain the node from K8s. This issue have been described [here ](https://rook.io/docs/rook/v1.4/ceph-common-issues.html#node-hangs-after-reboot) and should be fixed with rook-ceph 1.3.1+ but it still existed  in our case. We are using rook-ceph 1.4.2 . Thank you

**Comment by nixpanic** [comment]
In that case, you may want to open an issue with [Rook](https://github.com/rook/rook/issues)?

**Comment by ttulong** [comment]
I can, but this is not the issue with Rook. It either the kernel/csi driver didnt unmount the drive before network go down when user execute the reboot command.

**Comment by nixpanic** [comment]
> I can, but this is not the issue with Rook. It either the kernel/csi driver didnt unmount the drive before network go down when user execute the reboot command.

Well, the volumes you listed have the `_netdev` option, so they should get unmounted by the system before a reboot. However, there can be issues with the ordering of services that prevents the unmounting from happening. If parts of the network are shut down (like routes to the Ceph cluster), unmounting a CephFS volume will not be possible as flushing the data to the Ceph cluster can not be done without the proper network routes.

So, you may need to investigate about the order of services that happens in the shutdown process. This is possibly outside of the scope of Ceph-CSI and Rook. You should capture the systemd logs while shutting down, and see if any network services (these can be inside pods) is stopped before unmounting network filesystems (indicated with `_netdev`) is done.

The workaround to reboot cleanly, is to drain the node of any pods before shutting down the system.

**Comment by ttulong** [comment]
hi Nixpanic,
Here is addtional logs. I see "Reached target Unmount All Filesystems", does that mean all  files system unmounted?
After the "Shutting down",  all message came from libceph repeatedly. Let me know if you need more logs. 
Also for _netdev, i saw it on "mount|grep ceph" but cannot find the under "cat /proc/mounts". I am not sure if that make any different.

`Oct 29 22:29:49 nodename01 kernel: libceph: mon2 10.43.242.11:6789 connect error
Oct 29 22:29:49 nodename01 kernel: libceph: connect 10.43.242.11:6789 error -101
Oct 29 22:29:48 nodename01 kernel: libceph: mon2 10.43.242.11:6789 connect error
Oct 29 22:29:48 nodename01 kernel: libceph: connect 10.43.242.11:6789 error -101
Oct 29 22:29:48 nodename01 kernel: libceph: mon1 10.43.175.61:6789 connect error
Oct 29 22:29:48 nodename01 kernel: libceph: connect 10.43.175.61:6789 error -101
Oct 29 22:29:48 nodename01 kernel: libceph: mon0 10.43.175.61:6789 session lost, hunting for new mon
Oct 29 22:29:48 nodename01 kernel: libceph: mon0 10.43.175.61:6789 session lost, hunting for new mon
Oct 29 22:29:21 nodename01 systemd[1]: Shutting down.
Oct 29 22:29:21 nodename01 systemd[1]: Starting Reboot...
Oct 29 22:29:21 nodename01 systemd[1]: Reached target Final Step.
Oct 29 22:29:21 nodename01 systemd[1]: Started /etc/init.d/halt.local Compatibility.
Oct 29 22:29:21 nodename01 systemd[1]: Starting /etc/init.d/halt.local Compatibility...
Oct 29 22:29:21 nodename01 systemd[1]: Reached target Shutdown.
Oct 29 22:29:21 nodename01 systemd[1]: Stopped Remount Root and Kernel File Systems.
Oct 29 22:29:21 nodename01 systemd[1]: Stopped target Local File Systems (Pre).
Oct 29 22:29:21 nodename01 systemd[1]: **Reached target Unmount All Filesystems.**
Oct 29 22:29:21 nodename01 systemd[1]: Unmounted /tmp.
Oct 29 22:29:21 nodename01 systemd[1]: Closed Virtual machine lock manager socket.
Oct 29 22:29:21 nodename01 systemd[1]: Closed Virtual machine log manager socket.
Oct 29 22:29:21 nodename01 systemd[1]: Closed PC/SC Smart Card Daemon Activation Socket.
Oct 29 22:29:21 nodename01 systemd[1]: Closed Syslog Socket.
Oct 29 22:29:21 nodename01 systemd[1]: Closed Open-iSCSI iscsid Socket.
Oct 29 22:29:21 nodename01 systemd[1]: Stopped target Sockets.
Oct 29 22:29:21 nodename01 systemd[1]: Unmounting /tmp...
Oct 29 22:29:21 nodename01 systemd[1]: Stopped target Paths.
Oct 29 22:29:21 nodename01 systemd[1]: Removed slice Virtual Machine and Container Slice.
Oct 29 22:29:21 nodename01 systemd[1]: Removed slice User and Session Slice.
Oct 29 22:29:21 nodename01 systemd[1]: Stopped target Slices.
Oct 29 22:29:21 nodename01 systemd[1]: Stopped target Basic System.
Oct 29 22:29:21 nodename01 systemd[1]: Stopped Metricbeat is a lightweight shipper for metrics..
`

**Comment by nixpanic** [comment]
The logs suggest that something happened before systemd logged its messages about shutting down. If Kubernetes gets stopped and kills pods that contribute to the networking before the pods that have CephFS volumes mounted, this problem can happen too.

You should probably have a look at the kubelet logs and verify the order in which the pods are stopped. I think daemonsets get stopped as last, but that could also mean there is a risk with running pods in a daemonset that use network filesystems (stop order might be wrong).

**Comment by ttulong** [comment]
We dont have any daemonset running in our cluster, we have some deployment and statefulsets, not sure if that could cause the issue. I also notice the "libceph error 101" only show up after the systemd "Starting Reboot and Starting shutdown".  I will dig around to see if i can find the kubelet logs and report back. Thank you again.

**Comment by ttulong** [comment]
Hi @nixpanic 
Here is the kubelet logs. I am not really sure what to look. please advise
`Oct 29 22:29:21 nodename01 systemd[1]: var-lib-kubelet-plugins-kubernetes.io-csi-pv-pvc\x2d3f933360\x2d34e4\x2d43bf\x2dbcd6\x2d5bd1d566f4b9-globalmount.mount: Unit entered failed state.
Oct 29 22:29:21 nodename01 systemd[1]: Unmounted /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-3f933360-34e4-43bf-bcd6-5bd1d566f4b9/globalmount.
Oct 29 22:29:21 nodename01 umount[21856]: umount: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-3f933360-34e4-43bf-bcd6-5bd1d566f4b9/globalmount: not mounted
Oct 29 22:29:21 nodename01 systemd[1]: var-lib-kubelet-plugins-kubernetes.io-csi-pv-pvc\x2d3f933360\x2d34e4\x2d43bf\x2dbcd6\x2d5bd1d566f4b9-globalmount.mount: Mount process exited, code=exited status=32
Oct 29 22:29:21 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/ab874301-848d-4326-b57c-6a41b9f2297c/volumes/kubernetes.io~csi/pvc-3f933360-34e4-43bf-bcd6-5bd1d566f4b9/mount.
Oct 29 22:29:21 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/ab874301-848d-4326-b57c-6a41b9f2297c/volumes/kubernetes.io~csi/pvc-e34048d4-adae-4999-834f-06f64fd770d7/mount.
Oct 29 22:29:21 nodename01 systemd[1]: Unmounting /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-3f933360-34e4-43bf-bcd6-5bd1d566f4b9/globalmount...
Oct 29 22:29:21 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/ab874301-848d-4326-b57c-6a41b9f2297c/volumes/kubernetes.io~csi/pvc-3f933360-34e4-43bf-bcd6-5bd1d566f4b9/mount...
Oct 29 22:29:21 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/ab874301-848d-4326-b57c-6a41b9f2297c/volumes/kubernetes.io~csi/pvc-e34048d4-adae-4999-834f-06f64fd770d7/mount...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/1be9a555-ed77-4845-a300-a58d9425ba3c/volumes/kubernetes.io~secret/istio-nodeagent-service-account-token-88lbk.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/23f58b67-b695-47dc-b4d4-7d73ee753ee6/volumes/kubernetes.io~secret/cloud-credentials.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/4d9bbd88-2a49-44ec-bb10-c51ec7b1b792/volumes/kubernetes.io~empty-dir/keys-tmp-dir.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/c772bc2d-2ea8-40c3-9176-25acd2bd7331/volumes/kubernetes.io~secret/cert-manager-cainjector-token-lxhh6.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/4b3c2bfa-c270-410f-a54a-2f267ac9d02b/volumes/kubernetes.io~secret/certs.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/4d9bbd88-2a49-44ec-bb10-c51ec7b1b792/volumes/kubernetes.io~secret/rook-csi-rbd-plugin-sa-token-trzdz.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/2255b4cf-d5ff-4b4e-8fac-f40b19c50691/volumes/kubernetes.io~secret/rook-csi-cephfs-plugin-sa-token-6s9zm.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/2a82aecf-3205-42de-b6e6-7e0f77b8d405/volumes/kubernetes.io~secret/entry.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/d8253fe5-c3f6-4fc7-9d84-abc7adee1a9b/volumes/kubernetes.io~secret/exporter-node-cluster-monitoring-token-nl8h6.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/2a82aecf-3205-42de-b6e6-7e0f77b8d405/volumes/kubernetes.io~secret/rancher-logging-fluentd-token-99jjt.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/2a82aecf-3205-42de-b6e6-7e0f77b8d405/volumes/kubernetes.io~secret/config.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/23f58b67-b695-47dc-b4d4-7d73ee753ee6/volumes/kubernetes.io~secret/velero-server-token-hhj26.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/ab874301-848d-4326-b57c-6a41b9f2297c/volumes/kubernetes.io~secret/blue-jenkins-token-hsjn8.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/1f9a35e2-7768-48b9-9686-1efb03594565/volumes/kubernetes.io~secret/rancher-logging-log-aggregator-token-l27p4.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/4932c45a-adbf-431c-9eb2-c7be41a24069/volumes/kubernetes.io~secret/cert-manager-token-lfm4x.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/2255b4cf-d5ff-4b4e-8fac-f40b19c50691/volumes/kubernetes.io~empty-dir/keys-tmp-dir.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/2a82aecf-3205-42de-b6e6-7e0f77b8d405/volumes/kubernetes.io~secret/ssl.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/4b3c2bfa-c270-410f-a54a-2f267ac9d02b/volumes/kubernetes.io~secret/cert-manager-webhook-token-tnn45.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/549e4596-1f6f-4878-9559-e4f3ae497427/volumes/kubernetes.io~secret/cattle-credentials.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/549e4596-1f6f-4878-9559-e4f3ae497427/volumes/kubernetes.io~secret/cattle-token-nnk92.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounted /var/lib/kubelet/pods/f00df183-b28d-472a-9563-27139cb638e2/volumes/kubernetes.io~secret/flannel-token-4s4mh.
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/1be9a555-ed77-4845-a300-a58d9425ba3c/volumes/kubernetes.io~secret/istio-nodeagent-service-account-token-88lbk...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/23f58b67-b695-47dc-b4d4-7d73ee753ee6/volumes/kubernetes.io~secret/cloud-credentials...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/4d9bbd88-2a49-44ec-bb10-c51ec7b1b792/volumes/kubernetes.io~empty-dir/keys-tmp-dir...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/c772bc2d-2ea8-40c3-9176-25acd2bd7331/volumes/kubernetes.io~secret/cert-manager-cainjector-token-lxhh6...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/4b3c2bfa-c270-410f-a54a-2f267ac9d02b/volumes/kubernetes.io~secret/certs...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/4d9bbd88-2a49-44ec-bb10-c51ec7b1b792/volumes/kubernetes.io~secret/rook-csi-rbd-plugin-sa-token-trzdz...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/2255b4cf-d5ff-4b4e-8fac-f40b19c50691/volumes/kubernetes.io~secret/rook-csi-cephfs-plugin-sa-token-6s9zm...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/2a82aecf-3205-42de-b6e6-7e0f77b8d405/volumes/kubernetes.io~secret/entry...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/d8253fe5-c3f6-4fc7-9d84-abc7adee1a9b/volumes/kubernetes.io~secret/exporter-node-cluster-monitoring-token-nl8h6...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/2a82aecf-3205-42de-b6e6-7e0f77b8d405/volumes/kubernetes.io~secret/rancher-logging-fluentd-token-99jjt...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/2a82aecf-3205-42de-b6e6-7e0f77b8d405/volumes/kubernetes.io~secret/config...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/23f58b67-b695-47dc-b4d4-7d73ee753ee6/volumes/kubernetes.io~secret/velero-server-token-hhj26...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/ab874301-848d-4326-b57c-6a41b9f2297c/volumes/kubernetes.io~secret/blue-jenkins-token-hsjn8...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/1f9a35e2-7768-48b9-9686-1efb03594565/volumes/kubernetes.io~secret/rancher-logging-log-aggregator-token-l27p4...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/4932c45a-adbf-431c-9eb2-c7be41a24069/volumes/kubernetes.io~secret/cert-manager-token-lfm4x...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/2255b4cf-d5ff-4b4e-8fac-f40b19c50691/volumes/kubernetes.io~empty-dir/keys-tmp-dir...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/2a82aecf-3205-42de-b6e6-7e0f77b8d405/volumes/kubernetes.io~secret/ssl...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/4b3c2bfa-c270-410f-a54a-2f267ac9d02b/volumes/kubernetes.io~secret/cert-manager-webhook-token-tnn45...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/549e4596-1f6f-4878-9559-e4f3ae497427/volumes/kubernetes.io~secret/cattle-credentials...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/549e4596-1f6f-4878-9559-e4f3ae497427/volumes/kubernetes.io~secret/cattle-token-nnk92...
Oct 29 22:29:19 nodename01 systemd[1]: Unmounting /var/lib/kubelet/pods/f00df183-b28d-472a-9563-27139cb638e2/volumes/kubernetes.io~secret/flannel-token-4s4mh...
Oct 29 22:29:18 nodename01 systemd[1]: var-lib-kubelet-plugins-kubernetes.io-csi-pv-pvc\x2de34048d4\x2dadae\x2d4999\x2d834f\x2d06f64fd770d7-globalmount.mount: Job var-lib-kubelet-plugins-kubernetes.io-csi-pv-pvc\x2de34048d4\x2dadae\x2d4999\x2d834f\x2d06f64fd770d7-globalmount.mount/stop deleted to break ordering cycle starting with local-fs.target/stop
Oct 29 22:29:18 nodename01 systemd[1]: local-fs.target: Breaking ordering cycle by deleting job var-lib-kubelet-plugins-kubernetes.io-csi-pv-pvc\x2de34048d4\x2dadae\x2d4999\x2d834f\x2d06f64fd770d7-globalmount.mount/stop
Oct 29 22:29:18 nodename01 systemd[1]: local-fs.target: Found dependency on var-lib-kubelet-plugins-kubernetes.io-csi-pv-pvc\x2de34048d4\x2dadae\x2d4999\x2d834f\x2d06f64fd770d7-globalmount.mount/stop
`

**Comment by ttulong** [comment]
I also notice, in this log below, some of them have the **_netdev**  (some does not) in the mount opts and they are the same volume. I am not sure if i missed anything? Thanks in advance

```
**mount**|**grep** 6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-305360ab-4c7f-4ffb-a5ce-1067ea30324f/globalmount type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432,**_netdev**)
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f on /var/lib/kubelet/pods/2ba22c57-6381-4857-baae-aa6dca7a0082/volumes/kubernetes.io~csi/pvc-305360ab-4c7f-4ffb-a5ce-1067ea30324f/mount type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432,_**netdev)**
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f on /var/lib/kubelet/pods/2ba22c57-6381-4857-baae-aa6dca7a0082/volume-subpaths/pvc-305360ab-4c7f-4ffb-a5ce-1067ea30324f/chmod-volume-mounts/0 type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432)
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f on /var/lib/kubelet/pods/2ba22c57-6381-4857-baae-aa6dca7a0082/volume-subpaths/pvc-305360ab-4c7f-4ffb-a5ce-1067ea30324f/chmod-volume-mounts/1 type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432)
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f on /var/lib/kubelet/pods/2ba22c57-6381-4857-baae-aa6dca7a0082/volume-subpaths/pvc-305360ab-4c7f-4ffb-a5ce-1067ea30324f/chmod-volume-mounts/2 type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432)
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f on /var/lib/kubelet/pods/2ba22c57-6381-4857-baae-aa6dca7a0082/volume-subpaths/pvc-305360ab-4c7f-4ffb-a5ce-1067ea30324f/chmod-volume-mounts/3 type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432)
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f on /var/lib/kubelet/pods/2ba22c57-6381-4857-baae-aa6dca7a0082/volume-subpaths/pvc-305360ab-4c7f-4ffb-a5ce-1067ea30324f/chmod-volume-mounts/4 type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432)
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f on /var/lib/kubelet/pods/2ba22c57-6381-4857-baae-aa6dca7a0082/volume-subpaths/pvc-305360ab-4c7f-4ffb-a5ce-1067ea30324f/chmod-volume-mounts/5 type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432)
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f on /var/lib/kubelet/pods/2ba22c57-6381-4857-baae-aa6dca7a0082/volume-subpaths/pvc-305360ab-4c7f-4ffb-a5ce-1067ea30324f/sonarqube/3 type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432)
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f on /var/lib/kubelet/pods/2ba22c57-6381-4857-baae-aa6dca7a0082/volume-subpaths/pvc-305360ab-4c7f-4ffb-a5ce-1067ea30324f/sonarqube/4 type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432)
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f on /var/lib/kubelet/pods/2ba22c57-6381-4857-baae-aa6dca7a0082/volume-subpaths/pvc-305360ab-4c7f-4ffb-a5ce-1067ea30324f/sonarqube/5 type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432)
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f on /var/lib/kubelet/pods/2ba22c57-6381-4857-baae-aa6dca7a0082/volume-subpaths/pvc-305360ab-4c7f-4ffb-a5ce-1067ea30324f/sonarqube/6 type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432)
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f on /var/lib/kubelet/pods/2ba22c57-6381-4857-baae-aa6dca7a0082/volume-subpaths/pvc-305360ab-4c7f-4ffb-a5ce-1067ea30324f/sonarqube/7 type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432)
10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f on /var/lib/kubelet/pods/2ba22c57-6381-4857-baae-aa6dca7a0082/volume-subpaths/pvc-305360ab-4c7f-4ffb-a5ce-1067ea30324f/sonarqube/8 type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432)
```

**Comment by ttulong** [comment]
hi @nixpanic 
Look like the _netdev doesnt apply to host when 

1. using symlink on kubelet directory. example: /var/lib/kubelet --> /var/lib/docker/kubelet (using default Kubelet host path, /var/lib/docker in on its own partition)
```10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-8aca0742-f3a6-11ea-9dcc-0a580a2a0bae/d6c21de5-5213-46bb-8153-423fe7e33f5e on /var/lib/docker/kubelet/plugins/kubernetes.io/csi/pv/pvc-c2caa0f8-8a26-4b20-951e-e9fd05da5688/globalmount type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432)```
2. mount pod with subpath (volume-subpaths)
```10.43.175.61:6789,10.43.93.185:6789,10.43.242.11:6789:/volumes/csi/csi-vol-6b4ea0a4-eb15-11ea-b52f-0a580a2a0b7f on /var/lib/kubelet/pods/2ba22c57-6381-4857-baae-aa6dca7a0082/volume-subpaths/pvc-305360ab-4c7f-4ffb-a5ce-1067ea30324f/chmod-volume-mounts/1 type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=devops-cephfs,wsize=33554432)
```

**Comment by prazumovsky** [comment]
Found exactly same issue with rdbplugin. Do we need to increase level of issue?
