### ISSUE TITLE
[csi-rbd]  Pod with block volume PVC fails to start: "CSIBlockVolume feature not enabled"

### ISSUE THREAD

**Issue by rollandf** [ceph/ceph-csi#167]
**Describe the bug**
Creating a pod with Blockvolume PVC fails with:
Warning  FailedMapVolume         28s (x11967 over 20m)  kubelet, ishaby2.tlv.redhat.com  MapVolume.NewBlockVolumeMapper initialization failed for volume "pvc-52e08ebd-294b-11e9-8e0f-b8ca3aad030b" : CSIBlockVolume feature not enabled

**Kubernetes and Ceph CSI Versions**
Kubernetes: 1.13
csi-v1.0
**Ceph CSI Driver logs**

https://gist.github.com/rollandf/42b70635ea3c5bdf32e83bf353caa154

**To Reproduce**
Configure csi-rbd as described in examples directory.
Create PVC with volumeMode: Block
Create Pod with volumeDevices

**Expected behavior**
The pod is created successfully with access to block device

**Comment by rollandf** [comment]
the feature-gate used: VolumeSnapshotDataSource=true,CSIBlockVolume=true

ps output:
kube-apiserver --authorization-mode=Node,RBAC --feature-gates=VolumeSnapshotDataSource=true,CSIBlockVolume=true --advertise-address=10.35.0.11 --allow-privileged=true --client-ca-file=/etc/kubernetes/pki/ca.crt --enable-admission-plugins=NodeRestriction --enable-bootstrap-token-auth=true --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key --etcd-servers=https://127.0.0.1:2379 --insecure-port=0 --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key --requestheader-allowed-names=front-proxy-client --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-key-file=/etc/kubernetes/pki/sa.pub --service-cluster-ip-range=10.96.0.0/12 --tls-cert-file=/etc/kubernetes/pki/apiserver.crt --tls-private-key-file=/etc/kubernetes/pki/apiserver.key

**Comment by Madhu-1** [comment]
https://kubernetes-csi.github.io/docs/Setup.html#enable-raw-block-volume-support-alpha

**Comment by rollandf** [comment]
Thanks, I missed a place configurating the featuregates

**Comment by ripulpatel** [comment]
@rollandf ,
Can you please provide detail on which other place feature gate was missing? I have enabled feature gate on API server and also on kube-controller-manager but still seeing the same error as yours.

`
kube-apiserver --authorization-mode=Node,RBAC --encryption-provider-config=/etc/kubernetes/pki/secrets.conf --feature-gates=VolumeSnapshotDataSource=true,BlockVolume=true,CSIBlockVolume=true

..

kube-controller-manager --feature-gates=VolumeSnapshotDataSource=true,BlockVolume=true,CSIBlockVolume=true

..

MapVolume.NewBlockVolumeMapper initialization failed for volume "pvc-407f6d71-9cfb-11e9-b76c-00155d8c65ec" : CSIBlockVolume feature not enabled
`

**Comment by Madhu-1** [comment]
@ripulpatel please check the flag is present on kubelet

```
/usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1 --feature-gates=CustomResourceSubresources=true,BlockVolume=true,CSIBlockVolume=true,VolumeSnapshotDataSource=true,VolumePVCDataSource=true
```

**Comment by ripulpatel** [comment]
@Madhu-1 , Thanks. That worked.
