### ISSUE TITLE
Can not run make containerized-test as rootless podman

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/ceph-csi#1670]
# Describe the bug #

The way the container command is invoked from the cli fails with rootless podman (2.1.1).
This appears to be caused by the "CPUSET" variable in the Makefile. I do not believe regular users can make use of this option.

# Environment details #

- Fedora 32 development environment

# Steps to reproduce #

1. checkout ceph-ci master branch
1. make containerized-tests

Error:
```
STEP 5: RUN source /build.env     && dnf -y install     git     make    golang  gcc       librados-devel  librbd-devel    rubygems        ShellCheck      yamllint npm       python3-prettytable       pylint     && dnf -y update     && dnf -y clean all     && gem install mdl     && curl -sf "https://install.goreleaser.com/github.com/golangci/golangci-lint.sh"        | bash -s -- -b ${GOPATH}/bin "${GOLANGCI_VERSION}"     && curl -sfL "https://raw.githubusercontent.com/securego/gosec/master/install.sh"        | sh -s -- -b $GOPATH/bin "${GOSEC_VERSION}"     && curl -L https://git.io/get_helm.sh | bash -s -- --version "${HELM_VERSION}"     && mkdir /opt/commitlint && pushd /opt/commitlint     && npm init -y     && npm install @commitlint/cli     && popd     && true
2020-11-05T18:47:52.000009928Z: opening file `cpuset.cpus` for writing: Permission denied
```

The output is a tad confusing because it looks like the long line of commands triggers the error, but it must just be that podman tries to access the cpuset.cpus knob right after printing that line.

# Expected behavior #

It would be good to not have to read the makefile source and then learn that if I unset CPUSET I can run the checks.
Perhaps the makefile should only set this option when run in particular environments (the ceph-csi CI?) or only if running as uid 0?

**Comment by nixpanic** [comment]
I am hitting this now as well. On Fedora 32 I seem to have downgraded podman to work around this (or something else), but on Fedora 33 this is (probably) not easily possible.
