### ISSUE TITLE
got error when go get 

### ISSUE THREAD

**Issue by tskdsb** [ceph/ceph-csi#1691]
# Describe the bug #

I want to import `github.com/ceph/ceph-csi` as dependency, but got an error:
```
 go get github.com/ceph/ceph-csi@v3.1.1
go get github.com/ceph/ceph-csi@v3.1.1: github.com/ceph/ceph-csi@v3.1.1: reading https://goproxy.cn/github.com/ceph/ceph-csi/@v/v3.1.1.info: 404 Not Found
        server response: not found: github.com/ceph/ceph-csi@v3.1.1: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3
```

**Comment by nixpanic** [comment]
Ceph-CSI is not intended to be consumable by other projects, the API is not stable in any way or form.

Can you explain the reason why you want to import ceph-csi?

**Comment by tskdsb** [comment]
> Ceph-CSI is not intended to be consumable by other projects, the API is not stable in any way or form.
> 
> Can you explain the reason why you want to import ceph-csi?

I want to use the struct:
https://github.com/ceph/ceph-csi/blob/22b631e991c5309e117f1b99f49d1163aa5c8744/internal/util/csiconfig.go#L37

to `json.Unmarshal` the value of key `config.json`) in the configMap:
https://github.com/ceph/ceph-csi/blob/master/examples/csi-config-map-sample.yaml

**Comment by nixpanic** [comment]
We could consider moving the struct to a non-internal package, so that other projects can import it. That is a cleaner solution than importing the internal packages from ceph-csi. It makes clear what parts are consumable by others, and Ceph-CSI developers can then take care not to break things unintentionally.

**Comment by tskdsb** [comment]
event just init a go-module in the directory which other projects can import
