### ISSUE TITLE
Do golang profiling to find out any memory leak in cephcsi

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1699]
Golang supports [profiling](https://blog.golang.org/pprof) , we can also make use of profiling and check are we leaking any memory and if required we can also do some optimization to improve the performance.

**Comment by nixpanic** [comment]
This should probably be a configurable option, either by setting a commandline parameter or environment variable.

heketi/heketi#1396 does something of the sort too.

**Comment by Madhu-1** [comment]
Assigning this to you @nixpanic as you have more idea and you already implemented the same for heketi

**Comment by yati1998** [comment]
@Madhu-1  you can assign this to me. I will discuss it with @nixpanic .

**Comment by yati1998** [comment]
Thanks @Madhu-1  for assigning. Will start working on this once I am done with the snapshot issue.
