### ISSUE TITLE
logging key

### ISSUE THREAD

**Issue by kfox1111** [ceph/ceph-csi#171]
Seen in the 1.0 csi driver log

I0205 20:48:10.456278   17192 rbd_util.go:170] rbd: status pvc-32961cb4-1b85-11e9-9566-001aef16017e using mon xxx,yyy,zzz, pool thingy id otherthingy key ACTUALKEYHERE

It shouldn't log this.

**Comment by Madhu-1** [comment]
@kfox1111 hope this is Fixed in #184, can we close this one?
