### ISSUE TITLE
rbd driver restart

### ISSUE THREAD

**Issue by kfox1111** [ceph/ceph-csi#172]
I upgraded 1.0.0 to a newer release causing the pods to be recreated. I then deleted a pod that had an rbd mount. it moved to another node but /dev/rbd0 was still mounted on the original host. The driver seems to have forgotten it had mounts after the reload.

It would be nice if restarting the driver didn't require the node to be drained first.

**Comment by Madhu-1** [comment]
@dillaman @humblec @ShyamsundarR is it possible to handle this one?

**Comment by humblec** [comment]
@kfox1111 with the latest version this would have fixed as we had some fixes in staging and publishing path also some fixes has come in latest CSI spec in this area which we depend on with latest ( v2.*) ceph-csi release. Closing this issue for now and feel free to reopen if you still face this issue.
