### ISSUE TITLE
cephcsi create too many process    

### ISSUE THREAD

**Issue by JadeQin** [ceph/ceph-csi#1722]
# Describe the bug #

# Environment details #

- Image/version of Ceph CSI driver : 2.1.1
- Kernel version : 5.7.2
- Kubernetes cluster version : 1.18.3
- Ceph cluster version : 14.2.9

I found that my node has too high load about 2000+, there are 2200+ sub process  about cephcsi.
![image](https://user-images.githubusercontent.com/1001227/100221849-35b8e480-2f54-11eb-9404-cdd19742735d.png)

I see the log about cephcsi, it looks like this:
```
E1125 11:44:56.606340       1 nodeserver.go:232] ID: 15930 Req-ID: 0001-0009-rook-ceph-0000000000000001-1d9ac43f-b451-11ea-8177-4a4001253a2f an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-1d9ac43f-b451-11ea-8177-4a4001253a2f already exists
E1125 11:44:56.606374       1 utils.go:163] ID: 15930 Req-ID: 0001-0009-rook-ceph-0000000000000001-1d9ac43f-b451-11ea-8177-4a4001253a2f GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-1d9ac43f-b451-11ea-8177-4a4001253a2f already exists
E1125 11:46:58.698943       1 nodeserver.go:232] ID: 15935 Req-ID: 0001-0009-rook-ceph-0000000000000001-1d9ac43f-b451-11ea-8177-4a4001253a2f an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-1d9ac43f-b451-11ea-8177-4a4001253a2f already exists
E1125 11:46:58.698967       1 utils.go:163] ID: 15935 Req-ID: 0001-0009-rook-ceph-0000000000000001-1d9ac43f-b451-11ea-8177-4a4001253a2f GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-1d9ac43f-b451-11ea-8177-4a4001253a2f already exists
E1125 11:49:00.782850       1 nodeserver.go:232] ID: 15938 Req-ID: 0001-0009-rook-ceph-0000000000000001-1d9ac43f-b451-11ea-8177-4a4001253a2f an operation with the given Volume ID 0001-0009-rook-ceph-0000000000000001-1d9ac43f-b451-11ea-8177-4a4001253a2f already exists

```

How can I resolve it ? Thanks.

**Comment by Madhu-1** [comment]
@JadeQin do you have any steps to reproduce it?

**Comment by Madhu-1** [comment]
can you please also check is it happening with the latest cephcsi releases?

**Comment by JadeQin** [comment]
> @JadeQin do you have any steps to reproduce it?

I do not know how it can reproduce

**Comment by Madhu-1** [comment]
Currently, cephcsi uses ceph CLI to perform all ceph fs operations, this will be replaced with go-ceph in the next releases.

**Comment by Madhu-1** [comment]
@JadeQin few question below

* How many pvc are there in your cluster
*  How many applications are using the pvc on the node.
* Is it happening on all the nodes

**Comment by JadeQin** [comment]
I 

> @JadeQin few question below
> 
> * How many pvc are there in your cluster
> * How many applications are using the pvc on the node.
> * Is it happening on all the nodes

Some information on site has been lost because of the restoration at that time.

There are currently 12 PVCs, and each PVC corresponds to an app.

I will try to upgrade to the latest version to see if this problem will happen again

**Comment by nixpanic** [comment]
I expect that this is not happening with the current ceph-csi:v3.2.1 image anymore. All items on https://github.com/ceph/ceph-csi/projects/3 have been addressed, meaning go-ceph is used for CephFS provisioning now, instead of the `ceph` command earlier.

**Comment by Madhu-1** [comment]
closing this one as we moved to go-ceph for cephfs, please feel free to reopen if you see this again.
