### ISSUE TITLE
e2e: update kubernetes version in ci

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1784]
we are running E2E with kubernetes v1.18  and v1.19. as kubernetes, 1.20  https://kubernetes.io/docs/setup/release/notes/#changelog-since-v1-19-0 is released we should update our E2E to run against the latest 2 versions of kubernetes 1.19 and 1.20

- [x] add v1.20 to CI jobs (ci/centos branch)
- [x] update mergify rules (master branch)
- [x] remove v1.18 from CI jobs (ci/centos branch)

**Comment by nixpanic** [comment]
[1st job](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/job/mini-e2e_k8s-1.20/1/display/redirect) is running, we'll see if any updates to the scripts are needed or a minikube upgrade is required.

**Comment by nixpanic** [comment]
v1.20.0-beta.2 gets detected, but [minikube seems to install it](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.20/detail/mini-e2e_k8s-1.20/1/pipeline/64/#step-75-log-1681) just fine

**Comment by nixpanic** [comment]
> v1.20.0-beta.2 gets detected

#1792 fixes the version detection
