### ISSUE TITLE
CI jobs ocasionaly fail with: missing encryption passphrase in secrets

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1795]
# Describe the bug #

While running the mini-e2e CI jobs, on occasion these fail with

    invalid encryption kms configuration: missing encryption passphrase in secrets

# Actual results #

While provisioning, the KMS configuration gets read from the parameters in the StorageClass. These can define a KMS that uses a passphrase stored in the Secrets that are linked to the StorageClass. Sometimes, the provisioner/node-plugin fail to receive the passphrase from the Secret.

# Expected behavior #

The CI environment should configure the Secret with the passphrase for encrypting RBD volumes correctly. The secret should get passed by CSI to the provisioner/node-plugin.

# Logs #

CI job [mini-e2e_k8s-1.20/9](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.20/detail/mini-e2e_k8s-1.20/9/pipeline)

These logs do not help with identifying where the problem is caused. :thinking: Possibly the deployment of the StorageClass-Secret is failing to add the passphrase.

**Comment by Madhu-1** [comment]
currently, we are making use of the secretes created by the rook for our E2E. incase of the RBD pvc encryption test case we are adding the encryption key to the same secret. there is a good chance that Rook is reconciling the secretes which it has created. i  would suggest creating new secrets for the cephcsi E2E instead of using the secrets created by the Rook.

**Comment by Yuggupta27** [comment]
@Madhu-1 @nixpanic @agarwal-mudit @humblec, Since https://github.com/ceph/ceph-csi/pull/1863 and https://github.com/ceph/ceph-csi/pull/1888 are merged, most probably this CI issue will be prevented. Can we close this issue for now and reopen it if we hit it anytime later?

**Comment by Madhu-1** [comment]
Yes, closing it for now.
