### ISSUE TITLE
config.json should be configurable path, otherwise this plugin is useless for mesos

### ISSUE THREAD

**Issue by f1-outsourcing** [ceph/ceph-csi#1797]
This directory does not exist on centos7

https://github.com/ceph/ceph-csi/blob/9160a5309ec1cdecce932b5466716780f5cc7405/internal/util/csiconfig.go#L33

**Comment by Madhu-1** [comment]
currently, it's a configmap that will be mounted to the cephcsi plugins https://github.com/ceph/ceph-csi/blob/master/deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml#L174-L175.

If memos is not able to mount a file to a cephcsi container we can make it configurable.

**Comment by f1-outsourcing** [comment]
I am currently testing on the command line with csc when I noticed this, it would be nice to have this configurable. Because I am not fetching any files, nor do I use a container image.
