### ISSUE TITLE
ceph.conf is deleted/changed at cephcsi startup

### ISSUE THREAD

**Issue by f1-outsourcing** [ceph/ceph-csi#1799]
Looks like the cephcsi plugin is changing the ceph.conf. This is not really desirable, nobody is going to expect that a csi plugin is going to change your /etc/ceph/ceph.conf file. 

Before running the csi plugin
```
[@ceph]# ls -arlt
total 28

-rw-r--r--   1 root root  170 Feb 16  2019 rbdmap
-rw-r--r--   1 root root 6189 Sep 25 09:30 ceph.conf
drwxr-xr-x 110 root root 8192 Dec 16 12:04 ..
drwxr-xr-x   2 root root   89 Dec 16 12:23 .
-rw-r--r--   1 root root    0 Dec 16 17:07 keyring
```
After running the csi plugin with
`/usr/libexec/csi/csiceph -endpoint unix:///tmp/csiceph.sock -nodeid $HOSTNAME -type rbd -drivername ceph-csi-v3.2.0-rbd -alsologtostderr -v 99`

```
[@ceph]# ls -arlt
total 24
-rw-r--r--   1 root root  170 Feb 16  2019 rbdmap
drwxr-xr-x 110 root root 8192 Dec 16 12:04 ..
drwxr-xr-x   2 root root   89 Dec 16 12:23 .
-rw-r--r--   1 root root    0 Dec 16 17:09 keyring
-rw-r--r--   1 root root  182 Dec 16 17:09 ceph.conf
```

**Comment by Madhu-1** [comment]
currently, cephcsi is built and shipped as a container image and when it starts will create its own ceph.conf with minimal required configurations. We don't have a requirement to pass the ceph.conf as an argument to the cephcsi pod. if you see any requirement in passing the ceph.conf as an argument please do open a feature request.

**Comment by f1-outsourcing** [comment]
I would implement a test on the existence of a file, and if it exists not overwrite it. 

This from the perspective that if someone puts a file, he did this knowingly. If it is not according to specific plugin demands, that is his problem and that probably would be revealed in the logs.
