### ISSUE TITLE
Support creating volume snapshots and clones without flattening

### ISSUE THREAD

**Issue by cjheppell** [ceph/ceph-csi#1800]
# Describe the feature you'd like to have #

Support creating volume snapshots and clones without flattening

# What is the value to the end user? (why is it a priority?) #

I'm able to create snapshots (and therefore clones) of an existing PVC without needing to wait for the full flatten operation to complete. This means I'll be able to take advantage of Ceph's block-level copy-on-write to quickly create clones of existing PVC's via a their snapshot.

As it stands right now (presumably due to the work in https://github.com/ceph/ceph-csi/pull/1160), whenever I create a volume snapshot, it causes a _full copy_ of the PVC I'm snapshotting due to flattening. This is the **exact opposite of what I'd expect as a user**. I want my snapshot to be a point-in-time record of the state of the PVC that I can then create subsequent clones of _without needing to perform a full copies_.

The current implementation of the Ceph CSI driver prevents this from being possible, effectively making the copy-on-write snapshot behaviour provided by Ceph inaccessible to me.

# How will we know we have a good solution? (acceptance criteria) #

When I create a VolumeSnapshot of an existing Ceph PVC, that should be equivalent to a Ceph RBD snapshot of the underlying PVC _without any full-copying or flattening applied_.

I'm then able to create _clones_ of that VolumeSnapshot which maps exactly to the `clone` operation provided by Ceph.

# Additional context #

From a brief read, it seems that this "flattening" behaviour was introduced to avoid having a dependent relationship between the pvc <-> snapshot <-> clones, so that I can delete the PVC whilst still leaving the VolumeSnapshot around.

I actually _want_ this relationship to exist. It's the reason I want to use Ceph in my cluster, so that I can quickly provision clones of PVCs without taking up all the disk space and time to do a full-copy.

**Comment by dillaman** [comment]
@cjheppell Have you overridden `softMaxCloneDepth` to 1? It shouldn't be flattening images unless you make chains of clones longer than the `softMaxCloneDepth` setting. If it's always flattening, that sounds like a bug.

**Comment by cjheppell** [comment]
Not as far as I'm aware.

For context, the Ceph CSI driver I'm using is `quay.io/cephcsi/cephcsi:v3.1.0` installed via Rook in a Kubernetes Cluster.

Having just manually patched the `cephcsi` version to `v2.1.2` I'm getting the behaviour I'd expect:

- Creating a VolumeSnapshot creates a snapshot _on_ the corresponding rbd image representing my PVC
- Creating a PVC with that VolumeSnapshot defined as the source creates a _clone_ rbd image based off the snapshot created on the original rbd image

Perhaps there's something I'm missing, but I've definitely observed behaviour where (without any additional config out of the box via a Rook-provisioned Ceph cluster) creating a VolumeSnapshot from a PVC will immediately cause a flatten because rather than just creating a snapshot on the source rbd image it does this:

- Create a temporary snapshot from the parent volume
- Clone a new image from a temporary snapshot with options --rbd-default-clone-format 2 --image-feature layering,deep-flatten
- Delete temporary snapshot created
- Create snapshot from clone image

As far as I could understand, this caused a full-copy, and means that my new volume snapshot is completely detached from the original PVC?

**Comment by dillaman** [comment]
> As far as I could understand, this caused a full-copy to the clone layer (as the snapshot it was created from was deleted), and means that my new volume snapshot is completely detached from the original PVC?

None of the steps listed above will cause a flatten. Are you actually seeing a flatten?

**Comment by cjheppell** [comment]
> None of the steps listed above will cause a flatten. Are you actually seeing a flatten?

This could well be a lack of understanding on my part on how Ceph works in that case...

I guess my confusion comes from the fact that reviewing the Ceph Dashboard (and indeed the output of `ceph rbd ls`) shows a new image representing the volumesnapshot with no parents, rather than a snapshot _on_ the original rbd image. 

I was under the impression that _must_ cause a full-copy from the parent snapshot that was deleted down to the cloned child according to https://docs.ceph.com/en/latest/rbd/rbd-snapshot/#flattening-a-cloned-image

**Comment by dillaman** [comment]
> I guess my confusion comes from the fact that reviewing the Ceph Dashboard (and indeed the output of `ceph rbd ls`) shows a new image representing the volumesnapshot with no parents, rather than a snapshot _on_ the original rbd image it was taken from.

Perhaps there is a bug in the dashboard. What does "rbd info" show against the snapshot image?

```
$ rbd create --size 1G image1
$ rbd snap create image1@snap
Creating snap: 100% complete...done.
$ rbd clone --rbd-default-clone-format=2 --image-feature layering,deep-flatten image1@snap image2
$ rbd snap rm image1@snap
Removing snap: 100% complete...done.
$ rbd snap create image2@snap
$ rbd clone --rbd-default-clone-format=2 --image-feature layering image2@snap image3
$ rbd info image2
rbd image 'image2':
	size 1 GiB in 256 objects
	order 22 (4 MiB objects)
	snapshot_count: 1
	id: 10337a6504ed
	block_name_prefix: rbd_data.10337a6504ed
	format: 2
	features: layering, deep-flatten, operations
	op_features: clone-parent, clone-child
	flags: 
	create_timestamp: Wed Dec 16 13:48:01 2020
	access_timestamp: Wed Dec 16 13:48:01 2020
	modify_timestamp: Wed Dec 16 13:48:01 2020
	parent: rbd/image1@e4b72fcf-8d0a-42ab-8076-07918588c13f
	overlap: 1 GiB
$ rbd info image3
rbd image 'image3':
	size 1 GiB in 256 objects
	order 22 (4 MiB objects)
	snapshot_count: 0
	id: 103dac306e02
	block_name_prefix: rbd_data.103dac306e02
	format: 2
	features: layering, operations
	op_features: clone-child
	flags: 
	create_timestamp: Wed Dec 16 13:50:21 2020
	access_timestamp: Wed Dec 16 13:50:21 2020
	modify_timestamp: Wed Dec 16 13:50:21 2020
	parent: rbd/image2@snap
	overlap: 1 GiB
```

**Comment by cjheppell** [comment]
Yes, you're quite right!

Having run `rbd info` on the "snapshot" image shows that its parent is indeed my original PVC. Thanks a lot for clearing that up 👍 

What _is_ confusing however, is that the dashboard is now only showing the "snapshot" rbd image, not the original PVC rbd image:

![image](https://user-images.githubusercontent.com/12884767/102396620-988e2080-3fd4-11eb-953c-8c9073358415.png)

Whereas rbd ls is showing the original PVC rbd image too:

```
$ rbd ls
csi-snap-84cf774b-3fd3-11eb-ac83-1eaeb7b3b119
csi-vol-3957c2fc-3fd3-11eb-ac83-1eaeb7b3b119
```

**Comment by cjheppell** [comment]
I wonder if this ought to be reopened?

I've done a bit more digging and I've seen this flattening happen from the ceph csi-plugin pod itself.

See: https://github.com/ceph/ceph-csi/issues/1543#issuecomment-780132055
