### ISSUE TITLE
error decoding volume ID (failed to decode CSI identifier, string underflow)

### ISSUE THREAD

**Issue by f1-outsourcing** [ceph/ceph-csi#1802]
I am not sure if this is a bug or just me using incorrect syntax for staging a volume

`csc -e unix:///tmp/csiceph.sock node stage --cap SINGLE_NODE_WRITER,block --staging-target-path '/mnt/staging/' --vol-context 'clusterID=ceph,pool=app,imageFeatures=layering'  'app-test'`

This is what the plugin is loggin
```
I1216 23:22:59.395372   13553 utils.go:132] ID: 8 Req-ID: app-test GRPC call: /csi.v1.Node/NodeStageVolume
I1216 23:22:59.397436   13553 utils.go:133] ID: 8 Req-ID: app-test GRPC request: {"secrets":"***stripped***","staging_target_path":"/mnt/staging/","volume_capability":{"AccessType":{"Block":{}},"access_mode":{"mode":1}},"volume_context":{"clusterID":"ceph","imageFeatures":"layering","pool":"app"},"volume_id":"app-test"}
I1216 23:22:59.400716   13553 rbd_util.go:808] ID: 8 Req-ID: app-test setting disableInUseChecks on rbd volume to: false
E1216 23:22:59.401794   13553 utils.go:136] ID: 8 Req-ID: app-test GRPC error: rpc error: code = Internal desc = error decoding volume ID (failed to decode CSI identifier, string underflow) (app-test)
```

using v3.2.0

**Comment by nixpanic** [comment]
How did you create the `app-test` volume? It is not something ceph-csi expects as name of an RBD image.

**Comment by f1-outsourcing** [comment]
I created the app-test with rbd create 

```
[@~]# rbd info app/app-test
rbd image 'app-test':
     size 1 GiB in 256 objects
     order 22 (4 MiB objects)
     snapshot_count: 0
     id: 34ba4d6b8b4567
     block_name_prefix: rbd_data.34ba4d6b8b4567
     format: 2
     features: layering
     op_features:
     flags:
     create_timestamp: Mon Feb 11 18:47:03 2019
```
the image maps just fine on the same host with the same credentials.

```
[@~]# rbd map  app/app-test  --id app.mesos -k /etc/ceph/ceph.client.app.mesos.keyring
/dev/rbd0

```

**Comment by Madhu-1** [comment]
this is not the way cephcsi works, the image is cannot be directly passed to the csi driver. the volumeHandle will be sent the in createVolume response. the same volumeHandle should be used to map the rbd image on the node.

**Comment by f1-outsourcing** [comment]
> 
> 
> this is not the way cephcsi works, the image is cannot be directly passed to the csi driver. the volumeHandle will be sent the in createVolume response. the same volumeHandle should be used to map the rbd image on the node.

I do not understand this. Do mind I am just user of csi. I did not read much of the specification of csi plugins. 
If I use a csinfs I can supply a Volume, that is being mounted. I do not need to get the 'handle' of the volume first. Maybe I have seen old descriptions/processes of csi, but this is the first time I heard about it. I think this command line client does not even mention a handle argument.

I guess this means that you cannot use pre-provisioned images?

**Comment by Madhu-1** [comment]
> > this is not the way cephcsi works, the image is cannot be directly passed to the csi driver. the volumeHandle will be sent the in createVolume response. the same volumeHandle should be used to map the rbd image on the node.
> 
> I do not understand this. Do mind I am just user of csi. I did not read much of the specification of csi plugins.
> If I use a csinfs I can supply a Volume, that is being mounted. I do not need to get the 'handle' of the volume first. Maybe I have seen old descriptions/processes of csi, but this is the first time I heard about it. I think this command line client does not even mention a handle argument.
> 
Am not sure about how the CLI command that you have used works, cephcsi need both Nodestage and NodePlublish RPC request to successfully mount a volume to target path

> I guess this means that you cannot use pre-provisioned images?

You can only mount and unmount the pre-provisioner image but you cannot resize it nor you can create clones or snapshots from it. https://github.com/ceph/ceph-csi/blob/master/docs/static-pvc.md might help you

**Comment by f1-outsourcing** [comment]
ok so I do a create volume request for app-test2, with this command.
`
csc -e unix:///tmp/csiceph.sock controller create-volume --cap MULTI_NODE_MULTI_WRITER,block --lim-bytes 1000000 --req-bytes 1000000 --params 'clusterID=ceph,pool=app,volumeNamePrefix=app-' 'app-test2'`

csiceph plugin outputs this log:

```
I1217 13:01:32.087133   16020 utils.go:132] ID: 9 Req-ID: app-test2 GRPC call: /csi.v1.Controller/CreateVolume
I1217 13:01:32.088300   16020 utils.go:133] ID: 9 Req-ID: app-test2 GRPC request: {"capacity_range":{"limit_bytes":1000000,"required_bytes":1000000},"name":"app-test2","parameters":{"clusterID":"ceph","pool":"app","volumeNamePrefix":"app-"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":5}}]}
I1217 13:01:32.089855   16020 rbd_util.go:808] ID: 9 Req-ID: app-test2 setting disableInUseChecks on rbd volume to: true
I1217 13:01:32.093217   16020 omap.go:84] ID: 9 Req-ID: app-test2 got omap values: (pool="app", namespace="", name="csi.volumes.default"): map[csi.volume.app-test2:7957e938-405a-11eb-bfd0-0050563001a1]
I1217 13:01:32.096233   16020 omap.go:84] ID: 9 Req-ID: app-test2 got omap values: (pool="app", namespace="", name="csi.volume.7957e938-405a-11eb-bfd0-0050563001a1"): map[csi.imageid:4d2433a92eda7d csi.imagename:app-7957e938-405a-11eb-bfd0-0050563001a1 csi.volname:app-test2]
I1217 13:01:32.143396   16020 omap.go:118] ID: 9 Req-ID: app-test2 removed omap keys (pool="app", namespace="", name="csi.volumes.default"): [csi.volume.app-test2]
I1217 13:01:32.165559   16020 omap.go:148] ID: 9 Req-ID: app-test2 set omap keys (pool="app", namespace="", name="csi.volumes.default"): map[csi.volume.app-test2:7957e938-405a-11eb-bfd0-0050563001a1])
I1217 13:01:32.180357   16020 omap.go:148] ID: 9 Req-ID: app-test2 set omap keys (pool="app", namespace="", name="csi.volume.7957e938-405a-11eb-bfd0-0050563001a1"): map[csi.imagename:app-7957e938-405a-11eb-bfd0-0050563001a1 csi.volname:app-test2])
I1217 13:01:32.181213   16020 rbd_journal.go:436] ID: 9 Req-ID: app-test2 generated Volume ID (0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1) and image name (app-7957e938-405a-11eb-bfd0-0050563001a1) for request name (app-test2)
I1217 13:01:32.182231   16020 rbd_util.go:201] ID: 9 Req-ID: app-test2 rbd: create app/app-7957e938-405a-11eb-bfd0-0050563001a1 size 1M (features: []) using mon 192.168.10.111,192.168.10.112,192.168.10.113
I1217 13:01:32.270955   16020 controllerserver.go:486] ID: 9 Req-ID: app-test2 created volume app-test2 backed by image app-7957e938-405a-11eb-bfd0-0050563001a1
I1217 13:01:32.280586   16020 omap.go:148] ID: 9 Req-ID: app-test2 set omap keys (pool="app", namespace="", name="csi.volume.7957e938-405a-11eb-bfd0-0050563001a1"): map[csi.imageid:4d2433a92eda7d])
I1217 13:01:32.281951   16020 utils.go:138] ID: 9 Req-ID: app-test2 GRPC response: {"volume":{"capacity_bytes":1048576,"volume_context":{"clusterID":"ceph","imageName":"app-7957e938-405a-11eb-bfd0-0050563001a1","journalPool":"app","pool":"app","radosNamespace":"","volumeNamePrefix":"app-"},"volume_id":"0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1"}}
```

Then one expects that the PublishVolume would require the same argument 'app-test2' not? More confusing is that there is a VolumeNamePrefix which is indeed applied to the rbd image name.

Ok so now I take the volume id from the output and try to stage that with this command:

`csc -e unix:///tmp/csiceph.sock node stage --cap SINGLE_NODE_WRITER,block --staging-target-path '/mnt/staging/' --vol-context 'clusterID=ceph,pool=app,volumeNamePrefix=app-,imageFeatures=layering' '0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1'`

Then I get a different error "rbd: ret=-22, Invalid argument: RBD image not found"

The csiceph plugin returns this log.

```
I1217 13:11:24.621519   16020 utils.go:132] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 GRPC call: /csi.v1.Node/NodeStageVolume
I1217 13:11:24.622979   16020 utils.go:133] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 GRPC request: {"secrets":"***stripped***","staging_target_path":"/mnt/staging/","volume_capability":{"AccessType":{"Block":{}},"access_mode":{"mode":1}},"volume_context":{"clusterID":"ceph","imageFeatures":"layering","pool":"app","volumeNamePrefix":"app-"},"volume_id":"0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1"}
I1217 13:11:24.625095   16020 rbd_util.go:808] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 setting disableInUseChecks on rbd volume to: false
I1217 13:11:24.629305   16020 omap.go:84] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 got omap values: (pool="app", namespace="", name="csi.volume.7957e938-405a-11eb-bfd0-0050563001a1"): map[csi.imageid:4d2433a92eda7d csi.imagename:app-7957e938-405a-11eb-bfd0-0050563001a1 csi.volname:app-test2]
E1217 13:11:24.630865   16020 util.go:232] kernel 3.10.0-1160.6.1.el7.x86_64 does not support required features
I1217 13:11:24.687629   16020 rbd_util.go:326] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 executing [rbd task add flatten app/app-7957e938-405a-11eb-bfd0-0050563001a1 --id app.mesos --keyfile=/tmp/csi/keys/keyfile-157862282 -m 192.168.10.111,192.168.10.112,192.168.10.113] for image (app-7957e938-405a-11eb-bfd0-0050563001a1) using mon 192.168.10.111,192.168.10.112,192.168.10.113, pool app
I1217 13:11:25.563996   16020 cephcmds.go:53] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 an error (exit status 13) occurred while running ceph args: [rbd task add flatten app/app-7957e938-405a-11eb-bfd0-0050563001a1 --id app.mesos --keyfile=***stripped*** -m 192.168.10.111,192.168.10.112,192.168.10.113]
W1217 13:11:25.564392   16020 rbd_util.go:337] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 access denied to Ceph MGR-based rbd commands on cluster ID (ceph)
E1217 13:11:25.564616   16020 rbd_util.go:508] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 task manager does not support flatten,image will be flattened once hardlimit is reached: an error (exit status 13) occurred while running ceph args: [rbd task add flatten app/app-7957e938-405a-11eb-bfd0-0050563001a1 --id app.mesos --keyfile=***stripped*** -m 192.168.10.111,192.168.10.112,192.168.10.113]
E1217 13:11:25.662586   16020 rbd_util.go:516] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 rbd failed to flatten image app app-7957e938-405a-11eb-bfd0-0050563001a1: rbd: ret=-22, Invalid argument: RBD image not found
E1217 13:11:25.664080   16020 utils.go:136] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 GRPC error: rpc error: code = Internal desc = rbd: ret=-22, Invalid argument: RBD image not found

```

Hmmmm, so lets try again with -forcecephkernelclient

```
I1217 13:27:16.330084   16318 utils.go:132] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 GRPC call: /csi.v1.Node/NodeStageVolume
I1217 13:27:16.337391   16318 utils.go:133] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 GRPC request: {"secrets":"***stripped***","staging_target_path":"/mnt/staging/","volume_capability":{"AccessType":{"Block":{}},"access_mode":{"mode":1}},"volume_context":{"clusterID":"ceph","imageFeatures":"layering","pool":"app","volumeNamePrefix":"app-"},"volume_id":"0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1"}
I1217 13:27:16.338949   16318 rbd_util.go:808] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 setting disableInUseChecks on rbd volume to: false
I1217 13:27:16.507780   16318 omap.go:84] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 got omap values: (pool="app", namespace="", name="csi.volume.7957e938-405a-11eb-bfd0-0050563001a1"): map[csi.imageid:4d2433a92eda7d csi.imagename:app-7957e938-405a-11eb-bfd0-0050563001a1 csi.volname:app-test2]
E1217 13:27:16.509268   16318 util.go:232] kernel 3.10.0-1160.6.1.el7.x86_64 does not support required features
I1217 13:27:16.561805   16318 rbd_util.go:326] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 executing [rbd task add flatten app/app-7957e938-405a-11eb-bfd0-0050563001a1 --id app.mesos --keyfile=/tmp/csi/keys/keyfile-975520426 -m 192.168.10.111,192.168.10.112,192.168.10.113] for image (app-7957e938-405a-11eb-bfd0-0050563001a1) using mon 192.168.10.111,192.168.10.112,192.168.10.113, pool app
I1217 13:27:17.427406   16318 cephcmds.go:53] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 an error (exit status 13) occurred while running ceph args: [rbd task add flatten app/app-7957e938-405a-11eb-bfd0-0050563001a1 --id app.mesos --keyfile=***stripped*** -m 192.168.10.111,192.168.10.112,192.168.10.113]
W1217 13:27:17.433269   16318 rbd_util.go:337] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 access denied to Ceph MGR-based rbd commands on cluster ID (ceph)
E1217 13:27:17.433373   16318 rbd_util.go:508] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 task manager does not support flatten,image will be flattened once hardlimit is reached: an error (exit status 13) occurred while running ceph args: [rbd task add flatten app/app-7957e938-405a-11eb-bfd0-0050563001a1 --id app.mesos --keyfile=***stripped*** -m 192.168.10.111,192.168.10.112,192.168.10.113]
E1217 13:27:17.513076   16318 rbd_util.go:516] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 rbd failed to flatten image app app-7957e938-405a-11eb-bfd0-0050563001a1: rbd: ret=-22, Invalid argument: RBD image not found
E1217 13:27:17.514554   16318 utils.go:136] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 GRPC error: rpc error: code = Internal desc = rbd: ret=-22, Invalid argument: RBD image not found

```

So still the same 'RBD image not found'

- What is the csi event to retrieve this volume id? How can I get this volumeID from a pre-provisioned Volume?
- And why is csiceph plugin showing 'NodeStageVolume' and not 'NodeStageVolumeID' in logs? I still cannot understand that if I use the CreateVolume event with an argument, I can not use the same argument with a PublishVolume or StageVolume event.

**Comment by Madhu-1** [comment]
> ok so I do a create volume request for app-test2, with this command.
> ` csc -e unix:///tmp/csiceph.sock controller create-volume --cap MULTI_NODE_MULTI_WRITER,block --lim-bytes 1000000 --req-bytes 1000000 --params 'clusterID=ceph,pool=app,volumeNamePrefix=app-' 'app-test2'`
> 
Please pass imageFeatures=layering for createVolume

> csiceph plugin outputs this log:
> 
> ```
> I1217 13:01:32.087133   16020 utils.go:132] ID: 9 Req-ID: app-test2 GRPC call: /csi.v1.Controller/CreateVolume
> I1217 13:01:32.088300   16020 utils.go:133] ID: 9 Req-ID: app-test2 GRPC request: {"capacity_range":{"limit_bytes":1000000,"required_bytes":1000000},"name":"app-test2","parameters":{"clusterID":"ceph","pool":"app","volumeNamePrefix":"app-"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Block":{}},"access_mode":{"mode":5}}]}
> I1217 13:01:32.089855   16020 rbd_util.go:808] ID: 9 Req-ID: app-test2 setting disableInUseChecks on rbd volume to: true
> I1217 13:01:32.093217   16020 omap.go:84] ID: 9 Req-ID: app-test2 got omap values: (pool="app", namespace="", name="csi.volumes.default"): map[csi.volume.app-test2:7957e938-405a-11eb-bfd0-0050563001a1]
> I1217 13:01:32.096233   16020 omap.go:84] ID: 9 Req-ID: app-test2 got omap values: (pool="app", namespace="", name="csi.volume.7957e938-405a-11eb-bfd0-0050563001a1"): map[csi.imageid:4d2433a92eda7d csi.imagename:app-7957e938-405a-11eb-bfd0-0050563001a1 csi.volname:app-test2]
> I1217 13:01:32.143396   16020 omap.go:118] ID: 9 Req-ID: app-test2 removed omap keys (pool="app", namespace="", name="csi.volumes.default"): [csi.volume.app-test2]
> I1217 13:01:32.165559   16020 omap.go:148] ID: 9 Req-ID: app-test2 set omap keys (pool="app", namespace="", name="csi.volumes.default"): map[csi.volume.app-test2:7957e938-405a-11eb-bfd0-0050563001a1])
> I1217 13:01:32.180357   16020 omap.go:148] ID: 9 Req-ID: app-test2 set omap keys (pool="app", namespace="", name="csi.volume.7957e938-405a-11eb-bfd0-0050563001a1"): map[csi.imagename:app-7957e938-405a-11eb-bfd0-0050563001a1 csi.volname:app-test2])
> I1217 13:01:32.181213   16020 rbd_journal.go:436] ID: 9 Req-ID: app-test2 generated Volume ID (0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1) and image name (app-7957e938-405a-11eb-bfd0-0050563001a1) for request name (app-test2)
> I1217 13:01:32.182231   16020 rbd_util.go:201] ID: 9 Req-ID: app-test2 rbd: create app/app-7957e938-405a-11eb-bfd0-0050563001a1 size 1M (features: []) using mon 192.168.10.111,192.168.10.112,192.168.10.113
> I1217 13:01:32.270955   16020 controllerserver.go:486] ID: 9 Req-ID: app-test2 created volume app-test2 backed by image app-7957e938-405a-11eb-bfd0-0050563001a1
> I1217 13:01:32.280586   16020 omap.go:148] ID: 9 Req-ID: app-test2 set omap keys (pool="app", namespace="", name="csi.volume.7957e938-405a-11eb-bfd0-0050563001a1"): map[csi.imageid:4d2433a92eda7d])
> I1217 13:01:32.281951   16020 utils.go:138] ID: 9 Req-ID: app-test2 GRPC response: {"volume":{"capacity_bytes":1048576,"volume_context":{"clusterID":"ceph","imageName":"app-7957e938-405a-11eb-bfd0-0050563001a1","journalPool":"app","pool":"app","radosNamespace":"","volumeNamePrefix":"app-"},"volume_id":"0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1"}}
> ```
> 
> Then one expects that the PublishVolume would require the same argument 'app-test2' not? More confusing is that there is a VolumeNamePrefix which is indeed applied to the rbd image name.
> 

Yes you are asking to create an rbd image with your own prefix.  

> Ok so now I take the volume id from the output and try to stage that with this command:
> 
> `csc -e unix:///tmp/csiceph.sock node stage --cap SINGLE_NODE_WRITER,block --staging-target-path '/mnt/staging/' --vol-context 'clusterID=ceph,pool=app,volumeNamePrefix=app-,imageFeatures=layering' '0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1'`
> 
> Then I get a different error "rbd: ret=-22, Invalid argument: RBD image not found"
> 
> The csiceph plugin returns this log.
> 

What version of cephcsi you are using?

> ```
> I1217 13:11:24.621519   16020 utils.go:132] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 GRPC call: /csi.v1.Node/NodeStageVolume
> I1217 13:11:24.622979   16020 utils.go:133] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 GRPC request: {"secrets":"***stripped***","staging_target_path":"/mnt/staging/","volume_capability":{"AccessType":{"Block":{}},"access_mode":{"mode":1}},"volume_context":{"clusterID":"ceph","imageFeatures":"layering","pool":"app","volumeNamePrefix":"app-"},"volume_id":"0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1"}
> I1217 13:11:24.625095   16020 rbd_util.go:808] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 setting disableInUseChecks on rbd volume to: false
> I1217 13:11:24.629305   16020 omap.go:84] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 got omap values: (pool="app", namespace="", name="csi.volume.7957e938-405a-11eb-bfd0-0050563001a1"): map[csi.imageid:4d2433a92eda7d csi.imagename:app-7957e938-405a-11eb-bfd0-0050563001a1 csi.volname:app-test2]
> E1217 13:11:24.630865   16020 util.go:232] kernel 3.10.0-1160.6.1.el7.x86_64 does not support required features
> I1217 13:11:24.687629   16020 rbd_util.go:326] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 executing [rbd task add flatten app/app-7957e938-405a-11eb-bfd0-0050563001a1 --id app.mesos --keyfile=/tmp/csi/keys/keyfile-157862282 -m 192.168.10.111,192.168.10.112,192.168.10.113] for image (app-7957e938-405a-11eb-bfd0-0050563001a1) using mon 192.168.10.111,192.168.10.112,192.168.10.113, pool app
> I1217 13:11:25.563996   16020 cephcmds.go:53] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 an error (exit status 13) occurred while running ceph args: [rbd task add flatten app/app-7957e938-405a-11eb-bfd0-0050563001a1 --id app.mesos --keyfile=***stripped*** -m 192.168.10.111,192.168.10.112,192.168.10.113]
> W1217 13:11:25.564392   16020 rbd_util.go:337] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 access denied to Ceph MGR-based rbd commands on cluster ID (ceph)
> E1217 13:11:25.564616   16020 rbd_util.go:508] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 task manager does not support flatten,image will be flattened once hardlimit is reached: an error (exit status 13) occurred while running ceph args: [rbd task add flatten app/app-7957e938-405a-11eb-bfd0-0050563001a1 --id app.mesos --keyfile=***stripped*** -m 192.168.10.111,192.168.10.112,192.168.10.113]
> E1217 13:11:25.662586   16020 rbd_util.go:516] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 rbd failed to flatten image app app-7957e938-405a-11eb-bfd0-0050563001a1: rbd: ret=-22, Invalid argument: RBD image not found
> E1217 13:11:25.664080   16020 utils.go:136] ID: 10 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 GRPC error: rpc error: code = Internal desc = rbd: ret=-22, Invalid argument: RBD image not found
> ```
> 
> Hmmmm, so lets try again with -forcecephkernelclient
> 

ForceKernelClient is not for RBD it's for cephfs.

> ```
> I1217 13:27:16.330084   16318 utils.go:132] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 GRPC call: /csi.v1.Node/NodeStageVolume
> I1217 13:27:16.337391   16318 utils.go:133] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 GRPC request: {"secrets":"***stripped***","staging_target_path":"/mnt/staging/","volume_capability":{"AccessType":{"Block":{}},"access_mode":{"mode":1}},"volume_context":{"clusterID":"ceph","imageFeatures":"layering","pool":"app","volumeNamePrefix":"app-"},"volume_id":"0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1"}
> I1217 13:27:16.338949   16318 rbd_util.go:808] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 setting disableInUseChecks on rbd volume to: false
> I1217 13:27:16.507780   16318 omap.go:84] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 got omap values: (pool="app", namespace="", name="csi.volume.7957e938-405a-11eb-bfd0-0050563001a1"): map[csi.imageid:4d2433a92eda7d csi.imagename:app-7957e938-405a-11eb-bfd0-0050563001a1 csi.volname:app-test2]
> E1217 13:27:16.509268   16318 util.go:232] kernel 3.10.0-1160.6.1.el7.x86_64 does not support required features
> I1217 13:27:16.561805   16318 rbd_util.go:326] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 executing [rbd task add flatten app/app-7957e938-405a-11eb-bfd0-0050563001a1 --id app.mesos --keyfile=/tmp/csi/keys/keyfile-975520426 -m 192.168.10.111,192.168.10.112,192.168.10.113] for image (app-7957e938-405a-11eb-bfd0-0050563001a1) using mon 192.168.10.111,192.168.10.112,192.168.10.113, pool app
> I1217 13:27:17.427406   16318 cephcmds.go:53] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 an error (exit status 13) occurred while running ceph args: [rbd task add flatten app/app-7957e938-405a-11eb-bfd0-0050563001a1 --id app.mesos --keyfile=***stripped*** -m 192.168.10.111,192.168.10.112,192.168.10.113]
> W1217 13:27:17.433269   16318 rbd_util.go:337] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 access denied to Ceph MGR-based rbd commands on cluster ID (ceph)
> E1217 13:27:17.433373   16318 rbd_util.go:508] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 task manager does not support flatten,image will be flattened once hardlimit is reached: an error (exit status 13) occurred while running ceph args: [rbd task add flatten app/app-7957e938-405a-11eb-bfd0-0050563001a1 --id app.mesos --keyfile=***stripped*** -m 192.168.10.111,192.168.10.112,192.168.10.113]
> E1217 13:27:17.513076   16318 rbd_util.go:516] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 rbd failed to flatten image app app-7957e938-405a-11eb-bfd0-0050563001a1: rbd: ret=-22, Invalid argument: RBD image not found
> E1217 13:27:17.514554   16318 utils.go:136] ID: 1 Req-ID: 0001-0004-ceph-0000000000000016-7957e938-405a-11eb-bfd0-0050563001a1 GRPC error: rpc error: code = Internal desc = rbd: ret=-22, Invalid argument: RBD image not found
> ```
> 
> So still the same 'RBD image not found'
> 
> * What is the csi event to retrieve this volume id? How can I get this volumeID from a pre-provisioned Volume?

the volume ID will be create by the cephcsi driver for the rbd image its creating

> * And why is csiceph plugin showing 'NodeStageVolume' and not 'NodeStageVolumeID' in logs? 

This is as per the standard RPC request.

I still cannot understand that if I use the CreateVolume event with an argument, I can not use the same argument with a PublishVolume or StageVolume event.

I would suggest you to check how cs tool is implemented and what are the parameters for different RPC calls
and also it's good to go through the latest CSI spec and cephcsi documents.

**Comment by f1-outsourcing** [comment]
> the volume ID will be create by the cephcsi driver for the rbd image its creating

but where is this volume ID stored?

**Comment by f1-outsourcing** [comment]
(using 3.2.0 still) ok so adding the imageFeatures=layering to the createVolume makes it possible for me to stage the volume.

**Comment by Madhu-1** [comment]
sounds good. Closing it's not an issue

**Comment by hasonhai** [comment]
I need to convert the pv from k8s in-tree rbd-provisioner to ceph-csi version. Currently I can only convert it to static PV. But with static PV, I cannot resize or delete the rbd image in the pool. Is there any way to generate the volumeHandle ID to make static PV become dynamic PV?

**Comment by AntoineNGUYEN31** [comment]
@hasonhai @f1-outsourcing the volumeHandleID is computed as below
0001-00[Min Size of pool][Size]-[cluster uid]-000000000000000[pool number in hexa]-[image uid]
The first 4 digit seems not important, it works with 0002 too :)
