### ISSUE TITLE
Unable to delete ghost snapshot

### ISSUE THREAD

**Issue by crazyworlds** [ceph/ceph-csi#1816]
# Describe the bug #

Due to an incorrect configuration, some snapshots not linked to any volume persist and it is impossible to delete

- Image/version of Ceph CSI driver : release-v3.2
- Kernel version : 4.18.0-193.19.1.el8_2.x86_64
- Kubernetes cluster version :  1.19.4
- Ceph cluster version : 14.2.15

We notice some snapshat not bounded to volume. 
We try to delete them, but we are unable to do it.:

`kubectl -n idsprod delete volumesnapshot velero-data-mariadb-galera-0-qcvh7  --grace-period=0 --force

warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.

volumesnapshot.snapshot.storage.k8s.io "velero-data-mariadb-galera-0-qcvh7" force deleted
error: An error occurred while waiting for the object to be deleted: an error on the server ("unable to decode an event from the watch stream: stream error: stream ID 5; INTERNAL_ERROR") has prevented the request from succeeding
`

It's possibile that this sitution is caused by storage/backup moving.

`kubectl get volumesnapshot -A 
NAMESPACE   NAME                                                              READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT                                             RESTORESIZE   SNAPSHOTCLASS                SNAPSHOTCONTENT                                                   CREATIONTIME   AGE
i
dsprod     velero-data-mariadb-galera-0-qcvh7                                true                     velero-velero-data-mariadb-galera-0-qcvh7-vn7ns                   0             csi-rbdplugin-snapclass      velero-velero-data-mariadb-galera-0-qcvh7-vn7ns                   6d20h          6d20h

idsprod     velero-data-mariadb-galera-1-nhpq2                                true                     velero-velero-data-mariadb-galera-1-nhpq2-f2sz8                   0             csi-rbdplugin-snapclass      velero-velero-data-mariadb-galera-1-nhpq2-f2sz8                   6d20h          6d20h

idsprod     velero-data-mariadb-galera-2-w2vsh                                true                     velero-velero-data-mariadb-galera-2-w2vsh-tdtjp                   0             csi-rbdplugin-snapclass      velero-velero-data-mariadb-galera-2-w2vsh-tdtjp                   6d20h          6d20h

idsprod     velero-wso2is-pattern-1-identity-server-shared-tenants-vol4zltb   true                     velero-velero-wso2is-pattern-1-identity-server-shared-tenaf2d82   0             csi-cephfsplugin-snapclass   velero-velero-wso2is-pattern-1-identity-server-shared-tenaf2d82   6d20h          6d20h

idsprod     velero-wso2is-pattern-1-identity-server-shared-userstores-tgmfw   true                     velero-velero-wso2is-pattern-1-identity-server-shared-user8kblp   0             csi-cephfsplugin-snapclass   velero-velero-wso2is-pattern-1-identity-server-shared-user8kblp   6d20h          6d20h

idsprod     velero-wso2is-pv-claim-app-authentication-endpoint-new-vc2cc      true                     velero-velero-wso2is-pv-claim-app-authentication-endpoint-h7fc6   0             csi-cephfsplugin-snapclass   velero-velero-wso2is-pv-claim-app-authentication-endpoint-h7fc6   6d20h          6d20h

idsprod     velero-wso2is-pv-claim-new-9jw8w                                  true                     velero-velero-wso2is-pv-claim-new-9jw8w-ff5l6                     0             csi-cephfsplugin-snapclass   velero-velero-wso2is-pv-claim-new-9jw8w-ff5l6                     6d20h          6d20h

idsprod     velero-wso2is-pv-claim-userstores-new-7xm9m                       true                     velero-velero-wso2is-pv-claim-userstores-new-7xm9m-sll6z          0             csi-cephfsplugin-snapclass   velero-velero-wso2is-pv-claim-userstores-new-7xm9m-sll6z          6d20h          6d20h

idsprod     velero-wso2is-pv-security-new-mgdk4                               true                     velero-velero-wso2is-pv-security-new-mgdk4-ffrqn                  0             csi-cephfsplugin-snapclass   velero-velero-wso2is-pv-security-new-mgdk4-ffrqn                  6d20h          6d20h

$ kubectl get volumesnapshotcontents.snapshot.storage.k8s.io  

NAME                                                              READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER                VOLUMESNAPSHOTCLASS          VOLUMESNAPSHOT                                                    AGE

snapcontent-08bfc73c-2126-4a81-90b8-520b21cd07bc                  false                      Delete           cephfs.csi.ceph.com   csi-cephfsplugin-snapclass   velero-wso2is-pv-claim-new-9jw8w                                  6d20h

snapcontent-16a7c1fb-c27a-4c33-af91-326f6e1aea9c                  false                      Delete           cephfs.csi.ceph.com   csi-cephfsplugin-snapclass   velero-wso2is-pattern-1-identity-server-shared-userstores-tgmfw   6d20h

snapcontent-46ab940e-7f6a-4101-931c-dca888df6d97                  false                      Delete           cephfs.csi.ceph.com   csi-cephfsplugin-snapclass   velero-wso2is-pattern-1-identity-server-shared-tenants-vol4zltb   6d20h

snapcontent-56d789cd-70ac-4c46-b683-1b26d108083e                  false                      Delete           cephfs.csi.ceph.com   csi-cephfsplugin-snapclass   velero-wso2is-pv-claim-app-authentication-endpoint-new-vc2cc      6d20h

snapcontent-5bb1f802-bad0-48c8-ab68-6e883a0e6b60                  false                      Delete           cephfs.csi.ceph.com   csi-cephfsplugin-snapclass   velero-wso2is-pv-claim-userstores-new-7xm9m                       6d20h

snapcontent-8a8aa655-a000-40ea-b6aa-aaf6c737b283                  false                      Delete           cephfs.csi.ceph.com   csi-cephfsplugin-snapclass   velero-wso2is-pv-security-new-mgdk4                               6d20h

snapcontent-8aa93498-8993-478e-98de-b595a7b23c18                                             Delete           rbd.csi.ceph.com      csi-rbdplugin-snapclass      velero-data-mariadb-galera-2-w2vsh                                6d20h

snapcontent-e1b06fc4-4d3f-4066-90b6-fae8db144417                                             Delete           rbd.csi.ceph.com      csi-rbdplugin-snapclass      velero-data-mariadb-galera-1-nhpq2                                6d20h

snapcontent-fff99732-b990-414b-9457-e4934b563f0c                                             Delete           rbd.csi.ceph.com      csi-rbdplugin-snapclass      velero-data-mariadb-galera-0-qcvh7                                6d20h

velero-velero-data-mariadb-galera-0-qcvh7-vn7ns                   true         0             Delete           rbd.csi.ceph.com      csi-rbdplugin-snapclass      velero-data-mariadb-galera-0-qcvh7                                6d20h

velero-velero-data-mariadb-galera-1-nhpq2-f2sz8                   true         0             Delete           rbd.csi.ceph.com      csi-rbdplugin-snapclass      velero-data-mariadb-galera-1-nhpq2                                6d20h

velero-velero-data-mariadb-galera-2-w2vsh-tdtjp                   true         0             Delete           rbd.csi.ceph.com      csi-rbdplugin-snapclass      velero-data-mariadb-galera-2-w2vsh                                6d20h

velero-velero-wso2is-pattern-1-identity-server-shared-tenaf2d82   true         0             Delete           cephfs.csi.ceph.com   csi-cephfsplugin-snapclass   velero-wso2is-pattern-1-identity-server-shared-tenants-vol4zltb   6d20h

velero-velero-wso2is-pattern-1-identity-server-shared-user8kblp   true         0             Delete           cephfs.csi.ceph.com   csi-cephfsplugin-snapclass   velero-wso2is-pattern-1-identity-server-shared-userstores-tgmfw   6d20h

velero-velero-wso2is-pv-claim-app-authentication-endpoint-h7fc6   true         0             Delete           cephfs.csi.ceph.com   csi-cephfsplugin-snapclass   velero-wso2is-pv-claim-app-authentication-endpoint-new-vc2cc      6d20h

velero-velero-wso2is-pv-claim-new-9jw8w-ff5l6                     true         0             Delete           cephfs.csi.ceph.com   csi-cephfsplugin-snapclass   velero-wso2is-pv-claim-new-9jw8w                                  6d20h

velero-velero-wso2is-pv-claim-userstores-new-7xm9m-sll6z          true         0             Delete           cephfs.csi.ceph.com   csi-cephfsplugin-snapclass   velero-wso2is-pv-claim-userstores-new-7xm9m                       6d20h

velero-velero-wso2is-pv-security-new-mgdk4-ffrqn                  true         0             Delete           cephfs.csi.ceph.com   csi-cephfsplugin-snapclass   velero-wso2is-pv-security-new-mgdk4                               6d20h
:~$ 
`

- csi-snapshotter and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

`
I1224 12:03:56.317277       1 request.go:581] Throttling request took 590.623348ms, request: PUT:https://10.43.0.1:443/apis/snapshot.storage.k8s.io/v1beta1/volumesnapshotcontents/snapcontent-8aa93498-8993-478e-98de-b595a7b23c18 
I1224 12:03:56.324970       1 util.go:258] storeObjectUpdate updating content "snapcontent-8aa93498-8993-478e-98de-b595a7b23c18" with version 5095264 
I1224 12:03:56.324992       1 snapshot_controller.go:583] setAnnVolumeSnapshotBeingCreated: volume snapshot content &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:snapcontent-8aa93498-8993-478e-98de-b595a7b23c18 GenerateName: Namespace: SelfLink:/apis/snapshot.storage.k8s.io/v1beta1/volumesnapshotcontents/snapcontent-8aa93498-8993-478e-98de-b595a7b23c18 UID:0bce6071-12ab-4351-a1fb-556bcd823ffc ResourceVersion:5095264 Generation:1 CreationTimestamp:2020-12-17 15:27:45 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[velero.io/backup-name:idsprod001] Annotations:map[snapshot.storage.kubernetes.io/deletion-secret-name:csi-rbd-secret snapshot.storage.kubernetes.io/deletion-secret-namespace:default snapshot.storage.kubernetes.io/volumesnapshot-being-created:yes] OwnerReferences:[] Finalizers:[snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection] ClusterName: ManagedFields:[{Manager:velero-server Operation:Update APIVersion:snapshot.storage.k8s.io/v1beta1 Time:2020-12-17 15:27:45 +0000 UTC FieldsType:FieldsV1 FieldsV1:{"f:metadata":{"f:annotations":{".":{},"f:snapshot.storage.kubernetes.io/deletion-secret-name":{},"f:snapshot.storage.kubernetes.io/deletion-secret-namespace":{}},"f:finalizers":{".":{},"v:\"snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection\"":{}},"f:labels":{".":{},"f:velero.io/backup-name":{}}},"f:spec":{".":{},"f:deletionPolicy":{},"f:driver":{},"f:source":{".":{},"f:volumeHandle":{}},"f:volumeSnapshotClassName":{},"f:volumeSnapshotRef":{".":{},"f:apiVersion":{},"f:kind":{},"f:name":{},"f:namespace":{},"f:resourceVersion":{},"f:uid":{}}},"f:status":{".":{},"f:creationTime":{},"f:readyToUse":{},"f:restoreSize":{},"f:snapshotHandle":{}}}} {Manager:csi-snapshotter Operation:Update APIVersion:snapshot.storage.k8s.io/v1beta1 Time:2020-12-24 12:03:59 +0000 UTC FieldsType:FieldsV1 FieldsV1:{"f:metadata":{"f:annotations":{"f:snapshot.storage.kubernetes.io/volumesnapshot-being-created":{}}}}}]} Spec:{VolumeSnapshot 
Ref:{Kind:VolumeSnapshot Namespace:idsprod Name:velero-data-mariadb-galera-2-w2vsh UID:8aa93498-8993-478e-98de-b595a7b23c18 APIVersion:snapshot.storage.k8s.io/v1beta1 ResourceVersion:310727763 FieldPath:} DeletionPolicy:Delete Driver:rbd.csi.ceph.com VolumeSnapshotClassName:0xc00014e8a0 Source:{VolumeHandle:0xc00014e890 SnapshotHandle:<nil>}} Status:<nil>} 
I1224 12:03:56.325091       1 snapshotter.go:56] CSI CreateSnapshot: snapshot-8aa93498-8993-478e-98de-b595a7b23c18 
I1224 12:03:56.326251       1 snapshot_controller_base.go:140] enqueued "snapcontent-8aa93498-8993-478e-98de-b595a7b23c18" for sync 
I1224 12:03:56.350710       1 snapshot_controller.go:292] createSnapshotWrapper: CreateSnapshot for content snapcontent-8aa93498-8993-478e-98de-b595a7b23c18 returned error: rpc error: code = Internal desc = rados: ret=-1, Operation not permitted 
I1224 12:03:56.350751       1 snapshot_controller.go:142] updateContentStatusWithEvent[snapcontent-8aa93498-8993-478e-98de-b595a7b23c18] 
I1224 12:03:56.517277       1 request.go:581] Throttling request took 592.516672ms, request: PUT:https://10.43.0.1:443/apis/snapshot.storage.k8s.io/v1beta1/volumesnapshotcontents/snapcontent-fff99732-b990-414b-9457-e4934b563f0c/status 
I1224 12:03:56.522782       1 snapshot_controller.go:166] updating VolumeSnapshotContent[snapcontent-fff99732-b990-414b-9457-e4934b563f0c] error status failed Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io "snapcontent-fff99732-b990-414b-9457-e4934b563f0c": the object has been modified; please apply your changes to the latest version and try again 
E1224 12:03:56.522800       1 snapshot_controller.go:106] createSnapshot for content [snapcontent-fff99732-b990-414b-9457-e4934b563f0c]: error occurred in createSnapshotWrapper: failed to take snapshot of the volume, 0001-0024-d9ed3cd5-8d90-4ec4-90fc-8ceac9897746-0000000000000016-39102580-407a-11eb-9f59-526aa67cc365: %!q(<nil>) 
E1224 12:03:56.522810       1 snapshot_controller_base.go:261] could not sync content "snapcontent-fff99732-b990-414b-9457-e4934b563f0c": failed to take snapshot of the volume, 0001-0024-d9ed3cd5-8d90-4ec4-90fc-8ceac9897746-0000000000000016-39102580-407a-11eb-9f59-526aa67cc365: %!q(<nil>) 
I1224 12:03:56.522829       1 snapshot_controller_base.go:163] Failed to sync content "snapcontent-fff99732-b990-414b-9457-e4934b563f0c", will retry again: failed to take snapshot of the volume, 0001-0024-d9ed3cd5-8d90-4ec4-90fc-8ceac9897746-0000000000000016-39102580-407a-11eb-9f59-526aa67cc365: %!q(<nil>) 
I1224 12:03:56.522839       1 snapshot_controller_base.go:174] syncContentByKey[snapcontent-fff99732-b990-414b-9457-e4934b563f0c] 
I1224 12:03:56.522855       1 util.go:258] storeObjectUpdate updating content "snapcontent-fff99732-b990-414b-9457-e4934b563f0c" with version 5095261 
I1224 12:03:56.522863       1 snapshot_controller.go:57] synchronizing VolumeSnapshotContent[snapcontent-fff99732-b990-414b-9457-e4934b563f0c] 
I1224 12:03:56.522867       1 snapshot_controller.go:531] Check if VolumeSnapshotContent[snapcontent-fff99732-b990-414b-9457-e4934b563f0c] should be deleted. 
I1224 12:03:56.522871       1 snapshot_controller.go:76] syncContent: Call CreateSnapshot for content snapcontent-fff99732-b990-414b-9457-e4934b563f0c 
I1224 12:03:56.522884       1 snapshot_controller.go:102] createSnapshot for content [snapcontent-fff99732-b990-414b-9457-e4934b563f0c]: started 
I1224 12:03:56.522889       1 snapshot_controller.go:268] createSnapshotWrapper: Creating snapshot for content snapcontent-fff99732-b990-414b-9457-e4934b563f0c through the plugin ... 
I1224 12:03:56.522893       1 snapshot_controller.go:181] getCSISnapshotInput for content [snapcontent-fff99732-b990-414b-9457-e4934b563f0c] 
I1224 12:03:56.522896       1 snapshot_controller.go:439] getSnapshotClass: VolumeSnapshotClassName [csi-rbdplugin-snapclass] 
I1224 12:03:56.522894       1 event.go:282] Event(v1.ObjectReference{Kind:"VolumeSnapshotContent", Namespace:"", Name:"", UID:"", APIVersion:"snapshot.storage.k8s.io/v1beta1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'SnapshotCreationFailed' Failed to create snapshot: failed to take snapshot of the volume, 0001-0024-d9ed3cd5-8d90-4ec4-90fc-8ceac9897746-0000000000000016-39102580-407a-11eb-9f59-526aa67cc365: %!q(<nil>) 
I1224 12:03:56.526398       1 snapshot_controller.go:568] setAnnVolumeSnapshotBeingCreated: set annotation [snapshot.storage.kubernetes.io/volumesnapshot-being-created:yes] on content [snapcontent-fff99732-b990-414b-9457-e4934b563f0c]. 
I1224 12:03:56.717263       1 request.go:581] Throttling request took 587.638168ms, request: PUT:https://10.43.0.1:443/apis/snapshot.storage.k8s.io/v1beta1/volumesnapshotcontents/snapcontent-e1b06fc4-4d3f-4066-90b6-fae8db144417 
I1224 12:03:56.726372       1 snapshot_controller.go:605] Removed VolumeSnapshotBeingCreated annotation from volume snapshot content snapcontent-e1b06fc4-4d3f-4066-90b6-fae8db144417 
I1224 12:03:56.726411       1 util.go:258] storeObjectUpdate updating content "snapcontent-e1b06fc4-4d3f-4066-90b6-fae8db144417" with version 5095270 
I1224 12:03:56.726427       1 snapshot_controller.go:142] updateContentStatusWithEvent[snapcontent-e1b06fc4-4d3f-4066-90b6-fae8db144417] 
I1224 12:03:56.726575       1 snapshot_controller_base.go:140] enqueued "snapcontent-e1b06fc4-4d3f-4066-90b6-fae8db144417" for sync 
I1224 12:03:56.917278       1 request.go:581] Throttling request took 566.378534ms, request: PUT:https://10.43.0.1:443/apis/snapshot.storage.k8s.io/v1beta1/volumesnapshotcontents/snapcontent-8aa93498-8993-478e-98de-b595a7b23c18/status 
I1224 12:03:56.923761       1 snapshot_controller.go:166] updating VolumeSnapshotContent[snapcontent-8aa93498-8993-478e-98de-b595a7b23c18] error status failed Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io "snapcontent-8aa93498-8993-478e-98de-b595a7b23c18": the object has been modified; please apply your changes to the latest version and try again 
E1224 12:03:56.923779       1 snapshot_controller.go:106] createSnapshot for content [snapcontent-8aa93498-8993-478e-98de-b595a7b23c18]: error occurred in createSnapshotWrapper: failed to take snapshot of the volume, 0001-0024-d9ed3cd5-8d90-4ec4-90fc-8ceac9897746-0000000000000016-37aab5fa-407a-11eb-92ef-aeada00b5156: %!q(<nil>) 
E1224 12:03:56.923788       1 snapshot_controller_base.go:261] could not sync content "snapcontent-8aa93498-8993-478e-98de-b595a7b23c18": failed to take snapshot of the volume, 0001-0024-d9ed3cd5-8d90-4ec4-90fc-8ceac9897746-0000000000000016-37aab5fa-407a-11eb-92ef-aeada00b5156: %!q(<nil>) 
I1224 12:03:56.923807       1 snapshot_controller_base.go:163] Failed to sync content "snapcontent-8aa93498-8993-478e-98de-b595a7b23c18", will retry again: failed to take snapshot of the volume, 0001-0024-d9ed3cd5-8d90-4ec4-90fc-8ceac9897746-0000000000000016-37aab5fa-407a-11eb-92ef-aeada00b5156: %!q(<nil>) 
I1224 12:03:56.923817       1 snapshot_controller_base.go:174] syncContentByKey[snapcontent-8aa93498-8993-478e-98de-b595a7b23c18] 
I1224 12:03:56.923833       1 util.go:258] storeObjectUpdate updating content "snapcontent-8aa93498-8993-478e-98de-b595a7b23c18" with version 5095264 
I1224 12:03:56.923843       1 snapshot_controller.go:57] synchronizing VolumeSnapshotContent[snapcontent-8aa93498-8993-478e-98de-b595a7b23c18] 
I1224 12:03:56.923848       1 snapshot_controller.go:531] Check if VolumeSnapshotContent[snapcontent-8aa93498-8993-478e-98de-b595a7b23c18] should be deleted. 
I1224 12:03:56.923852       1 snapshot_controller.go:76] syncContent: Call CreateSnapshot for content snapcontent-8aa93498-8993-478e-98de-b595a7b23c18 
I1224 12:03:56.923856       1 snapshot_controller.go:102] createSnapshot for content [snapcontent-8aa93498-8993-478e-98de-b595a7b23c18]: started 
I1224 12:03:56.923860       1 snapshot_controller.go:268] createSnapshotWrapper: Creating snapshot for content snapcontent-8aa93498-8993-478e-98de-b595a7b23c18 through the plugin ... 
I1224 12:03:56.923864       1 snapshot_controller.go:181] getCSISnapshotInput for content [snapcontent-8aa93498-8993-478e-98de-b595a7b23c18] 
I1224 12:03:56.923868       1 snapshot_controller.go:439] getSnapshotClass: VolumeSnapshotClassName [csi-rbdplugin-snapclass] 
I1224 12:03:56.923874       1 event.go:282] Event(v1.ObjectReference{Kind:"VolumeSnapshotContent", Namespace:"", Name:"", UID:"", APIVersion:"snapshot.storage.k8s.io/v1beta1", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'SnapshotCreationFailed' Failed to create snapshot: failed to take snapshot of the volume, 0001-0024-d9ed3cd5-8d90-4ec4-90fc-8ceac9897746-0000000000000016-37aab5fa-407a-11eb-92ef-aeada00b5156: %!q(<nil>) 
I1224 12:03:56.927440       1 snapshotter.go:56] CSI CreateSnapshot: snapshot-8aa93498-8993-478e-98de-b595a7b23c18 
I1224 12:03:56.930547       1 snapshot_controller.go:292] createSnapshotWrapper: CreateSnapshot for content snapcontent-8aa93498-8993-478e-98de-b595a7b23c18 returned error: rpc error: code = Internal desc = rados: ret=-1, Operation not permitted 
I1224 12:03:57.117268       1 request.go:581] Throttling request took 590.750666ms, request: PUT:https://10.43.0.1:443/apis/snapshot.storage.k8s.io/v1beta1/volumesnapshotcontents/snapcontent-fff99732-b990-414b-9457-e4934b563f0c 
I1224 12:03:57.126299       1 util.go:258] storeObjectUpdate updating content "snapcontent-fff99732-b990-414b-9457-e4934b563f0c" with version 5095273 
I1224 12:03:57.126395       1 snapshot_controller_base.go:140] enqueued "snapcontent-fff99732-b990-414b-9457-e4934b563f0c" for sync 
I1224 12:03:57.126327       1 snapshot_controller.go:583] setAnnVolumeSnapshotBeingCreated: volume snapshot content &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:snapcontent-fff99732-b990-414b-9457-e4934b563f0c GenerateName: Namespace: SelfLink:/apis/snapshot.storage.k8s.io/v1beta1/volumesnapshotcontents/snapcontent-fff99732-b990-414b-9457-e4934b563f0c UID:15d86a7d-485e-47c0-94eb-0c24633e7569 ResourceVersion:5095273 Generation:1 CreationTimestamp:2020-12-17 15:27:45 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[velero.io/backup-name:idsprod001] Annotations:map[snapshot.storage.kubernetes.io/deletion-secret-name:csi-rbd-secret snapshot.storage.kubernetes.io/deletion-secret-namespace:default snapshot.storage.kubernetes.io/volumesnapshot-being-created:yes] OwnerReferences:[] Finalizers:[snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection] ClusterName: ManagedFields:[{Manager:velero-server Operation:Update APIVersion:snapshot.storage.k8s.io/v1beta1 Time:2020-12-17 15:27:45 +0000 UTC FieldsType:FieldsV1 FieldsV1:{"f:metadata":{"f:annotations":{".":{},"f:snapshot.storage.kubernetes.io/deletion-secret-name":{},"f:snapshot.storage.kubernetes.io/deletion-secret-namespace":{}},"f:finalizers":{".":{},"v:\"snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection\"":{}},"f:labels":{".":{},"f:velero.io/backup-name":{}}},"f:spec":{".":{},"f:deletionPolicy":{},"f:driver":{},"f:source":{".":{},"f:volumeHandle":{}},"f:volumeSnapshotClassName":{},"f:volumeSnapshotRef":{".":{},"f:apiVersion":{},"f:kind":{},"f:name":{},"f:namespace":{},"f:resourceVersion":{},"f:uid":{}}},"f:status":{".":{},"f:creationTime":{},"f:readyToUse":{},"f:restoreSize":{},"f:snapshotHandle":{}}}} {Manager:csi-snapshotter Operation:Update APIVersion:snapshot.storage.k8s.io/v1beta1 Time:2020-12-24 12:04:00 +0000 UTC FieldsType:FieldsV1 FieldsV1:{"f:metadata":{"f:annotations":{"f:snapshot.storage.kubernetes.io/volumesnapshot-being-created":{}}}}}]} Spec:{VolumeSnapshot 
Ref:{Kind:VolumeSnapshot Namespace:idsprod Name:velero-data-mariadb-galera-0-qcvh7 UID:fff99732-b990-414b-9457-e4934b563f0c APIVersion:snapshot.storage.k8s.io/v1beta1 ResourceVersion:310727644 FieldPath:} DeletionPolicy:Delete Driver:rbd.csi.ceph.com VolumeSnapshotClassName:0xc000567400 Source:{VolumeHandle:0xc0005673f0 SnapshotHandle:<nil>}} Status:<nil>} 
I1224 12:03:57.126443       1 snapshotter.go:56] CSI CreateSnapshot: snapshot-fff99732-b990-414b-9457-e4934b563f0c 
I1224 12:03:57.131681       1 snapshot_controller.go:292] createSnapshotWrapper: CreateSnapshot for content snapcontent-fff99732-b990-414b-9457-e4934b563f0c returned error: rpc error: code = Internal desc = rados: ret=-1, Operation not permitted 
I1224 12:03:57.131716       1 snapshot_controller.go:142] updateContentStatusWithEvent[snapcontent-fff99732-b990-414b-9457-e4934b563f0c] 

`

**Comment by Madhu-1** [comment]
>I1224 12:03:56.930547 1 snapshot_controller.go:292] createSnapshotWrapper: CreateSnapshot for content snapcontent-8aa93498-8993-478e-98de-b595a7b23c18 returned error: rpc error: code = Internal desc = rados: ret=-1, Operation not permitted

the above looks to be a permission issue.
