### ISSUE TITLE
ceph fs cannot use in PV

### ISSUE THREAD

**Issue by liyin37** [ceph/ceph-csi#1824]
# Describe the bug #

# Environment details #

- Image/version of Ceph CSI driver : release-v3.2.0
- Helm chart version :
- Kernel version : 3.10.0-957.21.3.el7.x86_64 +
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
- Kubernetes cluster version : v1.17.0
- Ceph cluster version : ceph version 13.2.10 (564bdc4ae87418a232fc901524470e1a0f76d641) mimic (stable)

# Steps to reproduce #

1. Setup details: '...'
1. Deployment to trigger the issue '....'
1. See error

# Actual results #

Describe what happened

# Expected behavior #

# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.
Name:          csi-cephfs-pvc
Namespace:     default
StorageClass:  csi-cephfs-sc
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"csi-cephfs-pvc","namespace":"default"},"spec":{"acc...
               volume.beta.kubernetes.io/storage-provisioner: cephfs.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason                Age                From                                                                                                   Message
  ----     ------                ----               ----                                                                                                   -------
  Normal   Provisioning          14s (x6 over 29s)  cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-fc8545f74-qr75m_63a83a70-8d3d-4898-a830-7d67bef20123  External provisioner is provisioning volume for claim "default/csi-cephfs-pvc"
  Warning  ProvisioningFailed    14s (x6 over 29s)  cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-fc8545f74-qr75m_63a83a70-8d3d-4898-a830-7d67bef20123  failed to provision volume with StorageClass "csi-cephfs-sc": rpc error: code = Internal desc = API call not implemented server-side: No handler found for 'fs subvolumegroup create'
  Normal   ExternalProvisioning  6s (x4 over 29s)   persistentvolume-controller                                                                            waiting for a volume to be created, either by external provisioner "cephfs.csi.ceph.com" or manually created by system administrator

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC resize please attach complete logs of below containers.

- csi-resizer and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in snapshot creation and deletion please attach complete logs
of below containers.

- csi-snapshotter and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC mounting please attach complete logs of below containers.

- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
  plugin pod from the node where the mount is failing.

- if required attach dmesg logs.

**Note:-** If its a rbd issue please provide only rbd related logs, if its a
cephfs issue please provide cephfs logs.

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior
the same problem：https://github.com/ceph/ceph-csi/issues/562，but I set it with the same,it dont works .
ceph.conf
[mgr]
client mount uid = 0
client mount gid = 0

mgr.service
[Unit]
Description=Ceph cluster manager daemon
After=network-online.target local-fs.target time-sync.target
Wants=network-online.target local-fs.target time-sync.target
PartOf=ceph-mgr.target

[Service]
LimitNOFILE=1048576
LimitNPROC=1048576
EnvironmentFile=-/etc/sysconfig/ceph
Environment=CLUSTER=ceph

ExecStart=/usr/bin/ceph-mgr -f --cluster ${CLUSTER} --id %i --setuser root --setgroup root
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=10
StartLimitInterval=30min
StartLimitBurst=3

[Install]
WantedBy=ceph-mgr.target

then restart the mgr.service on ceph nodes:
sudo systemctl daemon-reload
sudo systemctl restart ceph-mgr@node1
sudo systemctl restart ceph-mgr@node2
sudo systemctl restart ceph-mgr@node3

**Comment by Madhu-1** [comment]
@liyin37 minimum required ceph version is 14.2.2 for cephcsi to work, please refer to https://github.com/ceph/ceph-csi#support-matrix for supported ceph version details.

**Comment by liyin37** [comment]
@Madhu-1  thanks for your answer,buy the way,I update the ceph version to "ceph version 15.2.8 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable)
"
then use the default user：admin  can use cephfs ,but I ceph auth new user,it does't works ,the error in pvc is below:
--
  Normal   Provisioning          25s (x7 over 55s)  cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-fc8545f74-2nkcr_4039e16d-af61-4a13-8b13-d0e9d392d1e2  External provisioner is provisioning volume for claim "default/csi-cephfs-pvc"
  Warning  ProvisioningFailed    25s (x7 over 55s)  cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-fc8545f74-2nkcr_4039e16d-af61-4a13-8b13-d0e9d392d1e2  failed to provision volume with StorageClass "csi-cephfs-sc": rpc error: code = Internal desc = rados: ret=-13, Permission denied: "access denied: does your client key have mgr caps? See http://docs.ceph.com/docs/master/mgr/administrator/#client-authentication"
  Normal   ExternalProvisioning  14s (x4 over 55s)  persistentvolume-controller                                                                            waiting for a volume to be created, either by external provisioner "cephfs.csi.ceph.com" or manually created by system administrator

the user client.cephfs create command is : 
ceph auth caps client.cephfs mon 'allow r' mds 'allow rw' mgr 'allow rwx' osd 'allow rwx pool=fs_metadata,allow rwx pool=fs_data'
[ceph@node1 ~]$ ceph auth get client.cephfs
exported keyring for client.cephfs
[client.cephfs]
	key = AQA1FPhfTzFdABAAthosDRYcEYly6qyLccLRUA==
	caps mds = "allow rw"
	caps mgr = "allow rwx"
	caps mon = "allow r"
	caps osd = "allow rwx pool=fs_metadata,allow rwx pool=fs_data"


[ceph@node1 ~]$ ceph  osd lspools
1 device_health_metrics
2 kubernetes
3 fs_metadata
4 fs_data

**Comment by Madhu-1** [comment]
@liyin37 required caps are documented here https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#cephfs

**Comment by liyin37** [comment]
thanks,when use kubernetes,the secret for cephfs need to use this configrations:
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
stringData:
  userID: cephfs
  userKey: AQBK7VZg/RP8BhAA+O1eSZlLRBzMjc5h9Q2BuA==
  adminID: cephfs
  adminKey: AQBK7VZg/RP8BhAA+O1eSZlLRBzMjc5h9Q2BuA==
