### ISSUE TITLE
csi-rbdplugin-controller requires watch permissions on secret objects

### ISSUE THREAD

**Issue by mattb18** [ceph/ceph-csi#1841]
# Describe the bug #

csi-rbdplugin-controller appears to require watch permissions on secret objects (I think this is due to the go controller library caching the requets).

I've manually added the watch permission to the **ceph-csi-rbd-provisioner** role and it appears to resolve the issue.

I discovered this using the helm chart but the permissions also appear to be missing from the deploy manifests.

I'm assuming this in not intended and happy to open a PR if that's the case.

# Environment details #

- Image/version of Ceph CSI driver : 3.2.1
- Helm chart version : 3.2.1
- Kernel version :  5.4.0-59-generic
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : 
- Kubernetes cluster version : v1.20.1
- Ceph cluster version : 15.2.0 (dc6a0b5c3cbf6a5e1d6d4f20b5ad466d76b96247) octopus (rc)

# Steps to reproduce #

1. Deploy helm chart veraion 3.2.1 with default rbac enabled
2. Check csi-rbdplugin-controller logs and you should see the errors below

# Actual results #

csi-rbdplugin-controller unable to watch namespace secrets and error below is reported

# Expected behavior #

csi-rbdplugin-controller able to watch namespace secrets

# Logs #

```
 E0124 11:46:56.936589       1 reflector.go:383] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1.Secret: unknown (get secrets)
 E0124 11:46:59.170184       1 reflector.go:383] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1.Secret: unknown (get secrets)
 E0124 11:47:03.892560       1 reflector.go:383] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1.Secret: unknown (get secrets)
 E0124 11:47:12.187155       1 reflector.go:383] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1.Secret: unknown (get secrets)
 E0124 11:47:27.802351       1 reflector.go:383] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1.Secret: unknown (get secrets)
 E0124 11:48:02.662399       1 reflector.go:383] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1.Secret: unknown (get secrets)
 E0124 11:48:58.558142       1 reflector.go:383] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1.Secret: unknown (get secrets)
 E0124 11:49:37.493219       1 reflector.go:383] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1.Secret: unknown (get secrets)
 E0124 11:50:13.719144       1 reflector.go:383] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to watch *v1.Secret: unknown (get secrets)
```

**Comment by Madhu-1** [comment]
@mattb18 thanks for raising the issue. PR is welcome to fix the issue.
