### ISSUE TITLE
Logging is broken

### ISSUE THREAD

**Issue by gman0** [ceph/ceph-csi#187]
It seems that after the recent glog->klog changes, both cephfs and rbd plugins have stopped outputting anything but error log messages (i.e. `klog.Info`s are muted). Can someone please replicate and verify that this is really broken? I have a PR ready which seems to fix the issue but i want to make sure it's not just a problem in my setup - I haven't tested+ran the code for quite some time now so maybe I'm doing something wrong...

**Comment by rootfs** [comment]
cc @humblec

**Comment by gman0** [comment]
Closed via #188
