### ISSUE TITLE
e2e tests fail with "monclient(hunting): authenticate timed out after 300"

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1875]
# Describe the bug #

Occasionally e2e tests fail with messages similar to:
```
Feb 16 16:32:40.944: INFO: ExecWithOptions {Command:[/bin/sh -c rbd ls --format=json --pool=replicapool] Namespace:rook-ceph PodName:rook-ceph-tools-5949d6759-sc49f ContainerName:rook-ceph-tools Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true Quiet:false}
Feb 16 16:32:40.944: INFO: >>> kubeConfig: /root/.kube/config
Feb 16 16:37:46.299: INFO: stdErr occurred: 2021-02-16T16:37:41.815+0000 7f64d00cc500  0 monclient(hunting): authenticate timed out after 300

Feb 16 16:37:46.299: FAIL: failed to list rbd images with error failed to list images 2021-02-16T16:37:41.815+0000 7f64d00cc500  0 monclient(hunting): authenticate timed out after 300
```

It seems `kubectl` is used to call an `rbd` command, which then fails to authenticate to the Ceph cluster.

**Comment by nixpanic** [comment]
Happened at https://github.com/ceph/ceph-csi/pull/1869#issuecomment-780415172

**Comment by nixpanic** [comment]
An other occurrence at https://github.com/ceph/ceph-csi/pull/1873#issuecomment-780080222

**Comment by nixpanic** [comment]
And at https://github.com/ceph/ceph-csi/pull/1675#issuecomment-778749379

**Comment by nixpanic** [comment]
https://github.com/ceph/ceph-csi/pull/1013#issuecomment-780497604 as well

**Comment by Rakshith-R** [comment]
This can be closed since we are not seeing it occur anymore and it was probably due to `mon allowing insecure id` issue https://github.com/rook/rook/issues/7746
