### ISSUE TITLE
Add ‘subvolumegroup’ field in cephfs storageclass

### ISSUE THREAD

**Issue by hookak** [ceph/ceph-csi#1884]
CephFS has a directory structure like ’/{volume}/{SVG}/{SV}.
Currently, SVG is fixed as `csi` for all pvc. 
e.g., ‘/vol/csi/pvc-1’ , ‘vol/csi/pvc-2’.

I think adding a SVG field in storageclass is necessary.
So the parent directory in which the SV is created could be classified by storageclass.
This makes it easy for multiple MDSs to process metadata in SVG.

I wonder if these features are in the plan.
I'm willing to create a PR for this issue.

**Comment by Madhu-1** [comment]
This is already supported in configmap  https://github.com/ceph/ceph-csi/blob/0d9cb96db1c352e04a029d1ebb4a27eb0cf35a2e/examples/csi-config-map-sample.yaml#L37-L39

**Comment by hookak** [comment]
Thanks a lot! That's exactly what I want. 
Close issue.

**Comment by hookak** [comment]
Hi, again.
Changing the default SVG is possible by specifying SVG in the configmap. However, in that case, creating SVs in multiple SVGs is still can not be achieved. 

Currently, clusterID and cephFS can be specified in storageclass. Likewise, if a user can specify SVG in storageclass, a SV can be created in the cephfs path that the user wants.

What do you think of this approach? I think a feature to separate the cephfs path by different tenants or services is needed to support QoS.

**Comment by Madhu-1** [comment]
setting the SVG at storageclass is not possible as the storageclass parameters are not sent to the cephcsi In deleteVolume or deleteSnapshot operations. for that the SVG is moved to the configmap. if you want multiple SVG in single cluster you can create configmap like below

```yaml
[
      {
        "clusterID": "abcd", # this need to be specified in storageclass
        "monitors": [
          "10.20.30.40:6879",
        ],
        "cephFS": {
          "subvolumeGroup": "test"
        }
      },
       {
        "clusterID": "xyz", # this need to be specified in storageclass
        "monitors": [
          "10.20.30.40:6879",
        ],
        "cephFS": {
          "subvolumeGroup": "testing_123"
        }
      },
      {
        "clusterID": "klm", # this need to be specified in storageclass
        "monitors": [
          "10.20.30.40:6879",
        ],
        "cephFS": {
          "subvolumeGroup": "testing_svg"
        }
      }
    ]
```

**Comment by hookak** [comment]
You're right. I thought it a little tricky that pointing the same ceph cluster using a different clusterID in configmap. But I didn't know this detail before.
> setting the SVG at storageclass is not possible as the storageclass parameters are not sent to the cephcsi In deleteVolume or deleteSnapshot operations.

Thanks a lot for your comment. I'm gonna update docs for others.

**Comment by Madhu-1** [comment]
closing this one, as its already covered in configmap.

**Comment by jpsn123** [comment]
> Thanks a lot for your comment. I'm gonna update docs for others.
@hookak
please quick ^_^
