### ISSUE TITLE
Change cephfs mount options for existing volume

### ISSUE THREAD

**Issue by mlaguilharre** [ceph/ceph-csi#1887]
**# Describe the feature you'd like to have #**
- Ability to override the cephfs mount option in the configMap.

**# What is the value to the end user? (why is it a priority?) #**
- During tuning process, we need to change mount option for existing PV, however this is set during provisioning and can't be changed afterward without copying the existing data to new provisionned volume.

Ex: We want to add cephfs mount option noacl,noatime, nodiratime.

**# How will we know we have a good solution? (acceptance criteria) #**
- Keep the ability to add cephfs mount options in the Storage Class for new provisioned volume.
- Possibility to override mount options for existing volume in Config Map.

**Comment by humblec** [comment]
@mlaguilharre ideally the mount options are kind of admin property so the choices are available in storage class . https://github.com/ceph/ceph-csi/blob/master/examples/cephfs/storageclass.yaml#L52 . Are you pointing it out this is not enough ?

**Comment by mlaguilharre** [comment]
@humblec Yes we like to modify mount options after volume provisioning, as far I know, Storage Class is used only during provisioning process, therefor it is not enforced for already existing volume. Ideally we could override the cephfs mount options in the configmap.

**Comment by nixpanic** [comment]
@mlaguilharre, have you tried to modify the mount options in the PV object?

**Comment by mlaguilharre** [comment]
@nixpanic Yes, it is not possible, it is immutable.
 kubectll patch pv pvc-471411d0-4da3-4ee2-9ee5-b9b144839655 -p '{"spec":{"csi":{"volumeAttributes":{"kernelMountOptions": "noatime,nodiratime,noacl"}}}}'
The PersistentVolume "pvc-471411d0-4da3-4ee2-9ee5-b9b144839655" is invalid: spec.persistentvolumesource: Forbidden: is immutable after creation.

**Comment by sgissi** [comment]
Just a note: CephFS doesn't handle atime ([or even relatime](https://tracker.ceph.com/issues/43337))

**Comment by nixpanic** [comment]
It seems CSI does not expose the `mountOptions` into the Kuberenetes PersistentVolume object. Ceph-CSI works around this by putting them in the (immutable) PersistentVolumeSource `volumeAttributes`.

The clean way of editing mount-options would be to have CSI expose the `mount_flags` from the `VolumeCapability` response (see [CSI spec](https://github.com/container-storage-interface/spec/blob/master/spec.md)) in the PersistentVolume `mountOptions` (see [Mount Options](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options)).

This needs to be an enhancement to [Kubernetes CSI](https://github.com/kubernetes/kubernetes/tree/master/pkg/volume/csi), and not Ceph-CSI (unless our plugin always uses the mount options from the `volumeAttributes`).

**Comment by humblec** [comment]
> Just a note: CephFS doesn't handle atime ([or even relatime](https://tracker.ceph.com/issues/43337))

@sgissi even after placing it in SC ?

**Comment by humblec** [comment]
@mlaguilharre The CSI driver fetching  the config map and adjust according to that for each node stage/publish request looks tedious to me. As mentioned above, ideally this would be handled by the core CSI. afacir, the main reason for placing the mount options in SC was making it admin thing than a user for better security.

**Comment by sgissi** [comment]
> > Just a note: CephFS doesn't handle atime ([or even relatime](https://tracker.ceph.com/issues/43337))

> @sgissi even after placing it in SC ?

It is not a Ceph CSI limitation, the flag isn't supported by CephFS itself. The inability to change mount options is a valid issue, I'm just pointing out that flags related to "noatime" (noatime, realtime, nodiratime) have no effect on CephFS.

**Comment by humblec** [comment]
>It is not a Ceph CSI limitation, the flag isn't supported by CephFS itself. The inability to change mount options is a valid issue, I'm just pointing out that flags related to "noatime" (noatime, realtime, nodiratime) have no effect on CephFS.
>

@sgissi if you think there is an issue at CephFS side, please feel free to open an issue here https://tracker.ceph.com/issues

**Comment by sgissi** [comment]
@humblec Not a problem for me and in any case there is an issue open for relatime that I linked in my previous comment. I just wanted to make sure @mlaguilharre is aware as he mentioned these flags.

To add 2c into the actual issue: it makes sense to be an issue against CSI itself, not Ceph CSI.

**Comment by mlaguilharre** [comment]
Understood, I may open a issue with CSI. We are evaluating it. Thanks for the help.

**Comment by Madhu-1** [comment]
@mlaguilharre as all of your questions are answered and nothing much can be done at cephcsi level am closing this one. Please feel free to reopen if you need help on this one,
