### ISSUE TITLE
Question: can we remove gocyclo from the CI?

### ISSUE THREAD

**Issue by gman0** [ceph/ceph-csi#189]
**Is your feature request related to a problem? Please describe.**
IMHO the gocyclo tool (measures the cyclomatic complexity of a function) in this repo's CI is too strict. I _do_ like functions short and lean, but there are cases where longer functions are justifiable and sometimes are more readable than if they were artificially split into more smaller functions.

From [fzipp/gocyclo](https://github.com/fzipp/gocyclo/blob/master/README.md):
>  1 is the base complexity of a function
> +1 for each 'if', 'for', 'case', '&&' or '||'

Given how tedious Go's error handling is, and the amount of if-statements it requires, I don't think it's fair to constrain developers as much as current CI settings do, because much of this "complexity" here is just boilerplate code for logging an error and returning. For a comparison, languages that support other means of handling erroneous state (like exceptions) would, in this case, get a free pass simply for not using `if err != nil` as their error handling mechanism.

IMHO, the way the gocyclo tool defines complexity is too general, and doesn't provide very reliable metric for gauging actual complexity. The CI shouldn't refuse people's PRs just because of a couple of conditional log messages.

**Describe the solution you'd like**
Remove gocyclo from the CI altogether and let the reviewers decide if any given function needs to be split up.

**Describe alternatives you've considered**
Set the limit for cyclomatic complexity higher (now, complexity of 10 or above triggers a CI failure)

Thoughts? @rootfs @Madhu-1

**Comment by Madhu-1** [comment]
@gman0  if we increase the complexity to 10+ maybe we will hit the issue one or other day.
 am fine with removing the gocyclo from the CI.

am not sure that we can provide the unit test code coverage more than 70 to 80 % if we remove gocyclo as it increases the number of if-else statements in a single function.

**Comment by rootfs** [comment]
@gman0 if necessary, you can skip lint by adding `// nolint: gocyclo`

**Comment by gman0** [comment]
@rootfs ah, that seems sensible. Closing.
