### ISSUE TITLE
Get rbd snap image name from VolumeSnapshotContent

### ISSUE THREAD

**Issue by tareqhs** [ceph/ceph-csi#1892]
# Describe the feature you'd like to have #

The ability to identify which rbd child image (`csi-snap-...`) backs a `VolumeSnapshotContent` resource.

# What is the value to the end user? (why is it a priority?) #

Various custom operations on the RBDs directly, e.g. exporting, sparsifying, ad-hoc stuff ...

# How will we know we have a good solution? (acceptance criteria) #

A field in csi parameters of `VolumeSnapshotConrent` with the name of the rbd child image that backs the the snapshot resource.

# Additional context #

I am developing a small job that does several low level operations on the rbds directly. Identifying the RBD of a `PersistentVolume` provisioned by ceph-csi is straight forward because it is exposed via the csi parameter `imageName`. No such field exists in `VolumeSnapshotContent`, which forces me to handle the child images collectively without knowing how they map to the kubernetes reources.

**Comment by Madhu-1** [comment]
@tareqhs Thanks for opening the issue. the context on the volumesnapshotContent is set by the external-snapshotter, not by the cephcsi driver. can you please open an issue in https://github.com/kubernetes-csi/external-snapshotter/issues to have this feature?

**Comment by Madhu-1** [comment]
https://github.com/kubernetes-csi/external-snapshotter/issues/379 is the one already opened in external-snapshotter.

**Comment by tareksha** [comment]
Hi @Madhu-1 thanks for info. Seems like the issue goes all the way down to the CSI spec. Is there any workaround that I can do in order to get image names?

**Comment by Madhu-1** [comment]
you can decode the SnapshotHandle. `csi-snap-` and the last part of the SnapshotHandle is your rbd image name.

**Comment by tareksha** [comment]
@Madhu-1 thank you!

**Comment by Madhu-1** [comment]
closing this as not an issue. please free to join cephcsi slack or reopen this if you need more help.

**Comment by tareksha** [comment]
@Madhu-1 checked this ..  `volumeHandle` in `VolumeSnapshotContent` contains the GUID of the `csi-vol-` image, exactly the same as `volumeHandle` in `PersistentVolume`. Can't find the GUID of `csi-snap-...`. Is this intentional?

**Comment by Madhu-1** [comment]
@tareqhs yes it intentional it's the same as the snapshothandle which is an encoded one.

for pvc it starts with `csi-vol` for snapshot it starts with `csi-snap` unless you use a custom prefix in storageclass or snapshotclass
