### ISSUE TITLE
Requirement of adding Volume ID to the CSI PV spec

### ISSUE THREAD

**Issue by anmolsachan** [ceph/ceph-csi#1894]
# Describe the feature you'd like to have #

CSI PVs should have another spec that exposes the actual RBD (imageName) or CephFS (subvolumeName) volume name.

The actual requirement is to expose ceph storage (rbd/cephFS) volumeID via the Kube-state-metrics like other Kubernetes storage drivers : https://github.com/kubernetes/kube-state-metrics/blame/ef393104fe8cc3aa7903b443217725e02fbf2622/internal/store/persistentvolume.go#L147

Currently, the Ceph CSI exposes the required info in the form of spec `csi.volume attributes.imageName/subvolumeName` . These volumeAttribute are not common to all Kubernetes CSI storage drivers thus cannot be referenced generically in Kubernetes code like other Kubernetes Drivers. Thus, there is a requirement of a generic spec common to all CSI drivers which can expose the storage volumeID attached to a PV.

The reason spec volumeHandle cannot be used is because it does not represent the exact volumeID. Prometheus cannot do runtime manipulation of label values to convert the volumeHandle to volumeID, 

# What is the value to the end user? (why is it a priority?) #

This will help the customers and developers to establish a relationship between PV and actual storage volumes in the form of Kubernetes Prometheus metrics; which will further help in exposing the RBD/cephFS metrics on a Kubernetes PV level, which is currently limited to a lower level ceph metrics.

# How will we know we have a good solution? (acceptance criteria) #

The solution should be able to help in exposing the volumeID for ceph volumes as a spec, which is applicable to other non-ceph Kubernetes CSI drivers. 

# Additional context #

**Comment by humblec** [comment]
@anmolsachan the referenced PV volume handle mapping from Kube is for the `intree` drivers. The CSI spec capability of exposing such attributes are via Volume Attributes in CSI PV struct and we expose that information via `csi.volume attributes.imageName`. Is this a request to enhance CSI spec itself or do you think we miss something in Ceph CSI driver compared to general or other CSI drivers? may be I missed some context here on the requirement so asking for the confirmation.

**Comment by anmolsachan** [comment]
> @anmolsachan the referenced PV volume handle mapping from Kube tree for the intree drivers. The CSI spec capability of exposing such attributes are via Volume Attributes in CSI PV struct and we expose that information via `csi.volume attributes.imageName/`. Is this a request to enhance CSI spec itself or do you think we miss something in Ceph CSI driver compared to general or other CSI drivers? may be I missed some context here on the requirement so asking for the confirmation.

@humblec This is a requirement to enhance Kubernetes PV CSI spec and then the same shall be implemented in csph-csi.

Just like 

```
spec.GCEPersistentDisk.PDName
spec.AWSElasticBlockStore.VolumeID

```
CSI should have

`spec.csi.VolumeID`

**Comment by Madhu-1** [comment]
> > @anmolsachan the referenced PV volume handle mapping from Kube tree for the intree drivers. The CSI spec capability of exposing such attributes are via Volume Attributes in CSI PV struct and we expose that information via `csi.volume attributes.imageName/`. Is this a request to enhance CSI spec itself or do you think we miss something in Ceph CSI driver compared to general or other CSI drivers? may be I missed some context here on the requirement so asking for the confirmation.
> 
> @humblec This is a requirement to enhance Kubernetes PV CSI spec and then the same shall be implemented in csph-csi.
> 
> Just like
> 
> ```
> spec.GCEPersistentDisk.PDName
> spec.AWSElasticBlockStore.VolumeID
> ```
> 
> CSI should have
> 
> `spec.csi.VolumeID`

VolumeHandle in the PV spec is the volumeID generated by the CSI driver.   It's an encoded ID that is required by cephcsi to identify the underlying rbd image in different ceph clusters (as cephcsi supports multiple ceph clusters)

**Comment by anmolsachan** [comment]
> VolumeHandle in the PV spec is the volumeID generated by the CSI driver. It's an encoded ID that is required by cephcsi to identify the underlying rbd image in different ceph clusters (as cephcsi supports multiple ceph clusters)

@Madhu-1  Exactly, But, 

The rbd metrics expose the ID/Name of the metrics like

Image: `csi-vol-18624d24-7656-11eb-ac83-0a580a810213`
But CSI volumeHandle: >-
      `0001-0011-openshift-storage-0000000000000001-18624d24-7656-11eb-ac83-0a580a810213. `
      
Prometheus on run-time cannot convert VolumeHandle to Image ID. That is why we need another spec that exposes the exact volume ID and then that can be exposed via Kube-state-metrics, So that we can establish the relationship between PV and RBD
      
![Screenshot from 2021-02-25 14-30-15](https://user-images.githubusercontent.com/8753636/109510262-ce1cb300-7ac7-11eb-97b1-9758c7fe51dd.png)

**Comment by Madhu-1** [comment]
The VolumeHandle will be the one to identify the backend storage. The volumeHandle `0001-0011-openshift-storage-0000000000000001-18624d24-7656-11eb-ac83-0a580a810213 ` is cephcsi specific because we generate a new volumeID which is required for cephcsi to identify the pool, cluster, rbd image/subvolume, etc. IMO this cannot be a CSI spec/kubernetes change because maybe for many storage providers the VolumeHandle might be the same as the volume ID created for volume in their backend.

**Comment by dillaman** [comment]
Seems to be semi-related to the goals of #925

**Comment by Madhu-1** [comment]
@anmolsachan as @dillaman mentioned this will be covered as a part of #925. am closing this one. Please reach out to us if you need more help.
