### ISSUE TITLE
create ceph-csi channel on slack

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#190]
@rootfs can we create ceph-csi channel slack channel for development communication?

**Comment by rootfs** [comment]
@Madhu-1 how about creating a csi channel under rook? 
also cc @travisn

**Comment by briantopping** [comment]
Hi, thanks for a great product! `README.md` still refers to cephcsi.slack.com. Is the rook csi channel the correct one?

**Comment by Madhu-1** [comment]
@briantopping we are active on both slack channels. but later on, we will be moving to `cephcsi.slack.com`

**Comment by briantopping** [comment]
Ah great, thanks @Madhu-1! Don't forget to provide some means of getting an invitation to the latter!! :D
