### ISSUE TITLE
Address already in use for prometheus-liveness container (tcp/8081) of ceph-csi-cephfs

### ISSUE THREAD

**Issue by evgkrsk** [ceph/ceph-csi#1902]
# Describe the bug #

We have constantly crashed nodeplugin pods (prometheus-liveness containers) with mostly default values.yml

# Environment details #

- Image/version of Ceph CSI driver : see chart versions below
- Helm chart version : versions 2.1.2 AND 3.2.1 of ceph-csi-cephfs chart
- Kernel version : 4.20.13
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : chart defaults
- Kubernetes cluster version : v1.18.3
- Ceph cluster version : latest octopus

# Steps to reproduce #

1. Setup k8s cluster
2. Setup ceph cluster
3. Install ceph-csi-cephfs chart (with minimal values.yaml: csiConfig)

# Actual results #

Constanly crashing nodeplugin pods (container prometheus-liveness didnt start)

# Expected behavior #

Smooth startup of all 3/3 containers of nodeplugin pods

# Logs #

```
F0303 05:54:35.757098       1 httpserver.go:24] failed to listen on address 10.40.0.130:8081: listen tcp 10.40.0.130:8081: bind: address already in use
```

# Workaround #

```
nodeplugin:
  httpMetrics:
    containerPort: 8082
```

in values.yaml

**Comment by Madhu-1** [comment]
@evgkrsk you need to check if anyone is already using the 8081 port on the host machine. if yes you need to change the value of the port when you are deploying with a helm chart

**Comment by evgkrsk** [comment]
Yep, sorry, false alarm.

Port 8081 is used by other program on host machine, missed out...
