### ISSUE TITLE
feature: support mesos slrp csi implementation

### ISSUE THREAD

**Issue by f1-outsourcing** [ceph/ceph-csi#1909]
# Describe the feature you'd like to have #
Adding support for mesos slrp csi implementation
http://mesos.apache.org/documentation/latest/csi/

requires ListVolumes and GetCapacity

**Comment by nixpanic** [comment]
Would you be willing to assist with writing and maintaining test scripts for Mesos support?

The CI jobs we have are in the [ci/centos branch](https://github.com/ceph/ceph-csi/tree/ci/centos). The main script that is used for k8s is [single-node-k8s.sh](https://github.com/ceph/ceph-csi/blob/ci/centos/single-node-k8s.sh), and we would need a similar one for Mesos. After that, we also need to deploy a Ceph cluster (we use Rook for k8s) and Ceph-CSI in the different `mini-e2e*.groovy` files.

This will be quite a time consuming task, as starting tests, see deployment fail, fix and retry usually needs more iterations than one hopes. The current contributors all work with Kubernetes, and we do not have sufficient Mesos experience or time to pick this up. Of course we'll be available for answering questions and providing guidance.

**Comment by f1-outsourcing** [comment]
I would not mind giving this a try. However is it not that csi was created to arrange independence of the CO platform. So is it maybe better to create tests that are not related to any platform.

I assume that kubernetes at some point will also evolve to require the mentioned capabilities. Those are required for scaling tasks I guess.

I have been asking on the mesos mailing list about interest in csi ceph support, but most mesos depolyments seem to be using still the (old/buggy) docker volume interface to mount external volumes. There is also some discussion about future support. Regardless of mesos, I think sooner or later such ListVolumes and GetCapacity services are necessary and even maybe required to be compatible with a csi spec version.
