### ISSUE TITLE
Add Mudit as new Maintainer of cephcsi

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1920]
Am suggesting adding Mudit to the list of Maintainers to cephcsi. Below is the list of contributions from Mudit

List of contribution

* Add E2E for CephFS static PVC
* Add Documentation of CephFS static PVC
* Impore logging if mount fails
* Enhance tracevol.py to work for CephFS PVC
* Add support for namespace in trace.py
* Update volume resize using go-ceph
* Update e2e README for snapshot operation
* Use staging path for resize when available 
* Implement rbd.updateVolWithImageInfo() with go-ceph
* Replace cli with go-ceph for snapshot namespace
* Update sidecars to latest releases
* Replace go-ceph GetParentInfo() with GetParent()
* Upgrade documentation
* Ignore BytesQuota field in case it is not set
* Add support to specify custom ceph image in rook.sh
* Add E2E for snapshot retention case

Mudit already helped with PR reviews/issue triage etc.

cc @nixpanic @ShyamsundarR @agarwal-mudit @humblec

**Comment by nixpanic** [comment]
:+1: happy to support Mudits promoting :partying_face:

**Comment by Madhu-1** [comment]
will provide write access to Mudit by EOD if I don't see any objections.

**Comment by humblec** [comment]
@nixpanic  @Madhu-1 I would also propose to add @Yuggupta27 too into this  list, Looking at the contributions from his side https://github.com/ceph/ceph-csi/commits?author=Yuggupta27 its a measurable one!

**Comment by Madhu-1** [comment]
@humblec as the PR suggests this is for Mudit can you please open a separate issue with a list of PRs and other helpful information.

**Comment by humblec** [comment]
> @humblec as the PR suggests this is for Mudit can you please open a separate issue with a list of PRs and other helpful information.

yeah, let me open one for Yug too..  :+1:

**Comment by humblec** [comment]
Ack on this proposal for @agarwal-mudit :+1:

**Comment by humblec** [comment]
> > @humblec as the PR suggests this is for Mudit can you please open a separate issue with a list of PRs and other helpful information.
> 
> yeah, let me open one for Yug too.. +1

here it is https://github.com/ceph/ceph-csi/issues/1922

**Comment by Madhu-1** [comment]
Provided write access. closing this one.
