### ISSUE TITLE
cephfs: run with fuse_big_writes by default

### ISSUE THREAD

**Issue by gman0** [ceph/ceph-csi#1928]
# Describe the feature you'd like to have #

ceph-fuse in ceph-csi image v3.2.1 is linked against libfuse2:

```
$ kubectl exec -it ceph-csi-cephfs-nodeplugin-nv8c9 -c csi-cephfsplugin -- ceph-fuse --version
ceph version 15.2.8 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable)
```
```
$ kubectl exec ceph-csi-cephfs-nodeplugin-nv8c9 -c csi-cephfsplugin -- dnf repoquery --requires --resolve ceph-fuse.x86_64
Last metadata expiration check: 0:02:19 ago on Wed Mar 17 15:36:58 2021.
fmt-0:6.2.1-1.el8.x86_64
fuse-0:2.9.7-12.el8.x86_64
fuse-libs-0:2.9.7-12.el8.x86_64
```

By default, the write buffer size in libfuse2 is 2KiB for reasons described here:

https://github.com/libfuse/libfuse/blob/d44bf3a4ac1ce1b56672ac9ae4a5caa3a8ee6844/ChangeLog#L653-L659

`-o big_writes` mount option is used to override this limit. libfuse3 removes `big_writes`, making it enabled by default: https://github.com/libfuse/libfuse/blob/master/ChangeLog.rst#libfuse-300-2016-12-08 , so this change will be incorporated automatically by ceph-fuse as well, see https://github.com/ceph/ceph/pull/34531 , Octopus backport https://github.com/ceph/ceph/pull/34769 .

I propose that until we get ceph-fuse with libfuse3 in the image, `fuse_big_writes` option should be added to ceph.conf

# What is the value to the end user? (why is it a priority?) #

Without enabling this option, the write performance is very poor: https://tracker.ceph.com/issues/44885

Granted, users could add this option into their `mountOptions` or `fuseMountOptions` parameters, but are there reasons to not have it on by default?

# How will we know we have a good solution? (acceptance criteria) #

Test write performance with and without having `big_writes` enabled while still using libfuse2.

# Additional context #

None.

**Comment by nixpanic** [comment]
By default the Linux kernels `cephfs` module is used, not `ceph-fuse`. I should be relatively simple to add the option by default for users that deploy with `ceph-fuse`.
