### ISSUE TITLE
Image builds are not reproducible

### ISSUE THREAD

**Issue by gman0** [ceph/ceph-csi#1943]
# Describe the bug #

ceph/ceph-csi container images are based on ceph/ceph. This is defined in ENV file in https://github.com/ceph/ceph-csi/blob/v3.2.1/build.env#L16 .

The image tag for ceph/ceph is using the floating version "v15" that changes over time as new point releases are added. This results in unreproducible ceph-csi builds.

# Steps to reproduce #

1. Checkout a release tag, e.g. ceph-csi v3.2.1.
2. Observe that `build.env` includes line `BASE_IMAGE=docker.io/ceph/ceph:v15` -- tag used here is not pinned to any specific image version, just the general Ceph Octopus release.
3. Build a ceph-csi container image.
4. Compare the versions of Ceph tools/libraries of the freshly built v3.2.1 image and the official v3.2.1 release image.

# Actual results #

The official v3.2.1 image was built on an earlier date, so it contains older versions of Ceph tools/libs.

# Expected behavior #

When I build v3.2.1 image I expect it to match the official v3.2.1 image.

**Comment by nixpanic** [comment]
Could you explain why this is a problem? Any container image that builds on top of other layers might be different when building at a later time. There is no guarantee that the lower layers do not change. It is not practical to have a fixed version, as most users will want to get the latest version of the lower layered container image.

If you want reproducible behaviour, you can pass `BASE_IMAGE=...` to `make image-cephcsi` and point to a different version. Is that not sufficient for you?

**Comment by gman0** [comment]
This may become a problem when debugging some issue that didn't arise in an "older v3.2.1", but the "newer v3.2.1" suddenly stops working / behaves differently because of e.g. update in the cephfs client toolset. All because the image was rebuilt. Sure I could pass in `BASE_IMAGE`, but then I'd need to keep track of what tag was the original image built with in the first place.

The latest base layer probably makes sense in master/devel branches, but in release branches something more conservative might be more apt. As an example I can add that even the sidecar containers in deployment manifests / Helm charts are pinned to a specific tag, and not the latest "canary". By the same token, IMO the base layer should have a fixed version (at least in release branches) too.

**Comment by rochaporto** [comment]
This is still an issue in our builds, i think it's worth reopening.
