### ISSUE TITLE
Operator for easy install of CSI plugin

### ISSUE THREAD

**Issue by rollandf** [ceph/ceph-csi#195]
**Is your feature request related to a problem? Please describe.**
The user needs an easy way to install the CEPH-CSI plugin in a cluster.

**Describe the solution you'd like**
An operator that will install the needed pods.

**Comment by rootfs** [comment]
That would be a nice addition. Currently we have a helm chart for rbd driver (no cephfs yet). Rook will orchestrate the driver deployment soon.

**Comment by mykaul** [comment]
@rollandf  - is https://github.com/rook/rook/pull/2580 good enough?

**Comment by humblec** [comment]
@rollandf the initial work is done with the Rook PR# 2580, however some more followup PRs are in flight. For ex: :https://github.com/rook/rook/issues/2649

**Comment by rollandf** [comment]
If Rook is supporting this, I am OK to close this issue.

**Comment by Madhu-1** [comment]
@rollandf if you want to try this out this will help https://github.com/rook/rook/blob/master/Documentation/ceph-csi-drivers.md
