### ISSUE TITLE
Validate e2e testing on Kubernetes 1.21

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1963]
# Describe the feature you'd like to have #

Kubernetes 1.21 is currently in Beta and we should start testing with this version too.

Admins in the Jenkins environment can manually start the mini-e2e jobs with a given Kubernetes version, doing some pre-check runs.

Once Kubernetes 1.21 has been released, the version should be added as a regular job. The `.mergify.yml` should then also require the tests before merging.

Jobs are available for testing:

* https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.21/activity/
* https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.21/activity/

**Comment by nixpanic** [comment]
#1962 has not been complete, the `scripts/skip-doc-change.sh` script does not detect non-doc changes if there is no PR associated with the CI job run. It will be needed to skip the check when `git_since` is the same as the checked out branch.

**Comment by nixpanic** [comment]
https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.20/detail/mini-e2e_k8s-1.20/639/pipeline is a new manual run with Kubernetes 1.21.

**Comment by nixpanic** [comment]
> https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.20/detail/mini-e2e_k8s-1.20/639/pipeline is a new manual run with Kubernetes 1.21.

This failed with some minikube errors during cluster creation. Maybe the new Kubernetes version needs more resources?

**Comment by nixpanic** [comment]
https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/k8s-e2e-external-storage/detail/k8s-e2e-external-storage/9/pipeline is an other test, running the k8s-e2e-external-storage job with Kubernetes 1.21.

**Comment by nixpanic** [comment]
[mini-e2e-helm_k8s-1.21/1](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.21/detail/mini-e2e-helm_k8s-1.21/1/pipeline) failed in **STEP: create a PVC and bind it to an app with encrypted RBD volume with VaultKMS**:

```
Apr 20 09:25:10.256: INFO: At 2021-04-20 09:15:13 +0100 BST - event for rbd-pvc: {rbd.csi.ceph.com_csi-rbdplugin-provisioner-5b864cb457-sr68z_1d36d602-da81-4913-812e-e6ad6b29e6b2 } ProvisioningFailed: failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = InvalidArgument desc = invalid encryption kms configuration: failed creating new Vault Secrets: Error making API request.

URL: PUT http://vault.cephcsi-e2e-ef7bdef00777.svc.cluster.local:8200/v1/auth/kubernetes/login
Code: 500. Errors:

* claim "iss" is invalid
```

**Comment by Rakshith-R** [comment]
k8s 1.21 e2e runs fails at `STEP: create a PVC and bind it to an app with encrypted RBD volume with VaultKMS` .
e2e run at https://github.com/ceph/ceph-csi/pull/1974#issuecomment-826503590 
logs: https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/rest/organizations/jenkins/pipelines/mini-e2e_k8s-1.21/runs/3/nodes/87/steps/90/log/?start=0
```bash
I0426 05:52:54.094777       1 connection.go:186] GRPC error: rpc error: code = InvalidArgument 
desc = invalid encryption kms configuration: failed creating new Vault Secrets: Error making API request.

URL: PUT http://vault.cephcsi-e2e-896c716a.svc.cluster.local:8200/v1/auth/kubernetes/login
Code: 500. Errors:

* claim "iss" is invalid
```

**Comment by nixpanic** [comment]
I have now updated the `vault:latest` container image in the registry that the CI uses. Maybe that adds support for Kubernetes 1.21?

**Comment by Madhu-1** [comment]
can we manually test it out and check what is changed?

**Comment by Rakshith-R** [comment]
Adding vault pod logs obtained during manual testing here , I'll run it again adding `VAULT_ADDR`
```bash
==> Vault server configuration:

             Api Address: http://0.0.0.0:8200
                     Cgo: disabled
         Cluster Address: https://0.0.0.0:8201
              Go Version: go1.15.11
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
           Recovery Mode: false
                 Storage: inmem
                 Version: Vault v1.7.1
             Version Sha: 917142287996a005cb1ed9d96d00d06a0590e44e

==> Vault server started! Log data will stream in below:

2021-04-28T06:21:29.199Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
2021-04-28T06:21:29.199Z [WARN]  no `api_addr` value specified in config or in VAULT_API_ADDR; falling back to detection if possible, but this value should be manually set
...

You may need to set the following environment variable:

    $ export VAULT_ADDR='http://0.0.0.0:8200'

The unseal key and root token are displayed below in case you want to
seal/unseal the Vault or re-authenticate.

Unseal Key: JluvyeFsSwnnptnwiOwMrssY1+CQj78hY5dg/OO/y9k=
Root Token: sample_root_token_id

Development mode should NOT be used in production installations!

2021-04-28T06:21:39.501Z [INFO]  core: enabled credential backend: path=kubernetes/ type=kubernetes
```

**Update: This is the exact same logs for k8s 1.20 also, so does not seem to be the cause of failures.**

**Comment by Rakshith-R** [comment]
e2e testing K8s 1.21 is failing only on test cases involving vault.
Tried 
- updating github.com/hashicorp/vault/api => same error.
- updating github/libopenstorage/secrets => did not fix it.
- updating both results in version mismatch in another package that both of them import indirectly.
- psp is deprecated in k8s 1.21 => tried with additional rbac rules for configmaps and secrets, did not work in my local testing, ended up with same error.

@nixpanic I'll leave it to you to figure it out :sweat_smile:
