### ISSUE TITLE
cephfs: how to control different ceph users can only access certain directories?

### ISSUE THREAD

**Issue by chenxianpao** [ceph/ceph-csi#1967]
# Describe the feature you'd like to have #
I found that the dynamically created volume uses the admin credentials(create or mount). If so, how to control different ceph users can only access certain directories? Can we only perform access management on pre-created volumes?

Thank you for your help.

**Comment by nixpanic** [comment]
You could create static PVs and refer to a Secret that contains the particular Ceph user/key. See https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md#cephfs-static-pvc for examples. Different PVs can have different Secrets (in different Namespaces if you like).
