### ISSUE TITLE
update kubernetes dependency to 1.21.0

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1968]
as kubernetes 1.21.0 is released https://github.com/kubernetes/kubernetes/releases/tag/v1.21.0 we need to update the below items in our codebase

* Update go.mod
* Use kube 1.20 and 1.21 for E2E testing in centos CI
* Update mergify rules for the same.

**Comment by nixpanic** [comment]
See also #1963

**Comment by humblec** [comment]
@Madhu-1 @nixpanic `devel` branch update can be done. Just have to confirm do we need to pull this change in `release-3.3` minor versions or we will keep this as next major release item ?

**Comment by Madhu-1** [comment]
To avoid  backport issue I think we can backport it to 3.3 itself.

**Comment by nixpanic** [comment]
What is the reason we need to backport this to `release-3.3`? If there are bugfixes from Kubernetes we need to include, we should just vendor in a minor v1.20.x update of the Kubernetes packages.

I would see this as a change for Ceph-CSI v3.4.

**Comment by humblec** [comment]
> What is the reason we need to backport this to `release-3.3`? If there are bugfixes from Kubernetes we need to include, we should just vendor in a minor v1.20.x update of the Kubernetes packages.
> 
> I would see this as a change for Ceph-CSI v3.4.

Agreed.. yeah, in general,  the must required PRs in kube are backported to 1.20 branch , so we should be good even if we keep v3.3 branch in parity with `1.20` kube major version . 

@Madhu-1 I believe its good to have parity with ceph csi major version to kube major version.
