### ISSUE TITLE
e2e tests in CI fail with: snapshotter controller creation failed

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#1971]
# Describe the bug #

On occasion e2e testing fails with
```
snapshotter controller creation failed
```

The deployment is then aborted, before the actual e2e testing is started.

**Comment by nixpanic** [comment]
From #1918 :
- https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.20/detail/mini-e2e_k8s-1.20/641/pipeline/
- https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/upgrade-tests-cephfs/detail/upgrade-tests-cephfs/1302/pipeline/

**Comment by humblec** [comment]
@nixpanic I havent seen this issue in recent runs especially at release time. Do we need to keep this open ?
