### ISSUE TITLE
Release 3.4.0 ( Planning Doc)

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#1986]
# Describe the feature you'd like to have #

The idea here is to capture the `wishlist` from  Ceph CSI community which they would like to see in this release. We could capture this in a google doc or in form of comments on the issue. However the format should not be a blocker for capturing this info, thus tracking it for the next release. 

[update] Wish list:

https://hackmd.io/8OqCr1mrTMGtBcJ7XNdDBg?view

Additionally having a `planning call` for an upcoming release would help the users to discuss about the use case and priority for a feature.

# What is the value to the end user? (why is it a priority?) #

User get a chance to come up with their own `wishlist` for the upcoming release. It will also help the CSI community to do some planning based on the priority, owning the features , driving to the release ..etc. 

We could also rotate the responsibilities among the community for various release tasks.

**Comment by Madhu-1** [comment]
@humblec this should be 3.4.0?

**Comment by Madhu-1** [comment]
Renamed as 3.4.0 hope that should be fine.

**Comment by Madhu-1** [comment]
all required issues/PR's are added to 3.4.0 milestone https://github.com/ceph/ceph-csi/milestone/9

**Comment by Madhu-1** [comment]
closing this one as 3.4.0 release is done
