### ISSUE TITLE
Remove PSP from kubernetes templates

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1988]
PSP is deprecated in kubernetes 1.21 and will be removed in kubernetes 1.25 https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/ . as it's deprecated, we need to take into consideration when to remove the PSP templates from the cephcsi repo.

**Comment by humblec** [comment]
@Madhu-1 considering 1.21 will be the base for release 3.4, this could be targetted for next major version. Also we have breathing time on deprecated stuff. @nixpanic wdyt?

**Comment by Madhu-1** [comment]
Still required as kubernetes 1.25 is next release
