### ISSUE TITLE
Bot authored backport PR's are not getting auto-merge in release branches

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#1994]
when a PR is backported by the mergify bot and it has one approval and CI is passing, Merigfy should auto-merge the PR. 

See not applicable rules at https://github.com/ceph/ceph-csi/pull/1993/checks?check_run_id=2382789769

**Comment by Rakshith-R** [comment]
All backported prs are authored by `author=mergify[bot]` not `author=ceph-csi-bot`.
https://github.com/ceph/ceph-csi/pulls?q=is%3Apr+is%3Aclosed+backport+author%3Aapp%2Fmergify
and I don't see mergify providing option for a bot to send backport pr https://docs.mergify.io/actions/backport/.

https://github.com/ceph/ceph-csi/blob/52290333e61bf5e659ab8ff22c412366b42db126/.mergify.yml#L91-L103

changing the condition  `author=ceph-csi-bot` back to  `author=mergify[bot]` done by https://github.com/ceph/ceph-csi/commit/1fcbbe0fa7680caa44bbfef2896726cb3fc8dbec should resolve the issue ?

**Comment by Madhu-1** [comment]
@Rakshith-R  yes we need to revert back to the author in the condition. @nixpanic  PTAL

**Comment by humblec** [comment]
> @Rakshith-R yes we need to revert back to the author in the condition. @nixpanic PTAL

Ideally its good to keep `ceph-csi-bot` as the name, iow, instead of reverting may be make `ceph-csi-bot` conditions correct is preferred.

**Comment by nixpanic** [comment]
It seems an update of Mergify broke this :disappointed:
They now ask for a monthly contribution to use the `ceph-csi-bot` for certain features. As this repository is part of the Ceph organization, and there are **many** users, the costs are quite high.
Ideally we can have both bot accounts on the same `author=` line, so that `ceph-csi-bot` can be used in the future again. If it is needed to duplicate the whole rule, a comment above the `authot=mergify[bot]` line about our preference to use ceph-csi-bot is sufficient too.

**Comment by humblec** [comment]
> It seems an update of Mergify broke this disappointed

Ah.. I see :(

> They now ask for a monthly contribution to use the `ceph-csi-bot` for certain features. As this repository is part of the Ceph organization, and there are **many** users, the costs are quite high.

We dont need any fancy features :) . btw, I remember some discussions on this in a thread with @leseb few months back. 

> Ideally we can have both bot accounts on the same `author=` line, so that `ceph-csi-bot` can be used in the future again. If it is needed to duplicate the whole rule, a comment above the `authot=mergify[bot]` line about our preference to use ceph-csi-bot is sufficient too.

That would be good :+1:
