### ISSUE TITLE
Register newly created RBD images with the iSCSI target (using [gwcli](https://docs.ceph.com/en/latest/rbd/iscsi-target-cli/)).

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2004]
The effort here is divided into below sub parts:

- [ ] Expose RBD images as ISCSI targets 
- [ ] Try mount/client access on these volumes 
- [ ]  Perform I/Os on these volumes and confirm data path works
- [ ] Try to find code flow for supporting this from RBD driver
- [ ] Register newly created RBD images with the ISCSI targets.

`gwcli` and other requirements are documented at the the [Configuring the iSCSI Target](https://docs.ceph.com/en/latest/rbd/iscsi-target-cli/) section.

**Comment by mykaul** [comment]
What's the use case?

**Comment by humblec** [comment]
> What's the use case?

The plan here is to experiment on possibilities of exposing RBD Volumes via ISCSI protocol which helps especially in `Windows clients ` where the access can be granted to RBD volumes from Ceph Cluster via ISCSI.
