### ISSUE TITLE
ceph-csi release v3.3.1

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2008]
This issue is a tracker for the v3.3.1 bugfix release which includes below bug fixes

#Bug Fixes

Build:

* Update ceph to `15.2.11` https://github.com/ceph/ceph-csi/issues/1995
* Fix helm chart push issue 

RBD
* Modified logic to check image watchers https://github.com/ceph/ceph-csi/pull/1993
* Return crypt error for the rpc return https://github.com/ceph/ceph-csi/pull/2005

**Comment by nixpanic** [comment]
Duplicate of #1986?

**Comment by nixpanic** [comment]
Also make sure to add PRs/Issues to the [release-3.3.1 milestone](https://github.com/ceph/ceph-csi/milestone/10).

**Comment by Madhu-1** [comment]
> Duplicate of #1986?

3.3.1 is a bug fix release.  as the #1986 covers more items let's make it a 3.4.0 release

**Comment by Madhu-1** [comment]
As the release is available closing this one https://github.com/ceph/ceph-csi/releases/tag/v3.3.1
