### ISSUE TITLE
Cleaning up resources

### ISSUE THREAD

**Issue by gman0** [ceph/ceph-csi#202]
**Is your feature request related to a problem? Please describe.**
Cleaning up resources is showing to be a prevalent issue in regards to how we handle deletion idempotency.

The CSI spec states:
[`DeleteVolume`](https://github.com/container-storage-interface/spec/blob/master/spec.md#deletevolume)
> If a volume corresponding to the specified volume_id does not exist or the artifacts associated with the volume do not exist anymore, the Plugin MUST reply 0 OK.

[`DeleteSnapshot`](https://github.com/container-storage-interface/spec/blob/master/spec.md#deletesnapshot)
> If a snapshot corresponding to the specified snapshot_id does not exist or the artifacts associated with the snapshot do not exist anymore, the Plugin MUST reply 0 OK.

When `DeleteVolume/Snapshot` is being called, we're not deleting only the volume/snapshot, but also a number of other resources on which the volume/snapshot depends on. This means that any possible errors that may occur while performing the deletion may leave the volume/snapshot in an inconsistent state, where the already deleted resources would prevent deletion of the leftover resources due to _Not Found_ errors (which should be treated as success).

Another case of this problem is described in https://github.com/ceph/ceph-csi/issues/192, where the volume is in fact deleted, but due to timeouts, all subsequent attempts to delete (an already deleted) volume fail, rendering the overall operation as a failure where it should have been a success.

**Describe the solution you'd like**
For deletion, _Not Found_ errors are ought to be treated as success, but best effort should be made to delete all resources - returning immediately after _Not Found_ might not be sufficient.

Example with csi-cephfs plugin:
* First attempt for `DeleteVolume` RPC: volume is deleted fine, but deleting the dedicated ceph user takes too long, external-provisioner retries. After some time the operation fails because of connection failure and returns with error.
* Second attempt: the plugin sees the volume doesn't exist - it shouldn't return success immediately but rather continue with the deletion.

**Comment by Madhu-1** [comment]
@gman0 ,@rootfs  I think same applies for volume/snapshot create also. suppose volume creation succeed in ceph but failed to store the metadata, don't we end up in the same situation?


and currently, we delete the rbd volume and snapshot if storing metadata fails. do we need to delete the same? cant we retrieve the volume/snapshot based on the name?

**Comment by gman0** [comment]
@Madhu-1 not anymore, see https://github.com/ceph/ceph-csi/pull/201

**Comment by Madhu-1** [comment]
@gman0 sorry i missed the recent change, Thanks :)

**Comment by Madhu-1** [comment]
Fixed in #201
