### ISSUE TITLE
Add E2E testing to validate the Encryption keys in KMS

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2022]
Currently looks like we are not validating the creation and deletion of the Encryption keys in the KMS. we need to add an E2E to verify that the keys get created and deleted properly.

update: we have E2E for PVC not for restore from snapshot or PVC-PVC clone

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/pull/2021 added E2E for snapshots, we need to do the same for PVC-PVC cloned images also.

**Comment by yati1998** [comment]
Hey @Madhu-1 , if no one is working I can work on this issue?

**Comment by Madhu-1** [comment]
closed by #2095
