### ISSUE TITLE
question about volumeName in RBD

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#204]
In RBD, volume name is a required parameter and for the same validation has been done [here](https://github.com/ceph/ceph-csi/blob/csi-v1.0/pkg/rbd/controllerserver.go#L82).
and [here](https://github.com/ceph/ceph-csi/blob/csi-v1.0/pkg/rbd/controllerserver.go#L102) we are checking if the length of volume name is `zero`, is it possible to hit this case in any mean?

**Comment by Madhu-1** [comment]
@rootfs @gman0 ^^

**Comment by gman0** [comment]
Correct me if I'm wrong, but it seems like the spec doesn't have an opinion on the minimum name length.

**Comment by Madhu-1** [comment]
I don't see a minimum length of volume name, but i have read it again to double check. But as i said earlier we are making the volume name as mandatory parameter we can skip the second length check IMO.

**Comment by gman0** [comment]
Can we close this?
