### ISSUE TITLE
RBD: Failed to mount cloned PVC when parent PVC and snapshot is deleted

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2044]
With kernel v3.10.x failed to mount the PVC when the parent PVC and snapshot is deleted

```
  Normal   Scheduled               10s              default-scheduler        Successfully assigned default/csirbd-demo-pod to minikube
  Normal   SuccessfulAttachVolume  10s              attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-ebfbcb08-41ee-4042-bcb9-24b4d7b096da"
  Warning  FailedMount             3s (x4 over 7s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-ebfbcb08-41ee-4042-bcb9-24b4d7b096da" : rpc error: code = Internal desc = image not found: RBD image not found

```

steps to reproduce the issue

* Create PVC
* Create Snapshot from PVC
* Delete PVC
* Create Clone from snapshot
* Delete snapshot
* Mount PVC clone to application pod
* Delete PVC clone and application pod

**Comment by humblec** [comment]
@Madhu-1 if the kernel does not have `deep-flatten` support, Isnt  'mount' supposed to fail ? or we have some other bug which allowed other operations to proceed like `snapshot creation` , `parent PVC deletion`, `restore` but ONLY fails at "mount" of restored PVC which is not correct?

**Comment by Madhu-1** [comment]
> @Madhu-1 if the kernel does not have `deep-flatten` support, Isnt 'mount' supposed to fail ? 

the mount should not fail if the mount fails it's problematic for user applications. cephcsi should handle this problem by flattening the image before mounting.

>or we have some other bug which allowed other operations to proceed like `snapshot creation` , `parent PVC deletion`, `restore` but ONLY fails at "mount" of restored PVC which is not correct?

can you please elaborate on this one?

**Comment by humblec** [comment]
```
steps to reproduce the issue

    Create PVC
    Create Snapshot from PVC
    Delete PVC
    Create Clone from snapshot
    Delete snapshot
    Mount PVC clone to application pod
    Delete PVC clone and application pod
```
@Madhu-1 even if we do first 4 steps, ie `Create PVC-> Snapshot-> Delete PVC -> Create Clone` Then if we  `Mount`, it should also fail in this situation, Isnt it ?

**Comment by Madhu-1** [comment]
Yes, there are multiple ways to reproduce it. the main problem is that snapshot or parent pvc should be deleted
