### ISSUE TITLE
cephfs upgrade E2E is failing

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2052]
Looks like cephfs upgrade testing is failing someone needs to look into it

Log snippet

```log
I0504 09:32:26.319040       1 utils.go:162] ID: 19 Req-ID: 0001-0024-52af6820-1cb4-4a6a-a658-1738d60361fd-0000000000000001-f617b3d4-acba-11eb-b431-9e8aec51583b GRPC call: /csi.v1.Node/NodeStageVolume
I0504 09:32:26.319192       1 utils.go:166] ID: 19 Req-ID: 0001-0024-52af6820-1cb4-4a6a-a658-1738d60361fd-0000000000000001-f617b3d4-acba-11eb-b431-9e8aec51583b GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-77db9a45-5407-49a1-a9e1-ba89255fc9bf/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["debug"]}},"access_mode":{"mode":5}},"volume_context":{"clusterID":"52af6820-1cb4-4a6a-a658-1738d60361fd","fsName":"myfs","pool":"myfs-data0","storage.kubernetes.io/csiProvisionerIdentity":"1620120451914-8081-cephfs.csi.ceph.com","subvolumeName":"csi-vol-f617b3d4-acba-11eb-b431-9e8aec51583b"},"volume_id":"0001-0024-52af6820-1cb4-4a6a-a658-1738d60361fd-0000000000000001-f617b3d4-acba-11eb-b431-9e8aec51583b"}
E0504 09:32:26.319239       1 nodeserver.go:84] ID: 19 Req-ID: 0001-0024-52af6820-1cb4-4a6a-a658-1738d60361fd-0000000000000001-f617b3d4-acba-11eb-b431-9e8aec51583b an operation with the given Volume ID 0001-0024-52af6820-1cb4-4a6a-a658-1738d60361fd-0000000000000001-f617b3d4-acba-11eb-b431-9e8aec51583b already exists
E0504 09:32:26.319268       1 utils.go:171] ID: 19 Req-ID: 0001-0024-52af6820-1cb4-4a6a-a658-1738d60361fd-0000000000000001-f617b3d4-acba-11eb-b431-9e8aec51583b GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0024-52af6820-1cb4-4a6a-a658-1738d60361fd-0000000000000001-f617b3d4-acba-11eb-b431-9e8aec51583b already exists
```

https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/rest/organizations/jenkins/pipelines/upgrade-tests-cephfs/runs/1447/nodes/87/steps/90/log/?start=0

**Comment by Madhu-1** [comment]
>May  4 10:44:01.109: INFO: csi-cephfs-demo-pod app  is in Pending phase expected to be in Running  state (600 seconds elapsed)
May  4 10:44:01.111: INFO: csi-cephfs-demo-pod app  is in Pending phase expected to be in Running  state (600 seconds elapsed)
May  4 10:44:01.111: FAIL: failed to validate CephFS pvc and application binding with error timed out waiting for the condition
[AfterEach] cephfs
  /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:175
[1mSTEP[0m: Collecting events from namespace "cephfs-694".
[1mSTEP[0m: Found 18 events.
May  4 10:44:01.117: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for csi-cephfs-demo-pod: { } Scheduled: Successfully assigned cephfs-694/csi-cephfs-demo-pod to minikube
May  4 10:44:01.117: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for csi-cephfs-demo-pod: { } FailedScheduling: 0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
May  4 10:44:01.117: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for csi-cephfs-demo-pod: { } Scheduled: Successfully assigned cephfs-694/csi-cephfs-demo-pod to minikube
May  4 10:44:01.117: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for csi-cephfs-demo-pod: { } FailedScheduling: 0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
May  4 10:44:01.117: INFO: At 2021-05-04 10:32:18 +0100 BST - event for csi-cephfs-demo-pod: {attachdetach-controller } SuccessfulAttachVolume: AttachVolume.Attach succeeded for volume "pv-name" 
May  4 10:44:01.117: INFO: At 2021-05-04 10:32:34 +0100 BST - event for csi-cephfs-demo-pod: {kubelet minikube} FailedMount: MountVolume.MountDevice failed for volume "pv-name" : rpc error: code = Internal desc = failed to fetch monitor list using clusterID (772d7b38-8ac7-43a9-a488-7f0e145c988b): missing configuration for cluster ID "772d7b38-8ac7-43a9-a488-7f0e145c988b"
May  4 10:44:01.117: INFO: At 2021-05-04 10:33:39 +0100 BST - event for csi-cephfs-demo-pod: {kubelet minikube} Created: Created container web-server
May  4 10:44:01.117: INFO: At 2021-05-04 10:33:39 +0100 BST - event for csi-cephfs-demo-pod: {kubelet minikube} Started: Started container web-server
May  4 10:44:01.117: INFO: At 2021-05-04 10:33:39 +0100 BST - event for csi-cephfs-demo-pod: {kubelet minikube} Pulled: Container image "docker.io/library/nginx:latest" already present on machine
May  4 10:44:01.117: INFO: At 2021-05-04 10:33:42 +0100 BST - event for csi-cephfs-demo-pod: {kubelet minikube} Killing: Stopping container web-server
May  4 10:44:01.117: INFO: At 2021-05-04 10:33:59 +0100 BST - event for csi-cephfs-pvc: {persistentvolume-controller } ExternalProvisioning: waiting for a volume to be created, either by external provisioner "cephfs.csi.ceph.com" or manually created by system administrator
May  4 10:44:01.117: INFO: At 2021-05-04 10:33:59 +0100 BST - event for csi-cephfs-pvc: {cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-55f76948d4-8jm94_2464f909-9faf-47cc-a79d-1e99e73bbc6e } Provisioning: External provisioner is provisioning volume for claim "cephfs-694/csi-cephfs-pvc"
May  4 10:44:01.117: INFO: At 2021-05-04 10:33:59 +0100 BST - event for csi-cephfs-pvc: {cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-55f76948d4-8jm94_2464f909-9faf-47cc-a79d-1e99e73bbc6e } ProvisioningSucceeded: Successfully provisioned volume pvc-5804846d-a0c1-481f-a6cc-5a1b862ce546
May  4 10:44:01.117: INFO: At 2021-05-04 10:34:01 +0100 BST - event for csi-cephfs-demo-pod: {attachdetach-controller } SuccessfulAttachVolume: AttachVolume.Attach succeeded for volume "pvc-5804846d-a0c1-481f-a6cc-5a1b862ce546" 
May  4 10:44:01.117: INFO: At 2021-05-04 10:36:04 +0100 BST - event for csi-cephfs-demo-pod: {kubelet minikube} FailedMount: Unable to attach or mount volumes: unmounted volumes=[mypvc], unattached volumes=[mypvc default-token-z4j42]: timed out waiting for the condition
May  4 10:44:01.117: INFO: At 2021-05-04 10:36:08 +0100 BST - event for csi-cephfs-demo-pod: {kubelet minikube} FailedMount: MountVolume.MountDevice failed for volume "pvc-5804846d-a0c1-481f-a6cc-5a1b862ce546" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
May  4 10:44:01.117: INFO: At 2021-05-04 10:36:09 +0100 BST - event for csi-cephfs-demo-pod: {kubelet minikube} FailedMount: MountVolume.MountDevice failed for volume "pvc-5804846d-a0c1-481f-a6cc-5a1b862ce546" : rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0024-772d7b38-8ac7-43a9-a488-7f0e145c988b-0000000000000001-da975433-acbb-11eb-b3b1-b2e5c4172e07 already exists
May  4 10:44:01.117: INFO: At 2021-05-04 10:40:38 +0100 BST - event for csi-cephfs-demo-pod: {kubelet minikube} FailedMount: Unable to attach or mount volumes: unmounted volumes=[mypvc], unattached volumes=[default-token-z4j42 mypvc]: timed out waiting for the condition

one more instance but this is in Kubernetes 1.20 testing

**Comment by nixpanic** [comment]
might be a duplicate of #1969 ?

**Comment by Madhu-1** [comment]
@nixpanic for this issue looks like kubernetes is running fine and PVC mounting is failing.

**Comment by Madhu-1** [comment]
Not seen in recent builds closing this one.
