### ISSUE TITLE
Support snapshot restore to a thick provisioned PVC

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2071]
# Describe the bug #

If the snapshot is created from a thin provisioned PVC and and if we attempt snapshot restore based on a SC which has "thick provision" set, the snapshot restore operation goes through. The restore PVC move to "BOUND" state and we can attach this PVC to a POD. However this PVC is not "thick provisioned" eventhough restore SC has it set. 

ideally below combination should work.

```
1. Thin SC to create PVC --> Thick SC to restore snapshot.
2. Thick SC to create PVC --> Thick SC to restore snapshot
3. Thick SC to create PVC --> Thin SC to restore snapshot.
```

Clone:

 Thick SC to create PVC --> Same thick SC to clone

**Comment by humblec** [comment]
@nixpanic jfyi

**Comment by Madhu-1** [comment]
@nixpanic Is creating thick clones already supported?

**Comment by humblec** [comment]
> @nixpanic Is creating thick clones already supported?

Few options we could see : 

Like `deep cp` , `unsparsify`...etc , but we have to check how to achieve this in ideal way

**Comment by humblec** [comment]
> > @nixpanic Is creating thick clones already supported?
> 
> Few options we could see :
> 
> Like `deep cp` , `unsparsify`...etc , but we have to check how to achieve this in ideal way

To be clear, those are not direct RBD image clone operations..

**Comment by Madhu-1** [comment]
> > @nixpanic Is creating thick clones already supported?
> 
> Few options we could see :
> 
> Like `deep cp` , `unsparsify`...etc , but we have to check how to achieve this in ideal way

@humblec sorry I didn't get this one

**Comment by nixpanic** [comment]
In order to un-thick a thick-provisioned volume, there is `rbd sparsify` that punches holes in the volume. I suggested that an `rbd unsparsify` command is needed to create a thick-clone from a thin-provisioned image. I am not aware that a `rbd unsparsify` or similar command or librbd-API exists.

This most likely depends on a new feature that needs to be implemented in Ceph RBD and go-ceph.

**Comment by nixpanic** [comment]
@humblec do you want to prevent cloning of a thin-provisioned volume with a thick-provisioner StorageClass?

**Comment by humblec** [comment]
> @humblec do you want to prevent cloning of a thin-provisioned volume with a thick-provisioner StorageClass?

@nixpanic  Ideally if the new PVC ( here restore pvc) request comes up without thick provision enabled, it should go through. In short: below combinations is :

```
1. Thin SC to create PVC --> Thick SC to restore snapshot.
2. Thick SC to create PVC --> Thick SC to restore snapshot
3. Thick SC to create PVC --> Thin SC to restore snapshot.
```

**Comment by Madhu-1** [comment]
> @humblec do you want to prevent cloning of a thin-provisioned volume with a thick-provisioner StorageClass?

cloning with different storageclass is not supported isn't it?

**Comment by humblec** [comment]
> > > @nixpanic Is creating thick clones already supported?
> > 
> > 
> > Few options we could see :
> > Like `deep cp` , `unsparsify`...etc , but we have to check how to achieve this in ideal way
> 
> @humblec sorry I didn't get this one

@Madhu-1 I was mentioning some of the options we have to solve this or options we could explore. :+1: 

> > @humblec do you want to prevent cloning of a thin-provisioned volume with a thick-provisioner StorageClass?
> 
> cloning with different storageclass is not supported isn't it?

Yeah, its not supported, so the different SC request could fail anyway.

**Comment by jilju** [comment]
> > cloning with different storageclass is not supported isn't it?
> 
> Yeah, its not supported, so the different SC request could fail anyway.

This issue is valid in this case as well. 
Thick SC to create PVC --> Same thick SC to clone

**Comment by humblec** [comment]
> > > cloning with different storageclass is not supported isn't it?
> > 
> > 
> > Yeah, its not supported, so the different SC request could fail anyway.
> 
> This issue is valid in this case as well.
> Thick SC to create PVC --> Same thick SC to clone

True.  :+1:

**Comment by Madhu-1** [comment]
> > > cloning with different storageclass is not supported isn't it?
> > 
> > 
> > Yeah, its not supported, so the different SC request could fail anyway.
> 
> This issue is valid in this case as well.
> Thick SC to create PVC --> Same thick SC to clone

Do we have an issue in this case? if yes we need to track it with a different Github issue.

**Comment by humblec** [comment]
> > > > cloning with different storageclass is not supported isn't it?
> > > 
> > > 
> > > Yeah, its not supported, so the different SC request could fail anyway.
> > 
> > 
> > This issue is valid in this case as well.
> > Thick SC to create PVC --> Same thick SC to clone
> 
> Do we have an issue in this case? if yes we need to track it with a different Github issue.

Opening one.

**Comment by nixpanic** [comment]
Please create a PR with a e2e test case for this. With that, we can better understand the issue and verify a fix.

**Comment by agarwal-mudit** [comment]
We need this also along with the clone PR, @humblec are you working on this?

**Comment by humblec** [comment]
> We need this also along with the clone PR, @humblec are you working on this?

 @agarwal-mudit, iic, the referred  thick provisioning  clone PR pretty much cover the base code path and it is good to club it with/over the same, may be thats why this was assigned to Niels.

**Comment by Madhu-1** [comment]
>If the snapshot is created from a thin provisioned PVC and and if we attempt snapshot restore based on a SC which has "thick provision" set, the snapshot restore operation goes through

This is not something supported now. Am moving this out of 3.4.0 for now. please feel free to revert if someone wants to see this in 3.4.0
