### ISSUE TITLE
create PVC  Permission denied

### ISSUE THREAD

**Issue by zhangzhao0827** [ceph/ceph-csi#2080]
![11111](https://user-images.githubusercontent.com/41892552/118252808-c02dda00-b4db-11eb-8fa4-cc1bf85d92ac.png)

**Comment by Yuggupta27** [comment]
Hi @zhangzhao0827 , can you please provide csi-cephfsplugin and csi-provisioner container logs from the provisioner pod?

**Comment by zhangzhao0827** [comment]
Hi @Yuggupta27 ,
Here are some of t
[Uploading kube-system_csi-cephfsplugin-provisioner-7f577b4bfc-dmtv9_csi-provisioner.log…]()
he logs. Please look at them. Thanks.

**Comment by zhangzhao0827** [comment]
Hi @Yuggupta27 ,this is one of csi-provisioner's logs
![545](https://user-images.githubusercontent.com/41892552/118421946-c519a600-b6f4-11eb-8f67-a1cecf685990.png)
and this is one of ccsi-cephfsplugin's logs
![654](https://user-images.githubusercontent.com/41892552/118422063-0b6f0500-b6f5-11eb-892c-e1eb9c2b3617.png)

Please take a look at it for me. Thank you.

**Comment by Yuggupta27** [comment]
Hey @zhangzhao0827 , Can you please share the logs of csi-cephfsplugin container from the provisioned pod? Along with that, which ceph-csi release is being used in the setup?

**Comment by zhangzhao0827** [comment]
Hi @Yuggupta27 ,here is the logs of csi-cephfsplugin container from the provisioned pod
[kube-system_csi-cephfsplugin-provisioner-7f577b4bfc-dmtv9_csi-cephfsplugin.log](https://github.com/ceph/ceph-csi/files/6490823/kube-system_csi-cephfsplugin-provisioner-7f577b4bfc-dmtv9_csi-cephfsplugin.log)
and the version of ceph-csi is 3.2.0
![vvv](https://user-images.githubusercontent.com/41892552/118427962-f8fac880-b700-11eb-867f-01dedfaecfde.png)

**Comment by Madhu-1** [comment]
@zhangzhao0827 please specify the ceph version you are using and also the user is having the required capabilities as mentioned in https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#cephfs?

**Comment by zhangzhao0827** [comment]
@Yuggupta27 after I upgraded the CEPH version to 13, there was no "permission denied" error, but there was an error of "no handler found for 'FS subvolumegroup create'".Here is the logs of csi-cephfsplugin container from the provisioned pod.
[kube-system_csi-cephfsplugin-provisioner-7f577b4bfc-c6jlg_csi-cephfsplugin.log](https://github.com/ceph/ceph-csi/files/6492613/kube-system_csi-cephfsplugin-provisioner-7f577b4bfc-c6jlg_csi-cephfsplugin.log)

**Comment by Madhu-1** [comment]
@zhangzhao0827 minimum supported ceph version  is 14.2.2 https://github.com/ceph/ceph-csi#support-matrix

**Comment by zhangzhao0827** [comment]
@Yuggupta27 version has been upgraded to 15, but there are still problems, here is the log, please help check, thank you
[Uploading kube-system_csi-cephfsplugin-provisioner-7f577b4bfc-c6jlg_csi-cephfsplugin.log…]()

**Comment by Yuggupta27** [comment]
> @Yuggupta27 version has been upgraded to 15, but there are still problems, here is the log, please help check, thank you
> Uploading kube-system_csi-cephfsplugin-provisioner-7f577b4bfc-c6jlg_csi-cephfsplugin.log…

Can you please re-share the link, this one seems to be broken.

**Comment by zhangzhao0827** [comment]
@Yuggupta27 
[kube-system_csi-cephfsplugin-provisioner-7f577b4bfc-c6jlg_csi-cephfsplugin.log](https://github.com/ceph/ceph-csi/files/6493270/kube-system_csi-cephfsplugin-provisioner-7f577b4bfc-c6jlg_csi-cephfsplugin.log)

**Comment by Yuggupta27** [comment]
> @zhangzhao0827 please specify the ceph version you are using and also the user is having the required capabilities as mentioned in https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#cephfs?
 
@zhangzhao0827, As @Madhu-1 mentioned above, can you please check if the user has the required capabilities?

**Comment by zhangzhao0827** [comment]
@Yuggupta27 ，i use the admin user

**Comment by zhangzhao0827** [comment]
@Yuggupta27 and there is no problem when using admin to mount directly on the Centos.

**Comment by dany27** [comment]
I have the same issue, here is my version of the related softwares:
Ceph version: 15.2.11
csi provisioner deployed with helm chart v3.3.1
K8s: 1.21

I tried admin account also but got the same problem (permission denied), rbd provisioning not work either. :/

**Comment by crsoph** [comment]
In a way, I also have that issue. I deployed ceph-csi manually (i.e. no helm) following the documentation and examples from this Github repo, devel branch.
The CephX user is called `client.cephfs-csi`.
Let's look at the Error Code returned by RADOS: I receive Error -13 as above when I enter `client.cephfs-csi` to the adminID attribute of the secret.yaml from the examples.
However, entering only `cephfs-cli` without the `client.` part, I receive Error -1.

So, @zhangzhao0827 @dany27 What's the userID string that you have in the secret?

Now, when I use the actual ceph admin user (`adminID: admin` & `adminKey` set to the admin's key), creating the PVC works fine.

Both the cephfs-csi user and the admin user have the same capabilities according to `ceph auth ls`:
~~~
client.admin
	key: <ADMIN_KEY>
	caps: [mds] allow *
	caps: [mgr] allow *
	caps: [mon] allow *
	caps: [osd] allow *
[...]
client.cephfs-csi
	key: <USER_KEY>
	caps: [mds] allow *
	caps: [mgr] allow *
	caps: [mon] allow *
	caps: [osd] allow *
~~~

I wonder if this is related to #904 or #919?
