### ISSUE TITLE
Add optional configuration to SecretsMetadataKMS to read passphrase from Namespace/Secret

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#2107]
# Describe the feature you'd like to have #

It would be useful to be able to configure the SecretsMetadataKMS with options to fetch the `encryptionPassphrase` from a given Namespace/Secret instead of the standard StorageClass Secret.

# What is the value to the end user? (why is it a priority?) #

The SecretsMetadataKMS service uses the `encryptionPassphrase` from the Secrets that are configured for the StorageClass. When Rook is used for deploying, the Secret is reconciled at regular intervals. After reconciling, any manual modifications (like adding a `encryptionPassphrase` are undone.

# How will we know we have a good solution? (acceptance criteria) #

The extended configuration would be reflected at

https://github.com/ceph/ceph-csi/blob/81809500be8dde7760978b3daa2e15bc2740eec1/examples/kms/vault/csi-kms-connection-details.yaml#L34-L37

**Comment by yati1998** [comment]
@nixpanic a small typo in the heading: "passphrase"
