### ISSUE TITLE
Add documentation of Regional/Metro DR

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2117]
Add documentation which covers failover and failback in case of Regional/Metro DR

**Comment by Madhu-1** [comment]
@Yuggupta27 looks like this is closed now can you please open a separate issue for Metro DR?

**Comment by Yuggupta27** [comment]
> @Yuggupta27 looks like this is closed now can you please open a separate issue for Metro DR?

Sure @Madhu-1 , will open another issue for the same.
