### ISSUE TITLE
Locking in NodeUnpublishVolume significantly slows down pod deletion

### ISSUE THREAD

**Issue by mape90** [ceph/ceph-csi#2123]
Case:
Application with multiple pods that have 20 PVs attached to it running on same node. There maybe only 20 PVs but all pods attach these volumes. (20 pods with 20 PVs on single node, all pods attach all 20 PVs) This Requires 400 mount binds and 20 actual cephfs mounts.

Issue:
Deletion of this application can take +15min because volumes are not unmounted and pods hang in Terminating state. Other CSI can handle this in some minutes.

Cause:
NodeUnpublishVolume acquires lock and returns error in case lock is held by another call. At mass deletion of pods (application unistal) NodeUnpublishVolume is called by kubelet ~400times almost immediately. This causes that most of the calls will fail as only first calls can acquire the lock and process the unmount. Others fail and cause back off delay to trigger. So first small patch of PVs are unattached. And all others fail the next round again only part of the volumes succeed and every time calls fail it will take longer and longer.

Actual NodeUnpublishVolume call when successful only takes 100-200ms. So call calls should complete in 1min

Possible solution:
Is the lock absolutely necessary for calling unmount? 
What makes it necessary to lock in NodeUnpublishVolume, as no other CSI implementation has lock. And they call same unmount and os.Remove. Also there is another lock for fuse that is this lock scope.

**Comment by mape90** [comment]
Same issue could happen also for NodePublishVolume, however there seems that kubelet gets throttled by k8s API. This causes that NodePublishVolume are only called 1/sec. Increasing the qps will make the mounting go faster. So there the problem is on kubelet side and not on CSI.

**Comment by humblec** [comment]
> Same issue could happen also for NodePublishVolume, however there seems that kubelet gets throttled by k8s API. This causes that NodePublishVolume are only called 1/sec. Increasing the qps will make the mounting go faster. So there the problem is on kubelet side and not on CSI.

Thanks for the detailed analysis . At umount/unpublish, we take lock ( https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/nodeserver.go#L576 )  to make sure or check any other ongoing operation exist on the volume. But considering the operation of unmount should not cause any harmful operation to the volume itself , I think we can live without locking. But allow some time, we have to think through this .

**Comment by mape90** [comment]
Hi,

I checked the code again and fro cephfs the lock is only called with functions NodeStageVolume/NodeUnStageVolume/NodePublishVolume/NodeUnPublishVolume. In RBD there is also NodeExpandVolume.

In kubelet code it is made sure that stage/unstage/publish/unpublish can not be called at same time.
Stage has to happen before Publish other vice there is no source to bind. And kubelet never calls mount and unmount at same time. So they can not collide. And cephfs do not need NodeExpandVolume. So in current state there isn't anything that could even in theory require locking.

For RBD it could be possible that NodeExpandVolume would be called at any point. However only thing that can there happen is if mount/umount and resizefs are called at same time. Can this cause problems for filesystem or are all supported FS handling this gracefully? And why no other CSI implementation isn't concerned about this issue? Even they have the same potential issue.

**Comment by mape90** [comment]
I now followed the full execution path of Kubelet for CSI calls. So I found that it already implements the locking/preventing parallel actions on volumes. So there is no need for locking in CSI.

Only UnmountVolume is allowed to be called multiple parallel. However it only is allowed to run with other UnmountVolume calls.

So only fusePidMapMtx.Lock() is needed in unmountVolume as there it is possible that kubelet can issue many calls at once.

"locking" implementation is done with nestedpendingoperations library in pendingOperations.

High level kubelet code goes as:
```
kubelet
	VolumeManager
		- reconcile()
		1) unmountVolumes()
			if actualStateOfWorld = mounted and desiredStateOfWorld != unmounted
				operationExecutor.UnmountVolume
					pendingOperations.Run(volID,PodName,podName,"",operationGenerator.GenerateUnmountVolumeFunc)
					  -> Signal to CSI
		2) mountAttachVolumes()
			if !attached
				operationExecutor.AttachVolume
					pendingOperations.Run(volID,"","",GenerateVerifyControllerAttachedVolumeFunc)
						-> Signal to CSI
			elif !mounted
				operationExecutor.MountVolume
					pendingOperations.Run(volID,PodName,"","",operationGenerator.GenerateMountVolumeFunc)
						-> Signal to CSI
			elif needs_resize
				operationExecutor.ExpandInUseVolume
					pendingOperations.Run(volID, "", "",operationGenerator.GenerateExpandInUseVolumeFunc)
						-> Signal to CSI
		3) unmountDetachDevices() ...
		4) sync
		5) sleep
```

**Comment by humblec** [comment]
> I now followed the full execution path of Kubelet for CSI calls. So I found that it already implements the locking/preventing parallel actions on volumes. So there is no need for locking in CSI.
> 
> Only UnmountVolume is allowed to be called multiple parallel. However it only is allowed to run with other UnmountVolume calls.
> 
> So only fusePidMapMtx.Lock() is needed in unmountVolume as there it is possible that kubelet can issue many calls at once.
> 
> "locking" implementation is done with nestedpendingoperations library in pendingOperations.
> 
> High level kubelet code goes as:
> 
> ```
> kubelet
> 	VolumeManager
> 		- reconcile()
> 		1) unmountVolumes()
> 			if actualStateOfWorld = mounted and desiredStateOfWorld != unmounted
> 				operationExecutor.UnmountVolume
> 					pendingOperations.Run(volID,PodName,podName,"",operationGenerator.GenerateUnmountVolumeFunc)
> 					  -> Signal to CSI
> 		2) mountAttachVolumes()
> 			if !attached
> 				operationExecutor.AttachVolume
> 					pendingOperations.Run(volID,"","",GenerateVerifyControllerAttachedVolumeFunc)
> 						-> Signal to CSI
> 			elif !mounted
> 				operationExecutor.MountVolume
> 					pendingOperations.Run(volID,PodName,"","",operationGenerator.GenerateMountVolumeFunc)
> 						-> Signal to CSI
> 			elif needs_resize
> 				operationExecutor.ExpandInUseVolume
> 					pendingOperations.Run(volID, "", "",operationGenerator.GenerateExpandInUseVolumeFunc)
> 						-> Signal to CSI
> 		3) unmountDetachDevices() ...
> 		4) sync
> 		5) sleep
> ```

Thanks @mape90 for the call path! , even I am leaning towards we can get rid of that locking at NodeUnPublish. I will go through and confirm this soon .. :+1:

**Comment by Madhu-1** [comment]
Note this needs to be tested extensively or else we will end up in problems. Even if any bug introduced in the future kubernetes or other CO version that can lead to other problems.

**Comment by mape90** [comment]
If kubernetes introduces bug that would require locking for CSIs it would mean that each CSI drivers would break as no other implement any kind of locking. So it would not be something that would only hit ceph-csi. However, yes testing is always good.

Here is some pointers for helping you to verify kubelet logic:
kubernetes/pkg/kubelet/volumenanager/reconciler/reconciler.go
- Here you find the logic how events are generated and how kubelet makes sure
  that operations for volumes are done in correct order.
kubernetes/pkg/kubelet/volumenanager/cache/*.go
- Here is the desired and actual state of world implementations. The state machine kubelet uses for selection actions.
kubernetes/pkg/volume/util/operationexecutor/operation_executor.go
- Generates the volume action calls.
kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
- Generates the functions for calling volume actions.
kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go
- Has the "locking" logic where it makes sure that duplicate calls can not be generated.
kubernetes/pkg/volume/csi/*.go
- Here is the implementation where actual CSI signals are generated.

**Comment by humblec** [comment]
> If kubernetes introduces bug that would require locking for CSIs it would mean that each CSI drivers would break as no other implement any kind of locking. So it would not be something that would only hit ceph-csi. However, yes testing is always good.
> 

True. Looking into this issue/fix, I went through  the other CSI drivers and yes, no one care about an exclusive access lock here , but interestingly those CSI drivers does not keep a state db like ( `omap`) we have today.  Verifying the code paths some more in depth to make sure we wont introduce regressions on this.

**Comment by Madhu-1** [comment]
Closing this one as #2149 is merged. Thanks, @mape90 for opening the issue and for providing more detailed information :+1:
