### ISSUE TITLE
Qualify data consistent snapshots and cloning with NBD backend

### ISSUE THREAD

**Issue by pkalever** [ceph/ceph-csi#2124]
# Describe the feature you'd like to have #

rbd-nbd backends support quiesce feature. While taking the snapshots rbd will notify rbd-nbd to call the quiesce hooks, upon receiving the notification the rbd-nbd will freeze the mount points and wait to finish the inflight IO. Once the snapshot is completed, rbd will notify the unquiesce, now rbd-nbd will unfreeze the mount points and allow IO to continue.

# What is the value to the end user? (why is it a priority?) #

Data consistent snapshots and clones.

**Comment by pkalever** [comment]
@Madhu-1 @nixpanic please assign this to me.

Also please target this for `release-3.4.0` milestone.

Thanks!

**Comment by humblec** [comment]
@pkalever instead of reinventing the wheel, my suggestion here is to make use of standard API which is getting introduced in Kube. That said, we have an upcoming feature for application consistent snapshots which could make use of `container notifier` and its `handler` mechanism which is flexible enough to make use of storage vendors `quiece and unqueice` features. There were enough discussions on this to make it flexible enough for various storage systems , so lets make use of it, as the expectation from a kube/ocp user could match with the available standard mechanisms in kube rather than our own way of doing the things and also its better to avoid different implementation for various backends like `krbd, rbd-nbd, cephfs`..etc even in our driver.

Reference#  
https://github.com/kubernetes/enhancements/pull/1051  
https://github.com/kubernetes/enhancements/pull/1995/

**Comment by nixpanic** [comment]
Removing this from the 3.4.0 planning. There are features planned in Kubernetes (and CSI?) that involve the application and storage layers for a better coordination of quiescing and filesystem freezing.

**Comment by msfrucht** [comment]
@nixpanic Can you point me to those planned features. Coordinated snapshots across multiple PVC would be really nice for clustered applications that use multiple PVCs in RWO mode like MongoDB.

**Comment by pkalever** [comment]
> @pkalever instead of reinventing the wheel, my suggestion here is to make use of standard API which is getting introduced in Kube. That said, we have an upcoming feature for application consistent snapshots which could make use of `container notifier` and its `handler` mechanism which is flexible enough to make use of storage vendors `quiece and unqueice` features. There were enough discussions on this to make it flexible enough for various storage systems , so lets make use of it, as the expectation from a kube/ocp user could match with the available standard mechanisms in kube rather than our own way of doing the things and also its better to avoid different implementation for various backends like `krbd, rbd-nbd, cephfs`..etc even in our driver.

@humblec Rbd-NBD already supports quiescing and this is not something that we are adding today, this is already supported today with ceph-csi too. All one has to do is to provide quiesce option in  `mapOptions: quiesce` at the storage class YAML.

This issue is to highlight its availability and also dev qualify snapshots and clones with rbd-nbd.

That all said, this option is coming from the storage vendor (RBD) directly, which means the inflight IO is well-taken care of already (Nothing more needs to be done)

Kubernetes Stateful Application Data Management API is at the layer above and will help cephfs and rbd (kernel mounter) too once available, we can see how it will benefit rbd-nbd once available like maybe to help capture definitions of Kubernetes resources that make up the application, e.g., Services, ConfigMaps, Secrets, etc.

I had highlighted the subject about Data Consistency because that is very useful as it was not available with rbd (kernel) and cephfs currently.

Treat this as a qualification effort for rbd-nbd for snapshots and clones.

**Comment by pkalever** [comment]
Update:
I had tested snapshots and clones with rbd-nbd mounter both with and without `mapOptions: quiesce`
They are working as expected. We can move this to Qualified. I will send a separate PR to add the doc changes required.

**Comment by pkalever** [comment]
@nixpanic @Madhu-1 I had fixed the subject of this issue to avoid confusion. Request to reattach this to the `release-3.4.0` tracker.

Thanks!
