### ISSUE TITLE
Failed to create over sized thick provisioning image 

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2128]
Currently For thick provisioning cephcsi creates an image and it writes zeros to the images until the image is full. If the ceph cluster gets full 9occupied more than 85%) during this operation the cephcsi client opened to write zeros hangs and all the subsequent requests for the same volume returns with an error when a user deletes the PVC this will leave a stale rbd image in the cluster.

The above problem can be fixed by #2115  by setting the SetPoolFullTry flag (which allows the delete of rbd images even if the cluster is full and also it returns an error when we are writing zeros when the ceph is full). Even with this fix, we end up Creating/Deleting the image multiple times until the ceph is freed up.  Once the ceph cluster is 85% the cluster becomes read-only and also affects the already mapping client read/write performance. With the help of #2125  we do check for the free space before creating the rbd image and we don't create/delete images frequent for a single PVC request. this will help to avoid the to an extent and will reduces the read/write overread of the already mapped rbd image.

**Comment by nixpanic** [comment]
> Currently For thick provisioning cephcsi creates an image and it writes zeros to the images until the image is full. If the ceph cluster gets full 9occupied more than 85%)

Note that the 85% is configurable.

> during this operation the cephcsi client opened to write zeros hangs

This is expected to be addressed with #2115.

> and all the subsequent requests for the same volume returns with an error when a user deletes the PVC this will leave a stale rbd image in the cluster.

Kubernetes will retry. Maybe there is a CSI status return code for 'provisioning in progress'? If that gets returned to Kubernetes, it should also request to abort/delete the volume that is being provisioned. This status notification exists for snapshots, maybe for volumes too?

> The above problem can be fixed by #2115 by setting the SetPoolFullTry flag (which allows the delete of rbd images even if the cluster is full and also it returns an error when we are writing zeros when the ceph is full).

Ok!

> Even with this fix, we end up Creating/Deleting the image multiple times until the ceph is freed up.

Yes, that is how Kubernetes is designed to work.

> Once the ceph cluster is 85% the cluster becomes read-only and also affects the already mapping client read/write performance.

Does this affect performance more than an application workload once the volume is provisioned? There is also a request to provide an optimized way for allocations in Ceph ([RHBZ#1924129](https://bugzilla.redhat.com/1924129)).

> With the help of #2125 we do check for the free space before creating the rbd image and we don't create/delete images frequent for a single PVC request. this will help to avoid the to an extent and will reduces the read/write overread of the already mapped rbd image.

A solution to prevent thick-provisioning from causing a full cluster should ideally take the following into account:

- understand is the reason to use thick-provisioning, it is a workaround for accounting issues, and makes it impossible to have the benefits of the (standard, well tested) thin-provisioning
- likeliness of running out of space (how many clusters are seized too small?)
- the 85% watermark in Ceph is configurable, anything Ceph-CSI does needs to adjust to that too
- ...

**Comment by nixpanic** [comment]
Some more questions that would help in judging to see if we need to (can?) fix this in Ceph-CSI

- Can we have a single sentence for the problem that needs addressing?
- Why is running out of space with thick-provisioning different from running out of space with workloads on thin-provisioned volumes?
- What cases are not addressed with #2125, and what is the plan to address those?
- Are there other workarounds that can prevent this issue from happening?
