### ISSUE TITLE
cephfs: question about cephfs directories' permissions

### ISSUE THREAD

**Issue by YingshuoTao** [ceph/ceph-csi#2137]
# Actual results #

After kernel mounting a pre-provisioned cephfs volume, the cephfs directory's permission was modified to 777.

# Expected behavior #

The mounting process should not have side effects on existing directories' privileges.

I noticed that in the snippet [internal/cephfs/nodeserver.go#L184](https://github.com/ceph/ceph-csi/blob/fb7dc13dfef64136e8fb63d237c4bae4686daa4f/internal/cephfs/nodeserver.go#L184), "chmod 777" was done to all non-readonly mount operations.
I have no idea for the reason of this behavior, could you please explain the purpose of it? Thanks!

**Comment by Madhu-1** [comment]
This is done to provide write access to the applications created with normal users https://github.com/ceph/ceph-csi/pull/423

**Comment by miaoshixuan** [comment]
Why not let users set it by themselves? Actually,I must add a initcontainer to remove 777 mod when running  some serive like postgres database.
