### ISSUE TITLE
Calling util.NewK8sClient() might lead to panic on non K8s env

### ISSUE THREAD

**Issue by pkalever** [ceph/ceph-csi#2138]
# Describe the bug #

Improve util.NewK8sClient(), currently it is very Kubernetes specific, it breaks the CSI guidelines as this now will panic on non-Kubernetes container orchestrators. There needs to be a check that logs some error and returns an error instead of panic'ing.

**Comment by Madhu-1** [comment]
The plan is to use https://github.com/ceph/ceph-csi/issues/1782 new sidecar for this operation.

**Comment by tomiles** [comment]
Indeed I get a panic running this on a Nomad cluster, so for now should we revert to v3.3.1 until there is a workaround?

**Comment by Madhu-1** [comment]
> Indeed I get a panic running this on a Nomad cluster, so for now should we revert to v3.3.1 until there is a workaround?

Sounds good to revert to avoid panic. Will see we can work about this with some `--orchestrator=kubernetes` flag when starting the cephcsi.

**Comment by pkalever** [comment]
> > Indeed I get a panic running this on a Nomad cluster, so for now should we revert to v3.3.1 until there is a workaround?
> 
> Sounds good to revert to avoid panic. Will see we can work about this with some `--orchestrator=kubernetes` flag when starting the cephcsi.

Makesense. Count me in, I can look into it.

**Comment by Madhu-1** [comment]
Thanks, @pkalever. am assigning this to you. see if you can fix it in 3.4.1

**Comment by nixpanic** [comment]
Actually, `util.NewK8sClient()` should return an error that is handled by the caller. The features are optional, so there should not be any real issue. Autodetection this way is much more user-friendly :v:

**Comment by nixpanic** [comment]
And, cleaning up Kubernetes dependencies would be much better too! `util.NewK8sClient()` and callers of that function might be more suitable to be placed in an `internal/k8s` package, providing helper functions so that there is no need to use Kubernetes objects anywhere else.

**Comment by pkalever** [comment]
@tomiles it will be helpful if you can paste the logs, I want to understand the panic causing instances better.

**Comment by humblec** [comment]
#2466 should have the fix for this issue. i am closing this issue for now . `3.4.1` release planned next week should carry this too @tomiles  :+1:

**Comment by tobias-urdin** [comment]
@humblec any progress on that 3.4.1? fix is still unreleased for a couple of months now since only 3.4.0 is released
