### ISSUE TITLE
cephfs: efficient read-only snapshots as volumes

### ISSUE THREAD

**Issue by gman0** [ceph/ceph-csi#2142]
# Describe the feature you'd like to have #

CephFS exposes snapshots as special, read-only directories of a subvolume. cephfs-csi can already provision writable volumes with snapshots as their data source, where snapshot contents are cloned to the newly created volume. Cloning to snapshot to volume is very expensive in CephFS, as the data needs to be fully copied.

I propose creating read-only (shallow) volumes from snapshots is added to cephfs-csi, where the driver would take advantage of the fact that snapshot's data is already available in a directory, and that directory would be exposed to workloads as a volume. This would make it possible to avoid the expensive cloning process.

# What is the value to the end user? (why is it a priority?) #

What's the point of such read-only volumes?
* **Restore snapshots selectively:** users may want to traverse snapshots, restoring data to a writable volume more selectively instead of restoring the whole snapshot.
* **Volume backup:** users can't backup a live volume, they first need to snapshot it. Once a snapshot is take, it still can't be backed-up, as backup tools usually work with volumes (that are exposed as file-systems) and not snapshots (which might have backend-specific format). What this means is that currently with cephfs-csi we'd have to clone snapshot data twice:
   1. first time, when restoring the snapshot into a volume,
   2. and second time, when transferring that volume into some backup/archive storage (e.g. object store).
   
   The backed-up volume will most likely be thrown away after the backup is finished. That's a lot of wasted work for what we originally wanted to do! Having the ability to create volumes from snapshots cheaply would be a big improvement for this use case.

# How will we know we have a good solution? (acceptance criteria) #

Creating/deleting and mounting/unmounting such read-only volumes should be O(1) regardless of snapshot size.

# Alternatives

* _User's could simply go to `.snap/<snapshot name>` by themselves._
   `.snap` is CephFS-specific detail of how snapshots are exposed. Users / tools may not be aware of this special directory, or it doesn't fit the workflow. The idiomatic way of accessing snapshot contents is by creating a new volume and populating it with snapshot.

# Additional context #

If you agree with the proposed feature, I can add a PR for a `docs/proposals` document where we can discuss this in more detail. After that I can work on its implementation.

**Comment by Madhu-1** [comment]
@gman0 sounds good hope we can see a design doc soon on this one. Also, note we are planning for cephfs mirroring support in cephcsi soon which will directly replicate the volume to remote ceph cluster but looks like this is useful if someone wants to do backup to some other store (object store).

cc @ShyamsundarR @kotreshhr

**Comment by gman0** [comment]
I'm still working on it but I'll submit it soon.

**Comment by pehlert** [comment]
Just to add here from a user perspective:

Through the amazing kasten.io, we not only create snapshots but also regularly transfer the data to an S3 store off-site which I think is a very common use-case.

While rbd snapshots and exports are working just fine, creating volumes from even medium-size cephfs snapshots is virtually impossible as the volume creation alone takes 30min+ for <60GB of data, so we'll run into timeouts at that step already.

As I see it this proposal would allow to mount the snapshot read-only which should be near instant? That would be a very useful feature!

**Comment by gman0** [comment]
@pehlert Thanks for your feedback! We have essentially the same use-case.

> As I see it this proposal would allow to mount the snapshot read-only which should be near instant?

Yes, if all goes well, this should be the result.

**Comment by taxilian** [comment]
This would definitely enable use cases which are very important to me as well -- the benefits for backup solutions would be difficult to overstate.

`Users could simply go to .snap/<snapshot name> by themselves.` - I was not aware of this and don't know how to use it in kubernetes -- I will definitely be looking into it to see if it can be used as a reasonable solution in the mean time

**Comment by taxilian** [comment]
It looks like this shouldn't be too difficult to do -- it's even technically possible to do it semi-reasonably using a script, though maybe I'm missing something that would make it easier?

- Look at the VolumeSnapshot you want to back up, get the VolumeSnapshotContent
- Look at the VolumeSnapshotContent you want to use and grab the last 36 characters of the Snapshot Handle (a guid)
- Look inside the PVC in question and list .snap/, find the directory which starts with `_csi-snap-${guid}` -- that is your read-only mount of the snapshot
- Start a backup pod using .snap/<dirname> as the subPath -- I haven't tested this, so not 100% sure it would work.

There are several steps here for which I can't think of a good way to automate, sadly; if there were it would really help a lot. Another thing that could help is if the name of those directories was easier to find, without jumping through three hoops. I assume there is some source for the suffix of the `.snap/<???>` directory name but I can't figure out what it is.

**Comment by haslersn** [comment]
This feature is important to me, too. It is important for implementing https://github.com/vmware-tanzu/velero/issues/3544 in an ideomatic way instead of accessing `.snap`.

**Comment by Madhu-1** [comment]
@gman0  would you like to track this for the 3.6.0 release?

**Comment by humblec** [comment]
I would like to propose this for release 3.6 considering there is a demand for this.. @gman0 please confirm from your end too!

**Comment by gman0** [comment]
@Madhu-1 @humblec thanks for pinging, yes let's do it. I'm finishing last bits in go-ceph missing for RADOS bindings and we're good to go.

**Comment by humblec** [comment]
Sure @gman0 and thanks for the patience :)

**Comment by taxilian** [comment]
I am super excited about this =] Thank you to those who are prioritizing it.

**Comment by humblec** [comment]
> I am super excited about this =] Thank you to those who are prioritizing it.

:+1: , @gman0 ++ :)

**Comment by Madhu-1** [comment]
@gman0 as we are targetting this for the 3.6 release ( by end of march), I can help on this one. please let me know if you need any help to take this to completion.

**Comment by gman0** [comment]
@Madhu-1 thanks! The last PR needed for go-ceph got merged today, and the release that contains all the new RADOS bindings, v0.14.0, is planned for next week, on the 15th. Until then I'd like to send a PR for the "reference tracker" component so that we can at least review the code. Afterwards we can start working on the code for controller and node services -- let's see if we can paralelize some tasks there.

**Comment by Madhu-1** [comment]
> @Madhu-1 thanks! The last PR needed for go-ceph got merged today, and the release that contains all the new RADOS bindings, v0.14.0, is planned for next week, on the 15th. Until then I'd like to send a PR for the "reference tracker" component so that we can at least review the code. Afterwards we can start working on the code for controller and node services -- let's see if we can paralelize some tasks there.

@gman0 Thanks for the quick response, sounds good. i think we can parallelize controller and node services (correct me if am wrong). I can help with the node service part.

**Comment by gman0** [comment]
Hi all, I have submitted the ref tracker PR in https://github.com/ceph/ceph-csi/pull/2893.

It improves on what the [design doc](https://github.com/ceph/ceph-csi/blob/devel/docs/design/proposals/cephfs-snapshot-shallow-ro-vol.md#reference-counting-for-shallow-volumes) stated in regards to when the tracking needs to happen.

The initial design has following refcounting life-cycle:
* `CreateSnapshot`: create a refcounter, initialize it to 1
* each `CreateVolume` call for a shallow volume increments the rc by 1
* each `DeleteVolume` and `DeleteSnapshot` for shallow volume decrements the rc by 1
* whenever the rc reaches zero, the backing CephFS snapshot will be deleted.

This implies that there must be one reference counter per snapshot.

---

With the reference tracker linked above, this drops down to one RT per shallow volume. Here is an example how the ref tracker would be used:

* any `CreateSnapshot` call: no change needed
* each `CreateVolume` call for a shallow volume: add (or initialize with) `thisVolID` and `sourceSnapID` refs to the tracker:

   ```go
   created, err := rt.Add(
   	ioctx,        // An existing rados.IOContext.
   	sourceSnapID, // Name for this reftracker.
   	map[string]struct{}{ // Refs to be tracked.
   		thisVolID: {},
   		sourceSnapID: {},
   	},
   )
   ```


* each `DeleteVolume` call for a shallow volume: remove ref `thisVolID` from the tracker:

   ```go
   deleted, err := rt.Remove(
   	ioctx,        // An existing rados.IOContext.
   	sourceSnapID, // Name of this reftracker.
   	map[string]reftype.RefType{ // Refs to be removed/masked.
   		thisVolID: reftype.Normal,
   	},
   )

   if deleted {
   	// The whole RT object was deleted by the Remove() operation,
   	// because all of the references it held are now gone (counter is zero).

   	// Delete the backing CephFS snapshot.
   }
   ```

* any `DeleteSnapshot` call: mask ref `thisSnapID` from the tracker:

   ```go
   deleted, err := rt.Remove(
   	ioctx,      // An existing rados.IOContext.
   	thisSnapID, // Name of this reftracker.
   	map[string]reftype.RefType{ // Refs to be removed/masked.
   		thisSnapID: reftype.Mask,
   	},
   )

   if deleted {
   	// The whole RT object was deleted by the Remove() operation,
   	// because all of the references it held are now gone (counter is zero).

   	// Delete the backing CephFS snapshot.
   }
   ```

`rt.Add()` and `rt.Remove()` are idempotent (adding a ref that's already tracked is a no-op), and if a reference is masked (as shown in the `DeleteVolume` example), it doesn't contribute to the refcount anymore and will be ignored by any future `rt.Add()` calls.

Also, regardless of `reftype.RefType` used in `rt.Remove()` calls, if the RT object doesn't exist, the function will return `deleted == true, err == nil`. That's the same as if the refcount dropped down to zero. This makes the integration of reference tracking for shallow volumes easier -- the same code path will be used in either case.

**Comment by humblec** [comment]
@gman0 this is attached to release 3.6 tracker atm.. Planning to do code freeze soon and release 3.6 on monday.. Could you please revisit this issue ?

**Comment by gman0** [comment]
@humblec yup, let's push it for the next release. I'm almost finished actually, just need to write e2e tests.

**Comment by humblec** [comment]
> @humblec yup, let's push it for the next release. I'm almost finished actually, just need to write e2e tests.

Thats great.. I am sure its gonna make it in 3.7 ! :+1:
