### ISSUE TITLE
ci: failed to checkout PR

### ISSUE THREAD

**Issue by Yuggupta27** [ceph/ceph-csi#2146]
# Describe the bug #

Job fails to checkout PR with error
```
fatal: cannot create directory at 'vendor/k8s.io/client-go/informers/node': Structure needs cleaning
```
See: https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.19/detail/mini-e2e-helm_k8s-1.19/1437/pipeline

**Comment by nixpanic** [comment]
Please check in #centos-ci on libera.chat for updates from the CentOS team.

**Comment by Yuggupta27** [comment]
Closing this issue, as it is not with our jobs, but an [issue from centos-ci side](https://pagure.io/centos-infra/issue/353)
