### ISSUE TITLE
containers crash directly after initializing

### ISSUE THREAD

**Issue by rsoika** [ceph/ceph-csi#2156]
# Describe the bug #

I followed the installation guide from ceph [here](https://docs.ceph.com/en/latest/rbd/rbd-kubernetes/)

The files [csi-rbdplugin.yaml](https://raw.githubusercontent.com/ceph/ceph-csi/master/deploy/rbd/kubernetes/csi-rbdplugin.yaml) and [csi-rbdplugin-provisioner.yaml](
https://raw.githubusercontent.com/ceph/ceph-csi/master/deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml) are containing development release 

```
....
          # for stable functionality replace canary with latest release version
          image: quay.io/cephcsi/cephcsi:canary
....
```

The documentation states tha the canary release should be replaced by a release version. I tried this by replacing 

`quay.io/cephcsi/cephcsi:canary `

with

`quay.io/cephcsi/cephcsi:3.1 or quay.io/cephcsi/cephcsi:canary:3.2 `

But this leads into a CrashLoopBackOff during deployment. Only the canary release seems to work.

Are you aware of this situation? And how can this be solved in a correct way?

# Environment details #

- Image/version of Ceph CSI driver :cephcsi/cephcsi:canary
- Ceph cluster version : octopus

**Comment by Rakshith-R** [comment]
@rsoika Please replace the image tag with any one of the tags mentioned [here](https://quay.io/repository/cephcsi/cephcsi?tab=tags) in proper format.

**Comment by yati1998** [comment]
check it [here](https://github.com/ceph/ceph-csi#ceph-csi-container-images-and-release-compatibility)
quay.io/cephcsi/cephcsi:3.1 -> quay.io/cephcsi/cephcsi:v3.1.0

**Comment by rsoika** [comment]
yes - sorry this was a typo form me in this bug report.
I think I tried every version. It takes me some hours. 

I am running my kuberentes cluster on Debian Buster. Can this be an issue?

**Comment by rsoika** [comment]
Ok, now I understand that I should take all the kubernetes objects form the corresponding release path like

https://github.com/ceph/ceph-csi/tree/release-v3.2/deploy/rbd/kubernetes

Sorry, this is not clear form the documentation which seems to mean that I should change the container versions inside the latest plugin objecs form the dev path

The sentence of the documentation [here](https://docs.ceph.com/en/latest/rbd/rbd-kubernetes/)

_The provisioner and node plugin YAMLs will, by default, pull the development release of the ceph-csi container (quay.io/cephcsi/cephcsi:canary). The YAMLs should be updated to use a release version container for production workloads._

should be

_The provisioner and node plugin YAMLs will, by default, be downloaded from the Github development release of the ceph-csi. For production you should switch to one of the release branches._

**Comment by Madhu-1** [comment]
@yati1998 can you please add a note to replace canary with version tag when deploying in production. https://github.com/ceph/ceph-csi/blob/devel/docs/deploy-rbd.md#deployment-with-kubernetes and https://github.com/ceph/ceph-csi/blob/devel/docs/deploy-cephfs.md#deployment-with-kubernetes

**Comment by yati1998** [comment]
Yes sure @Madhu-1

**Comment by shoaibjdev** [comment]
> Ok, now I understand that I should take all the kubernetes objects form the corresponding release path like
> 
> https://github.com/ceph/ceph-csi/tree/release-v3.2/deploy/rbd/kubernetes
> 
> Sorry, this is not clear form the documentation which seems to mean that I should change the container versions inside the latest plugin objecs form the dev path
> 
> The sentence of the documentation [here](https://docs.ceph.com/en/latest/rbd/rbd-kubernetes/)
> 
> _The provisioner and node plugin YAMLs will, by default, pull the development release of the ceph-csi container (quay.io/cephcsi/cephcsi:canary). The YAMLs should be updated to use a release version container for production workloads._
> 
> should be
> 
> _The provisioner and node plugin YAMLs will, by default, be downloaded from the Github development release of the ceph-csi. For production you should switch to one of the release branches._

Indeed, instead of just instructing to replace the release version for **cephcsi** image, one should take all the kubernetes objects form the corresponding release path.
