### ISSUE TITLE
[csi-cephfs] Plugin Pod dies

### ISSUE THREAD

**Issue by herrypio** [ceph/ceph-csi#217]
First of all, thanks for the csi-cephfs plugin implementations.

I have been using the csi-cephfs version `0.3.0` in our production Kubernetes `1.11.5-gke.5` for about a month. Most of the time the plugin works great, except when the plugin Pod was suddenly died and re-created by the DaemonSet. When this happened, I had to re-deploy the Pods and PVCs that use CephFS because the Pods got an error `Transport endpoint is not connected` (see #91). This situation happened 3-4 times so far.

Is there any way to mitigate this issue?

Has anyone considered to store the plugin's state (including mountpaths) on the node's volume? By this way, the plugin Pod may be able to restore the previous state when it is re-created.

**Comment by liewegas** [comment]
``Transport endpoint is not connected`` is what happens when the ceph-fuse process dies.  The question in my mind is why was the plugin pod killed/why did it die/whatever...

**Comment by herrypio** [comment]
@liewegas I and my colleagues are still collecting the data around this problem.

This might be a stupid question. Is it possible to replace the ceph-fuse process without re-deploying the user Pods and PVCs?

**Comment by liewegas** [comment]
> This might be a stupid question. Is it possible to replace the ceph-fuse process without re-deploying the user Pods and PVCs?

Nope.

If you have a reasonably recent kernel, you can use the kernel cephfs client instead...

**Comment by liewegas** [comment]
> > This might be a stupid question. Is it possible to replace the ceph-fuse process without re-deploying the user Pods and PVCs?
> 
> Nope.

Actually, I'm not 100% sure about that.  Ignoring the container part, if you mount ceph-fuse to /mnt, and ceph-fuse dies, you have to (1) fusermount -u /mnt, (2) remount at the same location.  I'm not sure if the bind mount of that path into a container will have a dangling reference to the old mount or will see the new mount.  Independent of that, though, if any files are/were open in the mount when ceph-fuse crashed then step 1 would fail with EBUSY.

So... probably still nope.

**Comment by herrypio** [comment]
As far as I know, the mount config files are stored in `/etc/ceph` directory which is located in the plugin Pod internal volume. These config files disappear when the Pod dies. However, if the plugin Pod mounts the node's volume to `/etc/ceph` then it can recover the mount config files by mounting the same node's volume when it is re-created. Afterwards the plugin can do the steps that you've mentioned before to restore ceph-fuse. But probably you're right that there's a possibility of dangling reference of the container.

**Comment by herrypio** [comment]
> If you have a reasonably recent kernel, you can use the kernel cephfs client instead...

I'm using cephfs-csi plugin because it is easier to maintain than kernel cephfs client.

**Comment by gman0** [comment]
@herrypio I think Sage meant you could use the kernel client instead of FUSE. See the `mounter` volume parameter in the [documentation](https://github.com/ceph/ceph-csi/blob/master/docs/deploy-cephfs.md#configuration). Unfortunately, as you already pointed out, another problem is `/etc/ceph`. We don't store keyrings anymore in the csi-v1.0 branch (requires k8s 1.13+) but it's still a very much WIP and things are expected to break.

**Comment by ShyamsundarR** [comment]
> `Transport endpoint is not connected` is what happens when the ceph-fuse process dies. The question in my mind is why was the plugin pod killed/why did it die/whatever...

@liewegas it could also be triggered due to an upgrade, as mentioned in #91

**Comment by UrbanWizardry** [comment]
@gman0 The trouble with kernel mounting is that it requires the Ceph packages to be installed on the host, which introduces operational overhead/issues when working on a cloud provider. We (I am a colleague of herrypio) moved from kernel mounting the old-school way to the CSI plugin with ceph-fuse partially to avoid that overhead but, per this thread, it comes with its own complications.

**Comment by Madhu-1** [comment]
@gman0 if we take the patches from csiv1.0 branch and apply to master will this be fixed?
if we do so, will there be any breaking changes?

**Comment by gman0** [comment]
@Madhu-1 i'm afraid not - the absence of keyrings after a pod restart is only 1% of the problem. It would still need a remount because of FUSE running in the container. If the container exits for whatever reason, the mount goes unavailable as well.

**Comment by huaizong** [comment]
> @Madhu-1 i'm afraid not - the absence of keyrings after a pod restart is only 1% of the problem. It would still need a remount because of FUSE running in the container. If the container exits for whatever reason, the mount goes unavailable as well.

if i want to  fixed remount problem,   the patch do these things is enough ?

1.  save the keyring info at configmap just add keyring info at controllerCacheEntry
2.  save the nodePublishVolume info when bindmount  volume root and pod mount dir as mount cache
3.  when csi-plugin start we load mount cache from node  and remount all pod pv

**Comment by gman0** [comment]
@huaizong this is a node-local problem so instead of going through the trouble of storing such information in a cluster-wide space, a better approach would be to use, in k8s case, an `emptyDir` mount and store the mount info there.

**Comment by gman0** [comment]
But still, see this comment https://github.com/ceph/ceph-csi/issues/217#issuecomment-465679017

> if any files are/were open in the mount when ceph-fuse crashed then step 1 would fail with EBUSY.

so this probably won't work either and draining may still be the best option, granted not very nice...

**Comment by huaizong** [comment]
> > if any files are/were open in the mount when ceph-fuse crashed then step 1 would fail with EBUSY.

i agree draining may be the clean option,  but  we can not  auto  drain all  pod at node, because it may be danger when  it is a cluster wide problem

**Comment by huaizong** [comment]
> @huaizong this is a node-local problem so instead of going through the trouble of storing such information in a cluster-wide space, a better approach would be to use, in k8s case, an `emptyDir` mount and store the mount info there.

thank you for relpy.  save thease info at   node local is a better approach

**Comment by herrypio** [comment]
Thanks @huaizong for #282. The PR will help us to recover when the CSI plugin Pod unexpectedly exits.

Does anyone know when this will be released?

**Comment by huaizong** [comment]
> Thanks @huaizong for #282. The PR will help us to recover when the CSI plugin Pod unexpectedly exits.
> 
> Does anyone know when this will be released?

The PR already merged in csi-v1.0 and master branch. 

@gman0  @Madhu-1  maybe we can release  some minor version just like  v1.0.1 ?

**Comment by ShyamsundarR** [comment]
> > Thanks @huaizong for #282. The PR will help us to recover when the CSI plugin Pod unexpectedly exits.
> > Does anyone know when this will be released?
> 
> The PR already merged in csi-v1.0 and master branch.
> 
> @gman0 @Madhu-1 maybe we can release some minor version just like v1.0.1 ?

The v1.0.0 [image](https://quay.io/repository/cephcsi/rbdplugin?tab=tags) in quay should already be built with this fix. Every PR merge refreshes the image, and hence this should be updated with the fix.

In the near future we would get to a versioned system, for minor updates to the 1.0 branch.

**Comment by herrypio** [comment]
I'm closing this issue because #282 is available in v1.0.0 image. Thank you all.

**Comment by tangle329** [comment]
Does this really work? I tested  #282 in my cluster, it seems the remount can not take effect in container. And `Transport endpoint is not connected` still exist when I visit the mounted path in the pod.

**Comment by ShyamsundarR** [comment]
> Does this really work? I tested #282 in my cluster, it seems the remount can not take effect in container. And `Transport endpoint is not connected` still exist when I visit the mounted path in the pod.

When I was working on https://github.com/ceph/ceph-csi/pull/390 I faced a similar issues, the re-mount occurs, but transport end point errors are still reported.

Further, the code stores the ID/Key on a local [empty dir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) volume supported by Kubernetes. I see 2 problems here,
1. Should we really store the ID/Key on the local host for every CephFS volume that is mounted? This seems like a security risk, having trusted Kubernetes secrets mechanism to store the said keys, and going back to storing this on every node. Any node compromised or such can hence leak these keys.
2. EmptyDir volumes state that "When a Pod is removed from a node for any reason, the data in the emptyDir is deleted forever." so there can be cases where this mount cache can be wiped off, because the node plugins are being restarted/recreated.

More importantly (1) is concerning, and I would vote to drop this added feature in-lieu of this concern.

@herrypio @huaizong Thoughts?

**Comment by huaizong** [comment]
> Does this really work? I tested #282 in my cluster, it seems the remount can not take effect in container. And `Transport endpoint is not connected` still exist when I visit the mounted path in the pod.

remount only take effect when pod restart @tangle329 @ShyamsundarR

**Comment by huaizong** [comment]
> > Does this really work? I tested #282 in my cluster, it seems the remount can not take effect in container. And `Transport endpoint is not connected` still exist when I visit the mounted path in the pod.
> 
> When I was working on #390 I faced a similar issues, the re-mount occurs, but transport end point errors are still reported.
> 
> Further, the code stores the ID/Key on a local [empty dir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) volume supported by Kubernetes. I see 2 problems here,
> 
> 1. Should we really store the ID/Key on the local host for every CephFS volume that is mounted? This seems like a security risk, having trusted Kubernetes secrets mechanism to store the said keys, and going back to storing this on every node. Any node compromised or such can hence leak these keys.

yeah, you are right. it depends on the mechanism of kubernetes secrets. 

> 2. EmptyDir volumes state that "When a Pod is removed from a node for any reason, the data in the emptyDir is deleted forever." so there can be cases where this mount cache can be wiped off, because the node plugins are being restarted/recreated.
> 
when pod restart on the same node the empty dir will not wipe off mount cache.

> More importantly (1) is concerning, and I would vote to drop this added feature in-lieu of this concern.
> 
> @herrypio @huaizong Thoughts?
