### ISSUE TITLE
rbd-nbd does not support `--options notrim`, fails mapping thick-provisioned volumes

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#2171]
# Describe the bug #

Enabling both thick-provisioning and the `rbd-nbd` mounter in a StorageClass causes mapping RBD images to fail:

```
rbd: map failed with error an error (exit status 22) occurred while running rbd args: [--id cephcsi-rbd-node -m rook-ceph-mon-a.rook-ceph.svc.cluster.local:6789 --keyfile=***stripped*** map replicapool/csi-vol-2ff8537d-ce8b-11eb-8cea-f696da6dd1c4 --device-type nbd --options notrim], rbd error output: rbd-nbd: unknown args: --notrim
```

It seems that the `--options notrim` is not accepted when using nbd. There might be an alternative option, or we should return a failure while provisioning when both thick-provisioning and nbd are enabled.

cc: @pkalever

**Comment by pkalever** [comment]
@nixpanic please assign this to me, I will look into this one.

Thanks!

**Comment by nixpanic** [comment]
A test case is available at #2172. Feel free to cherry-pick that commit (and adapt it if needed) when posting a fix for the issue.

**Comment by pkalever** [comment]
@nixpanic https://github.com/ceph/ceph/pull/41954 is already merged and should be out with the next release.
So we want to keep this issue open until we have a release?
I would like to hear your thoughts about it.
Thanks!

**Comment by nixpanic** [comment]
This should stay open until we have a test-case that validates thick-provisioning and rbd-nbd, including the `--notrim` attach option.

If the test-case can be adapted to check for the available options that `rbd-nbd` offers, and skips the test when the option is not available, that would be a good start.

**Comment by pkalever** [comment]
> This should stay open until we have a test-case that validates thick-provisioning and rbd-nbd, including the `--notrim` attach option.
> 
> If the test-case can be adapted to check for the available options that `rbd-nbd` offers, and skips the test when the option is not available, that would be a good start.

Yep, I remember that I added notrim option to the help here: https://github.com/ceph/ceph/blob/master/src/tools/rbd_nbd/rbd-nbd.cc#L155

So yes, I will adopt your https://github.com/ceph/ceph-csi/pull/2172 and make necessary changes.

Thanks @nixpanic :+1:
