### ISSUE TITLE
Only allow Restore/Clone from thick to thick

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2176]
Allow creation of Clone from thick PVC to thick PVC and Restore of a snapshot of a thick PVC to a thick PVC. this will keep the implementation simple.

 In the future, we can allow thick-to-thin and thin-to-thick operations. will open an issue to allow this functionality(we can consider this in upcoming releases)

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/issues/2177 to track  thick-to-thin and thin-to-thick operations

**Comment by humblec** [comment]
Agreed. This matrix has to be carefully analysed and fixed and possibly by phase. Its good to seggregate it in different issues :+1:
