### ISSUE TITLE
Allow Creation of Clone and Restore snapshot from thick-to-thin and thin-to-thick

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2177]
This issue is to track the feature support to allow the below operations

* Allow Restore of snapshot from Thick PVC to Thin PVC
* Allow Restore of snapshot from Thin PVC to Thick PVC

Note:- cloning might only be supported if one deleted the thick storageclass and recreates the storageclass with the same name with thick provisioned enabled.

**Comment by nixpanic** [comment]
csi-addons/spec#15 might be an alternative to support moving from thick to thin.

I do not know what a good reason is to use thick-provisioning and then clone thin volumes from it. What is the use-case?
