### ISSUE TITLE
deploy:  unable to pull any image from k8s.gcr.io

### ISSUE THREAD

**Issue by elrondwong** [ceph/ceph-csi#2185]
# Describe the bug #

In China，`k8s.gcr.io` can't be accessed. There are both `k8s.gcr.io/sig-storage/` and `quay.io/cephcsi/` in the following configuration files:

- `deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml`
- `deploy/cephfs/kubernetes/csi-cephfsplugin.yaml`
- `deploy/rbd/kubernetes/csi-rbdplugin.yaml`
- `deploy/rbd/kubernetes/csi-rbdplugin-provisioner.yaml`

Wouldn't it be better if we use `quay.io/cephcsi/ uniformly?

**Comment by Rakshith-R** [comment]
@elrondwong The k8s external provisioner,snapshotter, resizer, etc are maintained at https://github.com/kubernetes-csi.
You file a issue/ check with them for alternative container registry. 
Then replace the respective urls in the yaml files.

**Comment by elrondwong** [comment]
OK, got it, thack you! @Rakshith-R
