### ISSUE TITLE
Use go-ceph for ceph task manager commands

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2186]
Currently, we are using RBD CLI for the below two manager functionalities

* Add task to fatten the rbd image
* Add task to move the image to the trash

go-ceph issue https://github.com/ceph/go-ceph/issues/516 to track the same work. Once go-ceph API's are available we should switch from  CLI to go-ceph

Thanks, @phlogistonjohn for finding this one and opening the go-ceph issue :)

**Comment by phlogistonjohn** [comment]
I don't know how relevant this is to csi but I did recently assign the go-ceph issue to @Rakshith-R  - so take that as you will. :-)

**Comment by Rakshith-R** [comment]
> I don't know how relevant this is to csi but I did recently assign the go-ceph issue to @Rakshith-R  - so take that as you will. :-)

😅yes it's in progress,  I'll re-open this.

**Comment by nixpanic** [comment]
go-ceph v0.12.0 has been released and contains API support for this :partying_face:

**Comment by humblec** [comment]
@Rakshith-R can you please revisit the state and adjust the milestone tracker accordingly?
