### ISSUE TITLE
Can't create PVC using example: DeadlineExceeded

### ISSUE THREAD

**Issue by muhlba91** [ceph/ceph-csi#219]
I have installed a Rook cluster which exposes it's mon on the internal service address, and the files in `deploy/cephfs/kubernetes`. On the node I can mount and write to Ceph when using the credentials used for the CSI plugin and the address `rook-ceph-mon-a.rook-ceph.svc.cluster.local:6790` -> Ceph/Rook is working properly with those credentials and the monitor address.

However, when creating a simple PVC (StorageClass and PVC used from  `examples/cephfs`) the PVC can't get created. Please find the logs attached.
[csi-cephfsplugin-sts-attacher.txt](https://github.com/ceph/ceph-csi/files/2888142/csi-cephfsplugin-sts-attacher.txt)
[csi-cephfsplugin-sts-provisioner-cephfsplugin.txt](https://github.com/ceph/ceph-csi/files/2888143/csi-cephfsplugin-sts-provisioner-cephfsplugin.txt)
[csi-cephfsplugin-sts-provisioner-provisioner.txt](https://github.com/ceph/ceph-csi/files/2888144/csi-cephfsplugin-sts-provisioner-provisioner.txt)
[csi-cephfsplugin-ds-cephfsplugin.txt](https://github.com/ceph/ceph-csi/files/2888145/csi-cephfsplugin-ds-cephfsplugin.txt)
[csi-cephfsplugin-ds-driver-registrar.txt](https://github.com/ceph/ceph-csi/files/2888146/csi-cephfsplugin-ds-driver-registrar.txt)

**Comment by Madhu-1** [comment]
@muhlba91 I think you are hitting  #140, please check  comments  on #140  for more details how to check  whether the  fuse command  is struck

**Comment by Madhu-1** [comment]
for more logs please check the logs of mon pod you are targeting

**Comment by muhlba91** [comment]
ah, thank you. the issue was with the monitor not listening correctly. now it works! :)
