### ISSUE TITLE
Any plans to make CSIIdentifier parsing logic public?

### ISSUE THREAD

**Issue by evindunn** [ceph/ceph-csi#2210]
# Describe the feature you'd like to have #
I'm working on a project that maps k8s volumes to CephFS subvolume paths, and it would be nice to be able to import [CSIIdentifier](https://github.com/ceph/ceph-csi/blob/v3.3.1/internal/util/volid.go) through a Go module instead of reimplementing the parsing logic. I'm new to go modules though, so it's possible there's already a way to do this and I'm missing something.

# What is the value to the end user? (why is it a priority?) #
More of a developer feature. My particular use case is the development of a backup system in which Ceph snapshots are created and cataloged based on PersistentVolumeClaim name.

# How will we know we have a good solution? (acceptance criteria) #
- CSIIdentifier is importable into 3rd-party apps via go modules (moved from `internal/` to somewhere else)
- Maybe there are other exportable utilities that the community would find useful?

# Additional context #
N/A

**Comment by nixpanic** [comment]
We  currently do not have any plans do facilitate this. By placing parts of Ceph-CSI in a public package, we have to maintain compatibility. This is something that we prefer not to need to commit to.

Instead, we can consider features that benefit a broader audience. Would #1086 or similar help you?

**Comment by evindunn** [comment]
@nixpanic #1086 looks perfect. Thanks for the explanation!
