### ISSUE TITLE
resolve exhaustivestruct linter error

### ISSUE THREAD

**Issue by yati1998** [ceph/ceph-csi#2224]
exhaustivestruct is a go static analysis tool to find structs that have uninitialized fields.
For example:
type User struct {
  Name string
  Age int
}

var user = User{ // fails with "Age is missing in User"
  Name: "John",

Related to issue: https://github.com/ceph/ceph-csi/issues/1586

**Comment by yati1998** [comment]
I suggest to disable this linter.
the following has been mentioned in the description of linter too.
`warning This linter is meant to be used only for special cases. It is not recommended to use it for all files in a project.`

What's your thought on this? @Madhu-1 @nixpanic @Yuggupta27

**Comment by Madhu-1** [comment]
am okay with disabling it :+1:

**Comment by Rakshith-R** [comment]
> am okay with disabling it :+1: 

+1 :+1:

**Comment by Yuggupta27** [comment]
> I suggest to disable this linter.
> the following has been mentioned in the description of linter too.
> `warning This linter is meant to be used only for special cases. It is not recommended to use it for all files in a project.`
> 
> What's your thought on this? @Madhu-1 @nixpanic @Yuggupta27 

Sure, We can disable it.
