### ISSUE TITLE
rbd-nbd: thick provisioned volumes support

### ISSUE THREAD

**Issue by pkalever** [ceph/ceph-csi#2237]
# Describe the feature you'd like to have #

Tracker issue to implement the missing bits and qualify thick provisioned volumes backed by the rbd-nbd mounter

Known issues# https://github.com/ceph/ceph-csi/issues/2171

**Comment by pkalever** [comment]
@Madhu-1 @nixpanic can we close this based on https://github.com/ceph/ceph-csi/pull/2589 ?

**Comment by Madhu-1** [comment]
@pkalever Thanks for keeping track of it. yes makes sense to close this one.

**Comment by pkalever** [comment]
Closing this now based on previous discussions above, feel free to reopen if needed. Thanks!
