### ISSUE TITLE
Helm chart does not create secret and storageclass

### ISSUE THREAD

**Issue by kifeo** [ceph/ceph-csi#2255]
# Describe the bug #

when setting in the values.yaml file
storageClass:
  create: true

and 

secret:
  create: true

these are not created on helm install --values as decribed in the README file here 
https://github.com/ceph/ceph-csi/tree/devel/charts/ceph-csi-rbd

# Environment details #

- Helm chart version : 3.3.1

**Comment by Rakshith-R** [comment]
The Readme.md file is yet to be updated with storage class and secret settings.

Please set these options and try again https://github.com/ceph/ceph-csi/blob/853d77d7939cd17b3122f6a9b8a585848fe181a8/charts/ceph-csi-rbd/values.yaml

**Comment by yati1998** [comment]
Sure @kifeo. Will add it to the README file.

**Comment by kifeo** [comment]
Hi @yati1998 , not sure that changing the README will change the behavior ?
I would expect that setting true to secret.create would do it, same for the storageclass

**Comment by yati1998** [comment]
Hey @kifeo. Sorry, I thought you wanted the options to be mentioned in the README file. So JFYI, for now, is set to default values false and if you want, you can set the value true while installing the helm charts.
`helm install --set secret.create=true --set storageClass.create=true` 
and set other configuration that is required.

**Comment by Yuggupta27** [comment]
Hey @kifeo , we recently added this feature in https://github.com/ceph/ceph-csi/pull/1786 
Can you please try the following steps for deploying storage class and secret during installation via helm:

-  `./scripts/install-helm.sh up`
-  `./scripts/install-helm install-cephcsi --namespace "insert namespace" --deploy-sc --deploy-secret`

This should deploy both storageclass and secret for you. Let us know if it doesn't work for you

**Comment by kifeo** [comment]
Please reopen this issue as the merge #2257 does not resolve the situation

**Comment by kifeo** [comment]
@Yuggupta27 the goal would be to use the helm chart deploy the secret and storageclass, as there are these settings available in the values.yaml file

**Comment by Yuggupta27** [comment]
> @Yuggupta27 the goal would be to use the helm chart deploy the secret and storageclass, as there are these settings available in the values.yaml file

Sure, I'll verify the same and get back to you.
