### ISSUE TITLE
CI jobs often fail with minikube error `X Exiting due to GUEST_PROVISION`

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#2264]
# Describe the bug #

When runninc CI jobs, minikube regularly fails with the following error:
```
* Failed to start kvm2 VM. Running "minikube delete" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute

X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute
```

This prevents the job from continuing, and a `/retest ...` is needed.

# Logs #

From [mini-e2e_k8s-1.20/1523](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.20/detail/mini-e2e_k8s-1.20/1523/pipeline):
```
* Creating kvm2 VM (CPUs=8, Memory=14336MB, Disk=20000MB) ...
* Deleting "minikube" in kvm2 ...
! StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute
* Creating kvm2 VM (CPUs=8, Memory=14336MB, Disk=20000MB) ...
* Failed to start kvm2 VM. Running "minikube delete" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute

X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute
```

**Comment by nixpanic** [comment]
https://github.com/ceph/ceph-csi/pull/2343#issuecomment-891825471 failed again ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.19/detail/mini-e2e-helm_k8s-1.19/2298/pipeline))

**Comment by nixpanic** [comment]
https://github.com/ceph/ceph-csi/pull/2308#issuecomment-891856084 failed here too ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.20/detail/mini-e2e_k8s-1.20/1908/pipeline))

**Comment by nixpanic** [comment]
https://github.com/ceph/ceph-csi/pull/2354#issuecomment-892400000 as well ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.20/detail/mini-e2e-helm_k8s-1.20/1902/pipeline/))

**Comment by nixpanic** [comment]
failed in https://github.com/ceph/ceph-csi/pull/2350#issuecomment-892500553 too ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.21/detail/mini-e2e_k8s-1.21/589/pipeline)

**Comment by nixpanic** [comment]
https://github.com/ceph/ceph-csi/pull/2341#issuecomment-892516420 hit this too ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.19/detail/mini-e2e_k8s-1.19/2363/pipeline))

**Comment by Madhu-1** [comment]
@nixpanic as we are hitting frequently is it a good idea to add a wrapper to retry?

**Comment by nixpanic** [comment]
https://github.com/ceph/ceph-csi/pull/2322#issuecomment-892634477 hit this ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.21/detail/mini-e2e_k8s-1.21/608/pipeline))

**Comment by nixpanic** [comment]
> @nixpanic as we are hitting frequently is it a good idea to add a wrapper to retry?

I don't know. There is already an automated retry by minikube. We should try to identify the cause and work on preventing it. Gathering the hostnames of the CentOS CI bare-metal machines might give a clue. Different groups of hosts have different hardware, and are in different subnets (https://wiki.centos.org/QaWiki/PubHardware).

**Comment by nixpanic** [comment]
https://github.com/ceph/ceph-csi/pull/2341#issuecomment-892773815 as well ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/upgrade-tests-cephfs/detail/upgrade-tests-cephfs/2566/pipeline))

**Comment by nixpanic** [comment]
https://github.com/ceph/ceph-csi/pull/2339#issuecomment-892851474 hit this too ([logs](https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/upgrade-tests-cephfs/detail/upgrade-tests-cephfs/2572/pipeline))

**Comment by nixpanic** [comment]
https://github.com/ceph/ceph-csi/pull/2351#issuecomment-893288535 has seen this

**Comment by nixpanic** [comment]
2x even! https://github.com/ceph/ceph-csi/pull/2351#issuecomment-893288932

**Comment by nixpanic** [comment]
backports sometimes hit this too, like https://github.com/ceph/ceph-csi/pull/2369#issuecomment-893454809

**Comment by Madhu-1** [comment]
hit it again https://github.com/ceph/ceph-csi/pull/2374#issuecomment-895014980

**Comment by nixpanic** [comment]
once more https://github.com/ceph/ceph-csi/pull/2376#issuecomment-895195300

**Comment by nixpanic** [comment]
https://github.com/ceph/ceph-csi/pull/2448#issuecomment-908397774 failed too

**Comment by pkalever** [comment]
I don't know if it was by chance or the real workaround, but after generating the ssh keys locally via ssh-keygen it worked now for me for the first time after 20-25 different attempts.

Is this something that we can try?

**Comment by Madhu-1** [comment]
> I don't know if it was by chance or the real workaround, but after generating the ssh keys locally via ssh-keygen it worked now for me for the first time after 20-25 different attempts.
> 
> Is this something that we can try?

Just want to be sure how generating ssh keys will fix this issue?

**Comment by pkalever** [comment]
> > I don't know if it was by chance or the real workaround, but after generating the ssh keys locally via ssh-keygen it worked now for me for the first time after 20-25 different attempts.
> > Is this something that we can try?
> 
> Just want to be sure how generating ssh keys will fix this issue?

Yac! You are right! It doesn't make any sense.

The other thing I tried was 
1. Flushing IP tables locally
2. Disable SELinux

Maybe it worked because of this!

**Comment by pkalever** [comment]
Today I'm hitting this again locally and none of my previous mentioned guess workarounds are working :-(

**Comment by Madhu-1** [comment]
adding minikube logs when this fails might be helpful to see what's happening.

**Comment by Madhu-1** [comment]
```

! StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute

* Creating kvm2 VM (CPUs=8, Memory=14336MB, Disk=32768MB) ...

* Failed to start kvm2 VM. Running "minikube delete" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute



X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute

* 

���                                                                                             ���

���    * If the above advice does not help, please let us know:                                 ���

���      https://github.com/kubernetes/minikube/issues/new/choose                               ���

���                                                                                             ���

���    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    ���

���                                                                                             ���

���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
```

**Comment by nixpanic** [comment]
This is definitely not fixed yet :disappointed:

**Comment by nixpanic** [comment]
Seems like kubernetes/minikube#11459 is reported too.

**Comment by nixpanic** [comment]
This has not happened since a long time.
