### ISSUE TITLE
SELinux-related mount options are silently ignored

### ISSUE THREAD

**Issue by alexcern** [ceph/ceph-csi#2295]
# Describe the bug #

SELinux-related `kernelMountOptions` for a cephfs mount (typically `-o context=...`) are silently ignored.

# Environment details #

- Image/version of Ceph CSI driver : 3.2.1
- Helm chart version : 3.2.1
- Kernel version : 5.10.19-200.fc33.x86_64 (FCOS)
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : cephfs / kernel
- Kubernetes cluster version : 1.20
- Ceph cluster version : ?

# Steps to reproduce #

1. Consider a cephfs volume with existing SELinux labels on files
1. Create cephfs-csi PV with `kernelMountOptions: context=system_u:object_r:container_file_t:s0` (Using kernel mounter; fuse mounter doesn't support SElinux labels on files)
1. Run a pod mounting that PV as `/cephfs`

# Actual results #

`mount` shows something like this:

```
<redacted>:6789,<redacted>:6789,<redacted>:6789:/volumes/_nogroup/8693b026-39af-4c90-af60-1e8290cc3c79 on /cephfs type ceph (rw,relatime,seclabel,name=pvc-db621df2-199d-4c23-b16f-bcc0f06d8b14,secret=<hidden>,acl)
```

Notice the `context` option is missing and we have `seclabel` instead.

In the pod, `ls -lZ /cephfs` shows different SELinux file labels than what we specified in the mount options

# Expected behavior #

The SELinux file labels should be exactly the context specified in the mount options (here `system_u:object_r:container_file_t:s0`)

`mount` should show something like the following, reflecting our mount option:

```
<redacted>:6789,<redacted>:6789,<redacted>:6789:/volumes/_nogroup/8693b026-39af-4c90-af60-1e8290cc3c79 on /cephfs type ceph (rw,relatime,context=system_u:object_r:container_file_t:s0,name=pvc-db621df2-199d-4c23-b16f-bcc0f06d8b14,secret=<hidden>,acl)
```

# Logs #

# Additional context #

AFAICS this happens because `libmount` silently drops selinux-related mount options if it doesn't detect that selinux is enabled: https://github.com/karelzak/util-linux/blob/17fc869/libmount/src/context_mount.c#L291

This detection fails because the host's `/etc/selinux` is not mounted in the csi-cephfsplugin pods. This can be confirmed by running `sestatus` in csi-cephfsplugin pod.

After bind-mounting `/etc/selinux`, `sestatus` works properly and the selinux-related mount options are properly taken into account by `mount`. 

Would it be reasonable to add  `/etc/selinux` to the list of host paths mounted by the csi-cephfsplugin daemonset pods? In this case I'm happy to provide a PR for the Helm chart.

**Comment by humblec** [comment]
@alexcern Thanks for the report! 

One quick question, 

>After bind-mounting /etc/selinux, sestatus works properly and the selinux-related mount options are properly taken into account by mount.
>

In above:, 
did you get a chance to check both node mount and pod mount and verify `contexts` are populated properly ?
also, any permission denials/audit do you see while app access or work on the files inside the volume ? 
does your app pod also carry any `SCC` setting for `selinux` in this case ?


The context population have given some tough time with `permission errors` at time to time, so we have to do some experiment before we enable the `selinux` mount,

**Comment by alexcern** [comment]
Thanks @humblec for pointing out the possible issues. I'll check this in details and come back with answers ASAP.

**Comment by alexcern** [comment]
BTW, I forgot to mention in the issue description that setting a `context` mount option is an attempt to avoid the expensive SELinux relabeling at each container start - https://github.com/kubernetes/kubernetes/issues/69799

Since https://github.com/torvalds/linux/commit/ac6713ccb5a6d13b59a2e3fda4fb049a2c4e0af2 this affects kernel-mounted cephfs

**Comment by alexcern** [comment]
Hi @humblec

I opened #2353 to add support of selinux mount options. In addition to bind-mounting host's `/etc/selinux`, it includes a fix for a code path (in volume option processing) that would ignore `kernelMountOptions`.

@gman0 and myself validated the patch in the following environments:

## Environment using selinux: OKD4.7

- sets pod SCC to `securityContext: { seLinuxOptions: { level: s0:c28,c22 }}` (the level is unique per namespace and the same value is used for all pods in the same namespace)
- uses crio container runtime configured with `selinux = true`
- cephfs kernel mounts are affected by https://github.com/kubernetes/kubernetes/issues/69799
- context of files in cephfs volumes looks like `system_u:system_r:container_t:s0:c22,c28`

Findings:
- no difference observed after deploying the patched cephfs-csi chart and image when no `kernelMountOptions` specified
- the patch makes it possible to specify a selinux context at mount time, e.g. `kernelMountOptions: context=system_u:object_r:cephfs_t:s0`
- with the `context` set in mount options, the whole cephfs filesystem gets the specified context and individual file labels are disabled. This successfully avoids the slow and expensive relabling of each file in the volume at each container start described in https://github.com/kubernetes/kubernetes/issues/69799
- no permission denials/audit visible (whether beforethe patch, after the patch or after the patch with `context` mount option). OKD4.7 nodes run FCOS33, whose default selinux configuration allows unprivileged containers (`system_u:system_r:container_t:s0`) to access files labeled as `system_u:object_r:cephfs_t:s0`
- this `cephfs_t` type is predefined in our systems (FCOS33): AFAICS it was used for cephfs kernel mounts before support for individual file labels was added - and I expect it is still in use in kernels compiled without `CEPH_FS_SECURITY_LABEL`

## Environment not using selinux: Openstack Magnum K8s cluster

- pods do not have a selinux `securityContext`
- uses containerd container runtime configured with `enable_selinux = false`
- thus the containerd runtime ignores file relabeling requests from the kubelet and the cluster is NOT affected by https://github.com/kubernetes/kubernetes/issues/69799

Findings:
- no difference observed after deploying the patched cephfs-csi chart and image, with either fuse or kernel mounter
- no permission denials/audit visible (whether before or after the patch)
- `context` mount option is not useful since the cluster is not affected by https://github.com/kubernetes/kubernetes/issues/69799

**Comment by humblec** [comment]
@alexcern Thanks for the detailed testing report and summary.  
>the patch makes it possible to specify a selinux context at mount time, e.g. kernelMountOptions: context=system_u:object_r:cephfs_t:s0
with the context set in mount options, the whole cephfs filesystem gets the specified context and individual file labels are disabled. 
>

The fix definitely helps!  the part which I am not completely sure here is the practice of explictly setting a specified selinux context at mount (May be this is  a 'usual' practice.) . Indeed it helps in setups and avoid relabelling which has been discovered as an issue which cause the delayed app pod start. 
 
Also, to point out, one other solution I have been thinking here to avoid the selinux relabelling was with mount option `noseclabel` in SC which tells kubelet to avoid looking further on selinux relabelling.

**Comment by alexcern** [comment]
Hi @humblec, thanks for merging this so quickly!

AFAICS `noseclabel` can be used as a filter in `findmnt` but we cannot pass it as an actual option for `mount`. Like `seclabel` itself it looks like an implied option.

We've indeed been looking for the possibility to specify something like a `noseclabel` mount option and the `context` mount option was the closest we could find. I interpret it as "disable `seclabel` and use that specific context instead".

**Comment by humblec** [comment]
> Hi @humblec, thanks for merging this so quickly!
> 

yeah , it went fast  than I expected too :). 
 
> AFAICS `noseclabel` can be used as a filter in `findmnt` but we cannot pass it as an actual option for `mount`. Like `seclabel` itself it looks like an implied option.
>

I did some testing on setting this option in SC and it seems that,  it was a  successful attempt:

This is what it resulted:

```
> SC

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-cephfs
parameters:

  fsName: myfs

  pool: myfs-data0

  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node

reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - noseclabel

> PV Object

  csi:
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      fsName: myfs
      pool: myfs-data0
      storage.kubernetes.io/csiProvisionerIdentity: 1627647990691-8081-rook-ceph.cephfs.csi.ceph.com
      subvolumeName: csi-vol-c338254e-f45b-11eb-a0bb-46c47509a5b7
      subvolumePath: /volumes/csi/csi-vol-c338254e-f45b-11eb-a0bb-46c47509a5b7/ebf90a5c-24d0-471b-8ee8-a41d3123e9ce
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-c338254e-f45b-11eb-a0bb-46c47509a5b7
  mountOptions:
  - noseclabel
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rook-cephfs
  volumeMode: Filesystem
status:
  phase: Bound

> POD

apiVersion: v1
kind: Pod
metadata:
 ..
  name: csicephfs-demo-pod
  namespace: default
 ...
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: web-server
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/www/html
      name: mypvc
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wwr49
      readOnly: true
.........
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}          -----------------------------> [1]
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: cephfs-pvc


> MOUNT

10.70.53.126:6789:/volumes/csi/csi-vol-c338254e-f45b-11eb-a0bb-46c47509a5b7/ebf90a5c-24d0-471b-8ee8-a41d3123e9ce on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f6bf616e-54ac-4b22-82a7-82a135af8096/globalmount type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=myfs,_netdev)
10.70.53.126:6789:/volumes/csi/csi-vol-c338254e-f45b-11eb-a0bb-46c47509a5b7/ebf90a5c-24d0-471b-8ee8-a41d3123e9ce on /var/lib/kubelet/pods/e346c77b-215c-4245-8f7e-c97160d96bd4/volumes/kubernetes.io~csi/pvc-f6bf616e-54ac-4b22-82a7-82a135af8096/mount type ceph (rw,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=myfs,_netdev)
```
As expected, it actually wiped the `seclabel` from the mount. 

This was performed on a kube cluster where SCC from namespace controller is not enforced like Openshift. Not sure what are the other gotchas in place in various permutations and combinations of SCC settings though.

 
> We've indeed been looking for the possibility to specify something like a `noseclabel` mount option and the `context` mount option was the closest we could find. I interpret it as "disable `seclabel` and use that specific context instead".

Sure, it indeed helps, however `enforcing context` is a practice or not is what I have been trying to find out. :)

**Comment by alexcern** [comment]
Interesting... I'm not able to easily reproduce this exact setup with rook but in our current environment (OKD4.7/FCOS33 and Openstack Manila) `noseclabel` is not accepted as a valid mount option:

```
mount: /mnt: wrong fs type, bad option, bad superblock on ***:6789:/volumes/_nogroup/891443d6-b437-4459-9c77-08929f4f5fda, missing codepage or helper program, or other error.
```

`dmesg` shows: 

```
[Tue Aug 10 14:51:18 2021] ceph: Unknown parameter 'noseclabel'
```

However `findmnt --options noseclabel` does work.

**Comment by humblec** [comment]
> Interesting... I'm not able to easily reproduce this exact setup with rook but in our current environment (OKD4.7/FCOS33 and Openstack Manila) `noseclabel` is not accepted as a valid mount option:
> 
> ```
> mount: /mnt: wrong fs type, bad option, bad superblock on ***:6789:/volumes/_nogroup/891443d6-b437-4459-9c77-08929f4f5fda, missing codepage or helper program, or other error.

above looks like a FS issue than mount option issue to me. may be something causing it ? I will check on this though.

When you list the PV object do you see the mountOption there ?

**Comment by leseb** [comment]
@alexcern Can you explain again why is `/etc/selinux` the key to enable the correct detection of selinux being enabled? Quickly glancing at https://github.com/util-linux/util-linux/blob/17fc869/libmount/src/context_mount.c#L291 and further, it looks like most the detection depends on this mountpoint to be present `/sys/fs/selinux` in `is_selinux_enabled`. So I'm a bit confused and would like to understand if I missed anything and what is `/etc/selinux` effectively helping with.

Thanks!

**Comment by alexcern** [comment]
Hi @leseb 

Looks like `is_selinux_enabled` internally does some access check on `/etc/selinux/config`:

https://github.com/SELinuxProject/selinux/blob/d155b410d4bbc90d28f361b966f0429598da8188/libselinux/src/enabled.c#L19
https://github.com/SELinuxProject/selinux/blob/d155b410d4bbc90d28f361b966f0429598da8188/libselinux/src/init.c#L152
https://github.com/SELinuxProject/selinux/blob/d155b410d4bbc90d28f361b966f0429598da8188/libselinux/src/selinux_internal.h#L73-L74

**Comment by leseb** [comment]
> Hi @leseb
> 
> Looks like `is_selinux_enabled` internally does some access check on `/etc/selinux/config`:
> 
> https://github.com/SELinuxProject/selinux/blob/d155b410d4bbc90d28f361b966f0429598da8188/libselinux/src/enabled.c#L19 https://github.com/SELinuxProject/selinux/blob/d155b410d4bbc90d28f361b966f0429598da8188/libselinux/src/init.c#L152 https://github.com/SELinuxProject/selinux/blob/d155b410d4bbc90d28f361b966f0429598da8188/libselinux/src/selinux_internal.h#L73-L74

Thanks for the prompt response!

**Comment by ItayRingler** [comment]
Hi all, I have a question that is very much related to this solved issue. We have in production volumes used with csi-cephfs chart 3.4, before the fix for this issue was implemented (I guess before the backport too). So for me, when multiple pods access the same volume, only the newest pod will access to the mountpoint. The rest of them get 'Permission denied' with the exact same symptoms like in the description of this issue.
I've tested and when having the 'kernelMountOptions: context=system_u:object_r:container_file_t:s0' option enabled in the csi-cephfs storageClass, and creating new PVs - everything works fine.
My question is about **existing PVs**. Is there a way of making a work-around to apply the SElinux context on the existing PV? I want the customer to have the option to fix the issue without losing all the data. 

Currently the only working option in my eyes is snapshot backup & restore, which I don't really like for this case.

**Comment by alexcern** [comment]
> Is there a way of making a work-around to apply the SElinux context on the existing PV? 

We used something like the following, but our cephfs PVs are provisioned by the Openstack Manila CSI driver rather than the ceph CSI driver directly so it may need to be adjusted. The operation didn't affect running pods mounting the PV.

```bash
kubectl get pv my-cephfs-pv -o json | jq '.spec.csi.volumeAttributes.kernelMountOptions="noatime,context=system_u:object_r:cephfs_t:s0"' > /tmp/pv.json
kubectl delete -f /tmp/pv.json --wait=false
# PV now stuck in Terminating state waiting for PVC deletion...
kubectl patch -f /tmp/pv.json --type json -p '[{"op":"remove","path":"/metadata/finalizers"}]'
# PV gone, PVC still there with status Lost
# recreate PV
kubectl create -f /tmp/pv.json
# NB: PVC takes some time to be bound again.
```
