### ISSUE TITLE
Is there a way to specify rbd pool namespace?

### ISSUE THREAD

**Issue by AmazingPangWei** [ceph/ceph-csi#2303]
# Describe the feature you'd like to have #

I've read this [doc](https://github.com/ceph/ceph-csi/blob/devel/docs/deploy-rbd.md#configuration)，but I still don't know how to specify a rbd pool namespace for a image like this `rbd create --pool my_pool --namespace my_ns`. Did I miss something?

**Comment by Rakshith-R** [comment]
hey @AmazingPangWei , 
Currently, rados namespace setting for rbd images is present in [csi-config-map-sample.yaml](https://github.com/ceph/ceph-csi/blob/devel/examples/csi-config-map-sample.yaml). 
It is not configurable via storageclass.

**Comment by AmazingPangWei** [comment]
@Rakshith-R Thank you so much, I'll try this.

**Comment by yati1998** [comment]
@AmazingPangWei let us know if you have resolved this issue and if we can close it?

**Comment by AmazingPangWei** [comment]
Sorry to reply so late. My issue has been resolved. I will close this issue.
