### ISSUE TITLE
e2e CI jobs should retry to create the deployment namespace

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#2309]
# Describe the bug #

e2e tests sometimes fail to create the namespace where Ceph-CSI will be deployed. When this happens, the tests will not start to run at all.

The output will look like
```
+ ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@n27.dusty.ci.centos.org 'kubectl create namespace '\''cephcsi-e2e-1f346f7c7e38'\'''
Warning: Permanently added 'n27.dusty.ci.centos.org,172.19.2.91' (ECDSA) to the list of known hosts.
Error from server: etcdserver: request timed out
```

# Expected behavior #

`etcdserver: request timed out` is a common failure where a retry can work later on. The CI script that creates the Kubernetes Namespace should have a way to retry in case of a failure.

https://github.com/ceph/ceph-csi/blob/c90023ad5d9ebf30a06f3e9fd7534aa74be60a24/mini-e2e-helm.groovy#L178

# Logs #

See https://github.com/ceph/ceph-csi/pull/2277#issuecomment-883447903

**Comment by Rakshith-R** [comment]
Merging https://github.com/ceph/ceph-csi/pull/2378 should have closed this issue(auto-close does not work across branches ?).
Anyway this has been addressed and can now be closed. 
Thanks !
