### ISSUE TITLE
Release 3.4.1 plan and milestones.

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2319]
# Describe the bug #

Issue to track next minor release of `3.4.0` series:

The idea here is to capture the wishlist from Ceph CSI community which they would like to see in this release. We could capture this in a google doc or in form of comments on the issue. However the format should not be a blocker for capturing this info, thus tracking it for the next release.

[update] Wish list:

https://hackmd.io/8OqCr1mrTMGtBcJ7XNdDBg?view

**Comment by humblec** [comment]
@Yuggupta27 thanks for volunteering as the release owner for 3.4.1 :+1: , so please take it forward wrt to release items sorting, sprint plan, board management...etc..

**Comment by Madhu-1** [comment]
Project board for 3.4.1 https://github.com/ceph/ceph-csi/projects/15

**Comment by Yuggupta27** [comment]
> @Yuggupta27 thanks for volunteering as the release owner for 3.4.1  , so please take it forward wrt to release items sorting, sprint plan, board management...etc..

My pleasure :) Will do the needful.
Thanks @Madhu-1 for sharing the project board :+1:
