### ISSUE TITLE
3.5.0 planning and release discussions

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2321]
# Describe the bug #

Issue to track next major release 3.5.0:

The idea here is to capture the wishlist from Ceph CSI community which they would like to see in this release. We could capture this in a google doc or in form of comments on the issue. However the format should not be a blocker for capturing this info, thus tracking it for the next release.

[update] Wish list:

https://hackmd.io/8OqCr1mrTMGtBcJ7XNdDBg?view

**Comment by humblec** [comment]
Considering this release is going to be the base for Rook 1.8 and other product releases, we have to come up with the possible dates for code freeze and release. I have started cleaning up the milestone linked issues, however appreciated if we all can help on the process.

**Comment by humblec** [comment]
> Considering this release is going to be the base for Rook 1.8 and other product releases, we have to come up with the possible dates for code freeze and release. I have started cleaning up the milestone linked issues, however appreciated if we all can help on the process.

Cc @ceph/ceph-csi-maintainers  @ceph/ceph-csi-contributors 

I would like to propose below dates for this release

Code Freeze: 
```
Dec 01- Code Freeze
Dec 06 - GA
```
Can you share your views ? once we decided we can work towards the same.

**Comment by Madhu-1** [comment]
IMHO these are not realistic dates. below is my proposal

Dec 24- Code Freeze
Dec 30 - GA

**Comment by Rakshith-R** [comment]
> IMHO these are not realistic dates. below is my proposal
> 
> Dec 24- Code 
> Freeze Dec 30 - GA

I agree with madhu's proposed dates. 
+ We need atleast 3 servers to be implemented (1 for fencing, 1 for each controller & node space reclaim operation), for both of  which even the spec is not completed yet.
+ There is no design doc for ibm hpcs encryption to begin with yet. 

1 week for all of the above is indeed very unrealistic.

**Comment by humblec** [comment]
> > IMHO these are not realistic dates. below is my proposal
> > Dec 24- Code
> > Freeze Dec 30 - GA
> 
> I agree with madhu's proposed dates.
> 
>     * We need atleast 3 servers to be implemented (1 for fencing, 1 for each controller & node space reclaim operation), for both of  which even the spec is not completed yet.
> 
>     * There is no design doc for ibm hpcs encryption to begin with yet.
> 
> 
> 1 week for all of the above is indeed very unrealistic.

@Rakshith-R Please populate the "tracker issues" and set "milestones"...etc for the  release tracking soon after things are in plan ateast! , so that we can come up with reaslistic dates.. I see HPCS in the milestone but nothing on other feature you pointed out here. Also this issue or the wish list was/is empty till now and it is difficult to plan the release without that.    

We can work on the possible dates, however the dependency to other projects also has to validated..

**Comment by humblec** [comment]
As discussed marking below dates for 3.5 release.

Code Freeze : 31 -Dec- 2021
GA                : 04-01-2022

**Comment by humblec** [comment]
Looks like most of the PRs tracked for 3.5 release has been merged. A couple of them ( ex: fencing) is yet to be merged though.

@ceph/ceph-csi-maintainers are we good to wrap this release may be tomorrow ? 

Otherwise we have to postpone it a week more and catch up with rook 1.8.3 . wdyt?

**Comment by humblec** [comment]
As discussed, we will try to wrap this release in a couple of days time. May be early next week .

**Comment by Madhu-1** [comment]
closing this one as 3.5.0 is already released
