### ISSUE TITLE
Remove clusterID mapping from the PV annotation

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2328]
we have added clusterID mapping to identify the volumes in case of a failover in Diaster recovery in https://github.com/ceph/ceph-csi/pull/1946. with https://github.com/ceph/ceph-csi/pull/2314 we are moving to a configuration in configmap for clusterID and poolID mapping. and with #2314 we have  all the required information to  identify the image  mappings and the workaround implementation in #1946  can be removed 

some discussion at https://github.com/ceph/ceph-csi/pull/2314#discussion_r677258041

**Comment by Rakshith-R** [comment]
This is still a TODO for v3.5.
