### ISSUE TITLE
Pod anti-affinity breaks upgrades

### ISSUE THREAD

**Issue by p-v-a** [ceph/ceph-csi#2335]
I have tired to upgrade ceph chars from 3.3.0 to 3.4.0 and ended up in a inconsistent state, with a new 3.4.0 pod in the pending state due to https://github.com/ceph/ceph-csi/blob/d3beaeb014fbc3a7f605054ab03006d127ac0430/charts/ceph-csi-rbd/templates/provisioner-deployment.yaml#L28-L42

In my case I have 3 workers and 3 replicas of ceph-provisioners, this leaves no node to start a new pod, as anti-affinity rules above prevents pod starting.
`
Selector:               app=ceph-csi-rbd,component=provisioner,release=ceph-csi-rbd
Replicas:               3 desired | 1 updated | 4 total | 3 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
`

**Comment by yati1998** [comment]
@Yuggupta27  can you have a look into this?

**Comment by fad3t** [comment]
Same issue here.
As a workaround, it's possible to delete one pod at a time (from the previous deployment) to let the new ones start.

**Comment by p-v-a** [comment]
Probably the best option in this case would be to add Release Version key to matchExpressions. This would allow multiple pods from different release versions to coexists on the same host while upgrade is running. This way Helm would be able to complete upgrade using RollingUpgrade strategy. This can be done by overwriting podAffinity rules via .Values.provisioner.affinity, but this is not ideal.

Unfortunately there is no other upgrade strategy that would work, re-create would kill all pods, and recreate them all at once, probably not an ideal.

Another option would be to set pod.spec.strategy.rollingUpdate.maxUnavailable to something like 50%, because default 25% wouldn't result in 0 pods terminating from the old replicaSet if replica is only 3. (see https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-unavailable)

**Comment by p-v-a** [comment]
> Same issue here.
> As a workaround, it's possible to delete one pod at a time (from the previous deployment) to let the new ones start.

That's what I did to rectify this issue, but K8S should be able to manage this automatically if configured correctly.

**Comment by fad3t** [comment]
> 
> 
> > Same issue here.
> > As a workaround, it's possible to delete one pod at a time (from the previous deployment) to let the new ones start.
> 
> That's what I did to rectify this issue, but K8S should be able to manage this automatically if configured correctly.

Agreed, I was just mentioning it so people facing the same problem have an immediate solution until the Helm chart gets updated ;)

**Comment by Yuggupta27** [comment]
Thanks for reaching out @p-v-a @fad3t, are you facing this issue in upgrade only for an upgrade from v3.3 to v3.4? Or is it the same with all the other releases too?

**Comment by fad3t** [comment]
> 
> 
> Thanks for reaching out @p-v-a @fad3t, are you facing this issue in upgrade only for an upgrade from v3.3 to v3.4? Or is it the same with all the other releases too?

In my case, that was an upgrade from v3.1.0 to v3.3.1.

**Comment by Yuggupta27** [comment]
Thanks for confirming @fad3t ! Seems like updating the rolling update strategy to set maxUnavailable to 50% can be a good solution for the issue, and we can also make it configurable. Will send a PR to fix the same shortly :+1:
