### ISSUE TITLE
Csi-provisioner can't dynamic create PersistentVolume after PVC created。false image features: [layering] mounter: rbd

### ISSUE THREAD

**Issue by dc-weizhenhua** [ceph/ceph-csi#2336]
### My environment:
ceph:  ceph version 15.2.13 (c44bc49e7a57a87d84dfff2a077a2058aa2172e2) octopus (stable)
native k8s: 1.21.0  1master; 3 worker nodes, all nodes have installed ceph-common;
ceph-csi: v3.4.0 release

### Here is more info:
note: All pods are deployed in ns default;

[root@master kubernetes]# **ceph mon dump**
dumped monmap epoch 3
epoch 3
fsid dd7ed546-eefb-11eb-baa5-000c29b8c9e9
last_changed 2021-07-27T17:45:05.817398+0000
created 2021-07-27T16:58:35.806004+0000
min_mon_release 15 (octopus)
0: [v2:192.168.6.149:3300/0,v1:192.168.6.149:6789/0] mon.ceph01
1: [v2:192.168.6.157:3300/0,v1:192.168.6.157:6789/0] mon.ceph02
2: [v2:192.168.6.158:3300/0,v1:192.168.6.158:6789/0] mon.ceph03

[root@master kubernetes]# **ceph osd lspools**         
1 device_health_metrics
2 kubernetes
3 csi-pool
[root@master kubernetes]# ceph auth get client.kubernetes
exported keyring for client.kubernetes
[client.kubernetes]
        key = AQBrSABhPHWbCBAAeYlPWBymTAU2ehcPhr90XA==
        caps mgr = "profile rbd pool=kubernetes"
        caps mon = "profile rbd"
        caps osd = "profile rbd pool=kubernetes"

**I comment ‘kmp’ in csi-rbdplugin*.yml,** like this:
  #- name: ceph-csi-encryption-kms-config
            #  mountPath: /etc/ceph-csi-encryption-kms-config/
        #- name: ceph-csi-encryption-kms-config
        #  configMap:
        #    name: ceph-csi-encryption-kms-config

**configmap:**
[root@master kubernetes]# cat csi-config-map.yaml 
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "dd7ed546-eefb-11eb-baa5-000c29b8c9e9",
        "monitors": [
          "192.168.6.149:6789",
          "192.168.6.157:6789",
          "192.168.6.158:6789"
        ]
      } 
    ]
metadata:
  name: ceph-csi-config

**secret:**
[root@master kubernetes]# cat csi-rbd-secret.yaml 
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: default
stringData:
  userID: kubernetes
  userKey: AQBrSABhPHWbCBAAeYlPWBymTAU2ehcPhr90XA==

[root@master kubernetes]# kubectl get pods 
NAME                                        READY   STATUS    RESTARTS   AGE
csi-rbdplugin-5kwvm                         3/3     Running   0          13m
csi-rbdplugin-7tftc                         3/3     Running   0          13m
csi-rbdplugin-provisioner-5c7d9c94d-77m5j   7/7     Running   0          13m
csi-rbdplugin-provisioner-5c7d9c94d-mv274   7/7     Running   0          13m
csi-rbdplugin-provisioner-5c7d9c94d-nqvcj   7/7     Running   0          13m
csi-rbdplugin-tjsmg                         3/3     Running   0          13m
pod-with-raw-block-volume                   1/1     Running   0          20h

**storageclass:**
[root@master kubernetes]# grep -v '#' storageclass.yaml   
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-rbd-sc
provisioner: rbd.csi.ceph.com
parameters:
   clusterID: "dd7ed546-eefb-11eb-baa5-000c29b8c9e9"
   pool: kubernetes
   thickProvision: "false"
   imageFeatures: layering
   csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
   csi.storage.k8s.io/provisioner-secret-namespace: default
   csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
   csi.storage.k8s.io/controller-expand-secret-namespace: default
   csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
   csi.storage.k8s.io/node-stage-secret-namespace: default
   csi.storage.k8s.io/fstype: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
      - discard

**PersistentVolumeClaim:**
[root@master kubernetes]# cat pvc.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-rbd-sc

### Error：rbd-pvc is pending!!!!!!!
[root@master kubernetes]# **kubectl describe pvc rbd-pvc** 
Name:          rbd-pvc
Namespace:     default
StorageClass:  csi-rbd-sc
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: rbd.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age                   From                                                                                             Message
  Warning  ProvisioningFailed    14m                   rbd.csi.ceph.com_csi-rbdplugin-provisioner-5c7d9c94d-77m5j_cea0307a-246c-43f1-9e1b-220260d2d3ad  failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Normal   ExternalProvisioning  2m12s (x63 over 17m)  persistentvolume-controller                                                                      waiting for a volume to be created, either by external provisioner "rbd.csi.ceph.com" or manually created by system administrator
  Normal   Provisioning          76s (x13 over 17m)    rbd.csi.ceph.com_csi-rbdplugin-provisioner-5c7d9c94d-77m5j_cea0307a-246c-43f1-9e1b-220260d2d3ad  External provisioner is provisioning volume for claim "default/rbd-pvc"
  Warning  ProvisioningFailed    76s (x12 over 14m)    rbd.csi.ceph.com_csi-rbdplugin-provisioner-5c7d9c94d-77m5j_cea0307a-246c-43f1-9e1b-220260d2d3ad  failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-f10f053c-955e-44ee-bb5f-d4f2f8c9a62a already exists

**Logs of csi-provisioner:** 
[root@master kubernetes]# kubectl logs csi-rbdplugin-provisioner-5c7d9c94d-77m5j -c csi-rbdplugin
I0729 19:09:35.307335       1 utils.go:180] ID: 44 GRPC request: {}
I0729 19:09:35.307353       1 utils.go:187] ID: 44 GRPC response: {}
I0729 19:10:05.223596       1 utils.go:176] ID: 45 Req-ID: pvc-f10f053c-955e-44ee-bb5f-d4f2f8c9a62a GRPC call: /csi.v1.Controller/CreateVolume
I0729 19:10:05.223737       1 utils.go:180] ID: 45 Req-ID: pvc-f10f053c-955e-44ee-bb5f-d4f2f8c9a62a GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-f10f053c-955e-44ee-bb5f-d4f2f8c9a62a","parameters":{"clusterID":"dd7ed546-eefb-11eb-baa5-000c29b8c9e9","csi.storage.k8s.io/pv/name":"pvc-f10f053c-955e-44ee-bb5f-d4f2f8c9a62a","csi.storage.k8s.io/pvc/name":"rbd-pvc","csi.storage.k8s.io/pvc/namespace":"default","imageFeatures":"layering","pool":"kubernetes","thickProvision":"false"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["discard"]}},"access_mode":{"mode":1}}]}
I0729 19:10:05.223993       1 rbd_util.go:1098] ID: 45 Req-ID: pvc-f10f053c-955e-44ee-bb5f-d4f2f8c9a62a setting disableInUseChecks: false image features: [layering] mounter: rbd
E0729 19:10:05.224019       1 controllerserver.go:288] ID: 45 Req-ID: pvc-f10f053c-955e-44ee-bb5f-d4f2f8c9a62a an operation with the given Volume ID pvc-f10f053c-955e-44ee-bb5f-d4f2f8c9a62a already exists
E0729 19:10:05.224049       1 utils.go:185] ID: 45 Req-ID: pvc-f10f053c-955e-44ee-bb5f-d4f2f8c9a62a GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-f10f053c-955e-44ee-bb5f-d4f2f8c9a62a already exists
I0729 19:10:35.307318       1 utils.go:176] ID: 46 GRPC call: /csi.v1.Identity/Probe
I0729 19:10:35.307356       1 utils.go:180] ID: 46 GRPC request: {}

**Comment by Rakshith-R** [comment]
> [root@master kubernetes]# ceph auth get client.kubernetes
> exported keyring for client.kubernetes
> [client.kubernetes]
> key = AQBrSABhPHWbCBAAeYlPWBymTAU2ehcPhr90XA==
> caps mgr = "profile rbd pool=kubernetes"
> caps mon = "profile rbd"
> caps osd = "profile rbd pool=kubernetes"

hey @dc-weizhenhua ,  ceph capabilities need some tweaks,please take a look at [capabilities.md ](https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#capabilities-of-a-user-required-for-ceph-csi-in-a-ceph-cluster) and try again.

**Comment by dc-weizhenhua** [comment]
> > [root@master kubernetes]# ceph auth get client.kubernetes
> > exported keyring for client.kubernetes
> > [client.kubernetes]
> > key = AQBrSABhPHWbCBAAeYlPWBymTAU2ehcPhr90XA==
> > caps mgr = "profile rbd pool=kubernetes"
> > caps mon = "profile rbd"
> > caps osd = "profile rbd pool=kubernetes"
> 
> hey @dc-weizhenhua , ceph capabilities need some tweaks,please take a look at [capabilities.md ](https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#capabilities-of-a-user-required-for-ceph-csi-in-a-ceph-cluster) and try again.

Thanks for you reply!
I'v tried update auth:  ceph auth caps client.kubernetes mon 'profile rbd' mgr 'allow rw' osd 'profile rbd'; &&  re-create pvc; Pvc is still pending and the error is the same;
[root@master kubernetes]# ceph auth get client.kubernetes
exported keyring for client.kubernetes
[client.kubernetes]
        key = AQBrSABhPHWbCBAAeYlPWBymTAU2ehcPhr90XA==
        caps mgr = "allow rw"
        caps mon = "profile rbd"
        caps osd = "profile rbd"

**Comment by Rakshith-R** [comment]
@dc-weizhenhua , can you check the following issue https://github.com/ceph/ceph-csi/issues/2301 and follow the debugging steps mentioned there.

- check mon ip is accessible from csi pods
- cluster, pool health
- try executing rbd, ceph, osd cmds manually inside csi pods

**Comment by dc-weizhenhua** [comment]
> @dc-weizhenhua , can you check the following issue #2301 and follow the debugging steps mentioned there.
> 
> * check mon ip is accessible from csi pods
> * cluster, pool health
> * try executing rbd, ceph, osd cmds manually inside csi pods

hey,@Rakshith-R，I just follow the debugging and login csi-rbdplugin；I found there is no route to  ceph-mon, the ceph-conf is not correct, and the version of ceph-common is not the same to ceph node;    How should I do to troubleshooting: my  k8s pod network plugin is CALICO. 

[root@csi-rbdplugin-provisioner-5c7d9c94d-8v5sn /]# cat /etc/ceph-csi-config/config.json 
[
  {
    "clusterID": "dd7ed546-eefb-11eb-baa5-000c29b8c9e9",
    "monitors": [
      "192.168.6.149:6789",
      "192.168.6.157:6789",
      "192.168.6.158:6789"
    ]
  } 
]

[root@csi-rbdplugin-provisioner-5c7d9c94d-8v5sn /]# ls /etc/ceph
ceph.conf  keyring  rbdmap
[root@csi-rbdplugin-provisioner-5c7d9c94d-8v5sn /]# cat /etc/ceph/keyring 
[root@csi-rbdplugin-provisioner-5c7d9c94d-8v5sn /]# ip a 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if21: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 02:71:17:84:f5:7d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.18.146/32 brd 192.168.18.146 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::71:17ff:fe84:f57d/64 scope link 
       valid_lft forever preferred_lft forever

[root@csi-rbdplugin-provisioner-5c7d9c94d-8v5sn /]# ceph status
unable to get monitor info from DNS SRV with service name: ceph-mon
[errno 2] RADOS object not found (error connecting to the cluster)
[root@csi-rbdplugin-provisioner-5c7d9c94d-8v5sn /]# ping 192.168.6.149
PING 192.168.6.149 (192.168.6.149) 56(84) bytes of data.
 192.168.6.149 ping statistics
8 packets transmitted, 0 received, 100% packet loss, time 7000ms

[root@csi-rbdplugin-provisioner-5c7d9c94d-8v5sn /]# ip route
default via 169.254.1.1 dev eth0 
169.254.1.1 dev eth0 scope link 
[root@csi-rbdplugin-provisioner-5c7d9c94d-8v5sn /]# cat /etc/ceph/ceph.conf
[global]
auth_cluster_required = cephx
auth_service_required = cephx
auth_client_required = cephx
fuse_set_user_groups = false
fuse_big_writes = true

[root@csi-rbdplugin-provisioner-5c7d9c94d-8v5sn /]# rpm -q ceph-common
ceph-common-16.2.5-0.el8.x86_64

**Comment by Rakshith-R** [comment]
> I just follow the debugging and login csi-rbdplugin；I found there is no route to ceph-mon, 

@dc-weizhenhua You have to setup network between csi pods and ceph cluster. Where's the ceph cluster running ?

>the ceph-conf is not correct,

This is created by ceph csi internally.

> and the version of ceph-common is not the same to ceph

You can try a lower ceph csi version if you want ceph base image version to be the same( but it should not matter much here).

**Comment by nixpanic** [comment]
This problem looks very much the same as [RHBZ#1986794](https://bugzilla.redhat.com/show_bug.cgi?id=1986794), which I am looking into at the moment too.

**Comment by dc-weizhenhua** [comment]
> > I just follow the debugging and login csi-rbdplugin；I found there is no route to ceph-mon,
> 
> @dc-weizhenhua You have to setup network between csi pods and ceph cluster. Where's the ceph cluster running ?
> 
> > the ceph-conf is not correct,
> 
> This is created by ceph csi internally.
> 
> > and the version of ceph-common is not the same to ceph
> 
> You can try a lower ceph csi version if you want ceph base image version to be the same( but it should not matter much here).

@Rakshith-R The ceph cluster is another 3vms; The mon public_network is 192.168.6.0/24;   the k8s cluster network  as follow:
[root@master rbd-csi]# ip a 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:e3:2b:ac brd ff:ff:ff:ff:ff:ff
    inet 192.168.6.130/24 brd 192.168.6.255 scope global noprefixroute dynamic ens33
       valid_lft 1523sec preferred_lft 1523sec
    inet6 fe80::386:b18a:eae9:7053/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: ens38: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:e3:2b:b6 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.122/24 brd 192.168.1.255 scope global noprefixroute dynamic ens38
       valid_lft 29618sec preferred_lft 29618sec
    inet6 fe80::f62:8752:ce7a:ebf4/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:d5:1f:f1:fb brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
5: calib027ccaff59@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
6: vxlan.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether 66:6b:c4:db:fa:cf brd ff:ff:ff:ff:ff:ff
    inet 192.168.204.64/32 scope global vxlan.calico
       valid_lft forever preferred_lft forever
    inet6 fe80::646b:c4ff:fedb:facf/64 scope link 
       valid_lft forever preferred_lft forever
7: cali4039a05a845@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
8: cali066d81df4e0@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever


[root@master rbd-csi]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

192.168.6.130 master.example.com master
192.168.6.154 k8snode01.example.com k8snode01
192.168.6.155 k8snode02.example.com k8snode02
192.168.6.156 k8snode03.example.com k8snode03

**Comment by dc-weizhenhua** [comment]
@Rakshith-R  @nixpanic  
Thank you very much!  I figured out the issue: The reason is there is no ip-route to the ceph-cluster，When i change the calico network-mode to CrossSubnet, I successfully ping ceph-mon and  pv is created dynamicly

[root@csi-rbdplugin-provisioner-5c7d9c94d-6hh6d /]# ping 192.168.6.149
PING 192.168.6.149 (192.168.6.149) 56(84) bytes of data.
64 bytes from 192.168.6.149: icmp_seq=1 ttl=63 time=1.18 ms
64 bytes from 192.168.6.149: icmp_seq=2 ttl=63 time=0.389 ms
64 bytes from 192.168.6.149: icmp_seq=3 ttl=63 time=0.314 ms 

[root@csi-rbdplugin-provisioner-5c7d9c94d-6hh6d /]# ceph osd lspools \
> -m=192.168.6.149:6789,192.168.6.157:6789,192.168.6.158:6789 --id=kubernetes \
> --key=AQBrSABhPHWbCBAAeYlPWBymTAU2ehcPhr90XA==
1 device_health_metrics
2 kubernetes
3 csi-pool

[root@master kubernetes]# kubectl get pvc
NAME       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
rbd-pvc    Bound    pvc-a46da726-b2a2-40e3-9f49-b1efc1f1fda9   1Gi        RWO            csi-rbd-sc     26s
test-pvc   Bound    test-pv                                    2Gi        RWO                           3d2h
[root@master kubernetes]# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM              STORAGECLASS   REASON   AGE
pvc-a46da726-b2a2-40e3-9f49-b1efc1f1fda9   1Gi        RWO            Delete           Bound    default/rbd-pvc    csi-rbd-sc              8m9s

**Comment by Rakshith-R** [comment]
@dc-weizhenhua , Glad to hear that its working ! :smiley:  
Please feel free to close the issue if you are satisfied.

**Comment by dc-weizhenhua** [comment]
> @dc-weizhenhua , Glad to hear that its working ! 😃
> Please feel free to close the issue if you are satisfied.

Thanks a lot! Appreciate!

**Comment by dc-weizhenhua** [comment]
@Rakshith-R Thanks a lot! It works.
