### ISSUE TITLE
Upgrade from CSI v3.2.1 -> v3.4.0 requires explicitly setting imageFeatures, and does not allow exclusive-lock

### ISSUE THREAD

**Issue by gpl** [ceph/ceph-csi#2344]
# Describe the bug #

(I'm not sure if this is really a bug report rather than a feature request, but:)

With ceph-csi v3.4.0 it looks like imageFeature is now required and not documented when creating a PVC.  It looks like previously, the images were created with the following features: 

`deep-flatten exclusive-lock fast-diff layering object-map`

We attached the following line to our storageclasses with `kubectl replace -f storageclass.yaml --force`

`imageFeatures: exclusive-lock,layering,fast-diff,object-map`

Additionally, when trying to specify the following image features for krbd, we now see the following issues:

> failed to provision volume with StorageClass "<>": rpc error: code = InvalidArgument desc = feature exclusive-lock requires rbd-nbd for mounter

Previously, we were using v3.2.1 which didn't have these additional checks.  

# Environment details #

- Image/version of Ceph CSI driver : 3.4.0
- Helm chart version : 3.4.0
- Kernel version : 5.10.40
- Mounter used for mounting PVC (for cephfs its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : krbd
- Kubernetes cluster version : 1.21.3
- Ceph cluster version : v15

# Expected behavior #

We would like to stick to the same set of image features as in v3.2.1, but it looks like v.3.4.0 has added some additional logic that now prevents using exclusive lock -- I tried going through a few issues and PRs but couldn't figure out why this was done, is this workflow no longer supported?

**Comment by Madhu-1** [comment]
@gpl `layering` was the only imageFeature supported in v3.2.1 https://github.com/ceph/ceph-csi/blob/bf0cc103228d54bcced0d76fc363ee1806484b32/examples/rbd/storageclass.yaml#L32-L34. there was a bug in cephcsi where we are not validating the image features. This is fixed in v3.4.0 as we are supporting imagefeatures mentioned  at https://github.com/ceph/ceph-csi/blob/94ef181bc866c8ccaf507de66f213b26608309ff/examples/rbd/storageclass.yaml#L35-L39

**Comment by gpl** [comment]
I see -- I have a lot of images created with `deep-flatten exclusive-lock fast-diff layering object-map`.  

Do I need to disable the features retroactively to upgrade to newer versions of ceph-csi?

Additionally, the images work fine for me -- was there any reason why these features were disabled?

**Comment by Madhu-1** [comment]
> I see -- I have a lot of images created with `deep-flatten exclusive-lock fast-diff layering object-map`.
> 
> Do I need to disable the features retroactively to upgrade to newer versions of ceph-csi?
> 
Yes you can disable all the features except `layering` for PVC and `deep-flatten` for PVC clone and snapshots restores.

> Additionally, the images work fine for me -- was there any reason why these features were disabled?

All the imageFeatures not well tested from the cephcsi side to make sure everything works when mount PVC, creating clones, snapshots etc. we are enabling features one by one based on the feature requests by  users.

**Comment by humblec** [comment]
@gpl hope above response answer your queries, if you have any further queries, please feel free to reopen this issue. thanks :+1:
