### ISSUE TITLE
Support Service account token for Ceph CSI driver

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2345]
# Describe the feature you'd like to have #

Currently, the CSI drivers acquire service account tokens is to directly read the token in the file system. However, this approach has drawbacks like : It will not work for csi drivers which run as a different non-root user than the pods.   CSI driver will have access to the secrets of pods that do not use it because the CSI driver should have a hostPath volume for the pods subdirectory to read the token.  The audience of the token is defaulted to kube apiserver, The token is not guaranteed to be available..
CSI service account token address these issues.  

This issue tracks this new feature support in Ceph CSI.

Additional info about the feature:

This feature allows CSI drivers to impersonate the pods that they mount the volumes for. This improves the security posture in the mounting process where the volumes are ACL’ed on the pods’ service account without handing out unnecessary permissions to the CSI drivers’ service account. This feature is especially important for secret-handling CSI drivers. Since these tokens can be rotated and short-lived, this feature also provides a knob for CSI drivers to receive NodePublishVolume RPC calls periodically with the new token. This knob is also useful when volumes are short-lived, e.g. certificates.

The CSI Driver object need to be expanded with TokenRequest:

For ex:

```
type CSIDriverSpec struct {
    ... // existing fields

    RequiresRepublish *bool
    TokenRequests []TokenRequest
}

type TokenRequest struct {
    Audience string
    ExpirationSeconds *int64
}

```
The interesting configuration here is the `RequiresRepublish` configuration, which is only set when the mounted volumes by the CSI driver have TTL and require re-validation on the token.

The general workflow looks like this :
```
    Before NodePublishVolume call, kubelet will request token from TokenRequest api with audiences=['vault'].
    The token will be specified in VolumeContext to NodePublishVolume call.
    Every 0.1 second, the reconciler component of volume manager will remount the volume in case the vault secrets expire and re-login is required.
```

Additional Details:
https://kubernetes-csi.github.io/docs/token-requests.html

Considering this feature has been GAd in kube 1.22,  its good to support this feature from Ceph CSI driver too. 

WIP:  design/implementation PR

**Comment by nixpanic** [comment]
Could you elaborate a little more on these points?

> It will not work for csi drivers which run as a different non-root user than the pods.

Ceph-CSI only has a single executable running in the container, and it should have access to the ServiceAccount/token which get automatically mapped under the default `/var/run/secrets/kubernetes.io/serviceaccount/token` path. Do you recommend to use the Kubernetes API to fetch the ServiceAccount/token?

>  CSI driver will have access to the secrets of pods that do not use it because the CSI driver should have a hostPath volume for the pods subdirectory to read the token.

This is a phrase I do not understand, and confuses me with the previous quote. Should the ServiceAccount/token get mapped into the filesystem, or not? Why a hostPath?

>  CSI service account token address these issues.

Each Ceph-CSI container deployment/daemonset already has its own ServiceAccount? Maybe I just do not understand what you mean with a "CSI service account"?

**Comment by humblec** [comment]
@nixpanic sorry, I missed this notification.  let me add a detailed info about this soon. Thanks
