### ISSUE TITLE
e2e: add retry around calls to `framework.ExecWithOptions()`

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#2347]
e2e failed while creating a Ceph user. This calls `framework.ExecWithOptions()` which needs to be wrapped in a function like `retryKubectlFile()`.

See-also: https://github.com/ceph/ceph-csi/pull/2298#issuecomment-889916215

**Comment by Madhu-1** [comment]
closing this one as we are not hitting the issue mentioned in description anymore :)
