### ISSUE TITLE
ci: jobs fail occasionally as rbd-nbd process fails to run

### ISSUE THREAD

**Issue by Yuggupta27** [ceph/ceph-csi#2362]
CI runs occasionally fail with 
```
timed out waiting for the rbd-nbd process: rbd-nbd process is not running yet: command terminated with exit code 1
```
on running the test case `STEP: perform IO on rbd-nbd volume after nodeplugin restart`

Job run: https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e_k8s-1.21/detail/mini-e2e_k8s-1.21/622/pipeline/

**Comment by nixpanic** [comment]
Failed at https://github.com/ceph/ceph-csi/pull/2329#issuecomment-893681377 too

**Comment by nixpanic** [comment]
https://github.com/ceph/ceph-csi/pull/2329#issuecomment-894037224 hit this too

**Comment by humblec** [comment]
https://github.com/ceph/ceph-csi/pull/2358/#issuecomment-897337628 hit this

**Comment by pkalever** [comment]
> #2358 hit this

From the recently available logs we can see the Healer and its respective NodeStageVolume calls return success:

```
I0804 18:42:20.383820   70338 rbd_healer.go:75] sending nodeStageVolume for volID: 0001-0024-6d535bc0-bfdd-4430-b76f-f8579c92438d-0000000000000002-a52a0649-f553-11eb-a84e-c6c213b01204, stagingPath: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-080a94a0-6945-414f-aac9-daa3dbf42869/globalmount
[...]
I0804 18:42:20.388380   70338 rbd_util.go:1109] setting disableInUseChecks: false image features: [layering] mounter: rbd-nbd
[...]
I0804 18:42:38.428422   70338 nodeserver.go:146] rbd volID: 0001-0024-6d535bc0-bfdd-4430-b76f-f8579c92438d-0000000000000002-a52a0649-f553-11eb-a84e-c6c213b01204 was successfully attached to device: /dev/nbd0
```
And the device is successfully attached, but the process is not running!?

Did the process abnormally terminate? Or failed to start? is the real question here!

Perhaps, we will be able to guess this only with the help of the rbd client logs which are missing at the moment. And PR#2393 should take us to a better position.
