### ISSUE TITLE
RBD: TODO: check image needs flattening and completed? for clone/snapshot

### ISSUE THREAD

**Issue by Rakshith-R** [ceph/ceph-csi#2383]
# Describe the bug #
This issue is to track progress on 

https://github.com/ceph/ceph-csi/blob/3c852199625333c8ccf8db18e592bb5627270d6b/internal/rbd/rbd_journal.go#L314

**Comment by Madhu-1** [comment]
@Rakshith-R this is not required anymore?

**Comment by Rakshith-R** [comment]
> @Rakshith-R this is not required anymore?

Yes this is no longer required.
