### ISSUE TITLE
Are encrypted and encryptionKMSID properties supported in cephfs storageclass.yaml?

### ISSUE THREAD

**Issue by laptimus** [ceph/ceph-csi#2429]
Below properties are present in ceph-csi/examples/rbd/storageclass.yaml but missing in ceph-csi/examples/cephfs/storageclass.yaml

(optional) Instruct the plugin it has to encrypt the volume
   By default it is disabled. Valid values are "true" or "false".
   A string is expected here, i.e. "true", not true.
   encrypted: "true"

   (optional) Use external key management system for encryption passphrases by
   specifying a unique ID matching KMS ConfigMap. The ID is only used for
   correlation to configmap entry.
   encryptionKMSID: <kms-config-id>

https://github.com/ceph/ceph-csi/blob/devel/examples/rbd/storageclass.yaml   
https://github.com/ceph/ceph-csi/blob/devel/examples/cephfs/storageclass.yaml

**Comment by Madhu-1** [comment]
No encryption is only supported for rbd not for cephfs for now, but there is an open issue to add support for cephfs also

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/issues/1563 closing as duplicate
