### ISSUE TITLE
Revisit the transactions chain , rollback ..etc 

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2435]
# Describe the bug #

At the moment ceph csi driver does not have a proper transaction framework which tracks or take care the transaction like createVolume, deleteVolume, CreateSnapshot...etc and do its rollback functions in  a chained fashion.

We have many small routines in various places which does the transaction rollbacks and sub tasks of a job and at the moment it lack the support for proper passing or recording of  consecutive stages and checkpoint tracking..etc.

The idea here is to introduce various transactions and its rollbacks gracefully by making use of proper interfaces and methods along with the locking in place. 

WIP Design draft # https://hackmd.io/TvrswhUUQDGwVk1vFLY7Pw
Locking improvements #2197 
..etc are the initial attempt to come up with a proper transnational framework for the ceph csi driver.

This issue updates or help #852 too.

**Comment by Rakshith-R** [comment]
👍I would love to see well defined transaction process, stages, checkpoints and rollback actions.

IMO, it will be great if CreateVolume is also split into createVolume, restoreSnapshot, & createClone with sharing common function/methods rather than having a single control flow with if conditions added in between for each.

**Comment by humblec** [comment]
> +1I would love to see well defined transaction process, stages, checkpoints and rollback actions.
> 
> IMO, it will be great if CreateVolume is also split into createVolume, restoreSnapshot, & createClone with sharing common function/methods rather than having a single control flow with if conditions added in between for each.

Indeed thats the plan @Rakshith-R :+1: , currently the control flow is really complicated and the aim here is to make it more transactional and commit/checkpoint/stage model.

**Comment by nixpanic** [comment]
Ideally a way of executing transactions is very modular, and should be re-usable for any of the transactions that Ceph-CSI does. A very much simplified view could be:

```go
type Transaction struct {
    steps []Operation
}

func (t *Transaction) Execute() error {
    for i, step := range t.steps {
        err := step.Run()
        if err != nil && i != 0 {
            t.Rollback(i - 1)
            return err
        }
    }
    return nil
}

func (t *Transaction) Rollback(pos int) {
    // rollback the last step
    t.steps[pos].Undo()

    if pos != 0 {
        t.Rollback(pos - 1)
    }
}
```

Each step can then implement a minimal interface
```go
type Operation interface {
     Run() error
     Undo()
}

type SetMetadata struct {
    RbdImage *rbd.rbdImage
    key, value string
}

func (sm *SetMetadata) Run() error {
    return sm.RbdImage.SetMetadata(sm.key, sm.value)
}

func (sm *SetMetadata) Undo() {
   sm.RbdImage.RemoveMetadata(sm.key)
}
```

The component that then wants to set metadata on an rbd image will create an instance of `Transaction`, add an instance of `SetMetadata` to the `Transaction.steps` and run `Transaction.Execute()`. Adding additional operations, like setting an other key/value, creating a snapshot, or anything should be straight forward.

For certain things, it is possible that a transaction has been interrupted. It may make sense to check in the `Run()` function if the action still needs to run (needs to be idempotent). Details like these should be documented in the API for the transaction framework.
