### ISSUE TITLE
Get rid of util package and move functions around

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2437]
# Describe the bug #

Keeping `util` package around has been considered as an outcome of deep package hierarchies and its not recommended or not considered as a best practice of go project package dependency. 

With this issue I would like to propose and get opinion on getting rid of `util` package in the project and moving the common functions to a seperate library.

It could also help us to export the common utilitiles or functions for other dependents projects , for example, a common library or function to generate volume ID ...etc could help other projects to import (ex: csi-addons)  and use it freely. 

@nixpanic @Madhu-1 @Yuggupta27 @yati1998 @Rakshith-R any thoughts on this ?

**Comment by Madhu-1** [comment]
> # Describe the bug
> Keeping `util` package around has been considered as an outcome of deep package hierarchies and its not recommended or not considered as a best practice of go project package dependency.
> 
> With this issue I would like to propose and get opinion on getting rid of `util` package in the project and moving the common functions to a seperate library.
> 
> It could also help us to export the common utilitiles or functions for other dependents projects , for example, a common library or function to generate volume ID ...etc could help other projects to import (ex: csi-addons) and use it freely.
> 
This increases the dependency on the external library and also we need to maintain backward compatibility.
 :-1:  from my side for common library
 
> @nixpanic @Madhu-1 @Yuggupta27 @yati1998 @Rakshith-R any thoughts on this ?

**Comment by humblec** [comment]
There can be 2 approaches :

1) take very common and independent functions to a library .
2) Forget completely about `util` package and move the functions to its callers even if there are some duplication..

**Comment by Yuggupta27** [comment]
> # Describe the bug
> Keeping `util` package around has been considered as an outcome of deep package hierarchies and its not recommended or not considered as a best practice of go project package dependency.
> 
> With this issue I would like to propose and get opinion on getting rid of `util` package in the project and moving the common functions to a seperate library.
> 
> It could also help us to export the common utilitiles or functions for other dependents projects , for example, a common library or function to generate volume ID ...etc could help other projects to import (ex: csi-addons) and use it freely.
> 
> @nixpanic @Madhu-1 @Yuggupta27 @yati1998 @Rakshith-R any thoughts on this ?

Calls of util functions are tailored currently to support their requirement in ceph-csi. Creating a separate library will in turn make us maintain the util functions as per other projects, which use them as well (which we might not want). Also, we might not want to move all the util functions in a separate library, and keep some in our repo, which will then get us back to having util package. Thoughts?

**Comment by nixpanic** [comment]
> 
> Keeping util package around has been considered as an outcome of deep package hierarchies and its not recommended or not considered as a best practice of go project package dependency.
> 

Care to share the documented recommended practises? Our `util` package is not deeply nested, just one level, adding a 2nd level to split utilities in smaller pieces seems reasonable to me.

> 
> It could also help us to export the common utilitiles or functions for other dependents projects , for example, a common library or function to generate volume ID ...etc could help other projects to import (ex: csi-addons) and use it freely.
> 

Other projects should probably not depend on ceph-csi specific behaviour or functions. Ceph-CSI as a project does not have an interest in supporting other projects with an API. If there are functions that are generally usable, a different project can provide those, and foster re-use in Ceph-CSI and other projects.

csi-addons is a project that should definitely **not** depend on Ceph-CSI parts, as it is intended to be a specification and components that can be used by other storage providers as well.
