### ISSUE TITLE
Start deprecating previous CSI releases

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2438]
# Describe the bug #

We dont have a clear policy on which ceph csi releases are supported and what are deprecated, I would like to propose below support policy and would like to get opinion on this :

1) Deprecate or mark all the `N-1` major releases as deprecated

For ex: 
Considering we have release `3.X` now, mark all the releases `<v2.0.0` as deprecated and remove from the support. 

@nixpanic @Madhu-1 @agarwal-mudit  any thoughts on this ?

**Comment by Madhu-1** [comment]
Sounds good to me to deprecate all releases less than N-1.

**Comment by Yuggupta27** [comment]
> # Describe the bug
> We dont have a clear policy on which ceph csi releases are supported and what are deprecated, I would like to propose below support policy and would like to get opinion on this :
> 
> 1. Deprecate or all the `N-1` major releases as depreacted
> 
> For ex:
> Considering we have release `3.X` now, mark all the releases `<v2.0.0` as deprecated and remove from the support.
> 
> @nixpanic @Madhu-1 @agarwal-mudit any thoughts on this ?

Sure, we can deprecate N-1 and suggest an upgrade for the same :+1:

**Comment by humblec** [comment]
Also what about `minor releases`? I think supporting last 2 or 3 minor releases are good enough , Isnt it ?

For example, on supported major versions, last 2 minor releases are supported. 

In that sense, with the release of `3.4.0` , we drop support for `3.1.0` ? and only support from `3.2.0`?

**Comment by Madhu-1** [comment]
> Also what about `minor releases`? I think supporting last 2 or 3 minor releases are good enough , Isnt it ?
> 
> For example, on supported major versions, last 2 minor releases are supported.
> 
> In that sense, with the release of `3.4.0` , we drop support for `3.1.0` ? and only support from `3.2.0`?

IMO Minor releases will always be backward compatible and no breaking changes and we should support all the minor releases for the supported major releases. the deprecation should be only for major releases.

**Comment by humblec** [comment]
also what about the `patch releases`?  considering patch releases are CVE fixes mostly, may be only last 2 patch releases in support?

**Comment by nixpanic** [comment]
The process to deprecate a release should be part of the process that is used for releasing a new version. This should also include adding/removing `backport-to*` labels, updating Mergify rules, ...

**Comment by Madhu-1** [comment]
@humblec anything pending on this one or we can close it?

**Comment by humblec** [comment]
> @humblec anything pending on this one or we can close it?

This has been addressed in both of the projects ( ceph-csi ) and rook https://github.com/rook/rook/pull/8756 , so closing it.
