### ISSUE TITLE
rbd-nbd logs are not getting dumped to the CI log collection

### ISSUE THREAD

**Issue by pkalever** [ceph/ceph-csi#2451]
# Describe the bug #

Unfortunately, the CI logs dump is not working as expected:

```
###
### going to execute: minikube_ssh sudo find /var/log/ceph/ -type f | xargs sudo tail -n +1
###
Warning: Permanently added '192.168.39.84' (ECDSA) to the list of known hosts.
###
### execution finished: minikube_ssh sudo find /var/log/ceph/ -type f | xargs sudo tail -n +1
###
```

**Comment by nixpanic** [comment]
Is it confirmed that the files have been created, and not deleted again? The CI run where this failed should still have PVCs with rbd-nbd available, if those have been unstaged, the logs would be gone too (I think?).

**Comment by pkalever** [comment]
> Is it confirmed that the files have been created, and not deleted again? The CI run where this failed should still have PVCs with rbd-nbd available, if those have been unstaged, the logs would be gone too (I think?).

Bingo! Yeah, I was thinking on similar lines later on the day I created this issue after cross-checking the code again. Should we also provide an option to disable the deletion of the logs on unmap, this should be helpful at CI?
