### ISSUE TITLE
improve documentation to include the missing configmap 

### ISSUE THREAD

**Issue by Ananth-vr** [ceph/ceph-csi#2535]
Trying https://docs.ceph.com/en/latest/rbd/rbd-kubernetes/ to integrate ceph-csi:canary with Pacific release of Ceph.

Documentation does not cover the steps required to create config-map for ceph-config which is needed by csi-rbdplugin.yaml

Steps to reproduce:
1.Follow steps as in the document 
2. execute csi-rbdplugin.yaml 

Expected Result:
csi-rbdplugin-xxx pods in running state

Actual state:
pod stuck in creating state
csi-rbdplugin-wgzzs                0/3     ContainerCreating   0          20m

Error:
  Warning  FailedMount  34h (x18 over 34h)  kubelet            MountVolume.SetUp failed for volume "ceph-config" : configmap "ceph-config" not found
  
  After creating ceph-config configmap from https://raw.githubusercontent.com/ceph/ceph-csi/devel/examples/ceph-conf.yaml
  
  kubectl get po -n kube-system|grep rbdplugin
csi-rbdplugin-jrhgr                3/3     Running             0          5m30s

Kubernetes Version: 1.21

**Comment by Madhu-1** [comment]
Closing as ceph PR is merged
