### ISSUE TITLE
Expose SCC's through ceph-csi package

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-csi#2541]
# Describe the feature you'd like to have #

The ceph-csi project is imported by several projects, typically Kubernetes operators.
When running on environments like OpenShift, Security Context Constraints need to be imported for Ceph-CSI to operate normally.
It would be nice if ceph-csi could export its own SCCs through its API (one of the packages). An exported function that returns the minimum SCCs.

# What is the value to the end-user? (why is it a priority?) #

This will reduce friction for consumers of Ceph-CSI who don't need to know or hardcore the SCCs in their own code. They can just pull the required SCC from any given branch.

# How will we know we have a good solution? (acceptance criteria) #

SCCs can be imported from ceph-csi.

# Additional context #

Rook-Ceph does that already https://github.com/rook/rook/blob/dcb88a71d1668f1b9a74c4af3fd2053fc39c0045/pkg/apis/ceph.rook.io/v1/scc.go#L30

**Comment by Madhu-1** [comment]
is it only to export SCC or pod/service templates also?

**Comment by leseb** [comment]
> is it only to export SCC or pod/service templates also?

I'll open a different one for the templates :-)

**Comment by nixpanic** [comment]
Could this easily be used to generate the deployment/Helm yaml files too? That would be ideal!

**Comment by Madhu-1** [comment]
Yes, we need to unmarshal the file and expose that as a function in the cephcsi package. main note here we don't have CI to test the SCC atleast

**Comment by nixpanic** [comment]
What I meant is that I hope we can maintain a single location (as a public API) where the SCC (and other templates) are maintained. When these are updated, we would need to run a small tool that takes the templates from the API and generates the files under `charts/` and `deploy/`.

**Comment by Madhu-1** [comment]
Sounds good :+1:

**Comment by leseb** [comment]
> Could this easily be used to generate the deployment/Helm yaml files too? That would be ideal!

Yes definitely, I have opened https://github.com/ceph/ceph-csi/issues/2542 separately, we can merge both if you want.

**Comment by nixpanic** [comment]
Hmm, I have been looking at this, and considered giving it a try. But there is no reference to `SecurityContextConstraints` or `security.openshift.io` in the Ceph-CSI repository. Where is a SCC for Ceph-CSI maintained now?

**Comment by leseb** [comment]
> Hmm, I have been looking at this, and considered giving it a try. But there is no reference to `SecurityContextConstraints` or `security.openshift.io` in the Ceph-CSI repository. Where is a SCC for Ceph-CSI maintained now?

It's maintainers in at least 2 repos:

* in rook here https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator-openshift.yaml#L47-L90
* in https://github.com/red-hat-storage/ocs-operator/blob/main/controllers/ocsinitialization/sccs.go

For ocs-op it will consume the SCCs through Ceph-CSI API. For Rook, we will add this in our build to auto-generate soon, based on the Ceph-CSI API also.

**Comment by nixpanic** [comment]
@leseb please have a look at the commit at https://github.com/ceph/ceph-csi/pull/2551/commits/6ba498f5cc2b77a04f87e89a9f5a619562c37992 and see if that is what you would like to have.

This is a separate Go module, so that importing it does not pull in the whole Ceph-CSI pieces. It should be possible to keep the API part of Ceph-CSI relatively small and self-contained that way. Other projects that deploy Ceph-CSI can then opt-in to only import the part(s) of the API that are relevant for them (OpenShift deployers will want to import the `ocp` and future `k8s` package, but Kubernetes environments should not need any OpenShift dependencies).

**Comment by leseb** [comment]
> @leseb please have a look at the commit at [6ba498f](https://github.com/ceph/ceph-csi/commit/6ba498f5cc2b77a04f87e89a9f5a619562c37992) and see if that is what you would like to have.
> 
> This is a separate Go module, so that importing it does not pull in the whole Ceph-CSI pieces. It should be possible to keep the API part of Ceph-CSI relatively small and self-contained that way. Other projects that deploy Ceph-CSI can then opt-in to only import the part(s) of the API that are relevant for them (OpenShift deployers will want to import the `ocp` and future `k8s` package, but Kubernetes environments should not need any OpenShift dependencies).

Yes it really matches the expectation. Thanks.

**Comment by nixpanic** [comment]
@leseb, the PR has been updated to reflect what we want to do. There are unit tests that show how to get the SecurityContextConstraints object, by passing a struct that contains keys to replace in a template. If this is an API that Rook still can use easily, we'll continue along this path.

**Comment by nixpanic** [comment]
#2551 has been merged
