### ISSUE TITLE
rbd: rewrite `updateVolWithImageInfo()` to use go-ceph

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#2558]
ceph/go-ceph#448 (part of upcoming go-ceph v0.12) adds support for `GetImageMirrorMode()` which can be used to rewrite

https://github.com/ceph/ceph-csi/blob/8ebc0659ab706f1b033876327d2b5c96dc74d9c5/internal/rbd/rbd_util.go#L1478-L1509

Using go-ceph instead of the `rbd` command will reduce the chance on hitting resource limits and running into undefined behaviour.

**Comment by Rakshith-R** [comment]
it's already supported in go-ceph v0.11.
https://github.com/ceph/go-ceph/blob/v0.11.0/rbd/mirror.go#L311
