### ISSUE TITLE
Allow multi-attach by default for Block mode

### ISSUE THREAD

**Issue by j-griffith** [ceph/ceph-csi#256]
We added multi node write capability via storage class as per issue #237 
It would makes sense to allow volumes that are block mode to do this by default, and not require an SC entry.  We don't need to remove the SC entry; but with a new default would just update the documentation and wording to clarify that the SC option is only for non-block mode RBD volumes.

We could probably rename the sc variable, we should discuss that going forward.

**Comment by Madhu-1** [comment]
@j-griffith can we close this issue

**Comment by j-griffith** [comment]
Fixed in: https://github.com/ceph/ceph-csi/pull/261
