### ISSUE TITLE
CephFS - extended client information in mds [client_metadata]

### ISSUE THREAD

**Issue by adamdrozdz** [ceph/ceph-csi#2561]
# Environment details #

- Image/version of Ceph CSI driver : v3.4.0
- Kernel version :5.13.12
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : cephFS with kernel
- Kubernetes cluster version : 1.20
- Ceph cluster version : 16.2.6

I'm looking for a way to extend the information provided by a client connected to a volume on cephFS. We have several hundred pods that use several volumes, but in any case the information contained in client_metadata is limited to these few fields `entity_id, hostname, kernel_version, root` . 
```
ceph tell mds.0 client ls
       {
        "id": 6260815,
        "entity": {
            "name": {
                "type": "client",
                "num": 6260815
            },
            "addr": {
                "type": "v1",
                "addr": "x.x.x.x:0",
                "nonce": 3973305286
            }
        },
        "client_metadata": {
            "client_features": {
                "feature_bits": "0x0000000000007bff"
            },
            "metric_spec": {
                "metric_flags": {
                    "feature_bits": "0x00000000000080ff"
                }
            },
            "entity_id": "admin",
            "hostname": "x-x",
            "kernel_version": "5.13.12-051312-generic",
            "root": "/volumes/x-x-x/x-x-x/ce49e589-ae4d-47d0-add4-e691be4f40be"
        }
 ```
        
I was looking for a solution in several places, unfortunately to no avail. I noticed some extra information in client_metadata in the documentation: 
https://docs.ceph.com/en/mimic/cephfs/eviction/#manual-client-eviction
```
        "client_metadata": {
            "ceph_sha1": "ae81e49d369875ac8b569ff3e3c456a31b8f3af5",
            "ceph_version": "ceph version 12.0.0-1934-gae81e49 (ae81e49d369875ac8b569ff3e3c456a31b8f3af5)",
            "entity_id": "0",
            "hostname": "senta04",
            "mount_point": "/tmp/tmpcMpF1b/mnt.0",
            "pid": "29377",
            "root": "/"
        }
```
It would be useful to get at least the `pid` information. It would be ideal to see information about the pod using the volume there: https://kubernetes-csi.github.io/docs/pod-info.html
I would like to bind a specific client and its stats from the [stats module](https://docs.ceph.com/en/latest/cephfs/cephfs-top/) to a specific container.

**Comment by nixpanic** [comment]
Not sure why the `pid` would not be listed, maybe because the kernel client is used by default and only the FUSE client provides it? In any case, the `pid` of the client (mount process) does not tell you a lot, it can not be correlated to the actual process that does I/O on the filesystem.

Is there an option for you to take the `root` attribute and match that with the details from the PersistentVolume object on the Kubernetes side? Then you should be able to find the PersistentVolumeClaim, and the the Pod that uses the volume.

**Comment by adamdrozdz** [comment]
> Not sure why the pid would not be listed, maybe because the kernel client is used by default and only the FUSE client provides it? In any case, the pid of the client (mount process) does not tell you a lot, it can not be correlated to the actual process that does I/O on the filesystem.

OK I understand. I didn't know that this information depends on the mounting method.

> Is there an option for you to take the root attribute and match that with the details from the PersistentVolume object on the Kubernetes side? Then you should be able to find the PersistentVolumeClaim, and the the Pod that uses the volume.

yes, this is an option, unfortunately it only works when using separate volumes per pod. In my case, 90% of pods use one static volume in `ROX` mode.
```
x:6789,x:6789,x:6789:/volumes/x-x-x/x-x-x/ce49e589-ae4d-47d0-add4-e691be4f40be on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/x-x-x-x-x-x-x-x-x-1/globalmount type ceph (ro,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=ceph-filesystem,_netdev)
x:6789,x:6789,x:6789:/volumes/x-x-x/x-x-x/ce49e589-ae4d-47d0-add4-e691be4f40be on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/x-x-x-x-x-x-x-x-x-x-2/globalmount type ceph (ro,relatime,name=csi-cephfs-node,secret=<hidden>,acl,mds_namespace=ceph-filesystem,_netdev)
```
I also found in client's configuration the option to add [client_metadata](https://docs.ceph.com/en/latest/cephfs/client-config-ref/#confval-client_metadata) passed to MDS. I have no idea where this could be added and whether there is such a possibility.

**Comment by nixpanic** [comment]
The mounting of the filesystem is done during [`NodeStageVolume`](https://github.com/container-storage-interface/spec/blob/master/spec.md#nodestagevolume):

https://github.com/ceph/ceph-csi/blob/90ecd2d7e84449288529b2884164b612c26b106c/internal/cephfs/nodeserver.go#L77

There is very little data available during that procedure, the Pod for which the mount is done is not known. It seems possible to pass more metadata while mounting (as you linked in the previous comment). But, as there is very little available to pass along, I am not sure if there is anything we can do to help...

Note that mounting the volume is done before Pods get started, the volume is mounted for the whole worker node. In case there are multiple Pods on the same worker node using the same volume, it is only mounted once (and bind-mounted into the container runtime environment afterwards in `NodePublishVolume`).

**Comment by adamdrozdz** [comment]
Is it possible to tag PVC or PV in a specific way that would allow any of these tags to be passed on?
Maybe you know about any other way to easily identify a client using cephfs? I was thinking about using separate credentials per workload (username is in metadata), but it's a very painful thing to do in a dynamic environment.
