### ISSUE TITLE
Volume snapshot is always not ready to use

### ISSUE THREAD

**Issue by byjos** [ceph/ceph-csi#2570]
hello,I installed csi driver followed https://fuckcloudnative.io/posts/kubernetes-storage-using-ceph-rbd/
k8s version：v1.18.8
ceph version：14.2.22
snapshotter version ：2.1
When I create a volumesnapshots,my volumesnapshot is always showing READYTOUSE: false
![image](https://user-images.githubusercontent.com/25920168/137281070-fce1701c-bef7-443c-ba4a-59575408d9a0.png)
If further info can be helpful let me know.

**Comment by Madhu-1** [comment]
@byjos please provide the required logs as mentioned in issue template

**Comment by xujianhai666** [comment]
@byjos did u finish the problem
