### ISSUE TITLE
Can't dynamic create PersistentVolume after PVC created. Operation not permitted #904

### ISSUE THREAD

**Issue by easonboy** [ceph/ceph-csi#2576]
quay.io/cephcsi/cephcsi v3.1.0 docker image
There seems to be the same problem，error:= failed to get connection: connecting failed: rados: ret=13, Permission denied. change to image quay.io/cephcsi/cephcsi:canary it's ok ,pls help check, thanks!

explain:

[root@master01 ceph-csi]# git branch

(detached from v3.1.0)
devel
[root@master01 ceph-csi]#
[root@master01 rbd]# kubectl -n ceph-csi describe pod csi-rbdplugin-provisioner-5f9d8fb9c6-4l8xf|grep quay.io/cephcsi/cephcsi
Image: quay.io/cephcsi/cephcsi:canary
Image ID: docker-pullable://quay.io/cephcsi/cephcsi@sha256:678dbf3dada23438ae101175e7ce893565982b6ff2362b19c7c4f13254446663
Image: quay.io/cephcsi/cephcsi:canary
Image ID: docker-pullable://quay.io/cephcsi/cephcsi@sha256:678dbf3dada23438ae101175e7ce893565982b6ff2362b19c7c4f13254446663
Normal Pulling 19m kubelet Pulling image "quay.io/cephcsi/cephcsi:canary"
Normal Pulled 16m kubelet Successfully pulled image "quay.io/cephcsi/cephcsi:canary"
Normal Pulled 16m kubelet Container image "quay.io/cephcsi/cephcsi:canary" already present on

**Comment by Madhu-1** [comment]
3.1.0 is too old and it's not supported anymore. @easonboy have you tried the 3.4.0 image?

**Comment by easonboy** [comment]
ok ,i will try 3.4.0 image,thansks!
