### ISSUE TITLE
External provisioner is provisioning volume for claim "default/abcd"   Warning  ProvisioningFailed    20s (x8 over 2m27s)  rbd.csi.ceph.com_csi-rbdplugin-provisioner-64598bf8f9-gbsls_efc5a55a-679e-4544-9323-7aa182540118  failed to provision volume with StorageClass "new-sc": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-1973d586-f6ce-43fc-aed9-4812c0f1443a already exists

### ISSUE THREAD

**Issue by easonboy** [ceph/ceph-csi#2592]
1, using ceph-csi driver, tag is v3.4.0, found this error all the time

failed to provision volume with StorageClass "new-sc": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-1973d586-f6ce-43fc-aed9-4812c0f1443a already exists

2，ceph cluster is ok 

  cluster:
    id:     43e426d7-c323-48ad-80c7-24c2bdf2f848
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum master01,master02,work01 (age 14h)
    mgr: work01(active, since 14h), standbys: master02
    mds: cephfs-demo:1 {0=master01=up:active} 1 up:standby
    osd: 3 osds: 3 up (since 23m), 3 in (since 23m)
    rgw: 1 daemon active (work02)
 
  task status:
 
  data:
    pools:   11 pools, 608 pgs
    objects: 409 objects, 107 MiB
    usage:   3.4 GiB used, 27 GiB / 30 GiB avail
    pgs:     608 active+clean
 

log:
csi-provisioner:

[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["discard"]}},"access_mode":{"mode":1}}]}
I1026 03:27:15.114673       1 connection.go:185] GRPC response: {}
I1026 03:27:15.114745       1 connection.go:186] GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-1973d586-f6ce-43fc-aed9-4812c0f1443a already exists
I1026 03:27:15.114834       1 controller.go:753] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Background: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-1973d586-f6ce-43fc-aed9-4812c0f1443a already exists
I1026 03:27:15.114939       1 controller.go:1106] Temporary error received, adding PVC 1973d586-f6ce-43fc-aed9-4812c0f1443a to claims in progress
W1026 03:27:15.114967       1 controller.go:958] Retrying syncing claim "1973d586-f6ce-43fc-aed9-4812c0f1443a", failure 9
E1026 03:27:15.115007       1 controller.go:981] error syncing claim "1973d586-f6ce-43fc-aed9-4812c0f1443a": failed to provision volume with StorageClass "new-sc": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-1973d586-f6ce-43fc-aed9-4812c0f1443a already exists
I1026 03:27:15.115054       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"abcd", UID:"1973d586-f6ce-43fc-aed9-4812c0f1443a", APIVersion:"v1", ResourceVersion:"20349376", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "new-sc": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-1973d586-f6ce-43fc-aed9-4812c0f1443a already exists
I1026 03:27:19.337730       1 leaderelection.go:273] successfully renewed lease ceph-csi/rbd-csi-ceph-com

csi-rbdplugin:

I1026 03:27:15.113064       1 utils.go:176] ID: 33 Req-ID: pvc-1973d586-f6ce-43fc-aed9-4812c0f1443a GRPC call: /csi.v1.Controller/CreateVolume
I1026 03:27:15.113421       1 utils.go:180] ID: 33 Req-ID: pvc-1973d586-f6ce-43fc-aed9-4812c0f1443a GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-1973d586-f6ce-43fc-aed9-4812c0f1443a","parameters":{"clusterID":"43e426d7-c323-48ad-80c7-24c2bdf2f848","csi.storage.k8s.io/pv/name":"pvc-1973d586-f6ce-43fc-aed9-4812c0f1443a","csi.storage.k8s.io/pvc/name":"abcd","csi.storage.k8s.io/pvc/namespace":"default","imageFeatures":"layering","pool":"ocp"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["discard"]}},"access_mode":{"mode":1}}]}
I1026 03:27:15.114308       1 rbd_util.go:1109] ID: 33 Req-ID: pvc-1973d586-f6ce-43fc-aed9-4812c0f1443a setting disableInUseChecks: false image features: [layering] mounter: rbd
E1026 03:27:15.114338       1 controllerserver.go:288] ID: 33 Req-ID: pvc-1973d586-f6ce-43fc-aed9-4812c0f1443a an operation with the given Volume ID pvc-1973d586-f6ce-43fc-aed9-4812c0f1443a already exists
E1026 03:27:15.114378       1 utils.go:185] ID: 33 Req-ID: pvc-1973d586-f6ce-43fc-aed9-4812c0f1443a GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-1973d586-f6ce-43fc-aed9-4812c0f1443a already exists
I1026 03:27:33.250951       1 utils.go:176] ID: 34 GRPC call: /csi.v1.Identity/Probe

**Comment by easonboy** [comment]
add

[root@master01 kubernetes]# kubectl -n ceph-csi exec -it csi-rbdplugin-54fss -c csi-rbdplugin sh
sh-4.4# ps -ef|grep rbd
root     1970902 1970881  0 03:18 ?        00:00:00 /csi-node-driver-registrar --v=5 --csi-address=/csi/csi.sock --kubelet-registration-path=/var/lib/kubelet/plugins/rbd.csi.ceph.com/csi.sock
root     1970949 1970928  0 03:18 ?        00:00:00 /usr/local/bin/cephcsi --nodeid=master02 --pluginpath=/var/lib/kubelet/plugins --stagingpath=/var/lib/kubelet/plugins/kubernetes.io/csi/pv/ --type=rbd --nodeserver=true --endpoint=unix:///csi/csi.sock --v=5 --drivername=rbd.csi.ceph.com --enableprofiling=false
root     1971816 1971794  0 03:19 ?        00:00:00 /usr/local/bin/cephcsi --nodeid=master02 --type=rbd --controllerserver=true --endpoint=unix:///csi/csi-provisioner.sock --v=5 --drivername=rbd.csi.ceph.com --pidlimit=-1 --rbdhardmaxclonedepth=8 --rbdsoftmaxclonedepth=4 --enableprofiling=false
root     1971875 1971848  0 03:19 ?        00:00:09 /usr/local/bin/cephcsi --type=controller --v=5 --drivername=rbd.csi.ceph.com --drivernamespace=ceph-csi
root     1983444 1983386  0 03:47 pts/1    00:00:00 grep rbd
sh-4.4# ps -ef|grep rados
root     1983546 1983386  0 03:48 pts/1    00:00:00 grep rados
sh-4.4#

**Comment by Madhu-1** [comment]
@easonboy can you please check you have network connectivity with the ceph cluster and the rbd-plugin container of the provisioner pod?

**Comment by easonboy** [comment]
Can you provide some specific commands for troubleshooting? Thanks

**Comment by Madhu-1** [comment]
see this help https://rook.io/docs/rook/v1.7/ceph-csi-troubleshooting.html (this is more specific to rook but the idea remains the same for external ceph cluster also

**Comment by easonboy** [comment]
I have solved the problem, thanks.

**Comment by rocdove** [comment]
> I have solved the problem, thanks.

I have the same problem. Can you describe in detail how to solve it? Thank you very much.
