### ISSUE TITLE
[RFE] separate node attach/detach/get device behind interface

### ISSUE THREAD

**Issue by dillaman** [ceph/ceph-csi#26]
By default krbd would be utilized, but it would be great if we could quickly and easily provide NBD and TCMU-based drivers if the node is configured to utilize something besides krbd.

**Comment by rootfs** [comment]
+1
current rbd_util.go is extracted from kubernetes source. Will make an interface for rbd-nbd and tcmu drivers.

**Comment by kfox1111** [comment]
Any updates on this?

**Comment by rootfs** [comment]
yes, it is being worked on, see https://github.com/rook/rook/pull/2059

**Comment by dillaman** [comment]
@rootfs will do
