### ISSUE TITLE
Improve detection and recovery of broken ceph-fuse mounts

### ISSUE THREAD

**Issue by gman0** [ceph/ceph-csi#2616]
# Describe the feature you'd like to have #

Broken FUSE-based mounts is a well known problem in CSI. While we can't guarantee that the fuse cephfs client won't fail (bugs in ceph-fuse or node plugin, OOM, upgrades, ...), we can make it easier for users to recover from this situation.

Currently, cephfs-csi mounts a cephfs volume in `NodeStageVolume` only, and then binds this to a target path in `NodePublishVolume`. If the Node Plugin container was restarted, it will lose the original FUSE mount as well as all the bindmounts, rendering all current and future Pods consuming the volume unable to access the volume. The only way for users to get out of this situation is to trigger `NodeUnstageVolume`, so that the volume can be properly remounted later. This would probably involve restarting the node, because at least in cephfs-csi v3.4.0, `NodeUnpublishVolume` can't finish with broken mounts ([`util.IsMountPoint()`](https://github.com/ceph/ceph-csi/blob/b95f3cdcbc1d3659afd48551e96744fd988db6bd/internal/cephfs/nodeserver.go#L294-L303) will keep failing).

Let's try to recover mountpoints in both `NodeStageVolume` and `NodePublishVolume`. In both we would check for broken mountpoints (`stat()` and check for `ENOTCONN`) and remount if necessary. Remounting is safe, because all Pods consuming the volume(s) have their mounts broken anyway.

I can work on this.

# What is the value to the end user? (why is it a priority?) #

It would be possible to recover a ceph-fuse mount without needing to trigger `NodeUnstageVolume`->`NodeStageVolume`. The next Pod to mount the volume would be also the one to trigger mount recovery.

Note that existing Pods would remain in a bad state, only new ones would have their mounts working. Existing Pods would need to `NodeUnpublishVolume`->`NodePublishVolume`, which could be achieved only by deleting these Pods. We can discuss this or some other automatic mount reconciliation in a separate ticket.

# How will we know we have a good solution? (acceptance criteria) #

* Create an app Pod that mounts a CephFS volume with `mounter: fuse`.
* Delete the Node plugin Pod (or kill the ceph-fuse process inside the container).
* Observe the app Pod not being able to access the volumes anymore (ends with an error, e.g. `Transport endpoint is not connected`).
* Create another app Pod, observe the volume being accessible again.

**Comment by humblec** [comment]
Thanks @gman0 for picking this up.. Indeed this is  one thing which we wanted to solve for some time now. :) , remounting should be safe in this case I believe. The main worry is on the race conditions which could be caused wrt to the volume or mount being moved to another node meanwhile by kube scheduler. 

Also we have seen some memory issues while fuse is in place https://github.com/ceph/ceph-csi/issues/554.

**Comment by pkalever** [comment]
The ideal solution according to me would be to get the reattach/reconnect working from ceph-fuse like [`rbd-nbd attach`](https://docs.ceph.com/en/latest/man/8/rbd-nbd/). Once we have that support may be add a healer at node-plugin level to repair the mounts.

There seem to be an open tracker for this https://tracker.ceph.com/issues/8369

**Comment by gman0** [comment]
@humblec 

> The main worry is on the race conditions which could be caused wrt to the volume or mount being moved to another node meanwhile by kube scheduler.

`Node{Stage,Unstage}Volume` is already protected by key-based locks:

https://github.com/ceph/ceph-csi/blob/b95f3cdcbc1d3659afd48551e96744fd988db6bd/internal/cephfs/nodeserver.go#L90-L95

We could expand these locks to publish procedures too, no? Although I do remember there were some lock contention issues too, but that's a separate problem.

> Also we have seen some memory issues while fuse is in place #554.

Yes we saw this too. This mount recovery covers container restarts caused by OOMs too.

**Comment by gman0** [comment]
@pkalever thanks, that would indeed be better, but that ticket seems to be really old and not active. In the meantime maybe we can have at least this? I'm not suggesting this proposal would completely fix mount problems, but if a mount does in fact fail, it makes the aftermath easier to clean.

**Comment by pkalever** [comment]
> @pkalever thanks, that would indeed be better, but that ticket seems to be really old and not active. In the meantime maybe we can have at least this?

Sure! I guess no one knows the current status of that tracker (I just came across it on a random search)

I initially had plans to fix userspace mounters, `rbd for block` and `cephfs for fs` both. I picked `rbd-nbd` first and currently working on it for some time now and I'm happy that we made [great progress](https://github.com/ceph/ceph-csi/projects/13) for `rbd-nbd`. My next target would be to fix `ceph-fuse` to add support for cephfs userspace mounters option. But honestly, I have not started anything on this yet.

@gman0 no objections from me to get this moving someway if that looks helpful. But someday I really wish to see ceph-fuse having a reattach+healer solution just like rbd-nbd :-)

Thanks!

**Comment by humblec** [comment]
> @pkalever thanks, that would indeed be better, but that ticket seems to be really old and not active. In the meantime maybe we can have at least this? I'm not suggesting this proposal would completely fix mount problems, but if a mount does in fact fail, it makes the aftermath easier to clean.

@gman0 imo, this is definitely a possible improvement or interim step  till we have reattach working.

**Comment by gman0** [comment]
@pkalever excellent, that sounds really good!

**Comment by Madhu-1** [comment]
> > @pkalever thanks, that would indeed be better, but that ticket seems to be really old and not active. In the meantime maybe we can have at least this?
> 
> Sure! I guess no one knows the current status of that tracker (I just came across it on a random search)
> 
> I initially had plans to fix userspace mounters, `rbd for block` and `cephfs for fs` both. I picked `rbd-nbd` first and currently working on it for some time now and I'm happy that we made [great progress](https://github.com/ceph/ceph-csi/projects/13) for `rbd-nbd`. My next target would be to fix `ceph-fuse` to add support for cephfs userspace mounters option. But honestly, I have not started anything on this yet.
> 
> @gman0 no objections from me to get this moving someway if that looks helpful. But someday I really wish to see ceph-fuse having a reattach+healer solution just like rbd-nbd :-)
> 
> Thanks!

the target making the volume healer framework usable for both rbd and cephfs. I assume that should solve the issue with fuse reattach+healing. @pkalever wdyt?

**Comment by pkalever** [comment]
> the target making the volume healer framework usable for both rbd and cephfs. I assume that should solve the issue with fuse reattach+healing. @pkalever wdyt?

Right! However, IMO in order to use the same, at first the core ceph-fuse tool should support reattach/reconnect functionality, which might be the major missing piece here.

**Comment by gman0** [comment]
@pkalever is [1] something you had in mind for the reconnect feature?

[1] https://sourceforge.net/p/fuse/mailman/fuse-devel/thread/CAJfpegvEppXZbX25Nage463biMjWPKthr%3D519PSJ61yZmTavCw%40mail.gmail.com/#msg37401044
