### ISSUE TITLE
Using Ceph with k3s installed with k3d

### ISSUE THREAD

**Issue by leon-andria** [ceph/ceph-csi#2620]
When I'm installing Ceph on a freshly k3d/k3s setup, I got the following plugins in errors/
![image](https://user-images.githubusercontent.com/1230744/140531692-1832bd66-9dd7-4300-98d6-1b23940053e9.png)
And the error message is below:
`Warning  Failed     20s                kubelet            Error: failed to generate container "11384884d35d441f08068cf5f9b5e9ba91b67d246aa5c030d2528c4a19f40882" spec: failed to generate spec: path "/var/lib/kubelet/pods" is mounted on "/var/lib/kubelet" but it is not a shared mount`.

To reproduce this behavior, a classical setup with k3d:
`k3d cluster create dev --port 8080:80@loadbalancer --port 8443:443@loadbalancer`

And apply the rook setup with cluster test.

Here is the describe of the pod that is running in error:
![image](https://user-images.githubusercontent.com/1230744/140533412-e02aa57c-69b8-43bc-b30a-a520be78a256.png)

**Comment by Madhu-1** [comment]
looks to be a generic issue can you please check https://github.com/rancher/k3d/issues/206 https://kubernetes-csi.github.io/docs/troubleshooting.html#node-plugin-pod-does-not-start-with-runcontainererror-status?
