### ISSUE TITLE
RBD maximum parent image chain for clones

### ISSUE THREAD

**Issue by dillaman** [ceph/ceph-csi#263]
When cloning an RBD image, it might be required to immediately flatten the image if it has more than 16 parents (ancestors). This is a limit of the kernel driver [1], but for IO performance you still wouldn’t want a potentially large chain of parent images to search through for read requests.

Note that Cinder will perform a flatten at a much more manageable 5 parents [2].

[1] 
https://github.com/torvalds/linux/blob/master/drivers/block/rbd.c#L92
[2] 
https://github.com/openstack/cinder/blob/9660f7010e3f54ec4c873cc3154cf275e046ca24/cinder/volume/drivers/rbd.py#L82

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/pull/467 will take care of flattening the image
