### ISSUE TITLE
Provisioner and Nodeplugin pods fails to come up 

### ISSUE THREAD

**Issue by yati1998** [ceph/ceph-csi#2632]
# Describe the bug #

On creating the rook-ceph cluster using the deploy script, the provisioner and nodeplugin pods don't come up.

1. Run `./scripts/minikube.sh deploy-rook`
2. check if all the pods are up `kubectl get pods -nrook-ceph`

# Actual results #
```
[yatipadia@192 ceph-csi]$ kubectl get pods -nrook-ceph
NAME                                      READY   STATUS      RESTARTS   AGE
rook-ceph-mds-myfs-a-586646fdb9-tbjfl     1/1     Running     0          3m52s
rook-ceph-mds-myfs-b-58c86776c5-k5c8g     1/1     Running     0          3m51s
rook-ceph-mgr-a-7bd4584945-s2tsg          1/1     Running     0          4m27s
rook-ceph-mon-a-669488fd67-hvmpp          1/1     Running     0          4m37s
rook-ceph-operator-6459f5dc4b-vggbf       1/1     Running     0          12m
rook-ceph-osd-0-7b8d6c47c4-v97n4          1/1     Running     0          4m18s
rook-ceph-osd-prepare-minikube--1-js885   0/1     Completed   0          4m2s
rook-ceph-tools-7467d8bf8-nqc2v           1/1     Running     0          12m
```
The provisioner and Nodeplugin pods don't come up.

# Expected behavior #

All the pods including the provisioner and nodeplugin pods should come up

**Comment by nixpanic** [comment]
This is intentional see commit f9c369918c for details.

**Comment by Madhu-1** [comment]
Yes as we are deploying cephcsi as standalone we don't need rook to deploy csi pods.
