### ISSUE TITLE
rbd: implement spec for CSI-Addons Operation ReclaimSpace

### ISSUE THREAD

**Issue by Rakshith-R** [ceph/ceph-csi#2672]
When executing a ReclaimSpace operation the storage consumption of the
volume is tried to be reduced. The Storage Provider can implement this
by calling functions like fstrim, blkdiscard or similar on the
volume.

More details at https://github.com/csi-addons/spec/pull/30

```
// Controller holds the RPC method for running discard operations on the
// inactive (not required to be staged/published) volume.
service Controller {
  // ControllerReclaimSpace is a procedure that gets called on the CSI
  // Controller.
  rpc ControllerReclaimSpace (ControllerReclaimSpaceRequest)
  returns (ControllerReclaimSpaceResponse) {}
}

// Node holds the RPC method for running discard operations on the active
// (staged/published) volume.
service Node {
  // NodeReclaimSpace is a procedure that gets called on the CSI NodePlugin.
  rpc NodeReclaimSpace (NodeReclaimSpaceRequest)
  returns (NodeReclaimSpaceResponse) {}
}
```

**Comment by humblec** [comment]
@Rakshith-R anything pending here , specifically from ceph csi repo side? please revisit the state as its marked for 3.5 release.

**Comment by Rakshith-R** [comment]
> @Rakshith-R anything pending here , specifically from ceph csi repo side? please revisit the state as its marked for 3.5 release.

I think it's done, but I'll let @nixpanic confirm there's nothing left.

**Comment by nixpanic** [comment]
> @Rakshith-R anything pending here , specifically from ceph csi repo side? please revisit the state as its marked for 3.5 release.

The functionality is available, and tested manually. There is no automated e2e verification yet, so this issue has not been closed either.
