### ISSUE TITLE
rbd: removed a workaround to fix rbd snapshot scheduling

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2675]
Removed to code workaround introduced in https://github.com/ceph/ceph-csi/pull/2656 to workaround the rbd snapshot scheduling bug.  once the rbd fixes the issue we will remove this in cephcsi

PR needs to be reverted back

- [ ] #2656 
- [ ] #2669
- [ ] #2694

**Comment by humblec** [comment]
@Madhu-1 iic, this is done, isnt it ?

**Comment by Madhu-1** [comment]
@humblec this is a tracker to remove the workaround in cephcsi. once ceph identifies the issue will remove the workaround.

**Comment by humblec** [comment]
Thanks!

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/pull/3413 fix it
