### ISSUE TITLE
Provide an option to use a common Ceph credential across CephFS subvolumes

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#269]
Currently, each CephFS volume gets a sub-directory under the CephFS root and further gets a user created with rw access to the directory (and a few other rights as required to access the directory). For each stage and publish request of such a sub-directory to a node, the CephFS root volume is mounted, and then the sub-directory is bind mounted into the requested directory, using the user credentials created for this volume.

In certain situations where the volume counts are high it is desirable to not have the additional per directory Ceph user, and instead leverage a single user that can mount the sub-directory, leaving kuberetes (or other container orchestration systems) to deal with access restrictions on bind mounted paths.

The above scheme also lends itself to staging the CephFS root once during staging the volume the first time on a node, and bind mounting sub-directories for each volume that recieves further publish requests on the same node. Again at scale, such a scheme helps, as it reduces the number of CephFS mounts on a node.

Thoughts on implementation:
- The option itself can be provided as a run-time option to the CSI plugin, thus reducing overhead on one more parameter to specify in the StorageClass and can also optionally be controlled by the StorageClass.

- The volume_options in CreateVolume response can carry the boolean regarding the nature of secret to use to mount the volume, and hence node level plugin can make a dynamic decision regarding the same.

**Comment by gman0** [comment]
I had a similar idea in mind, but wanted to wait till we have cluster IDs in place - those could be used to simplify things down further.

**Comment by ShyamsundarR** [comment]
:) totally agree, this can wait. I am just filing away stuff that is in my notes for consideration. Thanks!

**Comment by ajarr** [comment]
@ShyamsundarR can we close this issue now?

**Comment by ShyamsundarR** [comment]
Fixed, closing.
