### ISSUE TITLE
rbd: cannot take a incremental backup

### ISSUE THREAD

**Issue by liuminjian** [ceph/ceph-csi#2693]
# Describe the bug #

i take a few snapshots by creating some volumesnapshot crd.  i want to take a incremental backup in the ceph-csi container, but the snapshot cannot be found. this makes me very confused.
![image](https://user-images.githubusercontent.com/7840869/144970613-6f9cbf45-fcdd-4327-9bf8-213a71c63051.png)

# Environment details #

- Image/version of Ceph CSI driver : v3.4.0-canary
- Helm chart version : v3.4.0-canary
- Kernel version : 5.6.15-1.el7.elrepo.x86_64
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : rbd
- Kubernetes cluster version : v1.18.19
- Ceph cluster version : 14.2.22  nautilus

**Comment by liuminjian** [comment]
i find the reason. when calling create a snapshot, a snapshot clone will be created and the snapshot will be deleted at the end. but i don't know why.
![image](https://user-images.githubusercontent.com/7840869/144987593-83bb4e45-5d13-4987-a417-f241c38669ca.png)

**Comment by Madhu-1** [comment]
its internal implementation we delete the snapshot (moved to trash) once we take the clone. can you take the diff of the rbd image created when you create the Kubernetes volumesnapshot?

**Comment by liuminjian** [comment]
> its internal implementation we delete the snapshot (moved to trash) once we take the clone. can you take the diff of the rbd image created when you create the Kubernetes volumesnapshot?

What does it mean？ I want to add features such as rbd export-diff in the container，so i need the snapshot

**Comment by Madhu-1** [comment]
the snapshots will be deleted after taking the clone and it won't be required for cephcsi for any other operations.
