### ISSUE TITLE
metadata corruption after changing folder permissions

### ISSUE THREAD

**Issue by Masber** [ceph/ceph-csi#2708]
# Describe the bug #

running `chmod -R 0600 /mnt/my/folder` corrupts all metadata under /mnt/my/folder

# Environment details #

- Image/version of Ceph CSI driver : 3.4.0
- Helm chart version : 3.4.0
- Kernel version : SUSE 4.12.14-197.78
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : fuse and krbd
- Kubernetes cluster version : v1.18.0
- Ceph cluster version : 
{
    "mon": {
        "ceph version 14.2.11-394-g9cbbc473c0 (9cbbc473c02686761b4d27bfd134215209f85d2f) nautilus (stable)": 3
    },
    "mgr": {
        "ceph version 14.2.11-394-g9cbbc473c0 (9cbbc473c02686761b4d27bfd134215209f85d2f) nautilus (stable)": 3
    },
    "osd": {
        "ceph version 14.2.11-394-g9cbbc473c0 (9cbbc473c02686761b4d27bfd134215209f85d2f) nautilus (stable)": 36
    },
    "mds": {
        "ceph version 14.2.11-394-g9cbbc473c0 (9cbbc473c02686761b4d27bfd134215209f85d2f) nautilus (stable)": 3
    },
    "rgw": {
        "ceph version 14.2.11-394-g9cbbc473c0 (9cbbc473c02686761b4d27bfd134215209f85d2f) nautilus (stable)": 3
    },
    "overall": {
        "ceph version 14.2.11-394-g9cbbc473c0 (9cbbc473c02686761b4d27bfd134215209f85d2f) nautilus (stable)": 48
    }
}

# Steps to reproduce #

```
helm install --namespace "naret-csi-cephfs" "naret-csi-cephfs" ceph-csi/ceph-csi-cephfs --set nodeplugin.httpMetrics.containerPort=8082

cat > storageclass-cephfs-naret.yml << EOF
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: cephfs-naret
provisioner: cephfs.csi.ceph.com
parameters:
   clusterID: 63334166-d991-11eb-99de-40a6b72108d0
   fsName: cephfs
   csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
   csi.storage.k8s.io/provisioner-secret-namespace: msopena
   csi.storage.k8s.io/controller-expand-secret-name: csi-cephfs-secret
   csi.storage.k8s.io/controller-expand-secret-namespace: msopena
   csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
   csi.storage.k8s.io/node-stage-secret-namespace: msopena
   volumeNamePrefix: "rigi-"
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
   - discard
EOF

kubectl create -f storageclass-cephfs-naret.yml

cat > test.yaml << EOF
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "pvc-test"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "cephfs-naret-kernel"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: test
          mountPath: /tmp/test
      volumes:
      - name: test
        persistentVolumeClaim:
          claimName: "pvc-test"
EOF

kubectl create -f test.yaml

$ kubectl exec -it nginx-7656f7c468-gz87d -- ls -alsh /tmp/test
total 512
512 drwxrwxrwx 2 root root  0 Dec 10 10:54 .
  0 drwxrwxrwt 1 root root 18 Dec 10 15:34 ..
$ kubectl exec -it nginx-7656f7c468-gz87d -- mkdir /tmp/test/test
$ kubectl exec -it nginx-7656f7c468-gz87d -- touch /tmp/test/test/test.file
$ kubectl exec -it nginx-7656f7c468-gz87d -- chmod -R 0600 /tmp/test/test
chmod: cannot access '/tmp/test/test/test.file': Permission denied
command terminated with exit code 1
$ kubectl exec -it nginx-7656f7c468-gz87d -- ls -alsh /tmp/test/test
ls: cannot access '/tmp/test/test/test.file': Permission denied
total 1.0K
512 drw------- 2 root root 0 Dec 10 15:36 .
512 drwxrwxrwx 3 root root 0 Dec 10 15:35 ..
  ? -????????? ? ?    ?    ?            ? test.file
command terminated with exit code 1
```

1. Setup csi cephfs as described above
2. create credentials, configmap, storage class etc
3. create pvc and mount it a container
4. create new folder in mounted volume
5. create a file in folder created in step 4.
6. change permissions recursively (chmod -R 0600) on folder created on step 4.
7. you should get a permision denied message from running previous command
8. if list permissions of files within the folder, you could see metadata is corrupted (example above)

# Actual results #

after changing permissions in folder, files inside becomes corrupted which means metadata is missing

# Expected behavior #

I would expect to have files permissions updated

# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC resize please attach complete logs of below containers.

- csi-resizer and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in snapshot creation and deletion please attach complete logs
of below containers.

- csi-snapshotter and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC mounting please attach complete logs of below containers.

- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
  plugin pod from the node where the mount is failing.

- if required attach dmesg logs.

**Note:-** If its a rbd issue please provide only rbd related logs, if its a
cephFS issue please provide cephFS logs.

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by Madhu-1** [comment]
```
[root@dhcp53-170 cephfs]# kubectl create -f test.yaml 
persistentvolumeclaim/pvc-test created
deployment.apps/nginx created
[root@dhcp53-170 cephfs]# kubectl exec -it nginx-54c8dbf8c7-2f6ss -- ls -alsh /tmp/test
total 4.0K
   0 drwxrwxrwx 2 root root    0 Jan 10 06:08 .
4.0K drwxrwxrwt 1 root root 4.0K Jan 10 06:09 ..
[root@dhcp53-170 cephfs]# kubectl exec -it nginx-54c8dbf8c7-2f6ss -- mkdir /tmp/test/test
[root@dhcp53-170 cephfs]# kubectl exec -it nginx-54c8dbf8c7-2f6ss -- touch /tmp/test/test/test.file
[root@dhcp53-170 cephfs]# kubectl exec -it nginx-54c8dbf8c7-2f6ss -- chmod -R 0600 /tmp/test/test
[root@dhcp53-170 cephfs]# kubectl exec -it nginx-54c8dbf8c7-2f6ss -- ls -alsh /tmp/test/test
total 0
0 drw------- 2 root root 1 Jan 10 06:10 .
0 drwxrwxrwx 3 root root 1 Jan 10 06:10 ..
0 -rw------- 1 root root 0 Jan 10 06:10 test.file
```

@Masber i tried above reproducer nothing is failing for me.
