### ISSUE TITLE
Provide hints to the plugin binaries on their roles

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#271]
Currently each plugin (CephFS or rbd in their Run routines), create and start all 3 services (Identity, Node and Controller). This is incorrect, but does not cause issues, as the consumer of these services are the k8s sidecars, which are selectively installed with the plugin. Hence, due to the sidecars the right services get used.

Suggest that we make this configurable, such that only the required services are created and started. Such a configuration also provides the feasibility in the future to do certain controller level tasks in the startup (for now load the config maps etc.) and avoid them on node services, and vice versa.

**Comment by gman0** [comment]
Could you please elaborate how is this incorrect? The CSI spec allows either of those configurations. Anyway, as you pointed out, there could be some advantages.

**Comment by tombarron** [comment]
> The CSI spec allows either of those configurations.

Yeah, it explicitly a variety of [deployment architectures](https://github.com/container-storage-interface/spec/blob/master/spec.md#architecture) including ones where "unified Plugin component supplies both the Controller Service and Node Service."  Still worth considering the advantages w.r.t. doing some specialized tasks in startup, I'm not disagreeing with that.

**Comment by ShyamsundarR** [comment]
This is how I see it.
- At present we [create](https://github.com/ceph/ceph-csi/blob/csi-v1.0/pkg/rbd/rbd.go#L117-L123) and [start](https://github.com/ceph/ceph-csi/blob/csi-v1.0/pkg/rbd/rbd.go#L130) CS, NS and IS on all instances of the plugin
- IS running on all instances of the plugin is required
- CS in our case should run only as a singleton in the cluster, hence creating and starting a listener for the CS in each running instance of the plugin looks incorrect
- NS should run on all nodes, and we deploy the same using a DaemonSet, but the StatefulSet that deploys the provisioner would also create/listen on an instance of the NS, which looks incorrect

Why it still works is because, the client end of the listeners that we create are the kubernetes sidecars, and each deployment only packages either the provisioner or the node driver as required, and hence we do not see requests for the other in our running instances.

Side note: The IS as per the spec should claim all capabilities in GetPluginCapabilities hence that would not be specialized based on the actual components the plugin is running.

The unified plugin example in the spec to my understanding, is applicable when we can run CS on all nodes of the cluster and not as a singleton as in our case. IOW, I believe the unified case is not about code layout, but capabilities of each instance that is running, hence we can have the same binary, but we need to ensure we start listening on services that we would serve, and not all.

**Comment by dillaman** [comment]
> The unified plugin example in the spec to my understanding, is applicable when we can run CS on all nodes of the cluster and not as a singleton as in our case.

Forgive my ignorance in this matter, but is there any technical reason why the CS cannot run on all nodes? Does the CO ensure that only a single CS receives a given request (except in failure cases) [1] or are the requests multicasted to all listening CS instances so it would become a coordination issue between CS instances to determine which one is needed to actually perform the work?

[1] https://github.com/container-storage-interface/spec/blob/master/spec.md#concurrency

**Comment by ShyamsundarR** [comment]
> > The unified plugin example in the spec to my understanding, is applicable when we can run CS on all nodes of the cluster and not as a singleton as in our case.
> 
> Forgive my ignorance in this matter, but is there any technical reason why the CS cannot run on all nodes? Does the CO ensure that only a single CS receives a given request (except in failure cases) [1] or are the requests multicasted to all listening CS instances so it would become a coordination issue between CS instances to determine which one is needed to actually perform the work?
> 
> [1] https://github.com/container-storage-interface/spec/blob/master/spec.md#concurrency

In my understanding, the limitation at present comes from co-ordination requirements within our plugin implementation. As we use config maps that are closely managed by the CS to store created volumes and their respective CO generated volNames and such, we need strict/locked access to the same to ensure it's consistency. Further, we depend on name hash based locks to ensure idempotency of requests, and also to prevent same requests racing with each other. These cause us to remain a singleton.

Side note (again): I have also heard desire to retain it as such (single instance) for the simplicity it provides, and the lack of coordination requirements that otherwise must be implemented, and I relate and agree to the desire (till the request queue would overwhelm the single instance and service times starts increasing).

I do not see it mentioned anywhere about any assurances that the CO provides, regarding a single in-flight call per volume, on the contrary as you point out it is not guaranteed by the CO.

I am not aware if the CO would multicast requests or how they may behave.

**Comment by gman0** [comment]
You've raised good points, @ShyamsundarR . My question is however, whose job is it to ensure that the CS is being run as a singleton: if it's the operator's responsibility, then I guess it's not that much different from how we're doing it now already...although being more explicit about the fact that one particular instance of the plugin runs with CS couldn't hurt. If the plugin is the one who ensures that there's only one instance of CS active at a time, we'd need proper locking on back-end (in which case we better do it properly and not rely on the assumption that there _might_ be only one instance of CS running), or having some sort of leader election.

**Comment by gman0** [comment]
I'm just reading between the lines because the spec doesn't seem to be very clear on the subject, in the [Architecture](https://github.com/container-storage-interface/spec/blob/master/spec.md#architecture) section it states that:
> It SHOULD be possible to ship cross-CO compatible Plugins for a variety of deployment architectures. A CO SHOULD be equipped to handle both centralized and headless plugins, as well as split-component and unified plugins. Several of these possibilities are illustrated in the following figures.

my guess is that we, as storage providers, may demand that the plugin is running in such and such a way (and if those demands are not met then bad things may happen), [A CO SHOULD be equipped to handle] such deployment, and the operator should follow our deployment recommendations.

If this is how things are, it should be enough to add a `--is-controller` cmd flag and run the CS under the condition that the flag is supplied.

**Comment by ShyamsundarR** [comment]
> I'm just reading between the lines because the spec doesn't seem to be very clear on the subject, in the [Architecture](https://github.com/container-storage-interface/spec/blob/master/spec.md#architecture) section it states that:
> 
> > It SHOULD be possible to ship cross-CO compatible Plugins for a variety of deployment architectures. A CO SHOULD be equipped to handle both centralized and headless plugins, as well as split-component and unified plugins. Several of these possibilities are illustrated in the following figures.
> 
> my guess is that we, as storage providers, may demand that the plugin is running in such and such a way (and if those demands are not met then bad things may happen), [A CO SHOULD be equipped to handle] such deployment, and the operator should follow our deployment recommendations.

Agree, I would state the same.

> 
> If this is how things are, it should be enough to add a `--is-controller` cmd flag and run the CS under the condition that the flag is supplied.

This is how I was running it in one of my local branches, as I needed to do some startup work that was CS specific. So from an approach POV I acknowledge what you suggest, a bool stating WhoAmI equivalent.

Also, should we be adding cmd flags or using ENV variables? pod manifests seem to suggest using env variables more than CLI args (cmd vars), just dropping the thought here, to control bloat of cmd args.
