### ISSUE TITLE
Why is the copyright attributed to "The Kubernetes Authors"

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/ceph-csi#272]
Shouldn't the copyright for code original to ceph-csi be "The Ceph-CSI Authors" and code that's a modified copy-n-pasted could be attributed to both sources.

This looks like a case of copy-n-paste of headers to me. Any thoughts?

**Comment by rootfs** [comment]
PR please :)

**Comment by wilmardo** [comment]
@rootfs @phlogistonjohn @Madhu-1 

This can be closed now, the reference was lost somehow when merging the PR

**Comment by Madhu-1** [comment]
@wilmardo Thanks, closing
