### ISSUE TITLE
如何挂载一个已有的cephfs目录

### ISSUE THREAD

**Issue by zm274310577** [ceph/ceph-csi#2746]
使用ceph-deploy部署的ceph，可以创建pv来挂载cephfs的中已有的某个目录，如：
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-pv
  labels:
    pv: cephfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - 192.168.1.10:6789
      - 192.168.1.11:6789
    user: admin
    path: /test/path
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Delete

只要提供monitors、path、secret可以把cephfs上的/test/path目录挂载到pod的某个路径下，如/mnt/cephfs。那么从pod的/mnt/cephfs目录读取数据，就相当于从cephfs的/test/path中读取数据。

但是在rook中，无论csi中的 rbd 还是 cephfs，都是使用storageclass创建一个新的volume进行挂载。这样就不能使用cephfs中已有的数据了。

那位大神知道在rook中怎么实现挂载cephfs中已有目录的方法。万分感谢！

**Comment by nixpanic** [comment]
Sorry, not a lot of (if any) regular contributors will be able to read your language. Could you please elaborate it a little more, preferably in English? If you are reporting a problem, please include log messages from the start of the operation until the error happens.

**Comment by elrondwong** [comment]
这个issue应该可以解决你的问题 #1119 
参照[cephfs-static-pvc](https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md#cephfs-static-pvc)

**Comment by Madhu-1** [comment]
Closing this one. please feel free to open/update the issue with the template in English. and the above static PV is not as per the doc https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md#create-cephfs-static-pv.
