### ISSUE TITLE
[csi-cephfs] cache entries are not cleaned up when provision="false"

### ISSUE THREAD

**Issue by LiGeNvidia** [ceph/ceph-csi#275]
When using csi-cephfs with `provision="false"`, the cache entries are not being deleted (1, 2). This would cause the number of configmaps to store csi-cephfs to grow indefinitely:

```
> kubectl get cm | grep csi-cephfs
csi-cephfs-pvc-0037de92-45e2-11e9-a076-988609043c26   1      7d21h
csi-cephfs-pvc-155adb4f-468c-11e9-8a88-9886098cc473   1      7d
csi-cephfs-pvc-2dddceae-45e7-11e9-bbf0-988609bd0a19   1      7d20h
csi-cephfs-pvc-5bbd81db-45e3-11e9-bbf0-988609bd0a19   1      7d20h
csi-cephfs-pvc-6ac96392-45e7-11e9-8a88-9886098cc473   1      7d20h
csi-cephfs-pvc-766d74ee-45e6-11e9-8a88-9886098cc473   1      7d20h
csi-cephfs-pvc-838e24ee-4bed-11e9-8a88-9886098cc473   1      4h24m
csi-cephfs-pvc-bbd3c8df-45e8-11e9-8a88-9886098cc473   1      7d20h
```

1: https://github.com/ceph/ceph-csi/blob/csi-v1.0/pkg/cephfs/controllerserver.go#L131-L135
2: https://github.com/ceph/ceph-csi/blob/csi-v1.0/pkg/cephfs/controllerserver.go#L166

**Comment by Madhu-1** [comment]
@LiGeNvidia Thanks for pointing out the issue, would you like to send a PR to fix this one?

**Comment by Madhu-1** [comment]
as we are moved  configmap to rados omap to  store volume and snapshot information, this issue is no more valid
