### ISSUE TITLE
[csi-rdb] Mount snashopt in pod for backups, it is possible?

### ISSUE THREAD

**Issue by de1m** [ceph/ceph-csi#277]
Hi, sorry, I have't found the info about my question.
I'll make a snapshot and then mount this snapshot in a pod, where I can create a backup of this data. 
Can I mount the snapshot directly in a pod, without convert this to an image?

**Comment by ShyamsundarR** [comment]
There is no way in CSI to allow a mount of a snapshot. The way the protocol is written is to only support mounting of created volumes. Thus, for the case of backup, a snapshot once taken needs to be converted to a volume and then mounted and backed up.

IOW, this [yaml](https://github.com/ceph/ceph-csi/blob/b0d6737db81e2ba658514ea2ab19d043caa0b43f/examples/rbd/pvc-restore.yaml#L1) example in the code repository needs to be used to convert a snapshot taken to a volume, for use within a pod to backup the same.

**Comment by leseb** [comment]
@ShyamsundarR is right, snapshots are read-only so they are not intended for pod's consumption.

**Comment by de1m** [comment]
okay, thank you, then I close this "issue"
