### ISSUE TITLE
Attacher fails to communicate with the provided socket as there is no listener

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#278]
Branch: csi-v1.0

Recent change to the attacher YAML has changed it's communication socket form csi.sock to csi-attacher.sock, but there are no listeners (or even creators) of the same. Hence attach requests are failing if a new CSI instance is deployed using the provided deploy yaml manifests.

The fix though seems not to be to change the socket back to csi.sock, as this socket is being serviced by the node-driver-registrar that is NOT responsible for attacher RPC calls.

The attacher service calls the RPCs [Controller[un]Publish](https://github.com/kubernetes-csi/external-attacher#csi-attacher) calls and these are part of the provisioner pods and not the node plugin pods.

The ideal fix hence seems to be to run the attacher as a part of the provisioner pod, than a standalone that can run in any pod.

NOTE: It is currently working as calls to ControllerPublish/Unpublish are [No-Ops](https://github.com/ceph/ceph-csi/blob/ff7d649c9dc9667baf2f1d27f358193a43cee162/pkg/rbd/controllerserver.go#L367) in the code, and hence node or provisioner service responding to the same does not change the outcome.

As a result removing RPC_PUBLISH_UNPUBLISH_VOLUME capability and removing the attacher pod as well from the deployment is another solution to the problem (possibly a better one for the moment).

Thoughts?

**Comment by gman0** [comment]
Neither rbd nor cephfs csi drivers need the attachment RPCs, I'd vote for removing the external-attacher completely (and adding cluster-driver-registrar)

**Comment by Madhu-1** [comment]
Yeah i will go for option 2, currently am working on removing attacher from both cephfs and rbd, i will send a patch for same.

**Comment by Madhu-1** [comment]
Fixed in #290
