### ISSUE TITLE
use rbd internal image-level encryption

### ISSUE THREAD

**Issue by tareksha** [ceph/ceph-csi#2782]
# Describe the feature you'd like to have #

Starting with pacific, ceph can handle image-level encryption internally by the rbd framework:
https://docs.ceph.com/en/pacific/rbd/rbd-encryption/

ceph-go already exposes the necessary APIs:
https://pkg.go.dev/github.com/ceph/go-ceph@v0.13.0/rbd#Image.EncryptionFormat
https://pkg.go.dev/github.com/ceph/go-ceph@v0.13.0/rbd#Image.EncryptionLoad

Currently ceph-csi still performs its own LUKS operations on top of the RBD mapping layer. This responsibility is seemingly redundant now and can be taken down for ceph clusters running pacific or newer versions.

The switch does not have to be breaking. A more general "encryption layer" flag can be added to choose between the the current implementation and the one provided by rbd, something like:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
...
parameters:
  ...
  encryptionLayer: "rbd|csi"
```
A value of `csi` can be assumed if the exsting flag `encrypted` is set to `true`.

# What is the value to the end user? (why is it a priority?) #

1. Offload responsibility of encryption implementation from ceph-csi to the underlying RBD layer.
2. Focus on passphrase lifecycle in the context of CSI and kubernetes.

# How will we know we have a good solution? (acceptance criteria) #

1. Encryption logics (LUKS operations) removed from ceph-csi code.
2. RBD APIs for image-level encryption called from ceph-csi.

**Comment by Madhu-1** [comment]
cc @nixpanic

**Comment by tareksha** [comment]
hi @nixpanic any thoughts on this?
