### ISSUE TITLE
Helm charts not updated for release v3.5 

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2786]
# Describe the bug #

The helm charts on release 3.5 is still with `canary` and not been updated to release v3.5 specific tag, this issue will be tracking the same.

**Comment by humblec** [comment]
https://github.com/ceph/csi-charts/blob/master/docs/rbd/ceph-csi-rbd-3.5.0.tgz has the correct tags .

**Comment by Madhu-1** [comment]
closing this one as the charts are available.
