### ISSUE TITLE
Need to change from using 0 as the initializer value for keymutex based hash locks

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#279]
Currently the code uses ["k8s.io/kubernetes/pkg/util/keymutex"](https://github.com/kubernetes/utils/blob/master/keymutex/hashed.go#L30) based hash mutex lock scheme.

All lock initialization pass in a value of 0 for the count of hash buckets (or # mutexes to use). 0 is a special value that keymutex computes as NumCPU and allocates as many hash buckets.

These locks are used for VolName and VolID derived hashes, thus when using only #CPU number of locks, there is a lot of contention or potential contention in create/delete and other requests that acquire the same bucket numbered locks.

The work done within these locks are not CPU bound, as we make one or more CLI calls to create images or directories, or mount before performing certain activities, etc. As a result, using only #CPU number of locks, only increases contention for these locks.

Suggested way forward is to instead decide on a saner default  number of locks, and change all non-CPU bound locks to this value instead.

I suggest we start this out at 128, which is 28 more than [worker threads](https://github.com/kubernetes-csi/external-provisioner/blob/master/cmd/csi-provisioner/csi-provisioner.go#L57) of the provisioner at present, OR closely set this to the same value as worker threads in our side car deploy yaml.

NOTE: When testing delete volumes in bulk ('bulk' was just 5 deletes simultaneously), one of the deletes hung for more than 9 seconds on a lock. This caused the RPC to time out and send the delete request again, but as elaborated above the delete need not have waited for a lock slot for so long.

**Comment by gman0** [comment]
Recently I've implemented a bit different synchronization scheme for csi-manila which is imho better than either of those approaches...i can post a PR once things settle down (esp. the branches and your PRs)
