### ISSUE TITLE
Remove thickprovision deprecated code from devel branch

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2795]
As we have already deprecated the thick provisioning in https://github.com/ceph/ceph-csi/pull/2589 and it's already part of 3.5.0 we can plan to remove the support in 3.6.0. This issue is to track the same. 

@nixpanic couple of questions
*  Is it a good time to remove this from the devel branch or should we wait?
* What are the operations we need to support for already created images
       Mounting/Unmount should be enough?

**Comment by nixpanic** [comment]
>     * Is it a good time to remove this from the devel branch or should we wait?

This would surely be a good time. We do not plan to improve the feature anyway.

>     * What are the operations we need to support for already created images
>       Mounting/Unmount should be enough?

There is some metadata attribute in the RBD-image set. This can be removed in case it exists, but it also does not hurt to keep it. I do not think we need to pass special options for mounting anymore either. The metadata attribute would just be ignored. The CSI-Addons ReclaimSpace operation ignores the attribute as well already.

**Comment by Madhu-1** [comment]
> > ```
> > * Is it a good time to remove this from the devel branch or should we wait?
> > ```
> 
> This would surely be a good time. We do not plan to improve the feature anyway.
> 
> > ```
> > * What are the operations we need to support for already created images
> >   Mounting/Unmount should be enough?
> > ```
> 
> There is some metadata attribute in the RBD-image set. This can be removed in case it exists, but it also does not hurt to keep it. I do not think we need to pass special options for mounting anymore either. The metadata attribute would just be ignored. The CSI-Addons ReclaimSpace operation ignores the attribute as well already.

Does this mean we can remove the current code in nodeplugin to map it as a normal rbd image without `notrim` option?

**Comment by kfox1111** [comment]
Does this affect existing volumes or just new volumes?

**Comment by Madhu-1** [comment]
@kfox1111 AFAIK Existing will also not work. you can manually add the `notrim` map/unmap option

**Comment by kfox1111** [comment]
K. was preemptively asking as I wasn't sure if I had any or not. Now the next question becomes, how do I know if I have any? :)

**Comment by Madhu-1** [comment]
You can check below

* Check if any storageclass has `"thickProvision": "true"` parameter set
* check if any rbd image contains `rbd.csi.ceph.com/thick-provisioned` metadata set
