### ISSUE TITLE
switch to quay.io to use latest ceph releases

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2796]
ceph releases are not up to date in the docker.io but they are up to date in the quay.io, As we are dependent on the base ceph image we should switch to quay.io to use the latest ceph images.

**Comment by travisn** [comment]
This affects 3.5? Could we get a 3.5.1 release to include the new base image in time for the upstream rook release tomorrow?

**Comment by Madhu-1** [comment]
```
docker inspect quay.io/cephcsi/cephcsi:v3.5.0 |grep -i release
                "CEPH_POINT_RELEASE=-16.2.5",
                "CEPH_POINT_RELEASE": "-16.2.5",
                "RELEASE": "HEAD",
                "CEPH_POINT_RELEASE=-16.2.5",
                "CEPH_POINT_RELEASE": "-16.2.5",
                "RELEASE": "HEAD",
```
3.5.0 is still using 16.2.5, latest ceph release is 16.2.7 in quay.io https://quay.io/repository/ceph/ceph?tab=tags

**Comment by Madhu-1** [comment]
Yes, we can do it. we need a couple of PR's to use the latest ceph image from the quay.io. @ceph/ceph-csi-maintainers any thoughts?
