### ISSUE TITLE
Remove "KMS_PROVIDER" registration of "kp-metadata" from IBM key protect implementaiton

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#2816]
# Describe the bug #

Release 3.5 has placed the registration as "kp-metadata" which has been changed to "ibmkeyprotect" in latest updates, The old key will be deprecated with 3.5.2 and then removed with 3.6 release of ceph csi. This issue track the same.
```
 // RegisterProvider for kmsTypeKeyProtectMetadataOld is kept here for backward compatibility. 
```

Refer https://github.com/ceph/ceph-csi/pull/2812

**Comment by Madhu-1** [comment]
> The old key has to be deprecated with 3.6 release of ceph csi. This issue track the same.

@humblec the old key will be deprecated in the 3.5.1 release and in 3.6 it should be removed?

**Comment by humblec** [comment]
> > The old key has to be deprecated with 3.6 release of ceph csi. This issue track the same.
> 
> @humblec the old key will be deprecated in the 3.5.1 release and in 3.6 it should be removed?

you mean deprecated in 3.5.2 and ... ?

**Comment by Madhu-1** [comment]
> > > The old key has to be deprecated with 3.6 release of ceph csi. This issue track the same.
> > 
> > 
> > @humblec the old key will be deprecated in the 3.5.1 release and in 3.6 it should be removed?
> 
> you mean deprecated in 3.5.2 and ... ?

Yes deprecated it in 3.5.2

**Comment by humblec** [comment]
> > > The old key has to be deprecated with 3.6 release of ceph csi. This issue track the same.
> > 
> > 
> > @humblec the old key will be deprecated in the 3.5.1 release and in 3.6 it should be removed?
> 
> you mean deprecated in 3.5.2 and ... ?

updated it as 3.5.2 deprecation and 3.6 removal.
