### ISSUE TITLE
Run cephcsi upgrade with latest ceph-csi release

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#2818]
Currently, we are running upgrade tests with deprecated cephcsi release (3.3.1), This is fine for the 3.4.0 release but the upgrade tests in the devel branch and 3.5.0 branch should run only with the last latest released version, not the deprecated one.

**Comment by karthik-us** [comment]
@Madhu-1 I guess this can be closed since the [patch](https://github.com/ceph/ceph-csi/pull/3994) updated the upgrade version to latest (v3.9.0) and the [patch](https://github.com/ceph/ceph-csi/pull/4008) gives the flexibility to update the version as per the version mentioned in the `build.env`.
