### ISSUE TITLE
Bugs references in values.yaml are marked as solved upstream

### ISSUE THREAD

**Issue by sbskas** [ceph/ceph-csi#2825]
https://github.com/ceph/ceph-csi/blob/f82260068940aa4d5c5fe45c8f566ec22ca38028/charts/ceph-csi-rbd/values.yaml#L430-L436

According to the two links provided in the config files, both issue have been solved.
Are those values still revelant to be set as there are workarounds for those issues ?

**Comment by humblec** [comment]
@Rakshith-R or @Madhu-1 I remember some discussion we had on this topic..

**Comment by humblec** [comment]
Thanks @Rakshith-R 

This should be done soon with the above PR in place @sbskas :+1:
