### ISSUE TITLE
Wrong dataPool referenced when creating pv with topologyconstrainedPools

### ISSUE THREAD

**Issue by sbskas** [ceph/ceph-csi#2828]
Using erasure-coded constrainedDataPools as follow:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: block-topology-ec
provisioner: ceph.rbd.csi.ceph.com
parameters:
    clusterID: test

    imageFormat: "2"
    imageFeatures: layering


    pool: default-replicated
    dataPool: default-erasure

    topologyConstrainedPools: |
      [
        {
          "poolName": "pool-replicated-zone1",
          "dataPool": "pool-erasure-zone1",

          "domainSegments": [
            {
              "domainLabel":"zone",
              "value":"zone1"
            }
          ]
       },
       {
          "poolName": "pool-replicated-zone2",
          "dataPool": "pool-erasure-zone2",

          "domainSegments": [
            {
              "domainLabel":"zone",
              "value":"zone2"
            }
          ]
       },
       {
          "poolName": "pool-replicated-zone3",
          "dataPool": "pool-erasure-zone3",
          
          "domainSegments": [
            { 
              "domainLabel":"zone",
              "value":"zone3"
            }
          ]
       }
      ]

volumeBindingMode: WaitForFirstConsumer
```
And proper tagging of the nodes (topology.kubernetes.io/zone: zone1/2/3), deploying topology contrained pool works ok.
```
rbd  -p pool-replicated-zone3  -p pool-replicated-zone3 info csi-vol-386734ac-7edd-11ec-a2c5-3a73ec2b3d1a|grep pool
	data_pool: pool-erasure-zone3
	features: layering, data-pool
```
However, dataPool referenced in PV is set as the default data-pool.
```
kubectl get pv pvc-5d721f53-6cb3-4b19-bb1b-3a72ff55bf89 -o yaml |grep -i -e pool  -e handle
      dataPool: default-erasure
      journalPool: repldefault
      pool: pool-replicated-zone3
    volumeHandle: 0001-0009-rook-ceph-0000000000000005-386734ac-7edd-11ec-a2c5-3a73ec2b3d1a
```

**Comment by sbskas** [comment]
The problem seems to be here:
https://github.com/ceph/ceph-csi/blob/a553157b15e33f73b1c71b63be18f0474e757091/internal/rbd/controllerserver.go#L165-L169

It's doesn't update the volumeContext["dataPool"].

**Comment by Madhu-1** [comment]
@sbskas is it causing any functionality issue? or its just a wrong data is show in PV object?

**Comment by sbskas** [comment]
No functionality is impacted as far as I know. Only recorded information is wrong.
I don't know about rook behaviour in case of wrong data in the pv.

**Comment by Madhu-1** [comment]
> No functionality is impacted as far as I know. Only recorded information is wrong. I don't know about rook behaviour in case of wrong data in the pv.

no problem with Rook. Rook doesn't do anything with this data, its only for cephcsi

**Comment by sbskas** [comment]
So no functionnality impacted as far as I see.
PV datapool is just wrong.
You cannot rely on the information with `kubectl get pv`.
You have to fire a `rbd image info` to get the correct information.

**Comment by Madhu-1** [comment]
Yes, I just wanted to understand is there any functional problem. as your PR is fixing the problem we can take that in.

**Comment by humblec** [comment]
> So no functionnality impacted as far as I see. PV datapool is just wrong. You cannot rely on the information with `kubectl get pv`. You have to fire a `rbd image info` to get the correct information.

Yeah, this need to be fixed. Thanks for catching it @sbskas :+1:
