### ISSUE TITLE
[chart] ConfigMap conflict between ceph-csi-rbd and ceph-csi-cephfs

### ISSUE THREAD

**Issue by sgissi** [ceph/ceph-csi#2858]
# Describe the bug #

When deploying both **ceph-csi-rbd** and **ceph-csi-cephfs** in the same namespace, there is a conflict on ConfigMap ceph-config because the resource name is hard coded:
https://github.com/ceph/ceph-csi/blob/de2489ed7d3afb1322c12ad6ec4f5cc57fe38f81/charts/ceph-csi-rbd/templates/ceph-conf.yaml#L4
https://github.com/ceph/ceph-csi/blob/de2489ed7d3afb1322c12ad6ec4f5cc57fe38f81/charts/ceph-csi-cephfs/templates/ceph-conf.yaml#L4

Right now this issue is blocking the upgrade from ~~3.3.1~~ 3.4.0 to 3.5.1 in my cluster.

# Expected behavior #

Similar solution as CSI config: to suppress creation https://github.com/ceph/ceph-csi/blob/de2489ed7d3afb1322c12ad6ec4f5cc57fe38f81/charts/ceph-csi-rbd/templates/csiplugin-configmap.yaml#L1
And/or have a configurable name: https://github.com/ceph/ceph-csi/blob/de2489ed7d3afb1322c12ad6ec4f5cc57fe38f81/charts/ceph-csi-rbd/templates/csiplugin-configmap.yaml#L5

Please let me know which solution is acceptable and I'll be happy to send a PR.

Thank you!

**Comment by humblec** [comment]
@sgissi does upgrade work from 3.3.1 to 3.4.0 ?

**Comment by sgissi** [comment]
> @sgissi does upgrade work from 3.3.1 to 3.4.0 ?

My typo, I was running 3.4.0 already, I edited my text. The ceph-config ConfigMap was introduced on commit https://github.com/ceph/ceph-csi/commit/d22e7a1bdb01da31633147f5c920879d8a590d5e which was released on 3.5.0.

Would a patch introducing "externallyManagedCephConfigMap" and "cephConfigMapName" be acceptable?

**Comment by Madhu-1** [comment]
@sgissi having configmap name configurable looks good.
