### ISSUE TITLE
DocRequired: deployment of examples for cephfs

### ISSUE THREAD

**Issue by hongkailiu** [ceph/ceph-csi#287]
It would be nice to have more docs on [examples/cephfs](https://github.com/ceph/ceph-csi/tree/csi-v1.0/examples/cephfs).

Also I got a question ceph-csi in general:
For example, the [sc defined in rook repo](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/storageclass.yaml) can also be used to provision rbd PVCs. What is the difference if we use the [one defined here](https://github.com/ceph/ceph-csi/blob/csi-v1.0/examples/rbd/storageclass.yaml)?

For cephfs, there is no such provisioner or sc defined in rook. [openshift/external-storage](https://github.com/openshift/external-storage/tree/master/ceph/cephfs/deploy) provides those with [some restrictions](https://bugzilla.redhat.com/show_bug.cgi?id=1676953). That is the reason that I was suggested by @travisn to explore options here until @ShyamsundarR reminds me that [Requires Kubernetes 1.13](https://github.com/ceph/ceph-csi/blob/csi-v1.0/docs/deploy-cephfs.md#deployment-with-kubernetes) and OCP is with

```
$ oc version --short
Client Version: v4.0.22
Server Version: v1.12.4+7cf6a84
$ oc get clusterversion
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.0.0-0.nightly-2019-03-25-180911   True        False         3h35m   ...
```

**Comment by hongkailiu** [comment]
OCP 4.1 uses k82 1.13.
Any doc about ceph-csi and ocp4.1?

```
$ oc version --short
Client Version: v4.0.0-alpha.0+858c9f7-2002-dirty
Server Version: v1.13.4+2e01d67

$ oc get clusterversion
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.1.0-0.nightly-2019-05-08-131137   True        False         25h     Cluster version is 4.1.0-0.nightly-2019-05-08-131137

$ oc get nodes ip-172-31-130-237.us-west-2.compute.internal
NAME                                           STATUS   ROLES    AGE   VERSION
ip-172-31-130-237.us-west-2.compute.internal   Ready    master   25h   v1.13.4+d34b8bd34

```

**Comment by humblec** [comment]
@hongkailiu we have addressed the documentation in various PRs and also have a support matrix..etc now. I believe this is addressed and if you see any missing documentation please open a new issue. I am closing this for now.
