### ISSUE TITLE
Maintain metadata information with RBD images

### ISSUE THREAD

**Issue by pkalever** [ceph/ceph-csi#2874]
# Describe the feature you'd like to have #

Maintain PV/PVC/NameSpace mapping with backed image within the RBD image metadata

# What is the value to the end user? (why is it a priority?) #

This helps Monitoring solutions without access to Kubernetes clusters to display the details of the PV/PVC/NameSpace in their dashboard.

# How will we know we have a good solution? (acceptance criteria) #

* Validate metadata is present after Create of a PV
* Validate metadata is updated after Provisioner pod is restarted
* Validate metadata is updated after a PVC deleted and PV is reattached to a new PVC

**Comment by nixpanic** [comment]
Is there a particular format that some monitoring application expects to be used? If there is a Ceph Dashboards that shows these kind of details already (for other cloud environments?), then Ceph-CSI should probably use the same format.

**Comment by humblec** [comment]
@pkalever this issue is on 3.6 release tracker , could you please revisit and adjust the milestone tracker accordingly?

**Comment by pkalever** [comment]
> @pkalever this issue is on 3.6 release tracker , could you please revisit and adjust the milestone tracker accordingly?

It is on 3.6 as desired. I don't think any changes are needed.

**Comment by humblec** [comment]
Shall we close this then @pkalever

**Comment by pkalever** [comment]
> Shall we close this then @pkalever

Once https://github.com/ceph/ceph-csi/pull/2898 is merged it will auto close

**Comment by humblec** [comment]
> > Shall we close this then @pkalever
> 
> Once #2898 is merged it will auto close

ah... there was also doc PR reference..  so got confused.. lets leave it to bot then
