### ISSUE TITLE
nodeplugin failed to mkdir "/etc/selinux"

### ISSUE THREAD

**Issue by Aste88** [ceph/ceph-csi#2876]
# Describe the bug #
Unable to update or deploy from fresh the ceph-ccsi-cephfs plugin because on error failed to mkdir "/etc/selinux": mkdir /etc/selinux: read-only file system

# Environment details #

- Image/version of Ceph CSI driver : default for helm chart 3.5.1
- Helm chart version : 3.5.1
- Kernel version : 5.15.16
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : default
- Kubernetes cluster version : v1.23.1
- Ceph cluster version : 16.2.7

# Steps to reproduce #

1. Setup details: virtualized Talos cluster
1. Deployment to trigger the issue: 
   $ helm install  ceph-csi-cephfs ceph-csi/ceph-csi-cephfs --values values.yaml
      values.yam contains csiConfig, prom scrape, change in configMapName
1. See error
   spec: failed to generate spec: failed to mkdir "/etc/selinux": mkdir /etc/selinux: read-only file system

# Expected behavior #

Probably a flag in the values to disable selinux mounts on non-selinux suupporting distros.

**Comment by nixpanic** [comment]
> Probably a flag in the values to disable selinux mounts on non-selinux suupporting distros.

Hi @Aste88, is that :point_up:  something you would be willing to contribute to the project?
