### ISSUE TITLE
e2e: docker.io: ErrImagePull "toomanyrequests"

### ISSUE THREAD

**Issue by gman0** [ceph/ceph-csi#2889]
# Describe the bug #

I can see following errors in e2e CI logs:
```
Feb 17 18:15:15.301: INFO: At 2022-02-17 18:05:23 +0000 GMT - event for csi-cephfs-demo-depl-5dc85944b6-d5hh6: {kubelet minikube} Failed: Error: ErrImagePull
Feb 17 18:15:15.301: INFO: At 2022-02-17 18:05:23 +0000 GMT - event for csi-cephfs-demo-depl-5dc85944b6-d5hh6: {kubelet minikube} Failed: Failed to pull image "docker.io/library/nginx:latest": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

Docker Hub's limits:
* 100 image requests per 6 hours for anonymous usage
* 200 image requests per 6 hours for users with free Docker account

Source: https://www.docker.com/increase-rate-limits

e2e tests deploy Pods with nginx images pulled from docker.io, and ceph-csi's CI (+ maybe other projects that are using it in parallel?)  has clearly hit this limit. Are there any alternatives that would allow unlimited pulls?

**Comment by gman0** [comment]
@nixpanic @Madhu-1 @humblec would quay.io be an acceptable substitute? Or something from gcr.io (it has offers `gcr.io/google-containers/alpine-with-bash:1.0` or `gcr.io/google-containers/busybox:latest`, but they are quite outdated... but maybe it's good enough for ceph-csi's `example/*.yaml`)? I found https://quay.io/repository/prometheus/busybox for example. Could we use any of these instead of docker.io's nginx?

https://github.com/ceph/ceph-csi/blob/4235178f7c53ee3e6eba8e37cb175623fc0a8cea/examples/cephfs/deployment.yaml#L20

**Comment by Madhu-1** [comment]
@gman0 this should not be a problem, these images are pre pulled from the internal registry https://github.com/ceph/ceph-csi/blob/ci/centos/mirror/images.txt#L22. If I am not mistaken never seen this issue in any CI jobs till now.

**Comment by gman0** [comment]
For example here https://jenkins-ceph-csi.apps.ocp.ci.centos.org/blue/organizations/jenkins/mini-e2e-helm_k8s-1.22/detail/mini-e2e-helm_k8s-1.22/2170/pipeline

**Comment by gman0** [comment]
It's always that deployment. I think it might be due to pull policy which is overriden by e2e...

https://github.com/ceph/ceph-csi/blob/ac6bfeb6ef5483ca48ed277d3a788b9644a6700a/e2e/pod.go#L246-L256

https://github.com/ceph/ceph-csi/blob/ac6bfeb6ef5483ca48ed277d3a788b9644a6700a/e2e/deployment.go#L57-L66

**Comment by Madhu-1** [comment]
Yes, it could be. @gman0 can you send a fix to use notpresent pull policy?
