### ISSUE TITLE
Mounting RBD as block device to POD end with error

### ISSUE THREAD

**Issue by tavoda** [ceph/ceph-csi#2894]
# Describe the bug #
CSI generate long volume handler which leads to error in kubernetes:
Feb 21 18:22:30 kube04 systemd[1]: Failed to generate valid unit name from path '/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-d222a0af-9908-434a-a79f-4c23323f8acb/0001-0024-ae243d8e-a3b7-4aa8-a291-f4bd1edbb692-0000000000000005-7f9798c9-92fe-11ec-b7b8-468c46dd0c5b', ignoring mount point: File name too long

# Environment details #

- Image/version of Ceph CSI driver :
v3.5.1

- Kernel version :
Linux kube04 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux

- Kubernetes cluster version :
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

- Ceph cluster version :
ceph version 16.2.7 (f9aa029788115b5df5eeee328f584156565ee5b7) pacific (stable)

# Steps to reproduce #
Kubernetes cluster with calico networking
Create RBD CSI storage like described in https://docs.ceph.com/en/latest/rbd/rbd-kubernetes/
After kubectl exec to 'pod-with-raw-block-volume' from previous sample mount command ends with:
    mount: /QQ: cannot mount /dev/rbd0 read-only.
Of course filesytem is created on device and when I mount it in host, everything works
Host /var/log/daemon.log contains following error:
    Feb 21 18:37:20 kube04 systemd[1]: Failed to generate valid unit name from path '/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-d222a0af-9908-434a-a79f-4c23323f8acb/0001-0024-ae243d8e-a3b7-4aa8-a291-f4bd1edbb692-0000000000000005-7f9798c9-92fe-11ec-b7b8-468c46dd0c5b', ignoring mount point: File name too long

# Expected behavior #
Mounted volume

# Logs #
- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
I0221 17:44:44.934976    1126 utils.go:195] ID: 6181 GRPC request: {}
I0221 17:44:44.935001    1126 utils.go:202] ID: 6181 GRPC response: {}
I0221 17:45:44.934948    1126 utils.go:191] ID: 6182 GRPC call: /csi.v1.Identity/Probe
I0221 17:45:44.935165    1126 utils.go:195] ID: 6182 GRPC request: {}
I0221 17:45:44.935231    1126 utils.go:202] ID: 6182 GRPC response: {}
I0221 17:45:53.515884    1126 utils.go:191] ID: 6183 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0221 17:45:53.515982    1126 utils.go:195] ID: 6183 GRPC request: {}
I0221 17:45:53.516296    1126 utils.go:202] ID: 6183 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}},{"Type":{"Rpc":{"type":5}}}]}
I0221 17:45:53.517359    1126 utils.go:191] ID: 6184 GRPC call: /csi.v1.Node/NodeGetVolumeStats
I0221 17:45:53.517483    1126 utils.go:195] ID: 6184 GRPC request: {"volume_id":"0001-0024-ae243d8e-a3b7-4aa8-a291-f4bd1edbb692-0000000000000005-7f9798c9-92fe-11ec-b7b8-468c46dd0c5b","volume_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-d222a0af-9908-434a-a79f-4c23323f8acb/dev/50072985-1946-47d7-8d6a-5d6719ffead5"}
I0221 17:45:53.517657    1126 utils.go:202] ID: 6184 GRPC response: {"usage":[{"total":1073741824,"unit":1}]}
I0221 17:46:44.934841    1126 utils.go:191] ID: 6185 GRPC call: /csi.v1.Identity/Probe
I0221 17:46:44.934910    1126 utils.go:195] ID: 6185 GRPC request: {}
I0221 17:46:44.934936    1126 utils.go:202] ID: 6185 GRPC response: {}

**Comment by tavoda** [comment]
I tracked problem down to systemd on host system if you try this:
```
root@kube02# systemd-escape -p --suffix=mount "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-96b3a3a5-c494-4f77-87f4-05eedba25091/0001-0024-ae243d8e-a3b7-4aa8-a291-f4bd1edbb692-000000000000000a-4fd87529-95c8-11ec-ad5f-56c8229ed59b"
var-lib-kubelet-plugins-kubernetes.io-csi-volumeDevices-staging-pvc\x2d96b3a3a5\x2dc494\x2d4f77\x2d87f4\x2d05eedba25091-0001\x2d0024\x2dae243d8e\x2da3b7\x2d4aa8\x2da291\x2df4bd1edbb692\x2d000000000000000a\x2d4fd87529\x2d95c8\x2d11ec\x2dad5f\x2d56c8229ed59b.mount
```
It generates name which is 263 characters long and when systemd test for such file it crash with error. I found some fixes in systemd but best fix will be to generate shorter names for CSI produced volume names. Was ever somebody able to mount such volume?

You can emulate same error also on host system with following command:
```
root@kube02# systemd-mount "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-96b3a3a5-c494-4f77-87f4-05eedba25091/0001-0024-ae243d8e-a3b7-4aa8-a291-f4bd1edbb692-000000000000000a-4fd87529-95c8-11ec-ad5f-56c8229ed59b" /WW
Failed to start transient mount unit: Unit WW.mount failed to load properly: File name too long.

```
Debian testing has already fix for this bug: systemd 250 (250.3-2)

**Comment by tavoda** [comment]
Finally resolved it. You need new version of systemd. When you see following in your host log you are fine, this is only information message about mapping:
>  Failed to generate valid unit name from path '/var/lib/kubelet/plugins/ku....', ignoring mount point: File name too long

And for using mount command inside pod you need also privileged security context. Add to your deployment something like:

```
      volumeDevices:
        - name: data
          devicePath: /dev/rbd0
      securityContext:
        privileged: true
```

**Comment by JoeApo108** [comment]
Hi there, 

I'm also using provisioner: rbd.csi.ceph.com with `volumeMode: Block` as persistent storage. But I am unable to mount it without privilege escalation as I get the read-only permission limit. However, it works with @tavoda mentioned in his last post.

I need to know if it's intended behavior for CSI not to be able to mount RBD images without such escalation.

Thank you
