### ISSUE TITLE
rbd: Support Encrypted PVC clone to different storageclass

### ISSUE THREAD

**Issue by Rakshith-R** [ceph/ceph-csi#2901]
External-provisioner now supports pvc cloning to different storageclass.

https://github.com/kubernetes-csi/external-provisioner/pull/699

This needs some fixes for encryption and validation e2e.

**Comment by humblec** [comment]
Yeah and it helps a lot to users/customers.. so good to validate/qualify

**Comment by Rakshith-R** [comment]
Different storageclass PVC cloning  definitely fails if it is encrypted.

The fix will take time and we still have time till next external-provisioner release(which supports this feature). 
Moving it out of 3.6 release, maybe we can backport fix to a minor 3.6 minor release

**Comment by Rakshith-R** [comment]
This issue is fixed in https://github.com/ceph/ceph-csi/pull/3066.

**Comment by Madhu-1** [comment]
@Rakshith-R cloning across pools(different SC) is verified?

**Comment by Rakshith-R** [comment]
> @Rakshith-R cloning across pools(different SC) is verified?

no, Its not verified yet.
