### ISSUE TITLE
rbd: mapOptions `crush_location` cannot be used since it uses `:`

### ISSUE THREAD

**Issue by Rakshith-R** [ceph/ceph-csi#2910]
# Describe the bug #

mapOptions `crush_location` cannot be used since it uses `:` which is currently used as
a separator between mounter types.
`
E0301 10:19:13.615111    7348 utils.go:200] ID: 63 Req-ID: 0001-0009-rook-ceph-0000000000000001-fd37c41b-9948-11ec-ad32-0242ac110004 GRPC error: badly formatted map/unmap options: "krbd:read_from_replica=localize,crush_location=zone:zone1;"
`

This change was introduced in https://github.com/ceph/ceph-csi/pull/2643

cc @pkalever @ceph/ceph-csi-contributors

**Comment by Madhu-1** [comment]
@pkalever can you please take a look at this one? we need to fix this soon.
