### ISSUE TITLE
CephFS provisioner lack of documentation for dynamic provisioning

### ISSUE THREAD

**Issue by sf98723** [ceph/ceph-csi#2915]
# Describe the bug #

(This issue relies to a possible lack of documentation, so it could be re-qualified later as a feature request depending on the following)

The documentation seems to describe the userID capabilities [here](https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md) for static PVs but not the necessary and minimum Ceph caps that should be reported in the adminID field of the secret yaml for dynamic provisioning. It's quite weird to require (full ?) admin credentials without any details here and it can lead to configuration errors.

Indeed, we should not store these kind of credentials in the clear (base64 -d) in K8S secrets.

Could you specify in the capabilities.md part of the documentation more precisely what kind of ceph caps are required (minimum and sufficient) for the adminID config part of the provisioner, node stage and controller reported in the storage class YAML template ?

Otherwise it woulld be useful for users to understand why admin credentials are required here and not by the RBD provisioner or other CSI provisioners (spectrum scale …)

Thanks

# Environment details #

- Image/version of Ceph CSI driver : v3.5.1
- Helm chart version : - 
- Kernel version : 5.16.4-1.el7
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
`krbd` or `rbd-nbd`) : cephFS
- Kubernetes cluster version : 1.23.1
- Ceph cluster version : 16.2.6

# Steps to reproduce #

Create two users as described [here](https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md)

Create two secret yaml files you will find in the examples directory. One for provisioner and controller, the other for the node stage. 

Fill the user name and token in the secrets YAML (userID part ... and also adminID for the need of this test)

Fill the storage class to reflect these two secret definition for the provisioner controller and node stage

then kubectl storageclass.yaml and the two secrets 

# Actual results #

This user caps work only for static volumes as stated in the secret YAML template (userID only)

And Permission denied error 13 for dynamic provisioning.

# Expected behavior #

The exact specification for minimum and sufficient caps for a user or two (or three) users for the dynamic provisioner to succeed without a permission denied error 

# Logs #

Will post the provisioner logs later

**Comment by sf98723** [comment]
I've worked to restrict the admin capabilities this evening, with the same software configuration.

According to the ceph capabilities docs, I've tried to make it necessary and sufficient with these caps :

`[root@admin test]# ceph auth get client.admink8s`
`[client.admink8s]`
`	key = .........`
`	caps mds = "allow r, allow rw path=/volumes"`
`	caps mgr = "allow rw"`
`	caps mon = "allow r"`
`	caps osd = "allow rw tag cephfs data=test"`
`exported keyring for client.admink8s`

Note for the mgr caps that the [current requirements](https://docs.ceph.com/en/latest/cephfs/fs-volumes/) does not allow to be more restrictive.


Here is the result of the test :

**Ceph side** :

- create a new filesystem (not supported for ceph versions prior to 16/Pacific)

`ceph osd pool create test_data`
`ceph osd pool create test_metadata`
`ceph fs new test test_metadata test_data`

Then mount your filesystem with your favourite tools. My setup : /mnt/<ceph filesystems>, so I will mount this ceph filesystem in /mnt/test

**K8S** :

storageClass : `kubectl apply -f csi-cephfs-sc.yaml` (file attached)
secrets : `kubectl apply -f csi-cephfs-secret-node.yaml` and `kubectl apply -f csi-cephfs-secret-provisioner.yaml`. for dynamic provisioning you can provide only one secret (change the secrets settings in the storage class if you are doing so)
pod example : `kubectl apply -f nginx.yaml` (file attached) 

**At this point, I've faced the following issue :** (from provisioner logs): CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = Internal desc = rados: ret=-2, No such file or directory: "subvolume group 'csi' does not exist". 

The PVC is pending for creation, ceph-csi does not create the sub volume group (even with full admin caps)

Some guys have experienced this bug with [rook](https://github.com/rook/rook/issues/6183)

**back to Ceph:** (for the workaround)

Create the root volume with the CLI  : `ceph fs subvolumegroup create test csi`
It will create the root path _/volumes_ and the sub volume _csi_

**back to K8S**

`kubectl apply -f nginx.yaml`

Here it is !

The PV claim and the PV have been created, PVC has bound 👍 

<img width="963" alt="Screenshot 2022-03-04 at 23 24 47" src="https://user-images.githubusercontent.com/76551275/156851158-ec3c144d-8e50-4ef5-b552-8d928d1fbbe7.png">

Check in the container, the ce-hrs PV is mounted as expected (fuse):

<img width="748" alt="Screenshot 2022-03-04 at 23 36 53" src="https://user-images.githubusercontent.com/76551275/156851345-47b87edc-c9f1-4666-aced-6e95fc9cd515.png">

On another server find . to the whole CephFS filesystem mount directory (first find before kubectl apply -f nginx.yaml, the second after it succeeds):

<img width="749" alt="Screenshot 2022-03-04 at 23 33 41" src="https://user-images.githubusercontent.com/76551275/156851465-0580ce0d-e7fc-468b-ae7e-0a19b5b1b0f9.png">

It seems to work but I've not tested it extensively.

To the development team : could you confirm these minimal "admin" caps are likely to work as expected ?

**Comment by sf98723** [comment]
[Archive.zip](https://github.com/ceph/ceph-csi/files/8189153/Archive.zip)

(yaml files used for this test)

**Comment by sf98723** [comment]
Another test later, created a new filesystem (dynfs)

It failed, with the following error : I0305 06:52:51.231616       1 controller.go:764] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = Internal desc = rados: ret=-1, Operation not permitted

Changed the admink8s caps as is :

`[client.admink8s]`
`	key = AQBB4......== `
`	caps mds = "allow"`
`	caps mgr = "allow *"`
`	caps mon = "allow *"`
`	caps osd = "allow *"`

(same caps as the client.admin user)

il failed.

Changed the secrets to the client.admin user... it worked...

Hmmm, ....

I seems not rely to a cache issue (since I changed the secret and behaviour changed). 

will check the code...

**Comment by christianhuth** [comment]
@sf98723 did you manage to make this work?
