### ISSUE TITLE
rbd-nbd: nbd modprobe failed

### ISSUE THREAD

**Issue by slehlib** [ceph/ceph-csi#2918]
Red Hat Enterprise Linux Server release 7.9 (Maipo)
kubernetes v1.21.1
csi v3.5.1
I execute /root/storage/ceph-csi/examples/cephfs/plugin-deploy.sh to deployer provisioner 
NAME                                            READY   STATUS             RESTARTS   AGE
csi-cephfsplugin-ppc4d                          2/3     CrashLoopBackOff   3          87s
csi-cephfsplugin-provisioner-84bb5b599c-gzs7f   5/6     CrashLoopBackOff   3          87s
csi-cephfsplugin-provisioner-84bb5b599c-k7dgb   5/6     CrashLoopBackOff   3          87s
csi-cephfsplugin-provisioner-84bb5b599c-nnqhn   0/6     Pending            0          87s
csi-cephfsplugin-ztpr7                          2/3     CrashLoopBackOff   3          87s

and i have this msg in ppods logs

W0304 12:23:20.578799       1 rbd_attach.go:210] rbd-nbd: nbd modprobe failed (an error (exit status 1) occurred while running modprobe args: [nbd]): "modprobe: FATAL: Module nbd not found in directory /lib/modules/3.10.0-1160.25.1.el7.x86_64\n"
I0304 12:23:20.689478       1 cephcsi.go:171] Driver version: canary and Git version: 3a64ee48c3eed8131ad8eef0a889a89d56ffab17
F0304 12:23:20.689566       1 cephcsi.go:217] failed to write ceph configuration file (open /etc/ceph/ceph.conf: read-only file system)
goroutine 1 [running]:

**Comment by pkalever** [comment]
NBD module is absent in RHEL 7.9. RHEL8.1 or higher has NBD loadable module. You can check this yourself by just running `modprobe nbd` command locally. However, for `rbd-nbd` mounter type, It is recommended to use RHEL8.4 or higher as they got most of the bugs fixed and hence appear to be stable.

If you want to use the default `krbd` mounter, you can safely ignore `modeprobe` error.

**Comment by slehlib** [comment]
Thanks for response 
can yo say me how ignore modeprob because all pod CrashLoopBackOff

**Comment by Rakshith-R** [comment]
```
F0304 12:23:20.689566 1 cephcsi.go:217] failed to write ceph configuration file (open /etc/ceph/ceph.conf: read-only file system)
goroutine 1 [running]:
```

this was caused since,  creation of ceph-config is not present as part deployment steps here https://github.com/ceph/ceph-csi/tree/devel/examples#deploying-ceph-csi-services 
#2919 adds this info to the doc.

**Comment by Madhu-1** [comment]
> ```
> F0304 12:23:20.689566 1 cephcsi.go:217] failed to write ceph configuration file (open /etc/ceph/ceph.conf: read-only file system)
> goroutine 1 [running]:
> ```
> 
> this was caused since, creation of ceph-config is not present as part deployment steps here https://github.com/ceph/ceph-csi/tree/devel/examples#deploying-ceph-csi-services #2919 adds this info to the doc.

@Rakshith-R if the conf is not present how the deployment pass? i expect deployment to fail without starting csi pods saying `configmap not present to mount` something like that.

**Comment by Rakshith-R** [comment]
> > ```
> > F0304 12:23:20.689566 1 cephcsi.go:217] failed to write ceph configuration file (open /etc/ceph/ceph.conf: read-only file system)
> > goroutine 1 [running]:
> > ```
> > 
> > this was caused since, creation of ceph-config is not present as part deployment steps here https://github.com/ceph/ceph-csi/tree/devel/examples#deploying-ceph-csi-services #2919 adds this info to the doc.
> 
> @Rakshith-R if the conf is not present how the deployment pass? i expect deployment to fail without starting csi pods saying `configmap not present to mount` something like that.

I think @slehlib  created an empty configmap, writing into a configmap is not allowed, hence the error. I'll let him confirm. 

Our conversation on slack is [here](https://rook-io.slack.com/archives/CG3HUV94J/p1646392792642219?thread_ts=1646392792.642219&cid=CG3HUV94J)
