### ISSUE TITLE
Storing cephx keyring on node?

### ISSUE THREAD

**Issue by gman0** [ceph/ceph-csi#2924]
I'd like to discuss if it would be ok to store cephx keyrings on nodeplugin nodes -- the trigger for this is (at least) the discussion here: https://github.com/ceph/ceph-csi/pull/2634#pullrequestreview-894655827.

The argument in favor of storing these on the node is that once a user gets root access, it's trivial to retrieve the cephx key in at least three ways (demo below), so being prudent about not having such files present on the node doesn't protect the key effectively at all. It however makes certain things awkward to implement (see the PR linked above).

### Admin secret

This is the key I tried to to retrieve:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-microosd
  namespace: default
stringData:
  # Required for dynamically provisioned volumes
  adminID: admin
  adminKey: AQCAVwpi/9BDMxAAnXEqoz46veFB2AFW45sEGQ==
```

All examples listed below assume the user has access to the root account.

```
# docker ps | grep csi-cephfsplugin | grep nodeplugin
4a2a52d2730b   quay.io/cephcsi/cephcsi                            "/usr/local/bin/ceph…"   3 hours ago   Up 3 hours             k8s_csi-cephfsplugin_c-ceph-csi-cephfs-nodeplugin-lqt4c_default_77d57a02-5a31-420c-bab1-72bacbaf9cec_0
# docker exec -it 4a2a52d2730b /bin/bash
```

## (a) Intercepting NodeStageVolume calls on csi.sock

```
# dnf install socat
# cd /var/lib/kubelet/plugins/cephfs.csi.ceph.com/
# mv csi.sock csi.sock.original
# socat -t100 -x -v UNIX-LISTEN:./csi.sock,mode=777,reuseaddr,fork UNIX-CONNECT:./csi.sock.original
```

socat output:
```
> 2022/03/08 10:50:11.412640  length=1032 from=33 to=1064
 00 00 00 04 01 00 00 00 00 00 00 77 01 04 00 00  ...........w....
 00 01 83 86 45 96 60 88 32 fd c2 be 93 c8 56 34  ....E.`.2.....V4
 9e 42 eb b6 3a 0c 89 f8 9e 8b 69 2f 41 a6 63 b8  .B..:.....i/A.c.
 ec 62 83 46 c7 5b 63 2d 05 4b 15 d1 6c c6 a9 0c  .b.F.[c-.K..l...
 10 b5 cf 2a 17 22 0c b9 0b 5c eb 90 f4 b0 44 19  ...*."...\....D.
...
 75 67 3a 10 0a                                   ug:..
 07 61 64 6d 69 6e 49 44 12 05 61 64 6d 69 6e 3a  .adminID..admin:
 34 0a                                            4.
 08 61 64 6d 69 6e 4b 65 79 12 28 41 51 43 41 56  .adminKey.(AQCAV
 77 70 69 2f 39 42 44 4d 78 41 41 6e 58 45 71 6f  wpi/9BDMxAAnXEqo
 7a 34 36 76 65 46 42 32 41 46 57 34 35 73 45 47  z46veFB2AFW45sEG
 51 3d 3d 42 15 0a                                Q==B..
```

## (b) Reading ceph-fuse memory

```
# dnf install yum-utils gdb
# debuginfo-install ceph-fuse
# ps auxfww
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         163  0.0  0.0  12156  3424 pts/1    Ss   10:35   0:00 bash
root        1400  0.0  0.0  44692  3508 pts/1    R+   11:03   0:00  \_ ps auxfww
root           1  0.0  1.1 2010744 81392 ?       Ssl  10:25   0:00 /usr/local/bin/cephcsi --nodeid=127.0.0.1 --type=cephfs --nodeserver=true --pidlimit=-1 --endpoint=unix:///csi/csi.sock --v=5 --drivername=cephfs.csi.ceph.com
root        1342  0.0  0.1 1156564 12928 ?       Sl   10:50   0:00 ceph-fuse /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-7f5b6203-2a06-4372-8d5e-85b0fe1dfce5/globalmount -m rvasek-k8s-dev.cern.ch -c /etc/ceph/ceph.conf -n client.admin --keyfile=/tmp/csi/keys/keyfile-971064047 -r /volumes/csi/csi-vol-7d2c4c88-9ecd-11ec-b988-0242ac110003/8dd1f7d7-d523-46f7-aa64-2f64f2fe8912 -o nonempty --client_mds_namespace=cephfs
# gcore 1342
...
Saved corefile core.1342
[Inferior 1 (process 1342) detached]
```

```
# strings core.1342 | grep ==
A CephX authentication key, base64 encoded.  It normally looks something like 'AQAtut9ZdMbNJBAAHz6yBAWyJyz2yYRyeMWDag=='.
AQCAVwpi/9BDMxAAnXEqoz46veFB2AFW45sEGQ==
AQCAVwpi/9BDMxAAnXEqoz46veFB2AFW45sEGQ==
...
```

## (c) Intercepting the keyfile created by `util.NewAdminCredentials()` or `util.NewUserCredentials()`

`util.NewAdminCredentials()` and `util.NewUserCredentials()` store cephx keys in temporary files:

https://github.com/ceph/ceph-csi/blob/3a64ee48c3eed8131ad8eef0a889a89d56ffab17/internal/util/credentials.go#L45-L59

This file is then unlinked once `mount` finishes with [`Credentials.DeleteCredentials()`](https://github.com/ceph/ceph-csi/blob/3a64ee48c3eed8131ad8eef0a889a89d56ffab17/internal/util/credentials.go#L101-L105). If a user were to intercept this file, they would be able to retrieve the key.

## Conclusion

Having root access to the node basically means the user is able to read the cephx key.

**Comment by gman0** [comment]
cc @ceph/ceph-csi-maintainers

**Comment by humblec** [comment]
Thanks for listing these options @gman0 ! Indeed , if there is root access to the node atleast all of the above helps to retrieve the cephx keys ( may be there are more). In a broader view,  the security aspect also  has to be considered with different admin roles in place like kube cluster admin, storage admin, may be a different admin for ceph cluster management..etc. At current model/scenario, if there is a kube node access, ceph cluster access has been granted (via cephx keys) which is not optimal, so there is a security risk even with today's model.

**Comment by gman0** [comment]
Yes there's definitely more ways to get the keys. Here I just mentioned those that are trivial and took 1-2min to set up.

> the security aspect also has to be considered with different admin roles in place like kube cluster admin

That's true, there is some overlap, but unless we use different cephx users for the provisioned volumes, I don't see an immediate way to separate these two roles. Whoever gets hold of the node and has root access, I think we must assume they have access to the keys. Dan has also confirmed this in the mailing list.
