### ISSUE TITLE
Volume mounts for Pods failing with RBD mirroring enabled

### ISSUE THREAD

**Issue by log1cb0mb** [ceph/ceph-csi#2929]
# Describe the bug #

Two ceph cluster deployed under same stretched kubernetes cluster managed through single rook-ceph operator.  Each ceph cluster is created and confined under respective namespaces.
After RBD mirroring is enabled between ceph clusters,  I am able to create PVCs/PV and even volumeattachments is there but when I spin up a pod trying to use that PVC, scheduling fails with following error:
`MountVolume.MountDevice failed for volume "pvc-3b696002-f3c2-49d6-a9fb-5bcbcc82b921" : rpc error: code = Internal desc = failed to establish the connection: failed to get connection: connecting failed: rados: ret=-13, Permission denied`

Based on investigation, it was determined that since same rook operator is used to create both clusters, ceph-csi config generated by operator and fed to `csi-rbdplugin` containing information for both clusters:
```
csi-cluster-config-json: '[{"clusterID":"rook-ceph-dc1","monitors":["10.3.5.151:6789","10.3.130.59:6789","10.3.53.161:6789"]},{"clusterID":"rook-ceph-dc2","monitors":["10.3.44.248:6789","10.3.168.71:6789","10.3.224.29:6789"]}]'
```
this most likely leads to rbdplugin trying to mount image through second ceph cluster instead of local cluster (the one targeted under storage class and for respective PVC).

relevant debug:
`cluster_mapping.go:157] ID: 84 Req-ID: 0001-000d-rook-ceph-dc1-0000000000000002-a0e006b5-9fa0-11ec-a0e8-9e12c024f7a4 found new clusterID mapping "rook-ceph-dc2" for existing clusterID "rook-ceph-dc1"`

As credentials set under storage class point to local ceph cluster and within the namespace, permission denied occurs as second ceph cluster does not accept set credentials. This was verified with the scenario of creating same credentials on both clusters and used that under block pool storage class. Permission denied error does not occur anymore however volume mount still fails as it tries to mount the image which is set to non-primary state in second cluster:

`Warning  FailedMount             6s    kubelet                  MountVolume.MountDevice failed for volume "pvc-7442f51a-481a-4788-a390-f6740df59fb5" : rpc error: code = Internal desc = rbd image ceph-blockpool/csi-vol-1911755f-9fae-11ec-ba09-4641bc4d3bf8 is still being used`

This issue does not occur before the mirroring is enabled between ceph clusters. Without mirroring, Volume mounting against PVCs  created under each ceph clusters works.

# Environment details #

- Image/version of Ceph CSI driver : 3.5.1
- Helm chart version : rook/ceph:v1.8.6
- Kernel version :  5.15.17-200.fc35.x86_64
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : krbd
- Kubernetes cluster version : 1.22.7
- Ceph cluster version : 16.2.7

# Steps to reproduce #

1. Setup details: Enable RBD mirroring. [Example setup](https://www.rook.io/docs/rook/v1.8/rbd-mirroring.html)
2. Deployment to trigger the issue: create PVC with using storage class configured for one of the ceph clusters
 ```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block-dc1
EOF
```
Spin up a sample pod using defined PVC

# Actual results #

Volume mount for pod fails with:
`MountVolume.MountDevice failed for volume "pvc-3b696002-f3c2-49d6-a9fb-5bcbcc82b921" : rpc error: code = Internal desc = failed to establish the connection: failed to get connection: connecting failed: rados: ret=-13, Permission denied`

# Expected behavior #

Volume mount for pod is done on target node and pod scheduling process is completed i.e container started and pod going into ready state.

# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.
```
I0309 12:29:00.976190   60487 utils.go:191] ID: 82 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0309 12:29:00.976310   60487 utils.go:195] ID: 82 GRPC request: {}
I0309 12:29:00.976577   60487 utils.go:202] ID: 82 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}},{"Type":{"Rpc":{"type":5}}}]}
I0309 12:29:00.996152   60487 utils.go:191] ID: 83 GRPC call: /csi.v1.Node/NodeGetCapabilities
I0309 12:29:00.996293   60487 utils.go:195] ID: 83 GRPC request: {}
I0309 12:29:00.996485   60487 utils.go:202] ID: 83 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}},{"Type":{"Rpc":{"type":5}}}]}
I0309 12:29:00.998092   60487 utils.go:191] ID: 84 Req-ID: 0001-000d-rook-ceph-dc1-0000000000000002-a0e006b5-9fa0-11ec-a0e8-9e12c024f7a4 GRPC call: /csi.v1.Node/NodeStageVolume
I0309 12:29:00.998401   60487 utils.go:195] ID: 84 Req-ID: 0001-000d-rook-ceph-dc1-0000000000000002-a0e006b5-9fa0-11ec-a0e8-9e12c024f7a4 GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-2f6447ee-7355-42ca-9f74-d321adad56c2/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":7}},"volume_context":{"clusterID":"rook-ceph-dc1","csi.storage.k8s.io/pv/name":"pvc-2f6447ee-7355-42ca-9f74-d321adad56c2","csi.storage.k8s.io/pvc/name":"rbd-pvc-mirror","csi.storage.k8s.io/pvc/namespace":"default","imageFeatures":"layering","imageFormat":"2","imageName":"csi-vol-a0e006b5-9fa0-11ec-a0e8-9e12c024f7a4","journalPool":"ceph-blockpool","pool":"ceph-blockpool","storage.kubernetes.io/csiProvisionerIdentity":"1646825016236-8081-rook-ceph.rbd.csi.ceph.com"},"volume_id":"0001-000d-rook-ceph-dc1-0000000000000002-a0e006b5-9fa0-11ec-a0e8-9e12c024f7a4"}
I0309 12:29:00.998959   60487 cluster_mapping.go:157] ID: 84 Req-ID: 0001-000d-rook-ceph-dc1-0000000000000002-a0e006b5-9fa0-11ec-a0e8-9e12c024f7a4 found new clusterID mapping "rook-ceph-dc2" for existing clusterID "rook-ceph-dc1"
I0309 12:29:00.999150   60487 rbd_util.go:1296] ID: 84 Req-ID: 0001-000d-rook-ceph-dc1-0000000000000002-a0e006b5-9fa0-11ec-a0e8-9e12c024f7a4 setting disableInUseChecks: false image features: [layering] mounter: rbd
E0309 12:29:01.029990   60487 nodeserver.go:203] ID: 84 Req-ID: 0001-000d-rook-ceph-dc1-0000000000000002-a0e006b5-9fa0-11ec-a0e8-9e12c024f7a4 failed to establish cluster connection: failed to establish the connection: failed to get connection: connecting failed: rados: ret=-13, Permission denied
E0309 12:29:01.030164   60487 utils.go:200] ID: 84 Req-ID: 0001-000d-rook-ceph-dc1-0000000000000002-a0e006b5-9fa0-11ec-a0e8-9e12c024f7a4 GRPC error: rpc error: code = Internal desc = failed to establish the connection: failed to get connection: connecting failed: rados: ret=-13, Permission denied
```

# Additional context #

@Madhu-1 Already has a fix for this issue where cluster ID mapping is corrected. Tested csphcsi image with fix include and expected result was achieved.

**Comment by Madhu-1** [comment]
Keeping it open as PR is not merged yet.
