### ISSUE TITLE
Add VolumeSnapshotClass fields to the helm chart for RBD and CephFS

### ISSUE THREAD

**Issue by msfrucht** [ceph/ceph-csi#2935]
# Describe the feature you'd like to have #

The helm chart allows setup of the pods and optionally the storageclass and necessary secrets. Adding the volumesnapshotclass would complete the available installation objects for install. 

This would help with automated installs by reducing the complexity of adding volumesnapshotclasses via additional scripting on top of the YAML values file for the helm chart.

# What is the value to the end user? (why is it a priority?) #

The only thing missing from a one bash line complete install process is the creation of the volume snapshot class. Would help tremendously with automated installation.

# How will we know we have a good solution? (acceptance criteria) #

You can create a PVC and take a snapshot after installing the helm chart with no additional work.

Add a list of criteria that should be met for this feature to be useful

[ ] Allow specification of volumesnapshotclass options from the helm chart values option.
[ ] Create a volumesnapshotclass upon installation from the helm chart.

# Additional context #

Request primarily for automation purposes.

**Comment by Madhu-1** [comment]
volumesnapshotsclass is having the CRD dependency. the installation or upgrade might fail if the CRD is not installed in the first place. we might want to remove the storageclass from the helm itself as an update to the storageclass is not supported (we cannot update/delete/add new parameters to the existing storageclass) its another discussion.

**Comment by Madhu-1** [comment]
cc @ceph/ceph-csi-maintainers
