### ISSUE TITLE
csi-provisioner will be blocked when exist an error previous operation.

### ISSUE THREAD

**Issue by jpsn123** [ceph/ceph-csi#2938]
# Describe the bug #

i intentionally created an RWX RBD PVC without block mode, which obviously failed, so deleted the PVC that was still pending, and then create a normal pvc, you will see provisioner can't working with error "an operation with the given Volume ID pvc-XXXXXXXXXXX already exists", however, if delete provisioner pod, waiting it to restart, the normal pvc will be bound successfully.

i think, provisioner still focus on providing an error volume for a delete PVC. maybe provisioner should stop faild task or remove unowned task, switch to next queued task.

**Comment by humblec** [comment]
@jpsn123 can you please share which version of ceph csi is in play here? did you recreate the PVC with same name ? also any difference if you have a delay ( say for few minutes)  between delete the PVC and recreation of the PVC? was it a quick recreation as soon delete was issued?

**Comment by jpsn123** [comment]
@humblec  version:3.5.0,  different name, longest is serval days after deletion.
