### ISSUE TITLE
There are a few questions to ask about ceph and ceph-csi

### ISSUE THREAD

**Issue by fengruichao** [ceph/ceph-csi#2961]
Dear ceph, ceph-csi developers Hello:
We had a few issues with the ceph and ceph-csi plugins that we haven't figured out for this design.
Question one:
ceph-csi and why create a snapshot, then make a snapshot of the same snapshot, in ceph-csi and copy the design of the snapshot, delete the design of the snapshot, make a snapshot in the last long volume? Rejected cpeh's definition of my first edition. What does it feel like this way?
Question two:
cephcsi has several limits, the first one is limited to 500, think that finding maxs napshot image-diagnosing a plugin will affect its performance, because they are all siblings, so I would like to ask what is the purpose of limiting to 500. The second is rbdhardmaxclonedepth, the number limit of rbdhardmaxclonedepth. By querying the source, it is found that rbdhardmaxclonedepth and rbdhardmaxclonedepth are both used to judge the level depth of a large volume. Why is it hard and soft?

The versions we are currently using are ceph-csi:3.1.0 ceph:15.2.13
Looking forward to your reply! !

**Comment by Rakshith-R** [comment]
@fengruichao 

> Question one: ceph-csi and why create a snapshot, then make a snapshot of the same snapshot, in ceph-csi and copy the design of the snapshot, delete the design of the snapshot, make a snapshot in the last long volume? Rejected cpeh's definition of my first edition. What does it feel like this way? 

This discussion contains the explanation
https://github.com/ceph/ceph-csi/discussions/2729

>Question two: cephcsi has several limits, the first one is limited to 500, think that finding maxs napshot image-diagnosing a plugin will affect its performance, because they are all siblings, so I would like to ask what is the purpose of limiting to 500. The second is rbdhardmaxclonedepth, the number limit of rbdhardmaxclonedepth. By querying the source, it is found that rbdhardmaxclonedepth and rbdhardmaxclonedepth are both used to judge the level depth of a large volume. Why is it hard and soft?

https://github.com/ceph/ceph-csi/issues/1098

These are Ceph RBD limits, more information on this issue
