### ISSUE TITLE
Question: Helm chart versioning

### ISSUE THREAD

**Issue by jlyheden** [ceph/ceph-csi#2969]
I have a question about how versioning of the ceph-csi-cephfs Helm chart is handled by the project. It appears that for example the latest ceph-csi-cephfs chart at this time (3.5.1) does not reflect the structure of the Helm chart in the ceph-csi github release (3.5.1).

How can I track the relation from code changes to what resources is being deployed from the helm chart? The inconsistency can be illustrated by that the 3.5.1 ceph-csi-cephfs helm chart contains templates which was removed in a commit done in 2020 (https://github.com/ceph/ceph-csi/commit/cc0f0b8a6a113e9f5e40c68dbe8ff53cd9029ecb). It is not obvious to me the link to the source code where the 3.5.1 helm chart was built from.

**Comment by nixpanic** [comment]
Releases are tagged, the v3.5.1 release is at https://github.com/ceph/ceph-csi/releases/tag/v3.5.1 . You should be able to download the source from that page, browse it at https://github.com/ceph/ceph-csi/tree/v3.5.1 or checkout the v3.5.1 tag with a git client.

Recently v3.6.0 was released, and that should have pushed a new Helm chart as well.
