### ISSUE TITLE
Add CO cluster name to image metadata

### ISSUE THREAD

**Issue by pkalever** [ceph/ceph-csi#2973]
# Describe the feature you'd like to have #

Context: https://github.com/ceph/ceph-csi/pull/2898

Add CO cluster name to image metadata
This will be helpful if there are two or more CO clusters, meaning that the same external Ceph cluster will be provisioning volumes for two or more different CO clusters. Therefore, in addition to the fields, we already included as metadata, we'd need to add one additional field for the CO cluster name.

Yes, it is possible, but we need users to set cluster name in the env at deployment time so that ceph-csi will know about the cluster name info.

**Comment by nixpanic** [comment]
> Yes, it is possible, but we need users to set cluster name in the env at deployment time so that ceph-csi will know about the cluster name info.

It would be simpler to set a unique `volumeNamePrefix:` for the cluster in the StorageClass.

**Comment by Madhu-1** [comment]
> > Yes, it is possible, but we need users to set cluster name in the env at deployment time so that ceph-csi will know about the cluster name info.
> 
> It would be simpler to set a unique `volumeNamePrefix:` for the cluster in the StorageClass.

Yes it works but IMO setting based on ENV/input is better for below reason

* Metadata can be updated for the existing images (which helps in upgraded clusters)
* We don't need to worry about setting volumeNamePrefix in all storageclasses
* Setting metadata helps in the case of DR also as the image will move from one OCP cluster to another OCP cluster
* Ceph will support exporting image metadata as default ceph metrics.
