### ISSUE TITLE
dynamic pv with deterministic path (based on namespace-pvc)

### ISSUE THREAD

**Issue by chhsiao1981** [ceph/ceph-csi#2982]
# Describe the feature you'd like to have #

It would be great if we can have the option to have deterministic path in dynamic pv.

# What is the value to the end user? (why is it a priority?) #

There are some scenarios (ex. sts) which may delete the corresponding pvc/pv if the pod is deleted,
but would like to have the same context (storage) if the pod is recovered.
This is especially usefully when deploying with horizontally scalable databases / kafka.

It seems like that currently we relies on volume-snapshot to achieve same feature.
However, volume-snapshot takes additional time and resources to copy between the volumes.
Having deterministic path in dynamic pv would significantly save the time and resources.

I was using cephfs-provisioner and they provided such feature based on namespace and pvc name.

Although I was using under cephfs context, it should be easy to achieve same goal in rbd.

# How will we know we have a good solution? (acceptance criteria) #

* create a sc, and then create a pvc, able to see that the corresponding ceph storage is with the path `/[prefix]/[namespace-name]/[pvc-name]`.
* after putting some files in that path, the path in the ceph storage does not get deleted when deleting pvc / pv.
* create the same pvc again, ceph-csi does not complain that the path already exists, and the corresponding path is still `/[prefix]/[namespace-name]/[pvc-name]`

# Additional context #

https://github.com/kubernetes-retired/external-storage/blob/master/ceph/cephfs/cephfs-provisioner.go#L128

**Comment by nixpanic** [comment]
Namespaces and PVCs are types that are rather Kubernetes specific. It is not something that CSI-drivers can rely on being available. With #2874 we are adding metadata to the RBD-image. Is that something that could work for you too, if CephFS supports that?

**Comment by chhsiao1981** [comment]
hi @nixpanic ～

Thank you so much for the comments～
maintaining metadata seems to be another good alternative solution～

I'll try the newly released 3.6.0 first and check out the feature first 😄
