### ISSUE TITLE
Failed to mount a PVC ROX with VolumeSnapshot as source 

### ISSUE THREAD

**Issue by phuongatemc** [ceph/ceph-csi#3000]
# Environment details #

- Image/version of Ceph CSI driver : 
    quay.io/cephcsi/cephcsi:v3.1-canary, 
- Helm chart version :
- Kernel version : Multiple version from 1.18 to 1.21
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its `krbd` or `rbd-nbd`) :
- Kubernetes cluster version : 
- Ceph cluster version : 

# Steps to reproduce #

- Create RBD FileSystem PVC1 (ReadWriteOnce access mode), mount it on a pod.  Log in to pod and create some data on the mounted directory
- Create VolumeSnapshot of the PVC.
- Create a new PVC2 with AccessMode ReadOnlyMany and and the Source is set to VolumeSnapshot
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvol0
  namespace: phtest
spec:
  storageClassName: csi-rbd-sc
  dataSource:
    name: pvol0-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi

- Mount PVC2 on another Pod.  Pod stuck at Pending and error show it failed to mount PVC as read only

  Normal   Scheduled               <unknown>        default-scheduler                    Successfully assigned phtest/restore-ph-test to irv-12-172.asl.lab.emc.com
  Normal   SuccessfulAttachVolume  11s              attachdetach-controller              AttachVolume.Attach succeeded for volume "pvc-8e1d6329-0cb7-436c-b3c4-d919aa54a6d7"
  Warning  FailedMount             3s (x4 over 7s)  kubelet, irv-12-172.asl.lab.emc.com  MountVolume.MountDevice failed for volume "pvc-8e1d6329-0cb7-436c-b3c4-d919aa54a6d7" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o _netdev,discard,ro,defaults /dev/rbd17 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8e1d6329-0cb7-436c-b3c4-d919aa54a6d7/globalmount/0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8
**Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8e1d6329-0cb7-436c-b3c4-d919aa54a6d7/globalmount/0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8: cannot mount /dev/rbd17 read-only.**

Logs of "kubectl logs pod/csi-rbdplugin-vkr75 csi-rbdplugin":

I0406 21:45:28.198835   10198 omap.go:72] ID: 6597 Req-ID: 0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8 got omap values: (pool="kube", namespace="", name="csi.volume.640fd339-b442-11ec-a092-7aaf346582a8"): map[csi.imageid:19c28f58e0df4 csi.imagename:csi-vol-640fd339-b442-11ec-a092-7aaf346582a8 csi.volname:pvc-8e1d6329-0cb7-436c-b3c4-d919aa54a6d7]
I0406 21:45:28.198946   10198 nodeserver.go:255] ID: 6597 Req-ID: 0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8 setting disableInUseChecks on rbd volume to: 0x1370730
E0406 21:45:28.198962   10198 util.go:226] kernel 4.15.0-175-generic does not support required features
I0406 21:45:28.242078   10198 cephcmds.go:59] ID: 6597 Req-ID: 0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8 command succeeded: rbd [device list --format=json --device-type krbd]
I0406 21:45:28.258854   10198 rbd_attach.go:215] ID: 6597 Req-ID: 0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8 rbd: map mon 10.235.12.165,10.235.12.166
I0406 21:45:28.361481   10198 cephcmds.go:59] ID: 6597 Req-ID: 0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8 command succeeded: rbd [--id admin -m 10.235.12.165,10.235.12.166 --keyfile=***stripped*** map kube/csi-vol-640fd339-b442-11ec-a092-7aaf346582a8 --device-type krbd --read-only]
I0406 21:45:28.361513   10198 nodeserver.go:288] ID: 6597 Req-ID: 0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8 rbd image: 0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8/kube was successfully mapped at /dev/rbd17
E0406 21:45:28.393526   10198 mount_linux.go:150] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o _netdev,discard,ro,defaults /dev/rbd17 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8e1d6329-0cb7-436c-b3c4-d919aa54a6d7/globalmount/0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8e1d6329-0cb7-436c-b3c4-d919aa54a6d7/globalmount/0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8: cannot mount /dev/rbd17 read-only.

E0406 21:45:28.393577   10198 nodeserver.go:494] ID: 6597 Req-ID: 0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8 failed to mount device path (/dev/rbd17) to staging path (/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8e1d6329-0cb7-436c-b3c4-d919aa54a6d7/globalmount/0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8) for volume (0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8) error: mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o _netdev,discard,ro,defaults /dev/rbd17 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8e1d6329-0cb7-436c-b3c4-d919aa54a6d7/globalmount/0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8e1d6329-0cb7-436c-b3c4-d919aa54a6d7/globalmount/0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8: cannot mount /dev/rbd17 read-only.
 Check dmesg logs if required.
I0406 21:45:28.512590   10198 cephcmds.go:59] ID: 6597 Req-ID: 0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8 command succeeded: rbd [unmap --device-type krbd /dev/rbd17]
E0406 21:45:28.512706   10198 utils.go:163] ID: 6597 Req-ID: 0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8 GRPC error: rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o _netdev,discard,ro,defaults /dev/rbd17 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8e1d6329-0cb7-436c-b3c4-d919aa54a6d7/globalmount/0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8e1d6329-0cb7-436c-b3c4-d919aa54a6d7/globalmount/0001-0024-be5f33e9-8892-404d-b1e0-7b5c1b9f4b5e-0000000000000005-640fd339-b442-11ec-a092-7aaf346582a8: cannot mount /dev/rbd17 read-only.

**Comment by humblec** [comment]
@phuongatemc  `quay.io/cephcsi/cephcsi:v3.1-canary` is way old and an unsupported version.. Please use latest CSI version 3.6 or 3.5 and give a try.

**Comment by phuongatemc** [comment]
We also hit the same problem on our OpenShift cluster which has the following image version.  It's sha version so I'm not sure if it mapped to which CSI version.

registry.redhat.io/ocs4/cephcsi-rhel8@sha256:08c647d11a8dbb51f920d0c16ff7d81b08f39c72cd2c01ad40077a2ebc1d1fa2

**Comment by phuongatemc** [comment]
We still hit the same issue after upgrade to CSI 3.6

Container ID: docker://766a04a02b819585b15e0e024041f1ed5d0b099b1a2ce4cc50978f3608d8e558
Image: quay.io/cephcsi/cephcsi:v3.6-canary
Image ID: docker-pullable://quay.io/cephcsi/cephcsi@sha256:f56eee41a0da87ef550b9adba4016cc4c9777e69fc2b255a6cee761192b6ac27

vmdmtest@irv-esx-85-20:~$ kubectl describe pod dk-k8s-7-2022-04-07-14-14-25-dk-k8s-7-dk-k8s-7-pvc-1-cproxy -n powerprotect
Name: dk-k8s-7-2022-04-07-14-14-25-dk-k8s-7-dk-k8s-7-pvc-1-cproxy
Namespace: powerprotect
Priority: 0
Node: irv-esx-85-22.vmw.asl.lab.emc.com/10.235.85.22
Start Time: Thu, 07 Apr 2022 21:14:54 +0000
Labels: app=cproxy
jobName=dk-k8s-7-2022-04-07-14-14-25
Annotations: <none>
Status: Pending
IP:
IPs: <none>
Containers:
cproxy:
Container ID:
Image: ap-sc.drm.ops.lab.dell.com:8446/dellemc/powerprotect-cproxy:19.11.0-1-SNAPSHOT
Image ID:
Port: <none>
Host Port: <none>
State: Waiting
Reason: ContainerCreating
Ready: False
Restart Count: 0
Environment:
USE_FSAGENT: true
Mounts:
/mnt/dk-k8s-7-pvc-1 from volume-0 (rw)
/var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-g5564 (ro)
Conditions:
Type Status
Initialized True
Ready False
ContainersReady False
PodScheduled True
Volumes:
volume-0:
Type: PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
ClaimName: pvc-static-dk-k8s-7-2022-04-07-14-14-25-dk-k8s-7-pvc-1
ReadOnly: false
kube-api-access-g5564:
Type: Projected (a volume that contains injected data from multiple sources)
TokenExpirationSeconds: 3607
ConfigMapName: kube-root-ca.crt
ConfigMapOptional: <nil>
DownwardAPI: true
QoS Class: BestEffort
Node-Selectors: <none>
Tolerations: node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
Type Reason Age From Message
---- ------ ---- ---- -------
Normal Scheduled 2m1s default-scheduler Successfully assigned powerprotect/dk-k8s-7-2022-04-07-14-14-25-dk-k8s-7-dk-k8s-7-pvc-1-cproxy to irv-esx-85-22.vmw.asl.lab.emc.com
Normal SuccessfulAttachVolume 2m attachdetach-controller AttachVolume.Attach succeeded for volume "pvc-14c0a36d-1e68-495b-b684-a048f76600eb"
**Warning FailedMount 32s (x8 over 101s) kubelet MountVolume.MountDevice failed for volume "pvc-14c0a36d-1e68-495b-b684-a048f76600eb" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o _netdev,discard,ro,defaults /dev/rbd0 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-14c0a36d-1e68-495b-b684-a048f76600eb/globalmount/0001-0024-20706ff7-6b27-4cc5-b207-e9ffc958e1da-0000000000000006-c2ea6d4e-b6b7-11ec-95a5-aa0e793d9006
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-14c0a36d-1e68-495b-b684-a048f76600eb/globalmount/0001-0024-20706ff7-6b27-4cc5-b207-e9ffc958e1da-0000000000000006-c2ea6d4e-b6b7-11ec-95a5-aa0e793d9006: cannot mount /dev/rbd0 read-only.**

**Comment by Madhu-1** [comment]
@phuongatemc you can try below steps and see if its failing again

* Create ReadWriteOnce PVC
* Create pod and write some data
* Delete the pod
* Create snapshot
* Create ReadOnlyMany PVC
* Create pod with ReadOnlyMany PVC

**Comment by phuongatemc** [comment]
@Madhu-1 
  Yes, those were the steps we used and still hit that error.

**Comment by Madhu-1** [comment]
@phuongatemc deleting pod is important before taking the snapshot. I have tested it it's working fine for me.

**Comment by phuongatemc** [comment]
Sorry, I missed that step of deleting the pod.  We cannot delete the pod because that is our policy to avoid changing anything in customer's namespace.  Is there any way to get around that?

**Comment by msfrucht** [comment]
As I recall Ceph-CSI for RBD did not support ReadWriteMany access mode. Did this change?

**Comment by Madhu-1** [comment]
> Sorry, I missed that step of deleting the pod. We cannot delete the pod because that is our policy to avoid changing anything in customer's namespace. Is there any way to get around that?

Not sure let me check is it possible or not.

**Comment by msfrucht** [comment]
Ceph-csi-rbd refuses to create volume mode Filesystem PVCs with access mode ReadWriteMany.

`  Warning  ProvisioningFailed    <invalid> (x7 over <invalid>)  rbd.csi.ceph.com_ceph-csi-rbd-provisioner-7b9c67bc46-nzvpn_bff77b5c-572c-4d49-a004-d1c9645ecd0a  failed to provision volume with StorageClass "cirrus-csi-rbd-sc": rpc error: code = InvalidArgument desc = multi node access modes are only supported on rbd `block` type volumes
`

Why would restore from snapshot be different?
