### ISSUE TITLE
Improve integration with "rbd-nbd"

### ISSUE THREAD

**Issue by dillaman** [ceph/ceph-csi#301]
The decision to use ```rbd-nbd``` should not be handled by detecting if the package exists in the node container. Instead, it should be a configuration choice to use ```rbd-nbd```. This is especially important since ```krbd``` does not support all available RBD image features. 

Additionally, ```rbd-nbd``` should never be invoked directly. Preferably it should be executed via ```rbd device map --device-type nbd``` (in fact, technically ```krbd``` should be mapped via ```rbd device map --device-type krbd```). Since that command was added in the Mimic release, if you receive an EINVAL error code, you can always fall back to ```rbd map``` and ```rbd nbd map```.

The rationale for never executing ```rbd-nbd``` directly is because we (upstream Ceph block team) are planning to support a shared daemon mode that will allow multiple devices to be handled by a single daemon.

**Comment by humblec** [comment]
@dillaman now we have the mounter configuration in SC and also have the device mapping using the device type. I am closing this issue for now. Please feel free to reopen/open an issue if some other improvements required. :+1:
