### ISSUE TITLE
Prevent unauthorised volume mode conversion for RBD PVC/snapshots

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#3032]
This is a tracker to Prevent unauthorized volume mode conversion for RBD PVC from the filesystem to block and from block to filesystem. Kubernetes [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/3141-prevent-volume-mode-conversion#changes-to-external-provisioner) for this one

**Comment by Madhu-1** [comment]
Setting https://github.com/kubernetes-csi/external-provisioner/blob/5cd575259b4ff1474ba72d8f8292aef55bbe96ec/cmd/csi-provisioner/csi-provisioner.go#L120 to true is enough for this one. we only need to do this for RBD not for cephfs.

**Comment by Rakshith-R** [comment]
hey @riya-singhal31 ,
This is part of 3.10 milestone.
Can you prioritize this issue to get it done within this week or early next week ?
Thanks,

**Comment by riya-singhal31** [comment]
> hey @riya-singhal31 , This is part of 3.10 milestone. Can you prioritize this issue to get it done within this week or early next week ? Thanks,

Hey @Rakshith-R, yes, posting a PR tomorrow.

**Comment by riya-singhal31** [comment]
> Setting https://github.com/kubernetes-csi/external-provisioner/blob/5cd575259b4ff1474ba72d8f8292aef55bbe96ec/cmd/csi-provisioner/csi-provisioner.go#L120 to true is enough for this one. we only need to do this for RBD not for cephfs.

Hi @Madhu-1 ,
It is already set as true in the current code with this commit -> https://github.com/ceph/ceph-csi/commit/776821f17fa7fe5ce5c1a9c36c9b1a2e564ca5e9#diff-340e0105f86fcb425c7668e76bfaa7b8864a6d97231ae5050e4ab69725bbefd4R60

so are we good to close this one?
