### ISSUE TITLE
Fix image vulnerabilities found in quay.io

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#305]
currently there are 2 vulnerabilities issues  found in both [rbdplugin](https://quay.io/repository/cephcsi/rbdplugin/manifest/sha256:893f9d27d3abfb3a4a263566f638af6b98c0660ad684f94ecd4e0586a90c05ec?tab=vulnerabilities&fixable=true)  and [cephfsplugin](https://quay.io/repository/cephcsi/cephfsplugin/manifest/sha256:60a139192580f4d06aabe075842cd987d8147e569b6d04e7a9b849c64d35a1d3?tab=vulnerabilities).

**Comment by Madhu-1** [comment]
CC @humblec @leseb

**Comment by leseb** [comment]
This basically means:

* build more often
* add a timestamp to each build

**Comment by Madhu-1** [comment]
@humblec looks like this is not fixed. can you take a look at it https://quay.io/repository/cephcsi/cephcsi/manifest/sha256:d34fa7a188662e385437eee2dd2ce72481e0f4b678a8c548396ad0169fdf7b9a?tab=vulnerabilities&fixable=true

**Comment by humblec** [comment]
@Madhu-1 I was looking at this today morning. There are still good number of vulnerabilities. Enabling epel repo is one of the solution mentioned and removal of iscsi repo.  Will experiment more , however this should get some or good amount of support from Base Image I believe. @leseb can you please take a look at these vulnaribilites and any thoughts on how to fix it in base image ?

**Comment by humblec** [comment]
OK.. so most of the vulnarabilities are addressed now and it an ongoing process. Atm, it report 1 vulnariability which would be addressed with the base images we use and its common for different dockerfiles in the ceph org. There is no point in keeping an issue opened here for long. Closing it for now.
