### ISSUE TITLE
Include deployment manifests as an artifact with releases

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#307]
When a Ceph-CSI release is made, it should also provide an artifact with the deployment manifests. This makes it easier for users of Ceph-CSI to deploy a certain version. Other projects (like Rook) can then remove their copies of the manifests and refer to the original ones of a release.

**Comment by nixpanic** [comment]
It will likely be needed to merge certain pieces from [the Rook Ceph CSI manifests](https://github.com/rook/rook/tree/master/cluster/examples/kubernetes/ceph/csi) so that there are no regressions when Rook consumes the manifests from Ceph-CSI.

**Comment by ShyamsundarR** [comment]
Query: Where would such an artifact be released/made available? We build images in quay, so would it be fine if these are in the github releases assets? Or, is there a more canonical location for the same?

**Comment by Madhu-1** [comment]
@nixpanic do you think it still helps for cephcsi deployment in rook?

**Comment by nixpanic** [comment]
Yes, if rook still contains its own manifests, there is a benefit. Ideally there is a single source where the manifests are maintained, and rook should consume those.

**Comment by Madhu-1** [comment]
rook maintain its own cephcsi manifests because I need to configure a few things in the templates, which is kind of difficult to do if it consumes the manifests from the ceph-csi.
