### ISSUE TITLE
Can I change the default branch on GH to master now?

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-csi#308]
Since we resynced v1.0 on master, I believe we can change the default pointing branch to master.
I can easily do that if necessary. Thanks.

**Comment by Madhu-1** [comment]
@leseb once #302 is done, planning to make `master` as  default

**Comment by ShyamsundarR** [comment]
> @leseb once #302 is done, planning to make `master` as default

@leseb The above is now done, we can move the default branch to master.

**Comment by leseb** [comment]
Done.
