### ISSUE TITLE
Switch to the 'ceph' org on quay

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-csi#309]
I can add whoever we want to the org and use that account for pushing images.

I already created: https://quay.io/repository/ceph/csi-cephfs and https://quay.io/repository/ceph/csi-rbd.

I believe it makes more sense to use the 'ceph' org.

**Comment by Madhu-1** [comment]
@leseb makes sense to have csi images under ceph org.

just to note, current images names are `rbdplugin` and `cephfsplugin`, do we need to make changes in  https://github.com/ceph/ceph-csi/blob/csi-v1.0/Makefile#L19 ?

**Comment by leseb** [comment]
I guess I removed the 'plugin' part because I thought it wasn't that necessary and that `csi-cephfs` was pretty self-explanatory? wdyt?

**Comment by leseb** [comment]
So yes, if we go that route we will have to change the Makefile accordingly and just push the image to the new quay, that's easy.

**Comment by Madhu-1** [comment]
Agreed, someone with access needs to edit Travis configuration and Makefile to push the image to quay.

**Comment by Madhu-1** [comment]
@humblec @nixpanic any comments on moving to ceph org in quay?

**Comment by nixpanic** [comment]
Yes, it would be nice to move to quay.io/ceph/ceph-csi. From release 3.0 and onwards, I guess.
