### ISSUE TITLE
Cleanup bug in createVolumeFromSnapshot() and CreateSnapshot()

### ISSUE THREAD

**Issue by pkalever** [ceph/ceph-csi#3103]
# Describe the bug #

1. In createVolumeFromSnapshot(), if the unsetAllMetadata or copyEncryptionConfig or expand fails we need to remove the clone. 
2. Same in CreateSnapshot() too 

See:
https://github.com/ceph/ceph-csi/pull/3005#discussion_r867690813
https://github.com/ceph/ceph-csi/pull/3005#discussion_r867691871

**Comment by Madhu-1** [comment]
@yati1998 PTAL

**Comment by yati1998** [comment]
Closing this issue since the [fix](https://github.com/ceph/ceph-csi/pull/3155) is merged.
