### ISSUE TITLE
Fix omap Leaks

### ISSUE THREAD

**Issue by pkalever** [ceph/ceph-csi#3111]
# Describe the bug #
We had found 2 OMAP leaks in the e2e testing, PR https://github.com/ceph/ceph-csi/pull/3041 tries to work around it for now. This request is to investigate further to root cause and fix the actual problem.

**Comment by Madhu-1** [comment]
@Yuggupta27 PTAL

**Comment by Madhu-1** [comment]
closing this one we have check in CI to check for omap leaks
