### ISSUE TITLE
Attach error 

### ISSUE THREAD

**Issue by Mutantt** [ceph/ceph-csi#3113]
Hi 
When I apply a pod with a pvc, I see  pvc is made and bound, but attacher can't attach the volume to the pod.the error is : 

MountVolume.MountDevice failed for volume "pvc-179594a4-6757-4e44-915f-0f43da75c742" : rpc error: code = Internal desc = rbd: map failed with error failed to get stat for {{ .kubeletDir }}/plugins/{{ .driverName }}/net stat {{ .kubeletDir }}/plugins/{{ .driverName }}/net: no such file or directory, rbd error output:

would you please advice ?

**Comment by Madhu-1** [comment]
@Mutantt If you are not using the multus network or some pod network please remove `netNamespaceFilePath` from your value.yaml (if you are using helm) or from `ceph-csi-config` configmap.

**Comment by Mutantt** [comment]
@Madhu-1 It's working now,thank you for your help
