### ISSUE TITLE
Revisit unwanted permissions ( RBAC) allocated for CSI driver and sidecar PODs

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#3137]
# Describe the bug #

We have been flexible and opened some extra permissions for the PODs while running in the cluster.. Its also a security issue which we have to address by restricting only required permissions for the driver PODs and sidecar PODs. 

Making it more secure has some efforts beyond RBAC like revisiting the mounts and capabiliies...etc

This track the enhancements in detail for this effort.

**RBAC** 

- [x] Issue #3018
- [x] #3044 
- [x] https://github.com/ceph/ceph-csi/pull/3068
- [x] https://github.com/ceph/ceph-csi/pull/3045
- [x] https://github.com/ceph/ceph-csi/pull/3123  

 **Capabilities/Mounts**

* Revisit the capabilities we expose in the PODs
* Recheck the mounts/bind mounts we are having

**Comment by Madhu-1** [comment]
@humblec isnt duplicate of https://github.com/ceph/ceph-csi/issues/3018?

**Comment by humblec** [comment]
> @humblec isnt duplicate of #3018?

it can be part of it, added that to the descrition ..  that said, the mounts/capabilities.. etc are also has to be revisited..
