### ISSUE TITLE
Unable to mount with kernel client

### ISSUE THREAD

**Issue by shantur** [ceph/ceph-csi#317]
Hi,

I am using Kubernetes 1.14.0 with latest ceph-csi helm chart.
I tried to use examples to create volume claims. It only works with ceph-fuse mounter, if i specify kernel mounter then it fails with error below

```failed to provision volume with StorageClass "csi-cephfs": rpc error: code = Internal desc = error mounting ceph root: an error occurred while running (45) modprobe [ceph]: exit status 1:```

I am not sure if this is configuration issue at my end or a bug. To be able to debug more, can you please let me know where to look. For starters can you please tell me which containers try do to do `modprobe ceph`. I will try to see if it fails in the container

**Comment by shantur** [comment]
I think i have found the issue.

https://github.com/ceph/ceph-csi/blob/csi-v1.0/deploy/cephfs/helm/templates/provisioner-statefulset.yaml#L72 
is missing the `/lib/modules` mounts like in
https://github.com/ceph/ceph-csi/blob/csi-v1.0/deploy/cephfs/kubernetes/csi-cephfsplugin.yaml#L84

**Comment by ShyamsundarR** [comment]
@shantur That seems right, the rbd nodeservice plugins also require `/lib/modules` access, and that seems rightly plumbed in with the Helm charts for rbd, but missed out for CephFS.

Would you be sending a PR to fix this?

**Comment by shantur** [comment]
I am not sure what all mounts would be necessary out of 

```            - name: mount-cache-dir
              mountPath: /mount-cache-dir
            - name: plugin-dir
              mountPath: /csi
            - name: csi-plugins-dir
              mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi
              mountPropagation: "Bidirectional"
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: host-sys
              mountPath: /sys
            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true
            - name: host-dev
              mountPath: /dev```

**Comment by Madhu-1** [comment]
`/lib/modules` is present in cephfs helm charts now, closing for the same reason
