### ISSUE TITLE
Storagecapacity tracking feature support for Ceph CSI driver

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#3175]
# Describe the feature you'd like to have #

In kubernetes v1.24 the CSIStoageCapacity feature has been moved to GA. This allows us to work on a stable API to support capacity tracking aware scheduling with Ceph CSI drivers. Even for NAS storage this could help ( for ex high-speed network for data transfer inside a single data center) or regulatory reasons (data must only be stored and processed in a single jurisdiction) availability may still be limited to a subset of the nodes in a cluster.

Reference# 
https://kubernetes-csi.github.io/docs/storage-capacity-tracking.html

**Comment by Madhu-1** [comment]
@humblec do you have any plan to work on it, if not feel free to unassign :)

**Comment by humblec** [comment]
Looks like I will not be able to work on this in recent future.. unassigned.

**Comment by Madhu-1** [comment]
This looks not possible, please feel free to reopen with more details.
