### ISSUE TITLE
cannot find package "github.com/gman0/ceph-csi/pkg/cephfs"

### ISSUE THREAD

**Issue by arm64b** [ceph/ceph-csi#32]
When trying to get the `ceph-csi` source code with below command:
`# go get -d github.com/ceph/ceph-csi/...`
The output is:
```
warning: ignoring symlink /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/kubernetes/cluster/gce/cos
warning: ignoring symlink /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/kubernetes/cluster/gce/custom
warning: ignoring symlink /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/kubernetes/cluster/gce/ubuntu
package github.com/gman0/ceph-csi/pkg/cephfs: cannot find package "github.com/gman0/ceph-csi/pkg/cephfs" in any of:
        /usr/local/go/src/github.com/gman0/ceph-csi/pkg/cephfs (from $GOROOT)
        /go/src/github.com/gman0/ceph-csi/pkg/cephfs (from $GOPATH)
```
Then I try to use `go get github.com/gman0/ceph-csi/pkg/cephfs` to get the `gman0 cephfs`, but the command still complains that:
```
package github.com/gman0/ceph-csi/pkg/cephfs: cannot find package "github.com/gman0/ceph-csi/pkg/cephfs" in any of:
        /usr/local/go/src/github.com/gman0/ceph-csi/pkg/cephfs (from $GOROOT)
        /go/src/github.com/gman0/ceph-csi/pkg/cephfs (from $GOPATH)
```

Any idea?

**Comment by gman0** [comment]
I've submitted a PR https://github.com/ceph/ceph-csi/pull/33 that fixes this issue. For the time being, you should now be able to do a build without waiting for the merge of that PR - I've updated the master branch on the original repo, sorry for the inconvenience!

**Comment by arm64b** [comment]
Thanks @gman0  for the quick response 😃 I will try it soon...

**Comment by arm64b** [comment]
fixed, so close it.
