### ISSUE TITLE
List supported file systems for csi.storage.k8s.io/fstype

### ISSUE THREAD

**Issue by LukeMauldin** [ceph/ceph-csi#3238]
# Describe the bug #

The documentation states that `csi.storage.k8s.io/fstype` defaults to the file system type `ext4`.  What are the other supported file system values?  Specifically, is `btrfs` a supported value?

# Environment details #

- Image/version of Ceph CSI driver : v3.6.0
- Helm chart version :
- Kernel version : 5.3.18

**Comment by Madhu-1** [comment]
for now ext4 and xfs, buts ext4 is recommended as there is an issue with xfs https://github.com/rook/rook/issues/3132#issuecomment-580508760

**Comment by LukeMauldin** [comment]
Will other file systems such as `btrfs` work or will ceph-csi fail trying to provision them?

**Comment by Madhu-1** [comment]
> Will other file systems such as `btrfs` work or will ceph-csi fail trying to provision them?

We have tested ext4 and xfs, if rbd/kubernetes supports other filesystem types it should be supported with cephcsi also. Please try it out and let us know how it works.
