### ISSUE TITLE
Need to mount existing ceph image into pod

### ISSUE THREAD

**Issue by LukeMauldin** [ceph/ceph-csi#3242]
# Describe the bug #

I have an existing Ceph cluster and an existing Ceph image that was created outside of the CSI process that I would like to mount directly into my pod as an rbd device and mount as an ext4 file system.  How can I achieve that?
What I am looking for is similar to the Cephfs Kubernetes example referenced here https://github.com/kubernetes/examples/tree/master/volumes/cephfs/ but with an rbd image.  I could use normal rbdmap commands to map the rbd image onto the Linux host and then use Kubernetes local volumes to map through the host path but I would prefer for my pod to be able to move around the cluster and the rbd device mount/unmounted as necessary - similar to how it works with a ceph csi provisioned image.

# Environment details #

- Image/version of Ceph CSI driver : v3.6.1
- Helm chart version :
- Kernel version : 5.3.X
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
- Kubernetes cluster version : 1.22.X
- Ceph cluster version : 16.X

**Comment by Madhu-1** [comment]
rbd static volume should be fine for your case, please give it a try with the steps mentioned here https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md#rbd-static-pvc
