### ISSUE TITLE
quay.io/ceph/ceph:v17.2.2 causes segfault of Ceph Mgr

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#3259]
# Describe the bug #

The `ceph/ceph:v17` container-image (v17.2.2) does not have a fully working Ceph Mgr.

See the following links for more details:

- rook/rook#10627
- https://tracker.ceph.com/issues/56700 (closed as duplicate of 55304)
- https://tracker.ceph.com/issues/55304

**Comment by humblec** [comment]
@nixpanic considering the PR is merged, shall we close this issue?

**Comment by nixpanic** [comment]
> @nixpanic considering the PR is merged, shall we close this issue?

No, we need to track the bug in Ceph(-containers) and use `:v17` once it it fixed.

**Comment by nixpanic** [comment]
this was fixed with #3275
