### ISSUE TITLE
Document the nfs upgrade scenario to delete old `csi-nfs-node` daemonset 

### ISSUE THREAD

**Issue by Rakshith-R** [ceph/ceph-csi#3271]
Document the upgrade scenario as we will have new daemonset and users can delete old daemonsets

_Originally posted by @Madhu-1 in https://github.com/ceph/ceph-csi/pull/3258#discussion_r930979445_

**Comment by Madhu-1** [comment]
@Rakshith-R, Dont we need to address this one before 3.7 release?

**Comment by Rakshith-R** [comment]
Yes,  I'll send a pr for it now that 3.7 upgrade section is in.
