### ISSUE TITLE
Move volume replication operator to kubernetes-csi-addons

### ISSUE THREAD

**Issue by Rakshith-R** [ceph/ceph-csi#3277]
This issue to track the work required to move standalone [volume replication operator](https://github.com/csi-addons/volume-replication-operator) into the kubernetes-csi-addons repo.

- [x] add volumereplication capability.
- [ ] move volumereplication server to as part of csi-addons.

Refer:

- https://github.com/csi-addons/kubernetes-csi-addons/issues/116
- https://github.com/csi-addons/kubernetes-csi-addons/pull/189

**Comment by Madhu-1** [comment]
@Rakshith-R is this completed or anything else is required but getting tracked in different issue?

**Comment by Rakshith-R** [comment]
> @Rakshith-R is this completed or anything else is required but getting tracked in different issue?

This will be followed up with https://github.com/ceph/ceph-csi/issues/3314
