### ISSUE TITLE
[csi-cephfs] use ceph mgr volumes module to provision/manage csi volumes

### ISSUE THREAD

**Issue by ajarr** [ceph/ceph-csi#328]
Currently, cephfs CSI drivers fuse/kernel mounts a ceph filesytem to create/purge csi volumes, which are cephfs subdirectories with a specific quota and layout. There are already ceph CLI commands (nautilus version of Ceph onwards) that can create/delete csi volumes. The cephfs CSI driver can issue the following commands to ceph-mgr daemon to do this,
```
$ ceph fs subvolume create <filesystem-name> <csi-vol-id>  --size <size in GB>
$ ceph fs subvolume rm <filesystem-name> <csi-vol-id>`
```

**Comment by humblec** [comment]
@ajarr as per yesterday's discussion we are tracking this for `v1.1` release. 
@Madhu-1 @ShyamsundarR any further thoughts? 

As discussed in CSI call, one outstanding item is the migration story. The implementation and code availability looks feasible by v1.1 release deadline.

**Comment by humblec** [comment]
Current plan is to get the volume provisioning and deletion based on ceph mgr in v1.1. Once that is in , we will enhance further functionalities.

**Comment by gman0** [comment]
Does this mean dropping support for pre-Nautilus clusters? That's not exactly ideal.

**Comment by humblec** [comment]
>Does this mean dropping support for pre-Nautilus clusters? That's not exactly ideal.
@gman0 not really. the `v1.0` images will stay and will be supporting previous ceph clusters. However `v1.1` will be only supported with Nautilus clusters due to this dependency.

**Comment by Madhu-1** [comment]
@ajarr anything pending on this one?

**Comment by humblec** [comment]
This has been taken care by https://github.com/ceph/ceph-csi/releases v1.1.0.  @ajarr can you confirm and close the same?

**Comment by ajarr** [comment]
Completed in V1.1.0
