### ISSUE TITLE
Deploy csi cephfs failed

### ISSUE THREAD

**Issue by zhucan** [ceph/ceph-csi#3285]
# Describe the bug #
https://github.com/ceph/ceph-csi/blob/520903d07b5467e36f2b1ef03911a58f68902829/deploy/cephfs/kubernetes/csi-cephfsplugin-provisioner.yaml#L180

"ceph-config" is not found,  csi cephfs can not be deployed.

# Environment details #

- Image/version of Ceph CSI driver : 3.5.1
- Helm chart version : no
- Kernel version : 3.10.0-1127.el7.x86_64
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :  cephfs
- Kubernetes cluster version : 1.22.7
- Ceph cluster version : 16.2.10

# Steps to reproduce #

1. prepare k8s and rook ceph cluster
2. prepare other k8s cluster
3. deploy cephfs

# Actual results #

Describe what happened
deploy cephfs successfully

# Expected behavior #

# Logs #
![image](https://user-images.githubusercontent.com/13997135/182826306-c1fbf16c-6415-42de-ba5a-3ace353027d9.png)

**Comment by Madhu-1** [comment]
You need to create https://github.com/ceph/ceph-csi/blob/devel/examples/ceph-conf.yaml

**Comment by zhucan** [comment]
@Madhu-1 Thanks
