### ISSUE TITLE
Csi-rbdplugin-controller failed to regnerate journal errors

### ISSUE THREAD

**Issue by plnordquist-pnnl** [ceph/ceph-csi#3301]
# Describe the bug #

I recently checked on the csi-rbdplugin-controller container in my deployed RBD provisioners and discovered they have been throwing errors in the logs as seen below.  These errors don't seem to cause any issues with our persistent volumes but I'm not sure if there is something I'm missing.  We've been using the ceph-csi-rbd chart since the 1.1.0 days.  I don't think we skipped any minor versions of the ceph-csi-rbd chart since that showed up in the upgrade docs.  I'm seeing this on an in-use cluster and a test cluster that I use to test new versions of kubernetes and cluster addons.  We recently upgraded both backing ceph clusters from Nautilus to Pacifica.

```
I0810 23:59:09.156309       1 omap.go:87] got omap values: (pool="tb.k8s2", namespace="", name="csi.volumes.default"): map[csi.volume.pvc-57b8c16c-5c39-4207-840a-faa18b82ff72:8fe70af8-cb92-11ea-99e4-1ea94754030e]
I0810 23:59:09.157512       1 omap.go:87] got omap values: (pool="tb.k8s2", namespace="", name="csi.volume.8fe70af8-cb92-11ea-99e4-1ea94754030e"): map[csi.imagename:csi-vol-8fe70af8-cb92-11ea-99e4-1ea94754030e csi.volname:pvc-57b8c16c-5c39-4207-840a-faa18b82ff72]
E0810 23:59:09.157550       1 rbd_journal.go:659] failed to get image id tb.k8s2/: RBD image does not have a name
E0810 23:59:09.157605       1 persistentvolume.go:182] failed to regenerate journal RBD image does not have a name
I0810 23:59:09.159103       1 omap.go:87] got omap values: (pool="tb.k8s2", namespace="", name="csi.volumes.default"): map[csi.volume.pvc-74c1ff8f-ded9-4f3b-bcb3-7ed6d8bbba67:639f952f-f2c4-11ea-9ea5-0a7c24fe2776]
I0810 23:59:09.160392       1 omap.go:87] got omap values: (pool="tb.k8s2", namespace="", name="csi.volume.639f952f-f2c4-11ea-9ea5-0a7c24fe2776"): map[csi.imagename:csi-vol-639f952f-f2c4-11ea-9ea5-0a7c24fe2776 csi.volname:pvc-74c1ff8f-ded9-4f3b-bcb3-7ed6d8bbba67]
E0810 23:59:09.160425       1 rbd_journal.go:659] failed to get image id tb.k8s2/: RBD image does not have a name
E0810 23:59:09.160437       1 persistentvolume.go:182] failed to regenerate journal RBD image does not have a name
```

# Environment details #

- Image/version of Ceph CSI driver : 3.6.2, 3.4.0
- Helm chart version : 3.6.2, 3.4.0
- Kernel version : 3.10.0-1160.71.1.el7.x86_64, 3.10.0-1160.62.1.el7.x86_64
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : krbd
- Kubernetes cluster version : 1.22.12, 1.21.11
- Ceph cluster version : Pacifica

**Comment by Madhu-1** [comment]
@plnordquist can you please paste the complete logs of the controller and also the rbd-plugin container?

**Comment by plnordquist-pnnl** [comment]
I was checking this again with the 3.7.1 version of the driver and I don't see these log messages anymore.
