### ISSUE TITLE
rbd: complete migration of volrep to csi-addons

### ISSUE THREAD

**Issue by Rakshith-R** [ceph/ceph-csi#3314]
TODO's:

- [x] move logic to `internal/csi-addons/rbd`
- [x] address [comment](https://github.com/ceph/ceph-csi/pull/3608/files#r1092953730)
- [x] remove replication service from controller server
- [x] add minimal unit tests like `internal/csi-addons/rbd/reclaimspace_test.go`
- [x] https://github.com/ceph/ceph-csi/pull/3349

_Originally posted by @nixpanic in https://github.com/ceph/ceph-csi/issues/3305#issuecomment-1216245713_

**Comment by yati1998** [comment]
@Rakshith-R I guess all the task here is done already. Can you confirm and close the issue, if done?

**Comment by Rakshith-R** [comment]
> @Rakshith-R I guess all the task here is done already. Can you confirm and close the issue, if done?

No, 3 out of 4 TODOs are still not done.

@riya-singhal31  do you wanna take up this issue ?

**Comment by yati1998** [comment]
> > @Rakshith-R I guess all the task here is done already. Can you confirm and close the issue, if done?
> 
> No, 3 out of 4 TODOs are still not done.
> cool
> @riya-singhal31 do you wanna take up this issue ?
> yeah would be a good one

**Comment by riya-singhal31** [comment]
Closes with - https://github.com/ceph/ceph-csi/pull/3608

**Comment by Rakshith-R** [comment]
> Closes with - #3608

you mean updates,

Make sure to address this [comment](https://github.com/ceph/ceph-csi/pull/3608/files#r1092953730) too.
three more tasks are remaining including the above one.

**Comment by riya-singhal31** [comment]
>>add minimal unit tests like internal/csi-addons/rbd/reclaimspace_test.go 
There is already a test file for replication.go, moved it to csi-addons. Do we need to add some more tests to it?
cc @Rakshith-R

**Comment by Rakshith-R** [comment]
> > add minimal unit tests like internal/csi-addons/rbd/reclaimspace_test.go

> There is already a test file for replication.go, moved it to csi-addons. Do we need to add some more tests to it?
> cc @Rakshith-R

They need to be added after completion of task 3 `remove replication service from controller server`
refer https://github.com/ceph/ceph-csi/blob/devel/internal/csi-addons/rbd/reclaimspace_test.go.

**Comment by Madhu-1** [comment]
@riya-singhal31 any updates here?

**Comment by riya-singhal31** [comment]
> @riya-singhal31 any updates here?

Yes, sending an updated PR.

**Comment by riya-singhal31** [comment]
https://github.com/ceph/ceph-csi/pull/3884 - addresses all the rest sub-items.

**Comment by riya-singhal31** [comment]
>>remove replication service from controller server

@Rakshith-R can you please elaborate on it. My understanding is that we want to remove the replication import from the files in internal/rbd, or something else is also needed here?

Have done this here, #3884

**Comment by Rakshith-R** [comment]
> > > remove replication service from controller server
> 
> @Rakshith-R can you please elaborate on it. My understanding is that we want to remove the replication import from the files in internal/rbd, or something else is also needed here?
> 
> Have done this here, #3884

replication server still needs to be removed from rbd driver completely.
https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/driver/driver.go#L69

**Comment by riya-singhal31** [comment]
> > > > remove replication service from controller server
> > 
> > 
> > @Rakshith-R can you please elaborate on it. My understanding is that we want to remove the replication import from the files in internal/rbd, or something else is also needed here?
> > Have done this here, #3884
> 
> replication server still needs to be removed from rbd driver completely. https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/driver/driver.go#L69

Okay, thanks Rakshith.
