### ISSUE TITLE
Encrypted RBD Volumes

### ISSUE THREAD

**Issue by briantopping** [ceph/ceph-csi#332]
http://docs.ceph.com/docs/master/ceph-volume/lvm/encryption/ documents a process by which RBD volumes can be encrypted. https://kubernetes-csi.github.io/docs/secrets-and-credentials.html#node-publish-secret documents how PVCs could contain an annotation with a secret name the can templated into the PV. 

Put together, the templated key name could be used to set up the encryption in `CreateVolume` and use it during mount in `NodePublishVolume`, without the secret being visible outside the namespace of the workload. Per the Kubernetes CSI spec, "This could be used to give the creator of the PersistentVolumeClaim the ability to specify a secret containing a decryption key they have control over".

**Comment by AkarshES** [comment]
[LVM Encryption](http://docs.ceph.com/docs/master/ceph-volume/lvm/encryption/) is referring to the OSD encryption which is not the same as RBD volumes. The underlying storage that the OSD is encrypted using a single encryption key. This is the same dmcrypt encryption support that was present in ceph-disk, prior to moving everything to ceph-volume in Ceph 14 Nautilus.

**Comment by briantopping** [comment]
Ahh, got it. So this is probably a relevant "to-do", but the wrong way to do it. I'm going to close this out in deference to someone with a better solution. Thanks @AkarshES!
