### ISSUE TITLE
ceph-csi-cephfs helm chart still contains provisioner-rules-clusterrole.yaml template

### ISSUE THREAD

**Issue by geraldwuhoo** [ceph/ceph-csi#3329]
# Describe the bug #

The latest `ceph-csi-cephfs` chart version, 3.7.0 still has the `provisioner-rules-clusterrole.yaml` template, despite 
its removal [here](https://github.com/ceph/ceph-csi/pull/3149). This is causing deployments using the default values.yaml to fail.

# Environment details #

- Image/version of Ceph CSI driver : 3.7.0
- Helm chart version : 3.7.0
- Kernel version : N/A
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : N/A
- Kubernetes cluster version : N/A
- Ceph cluster version : N/A

# Steps to reproduce #

1. Add the helm repo and update it to 3.7.0.
1. Run `helm template ceph-csi/ceph-csi-cephfs` with no other arguments.
1. See error.

# Actual results #

Error rendering the helm chart:

```
λ › helm search repo ceph-csi
NAME                    	CHART VERSION	APP VERSION	DESCRIPTION
ceph-csi/ceph-csi-cephfs	3.7.0        	3.7.0      	Container Storage Interface (CSI) driver, provi...
ceph-csi/ceph-csi-rbd   	3.7.0        	3.7.0      	Container Storage Interface (CSI) driver, provi...
λ › helm template ceph-csi/ceph-csi-cephfs
Error: template: ceph-csi-cephfs/templates/provisioner-rules-clusterrole.yaml:41:14: executing "ceph-csi-cephfs/templates/provisioner-rules-clusterrole.yaml" at <.Values.provisioner.attacher.enabled>: nil pointer evaluating interface {}.enabled
```

# Expected behavior #

The helm rendering should succeed with the default `values.yaml`

# Logs #

N/A

# Additional context #

I can confirm manually that the `provisioner-rules-clusterrole.yaml` is still in the `templates` directory:

```
λ › helm search repo ceph-csi
NAME                    	CHART VERSION	APP VERSION	DESCRIPTION
ceph-csi/ceph-csi-cephfs	3.7.0        	3.7.0      	Container Storage Interface (CSI) driver, provi...
ceph-csi/ceph-csi-rbd   	3.7.0        	3.7.0      	Container Storage Interface (CSI) driver, provi...
λ › helm pull ceph-csi/ceph-csi-cephfs --untar
λ › ls ceph-csi-cephfs/templates | grep provisioner-rules
provisioner-rules-clusterrole.yaml
```

**Comment by humblec** [comment]
The templates looks to be not in sync between this and charts repo which caused the issue. 
If you remove the attacher session https://github.com/ceph/csi-charts/blob/master/docs/cephfs/ceph-csi-cephfs/templates/provisioner-rules-clusterrole.yaml#L41 in the extracted directory and render it , is it working @geraldwuhoo ?

**Comment by humblec** [comment]
Cc @ceph/ceph-csi-contributors

**Comment by geraldwuhoo** [comment]
> The templates looks to be not in sync between this and charts repo which caused the issue. If you remove the attacher session https://github.com/ceph/csi-charts/blob/master/docs/cephfs/ceph-csi-cephfs/templates/provisioner-rules-clusterrole.yaml#L41 in the extracted directory and render it , is it working @geraldwuhoo ?

@humblec While this may work, I think there is a bigger underlying issue. It seems both the `provisioner-rules-clusterrole.yaml` and `nodeplugin-rules-clusterrole.yaml` files were removed entirely years ago: https://github.com/ceph/ceph-csi/commit/cc0f0b8a6a113e9f5e40c68dbe8ff53cd9029ecb. Yet these files remain in the charts repo: [1](https://github.com/ceph/csi-charts/blob/1d9e6ee0cfc56defcf6efcbdae74d483ce8f1dbb/docs/cephfs/ceph-csi-cephfs/templates/provisioner-rules-clusterrole.yaml), [2](https://github.com/ceph/csi-charts/blob/1d9e6ee0cfc56defcf6efcbdae74d483ce8f1dbb/docs/cephfs/ceph-csi-cephfs/templates/nodeplugin-rules-clusterrole.yaml). Seems that there is something wrong with the process used to sync between this repo and the charts repo when a file is deleted from this repo. If I had to guess, I would assume it's here: https://github.com/ceph/ceph-csi/blob/924a5ab9498e3e8a87ead0785bc9058e6af7f795/deploy.sh#L80

This line copies all the files over recursively, but does not handle deletion of files on the remote if local files were deleted. I would use something like `rsync --archive --delete` instead of `cp -R` to keep the directories in sync with deletion, but at this point you know about the codebase+process than myself, so I will defer actual implementation to the Ceph team.

Out of curiosity, why is there a separate charts repo in the first place?

**Comment by humblec** [comment]
> > The templates looks to be not in sync between this and charts repo which caused the issue. If you remove the attacher session https://github.com/ceph/csi-charts/blob/master/docs/cephfs/ceph-csi-cephfs/templates/provisioner-rules-clusterrole.yaml#L41 in the extracted directory and render it , is it working @geraldwuhoo ?
> 
> @humblec While this may work, I think there is a bigger underlying issue.

Indeed. 
> It seems both the `provisioner-rules-clusterrole.yaml` and `nodeplugin-rules-clusterrole.yaml` files were removed entirely years ago: [cc0f0b8](https://github.com/ceph/ceph-csi/commit/cc0f0b8a6a113e9f5e40c68dbe8ff53cd9029ecb). Yet these files remain in the charts repo: [1](https://github.com/ceph/csi-charts/blob/1d9e6ee0cfc56defcf6efcbdae74d483ce8f1dbb/docs/cephfs/ceph-csi-cephfs/templates/provisioner-rules-clusterrole.yaml), [2](https://github.com/ceph/csi-charts/blob/1d9e6ee0cfc56defcf6efcbdae74d483ce8f1dbb/docs/cephfs/ceph-csi-cephfs/templates/nodeplugin-rules-clusterrole.yaml). 

Yes, noticed the same while looking at this issue.

>Seems that there is something wrong with the process used to sync between this repo and the charts repo when a file is deleted from this repo. If I had to guess, I would assume it's here:
> 
> https://github.com/ceph/ceph-csi/blob/924a5ab9498e3e8a87ead0785bc9058e6af7f795/deploy.sh#L80
> 
> This line copies all the files over recursively, but does not handle deletion of files on the remote if local files were deleted. I would use something like `rsync --archive --delete` instead of `cp -R` to keep the directories in sync with deletion, but at this point you know about the codebase+process than myself, so I will defer actual implementation to the Ceph team.
> 

Above solution of "rsync" looks to be on spot to keep this repo files and chart repo files in parity. We definitely have to keep these repos in sync or single source is better. 

While we wait for team's input, I would appreciate if you can file a PR and we can discuss the approach on the same too.

**Comment by KarlHerler** [comment]
Is there a non-invasive work around for this issue?

**Comment by jaricek** [comment]
Is possible solve this problem please ?

**Comment by jcollie** [comment]
This issue does not appear to be solved yet. I cannot upgrade to 3.7.0, I am getting the same errors as everyone else. Has the job to resync the helm charts not been done yet? Is there a change that I can add to my values file to get this to work temporarily?

**Comment by nixpanic** [comment]
There is no 3.7.1 release yet. Once that is available, the removed files should be gone, finally.
