### ISSUE TITLE
release 3.7.1 tracker issue

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#3335]
# Describe the bug #

This issue tracks release 3.7.1 and the subjected milestone is available here :https://github.com/ceph/ceph-csi/milestone/16

#3340

**Comment by Rakshith-R** [comment]
https://github.com/ceph/ceph-csi/pull/3340

**Comment by humblec** [comment]
~~#3340~~

**Comment by Rakshith-R** [comment]
https://github.com/ceph/ceph-csi/pull/3350

**Comment by Rakshith-R** [comment]
https://github.com/ceph/ceph-csi/pull/3385
@humblec one more pr

**Comment by humblec** [comment]
> #3385 @humblec one more pr

Sure, its IN as well. thanks

**Comment by Madhu-1** [comment]
closing it as 3.7.1 release is out
