### ISSUE TITLE
Resizing of static volumes based on cephfs subvolumes

### ISSUE THREAD

**Issue by takyon77** [ceph/ceph-csi#3343]
# Describe the feature you'd like to have #

Make possible the resizing of static volumes when they use a cephfs subvolume.

# What is the value to the end user? (why is it a priority?) #

Static volumes can be used to recover data from dynamic volumes after an Openshift cluster reinstallation.
Being able to resize them would unify the way we manage our PVs/PVCs during their lifecycle and avoid involving the admin each time a user need more space.
 
# How will we know we have a good solution? (acceptance criteria) #

The resizing would work as it does for dynamic volumes by just editing the size of the PVC

**Comment by Madhu-1** [comment]
We dont have any plan to support resize/clone/snapshot on the static volumes. I see two options for you
* why can't you take a pvc/PV object backup and restore it after reinstallation
* OR recalculate the volumeHandle as per the requirement of cephcsi and create the PV object; cephcsi will still consider this as the dynamic PVC

cc @ceph/ceph-csi-maintainers

**Comment by Madhu-1** [comment]
Closing as not planned.
