### ISSUE TITLE
Hard to debug, with missing logs

### ISSUE THREAD

**Issue by 1337andre** [ceph/ceph-csi#337]
We had problems to debug mount problems.

Currently only StdErr will print out in logs, when mounting cephfs failed. But in our cause mount only write in stdout. This results into an empty message log with only exitCode 1.

It would be helpful if you could write stdOut in logMessage, if something went wrong.
https://github.com/ceph/ceph-csi/blob/csi-v1.0/pkg/cephfs/util.go#L57

**Comment by humblec** [comment]
@1337andre we have improved the error return to great extent with the latest releases and this is actually addressed. That said, the error returned from the core is also sent back to the user now. I am closing this issue for now and please feel free to reopn thi issue if needed.
