### ISSUE TITLE
RoleBinding in the helm chart does not work

### ISSUE THREAD

**Issue by mmack** [ceph/ceph-csi#338]
Error when using the helm chart:
```
error validating data: ValidationError(RoleBinding.roleRef): unknown field "namespace" in io.k8s.api.rbac.v1.RoleRef; if you choose to ignore these errors, turn validation off with --validate=false
```

K8S Api does not have a namespace field in the roleref:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#roleref-v1-rbac-authorization-k8s-io

One of the problematic lines:
https://github.com/ceph/ceph-csi/blob/de94cb62a99b899dc95bf9db79510a1c6ae9a867/deploy/rbd/helm/templates/provisioner-rolebinding.yaml#L20

**Comment by Madhu-1** [comment]
as we removed the support for kube1.13 closing this issue
