### ISSUE TITLE
Update images to resolve CVEs

### ISSUE THREAD

**Issue by cjohnston1158** [ceph/ceph-csi#3393]
# Describe the bug #

Is it possible to update the ceph-csi images to resolve the security vulnerabilities in the images?

Security scan can be seen at:
https://quay.io/repository/cephcsi/cephcsi?tab=tags

**Comment by Madhu-1** [comment]
@cjohnston1158 we use ceph as the base image, if the vulnerabilities are in the ceph base image, they need to be resolved there first. https://quay.io/repository/ceph/ceph?tab=tags

**Comment by Madhu-1** [comment]
Closing this one as nothing can be done at the cephcsi level. this is getting tracked at https://github.com/ceph/ceph-container/issues/2061
