### ISSUE TITLE
fsGroupPolicy field is immutable

### ISSUE THREAD

**Issue by kub3let** [ceph/ceph-csi#3397]
# Describe the bug #

I'm trying to upgrade a cluster running Ceph CSI 3.7.0 to 3.7.1

# Environment details #

- Image/version of Ceph CSI driver : 3.7.0
- Helm chart version : 3.7.0
- Kernel version : 5.10.0-17-amd64
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : n/a
- Kubernetes cluster version : k3s v1.24.4+k3s1
- Ceph cluster version : 16.2.7

# Steps to reproduce #

Setup cluster with Ceph CSI 3.7.0 use helm to upgrade to 3.7.1

# Actual results #

Helm upgrade fails with message:

UPGRADE FAILED: cannot patch \"rbd.csi.ceph.com\" with kind CSIDriver: CSIDriver.storage.k8s.io \"rbd.csi.ceph.com\" is invalid: spec.fsGroupPolicy: Invalid value: \"File\": field is immutable"

```
 FAILED! => {"changed": false, "command": "/usr/sbin/helm --version=v3.7.1 upgrade -i --reset-values --create-namespace -f=/tmp/tmp2sr2me9a.yml ceph-csi ceph-csi/ceph-csi-rbd", "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: UPGRADE FAILED: cannot patch \"rbd.csi.ceph.com\" with kind CSIDriver: CSIDriver.storage.k8s.io \"rbd.csi.ceph.com\" is invalid: spec.fsGroupPolicy: Invalid value: \"File\": field is immutable\n", "stderr": "Error: UPGRADE FAILED: cannot patch \"rbd.csi.ceph.com\" with kind CSIDriver: CSIDriver.storage.k8s.io \"rbd.csi.ceph.com\" is invalid: spec.fsGroupPolicy: Invalid value: \"File\": field is immutable\n", "stderr_lines": ["Error: UPGRADE FAILED: cannot patch \"rbd.csi.ceph.com\" with kind CSIDriver: CSIDriver.storage.k8s.io \"rbd.csi.ceph.com\" is invalid: spec.fsGroupPolicy: Invalid value: \"File\": field is immutable"], "stdout": "", "stdout_lines": []}
```

# Expected behavior #

upgrade should succeed ?

# Additional context #

Maybe I'm missing something ?

Google search does not give much results for the error message.

Also did not find a existing issue for it.

Appreciate your help.

**Comment by Madhu-1** [comment]
This is a bug we introduced in 3.7.0 release. we are not able to catch this one as we don't have e2e testing for helm upgrade. AFAIK We cannot fix this one in any release. can you follow the below workaround for now

* Delete the csidriver object

```bash
kubectl delete csidriver rbd.csi.ceph.com
```
* Do helm upgrade

**Comment by kub3let** [comment]
Thanks @Madhu-1, update worked just fine now

**Comment by Syphdias** [comment]
Hi @Madhu-1, I just ran into this issue and could solve it by using the workaround from this issue (#3397) .

I did not find official documentation though. I sounds to me like this is a know and unavoidable problem when upgrading from <3.7.0 to higher versions. ((Certain) csidriver fields cannot be updated as far as I could understand). I think this should not be burried in the bug/issue tracker as closed.

I also did not find any documentation on how to tackle helm upgrades in general from certain versions to others, if you can skip versions, and if you should watch out for certain changes in default values.

I expected it alongside [Install Chart](https://github.com/ceph/ceph-csi/blob/devel/charts/ceph-csi-cephfs/README.md#install-chart) and [Delete Chart](https://github.com/ceph/ceph-csi/blob/devel/charts/ceph-csi-cephfs/README.md#delete-chart). Did I miss this documentation somewhere?

Would it be okay to add this to the README for the ceph-csi-cephfs? (I suspect it would be the same for ceph-cci-rbd.)

**Comment by Madhu-1** [comment]
@Syphdias please feel free to add it to the ReadMe for both cephfs and rbd.

**Comment by Syphdias** [comment]
Sorry, took me a while to get to :)
