### ISSUE TITLE
Optionally return old behavior

### ISSUE THREAD

**Issue by Antiarchitect** [ceph/ceph-csi#3399]
# Describe the feature you'd like to have #

Abitlity to return old behavior before https://github.com/ceph/ceph-csi/pull/2697
Related: https://github.com/rook/rook/issues/10406

# What is the value to the end user? (why is it a priority?) #

Ability to upgrade Rook from 1.8 further without any backward incompatibility

# How will we know we have a good solution? (acceptance criteria) #

# Additional context #

**Comment by Rakshith-R** [comment]
Refer https://github.com/rook/rook/issues/10406#issuecomment-1252111200

**Comment by Madhu-1** [comment]
This should had been the first preference from cephcsi before making the major change, as we have passed a major release is it still good to have this support with some flag and remove it later once everyone corrects/fixes all the application templates. lets here from other maintainers/contributors 

cc @ceph/ceph-csi-maintainers 
cc @ceph/ceph-csi-contributors
