### ISSUE TITLE
can not create pv dynamically when using csi-v0.3 

### ISSUE THREAD

**Issue by chenqiangzhishen** [ceph/ceph-csi#340]
when using the `StorageClass.yaml` to create `rbd StroageClass`, it failed to create PV,  it shows pending, as the provisioner can't dynamically create it according to the new pvc.

**Comment by chenqiangzhishen** [comment]
find the provisioner specified not as the same as  it is declared in the csi-provisioner StatefulSet , which leads to fail to create PV dynamically.
I used the example list in the dir `ceph-csi/examples/rbd/storageclass.yaml` in git branch csi-v0.3

**Comment by chenqiangzhishen** [comment]
fix it, please review, thanks

https://github.com/ceph/ceph-csi/pull/339/commits/cd03d39f97c1af895bf69bb58f64c8fb07d8b8d7

**Comment by ShyamsundarR** [comment]
Closing the issue as the relevant PR is merged. Thanks.
