### ISSUE TITLE
One OSD has two many PGs compared to others

### ISSUE THREAD

**Issue by phucnv282** [ceph/ceph-csi#3403]
# Describe the bug #

I have 5 OSDs, they have weight 1 but I don't know why the PGs aren't balanced between them
So, that makes the most PGs OSD store so much data while the rest still have many spaces

# Environment details #

- Image/version of Ceph CSI driver : v3.4.0
- Helm chart version : rook-ceph v1.7.9
- Kubernetes cluster version : 1.20.6

# Expected behavior #

Ceph OSDs have balanced PGs distribution so that my data is stored fairly

# Logs #

![image](https://user-images.githubusercontent.com/33126800/192154963-471fb99d-528b-408f-bc8a-b23428f12df8.png)

**Comment by Madhu-1** [comment]
@phucnv282 please open the issue in [Rook](https://github.com/rook/rook) repo as this is related to the ceph cluster
