### ISSUE TITLE
rbd volume failed to mount

### ISSUE THREAD

**Issue by celiawa** [ceph/ceph-csi#3426]
# Describe the bug #
rbd volume failed to mount.

# Environment details #

- Image/version of Ceph CSI driver : v3.3.1
- Helm chart version :
- Kernel version :  4.15.0-161-generic
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :  krbd
- Kubernetes cluster version :  v1.20.11
- Ceph cluster version :  Octopus 

# Steps to reproduce #
We met several times the rbd volume failed to attach to the node.  It repeatedly report the error "an operation with the given Volume ID  already exists".  But the first time when rbdplugin does NodeStageVolume, there is no error reported. But the attachRBDImage function seems not be called in https://github.com/ceph/ceph-csi/blob/83df1eae53a0e0e2b3b8ff0972f32ca110baf862/internal/rbd/nodeserver.go#L408
 
Below is the log from the node where the kernel is 4.15.0-161-generic. The same issue also obeserved some times on the cluster where the kernel is 5.4.0-80-generic. The difference is no this log "kernel 4.15.0-161-generic does not support required features" for the higher kernel.
```
I1010 08:14:41.840459    1658 utils.go:162] ID: 556208 GRPC call: /csi.v1.Identity/Probe
I1010 08:14:41.840597    1658 utils.go:166] ID: 556208 GRPC request: {}
I1010 08:14:41.840631    1658 utils.go:173] ID: 556208 GRPC response: {}
I1010 08:14:48.574124    1658 utils.go:162] ID: 556209 GRPC call: /csi.v1.Node/NodeGetCapabilities
I1010 08:14:48.574183    1658 utils.go:166] ID: 556209 GRPC request: {}
I1010 08:14:48.574283    1658 utils.go:173] ID: 556209 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}}]}
I1010 08:14:48.585958    1658 utils.go:162] ID: 556210 Req-ID: 0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000025a-f18a2ed0-486f-11ed-a3cb-dee5209d4233 GRPC call: /csi.v1.Node/NodeStageVolume
I1010 08:14:48.586289    1658 utils.go:166] ID: 556210 Req-ID: 0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000025a-f18a2ed0-486f-11ed-a3cb-dee5209d4233 GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4387e5d6-808a-4ab4-8f36-4862963406c8/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["_netdev"]}},"access_mode":{"mode":1}},"volume_context":{"clusterID":"228f86e3-0da9-4e52-986c-45f2fd7834a7","csi.storage.k8s.io/pv/name":"pvc-4387e5d6-808a-4ab4-8f36-4862963406c8","csi.storage.k8s.io/pvc/name":"runofpipeline-teste1929lm9qc-1-3116537416-pipeline-pvc","csi.storage.k8s.io/pvc/namespace":"aiflash","imageFeatures":"layering","imageName":"csi-vol-f18a2ed0-486f-11ed-a3cb-dee5209d4233","journalPool":"turing005","pool":"turing005","storage.kubernetes.io/csiProvisionerIdentity":"1664378323785-8081-rbd.csi.ceph.com"},"volume_id":"0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000025a-f18a2ed0-486f-11ed-a3cb-dee5209d4233"}
I1010 08:14:48.587225    1658 rbd_util.go:977] ID: 556210 Req-ID: 0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000025a-f18a2ed0-486f-11ed-a3cb-dee5209d4233 setting disableInUseChecks: false image features: [layering] mounter: rbd
I1010 08:14:48.593626    1658 omap.go:84] ID: 556210 Req-ID: 0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000025a-f18a2ed0-486f-11ed-a3cb-dee5209d4233 got omap values: (pool="turing005", namespace="", name="csi.volume.f18a2ed0-486f-11ed-a3cb-dee5209d4233"): map[csi.imageid:c11489c3f0b63d csi.imagename:csi-vol-f18a2ed0-486f-11ed-a3cb-dee5209d4233 csi.volname:pvc-4387e5d6-808a-4ab4-8f36-4862963406c8 csi.volume.owner:aiflash]
E1010 08:14:48.593929    1658 util.go:233] kernel 4.15.0-161-generic does not support required features
I1010 08:15:15.528742    1658 utils.go:162] ID: 556213 GRPC call: /csi.v1.Node/NodeGetCapabilities
I1010 08:15:15.528849    1658 utils.go:166] ID: 556213 GRPC request: {}
I1010 08:15:15.528939    1658 utils.go:173] ID: 556213 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}}]}
I1010 08:15:15.529838    1658 utils.go:162] ID: 556214 GRPC call: /csi.v1.Node/NodeGetVolumeStats
I1010 08:15:15.529896    1658 utils.go:166] ID: 556214 GRPC request: {"volume_id":"0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000025a-a43376cc-d68a-11ec-a3cb-dee5209d4233","volume_path":"/var/lib/kubelet/pods/01d3bdf8-b504-4d84-95d6-82e8dfc74771/volumes/kubernetes.io~csi/pvc-ff77e6d2-5468-48a3-adc4-622b20af6c8b/mount"}
```

After the first time, the next NodeStageVolume reported with error "an operation with the given Volume ID already exists" repeatedly. We have to restart the csi-rbdplugin pod to make the volume work.
```
"type":2}}},{"Type":{"Rpc":{"type":3}}}]}
I1010 08:16:49.153389    1658 utils.go:162] ID: 556222 Req-ID: 0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000025a-f18a2ed0-486f-11ed-a3cb-dee5209d4233 GRPC call: /csi.v1.Node/NodeStageVolume
I1010 08:16:49.153524    1658 utils.go:166] ID: 556222 Req-ID: 0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000025a-f18a2ed0-486f-11ed-a3cb-dee5209d4233 GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4387e5d6-808a-4ab4-8f36-4862963406c8/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["_netdev"]}},"access_mode":{"mode":1}},"volume_context":{"clusterID":"228f86e3-0da9-4e52-986c-45f2fd7834a7","csi.storage.k8s.io/pv/name":"pvc-4387e5d6-808a-4ab4-8f36-4862963406c8","csi.storage.k8s.io/pvc/name":"runofpipeline-teste1929lm9qc-1-3116537416-pipeline-pvc","csi.storage.k8s.io/pvc/namespace":"aiflash","imageFeatures":"layering","imageName":"csi-vol-f18a2ed0-486f-11ed-a3cb-dee5209d4233","journalPool":"turing005","pool":"turing005","storage.kubernetes.io/csiProvisionerIdentity":"1664378323785-8081-rbd.csi.ceph.com"},"volume_id":"0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000025a-f18a2ed0-486f-11ed-a3cb-dee5209d4233"}
E1010 08:16:49.153644    1658 nodeserver.go:141] ID: 556222 Req-ID: 0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000025a-f18a2ed0-486f-11ed-a3cb-dee5209d4233 an operation with the given Volume ID 0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000025a-f18a2ed0-486f-11ed-a3cb-dee5209d4233 already exists
E1010 08:16:49.153679    1658 utils.go:171] ID: 556222 Req-ID: 0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000025a-f18a2ed0-486f-11ed-a3cb-dee5209d4233 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000025a-f18a2ed0-486f-11ed-a3cb-dee5209d4233 already exists
I1010 08:16:50.249749    1658 utils.go:162] ID: 556223 GRPC call: /csi.v1.Node/NodeGetCapabilities
I1010 08:16:50.249815    1658 utils.go:166] ID: 556223 GRPC request: {}

```

# Expected behavior #

The volume should be attached and mounted. Or with error for what failed.

**Comment by Madhu-1** [comment]
>an operation with the given Volume ID already exists

@celiawa above error message is showing when command are stuck/not responding the cephCSI restarting cephcsi will get new RPC call and it issues in ceph commands and everything might work, if the ceph cluster is not in a healthy state or some network issue this is expected and pretty common., cephcsi 3.3 is deprecated and not supported anymore please upgrade to latest supported release https://github.com/ceph/ceph-csi#ceph-csi-container-images-and-release-compatibility

**Comment by celiawa** [comment]
Thanks very much for your quick answer,  @Madhu-1.  Could you help a little more? I'm trying to read the code. 
I think my case in the above is when calls rbdGetDeviceList here:
https://github.com/ceph/ceph-csi/blob/83df1eae53a0e0e2b3b8ff0972f32ca110baf862/internal/rbd/rbd_attach.go#L183

But the command stuck, so the thread hung till timeout. 
https://github.com/ceph/ceph-csi/blob/83df1eae53a0e0e2b3b8ff0972f32ca110baf862/internal/util/cephcmds.go#L91

Is that correct? Thanks a lot!

**Comment by Madhu-1** [comment]
it should not hung if no problem with the node machine because we run nodeplugin with privileged access and we use hostPid and its set to max https://github.com/ceph/ceph-csi/blob/devel/cmd/cephcsi.go#L205-L221

**Comment by CindyLizi** [comment]
@Madhu-1 , i have the same issue with cephcsi:v3.5.1

and all volumes cannot be mounted to one specific node, restart the csi-rbdplugin pod could resolve issue. 
so my question is if the bad RPC call  will impact all the mount on the node? 

thank you!

**Comment by Madhu-1** [comment]
> @Madhu-1 , i have the same issue with cephcsi:v3.5.1
> 
> and all volumes cannot be mounted to one specific node, restart the csi-rbdplugin pod could resolve issue. so my question is if the bad RPC call will impact all the mount on the node?
> 
> thank you!

No one bad RPC will impact only one pvc not all pvc on that node.

**Comment by celiawa** [comment]
@Madhu-1 , but when we saw this issue, all the pvc attach or dettach were failed on this node. We had to restart the csi-rbdplugin.

**Comment by Madhu-1** [comment]
> @Madhu-1 , but when we saw this issue, all the pvc attach or dettach were failed on this node. We had to restart the csi-rbdplugin.

@celiawa it could be due to some other reasons, as per the design lock is taken on volumeID and its unique per pvc.

**Comment by celiawa** [comment]
@Madhu-1 When had the problem, we could run rbd commands manually in the rbdplugin pod. And we shared the ceph cluster among different k8s clusters. The volume attach/mount has no issues on those clusters. I think that means the ceph cluster was in good status. 

Do you have any suggestions on how we can debug it if we see it again?

**Comment by Madhu-1** [comment]
https://rook.io/docs/rook/v1.10/Troubleshooting/ceph-csi-common-issues/ should help you to debug (steps to debug will remain same). closing this one for now as we cannot do anything here. please feel free to reopen if you need any help

**Comment by celiawa** [comment]
Thanks @Madhu-1

**Comment by celiawa** [comment]
@Madhu-1 , could you please reopen this issue, my colleague had some new findings and need your help. Many thanks!

**Comment by yingxin-gh** [comment]
We meet the same issue in another cluster also. The ceph-csi version is v3.5.1.  When the ceph-csi rbd pvc be used in pod, the volume do not attach/mount into the worker node. When enter the ceph-csi plugin container and check the rbd device, it display empty. 
```
 # crictl ps | grep csi
36615e933f90a       a68e15f8572a2       3 months ago        Running             csi-rbdplugin              0                   af37f4400d8c8
# crictl exec -it 36615e933f90a sh
sh-4.4# rbd device ls
sh-4.4# exit
```
Check the plugin log as below, the GRPC call NodeUnstageVolume be called after GRPC call: /csi.v1.Node/NodeGetCapabilities. There are no other message between NodeStageVolume and NodeUnstageVolume GRPC call. From the  NodeStageVolume function, it should print some message about success or failed.  If there are some metrics can help to monitor the csi-rbdplugin status ?
```
2022-09-27T11:53:27.375657484+02:00 stderr F I0927 09:53:27.375556   30364 utils.go:191] ID: 5910745 Req-ID: 0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000015a-0ead3945-3e49-11ed-ba41-e67956818c4f GRPC call: /csi.v1.Node/NodeStageVolume
2022-09-27T11:53:27.375732251+02:00 stderr F I0927 09:53:27.375659   30364 utils.go:195] ID: 5910745 Req-ID: 0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000015a-0ead3945-3e49-11ed-ba41-e67956818c4f GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-049f51d0-1e32-46c5-8e21-4f840e0b9de0/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["_netdev"]}},"access_mode":{"mode":1}},"volume_context":{"clusterID":"228f86e3-0da9-4e52-986c-45f2fd7834a7","csi.storage.k8s.io/pv/name":"pvc-049f51d0-1e32-46c5-8e21-4f840e0b9de0","csi.storage.k8s.io/pvc/name":"m3-data-m3-0","csi.storage.k8s.io/pvc/namespace":"m3-5a5835f","imageFeatures":"layering","imageName":"csi-vol-0ead3945-3e49-11ed-ba41-e67956818c4f","journalPool":"xxxx","pool":"xxxx","storage.kubernetes.io/csiProvisionerIdentity":"1654483969571-8081-rbd.csi.ceph.com"},"volume_id":"0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000015a-0ead3945-3e49-11ed-ba41-e67956818c4f"}
2022-09-27T11:53:27.679745967+02:00 stderr F I0927 09:53:27.677242   30364 utils.go:191] ID: 5910746 GRPC call: /csi.v1.Node/NodeGetCapabilities
2022-09-27T11:53:27.679773296+02:00 stderr F I0927 09:53:27.677289   30364 utils.go:195] ID: 5910746 GRPC request: {}
2022-09-27T11:53:27.679780335+02:00 stderr F I0927 09:53:27.677359   30364 utils.go:202] ID: 5910746 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}},{"Type":{"Rpc":{"type":3}}},{"Type":{"Rpc":{"type":5}}}]}
2022-09-27T11:53:27.679801398+02:00 stderr F I0927 09:53:27.679669   30364 utils.go:191] ID: 5910747 Req-ID: 0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000015a-44e8759f-2a99-11ed-ba41-e67956818c4f GRPC call: /csi.v1.Node/NodeUnstageVolume
2022-09-27T11:53:27.679806519+02:00 stderr F I0927 09:53:27.679716   30364 utils.go:195] ID: 5910747 Req-ID: 0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000015a-44e8759f-2a99-11ed-ba41-e67956818c4f GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-d2b633ad-2bea-4732-adf3-18ec110f3981/globalmount","volume_id":"0001-0024-228f86e3-0da9-4e52-986c-45f2fd7834a7-000000000000015a-44e8759f-2a99-11ed-ba41-e67956818c4f"}
```

**Comment by Madhu-1** [comment]
@yingxin-gh kubelet is the one who sends the request to csidriver to do Stage/Unstage operation. Please check kubelet logs to identify why it sent NodeUnstage, and for NodeStage check if are there any stale operations

**Comment by yingxin-gh** [comment]
@Madhu-1 , what's means stale operations and how we can check it ?  If the grcp calls  are not working during our issue?

**Comment by Madhu-1** [comment]
Please refer https://rook.io/docs/rook/latest/Troubleshooting/ceph-csi-common-issues/#shared-filesystem-cephfs this will give you some idea about it.
