### ISSUE TITLE
[Question] How many controllers do I need to run? And what happens during a migration?

### ISSUE THREAD

**Issue by JohnKiller** [ceph/ceph-csi#3494]
Hi, I didn't find this answer on the documentation, sorry if it's already been answered somewhere.

I'm using Nomad as the orchestrator, and I would like to know how many controllers do I need to run to maintain HA.

If only 1 is needed, what happens when the orchestrator moves the controller to another host? Any downtime?

Thanks

**Comment by Madhu-1** [comment]
Am not exactly sure how Nomad works with storage, but CephCSI alone cannot be run in HA in the CO. it needs to be run with some sidecar, for example, external-provisioner, external-snapshotter/external-resizer which are the sidecars in the Kubernetes which works with the leader election, in Kubernetes, you can have active/passive leaders. if one leader pod goes down another leader will take over.
