### ISSUE TITLE
DeadlineExceeded / an operation with the given Volume ID pvc-xxx already exists (rke2 / cephfs)

### ISSUE THREAD

**Issue by Pivert** [ceph/ceph-csi#3516]
# Describe the bug #
I did try different ways to configure the cephfs csi plugin, but always get to the same errors:
DeadlineExceeded / an operation with the given Volume ID pvc-xxx already exists

Since config is more concise I'll focus on the helm chart, but using the procedure at https://github.com/ceph/ceph-csi/blob/devel/examples/README.md gives the same results.

Configuring with https://github.com/ceph/ceph-csi/blob/devel/examples/README.md
Or using the helm chart provides the same result:

# Environment details #
CephFS 3 nodes cluster (pve[1-3]) + RKE2 3 nodes cluster (rke2[1-3])

- Image/version of Ceph CSI driver : v3.7.2
- Helm chart version :
$helm show chart ceph-csi/ceph-csi-cephfs
apiVersion: v1
appVersion: 3.7.2
- Kernel version : Linux rke21 5.15.0-1020-kvm #24-Ubuntu SMP (on RKE2 servers)
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : kernel (default)
- Kubernetes cluster version : v1.24.4+rke2r1
- Ceph cluster version : ceph version 16.2.9 (a569859f5e07da0c4c39da81d5fb5675cd95da49) pacific (stable)

# Steps to reproduce #

- kubectl create namespace ceph-csi-cephfs
- helm install --namespace "ceph-csi-cephfs" "ceph-csi-cephfs" ceph-csi/ceph-csi-cephfs --values ./values.yaml
- kubectl apply -f cephfs-claim1.yml

# Actual results #
`
$kubectl describe pvc cephfs-claim1 
Name:          cephfs-claim1
Namespace:     default
StorageClass:  csi-cephfs-sc
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: cephfs.csi.ceph.com
               volume.kubernetes.io/storage-provisioner: cephfs.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age                    From                                                                                                   Message
  ----     ------                ----                   ----                                                                                                   -------
  Warning  ProvisioningFailed    33m                    cephfs.csi.ceph.com_ceph-csi-cephfs-provisioner-754777b4d5-mcnnq_d3f3f0de-2405-4e97-99ab-01daad9688d4  failed to provision volume with StorageClass "csi-cephfs-sc": rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  ProvisioningFailed    15m (x13 over 33m)     cephfs.csi.ceph.com_ceph-csi-cephfs-provisioner-754777b4d5-mcnnq_d3f3f0de-2405-4e97-99ab-01daad9688d4  failed to provision volume with StorageClass "csi-cephfs-sc": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-0efceb88-3c2f-468a-9f00-d5c6fbd80979 already exists
  Normal   ExternalProvisioning  4m52s (x122 over 34m)  persistentvolume-controller                                                                            waiting for a volume to be created, either by external provisioner "cephfs.csi.ceph.com" or manually created by system administrator
  Normal   Provisioning          24s (x18 over 34m)     cephfs.csi.ceph.com_ceph-csi-cephfs-provisioner-754777b4d5-mcnnq_d3f3f0de-2405-4e97-99ab-01daad9688d4  External provisioner is provisioning volume for claim "default/cephfs-claim1"

`
Logs and values.yaml in attachment.

# Expected behavior #

The PVC to be bound.

# Logs #
[files.tar.gz](https://github.com/ceph/ceph-csi/files/9985027/files.tar.gz)

# Additional context #
Fresh RKE2 cluster.
The cephfstst filesystem can be mounted on any of the rke2 nodes with fstab like:
`admin@e7628d51-32b5-4f5c-8eec-1cafb41ead74.cephfstst=/ /mnt/cephfstst ceph name=admin,secretfile=/etc/cephsecret 0 0`

I feel like it's even not connecting to cephfs at all. And/or error messages are misleading. Please help !

**Comment by humblec** [comment]
@Pivert `Image/version of Ceph CSI driver : v2.5.1 (from default values.yaml)` this is too OLD version and unsupported one. We are at 3.7 version.  mostly this is a network connection issue between Ceph CSI  pods to Ceph Cluster.

**Comment by Pivert** [comment]
That's the registrar that is v2.5.1 (everything is latest stable):
- quay.io/cephcsi/cephcsi:v3.7.2
- registry.k8s.io/sig-storage/csi-provisioner:v3.2.1
- registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1
That was misleading. I updated the post.

**Comment by Madhu-1** [comment]
@Pivert Is the ceph cluster healthy? And reachable from csi-cephfsplugin from csi-cephfs-provisioner pod

**Comment by Pivert** [comment]
Touché Madhu

```
$kubectl exec -it ceph-csi-cephfs-provisioner-754777b4d5-8ms9g -c csi-cephfsplugin -- bash
[root@ceph-csi-cephfs-provisioner-754777b4d5-8ms9g /]# ceph status
2022-11-11T09:45:29.029+0000 7f93f4aea700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]
[errno 13] RADOS permission denied (error connecting to the cluster)
```

**Comment by Madhu-1** [comment]
you need to pass `mon` `id` and `key ` when running the ceph status command from the above container.

**Comment by Pivert** [comment]
Thanks a lot for this help. The problem was the firewall blocking port 3300, but allowing other ceph ports.

```
$kubectl -n default get pvc
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
cephfs-claim1   Bound    pvc-0efceb88-3c2f-468a-9f00-d5c6fbd80979   1Gi        RWX            csi-cephfs-sc   12h
```
So `ceph status` was working from the hosts using protocol v1 on port 6789, but not from the containers using protocol v2 (default port 3300). Firewall change:

```
-ACCEPT         rke2            pve             tcp 6789,6800-7300                            # Ceph
+ACCEPT         rke2            pve             tcp 3300,6789,6800-7300                       # Ceph
```
I think this ceph status check from the container is key to avoid this in the future, and should be part of all the docs. To be checked before adding the StorageClass.

 ### Test from the container
1. Identify one of the provisioner and run
`kubectl exec -it ceph-csi-cephfs-provisioner-754777b4d5-8ms9g -c csi-cephfsplugin -- bash`

1. Check the ceph.conf: `cat /etc/ceph/ceph.conf`
1. Copy the keyring from a ceph server
```
[root@ceph-csi-cephfs-provisioner-754777b4d5-8ms9g /]# cat << EOF > /keyring
> [client.admin]
>         key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==
>         caps mds = "allow *"
>         caps mgr = "allow *"
>         caps mon = "allow *"
>         caps osd = "allow *"
> EOF
```

4. Check health
```
[root@ceph-csi-cephfs-provisioner-754777b4d5-8ms9g /]# ceph health -k /keyring 
HEALTH_OK
```
Thanks
