### ISSUE TITLE
cephfs: microk8s pod mount fails - globalmount missing

### ISSUE THREAD

**Issue by delorsh** [ceph/ceph-csi#3527]
# Describe the bug #

Using microk8s, pods are unable to mount PVCs.

# Environment details #

- Image/version of Ceph CSI driver : v3.7.2
- Helm chart version : n/a
- Kernel version :  5.4.0-128-generic (Ubuntu 20.04.5)
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : `fuse` or `kernel`
- Kubernetes cluster version : MicroK8s v1.25.3 revision 4128
- Ceph cluster version : ceph version 17.2.5

# Steps to reproduce #

1. Git clone ceph-csi v3.7.2
2. **replace** `/var/lib/kubelet` **with** `/var/snap/microk8s/common/var/lib/kubelet/` **in** `deploy/cephfs/kubernetes`  **yaml files** (see issue: #1475)
3. configure configmaps, secrets and deploy plugin, storageclass, pvc.yaml from example directory
4. PVC is bound properly
5. deploy pod.yaml, mount dies with `mount error 110 = Connection timed out`

# Actual results #

Example pod deployment cannot mount already bound pvc.

```
Warning  FailedMount  48s                  kubelet            MountVolume.MountDevice failed for volume "pvc-0de10040-562c-49c5-af20-e74045aa24fd" : rpc error: code = Internal desc = an error (exit status 32) occurred while running mount args: [-t ceph 192.168.1.106:3300,192.168.1.107:3300,192.168.1.108:3300:/volumes/csi/csi-vol-0561c4b7-6364-11ed-8a7a-56a09ec0d153/a44030c4-6b58-48d6-a81c-cf9d47ed32ac /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/cephfs.csi.ceph.com/813c6b6276736f1299416ee15b2682116efaf72d78d44b68307118a7b925105f/globalmount -o name=admin,secretfile=/tmp/csi/keys/keyfile-707151844,mds_namespace=mdsdata,_netdev] stderr: mount error 110 = Connection timed out
```
ceph cluster is outside of microk8s (installed on host) but it is working properly.

Host directory `/var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/` is empty. 

# Expected behavior #

Pods able to mount PVCs.

# Logs #

If the issue is in PVC mounting please attach complete logs of below containers.

- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
  plugin pod from the node where the mount is failing.

- if required attach dmesg logs.

csi-cephfsplugin logs

```
Defaulted container "driver-registrar" out of: driver-registrar, csi-cephfsplugin, liveness-prometheus
I1113 15:00:14.168775 1414553 main.go:166] Version: v2.5.1
I1113 15:00:14.168910 1414553 main.go:167] Running node-driver-registrar in mode=registration
I1113 15:00:14.171011 1414553 main.go:191] Attempting to open a gRPC connection with: "/csi/csi.sock"
I1113 15:00:16.444367 1414553 main.go:198] Calling CSI driver to discover driver name
I1113 15:00:16.517715 1414553 node_register.go:53] Starting Registration Server at: /registration/cephfs.csi.ceph.com-reg.sock
I1113 15:00:16.518091 1414553 node_register.go:62] Registration Server started at: /registration/cephfs.csi.ceph.com-reg.sock
I1113 15:00:16.518906 1414553 node_register.go:92] Skipping HTTP server because endpoint is set to: ""
I1113 15:00:17.490082 1414553 main.go:102] Received GetInfo call: &InfoRequest{}
I1113 15:00:17.492563 1414553 main.go:109] "Kubelet registration probe created" path="/var/snap/microk8s/common/var/lib/kubelet/plugins/cephfs.csi.ceph.com/registration"
I1113 15:00:20.611310 1414553 main.go:120] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
```

# Additional context #

#1067 
#2779 
#1475
[commit](https://github.com/Madhu-1/ceph-csi/commit/3894b05e4fa861fcd4ab0e271fd246a0d7da7588)

I will test solutions and provide feedback.

**Comment by nixpanic** [comment]
The error `mount error 110 = Connection timed out` while mounting suggests that the Ceph-CSI container can not reach the Ceph cluster while mounting. Can you `kubectl exec ...` into the csi-cephfsplugin container of the daemonset and verify that you can connect to the Ceph cluster manually?
