### ISSUE TITLE
Find ways to avoid ceph CLI keyring error strings in logs

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#354]
As we do not have ceph keyring files on the CSI containers, CLIs that fail and are reported in the logs have additional errors calling out the same. This is a little noisy when debugging issues and is at times misleading. Need to find ways to determine how to let Ceph CLI commands ignore the absence of a keyring.

Sample output:
```
 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin
.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
```

**Comment by leseb** [comment]
Does that mean you're executing a `ceph` command without a key? Can you describe in under which circumstances you are getting this error?

**Comment by ShyamsundarR** [comment]
For example the following command from within the rbdplugin provisioner container would throw such warnings(?) but proceed. These get captured by the plugin when executing these commands from the [code](https://github.com/ceph/ceph-csi/blob/3f35bfd4d770adbb31480bec7575787d56eaab50/pkg/rbd/rbd_util.go#L573) and pollute the logs.

```
$ kubectl exec -it csi-rbdplugin-provisioner-0 -c csi-rbdplugin bash
[root@csi-rbdplugin-provisioner-0 /]# rbd snap rm --pool replicapool --snap id1 image1 --id admin -m 10.100.117.85:6790,10.108.182.120:6790,10.111.75.172:6790 --key=AQC50NBcusHYGBAAJmSLm9Aw98mBRT5FyeS1/w==
2019-05-13 11:12:31.544093 7f4532f68d40 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
rbd: error opening image image1: (2) No such file or directory
```
We do have a minimal ceph.conf in the [code](https://github.com/ceph/ceph-csi/blob/3f35bfd4d770adbb31480bec7575787d56eaab50/pkg/cephfs/cephconf.go#L24), but providing the same does not make the logs go away, is that a way forward? Does it need any further options in it?

**Comment by dillaman** [comment]
@ShyamsundarR Until the CSI gets to the point where it no longer passes the key on the command-line, you can just create an empty "/etc/ceph/ceph.conf" to remove the log message.
