### ISSUE TITLE
Troubleshooting and problem reporting guide/text/doc

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#355]
It would be helpful to add a troubleshooting and problem reporting instructions to the repository. It can ease initial self-help and also data collection requirements when reporting issues.

For example which logs to collect and report, or what manifests to collect and report for a bug.

This can even be pointed to when opening a new issue.

**Comment by Madhu-1** [comment]
> It would be helpful to add a troubleshooting and problem reporting instructions to the repository. It can ease initial self-help and also data collection requirements when reporting issues.
> 
> For example which logs to collect and report, or what manifests to collect and report for a bug.

is this should be part of the GitHub issue template?

> This can even be pointed to when opening a new issue.

**Comment by ShyamsundarR** [comment]
> > It would be helpful to add a troubleshooting and problem reporting instructions to the repository. It can ease initial self-help and also data collection requirements when reporting issues.
> > For example which logs to collect and report, or what manifests to collect and report for a bug.
> 
> is this should be part of the GitHub issue template?
> 
> > This can even be pointed to when opening a new issue.

Yes that is what I intended with the above statement, i.e the final result is pointing to the doc/guide and listing additional details when an issue is being filed using templates.
