### ISSUE TITLE
Memory leak seems to happen to container CSI-Cephfsplugin

### ISSUE THREAD

**Issue by githubformichael** [ceph/ceph-csi#3559]
# Describe the bug #
Thanks for Ceph-CSI plugins.
There are thousands of nodes in our clusters. But on several nodes,
the container of csi-cephfsplugin in pod cephfs-csi-cephfs-nodeplugin reached memory limit and got OOM-killed.
Then the memory usage of new container of csi-cephfsplugin continues to grow and got killed again.

- memory size of csi-cephfsplugin started at 70MB(metric is the container_memory_usage_bytes), 
- about 26 hours later, the memory usage increased to 210MB(container memory limit is 200MB).
- then the memory usage kept at 210MB, but cache size(container_memory_cache) started to decrease
- when cache size reached 0MB, the container of csi-cephfsplugin got OOM-killed.
- then the loop of the above steps continues.

The process of csi-cephfsplugin was checked and RSS size continued to increase.
The process's memory dump was taken and the count of volume path(
/var/lib/kubelet/pods/2c32624e-f4b0-412f-8b92-c5b7908ca6fa/volumes/kubernetes.io~csi/[xxxxxxxx]/mount)
continues to increase in memory dump files: from 378(not at the beginning) to 486 to 1308.
see below image.

# Environment details #

- Image/version of Ceph CSI driver : 3.3.1
- Helm chart version : v3.3.1
- Kernel version :  NAME="Container Linux by CoreOS" VERSION_ID=2135.6.0
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : not specified, default value
- Kubernetes cluster version : v1.20.12
- Ceph cluster version : ceph version 16.2.9 (4c3647a322c0ff5a1dd2344e039859dcbd28c830) pacific (stable)

# Steps to reproduce #
Really, It happened to several nodes, not on all nodes, 
How to reproduce it is unknown. 
It may be related to the number of files(too many files) on PV.

1. Setup details: '...'
1. Deployment to trigger the issue '....'
1. See error

# Actual results #

Describe what happened

# Expected behavior #
The memory usage keeps the same level. 

# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC resize please attach complete logs of below containers.

- csi-resizer and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in snapshot creation and deletion please attach complete logs
of below containers.

- csi-snapshotter and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC mounting please attach complete logs of below containers.

- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
  plugin pod from the node where the mount is failing.

- if required attach dmesg logs.

**Note:-** If its a rbd issue please provide only rbd related logs, if its a
cephFS issue please provide cephFS logs.

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior
![image2022-11-29_9-52-40](https://user-images.githubusercontent.com/32404097/204432779-26fc05da-7865-491f-9533-97fee1ba7fd8.png)
![Cephfs-csi-memory-issue](https://user-images.githubusercontent.com/32404097/204432485-3ce2e99a-e7f1-4481-9aae-8245da3c7cf4.png)

**Comment by humblec** [comment]
@githubformichael thanks for the detailed report. I would like to point out a couple of things here,  that said, from the report it is "v3.3.1" of ceph csi version, which is really old and unsupported version. Could you please try with latest ceph CSI release (( may be 3.7) and check the same. There could many bug fixes and improvements fall into various components over the time , so eager to know how it behaves with latest version.  Can you also confirm you are using kernel cephfs client or mounter in your setup ?

**Comment by githubformichael** [comment]
@humblec , Thanks for your quick response!
> Can you also confirm you are using kernel cephfs client or mounter in your setup

our side should use kernel cephfs client.  The PV volume type is **ceph**,  not type **fuse.ceph-fuse**( as mentioned in  https://github.com/ceph/ceph-csi/issues/838).
And static provisioning is used in our cluster. There is no value for **forcecephkernelclient** in [csi-cephfsplugin.yaml](https://github.com/ceph/ceph-csi/blob/devel/charts/ceph-csi-cephfs/templates/nodeplugin-daemonset.yaml#L74)
If you can tell me how to confirm it, I can confirm it again.

> Could you please try with latest ceph CSI release (( may be 3.7) and check the same. 

Yes. I may need long time to release it. It may be next year.
