### ISSUE TITLE
Ceph-csi should expose a prometheus metric for CSI service status

### ISSUE THREAD

**Issue by anmolsachan** [ceph/ceph-csi#356]
Ceph-csi should expose a prometheus metric for its own service status. This metric is required for detecting if the CSI is working and PV and PVC's can be created. If possible PV and PVC creation ability metrics should also be available. Otherwise on a minimum the Ceph-csi service running status metric should be available.

These metrics are required to generate prometheus alerts, in cases where storage provisioning is not possible.

**Comment by Madhu-1** [comment]
there is no way to check PV and PVC can be created.(But I think we can check the ceph backend status, but this also required the storage class and secret to be created prior to the probing)

if we want to check the ceph-csi is running you can just run a sidecar container to send ProbeRequest and check the response.

**Comment by humblec** [comment]
>Otherwise on a minimum the Ceph-csi service running status metric should be available.
>
@anmolsachan I am not sure checking ceph-csi service status is something of interest or in plate of CSI. The reason being, as these are pods, it will be taken care by the kubelet, but definitely there is a possibility for service not available, however its possible to get it from kubelet metrics about the pod status `up` or not. isnt it ?

**Comment by anmolsachan** [comment]
@Madhu-1 The CSI service metric is reqired as a prometheus metric to create alerts. So creating a Sidecar container will a big overhead. Also, in kubernetes each service can give its own metrics, so it will be much better to have from Ceph-csi. 
Regarding PV and PVC if its not possible, its not a major requirement. Would have been a add on to create better alerts to the user.

**Comment by Daniel-Pivonka** [comment]
There are 2 different implementation ideas to add a liveness prometheus metric. 

1.sidecar implementation
2.built into the plugin


There is a similar liveness probe [1] that is part of kubernetes-csi but it just supplies an http endpoint but we want a prometheus endpoint. This implementation creates a sidecar container inside the csi-plugin pod that when an http request happens a grpc request is made to the csi-plugin containers probe function [2] and the liveness metric is returned to the sidecar and then returned to the http request. 

[1] (https://github.com/kubernetes-csi/livenessprobe)
[2] (https://github.com/ceph/ceph-csi/blob/4b33c4a9df0c234d54700ab4e87264d01dcbe547/pkg/csi-common/identityserver-default.go#L51)






1.The prometheus liveness system could operate in a very similar way. Have a sidecar in the same pod but with a prometheus endpoint. This side car will periodically ping the csi-plugin container getting the liveness metric through a grpc request to the probe function same as above. That liveness metric will be stored in a prometheus gauge (1 if alive or 0 if dead). When the prometheus server scraps this metric from the sidecar it will get this gauge value. 

This will require a place for this code to live (ceph-csi repo or another one if they dont want that?) also the container needs to be built and stored in some image repo (quay?)


2.The other approach would be to build this directly into the csi-plugin. This would work by having a go routine start the prometheus endpoint at the start of the plugins execution and having another go routine periodically get the liveness metric from the probe function. This will be enabled or disabled through an argument passed in the csi-plugin yaml when the ceph-csi is deployed.

**Comment by Madhu-1** [comment]
@humblec @ShyamsundarR @anmolsachan @shtripat please let me know your thoughts on both the approaches which one to follow


 I would go with approach 1 because of the below points

* no extra service will be running if user don't want metrics
* even if matrics container  fails we don't need to restart csi-plugin container inside stateful sets (as we can define different liveness probe rules for each container
* this sidecar container can send the creds required to connect to the backend (so we can get more information related to image, snapshot, size, etc)
* with sidecar it will help us to collect metrics from different clusters as we will be passing the creds and csi-plugin will have access to cluster info


if am missing anything or am wrong please correct me

**Comment by Madhu-1** [comment]
> @Madhu-1 The CSI service metric is reqired as a prometheus metric to create alerts. So creating a Sidecar container will a big overhead. Also, in kubernetes each service can give its own metrics, so it will be much better to have from Ceph-csi.

@anmolsachan am not sure how running sidecar will become overhead 
IMO if we put memory and CPU limit per container then I think we won't have any issue related to resources.


> Regarding PV and PVC if its not possible, its not a major requirement. Would have been a add on to create better alerts to the user.

if we run as a sidecar container we can have it matrics per PVC also (but need some code implementaion)

**Comment by shtripat** [comment]
@Madhu-1 I would agree to option-1.

**Comment by humblec** [comment]
@Daniel-Pivonka @Madhu-1  As mentioned earlier , I would like to get this resolved with option `1` ie nothing but `sidecar container`. 

>This will require a place for this code to live (ceph-csi repo or another one if they dont want that?) also the container needs to be built and stored in some image repo (quay?)
>

This sidecar container can stay in other repo and dont have to be part of `ceph-csi` repo. 
We also have to validate whether this cause any performance impact on csi plugin while serviing the requests as its connected via UDS. If there is a performance hit, it has to be accounted before we move on.

**Comment by anmolsachan** [comment]
@Madhu-1 @Daniel-Pivonka @humblec I also agree with the sidecar approach. Sounds good. Regarding which repo this should go to is the question here. @humblec  If this cannot go to the ceph-csi, then would you advice this to go with ceph-csi deployment via rook-operator ?

**Comment by humblec** [comment]
>Regarding which repo this should go to is the question here. @humblec If this cannot go to the ceph-csi, then would you advice this to go with ceph-csi deployment via rook-operator ?
>

Yeah, it can be part of deployment via Rook, however this could be altogether a different deployment so that a user/admin can deploy it any time independently and start receiving metrics. Are we seeing any glitches if we deploy at any point in time or later to CSI deployment ?

**Comment by anmolsachan** [comment]
@humblec According to my understanding, the flow is something like this: Rook Operator depolyment -> Rook-Ceph-Csi deployment -> Cluster Creation -> deployment of monitoring pieces. This all has to be in a flow and there shall not be any interaction with the admin once the Rook deployment starts. Thus we will have to integrate with either CSI deployment or monitoring deployment. I feel this can be handled as part of Csi deployment in rook. One more reason to do this is, the resources or endpoints that have to be monitored by the monitoring stack shall be deployed before monitoring pieces are deployed. Thoughts ? @Madhu-1 @humblec  @Daniel-Pivonka

**Comment by Madhu-1** [comment]
I would like to make this deployment configurable during CSI deployment in rook.
currently we are doing same for cephfs and rbd https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/operator-with-csi.yaml#L41

**Comment by Daniel-Pivonka** [comment]
This is the sidecar container #438 Where do we want this? @anmolsachan @humblec

**Comment by anmolsachan** [comment]
@Daniel-Pivonka Let's have it in the CSI deployment in rook and a configurable component as @Madhu-1 said.  Please push a PR on Rook for the same with the design spec, as its expected there.

**Comment by humblec** [comment]
> This is the sidecar container #438 Where do we want this? @anmolsachan @humblec

The sidecar container image can be hosted anywhere, the deployment piece can be clubbed in CSI. But my point/question is that, 
@anmolsachan @Daniel-Pivonka at any point in time the deployment of sidecar can be done  in a cluster and serving of the request can be performed , Isnt it ? 

If above is the case, the sidecar itself can have a seperate 'deployment artifact/manifest" which is consumable independently .

**Comment by anmolsachan** [comment]
> @anmolsachan @Daniel-Pivonka at any point in time the deployment of sidecar can be done in a cluster and serving of the request can be performed , Isnt it ?
The sidecar container has to be deployed before monitoring pieces are deployed. 
> If above is the case, the sidecar itself can have a seperate 'deployment artifact/manifest" which is consumable independently .
Yes, that sounds good but again it needs to be deployed with the storage deployment flow before monitoring pieces are deployed in rook

**Comment by humblec** [comment]
Closing this as this is taken care now!. Thanks!
