### ISSUE TITLE
CephFS plugin needs an async subvolume purge mechanisim

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#357]
Currently the CephFS plugin on a volume delete is purging the contents of the deleted volume [in-line](https://github.com/ceph/ceph-csi/blob/882bebf1d8507d6bcd4b4bfae23a861057353785/pkg/cephfs/volume.go#L116) as a part of the DeleteVolume request. This may take time and hence cause the CO system to retry deletes against the same volume.

Further, this will also lock up the VolID name based [mutex](https://github.com/ceph/ceph-csi/blob/882bebf1d8507d6bcd4b4bfae23a861057353785/pkg/cephfs/controllerserver.go#L153) for longer, possibly causing delays in other RPCs due to lock contention issues.

It would be beneficial to move the purging to an asynchronous routine or if possible delegate the task to the Ceph backend.

**Comment by ShyamsundarR** [comment]
@ajarr Are there ways to achieve this when using the ceph volume based subvolume creation and deletion? Or, other means possible with the CephFS backend?

**Comment by ajarr** [comment]
Yes, we plan to purge fs subvolumes asynchronosuly in the backend. @vshankar is working on this.

**Comment by vshankar** [comment]
> Yes, we plan to purge fs subvolumes asynchronosuly in the ceph mgr volumes module. @vshankar is working on this.

I'll push the pr soon for review.

**Comment by vshankar** [comment]
https://github.com/ceph/ceph/pull/28003

**Comment by ajarr** [comment]
The [ceph PR](ceph/ceph#28003) has been merged in master. Working on nautilus backport, http://tracker.ceph.com/issues/40796

**Comment by ajarr** [comment]
The PR has been backported to nautilus, and the fasync purge feature will be available in 14.2.3 version of Ceph

**Comment by ShyamsundarR** [comment]
@ajarr I think this issue can be closed, as all required work is done?

**Comment by ajarr** [comment]
Yes. Async deletion available in Ceph version >= 14.2.3
