### ISSUE TITLE
Check for newline characters in secrets, and log appropriate messages

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#358]
In the recent past there have been a couple of issues in the repository and in the slack channels where users have inadvertently missed out using `echo -n ...` when encoding id and key in secrets. This causes the CLI commands to fail with permission errors, but the log output looks healthy (barring a line break).

To ease self service in terms of correcting such situations, we should maybe consider checking for newline characters in the id,key secrets and print explicit error messages that reflect the same.

**Comment by Madhu-1** [comment]
This is not an issue now as we moved from data to string data in secret
