### ISSUE TITLE
Document exact capabilities a id requires against a Ceph cluster for RBD and CephFS plugins

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#360]
The [various](https://github.com/ceph/ceph-csi/blob/3a308eaeeec724ed2bf4163a9e58d5c50bbde2b2/examples/rbd/secret.yaml#L9) [secrets](https://github.com/ceph/ceph-csi/blob/3a308eaeeec724ed2bf4163a9e58d5c50bbde2b2/examples/cephfs/secret.yaml#L13) that need to be provided to the plugins for provisioning and mounting needs documentation regarding exact capabilities that these identities require.

This helps create identities that have enough access to perform the plugin actions and also ensure that the capabilities are not too lenient to cause a security concern.

**Comment by Madhu-1** [comment]
do we need to document these capabilities or we can just point to the ceph user management for information?

**Comment by ShyamsundarR** [comment]
We need to document what capabilities CSI needs. Ceph documentation links can be pointed to for how to create it etc. but exact capabilities that are needed by the ID needs documentation from the CSI end I would think.

**Comment by ajarr** [comment]
For CephFS CSI plugin, please see,
https://github.com/ceph/ceph-csi/pull/437#issuecomment-511460712

**Comment by ajarr** [comment]
@ShyamsundarR would you know the capabilities required by the RBD plugin? We can then close this issue

**Comment by ShyamsundarR** [comment]
> @ShyamsundarR would you know the capabilities required by the RBD plugin? We can then close this issue

I actually do not, the best reference I have/had is/was [here](https://github.com/rook/rook/blob/7fb43d72ebfaba5afbb8faf017962a38364b2901/Documentation/ceph-csi-drivers.md#create-rbd-secret)

The credentials needed would be (from above),

`ceph auth get-or-create-key client.kubernetes mon \"allow profile rbd\" osd \"profile rbd pool=<poolname>\""`

If someone could validate this, and add it (and the CephFS requirement) to the documentation we can close this issue.

**Comment by ajarr** [comment]
This is a critical issue. Currently, the CSI volumes are mounted with cephx admin user with full privileges. This allows Ceph CSI volume users to misuse them, e.g, RWX CephFS volume users might take lot CephFS snapshots of the CSI volume without the k8s csi interface that is currently unavailable.
We need to restrict the privileges of the cephx user used to mount the CSI volumes.

**Comment by dillaman** [comment]
> If someone could validate this, and add it (and the CephFS requirement) to the documentation we can close this issue.

Right now RBD needs the following:

`ceph auth get-or-create-key client.kubernetes mon "allow profile rbd" osd "profile rbd pool=<poolname>" mgr "allow rw"`

That 'mgr' cap is a newly discovered issue from yesterday that is preventing the background image deletion from functioning. I am fixing that mgr cap issue by adding a `profile rbd`, but it will take time for that to trickle down into the nautilus branch (hopefully 14.2.5 release).

**Comment by ajarr** [comment]
FYI, rook now creates Ceph auth IDs with exact capabilities for provisioning and mounting volumes backed by RBD and CephFS
See,
https://github.com/rook/rook/pull/4086/commits/fcc2e21fafc338b55c4b3d6056e50ef900d38fa4#diff-0ffcd00c868712a2e6b1e27f823e304aR79-R110

**Comment by yati1998** [comment]
Hi @Madhu-1 can you assign me this issue? I would like to work on this.

**Comment by Madhu-1** [comment]
@yati1998 Am not able to assign this to you.

**Comment by Madhu-1** [comment]
@humblec can you help here?

**Comment by Madhu-1** [comment]
moving this one out of  release-3.0.0 milestone.
