### ISSUE TITLE
I want to use cephfs on k8s, but deploy cephfs-csi met some problem

### ISSUE THREAD

**Issue by andyzheung** [ceph/ceph-csi#3602]
manifest like this:

[kubernetes.zip](https://github.com/ceph/ceph-csi/files/10378239/kubernetes.zip)

log:
kubectl logs -n csi-cephfs csi-cephfsplugin-provisioner-7c7d9758fc-nvhmk  csi-provisioner

W0110 01:29:47.758529       1 controller.go:934] Retrying syncing claim "8125baff-d748-4ee5-87a2-4a67d034ff45", failure 0
E0110 01:29:47.758563       1 controller.go:957] error syncing claim "8125baff-d748-4ee5-87a2-4a67d034ff45": failed to provision volume with StorageClass "dev-csi-cephfs-sc": rpc error: code = InvalidArgument desc = volume not found
I0110 01:29:47.758581       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"csi-cephfs-pvc", UID:"8125baff-d748-4ee5-87a2-4a67d034ff45", APIVersion:"v1", ResourceVersion:"189122993", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "dev-csi-cephfs-sc": rpc error: code = InvalidArgument desc = volume not found

kubectl describe pvc csi-cephfs-pvc
Normal   Provisioning          2m7s (x10 over 6m23s)  cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-7c7d9758fc-5ldt5_d3d2e8ce-4e0a-469a-9097-f2c8d4066ff5  External provisioner is provisioning volume for claim "default/csi-cephfs-pvc"
  Warning  ProvisioningFailed    2m7s (x10 over 6m23s)  cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-7c7d9758fc-5ldt5_d3d2e8ce-4e0a-469a-9097-f2c8d4066ff5  failed to provision volume with StorageClass "dev-csi-cephfs-sc": rpc error: code = InvalidArgument desc = volume not found
  Normal   ExternalProvisioning  31s (x26 over 6m23s)   persistentvolume-controller                                                                             waiting for a volume to be created, either by external provisioner "cephfs.csi.ceph.com" or manually created by system administrator

**Comment by Rakshith-R** [comment]
@andyzheung 
Please follow the template while reporting new issues and fill in the required details 
https://github.com/ceph/ceph-csi/issues/new?assignees=&labels=&template=bug_report.md

you can edit current issue description or add these details in a new comment.

**Comment by Madhu-1** [comment]
>type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "dev-csi-cephfs-sc": rpc error: code = InvalidArgument desc = volume not found

Looks like the fsName you mentioned in the storageclass doesn't exist. Can you please check by running `ceph fs ls` if not present please create the filesystem

**Comment by andyzheung** [comment]
> > type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "dev-csi-cephfs-sc": rpc error: code = InvalidArgument desc = volume not found
> 
> Looks like the fsName you mentioned in the storageclass doesn't exist. Can you please check by running `ceph fs ls` if not present please create the filesystem
yes, I have changed it and i works ok. thank you.
