### ISSUE TITLE
I use ceph-csi for k8s and use rbd, but I find a problem.

### ISSUE THREAD

**Issue by andyzheung** [ceph/ceph-csi#3606]
I use rbd  as k8s backend storage, 
I create the sc like this:
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: autelrobotics-prod-csi-rbd-sc
provisioner: rbd.csi.ceph.com
parameters:
   clusterID: 61ef19c8-4076-46c1-b669-09ae77fcf9a0
   pool: kube
   imageFeatures: layering
   csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
   csi.storage.k8s.io/provisioner-secret-namespace: csi-ceph
   csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
   csi.storage.k8s.io/controller-expand-secret-namespace: csi-ceph
   csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
   csi.storage.k8s.io/node-stage-secret-namespace: csi-ceph
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
   - discard

And I create pvc  like:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raw-block-pvc
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50000Gi
  storageClassName: prod-csi-rbd-sc

and A deployment use it:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-test-pvc
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: autonomy-gpu-volume
        persistentVolumeClaim:
          claimName: raw-block-pvc
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /data
          name: autonomy-gpu-volume

Then I delete the deployment, And try to use this pvc to another pod like:
apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
  namespace: demo
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: autonomy-gpu-volume
  volumes:
    - name: autonomy-gpu-volume
      persistentVolumeClaim:
        claimName: raw-block-pvc
I rbd pvc seem can't mount to it, describe pod error like:
AttachVolume.Attach succeeded for volume "pvc-292007aa-5e8a-4814-9e58-7df5c9802529"
  Warning  FailedMount             4m45s  kubelet                  Unable to attach or mount volumes: unmounted volumes=[raw-block-pvc], unattached volumes=[workload-certs istio-podinfo workload-socket istio-data istio-envoy istio-token kube-api-access-ghh8m dshm jinliang-stereo-lite-gpu-volume raw-block-pvc istiod-ca-cert]: timed out waiting for the condition
  Warning  FailedMount             2m29s  kubelet                  Unable to attach or mount volumes: unmounted volumes=[raw-block-pvc], unattached volumes=[workload-socket workload-certs istio-envoy jinliang-stereo-lite-gpu-volume istiod-ca-cert istio-data istio-token kube-api-access-ghh8m dshm istio-podinfo raw-block-pvc]: timed out waiting for the condition

**I just want to know If I delete a deployment that used rbd pvc, and want to use it to another pod or deployment, If any else things need to do?**

**Comment by Madhu-1** [comment]
@andyzheung please fill the template when opening a GitHub issue with the required logs.
