### ISSUE TITLE
I use ceph-csi for k8s and use rbd, but I find a problem.

### ISSUE THREAD

**Issue by andyzheung** [ceph/ceph-csi#3607]
# Describe the bug #

I just want to know If I delete a deployment that used rbd pvc, and want to use it to another pod or deployment, If any else things need to do?

# Environment details #

- Image/version of Ceph CSI driver :
-
- Helm chart version :
ceph-csi v3.7.2
https://github.com/ceph/ceph-csi/tree/v3.7.2/deploy/rbd/kubernetes
- Kernel version :
-ubuntu 18.04
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
mount rbd
- Kubernetes cluster version :
- 1.21
- Ceph cluster version :
ceph version 14.2.11-199.el8cp (f5470cbfb5a4dac5925284cef1215f3e4e191a38) nautilus (stable)

# Steps to reproduce #

I create the sc like this:
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: autelrobotics-prod-csi-rbd-sc
provisioner: rbd.csi.ceph.com
parameters:
clusterID: 61ef19c8-4076-46c1-b669-09ae77fcf9a0
pool: kube
imageFeatures: layering
csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
csi.storage.k8s.io/provisioner-secret-namespace: csi-ceph
csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
csi.storage.k8s.io/controller-expand-secret-namespace: csi-ceph
csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
csi.storage.k8s.io/node-stage-secret-namespace: csi-ceph
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:

discard
And I create pvc like:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: raw-block-pvc
namespace: demo
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 50000Gi
storageClassName: prod-csi-rbd-sc

and A deployment use it:
apiVersion: apps/v1
kind: Deployment
metadata:
name: my-nginx-test-pvc
namespace: demo
spec:
replicas: 1
selector:
matchLabels:
app: nginx
template:
metadata:
labels:
app: nginx
spec:
volumes:
- name: autonomy-gpu-volume
persistentVolumeClaim:
claimName: raw-block-pvc
containers:
- name: nginx
image: nginx:latest
ports:
- containerPort: 80
volumeMounts:
- mountPath: /data
name: autonomy-gpu-volume

Then I delete the deployment, And try to use this pvc to another pod like:
apiVersion: v1
kind: Pod
metadata:
name: nginx-demo
namespace: demo
spec:
containers:
- name: nginx
image: nginx
volumeMounts:
- mountPath: /data
name: autonomy-gpu-volume
volumes:
- name: autonomy-gpu-volume
persistentVolumeClaim:
claimName: raw-block-pvc
I rbd pvc seem can't mount to it, describe pod error like:
AttachVolume.Attach succeeded for volume "pvc-292007aa-5e8a-4814-9e58-7df5c9802529"
Warning FailedMount 4m45s kubelet Unable to attach or mount volumes: unmounted volumes=[raw-block-pvc], unattached volumes=[workload-certs istio-podinfo workload-socket istio-data istio-envoy istio-token kube-api-access-ghh8m dshm jinliang-stereo-lite-gpu-volume raw-block-pvc istiod-ca-cert]: timed out waiting for the condition
Warning FailedMount 2m29s kubelet Unable to attach or mount volumes: unmounted volumes=[raw-block-pvc], unattached volumes=[workload-socket workload-certs istio-envoy jinliang-stereo-lite-gpu-volume istiod-ca-cert istio-data istio-token kube-api-access-ghh8m dshm istio-podinfo raw-block-pvc]: timed out waiting for the condition

# Actual results #

I deploy the deployment use rbd storageclass, them delete it , and try to deploy a Pod  use this pvc, But it can mount it.

# Expected behavior #

If I need to to anythiing else  when I delete the deployment can make the pvc is umount.

# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

[csi-rbdplugin-provsioner.txt](https://github.com/ceph/ceph-csi/files/10393977/csi-rbdplugin-provsioner.txt)

[csi-rbdplugin.txt](https://github.com/ceph/ceph-csi/files/10393985/csi-rbdplugin.txt)

If the issue is in PVC resize please attach complete logs of below containers.

- csi-resizer and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in snapshot creation and deletion please attach complete logs
of below containers.

- csi-snapshotter and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC mounting please attach complete logs of below containers.

- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
  plugin pod from the node where the mount is failing.

- if required attach dmesg logs.

**Note:-** If its a rbd issue please provide only rbd related logs, if its a
cephFS issue please provide cephFS logs.

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by Madhu-1** [comment]
Please provide the logs asked for in the issue template.

**Comment by andyzheung** [comment]
> Please provide the logs asked for in the issue template.

add logs on the issue above.
@Madhu-1

**Comment by Madhu-1** [comment]
i dont see any issue in attached logs can you please check volumeattachment object created for this PVC, please check attacher container logs.

**Comment by andyzheung** [comment]
> in attached logs can you please check volumeattachment object created for this PVC, please check attacher container logs.

May be the pvc name is not the same I just for example, but the process is what I describe above:
[csi-rbdplugin.txt](https://github.com/ceph/ceph-csi/files/10397485/csi-rbdplugin.txt)
[csi-rbd-provisoner.txt](https://github.com/ceph/ceph-csi/files/10397486/csi-rbd-provisoner.txt)
@Madhu-1

**Comment by andyzheung** [comment]
I think the problem is that if a rbd pod mount pvc them delete the pod, and mount this pvc to another pvc, often can't mount to it.

**Comment by sahaniarun** [comment]
I am facing similar issue with cephfs CSI , PVC in pending state.
cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-7ddb7f8cf4-h5ndt_e0ac55de-d690-4ff2-8bd0-3826144152a2  failed to provision volume with StorageClass "csi-cephfs-sc": rpc error: code = InvalidArgument desc = volume not found
![Screenshot from 2023-02-16 17-40-52](https://user-images.githubusercontent.com/37756393/219365640-cdde4adb-4e43-4013-b922-9e1958e5891c.png)

**Comment by Madhu-1** [comment]
@sahaniarun, the error message says you dont have filesystem created. please check filesystem exists or not
