### ISSUE TITLE
Error while adding second OSD host.

### ISSUE THREAD

**Issue by david0dt** [ceph/ceph-csi#3625]
Hi,
I tried to deploy ceph cluster on Ubuntu20.04 LTS and ceph version Quincy. I created a cluster and added mon, mgr and OSD. While adding OSDs, first OSD was successfully added, but during addition of  second OSD I faced errors. 
Used this command to add OSD: **sudo ceph orch daemon add osd st04:/dev/nvme1n1** 
Can you please help me with the same.
Thanking you in anticipation.

**Comment by Madhu-1** [comment]
Please contact ceph for this one as cephcsi will not handle ceph cluster deployment.
