### ISSUE TITLE
Remove support for Kubernetes 1.23

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#3636]
This is a tracker to remove support for [1.23](https://kubernetes.io/releases/#release-v1-23) from cephcsi

- [x] Update centos CI branch to remove 1.23
- [x] Remove 1.23 check from mergify config
- [x] Remove 1.23 from the PR commenter github action
- [ ] Remove 1.23 from the supported version in Readme.

Update the same to use 1.26 kubernetes in required places, with that the supported versions will be 1.24, 1.25, and 1.26

**Comment by travisn** [comment]
Is this about updating the CI to only run tests on the most recent three K8s versions, or is there a specific reason to remove support for 1.23?

**Comment by Madhu-1** [comment]
@travisn above is true and also as per the official Kubernetes release doc 1.23  EOL will be 2023-02-28.

**Comment by nixpanic** [comment]
https://kubernetes.io/releases/ for reference.

#3690 is used to remove the 1.23 CI checks from Mergify.
