### ISSUE TITLE
provide way to apply configuration to specific ceph clusters.

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#3649]
Today we have cephcsi command line arguments like kernelmountoptions,fusemountoptions, etc. These options can also be specific to the ceph clusters that cephcsi is managing. If we set these command line arguments, this will be applied to all the ceph clusters cephcsi is connecting to, which will not work in some cases. The request is to make it configurable and identifiable based on the clusterID or something else.
```[tasklist]
### Tasks
- [ ] https://github.com/ceph/ceph-csi/issues/4161
- [ ] https://github.com/ceph/ceph-csi/pull/4245
```

**Comment by iPraveenParihar** [comment]
@Madhu-1, I think we can close this as the subtasks are completed. Or do you have anything on this?
