### ISSUE TITLE
Are there docs for managing two storage classes based on ceph in the same k8s cluster?

### ISSUE THREAD

**Issue by adux6991** [ceph/ceph-csi#3650]
I have a ceph storage cluster and created two filesystems. Do we support creating two corresponding storage classes in k8s? e.g. class-gold, class-silver. Would there be any conflicts? Thanks in advance!

**Comment by Madhu-1** [comment]
You can configure and use two storageclasses with the different filesystem, please check below configurations https://github.com/ceph/ceph-csi/blob/650c522ce016bcff86d590006d120f7b829fb93d/examples/cephfs/storageclass.yaml#L8-L22
