### ISSUE TITLE
PVs stuck in Release

### ISSUE THREAD

**Issue by GiuseppeLoRe** [ceph/ceph-csi#3654]
# Short description #

Hi,
I see the following behaviour. When I delete a PVC, the corresponding PV stays in Release state forever. 
The describe pv commands reports:

`  Warning  VolumeFailedDelete  5m46s              cephfs.csi.ceph.com_ceph-csi-cephfs-provisioner-554699696c-gplbv_ed3167e6-6e1f-44b3-abd7-3a080208a267  rpc error: code = Internal desc = rados: ret=-18, Invalid cross-device link: "error in rename /volumes/psi/psi-ab96c24a-a6f8-11ed-bbe4-c20311826a4f to /volumes/_deleting/52da84ee-a733-439b-8720-b046a6c41f04"
`

Only when unset the quota on the cephfs directory the PV is actually removed.

# Environment details #

- Image/version of Ceph CSI driver : 3.7.2
- Helm chart version : 3.7.2
- Kernel version : 5.4.0-131
- Mounter used for mounting PVC: kernel
- Kubernetes cluster version : v1.24.9+rke2r2
- Ceph cluster version : 16.2.7

# Steps to reproduce #

1. create pvc
2. remove pvc
3. describe/get pv
4. on the ceph cluster: # setfattr -n ceph.quota -v max_bytes=0 /mnt/cephfs/volumes/psi
5. get pv

After point action in point 4 the pv is deleted.

# Expected behavior #

The PV should be deleted regardless if there is a quota limit set on the cephfs directory.

# Logs #

I don't see anything on the provisioner logs... should I look somewhere else  or increase the verbosity?

**Comment by GiuseppeLoRe** [comment]
Some more details. These are the caps:
# ceph auth get client.psi
[client.psi]
	key = xxx==
	caps mds = "allow * path=/volumes/psi, allow * path=/volumes/_deleting, allow * path=/alps/psi"
	caps mgr = "allow rw"
	caps mon = "allow r, profile rbd"
	caps osd = "allow rw tag cephfs *=*, profile rbd pool=psi-hdd-data, profile rbd pool=psi-nvme-meta"

**Comment by Madhu-1** [comment]
@GiuseppeLoRe please check the caps here https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#cephfs

**Comment by GiuseppeLoRe** [comment]
Hi @Madhu-1 from what I can see the caps are correct.
On that page I see:

mon 'allow r' \
osd 'allow rw tag cephfs *=*' \
mgr 'allow rw' \
mds 'allow rw'

On my cluster I have

mon = "allow r, profile rbd"
osd = "allow rw tag cephfs *=*, profile rbd pool=psi-hdd-data, profile rbd pool=psi-nvme-meta"
mgr = "allow rw"
mds = "allow * path=/volumes/psi, allow * path=/volumes/_deleting, allow * path=/alps/psi"

To me my caps are very close to the one in that doc page, except for the path restriction. I even give "*" instead of only "rw" for the mds part.

We did also the test to remove all restrictions, with "allow *" on everything but even in that situation the error was occurring, until we unset the quota on /volumes/psi.

**Comment by Madhu-1** [comment]
>gplbv_ed3167e6-6e1f-44b3-abd7-3a080208a267  rpc error: code = Internal desc = rados: ret=-18, Invalid cross-device link: "error in rename /volumes/psi/psi-ab96c24a-a6f8-11ed-bbe4-c20311826a4f to /volumes/_deleting/52da84ee-a733-439b-8720-b046a6c41f04"

The above error is coming from ceph.
@mchangir @kotreshhr can you please help here

**Comment by humblec** [comment]
@GiuseppeLoRe whats the size of this PVC? Is it really large?  My assumption here from this error is that , the source PVC is really large and syscall while deleting this pvc/dir land on this error due to the size of  the source Dir.
Ideally the quota setting to `0` would have helped in this situation

Do you see the same error on any other PVC ?  if yes, is it a small sized PVC  or really large one ?

**Comment by GiuseppeLoRe** [comment]
@humblec no is not a large pvc, the ones I have been using in my tests have a size of 1 GB. 
I'll try again with a smaller one if you think that would be useful to debug.

**Comment by humblec** [comment]
> @humblec no is not a large pvc, the ones I have been using in my tests have a size of 1 GB. I'll try again with a smaller one if you think that would be useful to debug.

may be not, because mostly that error comes in, while the source and dest of that file/dir movement belong to different FSs which I dont think is the case here. Also, I have seen similar error while move operation  is attempted  on a large dir in the Ceph Filesystem or that operation is taking long time which i in turn happens mostly due to a large filesystem in the backend. Thats why I was checking the size.  @GiuseppeLoRe

**Comment by GiuseppeLoRe** [comment]
@humblec the PV and relative directory are not large, as I said 1 GB in the test from which I have posted the error message.
The file system is actually big, 

[root@naret-monitor01 ~]# df -h /mnt/cephfs/
Filesystem             Size  Used Avail Use% Mounted on
148.187.20.141:6789:/   29P  6.0P   23P  21% /mnt/cephfs
