### ISSUE TITLE
How can I configure a snapshot cephFS PVC  through the helm chart?

### ISSUE THREAD

**Issue by andruwa13** [ceph/ceph-csi#3691]
There is no documentation on how to make a snapshot cephFS through a Helm chart.

**Comment by Madhu-1** [comment]
@andruwa13, what snapshot are you talking about, is that volume snapshot for cephfs PVC?

**Comment by andruwa13** [comment]
@Madhu-1 yes

**Comment by andruwa13** [comment]
The problem is still relevant
