### ISSUE TITLE
Reboot of worker node, Ceph CSI with encrypted volume

### ISSUE THREAD

**Issue by ipapatha85** [ceph/ceph-csi#3694]
Hi!

we are testing encrypted volumes in Ceph CSI (initially on RBD), and we are trying to understand what will happen in case a non-graceful reboot of worker takes place.

Application pod is rescheduled in other worker node. However, since unstaging of the volume was not performed, volume cannot be used in the new worker node.

In case of encrypted volume, apart from unmounting of staging path, closing of LUKS device and device mapping removal are taking place, too.

How Ceph will handle this kind of negative scenario?

Many thanks in advance!

# Environment details #

- Image/version of Ceph CSI driver : v3.6.2
- Kubernetes cluster version : 1.23.6

**Comment by Rakshith-R** [comment]
>closing of LUKS device and device mapping removal are taking place, too.

@ipapatha85 
Rebooting of worker nodes should take care of both removing LUKS device and the mapping, there's no need for any action from cephcsi side.

**Comment by ipapatha85** [comment]
Hi [Rakshith-R](https://github.com/Rakshith-R),

very clear! thanks a lot for the feedback.
