### ISSUE TITLE
volume deletion failed: rpc error: code = Internal desc = rbd: ret=-95, Operation not supported

### ISSUE THREAD

**Issue by gmyh** [ceph/ceph-csi#3699]
# Describe the bug #

kubelet delete pvc, can't pv and backend rbd .

# Environment details #

- Image/version of Ceph CSI driver : cephcsi:canary csi-node-driver-registrar:v2.5.1 csi-provisioner:canary csi-snapshotter:v6.0.1 csi-attacher:v3.4.0 csi-resizer:v1.4.0
- Kubernetes cluster version : v1.25.4
- Ceph cluster version : ceph version 10.2.2

# Steps to reproduce #

kubectl apply -f pvc.yaml 

pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-abcdocker
  labels:
    app: abcdocker-test
spec:
  storageClassName: csi-rbd-sc 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

 kubectl get pvc
NAME                             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nginx-pvc-abcdocker              Bound    pvc-1821806f-9bbe-4654-b976-e165845bf842   8Gi        RWO            csi-rbd-sc     4s

kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                    STORAGECLASS   REASON   AGE
pvc-1821806f-9bbe-4654-b976-e165845bf842   8Gi        RWO            Delete           Bound    default/nginx-pvc-abcdocker              csi-rbd-sc              4s

kubectl delete -f pvc.yaml 
persistentvolumeclaim "nginx-pvc-abcdocker" deleted

kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                    STORAGECLASS   REASON   AGE
pvc-1821806f-9bbe-4654-b976-e165845bf842   8Gi        RWO            Delete           Released   default/nginx-pvc-abcdocker              csi-rbd-sc              82s

kubectl logs csi-rbdplugin-provisioner-66fbb4f497-2b56q -c  csi-provisioner

I0301 06:33:29.015642       1 controller.go:1471] delete "pvc-1821806f-9bbe-4654-b976-e165845bf842": started
I0301 06:33:29.021118       1 connection.go:183] GRPC call: /csi.v1.Controller/DeleteVolume
I0301 06:33:29.021141       1 connection.go:184] GRPC request: {"secrets":"***stripped***","volume_id":"0001-0024-4812db37-1c81-463f-8d56-16a288f03657-0000000000000006-54c1d9a6-d0ed-4ee5-8f4b-095f179ab786"}
I0301 06:33:29.097312       1 connection.go:186] GRPC response: {}
I0301 06:33:29.097354       1 connection.go:187] GRPC error: rpc error: code = Internal desc = rbd: ret=-95, Operation not supported
E0301 06:33:29.097384       1 controller.go:1481] delete "pvc-1821806f-9bbe-4654-b976-e165845bf842": volume deletion failed: rpc error: code = Internal desc = rbd: ret=-95, Operation not supported
W0301 06:33:29.097420       1 controller.go:989] Retrying syncing volume "pvc-1821806f-9bbe-4654-b976-e165845bf842", failure 5
E0301 06:33:29.097453       1 controller.go:1007] error syncing volume "pvc-1821806f-9bbe-4654-b976-e165845bf842": rpc error: code = Internal desc = rbd: ret=-95, Operation not supported
I0301 06:33:29.097543       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-1821806f-9bbe-4654-b976-e165845bf842", UID:"9b958c08-7298-4a57-87f9-2a16b8ae14ea", APIVersion:"v1", ResourceVersion:"41776691", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' rpc error: code = Internal desc = rbd: ret=-95, Operation not supported
I0301 06:33:33.045072       1 leaderelection.go:278] successfully renewed lease default/rbd-csi-ceph-com
I0301 06:33:38.058274       1 leaderelection.go:278] successfully renewed lease default/rbd-csi-ceph-com
I0301 06:33:43.071506       1 leaderelection.go:278] successfully renewed lease default/rbd-csi-ceph-com
I0301 06:33:45.098549       1 controller.go:1471] delete "pvc-1821806f-9bbe-4654-b976-e165845bf842": started
I0301 06:33:45.104121       1 connection.go:183] GRPC call: /csi.v1.Controller/DeleteVolume
I0301 06:33:45.104150       1 connection.go:184] GRPC request: {"secrets":"***stripped***","volume_id":"0001-0024-4812db37-1c81-463f-8d56-16a288f03657-0000000000000006-54c1d9a6-d0ed-4ee5-8f4b-095f179ab786"}
I0301 06:33:45.173382       1 connection.go:186] GRPC response: {}
I0301 06:33:45.173412       1 connection.go:187] GRPC error: rpc error: code = Internal desc = rbd: ret=-95, Operation not supported
E0301 06:33:45.173434       1 controller.go:1481] delete "pvc-1821806f-9bbe-4654-b976-e165845bf842": volume deletion failed: rpc error: code = Internal desc = rbd: ret=-95, Operation not supported
W0301 06:33:45.173469       1 controller.go:989] Retrying syncing volume "pvc-1821806f-9bbe-4654-b976-e165845bf842", failure 6
E0301 06:33:45.173494       1 controller.go:1007] error syncing volume "pvc-1821806f-9bbe-4654-b976-e165845bf842": rpc error: code = Internal desc = rbd: ret=-95, Operation not supported
I0301 06:33:45.173545       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-1821806f-9bbe-4654-b976-e165845bf842", UID:"9b958c08-7298-4a57-87f9-2a16b8ae14ea", APIVersion:"v1", ResourceVersion:"41776691", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' rpc error: code = Internal desc = rbd: ret=-95, Operation not supported

kubectl logs csi-rbdplugin-provisioner-66fbb4f497-2b56q -c csi-rbdplugin

I0301 06:34:17.250713       1 rbd_util.go:628] ID: 1317 Req-ID: 0001-0024-4812db37-1c81-463f-8d56-16a288f03657-0000000000000006-54c1d9a6-d0ed-4ee5-8f4b-095f179ab786 rbd: delete csi-vol-54c1d9a6-d0ed-4ee5-8f4b-095f179ab786-temp using mon 10.104.50.179:6789, pool kubernetes
E0301 06:34:17.257381       1 rbd_util.go:609] ID: 1317 Req-ID: 0001-0024-4812db37-1c81-463f-8d56-16a288f03657-0000000000000006-54c1d9a6-d0ed-4ee5-8f4b-095f179ab786 failed to list images in trash: rbd: ret=-95, Operation not supported
E0301 06:34:17.257438       1 utils.go:210] ID: 1317 Req-ID: 0001-0024-4812db37-1c81-463f-8d56-16a288f03657-0000000000000006-54c1d9a6-d0ed-4ee5-8f4b-095f179ab786 GRPC error: rpc error: code = Internal desc = rbd: ret=-95, Operation not supported
I0301 06:34:28.619635       1 utils.go:195] ID: 1318 GRPC call: /csi.v1.Identity/Probe
I0301 06:34:28.619706       1 utils.go:206] ID: 1318 GRPC request: {}
I0301 06:34:28.619742       1 utils.go:212] ID: 1318 GRPC response: {}
I0301 06:35:21.264435       1 utils.go:195] ID: 1319 Req-ID: 0001-0024-4812db37-1c81-463f-8d56-16a288f03657-0000000000000006-54c1d9a6-d0ed-4ee5-8f4b-095f179ab786 GRPC call: /csi.v1.Controller/DeleteVolume
I0301 06:35:21.264592       1 utils.go:206] ID: 1319 Req-ID: 0001-0024-4812db37-1c81-463f-8d56-16a288f03657-0000000000000006-54c1d9a6-d0ed-4ee5-8f4b-095f179ab786 GRPC request: {"secrets":"***stripped***","volume_id":"0001-0024-4812db37-1c81-463f-8d56-16a288f03657-0000000000000006-54c1d9a6-d0ed-4ee5-8f4b-095f179ab786"}
I0301 06:35:21.267329       1 omap.go:88] ID: 1319 Req-ID: 0001-0024-4812db37-1c81-463f-8d56-16a288f03657-0000000000000006-54c1d9a6-d0ed-4ee5-8f4b-095f179ab786 got omap values: (pool="kubernetes", namespace="", name="csi.volume.54c1d9a6-d0ed-4ee5-8f4b-095f179ab786"): map[csi.imageid:08d1045befb924 csi.imagename:csi-vol-54c1d9a6-d0ed-4ee5-8f4b-095f179ab786 csi.volname:pvc-1821806f-9bbe-4654-b976-e165845bf842 csi.volume.owner:default]
I0301 06:35:21.330255       1 rbd_util.go:628] ID: 1319 Req-ID: 0001-0024-4812db37-1c81-463f-8d56-16a288f03657-0000000000000006-54c1d9a6-d0ed-4ee5-8f4b-095f179ab786 rbd: delete csi-vol-54c1d9a6-d0ed-4ee5-8f4b-095f179ab786-temp using mon 10.104.50.179:6789, pool kubernetes
E0301 06:35:21.337416       1 rbd_util.go:609] ID: 1319 Req-ID: 0001-0024-4812db37-1c81-463f-8d56-16a288f03657-0000000000000006-54c1d9a6-d0ed-4ee5-8f4b-095f179ab786 failed to list images in trash: rbd: ret=-95, Operation not supported
E0301 06:35:21.337469       1 utils.go:210] ID: 1319 Req-ID: 0001-0024-4812db37-1c81-463f-8d56-16a288f03657-0000000000000006-54c1d9a6-d0ed-4ee5-8f4b-095f179ab786 GRPC error: rpc error: code = Internal desc = rbd: ret=-95, Operation not supported

**Comment by nixpanic** [comment]
Please have a look at the [Support matrix](https://github.com/ceph/ceph-csi#support-matrix) that lists the Ceph versions that are supported. If you're really using an old Ceph 10.2.2 cluster, don't expect Ceph-CSI to work with that.
