### ISSUE TITLE
Containers of csi-cephfsplugin-provisioner are getting terminated with exit code 255.

### ISSUE THREAD

**Issue by dbenduga** [ceph/ceph-csi#3702]

**Comment by dbenduga** [comment]
Below listed containers are getting terminated with exit code 255. We are able to provision dynamic PVC and don't see any issue. Just want to know why these many restart.


NAME                                            READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-4kj4f                          3/3     Running   0          250d
csi-cephfsplugin-9zhp6                          3/3     Running   0          251d
csi-cephfsplugin-d5cqq                          3/3     Running   0          250d
csi-cephfsplugin-dn5qp                          3/3     Running   0          250d
csi-cephfsplugin-p622p                          3/3     Running   0          251d
csi-cephfsplugin-provisioner-84bb5b599c-fkpdz   6/6     Running   65         233d
csi-cephfsplugin-vb9d5                          3/3     Running   0          250d



  csi-resizer:
    Container ID:  cri-o://a4eeefd5ea9836c17e16f464623d0236cdd3ce83e62a5afc4d186271a399a026
    Image:         k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
    Image ID:      k8s.gcr.io/sig-storage/csi-resizer@sha256:9ebbf9f023e7b41ccee3d52afe39a89e3ddacdbb69269d583abfc25847cfd9e4
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=5
      --timeout=150s
      --leader-election
      --retry-interval-start=500ms
      --handle-volume-inuse-error=false
    State:          Running
      Started:      Fri, 06 Jan 2023 00:56:09 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255

***************************
Containers:
  csi-provisioner:
    Container ID:  cri-o://8e06295adee997cf560bde18ad64c101d04ae413b9c00fb3d1bf25c08ac3aa70
    Image:         k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
    Image ID:      k8s.gcr.io/sig-storage/csi-provisioner@sha256:122bfb8c1edabb3c0edd63f06523e6940d958d19b3957dc7b1d6f81e9f1f6119
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=5
      --timeout=150s
      --leader-election=true
      --retry-interval-start=500ms
      --feature-gates=Topology=false
      --extra-create-metadata=true
    State:          Running
      Started:      Wed, 21 Dec 2022 19:41:32 +0000
    Last State:     Terminated
      Reason:       Error
*********************************
  csi-snapshotter:
    Container ID:  cri-o://fb3d18875fbf297736d0f5c90dd0c257e7f61b85460abe8aa79440c4820b77f8
    Image:         k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
    Image ID:      k8s.gcr.io/sig-storage/csi-snapshotter@sha256:89e900a160a986a1a7a4eba7f5259e510398fa87ca9b8a729e7dec59e04c7709
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=5
      --timeout=150s
      --leader-election=true
    State:          Running
      Started:      Tue, 14 Feb 2023 21:21:28 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
***********************************
  csi-cephfsplugin-attacher:
    Container ID:  cri-o://5b3999e5e9bb0e28dfcc26d8a1bc270e19fd68c603206c576c189f69b3eec617
    Image:         k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
    Image ID:      k8s.gcr.io/sig-storage/csi-attacher@sha256:8b9c313c05f54fb04f8d430896f5f5904b6cb157df261501b29adc04d2b2dc7b
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --csi-address=$(ADDRESS)
      --leader-election=true
      --retry-interval-start=500ms
    State:          Running
      Started:      Tue, 14 Feb 2023 21:21:29 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255

**Comment by nixpanic** [comment]
Please provide the logs of the containers, and events from the namespace. Without any details, there is nothing that can be said about the cause of the termination.

**Comment by dbenduga** [comment]
logs from previous container.

goroutine 503 [sync.Cond.Wait, 168 minutes]:
sync.runtime_notifyListWait(0xc000249210, 0x57b)
        /go/pkg/csiprow.XXXXcGaFcn/go-1.17.3/src/runtime/sema.go:513 +0x13d
sync.(*Cond).Wait(0x0)
        /go/pkg/csiprow.XXXXcGaFcn/go-1.17.3/src/sync/cond.go:56 +0x8c
k8s.io/client-go/util/workqueue.(*Type).Get(0xc0006f81e0)
        /workspace/vendor/k8s.io/client-go/util/workqueue/queue.go:157 +0x9e
sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).processNextClaimWorkItem(0xc00044af00, {0x1c09090, 0xc000b0c3c0})
        /workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:911 +0x3e
sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).runClaimWorker(...)
        /workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:900
sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).Run.func1.2()
        /workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:856 +0x45
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f152b7c0768)
        /workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x1bd8120, 0xc000893020}, 0x1, 0xc0001d3140)
        /workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)
        /workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)
        /workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x25
created by sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).Run.func1
        /workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:856 +0xbaf

goroutine 504 [sync.Cond.Wait, 108 minutes]:
sync.runtime_notifyListWait(0xc000249310, 0x592)
        /go/pkg/csiprow.XXXXcGaFcn/go-1.17.3/src/runtime/sema.go:513 +0x13d
sync.(*Cond).Wait(0x16bd780)
        /go/pkg/csiprow.XXXXcGaFcn/go-1.17.3/src/sync/cond.go:56 +0x8c
k8s.io/client-go/util/workqueue.(*Type).Get(0xc0006f83c0)
        /workspace/vendor/k8s.io/client-go/util/workqueue/queue.go:157 +0x9e
sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).processNextVolumeWorkItem(0xc00044af00, {0x1c09090, 0xc000b0c3c0})
        /workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:966 +0x3e
sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).runVolumeWorker(...)
        /workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:905
sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).Run.func1.3()
        /workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:857 +0x45
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f152b84fd50)
        /workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x1bd8120, 0xc00049b9e0}, 0x1, 0xc0001d3140)
        /workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)
        /workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)
        /workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x25
created by sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller.(*ProvisionController).Run.func1
        /workspace/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v8/controller/controller.go:857 +0xa78
I0223 17:11:27.571334       1 reflector.go:225] Stopping reflector *v1.PersistentVolumeClaim (15m0s) from k8s.io/client-go/informers/factory.go:134
I0223 17:11:27.571360       1 volume_store.go:104] Stopped save volume queue
E0223 17:11:27.569221       1 event.go:276] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".1746834f3b8b4d23", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Lease", Namespace:"", Name:"", UID:"", APIVersion:"coordination.k8s.io/v1", ResourceVersion:"", FieldPath:""}, Reason:"LeaderElection", Message:"csi-cephfsplugin-provisioner-7bb9b6b77-8glnz stopped leading", Source:v1.EventSource{Component:"cephfs.csi.ceph.com/csi-cephfsplugin-provisioner-7bb9b6b77-8glnz", Host:""}, FirstTimestamp:time.Date(2023, time.February, 23, 17, 11, 27, 566728483, time.Local), LastTimestamp:time.Date(2023, time.February, 23, 17, 11, 27, 566728483, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't create an event with namespace 'default' in namespace 'ceph''(may retry after sleeping)

**Comment by dbenduga** [comment]
##csi-cephfsplugin-provisioner.yaml  file

---
kind: Service
apiVersion: v1
metadata:
  name: csi-cephfsplugin-provisioner
  namespace: ceph
  labels:
    app: csi-metrics
spec:
  selector:
    app: csi-cephfsplugin-provisioner
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: 8681

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-cephfsplugin-provisioner
  namespace: ceph
spec:
  selector:
    matchLabels:
      app: csi-cephfsplugin-provisioner
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-cephfsplugin-provisioner
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - csi-cephfsplugin-provisioner
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: cephfs-csi-provisioner
      priorityClassName: system-cluster-critical
      containers:
        - name: csi-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--timeout=150s"
            - "--leader-election=true"
            - "--retry-interval-start=500ms"
            - "--feature-gates=Topology=false"
            - "--extra-create-metadata=true"
          env:
            - name: ADDRESS
              value: unix:///csi/csi-provisioner.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-resizer
          image: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--timeout=150s"
            - "--leader-election"
            - "--retry-interval-start=500ms"
            - "--handle-volume-inuse-error=false"
          env:
            - name: ADDRESS
              value: unix:///csi/csi-provisioner.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-snapshotter
          image: k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--timeout=150s"
            - "--leader-election=true"
          env:
            - name: ADDRESS
              value: unix:///csi/csi-provisioner.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-cephfsplugin-attacher
          image: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election=true"
            - "--retry-interval-start=500ms"
          env:
            - name: ADDRESS
              value: /csi/csi-provisioner.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-cephfsplugin
          # for stable functionality replace canary with latest release version
          image: quay.io/cephcsi/cephcsi:v3.6.1
          args:
            - "--nodeid=$(NODE_ID)"
            - "--type=cephfs"
            - "--controllerserver=true"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--v=5"
            - "--drivername=cephfs.csi.ceph.com"
            - "--pidlimit=-1"
            - "--enableprofiling=false"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///csi/csi-provisioner.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: host-sys
              mountPath: /sys
            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true
            - name: host-dev
              mountPath: /dev
            - name: ceph-config
              mountPath: /etc/ceph/
            - name: ceph-csi-config
              mountPath: /etc/ceph-csi-config/
            - name: keys-tmp-dir
              mountPath: /tmp/csi/keys
        - name: liveness-prometheus
          image: quay.io/cephcsi/cephcsi:v3.6.1
          args:
            - "--type=liveness"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--metricsport=8681"
            - "--metricspath=/metrics"
            - "--polltime=60s"
            - "--timeout=3s"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi-provisioner.sock
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          imagePullPolicy: "IfNotPresent"
      volumes:
        - name: socket-dir
          emptyDir: {
            medium: "Memory"
          }
        - name: host-sys
          hostPath:
            path: /sys
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: host-dev
          hostPath:
            path: /dev
        - name: ceph-config
          configMap:
            name: ceph-config
        - name: ceph-csi-config
          configMap:
            name: ceph-csi-config
        - name: keys-tmp-dir
          emptyDir: {
            medium: "Memory"
          }

**Comment by dbenduga** [comment]
**logs  from csi-resizer container** 


goroutine 47214 [IO wait]:
internal/poll.runtime_pollWait(0x7fa5a44edce8, 0x72)
        /go/pkg/csiprow.XXXXGAHoFa/go-1.17.3/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000740180, 0xc00032f800, 0x0)
        /go/pkg/csiprow.XXXXGAHoFa/go-1.17.3/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /go/pkg/csiprow.XXXXGAHoFa/go-1.17.3/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000740180, {0xc00032f800, 0xb02, 0xb02})
        /go/pkg/csiprow.XXXXGAHoFa/go-1.17.3/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000740180, {0xc00032f800, 0xc00032f805, 0x308})
        /go/pkg/csiprow.XXXXGAHoFa/go-1.17.3/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc000888118, {0xc00032f800, 0x6, 0xc00040c7f0})
        /go/pkg/csiprow.XXXXGAHoFa/go-1.17.3/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0005bec30, {0xc00032f800, 0x0, 0x4099cd})
        /go/pkg/csiprow.XXXXGAHoFa/go-1.17.3/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc0005fc5f8, {0x1ad7660, 0xc0005bec30})
        /go/pkg/csiprow.XXXXGAHoFa/go-1.17.3/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0005fc380, {0x1ada2e0, 0xc000888118}, 0xb02)
        /go/pkg/csiprow.XXXXGAHoFa/go-1.17.3/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0005fc380, 0x0)
        /go/pkg/csiprow.XXXXGAHoFa/go-1.17.3/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
        /go/pkg/csiprow.XXXXGAHoFa/go-1.17.3/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc0005fc380, {0xc0002bb000, 0x1000, 0x846220})
        /go/pkg/csiprow.XXXXGAHoFa/go-1.17.3/src/crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc00074f560, {0xc0005d8200, 0x9, 0x8541e2})
        /go/pkg/csiprow.XXXXGAHoFa/go-1.17.3/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x1ad74c0, 0xc00074f560}, {0xc0005d8200, 0x9, 0x9}, 0x9)
        /go/pkg/csiprow.XXXXGAHoFa/go-1.17.3/src/io/io.go:328 +0x9a
io.ReadFull(...)
        /go/pkg/csiprow.XXXXGAHoFa/go-1.17.3/src/io/io.go:347
golang.org/x/net/http2.readFrameHeader({0xc0005d8200, 0x9, 0xc0018a40f0}, {0x1ad74c0, 0xc00074f560})
        /workspace/vendor/golang.org/x/net/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0005d81c0)
        /workspace/vendor/golang.org/x/net/http2/frame.go:498 +0x95
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00040cf98)
        /workspace/vendor/golang.org/x/net/http2/transport.go:2101 +0x130
golang.org/x/net/http2.(*ClientConn).readLoop(0xc00041b800)
        /workspace/vendor/golang.org/x/net/http2/transport.go:1997 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
        /workspace/vendor/golang.org/x/net/http2/transport.go:725 +0xac5

goroutine 47215 [select, 5 minutes]:
golang.org/x/net/http2.(*clientStream).writeRequest(0xc00041bb00, 0xc00057f000)
        /workspace/vendor/golang.org/x/net/http2/transport.go:1323 +0xaa8
golang.org/x/net/http2.(*clientStream).doRequest(0xc000723560, 0x0)
        /workspace/vendor/golang.org/x/net/http2/transport.go:1185 +0x1e
created by golang.org/x/net/http2.(*ClientConn).RoundTrip
        /workspace/vendor/golang.org/x/net/http2/transport.go:1114 +0x30f

goroutine 47240 [select, 5 minutes]:
golang.org/x/net/http2.(*clientStream).writeRequest(0xc0006b1b00, 0xc0004b3b00)
        /workspace/vendor/golang.org/x/net/http2/transport.go:1323 +0xaa8
golang.org/x/net/http2.(*clientStream).doRequest(0xc00029c180, 0xc0006aefd0)
        /workspace/vendor/golang.org/x/net/http2/transport.go:1185 +0x1e
created by golang.org/x/net/http2.(*ClientConn).RoundTrip
        /workspace/vendor/golang.org/x/net/http2/transport.go:1114 +0x30f
I0228 22:22:04.082711       1 controller.go:274] Shutting down external resizer cephfs.csi.ceph.com

**Comment by Madhu-1** [comment]
@dbenduga this looks to be an issue connecting to the kubernetes API server.  please provide complete logs of anyone of the container which is getting terminated.

**Comment by dbenduga** [comment]
Below pods are running in ceph namespace.  only "csi-cephfsplugin-provisioner" getting restarted 

Attached are complete logs of pods that are restarting.

NAME                                           READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-7b5nk                         3/3     Running   0          56d
csi-cephfsplugin-drdcm                         3/3     Running   0          82d
csi-cephfsplugin-g5bc8                         3/3     Running   0          56d
csi-cephfsplugin-pr7kf                         3/3     Running   0          55d
csi-cephfsplugin-provisioner-7bb9b6b77-8glnz   6/6     Running   61         55d
csi-cephfsplugin-qtt45                         3/3     Running   0          56d


- 
[podlogs.zip](https://github.com/ceph/ceph-csi/files/10977498/podlogs.zip)

**Comment by dbenduga** [comment]
@Madhu-1 - any luck :)

**Comment by Rakshith-R** [comment]
@dbenduga please open issue on corresponding repo here https://github.com/kubernetes-csi .
As far I can see above cephcsi container is not the reason for restarts.
