### ISSUE TITLE
Change limit INODES rbd device

### ISSUE THREAD

**Issue by denitol** [ceph/ceph-csi#374]
I trying formatting device real time, but I can't doing that because device is busy
```mkfs -t ext4 -N iNumberOfINodes /dev/XdY```
```/dev/rbd11 is mounted; will not make a filesystem here!```

How I can change limit inodes for my rbd block?

**Comment by Madhu-1** [comment]
CC @dillaman

**Comment by nixpanic** [comment]
Related to #626, although that is a parameter to the StorageClass and the number of inodes is surely a configuration attribute for the PV (as it depends on the size).

Alternatively XFS can be used, it dynamically allocates inodes so there is no practical limit.

**Comment by nixpanic** [comment]
Also, this feature is probably useful in the Kubernetes external-provisioner. So maybe it should get implemented there, and not in Ceph-CSI directly.

**Comment by nixpanic** [comment]
By placing `mkfsOptions` in the `VolumeContext`, the `NodeStageVolume` procedure can access the options and use it for formatting the filesystem. The `mkfsOptions` can be placed in the `StorageClass`.

**Comment by Madhu-1** [comment]
> By placing `mkfsOptions` in the `VolumeContext`, the `NodeStageVolume` procedure can access the options and use it for formatting the filesystem. The `mkfsOptions` can be placed in the `StorageClass`.

Yes, this is an option that can be applicable only for the SP. and it cannot be changed dynamically as it will be stored in volumeAttributes of the PV object.
