### ISSUE TITLE
Update Kubernetes dependencies/CI to 1.27

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#3743]
Kubernetes 1.27 is released https://kubernetes.io/blog/2023/04/11/kubernetes-v1-27-release/ let's make use of it in cephcsi

- [x]  Make Kubernetes E2E test mandatory in CI Run
- [x] Update Mergify rules to consider tests on kube 1.27
- [x] go dependency update
- [x] Readme update

**Comment by riya-singhal31** [comment]
Fix for subtask 2: https://github.com/ceph/ceph-csi/pull/3744

**Comment by riya-singhal31** [comment]
Fix for subtask 3: https://github.com/ceph/ceph-csi/pull/3752

**Comment by riya-singhal31** [comment]
Fix for subtask 4: https://github.com/ceph/ceph-csi/pull/3777

**Comment by riya-singhal31** [comment]
Fix for subtask 1: https://github.com/ceph/ceph-csi/pull/3745

**Comment by riya-singhal31** [comment]
closes-with: https://github.com/ceph/ceph-csi/pull/3752

**Comment by riya-singhal31** [comment]
@Madhu-1 , this can be closed now with https://github.com/ceph/ceph-csi/pull/3848
