### ISSUE TITLE
csi cannot create pvc 

### ISSUE THREAD

**Issue by jiamengguo** [ceph/ceph-csi#3746]
k8s 版本 21 
ceph version 15.2.17
csi 3.3 

创建pvc提示
  Type     Reason                Age                From                                                                                                    Message
  ----     ------                ----               ----                                                                                                    -------
  Normal   Provisioning          10s (x7 over 41s)  cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-7f9f774794-kk65f_86c74434-1420-4d80-a785-19c283d2eff2  External provisioner is provisioning volume for claim "cephcsi/data"
  Warning  ProvisioningFailed    10s (x7 over 41s)  cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-7f9f774794-kk65f_86c74434-1420-4d80-a785-19c283d2eff2  failed to provision volume with StorageClass "csi-cephfs-sc": rpc error: code = InvalidArgument desc = failed to get connection: connecting failed: rados: ret=-13, Permission denied
  Normal   ExternalProvisioning  1s (x4 over 41s)   persistentvolume-controller                                                                             waiting for a volume to be created, either by external provisioner "cephfs.csi.ceph.com" or manually created by system administrator

**Comment by jiamengguo** [comment]
![csi](https://user-images.githubusercontent.com/130622684/231692515-28f1a916-644d-4101-bd24-9e2626d21f20.png)

**Comment by Madhu-1** [comment]
@jiamengguo please fill in the issue template when opening an issue, Thank you

**Comment by wht1998** [comment]
> k8s 版本 21 ceph version 15.2.17 csi 3.3
> 
> 创建pvc提示 Type Reason Age From Message
> 
> Normal Provisioning 10s (x7 over 41s) cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-7f9f774794-kk65f_86c74434-1420-4d80-a785-19c283d2eff2 External provisioner is provisioning volume for claim "cephcsi/data" Warning ProvisioningFailed 10s (x7 over 41s) cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-7f9f774794-kk65f_86c74434-1420-4d80-a785-19c283d2eff2 failed to provision volume with StorageClass "csi-cephfs-sc": rpc error: code = InvalidArgument desc = failed to get connection: connecting failed: rados: ret=-13, Permission denied Normal ExternalProvisioning 1s (x4 over 41s) persistentvolume-controller waiting for a volume to be created, either by external provisioner "cephfs.csi.ceph.com" or manually created by system administrator

same issue,how resolve

**Comment by Madhu-1** [comment]
@wht1998 please make sure you have required caps https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#cephfs

**Comment by wht1998** [comment]
> [@wht1998](https://github.com/wht1998) please make sure you have required caps https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#cephfs

<img width="450" height="115" alt="Image" src="https://github.com/user-attachments/assets/005a8a13-de89-4f91-8b26-05f7268cc9f9" />
admin account

**Comment by Madhu-1** [comment]
can you please share the storageclass yaml? it would be better to open an new issue instead of using the existing closed one
