### ISSUE TITLE
csi 存储类创建pvc报错

### ISSUE THREAD

**Issue by jiamengguo** [ceph/ceph-csi#3747]
使用ceph-csi 创建pvc报错

k8s 版本 21
ceph version 15.2.17
ceph-csi  3.3 

![csi](https://user-images.githubusercontent.com/130622684/231699488-5530386a-26ef-41a9-9d0e-3bff1723446b.png)

**Comment by Madhu-1** [comment]
cephcsi 3.3 is not a supported version, please use the latest cephcsi version and make sure you have the required caps https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#cephfs, please create issues in English as its a common language for communication to get response

**Comment by jiamengguo** [comment]
> CePHCSI 3.3 不是受支持的版本，请使用最新的 CEPHCSI 版本并确保您具有所需的大写字母 https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#cephfs，请用英语创建问题，因为它是沟通以获得响应的通用语言


Thank you. I'll try
