### ISSUE TITLE
Parameter `pool` in CephFS storageclass should be made optional

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#380]
The CephFS storage class parameters mention that `pool` is a required parameter when `provisionVolume` parameter is `true` [1].

When a pool name is provided, its value is being used to set the following extended attributes on the subdirectory created for the CSI volume request in order to govern its layout [2],
- ceph.dir.layout.pool
and,
- ceph.dir.layout.pool_namespace

This parameter should be made optional, such that if not provided, the data goes to the default layouts (hence pools) as configured for the parent FS where the subvolume is created.

[1] storageclass reference: https://github.com/ceph/ceph-csi/blob/f60a07ae8268136f40de3d62537f4f8b020f0ec4/examples/cephfs/storageclass.yaml#L21

[2] CephFS layouts: http://docs.ceph.com/docs/nautilus/cephfs/file-layouts/

**Comment by humblec** [comment]
@poornimag Is it something u can address with Ceph Mgr PR #400 ?
