### ISSUE TITLE
csi-rbdplugin-xx pod restarts when attempting to create large amount of static PVs

### ISSUE THREAD

**Issue by perspectivus1** [ceph/ceph-csi#3803]
# Describe the bug #

When I simultaneously deploy Kubernetes `Deployment`s that cumulatively mount hundreds of existing rbd images ([**static** PVC](https://github.com/ceph/ceph-csi/blob/devel/docs/static-pvc.md)), the pod of the relevant CSI driver restarts multiple times. Consequently, the application pods take a very long time to become ready (between 10 minutes to several hours, depending on the amount of mounts).

In contrast, when I use **dynamic** provisioning, the application pods take ~30 minutes to become ready (again, depending on the amount of mounts), and there are no CSI driver restarts.

# Environment details #

- Image/version of Ceph CSI driver : v3.6.1
- Helm chart version : 
- Kernel version : 5.10.141
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : krbd
- Kubernetes cluster version : v1.24.12
- Ceph cluster version : version 17.2.5 quincy

# Steps to reproduce #

1. Setup details:
    1. I created 600 rbd images of size 1GB.
    1. I created a single namespace in Kubernetes.
    1. I created a helm chart that deploys:
        1. 600 "static" `PersistentVolumeClaim`s in that namespace and 600 corresponding `PersistentVolume`s.
        1. 20 deployments with replica size 1. Each pod in the deployment runs 1 alpine container that does nothing (`tail -f /dev/null;`). Each container mounts 30 of the PVCs.
1. Deployment to trigger the issue: Performing the above deployment causes the CSI driver pod to restart
1. See error: Sometime the `csi-rbdplugin` container has multiple `operation with the given Volume ID... already exists` errors, but other times it does not. The error manifests as multiple `csi-rbdplugin-xx` pod restarts, and the application pods not becoming ready (or taking a long time to become ready).

# Actual results #

Multiple `csi-rbdplugin-xx` pod restarts, and the application pods not becoming ready or taking a very long time to become ready.

# Expected behavior #

1. I expect the same behavior as with dynamic provisioning: the `csi-rbdplugin-xx` pod to *not* restart.
2. I expect the occasional `operation with the given Volume ID... already exists` errors to *not* appear.
3. I expect that in case of csi driver failure (restarts), it would recover promptly and handle the pods' requests to mount the volumes.

# Logs #

If the issue is in PVC mounting please attach complete logs of below containers.

- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
  plugin pod from the node where the mount is failing.

`csi-rbdplugin` container (hundreds of similar entries):

```sh
E0509 08:11:37.920422  140916 utils.go:200] ID: 6661 Req-ID: csi-vol-5758ff59-bd85-11ed-8e4b-e282e8f41138 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID csi-vol-5758ff59-bd85-11ed-8e4b-e282e8f41138 already exists
E0509 08:11:37.627645  140916 nodeserver.go:904] ID: 6664 Req-ID: csi-vol-5758ff59-bd85-11ed-8e4b-e282e8f40671 an operation with the given Volume ID csi-vol-5758ff59-bd85-11ed-8e4b-e282e8f40671 already exists
E0509 08:11:37.920439  140916 utils.go:200] ID: 6664 Req-ID: csi-vol-5758ff59-bd85-11ed-8e4b-e282e8f40671 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID csi-vol-5758ff59-bd85-11ed-8e4b-e282e8f40671 already exists
E0509 08:11:37.627734  140916 nodeserver.go:904] ID: 6665 Req-ID: csi-vol-5758ff59-bd85-11ed-8e4b-e282e8f40346 an operation with the given Volume ID csi-vol-5758ff59-bd85-11ed-8e4b-e282e8f40346 already exists
```

`driver-registrar` container:

```sh
I0509 06:19:09.915894   15624 main.go:166] Version: v2.5.0
I0509 06:19:09.915943   15624 main.go:167] Running node-driver-registrar in mode=registration
I0509 06:19:11.122083   15624 node_register.go:53] Starting Registration Server at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0509 06:19:11.122311   15624 node_register.go:62] Registration Server started at: /registration/rook-ceph.rbd.csi.ceph.com-reg.sock
I0509 06:19:11.122468   15624 node_register.go:92] Skipping HTTP server because endpoint is set to: ""
I0509 06:19:11.813661   15624 main.go:102] Received GetInfo call: &InfoRequest{}
I0509 06:19:11.814010   15624 main.go:109] "Kubelet registration probe created" path="/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/registration"
I0509 06:19:11.855750   15624 main.go:120] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
E0509 06:27:42.654445   15624 connection.go:132] Lost connection to unix:///csi/csi.sock.
E0509 06:29:27.960779   15624 connection.go:132] Lost connection to unix:///csi/csi.sock.
E0509 06:31:16.156243   15624 connection.go:132] Lost connection to unix:///csi/csi.sock.
E0509 06:33:18.837427   15624 connection.go:132] Lost connection to unix:///csi/csi.sock.
```

# Additional context #

**Comment by Madhu-1** [comment]
>See error: Sometime the csi-rbdplugin container has multiple operation with the given Volume ID... already exists errors, but other times it does not. The error manifests as multiple csi-rbdplugin-xx pod restarts, and the application pods not becoming ready (or taking a long time to become ready).


There is no need to worry about the error related to the given VolumeID causing a restart. At the volumeID level in nodeplugin, operations are serialized for a specific volume, and this error will disappear once the operation is finished. However, we suggest keeping a close eye on the logs to determine the root cause of the csi rbdplugin restart. Could it be due to OOM or something else?

**Comment by perspectivus1** [comment]
Thanks for the tip! It was indeed OOM for the `csi-rbdplugin-xx` container. I'll increase the limits.

**Comment by perspectivus1** [comment]
I increased the memory limits, and can now create many more static `PV`s.

Nevertheless, @Madhu-1, since I don't hit OOM when attempting to provision `PV`s at the same scale, could there be a memory leak in the static `PV` flow?

**Comment by Madhu-1** [comment]
> I increased the memory limits, and can now create many more static `PV`s.
> 
> Nevertheless, @Madhu-1, since I don't hit OOM when attempting to provision `PV`s at the same scale, could there be a memory leak in the static `PV` flow?

Not sure about that we need to do profiling. Do you see memory stays in the same state or increasing after mounting all the PVC?

**Comment by Madhu-1** [comment]
We do run rbd map commands/mount commands for each PV which can also consumes memory

**Comment by perspectivus1** [comment]
I stand corrected: the memory consumption is reduced once the images are mounted, so there seems to be *no* memory leak.

Nevertheless, the memory spikes considerably higher in static vs. dynamic provisioning.
