### ISSUE TITLE
Failed to deploy RBD CSI driver

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#388]
# Describe the bug #

Failed to deploy RBD CSI drivers
# Environment details #

- Image/version of Ceph CSI driver: `quay.io/cephcsi/cephcsi:canary`
- helm chart version
- Kubernetes cluster version
- Logs:
```
Normal   Pulling    21h   kubelet, worker1   pulling image "quay.io/cephcsi/cephcsi:canary"
  Warning  Failed     21h   kubelet, worker1   Failed to pull image "quay.io/cephcsi/cephcsi:canary": rpc error: code = Unknown desc = Error: Status 403 trying to pull repository cephcsi/cephcsi: "{\"error\": \"Permission Denied\"}"
  Warning  Failed     21h   kubelet, worker1   Error: ErrImagePull
```

```
[🎩︎]mrajanna@localhost rbd $]kubectl get po
NAME                          READY   STATUS             RESTARTS   AGE
csi-rbdplugin-9fvvr           0/2     ImagePullBackOff   5          11m
csi-rbdplugin-ctjhv           1/2     ImagePullBackOff   6          11m
csi-rbdplugin-provisioner-0   2/4     ImagePullBackOff   11         11m
```

# Steps to reproduce #

Deploy RBD csi driver.

# Actual results #
deployment of RBD CSI driver is failing due to image pull error
Describe what happened
RBD containers are not coming to running state
# Expected behavior #
RBD should get deployed successfully.

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by Madhu-1** [comment]
@leseb @rootfs can you guys help me to fix it. I don't have the permission to check the image present in quay or not

**Comment by Madhu-1** [comment]
getting below error from `quay`

```
403: Unauthorized
You are not authorized to view this resource
```

**Comment by humblec** [comment]
@Madhu-1 I am looking into..

**Comment by humblec** [comment]
@Madhu-1 it should be working now. I am closing this issue. Please feel free to reopen if required.
