### ISSUE TITLE
Document using multiple subvolume groups in same cluster

### ISSUE THREAD

**Issue by jascott1** [ceph/ceph-csi#3881]
# Describe the feature you'd like to have #

Document the ability to use two or more subvolume groups from the same Ceph cluster.

# What is the value to the end user? (why is it a priority?) #  

The end user benefits from clear configuration examples about a common use case.

# How will we know we have a good solution? (acceptance criteria) #

* A document that shows how to configure a single ceph-csi installation to use multiple subvolume groups from the same Ceph cluster. 

# Additional context #

The ceph-csi-config configmap appears to tie a cluster to a subvolume group:

```
{\"cephFS\":{\"subvolumeGroup\":\"my_subvolumegroup\"},\"clusterID\":\"604d56db-2fab-45db-a9ea-c418f9a8cca8\",\"monitors\":[\"10.45.128.26:3300\",\"10.45.128.26:6789\",\"10.45.128.27:3300\",\"10.45.128.27:6789\",\"10.45.128.28:3300\",\"10.45.128.28:6789\"]}]"}
```

Can we document any workarounds if ceph-csi does not have the ability to accommodate multiple subvolume groups in the same Ceph cluster?

**Comment by Madhu-1** [comment]
The clusterID in the configmap is an arbitrary value that provides the mapping between cephcluster and storageclass, you can follow below example to use multiple subvolume from the cephcluster with different storageclasses

```json
[{
		"clusterID": "abcd",
		"monitors": [
			"10.20.30.40:6789"
		],
		"cephFS": {
			"subvolumeGroup": "abcde"
		}
	},
	{
		"clusterID": "xyz",
		"monitors": [
			"10.20.30.40:6789"
		],
		"cephFS": {
			"subvolumeGroup": "abc-xyz"
		}
	}
]
```
