### ISSUE TITLE
SIGSEGV crash in csi-rbdplugin-controller

### ISSUE THREAD

**Issue by diskis** [ceph/ceph-csi#3935]
# Describe the bug #

 csi-rbdplugin-controller hard crashes on kubernetes 1.27.1 + metrics-server with custom metrics

Kubernetes team discussion and list of other affected applications
https://github.com/kubernetes/kubernetes/issues/118361

This is a known error where a 1.26 version go client accesses a 1.27 version cluster. The 1.27 kubernetes may in some cases return malformed metrics that crashes 1.26 go client.

The 1.26.4 client has been fixed: https://github.com/kubernetes/kubernetes/pull/116666

The rook project fixed this issue already
https://github.com/rook/rook/issues/12114
https://github.com/rook/rook/pull/12161/commits/ad068d966a9e63f8e1c8724bb8106c5683ef3aef

# Environment details #

- Image/version of Ceph CSI driver : 3.8 and 3.8-canary
- Kubernetes cluster version : 1.27.1

# Steps to reproduce #

Install a 1.27.1 cluster with ceph-csi rbd, install metrics-server, install anything that uses custom metrics like nvidia-operator.

Here the csi-rbdplugin-controller will crash and be stuck in CrashLoopBackoff

# Logs #

I0626 11:55:40.118973       1 cephcsi.go:199] Driver version: v3.8-canary and Git version: d7cf3a808414177e8fe75de5c90659852a48449c
I0626 11:55:40.119059       1 cephcsi.go:248] Starting driver type: controller with name: rbd.csi.ceph.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12cbfb0]

goroutine 1 [running]:
k8s.io/client-go/discovery.convertAPIResource(...)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/aggregated_discovery.go:88
k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0xc000e07938, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/aggregated_discovery.go:69 +0x5f0
k8s.io/client-go/discovery.SplitGroupsAndResources({{{0xc000e06bb8, 0x15}, {0xc000e0ada0, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/aggregated_discovery.go:35 +0x2f8
k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0x2052a51?)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/discovery_client.go:310 +0x47c
k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0xc0003d3ea0?)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/discovery_client.go:198 +0x5c
k8s.io/client-go/discovery.ServerGroupsAndResources({0x2545d98, 0xc00072c390})
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/discovery_client.go:392 +0x59
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources.func1()
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/discovery_client.go:356 +0x25
k8s.io/client-go/discovery.withRetries(0x2, 0xc000f1f040)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/discovery_client.go:621 +0x72
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources(0x0?)
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/discovery_client.go:355 +0x3a
k8s.io/client-go/restmapper.GetAPIGroupResources({0x2545d98?, 0xc00072c390?})
        /go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/restmapper/discovery.go:148 +0x42
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper.func1()
        /go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go:94 +0x25
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).setStaticMapper(...)
        /go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go:130
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper(0xc000e0d170?, {0x0, 0x0, 0xe3e2ad33087f4201?})
        /go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go:110 +0x182
sigs.k8s.io/controller-runtime/pkg/cluster.setOptionsDefaults.func1(0x0?)
        /go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/cluster/cluster.go:217 +0x25
sigs.k8s.io/controller-runtime/pkg/cluster.New(0xc0004338c0, {0xc000f1f9e8, 0x1, 0x0?})
        /go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/cluster/cluster.go:159 +0x18d
sigs.k8s.io/controller-runtime/pkg/manager.New(_, {0x0, 0x0, 0x0, {{0x25405b8, 0xc000e1a940}, 0x0}, 0x1, {0x20561ee, 0x6}, ...})
        /go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go:359 +0xf9
github.com/ceph/ceph-csi/internal/controller.Start({{0x7ffc553a291d, 0x10}, {0x7ffc553a2940, 0xc}, {0x0, 0x0}, 0x1})
        /go/src/github.com/ceph/ceph-csi/internal/controller/controller.go:70 +0x139
main.main()
        /go/src/github.com/ceph/ceph-csi/cmd/cephcsi.go:276 +0x971
```

**Comment by Madhu-1** [comment]
@diskis Thanks for reporting, we are already using 0.27.2 version https://github.com/ceph/ceph-csi/blob/1ca6f004a53632e9573ac907ff14bdaddddf1c1c/go.mod#L195-L220 it should be available in next release ( in 1 or 2 days), can you give a try with canary image and see if it works

**Comment by diskis** [comment]
I'm using 3.8-canary with commit https://github.com/ceph/ceph-csi/commit/d7cf3a808414177e8fe75de5c90659852a48449c
which seems to be using version 0.26 still, so will wait the 1-2 days for the release which most likely fixes the issue. 

Thanks.

**Comment by Madhu-1** [comment]
If you want to try, use Canary tag which is built from devel branch https://github.com/ceph/ceph-csi#ceph-csi-container-images-and-release-compatibility

**Comment by karthik-us** [comment]
Hi @diskis, did you try this on the latest [release v3.9.0](https://github.com/ceph/ceph-csi/releases/tag/v3.9.0) or on the devel branch with tag canary as suggested by @Madhu-1? Are you still seeing this on any of these branches?
