### ISSUE TITLE
RBD Provisioner Image Repository still using staging repo

### ISSUE THREAD

**Issue by plnordquist-pnnl** [ceph/ceph-csi#3976]
# Describe the bug #

The ceph-csi-rbd helm chart is still using the staging image repository for the provisioner after switching to an actual released version of the provisioner, see https://github.com/ceph/ceph-csi/blob/devel/charts/ceph-csi-rbd/values.yaml#L219.  The change originated in https://github.com/ceph/ceph-csi/commit/c8800618 where it was switched to use a canary version of the image to gain an un-released feature of the provisioner but is has not been switched back to the registry.k8s.io url now that it's using released versions.

# Environment details #

- Helm chart versions: 
  - 3.6.2 - this version uses the canary version of the sidecar
  - 3.7.0 - this version and versions after use a released version of the sidecar
  - 3.7.1
  - 3.7.2
  - 3.8.0
  - 3.9.0

**Comment by Rakshith-R** [comment]
@plnordquist Thanks for reporting the issue.

It seems like upating the image url was switched back here https://github.com/ceph/ceph-csi/commit/776821f17fa7fe5ce5c1a9c36c9b1a2e564ca5e9#diff-83733745c9fed782b2a4ac8a94fe2d94bad85964ade73f38102dc3b04b18f5c7 

would like to send a pr to fix this ?
