### ISSUE TITLE
Bulk delete of CSI based rbd volumes through project delete leaves behind some undeleted pvs

### ISSUE THREAD

**Issue by nehaberry** [ceph/ceph-csi#399]
**Description of problem:**

Bulk delete of CSI based rbd volumes leaves behind some undeleted pvs.

Created a project with ~120 app pods, each bound with one csi-rbd volume. To initiate bulk delete, deleted the whole project. Even though the pods and PersistentVolumeClaims are deleted, ~17 PersistentVolumes still stayed undeleted and in "Released" state. The volumes still existed on the ceph backend as well.

**Snip of the error message seen in the "csi-rbdplugin-provisioner-0/csi-provisioner log:**

```
I0531 11:42:34.935223       1 controller.go:1097] delete "pvc-b14bbc93-8397-11e9-9704-0ae6b1651af2": started

I0531 11:42:36.012411       1 controller.go:192] GRPC error: rpc error: code = Internal desc = rbd pvc-b14bbc93-8397-11e9-9704-0ae6b1651af2 is still being used
E0531 11:42:36.012435       1 controller.go:1120] delete "pvc-b14bbc93-8397-11e9-9704-0ae6b1651af2": volume deletion failed: rpc error: code = Internal desc = rbd pvc-b14bbc93-8397-11e9-9704-0ae6b1651af2 is still being used

-----
-----

I0531 12:31:02.507663       1 controller.go:192] GRPC error: rpc error: code = Internal desc = rbd pvc-b14bbc93-8397-11e9-9704-0ae6b1651af2 is still being used
E0531 12:31:02.507692       1 controller.go:1120] delete "pvc-b14bbc93-8397-11e9-9704-0ae6b1651af2": volume deletion failed: rpc error: code = Internal desc = rbd pvc-b14bbc93-8397-11e9-9704-0ae6b1651af2 is still being used
W0531 12:31:02.507750       1 controller.go:726] Retrying syncing volume "pvc-b14bbc93-8397-11e9-9704-0ae6b1651af2" because failures 8 < threshold 15
E0531 12:31:02.507793       1 controller.go:741] error syncing volume "pvc-b14bbc93-8397-11e9-9704-0ae6b1651af2": rpc error: code = Internal desc = rbd pvc-b14bbc93-8397-11e9-9704-0ae6b1651af2 is still being used
I0531 12:31:02.508404       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-b14bbc93-8397-11e9-9704-0ae6b1651af2", UID:"b1b9f608-8397-11e9-96cc-062db78a205c", APIVersion:"v1", ResourceVersion:"591678", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' rpc error: code = Internal desc = rbd pvc-b14bbc93-8397-11e9-9704-0ae6b1651af2 is still being used

```

**PV list of un-deleted volumes**

```

oc get pv|grep cirros
pvc-423aeea5-8397-11e9-983e-028dfec6f770   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc001                csi-rbd1                              110m
pvc-4ccfcb4a-8397-11e9-96cc-062db78a205c   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc006                csi-rbd1                              110m
pvc-50abd71c-8397-11e9-983e-028dfec6f770   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc008                csi-rbd1                              110m
pvc-5c46b88d-8397-11e9-983e-028dfec6f770   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc015                csi-rbd1                              109m
pvc-5dbe8f50-8397-11e9-96cc-062db78a205c   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc016                csi-rbd1                              109m
pvc-6584e985-8397-11e9-983e-028dfec6f770   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc021                csi-rbd1                              109m
pvc-6a734cb8-8397-11e9-96cc-062db78a205c   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc024                csi-rbd1                              109m
pvc-6c7fac9c-8397-11e9-96cc-062db78a205c   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc025                csi-rbd1                              109m
pvc-72e7ad64-8397-11e9-96cc-062db78a205c   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc028                csi-rbd1                              109m
pvc-8fa59e88-8397-11e9-983e-028dfec6f770   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc045                csi-rbd1                              108m
pvc-946a0f61-8397-11e9-9704-0ae6b1651af2   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc048                csi-rbd1                              108m
pvc-9fbbe61e-8397-11e9-983e-028dfec6f770   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc055                csi-rbd1                              107m
pvc-a3487c70-8397-11e9-9704-0ae6b1651af2   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc057                csi-rbd1                              107m
pvc-b14bbc93-8397-11e9-9704-0ae6b1651af2   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc066                csi-rbd1                              107m
pvc-bc316634-8397-11e9-9704-0ae6b1651af2   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc073                csi-rbd1                              107m
pvc-c2c24fe6-8397-11e9-96cc-062db78a205c   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc076                csi-rbd1                              106m
pvc-df7ec39f-8397-11e9-983e-028dfec6f770   2Gi        RWO            Delete           Released   cirros/claimrbd-pvc094                csi-rbd1                              106m


```

**sh-4.2 rbd ls -p rbd**

```
pvc-423aeea5-8397-11e9-983e-028dfec6f770
pvc-4ccfcb4a-8397-11e9-96cc-062db78a205c
pvc-50abd71c-8397-11e9-983e-028dfec6f770
pvc-5c46b88d-8397-11e9-983e-028dfec6f770
pvc-5dbe8f50-8397-11e9-96cc-062db78a205c
pvc-6584e985-8397-11e9-983e-028dfec6f770
pvc-6a734cb8-8397-11e9-96cc-062db78a205c
pvc-6c7fac9c-8397-11e9-96cc-062db78a205c
pvc-72e7ad64-8397-11e9-96cc-062db78a205c
pvc-8fa59e88-8397-11e9-983e-028dfec6f770
pvc-946a0f61-8397-11e9-9704-0ae6b1651af2
pvc-9fbbe61e-8397-11e9-983e-028dfec6f770
pvc-a3487c70-8397-11e9-9704-0ae6b1651af2
pvc-b14bbc93-8397-11e9-9704-0ae6b1651af2
pvc-bc316634-8397-11e9-9704-0ae6b1651af2
pvc-c2c24fe6-8397-11e9-96cc-062db78a205c
pvc-df7ec39f-8397-11e9-983e-028dfec6f770
```

**Version-Release number of selected component (if applicable):**

```
Ceph versions from toolbox pod
-----------------------------------

sh-4.2 ceph versions
{
    "mon": {
        "ceph version 14.2.0 (3a54b2b6d167d4a2a19e003a705696d4fe619afc) nautilus (stable)": 3
    },
    "mgr": {
        "ceph version 14.2.0 (3a54b2b6d167d4a2a19e003a705696d4fe619afc) nautilus (stable)": 1
    },
    "osd": {
        "ceph version 14.2.0 (3a54b2b6d167d4a2a19e003a705696d4fe619afc) nautilus (stable)": 6
    },
    "mds": {},
    "overall": {
        "ceph version 14.2.0 (3a54b2b6d167d4a2a19e003a705696d4fe619afc) nautilus (stable)": 10
    }
}


Ceph pod image
----------------
[nberry@localhost logs]$ oc describe pod rook-ceph-mon-a-69466447ff-kc272|grep -i image
    Image:         ceph/ceph:v14.2.0-20190410
    Image ID:      docker.io/ceph/ceph@sha256:212804b78633f61997440aa37fec87e144081ed60a5ee918c35070548bfc8c22
      CONTAINER_IMAGE:                ceph/ceph:v14.2.0-20190410
    Image:         ceph/ceph:v14.2.0-20190410
    Image ID:      docker.io/ceph/ceph@sha256:212804b78633f61997440aa37fec87e144081ed60a5ee918c35070548bfc8c22
      CONTAINER_IMAGE:                ceph/ceph:v14.2.0-20190410


CSI pod image 
----------------

[nberry@localhost logs]$ oc describe pod csi-rbdplugin-8cphn|grep -i image
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.0.2
    Image ID:      quay.io/k8scsi/csi-node-driver-registrar@sha256:ffecfbe6ae9f446e5102cbf2c73041d63ccf44bcfd72e2f2a62174a3a185eb69
    Image:         quay.io/cephcsi/rbdplugin:v1.0.0
    Image ID:      quay.io/cephcsi/rbdplugin@sha256:e04fa3d1d210ef07f3287d58362067b17b313a0b5e46ce0879b3142df484a12b
[nberry@localhost logs]$ oc describe pod rook-ceph-tools-76c7d559b6-d92mr|grep -i image
    Image:         rook/ceph:master
    Image ID:      docker.io/rook/ceph@sha256:11aca02d842184bfad5a405ee0c0446f9d2a3b5b4418b4ede0a3211f20d05aa4


Rook version ( from github, master branch) 
---------------
[nberry@localhost logs]$ oc describe pod rook-ceph-tools-76c7d559b6-d92mr|grep -i image
    Image:         rook/ceph:master
    Image ID:      docker.io/rook/ceph@sha256:11aca02d842184bfad5a405ee0c0446f9d2a3b5b4418b4ede0a3211f20d05aa4


oc version
------------

$ export KUBECONFIG=/home/nberry/aws-install/may31/auth/kubeconfig 
(ocs-ci) [nberry@localhost ocs-ci]$ oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0-201905091432+4910781-dirty", GitCommit:"4910781", GitTreeState:"dirty", BuildDate:"2019-05-09T19:19:42Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+f2cc675", GitCommit:"f2cc675", GitTreeState:"clean", BuildDate:"2019-05-18T00:35:43Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}


$ oc get clusterversion
NAME      VERSION      AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.1.0-rc.5   True        False         138m    Cluster version is 4.1.0-rc.5

```

**How reproducible:**
---------------------
Attempted once. The volumes were not yet deleted even after ~50 mins (last checked). 

**Steps to Reproduce:**
------------------------
1. Created a CSI based rook-ceph setup using ocs-ci
2. Create secret, storageclass using both "admin" and "kubernetes" user. Yamls are attached for reference in next comment.
3. Create a new-project (here cirros)
   oc new-project cirros
Now using project "cirros" on server "https://api.vavuthu-ocs.qe.rh-ocs.com:6443".

4. Run a script to create pod + pvc in a new-project. Copied the script for volume & pod creation in next comment.

for i in {001..100}; do sh cirros-create-with-pvc-with-io.sh rbd-pvc$i 2; done

5. Created 20 more volumes. 

6. Initiated PVC delete by deleting the whole project

  oc delete project cirros

7. This initiated pod deletion followed by PVC/PV deletion. 

8. Checked the PV list and ceph backend. Atleast 17 PVs were not yet deleted and there were delete failures in CSI logs

Some data for analysis:
----------------------------

1. First delete  request sent at (from logs) ~ I0531 11:42:10.62865
2. Out of 120 volumes, only 17 were left behind. 

**Actual results:**

Some PVs failed to get deleted from OC side and the ceph backend.
They still listed under OC as "Released" and in ceph backend under: (pool name = rbd)

rd ls -p rbd 

**Expected results:**

All the POds and volumes need to get removed once the hosting project(namespace) is deleted permanently.

**Comment by nehaberry** [comment]
Logs attached

[issue-399.zip](https://github.com/ceph/ceph-csi/files/3246223/issue-399.zip)

**Comment by Madhu-1** [comment]
@nehaberry current RBD version used  is `quay.io/cephcsi/rbdplugin:v1.0.0` please use `quay.io/cephcsi/cephcsi:canary`

**Comment by nehaberry** [comment]
@Madhu-1 we are using the rook image from upstream master.  Do we need to change the image names for these params in **operator-openshift-with-csi.yaml**


       - name: ROOK_CSI_CEPHFS_IMAGE
        - name: ROOK_CSI_RBD_IMAGE
        - name: ROOK_CSI_REGISTRAR_IMAGE
        - name: ROOK_CSI_PROVISIONER_IMAGE
        - name: ROOK_CSI_SNAPSHOTTER_IMAGE
        - name: ROOK_CSI_ATTACHER_IMAGE

Please let me know if I have missed anything.


**Correct ... Current images seem to be this:**

  - name: ROOK_CSI_CEPHFS_IMAGE
          value: "quay.io/cephcsi/cephfsplugin:v1.0.0"
        - name: ROOK_CSI_ENABLE_RBD
          value: "true"
        - name: ROOK_CSI_RBD_IMAGE
          value: "quay.io/cephcsi/rbdplugin:v1.0.0"
        - name: ROOK_CSI_REGISTRAR_IMAGE
          value: "quay.io/k8scsi/csi-node-driver-registrar:v1.0.2"
        - name: ROOK_CSI_PROVISIONER_IMAGE
          value: "quay.io/k8scsi/csi-provisioner:v1.0.1"
        - name: ROOK_CSI_SNAPSHOTTER_IMAGE
          value: "quay.io/k8scsi/csi-snapshotter:v1.0.1"
        - name: ROOK_CSI_ATTACHER_IMAGE
          value: "quay.io/k8scsi/csi-attacher:v1.0.1"

**Comment by Madhu-1** [comment]
using `canary` image needs more changes in rook. we are going to update rook once we release  ceph-csi `v1.1.0`
CC @humblec

**Comment by hnallurv** [comment]
@Madhu-1 when will ceph-csi v1.1.0 be available?

**Comment by Madhu-1** [comment]
@hnallurv https://github.com/ceph/ceph-csi/issues/393

**Comment by humblec** [comment]
@hnallurv its actually https://github.com/ceph/ceph-csi/issues/353 and as per our schedule its going to land on Jun 7th. .  https://github.com/ceph/ceph-csi/issues/393 is for next minor release.

**Comment by nehaberry** [comment]
@Madhu-1 so do you suggest that temporarily changing the image version to **quay.io/cephcsi/cephcsi:canary** for all the below variables be helpful to get past this bug ? I understand that it is WIP for the canary build as well 

   - name: ROOK_CSI_CEPHFS_IMAGE
    - name: ROOK_CSI_RBD_IMAGE
    - name: ROOK_CSI_REGISTRAR_IMAGE
    - name: ROOK_CSI_PROVISIONER_IMAGE
    - name: ROOK_CSI_SNAPSHOTTER_IMAGE
    - name: ROOK_CSI_ATTACHER_IMAGE

**Comment by Madhu-1** [comment]
> @Madhu-1 so do you suggest that temporarily changing the image version to **quay.io/cephcsi/cephcsi:canary** for all the below variables be helpful to get past this bug ? I understand that it is WIP for the canary build as well
> 
> * name: ROOK_CSI_CEPHFS_IMAGE
>   - name: ROOK_CSI_RBD_IMAGE
>   - name: ROOK_CSI_REGISTRAR_IMAGE
>   - name: ROOK_CSI_PROVISIONER_IMAGE
>   - name: ROOK_CSI_SNAPSHOTTER_IMAGE
>   - name: ROOK_CSI_ATTACHER_IMAGE

@nehaberry need to do some change in rook code itself changing template won't fix the issue.

**Comment by nehaberry** [comment]
@Madhu-1 ok. Please let us know once the code changes are made. Thanks :)

**Comment by Madhu-1** [comment]
@nehaberry are you still seeing this issue?

**Comment by nehaberry** [comment]
> @nehaberry are you still seeing this issue?

Hi @Madhu-1 yeah last when I tested lst week, some PVs were still being left behind. The corresponding bugzilla was updated.  

https://bugzilla.redhat.com/show_bug.cgi?id=1716276

**Comment by Madhu-1** [comment]
assigning to @ShyamsundarR as he is looking into it.

**Comment by ShyamsundarR** [comment]
https://github.com/ceph/ceph-csi/pull/510 should fix this issue.
