### ISSUE TITLE
Unable to build statically linked `ceph-csi` binary

### ISSUE THREAD

**Issue by roshanirathi** [ceph/ceph-csi#4020]
I am trying to do static build of ceph-csi binary. I am seeing following errors:
```
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrados
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lrbd
/bin/ld: cannot find -lpthread
/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

make: *** [Makefile:160: cephcsi] Error 2
make: *** [Makefile:196: containerized-build] Error 2
[ec2-user@ip-10-0-1-239 ceph-csi]$ 
```

I have added these flags in the Makefile:
`LDFLAGS ?= -linkmode=external -extldflags=-static`

I am running this command - `make containerized-build`

Dynamic build succeeds but I need help with static build. Please help

**Comment by nixpanic** [comment]
Because Ceph-CSI uses go-ceph, it links to several Ceph libraries. If you want to build a static executable, you will need to do that on a system that has the libraries for Ceph in a format that can be statically linked. I do not know if that is possible at all, it definitely is not common practice.

**Comment by roshanirathi** [comment]
I found this reply on a similar issue from 5 years ago - https://github.com/ceph/go-ceph/issues/23#issuecomment-403023115

Can someone please share the changes relevant to the code now? for example, I cant find which Makefile has these commands - 
```
make rados-static 
make ceph-common-static
```

**Comment by nixpanic** [comment]
I expect these to be part of the Ceph project. go-ceph needs the Ceph libraries that are statically compiled, in order to be able to statically compiled itself. You may want to ask on the Ceph developers list about all requirements.

**Comment by nixpanic** [comment]
See also #2946
