### ISSUE TITLE
csi-rbdplugin crashes when decoding volume ID(CSI identifier) failed

### ISSUE THREAD

**Issue by crazytaxii** [ceph/ceph-csi#4098]
# Describe the bug #

csi-rbdplugin will crash when decoding volume ID failed due to nil pointer

# Environment details #

- Image/version of Ceph CSI driver : v3.6.2
- Helm chart version :
- Kernel version : 4.18.0
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : krbd
- Kubernetes cluster version : v1.27.2
- Ceph cluster version : 16.2.13

problematic code:

```go
	rbdVol, err := GenVolFromVolID(ctx, volumeID, cr, req.GetSecrets())
	defer rbdVol.Destroy()
	if err != nil {
		return cs.checkErrAndUndoReserve(ctx, err, volumeID, rbdVol, cr)
	}
```

> `defer` should be placed under error processing

```[tasklist]
### Tasks
```

**Comment by Madhu-1** [comment]
@crazytaxii Do you have any test cases or the steps to produce this panic?

**Comment by crazytaxii** [comment]
the [code](https://github.com/ceph/ceph-csi/blob/v3.9.0/internal/rbd/controllerserver.go#L924-L928) itself is incorrect:

```go
	rbdVol, err := GenVolFromVolID(ctx, volumeID, cr, req.GetSecrets())
	defer rbdVol.Destroy()
	if err != nil {
		return cs.checkErrAndUndoReserve(ctx, err, volumeID, rbdVol, cr)
	}
```

it should be:

```go
	rbdVol, err := GenVolFromVolID(ctx, volumeID, cr, req.GetSecrets())
	if err != nil {
		return cs.checkErrAndUndoReserve(ctx, err, volumeID, rbdVol, cr)
	}
	defer rbdVol.Destroy()
```
