### ISSUE TITLE
Missing CRDs of the CSI Snapshotter in the "deploy" Ressources

### ISSUE THREAD

**Issue by tiwalter** [ceph/ceph-csi#4100]
# Describe the bug #

The `csi-snapshotter` container got the following errors, after deploying the [deploy](https://github.com/ceph/ceph-csi/tree/v3.8.1/deploy) ressources of `fs` and `rbd`:

```
csi-snapshotter E0824 10:01:40.186432       1 reflector.go:140] github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/factory.go:117: Failed to watch *v1.VolumeSnapshotContent: failed to list *v1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
csi-snapshotter W0824 10:02:03.644213       1 reflector.go:424] github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/factory.go:117: failed to list *v1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
csi-snapshotter E0824 10:02:03.644354       1 reflector.go:140] github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/factory.go:117: Failed to watch *v1.VolumeSnapshotClass: failed to list *v1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
csi-snapshotter W0824 10:02:37.337592       1 reflector.go:424] github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/factory.go:117: failed to list *v1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
```

Root cause: Missing CRDs of the CSI Snapshotter. They can be found here: https://github.com/kubernetes-csi/external-snapshotter/tree/v6.1.0/client/config/crd.

You have to use the CRDs that fit to the deployed `csi-snapshotter` version that is deployed.
E.g. vor ceph-csi version `v3.8.1`, the csi-snapshotter version `v6.1.0` is used.

Everything will be resolved, if you apply the CRDs.

# Environment details #

- Image/version of Ceph CSI driver : v3.8.1
- Kubernetes cluster version : v1.25.12
- Ceph cluster version : v16.2.7 (Pacific)

# Steps to reproduce #

1. Apply the resources in  the [deploy/cephfs/kubernetes](https://github.com/ceph/ceph-csi/tree/v3.8.1/deploy/cephfs/kubernetes) directory (rbd also possible)
2. Check the logs of the `csi-snapshotter`
3. See errors

# Expected behavior #

The Kuberntes resources in the [deploy](https://github.com/ceph/ceph-csi/tree/v3.8.1/deploy) directory must contain the needed CRDs for the `csi-snapshotter`.

**Comment by nixpanic** [comment]
Maybe the documentation needs to be improved , and https://github.com/ceph/ceph-csi/blob/devel/docs/snap-clone.md needs to be linked in some spots that make it easier to find?

**Comment by Rakshith-R** [comment]
>The Kuberntes resources in the [deploy](https://github.com/ceph/ceph-csi/tree/v3.8.1/deploy) directory must contain the needed CRDs for the csi-snapshotter.

The snapshot CRDs are an external dependency, mentioning it in deployment steps alone should be fine.
(It is actually expected to be provided by default in most latest kubernetes distros or made available by cluster admins)

> Maybe the documentation needs to be improved , and https://github.com/ceph/ceph-csi/blob/devel/docs/snap-clone.md needs to be linked in some spots that make it easier to find?

Yes, we need to link that document in steps mentioned in 

https://github.com/ceph/ceph-csi/blob/devel/docs/deploy-cephfs.md#deployment-with-kubernetes 

and 

https://github.com/ceph/ceph-csi/blob/devel/docs/deploy-rbd.md#deployment-with-kubernetes 

@iPraveenParihar Can you please make the required changes ?
