### ISSUE TITLE
Remove deprecated grpc metrics code

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#4122]
We already deprecated the grpc metrics in cephcsi, I think now we can remove it. This will also solve the issue of port conflict when cephcsi is used with hostnetworking enabled.

_Originally posted by @Madhu-1 in https://github.com/ceph/ceph-csi/issues/881#issuecomment-790328188_

**Comment by humblec** [comment]
This  PR https://github.com/ceph/ceph-csi/pull/3543  was trying to address, however got auto closed. It can be revisited if needed.
