### ISSUE TITLE
doc: remove cephfs storageclass mountOption related changes in Upgrade doc

### ISSUE THREAD

**Issue by Rakshith-R** [ceph/ceph-csi#4126]
# Describe the bug #

The following changes need to be made in upgrade co during preparation for 3.10 release: 

- [ ] Remove first line in https://github.com/ceph/ceph-csi/blob/devel/docs/ceph-csi-upgrade.md#upgrading-cephfs
- [ ] and entire section https://github.com/ceph/ceph-csi/blob/devel/docs/ceph-csi-upgrade.md#24-modifying-mountoptions-in-storageclass-and-persistentvolumes

**Comment by adithyaakrishna** [comment]
Would love to take this :)
