### ISSUE TITLE
cephfs: add capability to automatically enable read affinity

### ISSUE THREAD

**Issue by Rakshith-R** [ceph/ceph-csi#4149]
# Describe the feature you'd like to have #

CephFS kernel mounter supports read_from_replica and crush location options similar to rbd mount options.
We can add support for cephfs read affinity similar to rbd read affinity added in this pr https://github.com/ceph/ceph-csi/pull/3639

refer:
- https://tracker.ceph.com/issues/62837
- https://github.com/ceph/ceph-csi/pull/3639

**Comment by Rakshith-R** [comment]
hey @iPraveenParihar  ,
This is part of 3.10 milestone.
Can you prioritize this issue to get it done within this week or early next week ?

Thanks,

**Comment by iPraveenParihar** [comment]
> hey @iPraveenParihar , This is part of 3.10 milestone. Can you prioritize this issue to get it done within this week or early next week ?
> 
> Thanks,

Yes, I have raised a Draft PR already.
Doing local testing.
