### ISSUE TITLE
remove support for older kubernetes/ceph releases

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#4168]
Update the Readme and code where we have added support for older ceph or kubernetes versions. [Octopus](https://docs.ceph.com/en/latest/releases/octopus) is already EOL we can remove it from Readme support. also check code for cephfs resize/subvolume metadata related operations as well.

**Comment by Rakshith-R** [comment]
hey @karthik-us  ,
This is part of 3.10 milestone.
Can you prioritize this issue to get it done within this week or early next week ?

Thanks,

**Comment by karthik-us** [comment]
Sure @Rakshith-R.

**Comment by karthik-us** [comment]
@Madhu-1 can you please elaborate on this one please?
> also check code for cephfs resize/subvolume metadata related operations as well.

If you can point me to the changesets which requires changes in these parts of the codes, that would be great.

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/blob/6b3665b80c95ea84fdf4e310b18566cb65661964/internal/cephfs/core/metadata.go#L35-L52 https://github.com/ceph/ceph-csi/blob/6b3665b80c95ea84fdf4e310b18566cb65661964/internal/cephfs/core/volume.go#L278-L303
