### ISSUE TITLE
document the differences between the three cephcsi images

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-csi#421]
_What new functionality do you want?_

I would like a paragraph of documentation that describes the differences in [the three images we publish](https://quay.io/organization/cephcsi):

1. `cephcsi/cephfsplugin`
2. `cephcsi/rbdplugin`
3. `cephcsi/cephcsi`

The differences between these three are not clear to me. I suspect `cephfsplugin` and `rbdplugin` are going to go away at some point, but this is just a wild guess. If they are going away, why are they still around now? When should users expect them to disappear?

_How would the end user gain value from having this feature?_

Users have a clear understanding of what the three images are, and why consume one or the other.

This is also important to know how we want to package and ship these downstream in Red Hat's OpenShift Container Storage 4 product.

**Comment by humblec** [comment]
> _What new functionality do you want?_
> 
> I would like a paragraph of documentation that describes the differences in [the three images we publish](https://quay.io/organization/cephcsi):
> 
>     1. `cephcsi/cephfsplugin`
> 
>     2. `cephcsi/rbdplugin`
> 
>     3. `cephcsi/cephcsi`

The support matrix will be updated soon after the v1.1.0 release with the docker images or version and that should avoid this confusion.

> 
> 
> The differences between these three are not clear to me. I suspect `cephfsplugin` and `rbdplugin` are going to go away at some point, but this is just a wild guess. If they are going away, why are they still around now? When should users expect them to disappear?

We do have to maintain those for earlier versions of CSI spec. Say for example , v1.0 and 0.3. But eventually it will go out or will vanish. From csi v1.1.0 it will be just one iimage which is "cephcsi"
 
> 
> _How would the end user gain value from having this feature?_
> 
> Users have a clear understanding of what the three images are, and why consume one or the other.
> 
> This is also important to know how we want to package and ship these downstream in Red Hat's OpenShift Container Storage 4 product.

Downstream should be just one image which is "cephcsi" and it will be consumed by Rook.

**Comment by ktdreyer** [comment]
I was discussing the ceph-csi project with someone, and the question of "what is the canary image" came up. It would be great to document the technical explanation of the "canary" tag for the container, because I don't think that's common terminology like "master" or "latest". In fact, maybe we should rename "canary" to "master".

**Comment by Madhu-1** [comment]
@humblec any update on this one, moved to release-1.1.1
