### ISSUE TITLE
When building an image, an error is reported. Does the host have to enable selinux?

### ISSUE THREAD

**Issue by lijhnihaoa** [ceph/ceph-csi#4217]
# Describe the bug #

Running transaction
  Preparing        :                                                        1/1
  Running scriptlet: python3-ceph-common-2:17.2.7-0.el8.x86_64              1/1
  Upgrading        : python3-ceph-common-2:17.2.7-0.el8.x86_64            1/142
  Upgrading        : python3-ceph-argparse-2:17.2.7-0.el8.x86_64          2/142
  Running scriptlet: selinux-policy-targeted-3.14.3-130.el8.noarch        3/142
  Installing       : selinux-policy-targeted-3.14.3-130.el8.noarch        3/142
  Running scriptlet: selinux-policy-targeted-3.14.3-130.el8.noarch        3/142
/var/tmp/rpm-tmp.7jCvWl: line 2: /etc/selinux/config: No such file or directory
warning: %post(selinux-policy-targeted-3.14.3-130.el8.noarch) scriptlet failed, exit status 1

Error in POSTIN scriptlet in rpm package selinux-policy-targeted
  Running scriptlet: container-selinux-2:2.221.0-1.module_el8+653+fee     4/142
/var/tmp/rpm-tmp.Pk3td8: line 2: /etc/selinux/config: No such file or directory
error: %prein(container-selinux-2:2.221.0-1.module_el8+653+feef7bfe.noarch) scriptlet failed, exit status 1

Error in PREIN scriptlet in rpm package container-selinux
  Upgrading        : glibc-common-2.28-237.el8.x86_64                     5/142
error: container-selinux-2:2.221.0-1.module_el8+653+feef7bfe.noarch: install failed

  Upgrading        : glibc-gconv-extra-2.28-237.el8.x86_64                6/142
....

  Installing       : chrony-4.2-1.el8.x86_64                             52/142
  Running scriptlet: chrony-4.2-1.el8.x86_64                             52/142
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

  Upgrading        : ceph-base-2:17.2.7-0.el8.x86_64                     53/142
  Running scriptlet: ceph-base-2:17.2.7-0.el8.x86_64                     53/142
  Upgrading        : ceph-selinux-2:17.2.7-0.el8.x86_64                  54/142
  Running scriptlet: ceph-selinux-2:17.2.7-0.el8.x86_64                  54/142
/var/tmp/rpm-tmp.cYVLLa: line 2: /etc/selinux/config: No such file or directory
warning: %post(ceph-selinux-2:17.2.7-0.el8.x86_64) scriptlet failed, exit status 1

Error in POSTIN scriptlet in rpm package ceph-selinux
.......

Failed:
  container-selinux-2:2.221.0-1.module_el8+653+feef7bfe.noarch

The command '/bin/sh -c dnf -y update        && dnf clean all        && rm -rf /var/cache/yum' returned a non-zero code: 1
make: *** [Makefile:235: image-cephcsi] Error 1

# Environment details #
CentOS Stream release 8 

- Image/version of Ceph CSI driver :3.9.0
- Helm chart version :
- Kernel version :5.11.6
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :rbd
- Kubernetes cluster version :1.25.0
- Ceph cluster version :16.2.13

# Steps to reproduce #
 make image-cephcsi

**Comment by nixpanic** [comment]
I just tried to reproduce this, but `make image-cephcsi` worked for me.

Can you remove any container images that are used in the process, mainly `quay.io/ceph/ceph:v18`? It is possible that there was an intermediate Ceph base container image that was not fully functional.

**Comment by lijhnihaoa** [comment]
`quay.io/ceph/ceph:v17` There has been。My solution is to enter the container during execution and create the file and path `/etc/selinux/config` before downloading and installing.Content comes from the host.
