### ISSUE TITLE
clone PVC with deep-flatten

### ISSUE THREAD

**Issue by qkfrksvl** [ceph/ceph-csi#4240]
When creating PVC from source pvc, the default behavior is that creating new PVC from source PVC snapshot. 
so  it's dependent with parent snapshot.
how can we enable flatten as a default when using cloning PVC?

**Comment by Madhu-1** [comment]
@qkfrksvl we dont have any flag to do it, you can set these values to `1` and i think it will flatten on creation https://github.com/ceph/ceph-csi/blob/a4e0c696a9f201ca7ed1459752d2d9c550d3df09/cmd/cephcsi.go#L119-L138

**Comment by qkfrksvl** [comment]
Thanks for answer, I tried to set those both value at 1 but still has parent dependent :(
