### ISSUE TITLE
Support the creation of multiple StorageClasses in values.yaml file

### ISSUE THREAD

**Issue by ghost** [ceph/ceph-csi#4299]
# Describe the feature you'd like to have #

It seems that currently you can only create one StorageClass in the values.yaml file. To avoid having to create a second one (or more) outside of the values.yaml file, it would be nice to be able to define more than one SGs in it.

# What is the value to the end user? (why is it a priority?) #

No priority, but a nice to have. More config can be place into one single file instead of having one or more separate files for other storageclasses.

# How will we know we have a good solution? (acceptance criteria) #

Be able to create 1+n storage classes via the values.yaml file

# Additional context #

- None

**Comment by simon-wessel** [comment]
We could use this feature as well. The bot seems to be a bit hasty with closing issues 🙂
