### ISSUE TITLE
Base image upgrade

### ISSUE THREAD

**Issue by kfox1111** [ceph/ceph-csi#4303]
# Describe the feature you'd like to have #

This is somewhere between a bug and a feature....

CentOS Stream 8 is going to stop building May 31 2024 (https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/).... Which is coming up rather fast. It would be nice before hand to have some releases of the driver based on CentOS Stream 9 before that time.

# What is the value to the end user? (why is it a priority?) #
Supported OS under the driver. Sooner rather then later allows an easier upgrade path for the user. More likely it is done before the os goes unsupported.

**Comment by nixpanic** [comment]
Ceph-CSI uses the Ceph base images. ceph/ceph-container#2038 is a start for a PR that adds support for CentOS Stream 9. There has been little progress unfortunately. Please follow-up or report a new issue in the [Ceph Container](https://github.com/ceph/ceph-container) project to remind the maintainers there.

**Comment by kfox1111** [comment]
probably should be reopened
