### ISSUE TITLE
edit service, add host

### ISSUE THREAD

**Issue by AndrewOga** [ceph/ceph-csi#4305]
How can I display more than 10 hosts when adding a host to the service?

![image](https://github.com/ceph/ceph-csi/assets/150757688/ba7e1304-67b7-48ef-8e6b-4f9f87c36899)

I have 19 servers, but I see only 10 and if I add a server
ceph orch daemon add mgr cph-obs6-lp2:10.18.102.2
ceph orch daemon add mon cph-obs6-lp2:10.18.102.2
they are launched, but they are not visible through ceph orch ls

![image](https://github.com/ceph/ceph-csi/assets/150757688/923f97f0-4959-4767-83c7-2b64e451ed85)

and after a while they disappear

If I add a server from the drop-down list, then everything works

**Comment by nixpanic** [comment]
Sorry, you really need to ask about this in the [main ceph](https://github.com/ceph/ceph) project.

**Comment by Rakshith-R** [comment]
> Sorry, you really need to ask about this in the [main ceph](https://github.com/ceph/ceph) project.

Closing this issue as it not related to cephcsi
