### ISSUE TITLE
rbd: add support for adjusting the number of RBD mirror image watchers

### ISSUE THREAD

**Issue by togoschi** [ceph/ceph-csi#4312]
Since ceph-csi release v3.3.1 the workflow of RBD volume atttachment considers 2 watchers to check on the image when mirroring primary is true (https://github.com/ceph/ceph-csi/pull/1993).

If you operate your ceph cluster environment with more than one rbd-mirror daemon (e.g. for high availibility and/or the cluster is streched over more than one datacenter) you maybe want to adjust the number of image watchers to check on the image.

It's required to run at least 2 rbd-mirror daemons if you want to ensure non-disruptive RBD mirroring. This is not a problem for the "in use" logic of mirrored images because only 1 rbd-mirror client watches the image usually.
But we observed volume attachment issues with 2 rbd-mirror clients when a mirror daemon leader becomes temporarily unresponsive (for example due to heavy load in the peering cluster).
That's not an serious issue for the rbd mirroring because of redundancy but meanwhile for the volume attachment of re-scheduled stateful pods.

In addition in some cases you even want to run more than 2 rbd-mirror daemons to balance the leaders over multiple RBD pools. This setup is not possible with the current implementation because you have 2 watchers on every image with 3 daemons for example (under normal operation).

Current implementation tolerates only one watcher if mirroring primary is true (https://github.com/ceph/ceph-csi/blob/v3.10.0/internal/rbd/rbd_util.go#L553-L559). I think it would be very helpful to make it possible adjusting the number of rbd-mirror watchers in more complex ceph environments.

**Comment by simon-wessel** [comment]
Support for this would be great. The hardcoded value does not seem to be a clean solution.

**Comment by Madhu-1** [comment]
@simon-wessel @togoschi sure will make it configurable

**Comment by togoschi** [comment]
@Madhu-1 thx for take care of it. A viable approach could be include the ability to configure an ipaddress array of all RBD mirror dameons

**Comment by Madhu-1** [comment]
> @Madhu-1 thx for take care of it. A viable approach could be include the ability to configure an ipaddress array of all RBD mirror dameons

@togoschi i was thinking of adding a new key like `mirrorDaemonCount` (something like that) where the user can specify the count of daemons running https://github.com/ceph/ceph-csi/blob/200fbdbf28591c404a85888d8bfc9561fa23dbb8/deploy/csi-config-map-sample.yaml#L66. am not yet sure including `ipaddresses` will have any benefit as in case of container world the `ip` always changes dynamically, feel free to send a patch with suggestion  As the community is always a priority :)

**Comment by togoschi** [comment]
@Madhu-1 of course you're completely right, setting the number of mirror daemons is the better approach

**Comment by simon-wessel** [comment]
@Madhu-1 Is this still on the roadmap?

**Comment by Madhu-1** [comment]
> @Madhu-1 Is this still on the roadmap?

@simon-wessel will try to fix it in coming week

**Comment by simon-wessel** [comment]
Looking forward to the fix 🙂

**Comment by Madhu-1** [comment]
@simon-wessel Sorry, I wasn't able to work on it earlier. I have created a PR to make it configurable.
