### ISSUE TITLE
Creating a pvc is sometimes successful and sometimes not after integrating k8s1.22.10 in CentOS7.9.2009-aarch64 with ceph14.2.22(nautilus (stable))

### ISSUE THREAD

**Issue by jiangsanyin** [ceph/ceph-csi#4347]
# Describe the bug #
I deployed k8s1.22.10 with kubekey3.0.7 in three VMs which running the Centos7.9.2009-aarch64 operating system, all nodes are normal and all componnents are healthy
![image](https://github.com/ceph/ceph-csi/assets/15863985/5932d393-19df-4a29-aeec-dc6e049b1008)
Then I integrated ceph14.2.22 into this k8s1.22.10 cluster by reference to "https://docs.ceph.com/en/octopus/rbd/rbd-kubernetes/"(I cannot find document based on Ceph-Nautilus) and some other documents from internet.
All seems ok by now. But pvc created by k8s1.22.10 cluster is hanging most of time, and sometimes pvc will be created successfully.
![image](https://github.com/ceph/ceph-csi/assets/15863985/ba402dac-c0d7-45c1-a908-c1b54e8f9b46)
the yamls to create rbd-pvc02 and rbd-pvc03 are nearly identical.
![image](https://github.com/ceph/ceph-csi/assets/15863985/010a4000-c16f-4a23-bd78-9708a72b3444)

# Environment details #

- Image/version of Ceph CSI driver :v2.9.1
- Helm chart version :~
- Kernel version :4.18.0-193.28.1.el7.aarch64
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :krbd
- Kubernetes cluster version :v1.22.10
- Ceph cluster version :14.2.22, nautilus (stable)

# Steps to reproduce #
(1)deploying k8s1.22.10 with kubekey3.0.7 in three VMs which running the Centos7.9.2009-aarch64 operating system and ensuring ks8 cluster is healthy
(2)
[root@k8s02-01 ~]# mkdir -p /opt/installPkgs/install-k8s1.22/sc-rbd-practice && cd /opt/installPkgs/install-k8s1.22/sc-rbd-practice
[root@k8s02-01 sc-rbd-practice]# git clone https://github.com/ceph/ceph-csi.git
[root@k8s02-01 sc-rbd-practice]# cd ./ceph-csi/deploy/rbd/kubernetes/
[root@k8s02-01 kubernetes]# vi csi-config-map.yaml
#I am sure that clusterID and monitors is right in csi-config-map.yaml beblowed
[root@k8s02-01 kubernetes]# cat csi-config-map.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "ceph-csi-config"
  namespace: "kube-system"
data:
  config.json: |-
    [
      {
        "clusterID": "c393b28b-3f0f-4668-9e08-aef172036008",
        "monitors": [
          "172.24.1.100:6789",
          "172.24.1.101:6789",
          "172.24.1.102:6789"
        ]
      }
    ]
[root@k8s02-01 kubernetes]# touch ceph-config-map.yaml
[root@k8s02-01 kubernetes]# cat ceph-config-map.yaml
---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    {}
metadata:
  name: ceph-csi-encryption-kms-config
  namespace: "kube-system"
---
apiVersion: v1
kind: ConfigMap
data:
  ceph.conf: |
    [global]
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx
  keyring: |
metadata:
  name: ceph-config
  namespace: "kube-system"

###csidriver.yaml is not been changed
[root@k8s02-01 kubernetes]# sed -i "s/namespace: default/namespace: kube-system/g" `grep "namespace: default" -rl csi-provisioner-rbac.yaml`
[root@k8s02-01 kubernetes]# sed -i "s/namespace: default/namespace: kube-system/g" `grep "namespace: default" -rl csi-nodeplugin-rbac.yaml`
[root@k8s02-01 kubernetes]# sed -i "s/namespace: default/namespace: kube-system/g" `grep "namespace: default" -rl csi-rbdplugin-provisioner.yaml`

#csi-provisioner:v3.3.0-arm64
[root@k8s02-01 kubernetes]# sed -i "s#image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.2#image: docker.io/dyrnq/csi-provisioner@sha256:98ffd09c0784203d200e0f8c241501de31c8df79644caac7eed61bd6391e5d49#g" `grep "image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.2" -rl csi-rbdplugin-provisioner.yaml`
#csi-snapshotter:v6.1.0-arm64
[root@k8s02-01 kubernetes]# sed -i "s#image: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.2#image: docker.io/dyrnq/csi-snapshotter@sha256:bd6b8417b2a83e66ab1d4c1193bb2774f027745bdebbd9e0c1a6518afdecc39a#g" `grep "image: egistry.k8s.io/sig-storage/csi-snapshotter:v6.3.2" -rl csi-rbdplugin-provisioner.yaml`
#csi-attacher:v4.0.0-arm64
[root@k8s02-01 kubernetes]# sed -i "s#image: registry.k8s.io/sig-storage/csi-attacher:v4.4.2#image: docker.io/dyrnq/csi-provisioner@sha256:98ffd09c0784203d200e0f8c241501de31c8df79644caac7eed61bd6391e5d49#g" `grep "image: registry.k8s.io/sig-storage/csi-attacher:v4.4.2" -rl csi-rbdplugin-provisioner.yaml`
#csi-resizer:v1.6.0-arm64
[root@k8s02-01 kubernetes]# sed -i "s#image: registry.k8s.io/sig-storage/csi-resizer:v1.9.2#image: docker.io/dyrnq/csi-resizer@sha256:82c1945463342884c05a5b2bc31319712ce75b154c279c2a10765f61e0f688af#g" `grep "image: registry.k8s.io/sig-storage/csi-resizer:v1.9.2" -rl csi-rbdplugin-provisioner.yaml`

#csi-node-driver-registrar:v2.5.1-arm64
[root@k8s02-01 kubernetes]# sed -i "s#image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.1#image: docker.io/dyrnq/csi-node-driver-registrar@sha256:a8544fd23f870e64d5fa0c3d1f3653659f0695fab57f252ddb0af544106a4685#g" `grep "image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.1" -rl csi-rbdplugin.yaml`
[root@k8s02-01 kubernetes]# sed -i "s/namespace: default/namespace: kube-system/g" `grep "namespace: default" -rl csi-rbdplugin.yaml`

[root@k8s02-01 kubernetes]# kubectl apply -f csi-config-map.yaml -f ceph-config-map.yaml -f csidriver.yaml -f csi-provisioner-rbac.yaml -f csi-nodeplugin-rbac.yaml -f csi-rbdplugin-provisioner.yaml -f csi-rbdplugin.yaml
#and csi-rbdplugin pod and csi-rbdplugin-provisioner pod is in Running status
![image](https://github.com/ceph/ceph-csi/assets/15863985/022da690-7c4f-400b-a9eb-567a5ef119d4)

[root@k8s02-01 kubernetes]# cd /opt/installPkgs/install-k8s1.22/sc-rbd-practice/ceph-csi/examples/rbd/
[root@k8s02-01 rbd]# vi secret.yaml
#I am sure that the userKey of admin user is right for the ceph cluster to be integrated
[root@k8s02-01 rbd]# cat secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
stringData:
  # Key values correspond to a user name and its key, as defined in the
  # ceph cluster. User ID should have required access to the 'pool'
  # specified in the storage class
  userID: admin
  userKey: AQBPTg9i6AWEKBAAyUeCU19VZeV6lFgb+7A7rw==
  #userID: kubernetes
  #userKey: AQC3G4llRUc/BxAAKw03GDKw+Qn/LFGIdHbcTw==

  # Encryption passphrase
  encryptionPassphrase: test_passphrase
(3)#in ceph cluster I create pool named 
(ceph-mgr)[root@controller /]# ceph osd pool create kubernetes 16 16 disks
(ceph-mgr)[root@controller /]# ceph osd pool application enable kubernetes rbd
(ceph-mgr)[root@controller /]# rbd pool init kubernetes
(ceph-mgr)[root@controller /]# ceph osd pool ls detail | grep kubernets
![image](https://github.com/ceph/ceph-csi/assets/15863985/f9f0ab43-1d47-465f-82c9-b37d200ce8f8)
#ceph status is health_ok
(ceph-mgr)[root@controller /]# ceph -s
![image](https://github.com/ceph/ceph-csi/assets/15863985/9df91cab-9cae-47a9-968f-26dbae3ab1c9)
(4)#create storageclass
[root@k8s02-01 rbd]# cd /opt/installPkgs/install-k8s1.22/sc-rbd-practice/ceph-csi/examples/rbd/
[root@k8s02-01 rbd]# vi  storageclass.yaml
[root@k8s02-01 rbd]# head -n 35  storageclass.yaml
![image](https://github.com/ceph/ceph-csi/assets/15863985/d9fd602d-6ed5-4083-a0ac-9c232ef0a8cf)
(5)#to create pvc
[root@k8s02-01 rbd]# cp pvc.yaml pvc.yaml.172.24.1.100_02 
[root@k8s02-01 rbd]# vi pvc.yaml.172.24.1.100_02 
[root@k8s02-01 rbd]# cat pvc.yaml.172.24.1.100_02 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc02
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 100Mi
  storageClassName: csi-rbd-sc
[root@k8s02-01 rbd]# kubectl apply pvc.yaml.172.24.1.100_02

# Actual results #
(1)Creating pvc successfully sometimes
![image](https://github.com/ceph/ceph-csi/assets/15863985/bd8965a8-d9c8-4921-9da5-16233c110207)
(2)Failed to create pvc another time
![image](https://github.com/ceph/ceph-csi/assets/15863985/b6ff1496-9215-4bc9-ab5a-abcdb337fb86)

Describe what happened

# Expected behavior #
Creating pvc successfully all the time

# Logs #
- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.
![image](https://github.com/ceph/ceph-csi/assets/15863985/28784a4a-8d9a-4dd5-932e-af20c6df01bb)

- csi-resizer and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.
![image](https://github.com/ceph/ceph-csi/assets/15863985/47e97dc7-6270-4f95-85c6-ea26d8022a42)
all logs from csi-rbdplugin container was saved in file csi-rbdplugin.log
[csi-rbdplugin.log](https://github.com/ceph/ceph-csi/files/13765535/csi-rbdplugin.log)

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by nixpanic** [comment]
The versions that you use are rather old and not maintained any longer. It would be good to verify if this problem still occurs with recent and maintained versions (of all projects).

The `an operation with the given volume id ... already exists` usually comes up when the 1st request for that volume was blocked, delayed or failed in a completely unexpected way. You will need to find the 1st request in the logs, and find out if that request is still being processed by the Ceph cluster, or if it was aborted (and why).

**Comment by jiangsanyin** [comment]
> The versions that you use are rather old and not maintained any longer. It would be good to verify if this problem still occurs with recent and maintained versions (of all projects).
> 
> The `an operation with the given volume id ... already exists` usually comes up when the 1st request for that volume was blocked, delayed or failed in a completely unexpected way. You will need to find the 1st request in the logs, and find out if that request is still being processed by the Ceph cluster, or if it was aborted (and why).

Sorry for the delay in replying, I'm not in front of a computer the time you replied me.
The ceph14.2.22 cluster which was deployed by a colleague who left has this problem, I heavily doubt this results from some configurations in this ceph14.2.22 cluster. Because I tried to deply a new ceph14.2.22 cluster with almost everything default myself, and this new ceph14.2.22 works.

You said this ceph version is rather old and not maintained any longer, So I'm not going to look into it anymore and I I'll try a newer ceph version.

**Comment by jiangsanyin** [comment]
Thanks for your reply.
