### ISSUE TITLE
Provide tools/scripts to trace a PVC to its RADOS maps, keys and image/subvolume

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#435]
It would be useful to have a tool, that can take in a PVC as input and trace it to its image (rbd) or subvolume (cephFS), while also dumping required OMap and key information regarding the same.

Also a reverse mapping tool would be helpful to do the same in reverse.

This can aid debugging and troubleshooting to understand how things are linked up, and if they are linked up correctly as well.

The tool can also, provide options to start at varying input points (say PV instead of PVC) to dump similar information.

**Comment by humblec** [comment]
@ShyamsundarR are u working on this ? if not, let me find a volunteer :).. This can come handy , tagging it for next release with a flexible schedule.

**Comment by ShyamsundarR** [comment]
> @ShyamsundarR are u working on this ? if not, let me find a volunteer :).. This can come handy , tagging it for next release with a flexible schedule.

I am not working on this currently @humblec please reassign as appropriate.

**Comment by ShyamsundarR** [comment]
## Write-up of instructions to go from a PVC or a VolumeSnapshot to an image or subvolume in Ceph

**NOTE:** Assumption is that the input is the PVC-Name or snapshot name (as applicable) and that Ceph cluster details are known

### RBD images:
- PVC `volumeName` inspection
  - Command: ```kubectl get pvc/<PVC-Name> -o jsonpath='{.spec.volumeName}'```
  - Output is the PV `<volumeName>`

- PV `volumeHandle` inspection
  - Command: `kubectl get pv/<volumeName> -o jsonpath='{.spec.csi.volumeHandle}'`
  - Output is the CSI generated `VolID` and looks like: `0001-000c-rook-cluster-0000000000000001-f301898c-a192-11e9-852a-1eeeb6975c91`
    - fields in the output are, `<version>-<length of clusterID>-<clusterID>-<poolID>-<ImageUUID>`

- `volumeHandle` format and decomposition
  - Get `<poolname>` from `<poolID>` in `volumeHandle` using command: `ceph osd lspools`
  - Get `<ImageUUID>` from the `volumeHandle`

- Inspecting RADOS for the CSI journal
  - Check PV name is present in the RADOS managed CSI journal
    - Command: `rados -m ${monitors} --id ${id} --key ${key} -c /etc/ceph/ceph.conf -p ${poolname} getomapval csi.volumes.default csi.volume.<volumeHandle>`
    - Output should be the same as the `<ImageUUID>`
  - Check `<ImageUUID>` OMap points back to the `<volumeHandle>`
    - Command: `rados -m ${monitors} --id ${id} --key ${key} -c /etc/ceph/ceph.conf -p ${poolname} getomapval csi.volume.<ImageUUID> csi.volname`
    - Output should be the same as `<volumeName>`

- Inspecting RBD for the image details
  - Command: `rbd info -p replicapool csi-vol-<ImageUUID>`
  - Output is the required image information

### RBD snapshots:

- `VolumeSnapshot` `snapshotContentName` inspection:
  - Command: `kubectl get volumesnapshot/<snapshot-name> -o jsonpath='{.spec.snapshotContentName}'`
  - Output is the `<snapshotContentName>`

- `snapshotContentName` `snapshotHandle` inspection
  - Command: `kubectl get volumesnapshotcontent/<snapshotContentName> -o jsonpath='{.spec.csiVolumeSnapshotSource.snapshotHandle}'`
  - Output is a CSI snapshothandle like: `0001-000c-rook-cluster-0000000000000001-1f174142-a199-11e9-852a-1eeeb6975c91`
    - Fields are: `<version>-<length of clusterID>-<clusterID>-<poolID>-<SnapUUID>`

- Rest of the RADOS and snapshot inspection is as above with the following deltas,
  - In places where the OMap object names are `csi.volumes.default`, replace with `csi.snaps.default`
  - In places where the OMap object/keys names **start with** `csi.volume.`, replace with `csi.snap.`
  - In places where the OMap key names are `csi.volname`, replace with `csi.snapname`
  - The snapshot is named using `csi-snaps-<SnapUUID>`
  - The <SnapUUID> OMap additionally contains the parent image name as one of the keys, this is fetched using,
    - Command: `rados -m ${monitors} --id ${id} --key ${key} -c /etc/ceph/ceph.conf -p ${poolname} getomapval csi.snap.<SnapUUID> csi.source`
    - The output is the `<parentImage>` useful in command to list information about the snapshot: `rbd snap ls -p <poolname> <parentImage>`

### CephFS subvolumes:

Instructions are the same as with RBD except,
- The `<poolID>` encoded in the `volumeHandle` is the CephFS filesystem name `<fsname>` and hence to get the poolname to use with the RADOS commands, use the metadata pool associated with the `<fsname>` (which can be fetched using command `ceph fs ls`)
- Instead of looking for an RBD image, the subvolume is a directory under `/csi-volumes/<ImageUUID>`
  - **NOTE:** The above will change once we move to using Ceph manager based commands to create CephFS subvolumes.

**Comment by Madhu-1** [comment]
@ajarr can you update on how to track cephfs PVC?

**Comment by Madhu-1** [comment]
for rbd, we have a tool for mapping the PVC to backend image name, for cephfs we need to add the same. as this cannot be done before the release. moving this out of  v1.2.0

**Comment by Madhu-1** [comment]
@agarwal-mudit this might be interesting to you, would you like to take this up? the support is already present for rbd we need to add for cephfs

**Comment by agarwal-mudit** [comment]
sure, please assign.

**Comment by agarwal-mudit** [comment]
> for rbd, we have a tool for mapping the PVC to backend image name, for cephfs we need to add the same. as this cannot be done before the release. moving this out of v1.2.0

@Madhu-1 Please point to the location of the existing rbd tool.

**Comment by agarwal-mudit** [comment]
> > for rbd, we have a tool for mapping the PVC to backend image name, for cephfs we need to add the same. as this cannot be done before the release. moving this out of v1.2.0
> 
> @Madhu-1 Please point to the location of the existing rbd tool.

Got it, troubleshooting/tools/tracevol.py

**Comment by agarwal-mudit** [comment]
While running the existing script for RBD pvc I found some issue with python, may be when this script was written python version was lower which didn't care about bytes. Newer python version (python 3+) is strict about the binary mode.

For example: 
```
out = subprocess.Popen(cmd, stdout=subprocess.PIPE,  stderr=subprocess.STDOUT)                                                                                            
stdout, stderr = out.communicate() 
```
stdout is opened in binary mode and would be treated as binary-like object, if the coder treats it as string like in the below code:
`lines = [x.strip() for x in stdout.split("\n")]
`
It will give following error:
`

> TypeError: a bytes-like object is required, not 'str'

`
A way to fix this is:
`lines = [x.strip() for x in stdout.split(**b**"\n")]`

There are many such places in the script where this problem exists, we have three solutions:
1. Fix all the places and recommend user to run it with python 3.5 at least.
2. Recommend user to run it with a lower python version like 2.7
3. Create a venv before running the script with apt. python version

First option seems more trivial to me but I will wait for the comments.

**Comment by Madhu-1** [comment]
as python2.7 is EOL we can consider moving to python 3.x and fix this in all places

**Comment by agarwal-mudit** [comment]
This script will not work for static/pre-provisioned volumes because:
1. volume name would be in a different format compared to the format expected by the script.
2. subvolumefroup can be different from the one mentioned in configmap.

Do we need to enhance it for that, may be in a separate PR.
