### ISSUE TITLE
rbd: globalmount does not exist on node

### ISSUE THREAD

**Issue by PenphyYang** [ceph/ceph-csi#4382]
### Describe the bug：
i can create a volume and  it's bound but I get this error when i try to mount the volume in a image.
MountVolume.MountDevice failed for volume "pvc-43d2c1e6-2a28-4e14-80e9-c3d948f3c65c" : rpc error: code = InvalidArgument desc = staging path /data/k8s/kubelet/plugins/kubernetes.io/csi/rbd.csi.ceph.com/dbe13b4485d6eb6a44aa77bb8d812f82927b4848e60aa33f5b49a94bda13e486/globalmount does not exist on node
### Environment details：
k8s:1.27.6
k8s install_path:/data/k8s
ceph_csi: v3.5.1
ceph: v14.2.21
### Steps:
logs csi-rbdplugin:
![image](https://github.com/ceph/ceph-csi/assets/37333726/05d74415-d6d8-4220-b80c-49eb28e33a4a)

pvc is ok
![f0e7ee500380562508bafe90cb84971](https://github.com/ceph/ceph-csi/assets/37333726/a856097c-5b86-4a11-a03e-5eba2cdaad1d)

mount is false
![14d2c44fd8fa7c64b136d882722dd5b](https://github.com/ceph/ceph-csi/assets/37333726/677f51d6-a647-4efd-b166-2f60e39e37ce)

csi-rbdplugin.yml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "6"
  creationTimestamp: "2024-01-17T09:41:40Z"
  generation: 6
  name: csi-rbdplugin
  namespace: ceph-csi
  resourceVersion: "254777"
  uid: 38420bdd-318c-4c23-a7b4-d57492ce982b
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: csi-rbdplugin
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: csi-rbdplugin
    spec:
      containers:
      - args:
        - --v=5
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/data/k8s/kubelet/plugins/rbd.csi.ceph.com/csi.sock
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: registry.cn-shanghai.aliyuncs.com/singless/csi-node-driver-registrar:v2.4.0
        imagePullPolicy: IfNotPresent
        name: driver-registrar
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /registration
          name: registration-dir
      - args:
        - --nodeid=$(NODE_ID)
        - --pluginpath=/data/k8s/kubelet/plugins
        - --stagingpath=/data/k8s/kubelet/plugins/kubernetes.io/csi/pv/
        - --type=rbd
        - --nodeserver=true
        - --endpoint=$(CSI_ENDPOINT)
        - --csi-addons-endpoint=$(CSI_ADDONS_ENDPOINT)
        - --v=5
        - --drivername=rbd.csi.ceph.com
        - --enableprofiling=false
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: CSI_ADDONS_ENDPOINT
          value: unix:///csi/csi-addons.sock
        image: quay.io/cephcsi/cephcsi:v3.5.1
        imagePullPolicy: IfNotPresent
        name: csi-rbdplugin
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /dev
          name: host-dev
        - mountPath: /sys
          name: host-sys
        - mountPath: /run/mount
          name: host-mount
        - mountPath: /etc/selinux
          name: etc-selinux
          readOnly: true
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /etc/ceph-csi-config/
          name: ceph-csi-config
        - mountPath: /etc/ceph-csi-encryption-kms-config/
          name: ceph-csi-encryption-kms-config
        - mountPath: /var/lib/kubelet/plugins
          mountPropagation: Bidirectional
          name: plugin-dir
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
        - mountPath: /tmp/csi/keys
          name: keys-tmp-dir
        - mountPath: /var/log/ceph
          name: ceph-logdir
        - mountPath: /etc/ceph/
          name: ceph-config
      - args:
        - --type=liveness
        - --endpoint=$(CSI_ENDPOINT)
        - --metricsport=8680
        - --metricspath=/metrics
        - --polltime=60s
        - --timeout=3s
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: quay.io/cephcsi/cephcsi:v3.5.1
        imagePullPolicy: IfNotPresent
        name: liveness-prometheus
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rbd-csi-nodeplugin
      serviceAccountName: rbd-csi-nodeplugin
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/k8s/kubelet/plugins/rbd.csi.ceph.com
          type: DirectoryOrCreate
        name: socket-dir
      - hostPath:
          path: /data/k8s/kubelet/plugins
          type: Directory
        name: plugin-dir
      - hostPath:
          path: /data/k8s/kubelet/pods
          type: DirectoryOrCreate
        name: mountpoint-dir
      - hostPath:
          path: /data/k8s/log/ceph
          type: DirectoryOrCreate
        name: ceph-logdir
      - hostPath:
          path: /data/k8s/kubelet/plugins_registry/
          type: Directory
        name: registration-dir
      - hostPath:
          path: /dev
          type: ""
        name: host-dev
      - hostPath:
          path: /sys
          type: ""
        name: host-sys
      - hostPath:
          path: /etc/selinux
          type: ""
        name: etc-selinux
      - hostPath:
          path: /run/mount
          type: ""
        name: host-mount
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - configMap:
          defaultMode: 420
          name: ceph-config
        name: ceph-config
      - configMap:
          defaultMode: 420
          name: ceph-csi-config
        name: ceph-csi-config
      - configMap:
          defaultMode: 420
          name: ceph-csi-encryption-kms-config
        name: ceph-csi-encryption-kms-config
      - emptyDir:
          medium: Memory
        name: keys-tmp-dir
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 1
  observedGeneration: 6
  updatedNumberScheduled: 1

thanks!

**Comment by PenphyYang** [comment]
see https://github.com/ceph/ceph-csi/issues/1067

**Comment by PenphyYang** [comment]
see https://github.com/ceph/ceph-csi/issues/1067
it's ok
thanks

**Comment by nixpanic** [comment]
Thanks! I guess you were able to address the issue as you refer to one that has been fixed. If that is not the case, please let us know.
