### ISSUE TITLE
Invite link to slack workspace is not active

### ISSUE THREAD

**Issue by switchboardOp** [ceph/ceph-csi#4391]
# Describe the bug #

invite link to slack channel is broken.

# Environment details #

N/A this is in the readme of this repo

# Steps to reproduce #

1. open [https://bit.ly/40FQu7u](https://bit.ly/40FQu7u) a browser
# Actual results #

Slack error page saying 
```
This link is no longer active
```

# Expected behavior #

Expected to join a new slack workspace

# Logs #

N/A

# Additional context #

nope.

**Comment by nixpanic** [comment]
Can you check if https://ceph-storage.slack.com/archives/C05522L7P60 works for you?

**Comment by juanjalvarez** [comment]
The same is happening on my end, @nixpanic that link does not work for me either

**Comment by switchboardOp** [comment]
> Can you check if https://ceph-storage.slack.com/archives/C05522L7P60 works for you?

That looks to be a sign in link not an invite link. It doesn't work for me since I don't have an account in this workspace yet.

**Comment by nixpanic** [comment]
Aha, I didn't know there was a difference between links to channels and an invite to the workspace.

Let's try with https://join.slack.com/t/ceph-storage/shared_invite/zt-2bly4isgz-mSxwgheAYlcK~s1HjYeLzA ? You may still need to join the `#ceph-csi` channel after that.

**Comment by switchboardOp** [comment]
That's what I needed. Thanks @nixpanic
