### ISSUE TITLE
cephfs:  pod mount cephfs pvc error

### ISSUE THREAD

**Issue by yinshiweiysw** [ceph/ceph-csi#4423]
### Describe the bug
I created a pv/pvc with storageclass from ceph-csi, but I got an error when I tried to mount it with a pod

![image](https://github.com/ceph/ceph-csi/assets/58204637/4773de45-981f-490a-baf0-784ac2593af4)

###Environment details
Image/version of Ceph CSI driver : cephcsi/cephcsi:latest
Kernel version : ubuntu22.04
Kubernetes cluster version : v1.28.4 (k3s)
Ceph cluster version : 17.2.6

**Comment by yinshiweiysw** [comment]
This is my ceph environment
![image](https://github.com/ceph/ceph-csi/assets/58204637/1361450b-fe15-41a4-8d66-f065e24e752e)
and I have another question . The default mount mode is fuse, even if I point it to kernel through mounter, it's still fuse mode
![image](https://github.com/ceph/ceph-csi/assets/58204637/79cae4eb-4fd6-45fb-a7dc-c429eb002e06)

**Comment by nixpanic** [comment]
Can you pass the logs of the csi-cephfsplugin container from the Ceph-CSI daemonset that runs on that node? Possibly the Ceph kernel module is not available, causing the fallback to ceph-fuse.

**Comment by yinshiweiysw** [comment]
> Can you pass the logs of the csi-cephfsplugin container from the Ceph-CSI daemonset that runs on that node? Possibly the Ceph kernel module is not available, causing the fallback to ceph-fuse.
![image](https://github.com/ceph/ceph-csi/assets/58204637/f06c4281-1e89-4d5e-ae56-efb0af5056aa)
this is the log file，It doesn't seem to see anything wrong

**Comment by nixpanic** [comment]
Note the 1st line in that log screenshot. Please fetch the logs from the `csi-cephfsplugin` container instead of the `driver-registrar` container.
