### ISSUE TITLE
[csi-cephfs] cephfs PVC fails to mount in OCP4 postgresql pod

### ISSUE THREAD

**Issue by netzzer** [ceph/ceph-csi#444]
Cannot mount a cephfs PVC into a postgresql pod created from an openshift default template (attached). 
# Environment details #

- Image/version of Ceph CSI driver
$ cat operator-openshift-with-csi.yaml
...
CSI enablement
        - name: ROOK_CSI_ENABLE_CEPHFS
          value: "true"
        - name: ROOK_CSI_CEPHFS_IMAGE
          value: "quay.io/cephcsi/cephfsplugin:canary"
        - name: ROOK_CSI_ENABLE_RBD
          value: "true"
        - name: ROOK_CSI_RBD_IMAGE
          value: "quay.io/cephcsi/rbdplugin:canary"
        - name: ROOK_CSI_REGISTRAR_IMAGE
          value: "quay.io/k8scsi/csi-node-driver-registrar:v1.0.2"
        - name: ROOK_CSI_PROVISIONER_IMAGE
          value: "quay.io/k8scsi/csi-provisioner:v1.0.1"
        - name: ROOK_CSI_SNAPSHOTTER_IMAGE
          value: "quay.io/k8scsi/csi-snapshotter:v1.0.1"
        - name: ROOK_CSI_ATTACHER_IMAGE
          value: "quay.io/k8scsi/csi-attacher:v1.0.1"
- helm chart version
No idea
- Kubernetes cluster version
$ oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.2-201906121056+3569a06-dirty", GitCommit:"3569a06", GitTreeState:"dirty", BuildDate:"2019-06-12T15:47:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+d4417a7", GitCommit:"d4417a7", GitTreeState:"clean", BuildDate:"2019-06-12T15:47:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
[ceph-postgresql-persistent.yaml.gz](https://github.com/ceph/ceph-csi/files/3326620/ceph-postgresql-persistent.yaml.gz)

Need to have created csi-cephfs storageclas

1. oc new-project postgresql
2. oc create -f ceph-postgresql-persistent.yaml
3. oc get pvc
4. oc get pods
5. postgresql pod in CrashBackOffLoop
6. oc logs <postgresql_pod>

**Comment by netzzer** [comment]
Most likely it is due to securityContext of the pod. First pod is created from pod.yaml in ~/csi/examples/cephfs. Second pod is postgresql pod created from attached postgresql template using csi-rbd vs csi-cephfs storageclass (so that pod is created and you can look at yaml output).

$ oc get csicephfs-demo-pod -o yaml
...
    securityContext:
      capabilities:
        drop:
        - MKNOD
      procMount: Default

$ oc get pod/postgresql-1-6c4z9 -o yaml (create using csi-rbd to create PVC so pod will succeed)
...
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      privileged: false
      procMount: Default
      runAsUser: 1000550000

**Comment by netzzer** [comment]
logs for failed postgresql pod (cannot mount PVC created from csi-cephfs)
$ oc logs -f postgresql-x-xxxxx
mkdir: cannot create directory '/var/lib/pgsql/data': Permission denied

**Comment by ShyamsundarR** [comment]
Problem faced here is fixed in https://github.com/ceph/ceph-csi/pull/423 

@netzzer The images in use in your setup do not have the fix `"quay.io/cephcsi/rbdplugin:canary"`

The PR that got merged into Rook today [1] has the [changes](https://github.com/rook/rook/blob/004f795a7928f407d4d108cd678ffbd1264834fe/cluster/examples/kubernetes/ceph/operator-openshift-with-csi.yaml#L125-L126) to use the latest `"quay.io/cephcsi/cephcsi:canary"` images that do carry the fix mentioned. If the environment is shifted to use the same, the permission issue should not occur.

Request a retest with latest Rook images to ensure fix is working for you.

[1] Rook PR: https://github.com/rook/rook/pull/3324

**Comment by netzzer** [comment]
I did retest with fresh clone of rook master branch and the issue is fixed. I am able now to mount a cephfs PVC in a postgresql pod.

$ oc rsh postgresql-1-l9tqb
sh-4.2$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         119G  6.8G  113G   6% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
shm              64M  8.0K   64M   1% /dev/shm
tmpfs           7.7G  3.8M  7.7G   1% /etc/passwd
/dev/nvme0n1p3  119G  6.8G  113G   6% /etc/hosts
**ceph-fuse        10G   44M   10G   1% /var/lib/pgsql/data**

**Comment by Madhu-1** [comment]
@netzzer thanks for confirming. closing this issue.
