### ISSUE TITLE
How about adding a helm chart related to nfs in chart directory like deploy folder?

### ISSUE THREAD

**Issue by Bokki-Ryu** [ceph/ceph-csi#4456]
# Describe the feature you'd like to have #
Install helm chart related with nfs

What new functionality do you want?
Add  helm chart related with nfs

# What is the value to the end user? (why is it a priority?) #

How would the end user gain value from having this feature?
Easy configuration about ceph export with nfs

# How will we know we have a good solution? (acceptance criteria) #

Add a list of criteria that should be met for this feature to be useful

# Additional context #

**Comment by nixpanic** [comment]
Yes, that would be great to have!
