### ISSUE TITLE
`make cephcsi` is failing in head branch

### ISSUE THREAD

**Issue by parth-gr** [ceph/ceph-csi#4460]
# Describe the bug #
`make cephcsi` should create a docker image.

```
[root@localhost ceph-csi]# make cephcsi 
cephcsi image settings: quay.io/cephcsi/cephcsi version canary
if [ ! -d ./vendor ]; then (go mod tidy && go mod vendor); fi
GOOS=linux go build -tags=reef -mod vendor -a -ldflags '-X github.com/ceph/ceph-csi/internal/util.GitCommit=c0fc7b36e38d94a38500490a4c988beaa1179cdf -X github.com/ceph/ceph-csi/internal/util.DriverVersion=canary' -o _output/cephcsi ./cmd/
# github.com/ceph/go-ceph/rbd
vendor/github.com/ceph/go-ceph/rbd/encryption.go:35:50: could not determine kind of name for C.RBD_ENCRYPTION_ALGORITHM_AES128
vendor/github.com/ceph/go-ceph/rbd/encryption.go:36:50: could not determine kind of name for C.RBD_ENCRYPTION_ALGORITHM_AES256
vendor/github.com/ceph/go-ceph/rbd/encryption.go:73:19: could not determine kind of name for C.RBD_ENCRYPTION_FORMAT_LUKS1
vendor/github.com/ceph/go-ceph/rbd/encryption.go:87:19: could not determine kind of name for C.RBD_ENCRYPTION_FORMAT_LUKS2
vendor/github.com/ceph/go-ceph/rbd/encryption.go:29:26: could not determine kind of name for C.rbd_encryption_algorithm_t
vendor/github.com/ceph/go-ceph/rbd/encryption.go:111:9: could not determine kind of name for C.rbd_encryption_format
vendor/github.com/ceph/go-ceph/rbd/encryption.go:22:11: could not determine kind of name for C.rbd_encryption_format_t
vendor/github.com/ceph/go-ceph/rbd/encryption.go:136:9: could not determine kind of name for C.rbd_encryption_load
vendor/github.com/ceph/go-ceph/rbd/encryption.go:64:12: could not determine kind of name for C.rbd_encryption_luks1_format_options_t
vendor/github.com/ceph/go-ceph/rbd/encryption.go:78:12: could not determine kind of name for C.rbd_encryption_luks2_format_options_t
vendor/github.com/ceph/go-ceph/rbd/encryption.go:23:11: could not determine kind of name for C.rbd_encryption_options_t
vendor/github.com/ceph/go-ceph/rbd/encryption.go:71:30: could not determine kind of name for C.sizeof_rbd_encryption_luks1_format_options_t
vendor/github.com/ceph/go-ceph/rbd/encryption.go:85:30: could not determine kind of name for C.sizeof_rbd_encryption_luks2_format_options_t
make: *** [Makefile:164: cephcsi] Error 1
[root@localhost ceph-csi]# 

```

# Environment details #

- Image/version of Ceph CSI driver :
- Helm chart version :
- Kernel version :
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) :
- Kubernetes cluster version :
- Ceph cluster version :

# Steps to reproduce #

1. Setup details: '...'
1. Deployment to trigger the issue '....'
1. See error

# Actual results #

Describe what happened

# Expected behavior #

# Logs #

If the issue is in PVC creation, deletion, cloning please attach complete logs
of below containers.

- csi-provisioner and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC resize please attach complete logs of below containers.

- csi-resizer and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in snapshot creation and deletion please attach complete logs
of below containers.

- csi-snapshotter and csi-rbdplugin/csi-cephfsplugin container logs from the
  provisioner pod.

If the issue is in PVC mounting please attach complete logs of below containers.

- csi-rbdplugin/csi-cephfsplugin and driver-registrar container logs from
  plugin pod from the node where the mount is failing.

- if required attach dmesg logs.

**Note:-** If its a rbd issue please provide only rbd related logs, if its a
cephFS issue please provide cephFS logs.

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by Madhu-1** [comment]
@parth-gr have you followed https://github.com/ceph/ceph-csi/blob/devel/docs/development-guide.md#development-workflow?

**Comment by nixpanic** [comment]
The easiest is to run `make containerized-build`, that provides all dependencies in a container and you won't need to install Ceph or other development libraries on your system.

**Comment by parth-gr** [comment]
Not sure but looks like something wrong with the setup
```
[rider@localhost ceph-csi]$ make containerized-build
cephcsi image settings: quay.io/cephcsi/cephcsi version canary
docker run --rm -v /home/rider/go/src/github.com/ceph/ceph-csi:/go/src/github.com/ceph/ceph-csi:z quay.io/cephcsi/cephcsi:devel make cephcsi CONTAINERIZED=yes
cephcsi image settings: quay.io/cephcsi/cephcsi version canary
fatal: detected dubious ownership in repository at '/go/src/github.com/ceph/ceph-csi'
To add an exception for this directory, call:

	git config --global --add safe.directory /go/src/github.com/ceph/ceph-csi
if [ ! -d ./vendor ]; then (go mod tidy && go mod vendor); fi
GOOS=linux go build -tags=reef -mod vendor -a -ldflags ' -X github.com/ceph/ceph-csi/internal/util.GitCommit= -X github.com/ceph/ceph-csi/internal/util.DriverVersion=canary' -o _output/cephcsi ./cmd/
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
make: *** [Makefile:164: cephcsi] Error 1
make: *** [Makefile:200: containerized-build] Error 2

```

Secondly do we keep ceph-csi insisde the ceph project  generally for development?

**Comment by parth-gr** [comment]
In mac cmd is getting stucked 
```
e cephcsi CONTAINERIZED=yes
cephcsi image settings: quay.io/cephcsi/cephcsi version canary
if [ ! -d ./vendor ]; then (go mod tidy && go mod vendor); fi
GOOS=linux go build -tags=reef -mod vendor -a -ldflags ' -X github.com/ceph/ceph-csi/internal/util.GitCommit=65954fa563fca73f835e57ff503a3455e94ea77f -X github.com/ceph/ceph-csi/internal/util.DriverVersion=canary' -o _output/cephcsi ./cmd/
```

**Comment by parth-gr** [comment]
@Madhu-1 any idea??

**Comment by parth-gr** [comment]
worked in mac thanks, but image is corrupted

**Comment by iPraveenParihar** [comment]
> Not sure but looks like something wrong with the setup
> 
> ```
> [rider@localhost ceph-csi]$ make containerized-build
> cephcsi image settings: quay.io/cephcsi/cephcsi version canary
> docker run --rm -v /home/rider/go/src/github.com/ceph/ceph-csi:/go/src/github.com/ceph/ceph-csi:z quay.io/cephcsi/cephcsi:devel make cephcsi CONTAINERIZED=yes
> cephcsi image settings: quay.io/cephcsi/cephcsi version canary
> fatal: detected dubious ownership in repository at '/go/src/github.com/ceph/ceph-csi'
> To add an exception for this directory, call:
> 
> 	git config --global --add safe.directory /go/src/github.com/ceph/ceph-csi
> if [ ! -d ./vendor ]; then (go mod tidy && go mod vendor); fi
> GOOS=linux go build -tags=reef -mod vendor -a -ldflags ' -X github.com/ceph/ceph-csi/internal/util.GitCommit= -X github.com/ceph/ceph-csi/internal/util.DriverVersion=canary' -o _output/cephcsi ./cmd/
> error obtaining VCS status: exit status 128
> 	Use -buildvcs=false to disable VCS stamping.
> make: *** [Makefile:164: cephcsi] Error 1
> make: *** [Makefile:200: containerized-build] Error 2
> ```
> 
> Secondly do we keep ceph-csi insisde the ceph project generally for development?


connected offline with @parth-gr, 
Issue was due to change in folder ownership. By changing the owner to correct user issue was resolved.


@parth-gr, can we close this now?

**Comment by parth-gr** [comment]
Sure get is running by `make -j4 image-cephcsi CSI_IMAGE_NAME="quay.io/mpraveen/cephcsi" CSI_IMAGE_VERSION="volsnap-omap-regenerate" GO_ARCH="amd64"` and updating the folder permissions
