### ISSUE TITLE
Implement a merged RBD/CephFS "csi.ceph.com" driver

### ISSUE THREAD

**Issue by dillaman** [ceph/ceph-csi#451]
# Describe the feature you'd like to have #

Once both the RBD and CephFS CSI driver reach (near) feature parity, provide a unified driver that hides the low-level implementation details between RBD/CephFS. When requesting RWO for filesystem PVs or RWO/RWX for block PVs, it should automatically use RBD. When requesting RWX for filesystem PVs, it should automatically use CephFS. 

# What is the value to the end user? (why is it a priority?) #

Our goal should be to hide any low-level implementation details for the casual user of the Ceph CSI. Requesting PVs from a Ceph backend storage cluster should just work w/o having to understand RBD vs CephFS design choices.

# How will we know we have a good solution? (acceptance criteria) #

When we have a unified support matrix that just works between the two technologies w/o the user needing to explicitly choose which backend to use. Hopefully, it will be able to re-use the same core logic that the existing `rbd.csi.ceph.com` and `cephfs.csi.ceph.com` driver utilize. 

# Additional context #

n/a

**Comment by humblec** [comment]
@dillaman this is one of the goal we should chase once we are in feature completion in individual drivers. The abstraction or control completely at SP's hand would be most of the people like, but there are some users who want to tweak their own too. Considering that, my opinion would be having 2 versions available. One completely in SP's control , one for controlling it from admin side. Almost same as 'UPI, IPI' model. Ideally this need not be in CSI driver's control , the orchestrator or top level operator can take the user request and apply the business logic to reach out to specific driver.  The decision from operator would be better IMO, but nothing stopping us from carving out a unary driver too.  This is my immediate response here :).

**Comment by dillaman** [comment]
> this is one of the goal we should chase once we are in feature completion in individual drivers

Indeed, that was the intention of my caveat in the first sentence. 

> Ideally this need not be in CSI driver's control , the orchestrator or top level operator can take the user request and apply the business logic to reach out to specific driver.

Given the use-case of users requesting PVCs from SCs, that implies the creation of a new CSI that understands the business logic of Ceph. To me, since it would be inherently tied to the capabilities of Ceph, it makes sense to keep it all within `ceph-csi`.

I don't think the operator pattern would apply here since that would imply that something is watching for specific PVCs and will tweak the `StorageClass` under-the-hood to point to the correct one. In general, I'd imagine that would be fine -- until someone just dumps the tweaked yaml and uses it as a starting point for a new PVC (and thus bypassing the operator).

**Comment by humblec** [comment]
As this is our ultimate goal and this going to be a version of ceph-csi  for 'operating in an automatic way' which help admin to forget about the internals, this is a critical feature to have!. I am raising the priority for this issue/feature and would like to reach on the solution at the earliest. The current plan is to track it for the release after v1.1.  Calling out for volunteers for this enhancement , any takers ?, I can offer my help to  design/code..etc .

@madhu-1 @ShyamsundarR  @poornimag .. ?

**Comment by Madhu-1** [comment]
@humblec I will work on this.
/assign @Madhu-1

**Comment by mykaul** [comment]
@humblec  - what happens when I wish to change from RWO to RWX? If I've started with RBD/RWO, how will it move to CephFS/RWX? PVs can change between modes freely (not on runtime of course).

**Comment by dillaman** [comment]
We will also need to support clone-from-snapshot/volume between the two backend provisioners. Switching access modes is similar to the clone-from-volume case.

**Comment by nixpanic** [comment]
A single Ceph-CSI provisioner that allocates a PV on RBD or CephFS based on the volume request makes sense to me, it would be much more user-friendly than offering two separate storageclasses for their own functionality.

Using CephFS: `volumeType: filesystem` and `accessModes: <includes RWX>`
Using RBD: `volumeType: block` or `accessModes: <does not include RWX>`

This should likely be a 3rd provisioner in the `cephcsi` executable that forwards the request to the other provisioning functions. Once adopted, it may make sense to remove the dedicated CephFS/RBD provisioners, but keeping them for backwards compatibility would probably be good.
