### ISSUE TITLE
doc: Missing mgr capabilities  docs/capabilities.md document.

### ISSUE THREAD

**Issue by Amitgb14** [ceph/ceph-csi#4518]
In the docs/capabilities.md  document not mentioned mgr.<id> should has full capabilities access to delete pv's and because of that we faced below error while terminating instance.

`type: 'Warning' reason: 'VolumeFailedDelete' rpc error: code = Internal desc = rados: ret=-1, Operation not permitted: "[errno 1] RBD permission error (error retrieving image from trash)"`

After adding next cap to all mgrs then all instance goes into Terminate state,
`ceph auth caps mgr.<id> osd 'allow *' mon 'allow *'`

**Comment by Madhu-1** [comment]
@Amitgb14 If this needs to be done on the ceph cluster not specific to the csi user we created(as documented), we don't document this in cephcsi as it's an assumption that the user will be able to do all operations on the ceph cluster.

**Comment by Amitgb14** [comment]
Thanks @Madhu-1 , for quick reply. Yes your are correct this is ceph configuration but most of time we don't know what we missed to run csi and it's difficult to find actual root cause. CSI used rdb_support plugin to perform rwx operation on osd and running non rbd operation(RGW) in Ceph doesn't need to provide osd caps to mgr or not it mentioned anywhere. I hope if we not updated in documents, someone can find here.
