### ISSUE TITLE
csi-provisioner grpc: error while marshaling: string field contains invalid UTF-8

### ISSUE THREAD

**Issue by wangchao732** [ceph/ceph-csi#4581]
helm charts  install  csi-provisioner

failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-rbd-sc
  labels:
    app: ceph-csi-rbd
    app.kubernetes.io/managed-by: Helm
    chart: ceph-csi-rbd
    heritage: Helm
    release: ceph-csi-rbd
  annotations:
    kubesphere.io/creator: admin
    meta.helm.sh/release-name: ceph-csi-rbd
    meta.helm.sh/release-namespace: ceph-csi-rbd
    storageclass.kubesphere.io/allow-clone: 'true'
    storageclass.kubesphere.io/allow-snapshot: 'true'
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: 80a8efd7-8ed5-4e53-bc5b-f91c56300e99
  csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ceph-csi-rbd
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi-rbd
  csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi-rbd
  imageFeatures: layering
  pool: k8s-store
reclaimPolicy: Delete
mountOptions:
  - discard
allowVolumeExpansion: true
volumeBindingMode: Immediate

**Comment by toralux** [comment]
I have the same problem and wonder why this issue was closed wihout any comment about what was the solution to the problem?

```
Warning  ProvisioningFailed    55s (x11 over 9m26s)    rbd.csi.ceph.com_ceph-csi-rbd-provisioner-7c879fd6c8-f92w8_129bf5b9-5854-4dc9-b8b4-a2f1976f07c0  failed to provision volume with StorageClass "rbd": rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
```

**Comment by toralux** [comment]
Problem solved after finding [https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/2433](this) issue that sent me in the correct direction.

The problem was that the key returned by command ceph `auth get-key client.k8s-csi-rbd` looked like it was base64 encoded so I put it directly into Kubernetes secret as is, but in reality it had to be base64 encoded once more. Hope this helps anyone else finding this issue.
