### ISSUE TITLE
Docker image for cephfsplugin should be public

### ISSUE THREAD

**Issue by mkimuram** [ceph/ceph-csi#46]
Cephfsplugin should be able to be pulled from public repository.

Currently, below command fails and only rbdplugin seems visible in https://quay.io/organization/cephcsi .
```# docker pull quay.io/cephcsi/cephfsplugin```

This is required to make cephfsplugin run in k8s e2e testing https://github.com/kubernetes/kubernetes/issues/66388.

**Comment by rootfs** [comment]
It should be `quay.io/cephcsi/cephfsplugin:v0.2.0` but I just realized the repo was not there yet. I created it and the image should be pushed there by Travis CI when next PR (hopefully from @gman0) is merged

**Comment by rootfs** [comment]
@mkimuram it is there now (thanks to CI)
```console
# docker pull quay.io/cephcsi/cephfsplugin:v0.2.0
v0.2.0: Pulling from cephcsi/cephfsplugin
3620e2d282dc: Already exists 
ef22f5e4b3b2: Already exists 
99f229f854da: Already exists 
4fe433abe16a: Already exists 
c9b72a16d85e: Already exists 
0c881787af01: Downloading [>                                                  ]  536.1kB/55.39MB
9e37e18d4b25: Downloading [===========>                                       ]  895.4kB/3.889MB
```

**Comment by mkimuram** [comment]
@rootfs Thank you for quickly handling this! I also confirmed that this issue is resolved.
