### ISSUE TITLE
ceph image expansion problem

### ISSUE THREAD

**Issue by wenjunGU** [ceph/ceph-csi#4605]
My kubernetes cluster uses Ceph-CSI, changing storage in pvc can expand the size of ceph rbd img, but I found that this does not work for Pods using csi, only the size of /dev/rbdx mapped on the host. Is there a good solution to this problem?

**Comment by Madhu-1** [comment]
@wenjunGU please fill out the template when opening an issue.

if you are formatting the rbd image (assuming you are using RWX blockMode) you need to resize the filesystem as well.

Closing the issue as it doesn't contains all the required details.

**Comment by wenjunGU** [comment]
@Madhu-1 Thank you. I have solved the problem, but I need the help of other tools qemu-img. Thank you for your reminding
