### ISSUE TITLE
Please tag built releases

### ISSUE THREAD

**Issue by BlaineEXE** [ceph/ceph-csi#462]
# Describe the bug #

Please tag versioned releases which are published to Docker Hub and/or Quay in the source so that users may cross-reference the code with the container image. If there is a container `cephcsi/cephcsi:vX.Y.Z`, I should be able to find the tag `vX.Y.Z` in the source to know what code is built into that container.

**Comment by humblec** [comment]
@BlaineEXE sure, do u see this is missing any where ? with CSI v1.1 #353 we will be chaning the driver version too . https://github.com/ceph/ceph-csi/pull/405

**Comment by BlaineEXE** [comment]
Yes. GitHub shows only 1 tag/release for the `cephcsi` project. Each time a new container is built and published with a version, there should be a corresponding GitHub release.

**Comment by humblec** [comment]
> Yes. GitHub shows only 1 tag/release for the `cephcsi` project. Each time a new container is built and published with a version, there should be a corresponding GitHub release.

This is correct :), the reason being we havent released any versions yet! csi v1.1.0 going to be the first release.

**Comment by humblec** [comment]
> > Yes. GitHub shows only 1 tag/release for the `cephcsi` project. Each time a new container is built and published with a version, there should be a corresponding GitHub release.
> 
> This is correct :), the reason being we havent released any versions yet! csi v1.1.0 going to be the first release.

This is done with v1.1.0 release https://github.com/ceph/ceph-csi/releases

! closing this issue
