### ISSUE TITLE
Establish weekly meeting for Ceph-CSI issue/bug triage 

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#463]
With this, we would like to establish a process to triage ceph-csi issues ( https://github.com/ceph/ceph-csi/issues) weekly once . This helps on improving the code and also bring a forum for Ceph-CSI users to ask or highlight issues/bugs they encounter in their setup. 

The initial version of this meeting can be in ceph-csi slack or via video conferencing.
https://cephcsi.slack.com/messages/CJV6G2DFT/

You can join the slack by https://bit.ly/2MeS4KY

What we need ?

*) A volunteer for this effort :   @Madhu-1 
*) Meeting date and time : **Tuesday /  9:30 AM EST**

**Comment by humblec** [comment]
@Madhu-1 @poornimag @ShyamsundarR ...etc

**Comment by Madhu-1** [comment]
Proposed time:  **weekly once on Tuesday from 7:00 PM IST to 8:00 PM IST**

any comments or thoughts on this?

**Comment by humblec** [comment]
The proposal looks good to me. Thanks! lets kickstart it .

**Comment by Madhu-1** [comment]
@nehaberry please add relavent person if am missing any  one

**Comment by ShyamsundarR** [comment]
> Proposed time: **weekly once on Tuesday from 7:00 PM IST to 8:00 PM IST**
> 
> any comments or thoughts on this?

This is fine, where are we meeting (i.e chat/call or other means and details)? Thanks.

**Comment by Madhu-1** [comment]
@ShyamsundarR planning to meet on the slack channel. if we require audio/screen share etc will move to bluejeans (maybe in upcoming meetings)

**Comment by ShyamsundarR** [comment]
The slack channel seems invite only and I do not have one, or a way to ask for one from the landing signup page, I see this message:
"Don't have an account on this workspace yet?Contact the workspace administrator for an invitation" but do not know what next.

What are the next steps?

**Comment by Madhu-1** [comment]
@humblec can you help out with this.

**Comment by humblec** [comment]
@ShyamsundarR can you use this invite link https://join.slack.com/t/cephcsi/shared_invite/enQtNjc2NjEwMjUwODA2LWZjNzA1YjcwOGZjNjE1ODE5ZTZiOTE5OTEyY2NiM2QyZGE0MzVlZjcxNzA2MGM1MjBkNjI3MTI2NzBkZmJiODA ?

**Comment by Madhu-1** [comment]
@humblec can you update the readme on how to join ceph-csi slack channel?

**Comment by ShyamsundarR** [comment]
> @ShyamsundarR can you use this invite link https://join.slack.com/t/cephcsi/shared_invite/enQtNjc2NjEwMjUwODA2LWZjNzA1YjcwOGZjNjE1ODE5ZTZiOTE5OTEyY2NiM2QyZGE0MzVlZjcxNzA2MGM1MjBkNjI3MTI2NzBkZmJiODA ?

Worked for me, now joined the channel.

**Comment by humblec** [comment]
Thanks @ShyamsundarR for confirming.

**Comment by humblec** [comment]
[update on 16-Jul-2019]

Open issues were at "83" and we were able to close "12" issues !!! Currently it stands @ 71.
4 issues were triaged or tracked for next and upcoming releases.

**Comment by mykaul** [comment]
Do we still need this issue open?
@humblec  ?

**Comment by humblec** [comment]
> Do we still need this issue open?
> @humblec ?

hmm.. tricky to answer, we currently spent some time in a week to clear the backlog issues. However the slot is not consistent all the weeks. so give me some time, let me try to make it consistent and accordingly we can take the call.

**Comment by humblec** [comment]
@Madhu-1 @ShyamsundarR @nixpanic @Yuggupta27 @agarwal-mudit @pkalever @yati1998 I think we have to bring back this process. That said, we have a good count of issues opened here in this repo, most of them are actually solved. However the issue still remain open . 

So 2 proposals:

1) Lets kickstart bug triage call or meeting once again ( May be weekly)
2) Look at the the stale bot configuration, looks like its not working as expected.

I would like to open it up for volunteers , if no, I can setup this call.

**Comment by humblec** [comment]
@kuja53 has offered help on looking into the `stale` bot issues and its configuration..etc. Thanks :+1:
