### ISSUE TITLE
Add option for overriding kubeVersion to the helm charts

### ISSUE THREAD

**Issue by Kajot-dev** [ceph/ceph-csi#4630]
Some k8s distributions (for example OKD/Openshift) use more complex version string (for example `v1.28.2-3598+6e2789bbd58938-dirty`). Helm fails to parse it correctly and thus a v1.28.2 cluster fails a check for >= 1.25.x (selinuxMount in CSIDriver)

Please consider adding `kubeVersion` to values which would override `.Capabilities.KubeVersion.Version`

**Comment by Bengrunt** [comment]
In concur, this is error prone for those distributions!
