### ISSUE TITLE
Not able to start CI job because of no nodes

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#4649]
+ duffy client request-session pool=virt-ec2-t2-centos-8s-x86_64,quantity=1
Cannot get property 'nodes' on null object

is the current problem in centos CI [1], can we switch to `virt-ec2-t2-centos-9s-x86_64` pool which is having free resources or do we have any other alternative.

https://jenkins-ceph-csi.apps.ocp.cloud.ci.centos.org/blue/organizations/jenkins/k8s-e2e-external-storage-1.28/detail/k8s-e2e-external-storage-1.28/651/pipeline/

cc @nixpanic

**Comment by nixpanic** [comment]
The CI jobs were modified with #4650 and #4651, single jobs are working well.

Something made the Jenkins environment unstable, maybe some plugin updates caused partial wipe/reset of configuration files. The configuration has been restored, and jobs seem to be running now.
