### ISSUE TITLE
RBD-Images are not shown in the Dashbord: Failed to execute RBD [errno 19] error generating diff from snapshot None

### ISSUE THREAD

**Issue by roboticsalign** [ceph/ceph-csi#4653]
# Describe the bug #

Dear Community, 

I hope, you can guide me to solve this error or I can assist in solving a bug: RBD-Images are not shown in my Dashbord.

When accessing the dashboard page (block -> images) no images were listed and the error "Failed to execute RBD [errno 19] error generating diff from snapshot None" is shown. 
When asking for the list via cli by "rbd ls" the test-image is shown. 
There are no snapshots listed when asking for "rbd snap ls --all test".
Back to the ui: I can create and use a new image via UI, this will be shown via cli, but not in the ui.

The cluster manages several RBD, RGW and Cephfs pools successfully with ~13TiB used capacity out of ~18TiB. 

Thanks for this great piece of software!

# Environment details #

- Ceph-Cluster with 7 Debian 12 nodes and 3 Ubuntu 22.04 nodes at latest patch level.
- Cluster-Version: 18.2.2 (531c0d11a1c5d39fbfe6aa8a521f023abf3bf3e2) reef (stable).
- Error persists since Quincy.
- Orchestrator: cephadm.
- Dashboard is accessed via haproxy, but it's the same behavior when accessing it directly via ip.
- All nodes are updated and rebooted. 
- Dashboard was removed and reactivated. 

# Steps to reproduce #

I need your help to find the root cause.

# Logs #
Health status is ok. I can't find useful logs except the error message:
![image](https://github.com/ceph/ceph-csi/assets/23562360/ac5455bf-9b64-427b-b645-4f086479b975)

Problably you have an idea, where to search for further useful logs?

**Comment by Madhu-1** [comment]
@roboticsalign this is something you need to check with ceph. https://ceph.io/en/community/connect/ is the link to connect with ceph community.

**Comment by roboticsalign** [comment]
@Madhu-1 thanks for pointing me to the right community.
