### ISSUE TITLE
Add http health endpoint for ceph-csi-cephfs and ceph-csi-rbd

### ISSUE THREAD

**Issue by norbinor** [ceph/ceph-csi#4665]
Is it expected that you add http health endpoint implementation for ceph-csi-cephfs and ceph-csi-rbd, so that we can use them in K8s readiness/liveness Probes health check. In K8s deployments it would make the components more resilient against service outages or other issues. If it is expected, then when will it be possible?

**Comment by nixpanic** [comment]
This could be added, but there needs to be some definition of readiness/liveness. At what point is the Ceph-CSI driver expected to report "ready", and are there particular failure scenarios when the driver should report it is unhealthy?

/cc @ceph/ceph-csi-contributors

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/issues/1096 we already have this one that can help this one.
