### ISSUE TITLE
'luksOpen'` encrypted volumes

### ISSUE THREAD

**Issue by fevo1971** [ceph/ceph-csi#4708]
# What new functionality do you want? #

I am looking for a tool/script that derives the encryption password from `METADATA` (that's what I use as KMS)  and  `encryptionPassphrase`

# What is the value to the end user? (why is it a priority?) #

so i will be able to (manually) `luksOpen` my encrypted volumes e.g. in case of disaster recovery.
# How will we know we have a good solution? (acceptance criteria) #

any kind of help would be appicated (script, comand line tool or just a HowTo docuemntation)

**Comment by nixpanic** [comment]
I do not think there is a tool or script that can do this for you. If you write something for it, consider contributing it back to this project.

If you have the keys stored in the metadata of the RBD-image, you can find the encrypted key in the `rbd.csi.ceph.com/dek` metdata. Each RBD-image has its own key and nounce, stored as JSON.

You can decrypt that the key with the passphrase and nounce (volume id) that were used to encrypt the key. This is the function that does it:

https://github.com/ceph/ceph-csi/blob/d376271376d3912b1b313c39ea644751c9490032/internal/kms/secretskms.go#L237-L264
