### ISSUE TITLE
getVolumeRootPathCeph should detect and return ENOENT errors

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#474]
When a subvolume is deleted but before its relevant RADOS objects and keys are deleted a service fault occurs, then the next delete request is expected to garbage collect the same. This is done on errors where the image is not found in the background, but RADOS information leads us to the image (like in `newVolumeOptionsFromVolID`).

To satisfy this requirement and edge case, ENOENT errors from `getVolumeRootPathCeph` need to be detected and appropriately handled in the DeleteVolume request to only garbage collect the RADOS information stored for the same.

This is akin to returning `ErrImageNotFound` from `getImageInfo` and handling the same in DeleteVolume request in the rbd plugin code.

**Comment by Madhu-1** [comment]
@poornimag would you like to take this?

**Comment by ShyamsundarR** [comment]
Added this to the next release queue, looks like some testing has hit this path, when the provisioner pod is restarted, possibly interrupting deletions mid-way.

The test seems to be to issue ~100 PV deletes in parallel, and in between restarting the leader provisioner pod, causing an ENOENT error when looking for the image root path and failing deletion hence.

**Comment by humblec** [comment]
@joscollin can you take a look at this ?

**Comment by joscollin** [comment]
@ShyamsundarR Subvolume delete is a two step operation. The step moves/renames the subvolume to a trash directory and then purged in the background. Are you passing the [`force` option](https://github.com/ceph/ceph/blob/nautilus/src/pybind/mgr/volumes/fs/subvolume.py#L153) from your code? If so, don't do it and it would give you an `ENOENT`.

**Comment by Madhu-1** [comment]
@joscollin currently we are using force option https://github.com/ceph/ceph-csi/blob/master/pkg/cephfs/volume.go#L207

**Comment by joscollin** [comment]
@Madhu-1 Can you remove it and try? Then force would be `false` in `remove_subvolume`. Please see [this](https://github.com/ceph/ceph/blob/nautilus/src/pybind/mgr/volumes/fs/subvolume.py#L171).

**Comment by ShyamsundarR** [comment]
Please note, irrespective of force flag or not, handling image/subvolume not found errors ([like in RBD](https://github.com/ceph/ceph-csi/blob/aadce54b2f2e50a139e2188dc6625df97241ef44/pkg/rbd/controllerserver.go#L366-L383)) in the ceph-csi code is something that needs to be added.

**Comment by ShyamsundarR** [comment]
Post further discussion regarding subvolume deletion and usage of `--force` in the command ( as pointed to [here](https://github.com/ceph/ceph-csi/issues/474#issuecomment-577016917)), it is decided that we will also remove the `--force` option and detect ENOENT errors for the same routine as well, to safeguard against any other errors that force option may remove.

The `--force` option was added due to discussions [here](https://github.com/ceph/ceph-csi/pull/400#discussion_r291941625).

**Comment by joscollin** [comment]
Read the [Remove a subvolume](https://docs.ceph.com/docs/master/cephfs/fs-volumes/#fs-subvolumes) doc. It says what we have discussed: `The removal of a subvolume fails if it has snapshots, or is non-existent. ‘–force’ flag allows the non-existent subvolume remove command to succeed.`, which means `--force` doesn't actually force anything and it doesn't do a 'force remove', but it ignores the failure and allows the delete command succeed rather than throwing an exception. So you won't see an ENOENT if you pass 'force' from the CSI.
