### ISSUE TITLE
Use MGR 'rbd_support' module for long-running tasks

### ISSUE THREAD

**Issue by dillaman** [ceph/ceph-csi#477]
# Describe the feature you'd like to have #

Long-running tasks like image removal, trash image removal, and flatten should be handled via the MGR module (will backport to Mimic and later releases). This module keeps a persistent task list that can be recovered in the case of crashes and restarts.

# What is the value to the end user? (why is it a priority?) #

The CSI no longer needs to handle running long-running maintenance operations nor track redo log state. 

Volume removals can be sped up by first moving images to the trash (`rbd trash mv <image-spec>`) and then initiating a background removal (`ceph rbd task trash remove <image-id-spec>`). Similarly, flattening a cloned image can be handled in the background by scheduling it (`ceph rbd task flatten <image-spec>`).

# How will we know we have a good solution? (acceptance criteria) #

The CSI doesn't block waiting for long-running RBD operations. In the future we could even offload things like conversion between RBD block devices (w/ file systems) to CephFS subvolumes. 

# Additional context #

```
# schedule an image removal
$ ceph rbd task remove rbd/image
{"sequence": 1, "id": "09220aee-cf57-43dd-bb1b-5355c5f2a5d7", "action": "remove", "refs": {"message": "Removing image rbd/image", "pool_name": "rbd", "pool_namespace": "", "image_name": "image"}}

# attempting to re-add will just return the original task
$ ceph rbd task remove rbd/image
{"sequence": 1, "id": "09220aee-cf57-43dd-bb1b-5355c5f2a5d7", "action": "remove", "refs": {"message": "Removing image rbd/image", "pool_name": "rbd", "pool_namespace": "", "image_name": "image"}}

# show the current status of a scheduled task
$ ceph rbd task list 09220aee-cf57-43dd-bb1b-5355c5f2a5d7
{"sequence": 1, "id": "09220aee-cf57-43dd-bb1b-5355c5f2a5d7", "action": "remove", "refs": {"message": "Removing image rbd/image", "pool_name": "rbd", "pool_namespace": "", "image_name": "image"}, "in_progress": true}
```

See https://github.com/ceph/ceph/pull/29054 for initial PR

**Comment by Madhu-1** [comment]
@dillaman https://github.com/ceph/ceph-csi/pull/467  has to wait till we get this feature?

**Comment by dillaman** [comment]
> @dillaman #467 has to wait till we get this feature?

I don't think that is necessary since we can tweak the CSI to use this new background helper at a later time (when handling flatten and trash removal). If `flatten` and `trash remove` are needed right now, it will just block the CSI thread, and as long as that is OK (i.e. k8s will just time-out and retry), we should be fine.

**Comment by humblec** [comment]
>Volume removals can be sped up by first moving images to the trash (rbd trash mv <image-spec>) and then initiating a background removal (ceph rbd task trash remove <image-id-spec>). Similarly, flattening a cloned image can be handled in the background by scheduling it (ceph rbd task flatten <image-spec>).
>

I have to look into the Ceph PR in detail, however a quick question here, Isnt it a good idea to wrap these operations in a single command or "switch" option for client to consume easily? In short, "move to trash" and "async deletion later"..etc can be exposed by a single command ?

**Comment by dillaman** [comment]
> Isnt it a good idea to wrap these operations in a single command or "switch" option for client to consume easily

They are different operations, so I don't believe it makes sense to combine. Just because the CSI is going to use the "ceph rbd task trash remove" op after a "rbd trash move" op, doesn't mean that *all* users want that. Plus, adding support for "trash move" into the background async maintenance op runner breaks the abstraction that it's for long-running ops (which "trash move" is not).

**Comment by nixpanic** [comment]
@phlogistonjohn these are CephMGR commands that need some interface in go-ceph
