### ISSUE TITLE
Automatically attempt to use rbd-nbd when krbd cannot support RBD image features

### ISSUE THREAD

**Issue by dillaman** [ceph/ceph-csi#478]
# Describe the feature you'd like to have #

If an image has features enabled that are not supported by krbd, the attacher should automatically attempt to use rbd-nbd. The end user shouldn't need to know when to set the `mounter` StorageClass attribute [1]

# What is the value to the end user? (why is it a priority?) #

The implementation details (and limitations of krbd) will be hidden from the user, facilitating the use of the driver.

# How will we know we have a good solution? (acceptance criteria) #

An image with features enabled that are not supported by krbd will still be properly attached to a pod. For example, if the `journaling` feature is enabled in support of RBD mirroring.

[1] https://github.com/ceph/ceph-csi/blob/master/examples/rbd/storageclass.yaml#L35

**Comment by humblec** [comment]
@dillaman do we have list of features which are not supported or missing in krbd?

**Comment by dillaman** [comment]
> @dillaman do we have list of features which are not supported or missing in krbd?

It depends on the kernel version [1]


[1] http://docs.ceph.com/docs/master/rbd/rbd-config-ref/#rbd-features

**Comment by mcluseau** [comment]
Also, `/sys/bus/rbd/supported_features` fives access to the supported features in the system's krbd driver. It can be decoded using the list here too: https://github.com/ceph/ceph/blob/master/src/include/rbd/features.h#L4
