### ISSUE TITLE
restoreSize is missing at snapshots after ceph-csi-rbd 12.1

### ISSUE THREAD

**Issue by dragoangel** [ceph/ceph-csi#4788]
# Describe the bug #

After updating to ceph-csi-rbd 12.1 from 11.0 new snapshots missing restoreSize details.

# Environment details #

- Image/version of Ceph CSI driver : 12.1
- Helm chart version : v3.15.2
- Kernel version : 5.15.0-101-generic
- Mounter used for mounting PVC (for cephFS its `fuse` or `kernel`. for rbd its
  `krbd` or `rbd-nbd`) : krbd
- Kubernetes cluster version : v1.25.14
- Ceph cluster version : 17.2.7 quincy (stable)

# Steps to reproduce #

1. Deploy ceph-csi-rbd chart https://ceph.github.io/csi-charts ~3.12.0
2. Deploy snapshot-controller chart https://piraeus.io/helm-charts ~3.0.5
3. Create PVC
4. Create snapshot of PVC
5. Look at volumesnapshots.snapshot.storage.k8s.io and at volumesnapshotcontents.snapshot.storage.k8s.io for newly created snapshot - it will be missing restoreSize
6. Downgrade ceph-csi-rbd chart to 3.11.0 version
7. Delete snapshot and create it from scratch
8. Check volumesnapshots.snapshot.storage.k8s.io and at volumesnapshotcontents.snapshot.storage.k8s.io for newly created snapshot - both resourses will get restoreSize attribute

# Actual results #

snapshots missing restoreSize details

# Expected behavior #

snapshots must have restoreSize details that represents size of rbd image

# Logs #

unfortunetly logs are not provide any related details or errors, at least at default logs verbosity

# Additional context #

I checked ceph-csi-cephfs and this issue not reproduces there, so issue exactly in rdb realization.

**Comment by iPraveenParihar** [comment]
v3.12.0 has latest external-snapshotter v8. I see PR https://github.com/kubernetes-csi/external-snapshotter/pull/1011 related to restoreSize by @Madhu-1.

@Madhu-1 can you please take a look?

**Comment by Madhu-1** [comment]
> v3.12.0 has latest external-snapshotter v8. I see PR [kubernetes-csi/external-snapshotter#1011](https://github.com/kubernetes-csi/external-snapshotter/pull/1011) related to restoreSize by @Madhu-1.
> 
> @Madhu-1 can you please take a look?

This is a bug in cephcsi not in external-snapshotter

**Comment by dragoangel** [comment]
Hi @Madhu-1, thanks for taking onto it :)
