### ISSUE TITLE
snyk (not synk) job is failing on the release tag 

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#4824]
SYNK job is failing on the release tag https://github.com/ceph/ceph-csi/actions/runs/10738245639/job/29781429319

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/actions/runs/10738245628/job/29781429301 this job related to synk is also failing

**Comment by nixpanic** [comment]
#4797 should have fixed the auth issue, it may require backporting?

A 2nd problem is that `snyk.sarif` is missing when posting the results. I don't know where that file is supposed to come from.

What I also just noticed, is that the job contains `args: --file=Dockerfilei`, which contains a typo (added `i`).

**Comment by Madhu-1** [comment]
https://github.com/snyk/actions/blob/master/docker/README.md, if we fix the typo i think the problem will be fixed

**Comment by Madhu-1** [comment]
it looks like the auth problem is not fixed yet. let me give a try for this one and get back

**Comment by nixpanic** [comment]
> https://github.com/snyk/actions/blob/master/docker/README.md, if we fix the typo i think the problem will be fixed

Probably `deploy/cephcsi/image/Dockerfile` needs to be passed, as that is the file that is used to build the container-image.

**Comment by Madhu-1** [comment]
@Nikhil-Ladha I have assigned this issue to you!
