### ISSUE TITLE
Configurable log level for csi and sidecar in helm charts

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#4831]
Current helm charts (cephfs/rbd) doesn't provide flexibility to make the log level in helm charts configurable, we need to provide flexibility to the user to configure the log level when deploying using helm

**Comment by ShravaniVangur** [comment]
@Madhu-1 Currently `logLevel` and `sidecarLogLevel` variables exist which could be set while deploying using helm. Do the variables need to be tweaked or do we have to configure it in other ways?

**Comment by Madhu-1** [comment]
@ShravaniVangur i think i looked at the older releases not the new one, i am closing this as as we already have support for it.
