### ISSUE TITLE
Document steps for upgrading from v1.0.0 to v1.1.0 

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#484]
# Describe the bug #
Need to add a document for the changes required for upgrading v1.0.0 to v1.1.0

**Comment by kfox1111** [comment]
We concur.

**Comment by lelvisl** [comment]
any updates?

**Comment by Madhu-1** [comment]
upgrade document for v1.2.0

**Comment by lelvisl** [comment]
any updates? (2)

**Comment by lelvisl** [comment]
(it is almost december now)

**Comment by Madhu-1** [comment]
assigning to  myself to work on this

**Comment by nixpanic** [comment]
@Madhu-1 please remove this from the v2.1 project and set the right milestone (if any).

**Comment by humblec** [comment]
This is no longer valid in different aspects. closing this .
