### ISSUE TITLE
Cephfs "fs subvolumegroup create"  no valid command found

### ISSUE THREAD

**Issue by mkey-cdx** [ceph/ceph-csi#490]
# Describe the bug #

When creating a PVC, it remains in Pending state. csi-cephfsplugin-provisioner-0/csi-provisioner logs shows an 'command not found' error during volume creation.
The same behavior happens when running the fs subvolumegroup create command from within the container.

Note that we have a ceph cluster with multiple filesystems feature enabled. Can this be related?
I found this comment in the code: https://github.com/ceph/ceph-csi/blob/master/pkg/cephfs/volume.go#L82

# Environment details #

- Image/version of Ceph CSI driver: 1.1.0
- Ceph cluster version: 14.2.2
- helm chart version: N/A
- Kubernetes cluster version: v1.14.2
- Logs
```
GRPC error: rpc error: code = Internal desc = an error occurred while running (67781) ceph [fs subvolumegroup create cephfs-fast csi --mode 777 --pool_layout cephfs-fast_data -m 10.50.0.1:6789,10.50.0.3:6789,10.50.0.4:6789 -c /etc/ceph/ceph.conf -n client.admin --key=***stripped***]: exit status 22: 2019-07-23 07:59:24.045 7f7a4ab3e700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory

2019-07-23 08:25:44.198 7faac255c700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-07-23 08:25:44.198 7faac255c700 -1 AuthRegistry(0x7faabc063b98) no keyring found at /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,, disabling cephx
2019-07-23 08:25:44.274 7faac255c700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-07-23 08:25:44.274 7faac255c700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-07-23 08:25:44.274 7faac255c700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-07-23 08:25:44.322 7faac255c700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-07-23 08:25:44.322 7faac255c700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-07-23 08:25:44.322 7faac255c700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2019-07-23 08:25:44.322 7faac255c700 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
no valid command found; 10 closest matches:
fs status {<fs>}
fs dump {<int[0-]>}
fs new <fs_name> <metadata> <data> {--force} {--allow-dangerous-metadata-overlay}
fs ls
fs get <fs_name>
fs rm <fs_name> {--yes-i-really-mean-it}
fs reset <fs_name> {--yes-i-really-mean-it}
fs set <fs_name> max_mds|max_file_size|allow_new_snaps|inline_data|cluster_down|allow_dirfrags|balancer|standby_count_wanted|session_timeout|session_autoclose|down|joinable|min_compat_client <val> {<confirm>}
fs flag set enable_multiple <val> {--yes-i-really-mean-it}
fs authorize <filesystem> <entity> <caps> [<caps>...]
Error EINVAL: invalid command
```

# Steps to reproduce #

1. Setup and deploy ceph-csi/cephfs provisionner
2. Create a new PVC

# Actual results #

PVC is stuck in Pending state.
csi-provisioner container logs shows 'EINVAL: invalid command' error on ceph fs subvolumegroup create execution.

# Expected behavior #

PVC is provisioned and in Bound state.

# Additional context #

This is a bare-metal Kubernetes/Ceph deployment.
Multiple filesystems feature is enabled on ceph cluster and two ceph fs exist.

**Comment by Madhu-1** [comment]
@mkey-cdx can you point me to the dockerhub image you are using. this functionality is available in `ceph/ceph:v14.2.2-20190722` image

**Comment by Madhu-1** [comment]
@ajarr  ceph  fs commands are available in 1.14.2?
 btw the ceph is downloaded from `https://download.ceph.com/debian-nautilus/`

**Comment by humblec** [comment]
@poornimag

**Comment by mkey-cdx** [comment]
Ceph version we use from https://download.ceph.com/debian-nautilus/:
`ceph version 14.2.2 (4f8fa0a0024755aae7d95567c63f11d6862d55be) nautilus (stable)`

**Comment by wangxiao86** [comment]
How is it compatible with the ceph previous versions?  we use ceph:v12.2.5 which does not support “ceph fs subvolumegroup create”,  it prompts the same error.

**Comment by Madhu-1** [comment]
@batrick  @ajarr will this be backported to other releases?

**Comment by ajarr** [comment]
@Madhu-1 , I don't see ceph-mgr fs volumes being backported to luminous or mimic. The CephFS team had discussed this with the CSI team. For CSI v 1.1.0 to work you'd need nautilus. If this not documented, we need to document this ASAP.

**Comment by Madhu-1** [comment]
@ajarr its already documented here https://github.com/ceph/ceph-csi#ceph-csi-features-and-available-versions, but wanted to get confirmation is it getting backported

**Comment by ajarr** [comment]
> Ceph version we use from https://download.ceph.com/debian-nautilus/:
> `ceph version 14.2.2 (4f8fa0a0024755aae7d95567c63f11d6862d55be) nautilus (stable)`

@mkey-cdx , can you please check the version of ceph-mgr?
```
$ ceph-mgr --version
```
The commands are definitely in 14.2.2 version of Ceph. As you can see in v14.2.2's source code,
https://github.com/ceph/ceph/blob/v14.2.2/src/pybind/mgr/volumes/module.py#L47

Also, please make this change, and test,
https://github.com/ceph/ceph-csi/issues/486#issuecomment-514577205

This seemed to have worked for others with Ceph v14.2.2 non-rook deployment,
https://github.com/ceph/ceph-csi/issues/486#issuecomment-514591963

Thanks!

**Comment by ajarr** [comment]
> @ajarr its already documented here https://github.com/ceph/ceph-csi#ceph-csi-features-and-available-versions, but wanted to get confirmation is it getting backported

Cool. Thanks, @Madhu-1

**Comment by mkey-cdx** [comment]
@ajarr ceph mgr version is also 
`ceph version 14.2.2 (4f8fa0a0024755aae7d95567c63f11d6862d55be) nautilus (stable)`
I made the change ([#486 (comment)](https://github.com/ceph/ceph-csi/issues/486)) in the ceph-mgr node and could get a much more comprehensible log error:
```
Error ENOTSUP: Module 'volumes' is not enabled (required by command 'fs subvolumegroup create'): use `ceph mgr module enable volumes` to enable it
```
After enabling volumes module I could get PVC provisioned correctly :)
Note that I tested removing [#486 (comment)](https://github.com/ceph/ceph-csi/issues/486), restarting ceph-mgr and did recreated the PVC successfully. So it appears that enabling volumes module was everything I needed eventually.

**Comment by ajarr** [comment]
Great! Thanks @mkey-cdx. I'm working on documenting the ceph-mgr config setting for 14.2.2 tracked by #486.

Looks like this issue is resolved. Please feel free to open this issue if you think otherwise.
