### ISSUE TITLE
Intergration with https://coveralls.io/ for coverage

### ISSUE THREAD

**Issue by raghavendra-talur** [ceph/ceph-csi#491]
# Describe the feature you'd like to have #

What new functionality do you want?
Have a link to https://coveralls.io/ and a badge in readme for test coverage in the project.

# What is the value to the end user? (why is it a priority?) #
Having a coverage report will enable new developers to contribute easy tests. The end user in this case is developer.

**Comment by Madhu-1** [comment]
@raghavendra-talur is this something related to UT?

**Comment by Madhu-1** [comment]
As we dont have much UT coverage and we have more of Functional test coverage am closing this one for now, please reopen later if requried.
