### ISSUE TITLE
Use ceph image with a more specific tag that includes the date or commit ID

### ISSUE THREAD

**Issue by ajarr** [ceph/ceph-csi#493]
Currently, ceph csi image is built using ceph image with tag, v14.2. We can use a ceph image with tag that is more specific, e.g., with the date the image was created, v14.2.2-20190722, or with the HEAD commit ID. Rook does this currently.

**Comment by Madhu-1** [comment]
@ajarr how this is helpful for the end user?

**Comment by ajarr** [comment]
I'm not sure who you're referring to as end user?

IMO, this is good practice for the person who builds the CSI image that he uses a image with a more detailed tag. Unless otherwise you want the base Ceph image to always be the latest 14.2.x ? What if there was a bug in latest 14.2.x stable that affects Ceph CSI?

**Comment by Madhu-1** [comment]
the commit tag added to the image in this PR https://github.com/ceph/ceph-csi/pull/469. from this, we can check from which tag the image is built.

**Comment by ajarr** [comment]
PR #469 helps check the tag of Ceph-CSI release. I'm talking about the base Ceph image.

**Comment by Madhu-1** [comment]
@ajarr if you do docket inspect on the image you will see ceph version 

```
docker inspect quay.io/cephcsi/cephcsi:canary
[
    {
        "Id": "sha256:afb0079dd922597a926b8692af128455e1d33bf0c41244def8ce59f3636be7f0",
        "RepoTags": [
            "quay.io/cephcsi/cephcsi:canary"
        ],
        "RepoDigests": [
            "madhupr001/cephcsi@sha256:c16e6807a91102645840afbcf2311126610bb72683c8f79460d9fe8019a79e1a"
        ],
        "Parent": "sha256:91bd0b5601734afff652662f400e7176f0a106c6c29a22d727994abb4341bf0e",
        "Comment": "",
        "Created": "2019-07-24T11:35:45.79180354Z",
        "Container": "5b5c2db9e9b7de7aecb03da8a300b7aa02f20578123e0c032249c78919d40f03",
        "ContainerConfig": {
            "Hostname": "5b5c2db9e9b7",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "CEPH_VERSION=nautilus",
                "CEPH_POINT_RELEASE=-14.2.1",
                "CSIBIN=/usr/local/bin/cephcsi"
            ],
```

is this enough?

**Comment by ajarr** [comment]
@Madhu-1 , let's suppose Ceph 14.2.3 has a bug that affects Ceph-CSI. The travis CI would start failing once the new image is pushed with tag v14.2 in ceph/ceph repo. Can you not avoid this with more detailed tags?

**Comment by Madhu-1** [comment]
@ajarr you are taking from client library side right? this  cannot be avoided as the base ceph-csi image  as `FROM ceph/ceph:v14.2` i assume this is a stable image

**Comment by ajarr** [comment]
> @ajarr you are taking from client library side right? this cannot be avoided as the base ceph-csi image as `FROM ceph/ceph:v14.2` i assume this is a stable image

Yes, client side. And the base ceph csi image cannot be changed to `FROM ceph/ceph:v14.2.2-20190722`? v14.2.x might have bugs, right?

**Comment by nixpanic** [comment]
the `ceph/ceph:v14.2` tag refers to the latest image build with Ceph 14.2.x. We should trust the Ceph maintainers to not introduce regressions in the 14.2.x stable updates. We **do** want updates of the image, specially for security and bugfixes in the packages that are provided by the OS.

I do not see a need for fixing the base image for Ceph-CSI to a very particular version of the Ceph image. It would cause more maintenance work (tracking Ceph image releases and updating `FROM`) than it is worth.

@ajarr Can this be closed now?

**Comment by ajarr** [comment]
> the `ceph/ceph:v14.2` tag refers to the latest image build with Ceph 14.2.x. We should trust the Ceph maintainers to not introduce regressions in the 14.2.x stable updates. We **do** want updates of the image, specially for security and bugfixes in the packages that are provided by the OS.
> 

There have been Ceph stable releases with regressions in the past. In that case wouldn't automatic updates be an issue?

> I do not see a need for fixing the base image for Ceph-CSI to a very particular version of the Ceph image. It would cause more maintenance work (tracking Ceph image releases and updating `FROM`) than it is worth.
> 

Ceph stable releases don't happen too often. I'm not sure if it's too much maintenance work.
Rook does this currently, https://github.com/rook/rook/blob/master/images/ceph/Makefile#L20

> @ajarr Can this be closed now?

**Comment by nixpanic** [comment]
On Tue, Nov 19, 2019 at 05:22:04AM -0800, Ramana Raja wrote:
> > the `ceph/ceph:v14.2` tag refers to the latest image build with Ceph 14.2.x. We should trust the Ceph maintainers to not introduce regressions in the 14.2.x stable updates. We **do** want updates of the image, specially for security and bugfixes in the packages that are provided by the OS.
> > 
> 
> There have been Ceph stable releases with regressions in the past. In that case wouldn't automatic updates be an issue?

Yes, that could be a problem. But this should almost never happen. In
case of regressions we can always introduce a temporary workaround.

> > I do not see a need for fixing the base image for Ceph-CSI to a very particular version of the Ceph image. It would cause more maintenance work (tracking Ceph image releases and updating `FROM`) than it is worth.
> > 
> 
> Ceph stable releases don't happen too often. I'm not sure if it's too much maintenance work.
> Rook does this currently, https://github.com/rook/rook/blob/master/images/ceph/Makefile#L20

I do not know what advantage there could be for Rook. Maybe @leseb can
explain the reason. Otherwise they also might want to move to
ceph/ceph:v14.2 so that they do not need to update their Makefile everye
time.

**Comment by ShyamsundarR** [comment]
> the `ceph/ceph:v14.2` tag refers to the latest image build with Ceph 14.2.x. We should trust the Ceph maintainers to not introduce regressions in the 14.2.x stable updates. We **do** want updates of the image, specially for security and bugfixes in the packages that are provided by the OS.
> 
> I do not see a need for fixing the base image for Ceph-CSI to a very particular version of the Ceph image. It would cause more maintenance work (tracking Ceph image releases and updating `FROM`) than it is worth.

Please see comment dropped [here](https://github.com/ceph/ceph-csi/pull/573#discussion_r348008354), I am **unsure** if the base image is auto updated and reduces any work in terms of maintenance and rebuilds of CSI image when this changes.
