### ISSUE TITLE
needed step by step instructions of external cephfs cluster with pod.

### ISSUE THREAD

**Issue by goodidea-kp** [ceph/ceph-csi#495]
# Describe the feature you'd like to have #

better instruction on how to integrate external cephfs cluster with pod without using 3rd parties as rook etc

# What is the value to the end user? (why is it a priority?) #

I spent 3 days already trying different options and still not there. It will help save time

# How will we know we have a good solution? (acceptance criteria) #

document with bare minimum actions (without compilation with "GO" etc) and proof my pod can see the same data as my mount from Ubuntu

**Comment by Madhu-1** [comment]
@goodidea-kp can you tell us what you have tried and what is the current state?

**Comment by Madhu-1** [comment]
closing this one as we have doc for cephfs deployment https://github.com/ceph/ceph-csi/blob/master/docs/deploy-cephfs.md, if something is missing reopen this one
