### ISSUE TITLE
cephfs: do not set subvolumegroup's pool layout

### ISSUE THREAD

**Issue by ajarr** [ceph/ceph-csi#499]
Currently, while creating CSI volumes, the subvolume group `csi` the pool layout is set based on the pool setting in the storageclass.
https://github.com/ceph/ceph-csi/commit/32ea550e3#diff-33a13f3231aad3a3f5ec45f308007699R78
The storage class's pool setting is meant to change the pool layout of CSI volumes/CephFS subvolumes and not that of the `csi` subvolume group, which may contain subvolumes of different storage class types. The `csi` subvolume group's pool layout should not be set. It should just be the default. Instead, set the pool layout of the FS subvolume within the subvolume group.

Initially Reported by @ShyamsundarR

**Comment by humblec** [comment]
@poornimag

**Comment by ajarr** [comment]
@humblec , can I get the permissions to just set the labels, and assignee?

**Comment by humblec** [comment]
> @humblec , can I get the permissions to just set the labels, and assignee?

You are in!! Please feel free to send PRs too!

**Comment by ajarr** [comment]
> Please feel free to send PRs too! :)

ah! ;-)  I'll try.

FYI, I'm creating issues so that upstream development effort can be better tracked in the agile model.
