### ISSUE TITLE
use bot to merge the PR instead of mergify

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#505]
# Describe the bug #
The issue with mergify is if the committer pushes the new changes after having 2 approvals if tests are passed mergify will merge the PR. this could be an issue if you are not monitoring the PR. we need a bot to remove the approval if there is a new commit in  PR.

**Comment by humblec** [comment]
Indeed, I was about to file this issue !! Thanks for filing it we need a bot integration.

**Comment by nixpanic** [comment]
Mergify supports dropping approval status when a PR is updated. See the [documentation for dismiss-reviews](https://doc.mergify.io/actions.html#dismiss-reviews).
