### ISSUE TITLE
why ceph-provisioner deployed statefulset replicas is one not multipl replicas?

### ISSUE THREAD

**Issue by jianglingxia** [ceph/ceph-csi#524]
# Describe the feature you'd like to have #
why ceph fs or rbd plugin that deployed statefulset,the replicas is one,not 2 or 3?
if the sts down only k8s to let it run agian?
What new functionality do you want?
or the replicas are 2 or 3 cause what problem?

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-cephfsplugin-provisioner
spec:
  selector:
    matchLabels:
      app: csi-cephfsplugin-provisioner
  serviceName: "csi-cephfsplugin-provisioner"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-cephfsplugin-provisioner
    spec:
serviceAccount: cephfs-csi-provisioner
# What is the value to the end user? (why is it a priority?) #

How would the end user gain value from having this feature?

# How will we know we have a good solution? (acceptance criteria) #

Add a list of criteria that should be met for this feature to be useful

# Additional context #

**Comment by Madhu-1** [comment]
@jianglingxia if you are looking for more than one provisioner running consider using `1.14+`  https://github.com/ceph/ceph-csi/blob/master/docs/deploy-rbd.md#deployment-with-kubernetes templates, leader election is only supported in kube1.14+ higher version

**Comment by jianglingxia** [comment]
thanks for your reply,you means that the k8s version is v1.13 can not  use cephfs template v1.14?
another problem that the v1.14 has the lead election function can Ensuring data consistency ？thanks

**Comment by Madhu-1** [comment]
@jianglingxia yes with leader election only one provisioner will be processing your request with lock held.

you cannot use 1.14 templates with 1.13

**Comment by jianglingxia** [comment]
now my project decide use the k8s v1.13,if so only use v1.13 template,i want to know that use v1.13 template that the replicas is one ,the way have some problem? or occure some problem?

**Comment by Madhu-1** [comment]
for more than one replica we will end up in a situation where the same request will be provisioned by multiple provisioners, this will be fixed with leader election but you need Kube 1.14+ for that one.

**Comment by jianglingxia** [comment]
yeah,i mean that use one replica provisioner there occure some problem when use csi create delete volume?

**Comment by Madhu-1** [comment]
yes it will be a problem for create/delete volume and snapshot also

**Comment by jianglingxia** [comment]
ok,really thanks maybe occure problem only let k8s restart the pod，
another problem that the cephfs can resize volume ？or only ceph rbd can resize it?

**Comment by Madhu-1** [comment]
currently, both cephfs and rbd  doesn't  support resize

**Comment by Madhu-1** [comment]
closing this one
