### ISSUE TITLE
Add E2E for helm chats

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#526]
# Describe the bug #
currently, we don't have test support to test helm chats,  this needs manual testing, we need to add E2E  to deploy ceph-csi using helm chats

**Comment by wilmardo** [comment]
@Madhu-1 @umangachapagain

Might be cool to look into `ct`:

https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md

This could replace the functionality introduced in #556
