### ISSUE TITLE
[RFE] cephfs: storageclass should create and assign different pool or subpath for each pvc

### ISSUE THREAD

**Issue by nak3** [ceph/ceph-csi#53]
Current behavior of storageclass for cephfs is same with static
PV. Even if we create different PVCs, storageclass always assigns same
pool and same path like static PV.

I think that ceph-csi should create specific directory based on UUID
of PVC like [external-storage](https://github.com/kubernetes-incubator/external-storage/tree/master/ceph/cephfs)'s `/<"claimRoot" in StorageClass>/kubernetes/kubernetes-dynamic-pvc-<UUID>`.

It it possible to accept such change in this project?

**Comment by gman0** [comment]
Ok so how it's done now is for each `CreateVolume` request, a new directory is created in `/csi-volumes/<Generated UUID>` on Ceph's filesystem. I agree that the `/csi-volumes` part could be configurable. As for PVC UUIDs, those can't be accessed from inside CSI.

**Comment by gman0** [comment]
@nak3 Yes, exactly as you said :) `provisionVolume: false` will use an existing CephFS volume (this requires `rootPath` parameter with an absolute path to the volume), `provisionVolume: true` creates a new volume.

**Comment by gman0** [comment]
If you don't have any further questions I'll close this ticket now.

**Comment by niscinfo** [comment]
Hello all, 

Sorry I just found this old issue, that can maybe solve my current problem. 
I'm trying to use an external CephFS where I'm not admin on whole. I have write access on a certain /files/mypath
(the main cephfs is on /files). 

If I create a static PV, I can write directly to /file/mypath/. (using userID in ceph-csi secret). 
But what I'd like is to have a real storageClass behaviour : a PVC creates a PV /files/mypath/pvc-<uuid> 

You are talking about this option : "provisionVolume: false" (+ rootPath: /files/mypath ??) where should I put it ? 

Note : I'm using Helm chart ceph-csi-cephfs 3.7.2and it's not documented. 

Thanks in advance.
