### ISSUE TITLE
cephfs: optimize getVolumeRootPathCeph

### ISSUE THREAD

**Issue by ajarr** [ceph/ceph-csi#539]
For every volume delete/mount, the CephFS CSI driver uses a getVolumeRootPathCeph function to determine the CSI volume's RootPath. Internally, the getVolumeRootPathCeph function issues a Ceph command (`ceph fs subvolume getpath`) to get the path of the FS subvolume , which serves as the CSI volume.

We can optimize the getVolumeRootPathCeph function, by not calling the `fs subvolume getpath` command every time, and instead construct it from subvolume's base path, `<basepath>/<csi-volume-ID>`. The subvolume's base path can be determined by calling `ceph fs subvolumegroup getpath` command once during the lifetime of the CephFS CSI driver container.

The `ceph fs subvolumegroup getpath` command is available in latest nautilus branch, and will be available in the next nautilus stable release, Ceph v14.2.3

Originally identified by @ShyamsundarR .
See, https://github.com/ceph/ceph-csi/pull/400#discussion_r299260083

**Comment by ajarr** [comment]
@ShyamsundarR , does this issue look OK? Please edit the description if needed.

**Comment by ShyamsundarR** [comment]
Looks good, thanks for keeping track of the same.

Implementation note: should consider possibility of different fsNames/clusters that may use the same instance of the plugin, and build a cache based on the same.

**Comment by Madhu-1** [comment]
@Yuggupta27 can you please take a look at it.

**Comment by Madhu-1** [comment]
This cannot be implemented as subvolume path is dynamic(with subvolume versioning) and cannot be constructed. more info can be found on  https://github.com/rook/rook/issues/5471

@ajarr @ShyamsundarR am I missing something or this can be closed?

**Comment by ShyamsundarR** [comment]
> This cannot be implemented as subvolume path is dynamic(with subvolume versioning) and cannot be constructed. more info can be found on [rook/rook#5471](https://github.com/rook/rook/issues/5471)
> 
> @ajarr @ShyamsundarR am I missing something or this can be closed?

Agreed, the subdirectory naming is no longer unique for CSI plugin to construct the same.
