### ISSUE TITLE
cephfs: use kernel client as the default mounter instead of FUSE client

### ISSUE THREAD

**Issue by ajarr** [ceph/ceph-csi#546]
Discussed with CephFS developers @batrick and @jtlayton. They recommend switching the default FS mounter to kernel client [1] as it has much better performance than the FUSE client. FS kernel clients >= 4.17 support quotas and snapshots required to support CSI features.

For users with kernels clients < 4.17, they can switch to using fuse mounter by setting the `mounter` option in the storage class.

[1] https://github.com/ceph/ceph-csi/blob/release-v1.1.0/pkg/cephfs/driver.go#L112

**Comment by ajarr** [comment]
Also as per @ShyamsundarR ,
"From a CSI operations standpoint, kernel CephFS would be preferred as this retains the mount even when the CSI nodeplugin restarts. Thus providing smoother upgrade/recovery of the plugin on such cases, rather than having to drain a node of pods and then upgrade the nodeplugin"

**Comment by humblec** [comment]
@ajarr @poornimag can you please check any functionalty break with this change in CSI pov ?

**Comment by ajarr** [comment]
We'll have to do a kernel version check. If it's >= 4.17, then use kernel client as the default mounter, else use FUSE client. When the user explicitly mentions the mounter as kernel and uses a kernel version < 4.17, we'll have to error out with a useful message.

**Comment by ajarr** [comment]
https://github.com/ceph/ceph-csi/pull/571

**Comment by Madhu-1** [comment]
Fixed by #571

**Comment by andrewsali** [comment]
Is the snapshot feature fully supported by the kernel driver?  It seems there can be issues if a larger amount of snapshots are created: https://tracker.ceph.com/issues/21420

**Comment by Madhu-1** [comment]
you cannot have more than 400 snapshots for cephfs more info on https://github.com/ceph/ceph-csi/issues/1133
