### ISSUE TITLE
Handling CLI commands that interact with RADOS

### ISSUE THREAD

**Issue by idryomov** [ceph/ceph-csi#553]
(This might be obvious, feel free to close...)

I'm spawning this issue from https://github.com/ceph/ceph-csi/issues/520 to emphasise that any CLI command that interacts with RADOS, whether directly (such as "rbd create", "rbd ls", etc) or indirectly through the kernel (such as "rbd map", "rbd unmap", "mount", "umount") can take a long time and, in extreme cases, defeat the internal timeout (if present), because such a timeout is usually imposed on one of the steps of the operation (e.g. individual OSD request, poll() call, etc) as opposed to the entire operation.  If there are places in the plugin that expect a particular CLI command that interacts with RADOS to take no longer than X and/or places that interrupt/kill such commands without performing a cleanup, they are likely to break under load.

**Comment by Madhu-1** [comment]
some discussion regarding the same issue

https://github.com/ceph/ceph-csi/pull/194
https://github.com/ceph/ceph-csi/issues/140

**Comment by humblec** [comment]
@idryomov we have addressed RBD execution part to a great extent by the GO Ceph bindings. It has also gone through the some good amount of scale testing. CephFS improvements are on going as well and tracked under other PRs and issues. I am closing this issue for now and we could reopen it if we think there is something left which is handled in other PRs or issues.

**Comment by Madhu-1** [comment]
note:- rbd map and rbd unmap is done mount, umount with CLI, not with go-ceph

we may still face the issue and leave stale rbd maps or mounts if something timeouts
