### ISSUE TITLE
Cross (ceph-csi) storage-class clone support 

### ISSUE THREAD

**Issue by mmgaggle** [ceph/ceph-csi#560]
# Describe the feature you'd like to have #

Ability to clone volumes between Ceph-CSI managed storage-classes.

# What is the value to the end user? (why is it a priority?) #

A rook-ceph cluster may have pools with multiple device classes, or pools with different failure-domain rules and may want to transition a PVC to another. For example one may want to snapshot a PVC from rbd-ssd storage class, clone it to rbd-hdd, and delete the snapshot on the more expensive storage class. Another example would be to take a snapshot of an image on a storage class that has lower failure-domain tolerance (standard-rbd), and clone it to a storage class that has higher failure-domain tolerance (regional-rbd).

# How will we know we have a good solution? (acceptance criteria) #

A user is able to take a snapshot of a PVC that was created with one Ceph-CSI storage class, and then clone it to a PVC that is being created using another Ceph-CSI storage class.

# Additional context #

We can model after the behavior that was implemented in OpenStack Nova / Cinder / Glance, where RBD images were cloned across disparate pools.

https://www.sebastien-han.fr/blog/2015/10/05/openstack-nova-snapshots-on-ceph-rbd/

**Comment by dillaman** [comment]
@mmgaggle FYI -- there is a goal for RBD-backed PVs/snaphots to hide all Ceph implementation details. To support that, creating a CSI snapshot will actually create a new RBD clone image -- and will allow the parent PV to be deleted while it's still in-use by a snapshot. We would definitely want to support creating CSI PVs/snapshots across pools (via RBD clones w/ optional flattening) and just make it work in the background.

**Comment by nixpanic** [comment]
To me, the requested functionality sounds very much like a backup & restore procedure, within the same Kubernetes cluster.

**Comment by chenxu1990** [comment]
I do not find any interface about clone or restore pv in csi spec. Do we should implement this function by refactoring the CreateSnapshot inferface ? But how can kubernetes pass the target pool/name parameters to csi? To my understand csi generate these values from volumeID.   @nixpanic

**Comment by Madhu-1** [comment]
external-provisioner has to support it first. nothing needs to be done in cephcsi as of now.

**Comment by nixpanic** [comment]
Until more feature rich clone or snapshot/restore is available, this can be achieved by using a DataVolume to encapsulate a PVC and have [the Containerized-Data-Importer](https://github.com/kubevirt/containerized-data-importer#clone-another-pvc) do the cloning across namespaces.
