### ISSUE TITLE
Do not remove the /etc/yum.repos.d/ceph-iscsi.repo file

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#563]
# Describe the bug #

Currently #551 removed the `ceph-iscsi.repo` file, which should not be needed. However the yum repositories in the file are broken and can not be used. Disabling the repositories would have been nicer, but the end result is pretty much the same (unable to update ceph iscsi components).

# Actual results #

`yum -y update` fails due to several cehp-iscsi repositories.

# Expected behavior #

`yum -y update` should just work.

# Additional context #

This can be resolved once ceph/ceph-container#1453 has been addressed.

**Comment by Madhu-1** [comment]
@nixpanic closing this as we removed the workaround in the docker image, please feel free to reopen if it's still valid
