### ISSUE TITLE
helm chart config

### ISSUE THREAD

**Issue by kfox1111** [ceph/ceph-csi#565]
The new chart has a hardcoded config of: []. There needs to be a way for the user to specify the config, as it is not good for a user to manually edit a file that helm manages.

I think this can be easily acomplished by changing

https://github.com/ceph/ceph-csi/blob/release-v1.1.0/deploy/rbd/helm/templates/csiplugin-configmap.yaml to instead of:
```
data:
  config.json: |-
    []
```
do:
```
data:
  config.json: |-
{{ toJson .Values.config | indent 4 }}
```

and add to values.yaml:
```
config:
  []
```

**Comment by wilmardo** [comment]
I will pick this up, hopefully tomorrow also implementing:
https://github.com/ceph/ceph-csi/pull/555#discussion_r314618704

**Comment by Madhu-1** [comment]
awesome :+1: 
/assign @wilmardo
