### ISSUE TITLE
cephfs create volume failed of subvolumegroup

### ISSUE THREAD

**Issue by jianglingxia** [ceph/ceph-csi#574]
# Describe the bug #
i use the master branch in ceph v1.12,create volume failed by subvolumegroup

I0824 07:44:53.930346       1 controllerserver-default.go:60] Using default ControllerGetCapabilities
I0824 07:44:53.930354       1 log.go:44] ID: 9 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}}]}
I0824 07:44:54.682204       1 util.go:47] cephfs: EXEC ceph [-m 178.178.178.189:1091,178.178.178.19:1091,178.178.178.188:1091 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs ls --format=json]
I0824 07:45:05.895823       1 fsjournal.go:135] Generated Volume ID (0001-0024-952dc2bb-afed-45e3-844d-c2746c066b20-0000000000000001-168259aa-c643-11e9-bbb9-fa163eb49565) and subvolume name (csi-vol-168259aa-c643-11e9-bbb9-fa163eb49565) for request name (pvc-654d2916-c56b-11e9-a55e-fa163e3dc6af)
I0824 07:45:05.895938       1 util.go:47] cephfs: EXEC ceph [fs subvolumegroup create cephfs csi -m 178.178.178.189:1091,178.178.178.19:1091,178.178.178.188:1091 -c /etc/ceph/ceph.conf -n client.admin --keyfile=***stripped***]
E0824 07:45:06.396305       1 volume.go:91] failed to create subvolume group csi, for the vol csi-vol-168259aa-c643-11e9-bbb9-fa163eb49565(an error occurred while running (159) ceph [fs subvolumegroup create cephfs csi -m 178.178.178.189:1091,178.178.178.19:1091,178.178.178.188:1091 -c /etc/ceph/ceph.conf -n client.admin --keyfile=***stripped***]: exit status 22: 2019-08-24 07:45:06.083 7fc29d2ff700 -1 --2- 178.178.178.222:0/909849564 >> v2:178.178.178.19:1091/0 conn(0x7fc29815a6f0 0x7fc29815cbf0 unknown :-1 s=BANNER_CONNECTING pgs=0 cs=0 l=0 rx=0 tx=0)._handle_peer_banner peer v2:178.178.178.19:1091/0 is using msgr V1 protocol
2019-08-24 07:45:06.126 7fc297fff700 -1 --2- 178.178.178.222:0/905376040 >> v2:178.178.178.19:1091/0 conn(0x7fc2980b7de0 0x7fc2980ba290 unknown :-1 s=BANNER_CONNECTING pgs=0 cs=0 l=1 rx=0 tx=0)._handle_peer_banner peer v2:178.178.178.19:1091/0 is using msgr V1 protocol
no valid command found; 10 closest matches:
fs set-default <fs_name>
fs add_data_pool <fs_name> <pool>
fs rm_data_pool <fs_name> <pool>
fs set <fs_name> max_mds|max_file_size|allow_new_snaps|inline_data|cluster_down|allow_multimds|allow_dirfrags|balancer|standby_count_wanted <val> {<confirm>}
fs flag set enable_multiple <val> {--yes-i-really-mean-it}
fs ls
fs get <fs_name>
fs rm <fs_name> {--yes-i-really-mean-it}
fs reset <fs_name> {--yes-i-really-mean-it}
fs new <fs_name> <metadata> <data> {--force} {--allow-dangerous-metadata-overlay}
Error EINVAL: invalid command
)
E0824 07:45:06.396337       1 controllerserver.go:56] failed to create volume pvc-654d2916-c56b-11e9-a55e-fa163e3dc6af: an error occurred while running (159) ceph [fs subvolumegroup create cephfs csi -m 178.178.178.189:1091,178.178.178.19:1091,178.178.178.188:1091 -c /etc/ceph/ceph.conf -n client.admin --keyfile=***stripped***]: exit status 22: 2019-08-24 07:45:06.083 7fc29d2ff700 -1 --2- 178.178.178.222:0/909849564 >> v2:178.178.178.19:1091/0 conn(0x7fc29815a6f0 0x7fc29815cbf0 unknown :-1 s=BANNER_CONNECTING pgs=0 cs=0 l=0 rx=0 tx=0)._handle_peer_banner peer v2:178.178.178.19:1091/0 is using msgr V1 protocol
2019-08-24 07:45:06.126 7fc297fff700 -1 --2- 178.178.178.222:0/905376040 >> v2:178.178.178.19:1091/0 conn(0x7fc2980b7de0 0x7fc2980ba290 unknown :-1 s=BANNER_CONNECTING pgs=0 cs=0 l=1 rx=0 tx=0)._handle_peer_banner peer v2:178.178.178.19:1091/0 is using msgr V1 protocol

# Environment details #
k8s v1.13 csi driver master branch 
- Image/version of Ceph CSI driver
- helm chart version
- Kubernetes cluster version
- Logs

# Steps to reproduce #

1. Setup details: '...'
1. Deployment to trigger the issue '....'
1. See error

# Actual results #

Describe what happened

# Expected behavior #

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by jianglingxia** [comment]
@Madhu-1 
the question maybe that my ceph version is v1.12 and do not support the subvolumegroup command

but on july when i use master branch the create volume function do not have the function,so how can i modify the code in master branch? do not use the subvolumegroup command?
is the pr:https://github.com/ceph/ceph-csi/pull/400 merged reason?

**Comment by humblec** [comment]
@jianglingxia whats your Ceph Cluster version?

**Comment by Madhu-1** [comment]
@jianglingxia check ceph supported version for cephfs here https://github.com/ceph/ceph-csi#ceph-csi-features-and-available-versions

**Comment by jianglingxia** [comment]
yeah,my ceph version is v12 not v14,but if let csi driver support the ceph version,can i modify the code that delete the subvolumegrop?

**Comment by Madhu-1** [comment]
why modify code to delete subvolume group?

**Comment by jianglingxia** [comment]
because my ceph version now only v12,v14 not commercial until next year,so now use v12 ceph version

**Comment by Madhu-1** [comment]
okay I can't comment on the ceph commercial release, you can modify the code and use it but there won't be any migration supported in cephcsi

@humblec can give more info on this.

**Comment by jianglingxia** [comment]
can you help me with how many pr and what the pr is i need modify with the fssubvolumegroup?
thanks i only found the https://github.com/ceph/ceph-csi/pull/400 pr

**Comment by Madhu-1** [comment]
yes #400 will help you

**Comment by Madhu-1** [comment]
@mcronce its supported in 14.2.2 version

**Comment by jianglingxia** [comment]
@Madhu-1 i found the subvolume function not only the pr #400,many code place have the subvolume,i do not know how to modify the code...can helo me with it?thanks very much

**Comment by Madhu-1** [comment]
closing this as not an issue
