### ISSUE TITLE
shadow MountPropagation doesn't seem to work

### ISSUE THREAD

**Issue by clkao** [ceph/ceph-csi#58]
`deploy/cephfs/kubernetes/cephfsplugin.yaml` has `/var/lib/kubelet/pods` enabled with `mountPropagation: "Bidirectional"`, however it seems `plugin-dir` is also required to have `mountPropogation` enabled, for the CSI to work properly and the mounts to be visible outside the plugin container.

As the `csi-cephfsplugin` conatiner first mounts under `plugin-dir` and then bind-mount to `pods-mount-dir` (which enables propogation), I can see both mounted properly inside the `csi-cephfsplugin`, but not on the host node nor other containers that mounted the pvc successfully. Once `plugin-dir` enabled `mountPropagation: "Bidirectional"`, the propagation to host node and other containers worked as expected.

This is kubernetes v1.10.5 with ubuntu 16.04 4.15.0-29-generic

**Comment by humblec** [comment]
@Madhu-1 this is addressed already, Isnt it ?

**Comment by Madhu-1** [comment]
will verify and close it humble

**Comment by ShyamsundarR** [comment]
This has been fixed with this PR https://github.com/ceph/ceph-csi/pull/457
