### ISSUE TITLE
Update code and documentation about removal of cephfs-plugin option `volumemounter` 

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#584]
Prior to [this](https://github.com/ceph/ceph-csi/pull/571) commit the plugin args could specify a default using the option `volumemounter`, which is no longer the case as we are not using DefaultVolumeMounter in the code, as noted in the [review](https://github.com/ceph/ceph-csi/pull/571#discussion_r319655197). We would need to cleanup the option from the possible set of options and update the doc etc. to reflect the same.

**Comment by Madhu-1** [comment]
This has to be done before release
