### ISSUE TITLE
Upgrading to ceph-csi 1.1.0 leaves older pv unusable

### ISSUE THREAD

**Issue by sbskas** [ceph/ceph-csi#593]
We tried to migrate to the latest release of ceph-csi (1.1.0) from a previous version of ceph-csi (1.0.x-something).
After migration, creation and usage of new pv are ok.
Old pv are marked for release are not cleaned up and cannot and cannot be umounted if they were in usage.

Ceph-csi driver is from the ceph-csi release-v1.1.0 branch commit adad72ae83089e48450260af8d1fee36d0052c16

Testing cluster is running: 
Os:  RHEL 7.6
docker-1.13.1-94.gitb2f74b2.el7.x86_64
kubernetes v1.14.6

Deploy ceph-csi using https://github.com/Madhu-1/ceph-csi.git/ commit  849de000f4dc89e3e90de9fdcddeb4f90b629370
Create a few pvc pv with running pod using them.
Delete the deployment and redeploy the 1.1.0 version.
Convert the storageclass to the new format with config.map and reapply.
Try to delete a PVC
Try to scale down a process using an older PV.

Errors are showing up in the logs :
`I0906 15:10:27.642906       1 controller.go:1308] delete "pvc-fbcc7227-65ce-11e9-9853-0050568e92c4": started
I0906 15:10:27.668116       1 connection.go:180] GRPC call: /csi.v1.Controller/DeleteVolume
I0906 15:10:27.668173       1 connection.go:181] GRPC request: {"secrets":"***stripped***","volume_id":"csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b"}
I0906 15:10:27.672946       1 connection.go:183] GRPC response: {}
I0906 15:10:27.673641       1 connection.go:184] GRPC error: rpc error: code = InvalidArgument desc = missing metadata store configuration to proceed with deleting legacy volume ID (csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b)
E0906 15:10:27.673711       1 controller.go:1331] delete "pvc-fbcc7227-65ce-11e9-9853-0050568e92c4": volume deletion failed: rpc error: code = InvalidArgument desc = missing metadata store configuration to proceed with deleting legacy volume ID (csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b)
W0906 15:10:27.673830       1 controller.go:934] Retrying syncing volume "pvc-fbcc7227-65ce-11e9-9853-0050568e92c4", failure 6
E0906 15:10:27.673887       1 controller.go:952] error syncing volume "pvc-fbcc7227-65ce-11e9-9853-0050568e92c4": rpc error: code = InvalidArgument desc = missing metadata store configuration to proceed with deleting legacy volume ID (csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b)
I0906 15:10:27.673995       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-fbcc7227-65ce-11e9-9853-0050568e92c4", UID:"01791cd8-65cf-11e9-994e-0050568e50c1", APIVersion:"v1", ResourceVersion:"26363293", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' rpc error: code = InvalidArgument desc = missing metadata store configuration to proceed with deleting legacy volume ID (csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b)`

The provisionner fails to find the credentials related to the pv and refuse to delete them.
There's a configmap created for the pv :

`kubectl describe cm csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b
Name:         csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b
Namespace:    kube-system
Labels:       com.ceph.ceph-csi/metadata=csi-metadata
Annotations:  <none>

Data
====
content:
----
{"volName":"pvc-fbcc7227-65ce-11e9-9853-0050568e92c4","volID":"csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b","monitors":"","pool":"rbd","imageFormat":"2","imageFeatures":"layering","volSize":1073741824,"adminId":"admin","userId":"kube","mounter":"rbd","disableInUseChecks":false,"clusterId":""}
Events:  <none>`

I expected the deletion to be effective.

What is missing in the metadata store configuration and what should one put in the cm to restore the usage of pv by the new csi plugin ?

**Comment by sbskas** [comment]
We also try to scale a prometheus down :
The pod is stuck in terminating state. 
`prometheus-monitoring-k8s-prometheus-prometheus-0        0/4     Terminating   0          9d`
Logs at the csi-rbdplugin are showing the following logs:
`I0906 15:55:20.595209   41313 utils.go:105] GRPC call: /csi.v1.Node/NodeUnpublishVolume
I0906 15:55:20.595262   41313 utils.go:106] GRPC request: {"target_path":"/var/lib/kubelet/pods/99cc27b9-c9a9-11e9-acbe-0050568ea16a/volumes/kubernetes.io~csi/pvc-93ad516d-ae1b-11e9-ac6a-0050568e92c4/mount","volume_id":"csi-rbd-vol-93d0bdcc-ae1b-11e9-93f6-161600d4e3fc"}
I0906 15:55:20.596333   41313 nsenter.go:132] Running nsenter command: nsenter [--mount=/rootfs/proc/1/ns/mnt -- /bin/realpath -e /var/lib/kubelet/pods/99cc27b9-c9a9-11e9-acbe-0050568ea16a/volumes/kubernetes.io~csi/pvc-93ad516d-ae1b-11e9-ac6a-0050568e92c4/mount]
I0906 15:55:20.599843   41313 nsenter_mount.go:178] nsenter findmnt args: [-o target,fstype --noheadings --first-only --target /var/lib/kubelet/pods/99cc27b9-c9a9-11e9-acbe-0050568ea16a/volumes/kubernetes.io~csi/pvc-93ad516d-ae1b-11e9-ac6a-0050568e92c4/mount]
I0906 15:55:20.599930   41313 nsenter.go:132] Running nsenter command: nsenter [--mount=/rootfs/proc/1/ns/mnt -- /bin/findmnt -o target,fstype --noheadings --first-only --target /var/lib/kubelet/pods/99cc27b9-c9a9-11e9-acbe-0050568ea16a/volumes/kubernetes.io~csi/pvc-93ad516d-ae1b-11e9-ac6a-0050568e92c4/mount]
I0906 15:55:20.608415   41313 nsenter_mount.go:192] IsLikelyNotMountPoint findmnt output for path /var/lib/kubelet/pods/99cc27b9-c9a9-11e9-acbe-0050568ea16a/volumes/kubernetes.io~csi/pvc-93ad516d-ae1b-11e9-ac6a-0050568e92c4/mount: /var  :
I0906 15:55:20.608466   41313 nsenter_mount.go:198] IsLikelyNotMountPoint: /var/lib/kubelet/pods/99cc27b9-c9a9-11e9-acbe-0050568ea16a/volumes/kubernetes.io~csi/pvc-93ad516d-ae1b-11e9-ac6a-0050568e92c4/mount is not a mount point
I0906 15:55:20.608494   41313 nsenter.go:132] Running nsenter command: nsenter [--mount=/rootfs/proc/1/ns/mnt -- /bin/realpath -e /var/lib/kubelet/pods/99cc27b9-c9a9-11e9-acbe-0050568ea16a/volumes/kubernetes.io~csi/pvc-93ad516d-ae1b-11e9-ac6a-0050568e92c4/mount]
E0906 15:55:20.613073   41313 utils.go:109] GRPC error: rpc error: code = NotFound desc = volume not mounted
`

**Comment by Madhu-1** [comment]
@sbskas will prepare the doc on how to update from 1.0.x to 1.1.0

**Comment by sbskas** [comment]
@Madhu-1 Care to explain the update in a few sentences ? I'm a little puzzled here.
I migrated a ceph-plugin on another cluster previously and didn't face this problem.

**Comment by sbskas** [comment]
Any new about this doc ? We'te stuck here with a test cluster half working (for the new PV) / half broken  (for the PV in use). If you could just give us a hint about what's wrong with the current PV, that'll be most welcome.

**Comment by Madhu-1** [comment]
@sbskas am working on  the Doc  for upgrade (facing some issue while uprgading from 1.0.0  to 1.1.0 ( soon will update the doc)

this is the steps you need to follow to fix is issue found in https://github.com/ceph/ceph-csi/issues/593#issuecomment-528911758

while deleting the pod which uses the older PVC you might face below error message, this has been fixed in v1.2.0 branch
we need to do some manual steps to delete this pod

* find out on which node the pod was scheduled
```[🎩︎]mrajanna@localhost ceph $]kubectl get po -o wide
NAME                             READY   STATUS        RESTARTS   AGE     IP               NODE      NOMINATED NODE   READINESS GATES
csi-cephfsplugin-8p7lv           2/2     Running       1          69m     192.168.121.13   worker0   <none>           <none>
csi-cephfsplugin-attacher-0      1/1     Running       0          69m     10.44.0.10       worker0   <none>           <none>
csi-cephfsplugin-provisioner-0   2/2     Running       1          69m     10.44.0.11       worker0   <none>           <none>
csi-rbdplugin-gx24l              2/2     Running       0          20m     192.168.121.13   worker0   <none>           <none>
csi-rbdplugin-provisioner-0      4/4     Running       0          4m54s   10.44.0.8        worker0   <none>           <none>
csicephfs-demo-pod               1/1     Running       0          37m     10.44.0.12       worker0   <none>           <none>
csirbd-demo-pod                  0/1     Terminating   0          30m     10.44.0.13       worker0   <none>           <none>

```
app pod is runing on worker0 now we need to step into the rbdplugin on the worker0 to unmap and delete the mount point
```
[🎩︎]mrajanna@localhost k8s-cluster $]kubectl exec -it csi-rbdplugin-gx24l -c csi-rbdplugin sh
sh-4.2# 
sh-4.2# mount |grep rbd
/dev/rbd0 on /rootfs/var/lib/kubelet/pods/e4de4449-a4fe-45c2-a4ef-3c3255cba97f/volumes/kubernetes.io~csi/pvc-935e9e15-68dc-4961-9567-2a6c2be17392/mount type ext4 (rw,relatime,seclabel,stripe=1024,data=ordered)
tmpfs on /rootfs/var/lib/kubelet/pods/de672abd-4ed0-46b8-83bb-7aa3b3ca0d45/volumes/kubernetes.io~secret/rbd-csi-nodeplugin-token-899s4 type tmpfs (rw,relatime,seclabel)
tmpfs on /var/lib/kubelet/pods/de672abd-4ed0-46b8-83bb-7aa3b3ca0d45/volumes/kubernetes.io~secret/rbd-csi-nodeplugin-token-899s4 type tmpfs (rw,relatime,seclabel)
tmpfs on /var/lib/kubelet/pods/50724a12-c368-48ea-8708-19538dca94d3/volumes/kubernetes.io~secret/rbd-csi-provisioner-token-hsnc7 type tmpfs (rw,relatime,seclabel)


sh-4.2# umount /rootfs/var/lib/kubelet/pods/e4de4449-a4fe-45c2-a4ef-3c3255cba97f/volumes/kubernetes.io~csi/pvc-935e9e15-68dc-4961-9567-2a6c2be17392/mount
sh-4.2# rbd unmap /dev/rbd0 -f
rbd: sysfs write failed
rbd: unmap failed: (16) Device or resource busy

sh-4.2# rbd unmap /dev/rbd0 -o force

```
* note:i have used force flag overcome `Device or resource busy error`

* now try to delete the POD again forcefully
```bash
kubectl delete po/csirbd-demo-pod --force --grace-period=0

**Comment by Madhu-1** [comment]
to fix the issue in https://github.com/ceph/ceph-csi/issues/593#issue-490400319  please add `metadatastorage` flag to the rbd-provisioner statefulset, This is required to delete  the old PVC

 if the backend image is deleted and PV is still present, delete the PV object forcefully

**Comment by sbskas** [comment]
We added the --metadatastorage=k8s_configmap on all rbdplugin deployed.
First, rbdplugin is looking for configmaps in default namespace for which it has no rights.
We deployed the ceph-csi in the kube-system namepace.
Once given the correct rights, it blocks at mounting the voume with the following statement : 
`I0920 15:01:18.684159   37110 utils.go:119] ID: 62 GRPC call: /csi.v1.Node/NodeStageVolume
I0920 15:01:18.684229   37110 utils.go:120] ID: 62 GRPC request: {"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-93ad516d-ae1b-11e9-ac6a-0050568e92c4/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"xfs"}},"access_mode":{"mode":1}},"volume_context":{"adminid":"admin","imageFeatures":"layering","imageFormat":"2","monValueFromSecret":"monitors","pool":"rbd","storage.kubernetes.io/csiProvisionerIdentity":"1559665331581-8081-","userid":"kube"},"volume_id":"csi-rbd-vol-93d0bdcc-ae1b-11e9-93f6-161600d4e3fc"}
E0920 15:01:18.687938   37110 utils.go:123] ID: 62 GRPC error: rpc error: code = InvalidArgument desc = stage secrets cannot be nil or empty`

What's missing from the setup. Why the rbdplugin is asking to access the configmaps from default and not kube-system ?

**Comment by sbskas** [comment]
Same thing on the csi-provsionner : 
`I0920 13:05:45.754614       1 utils.go:120] ID: 47 GRPC request: {"secrets":"***stripped***","volume_id":"csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b"}
I0920 13:05:45.757168       1 controllerserver.go:303] ID: 47 attempting deletion of potential legacy volume (csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b)
I0920 13:05:45.797065       1 controllerserver.go:248] ID: 47 metadata for legacy volume csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b not found, assuming the volume to be already deleted (configmaps "csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b" not found)`
It's not finding the cm associated with the volume.

**Comment by Madhu-1** [comment]
@sbskas in v1.0.0 RBD stores the volume  information in the configmap in the default namespace or the namespace where  rbdplugin pod is  running https://github.com/ceph/ceph-csi/blob/csi-v1.0/pkg/util/k8scmcache.go#L53

node  stage secret is not required if you  are using `v1.1.0` ceph-csi images, can you please check what version of CSI you are using

`v1.1.0` does not implement nodestagevolume request itself https://github.com/ceph/ceph-csi/blob/release-v1.1.0/examples/rbd/storageclass.yaml#L31

**Comment by Madhu-1** [comment]
> Same thing on the csi-provsionner :
> `I0920 13:05:45.754614 1 utils.go:120] ID: 47 GRPC request: {"secrets":"***stripped***","volume_id":"csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b"} I0920 13:05:45.757168 1 controllerserver.go:303] ID: 47 attempting deletion of potential legacy volume (csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b) I0920 13:05:45.797065 1 controllerserver.go:248] ID: 47 metadata for legacy volume csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b not found, assuming the volume to be already deleted (configmaps "csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b" not found)`
> It's not finding the cm associated with the volume.

can you list the configmaps stored in the namespace where the pod is running and also in  default namespace

**Comment by sbskas** [comment]
kube-system    csi-rbd-vol-013a34c0-65cf-11e9-8afa-aa232122848b                  1      150d
kube-system    csi-rbd-vol-93d0bdcc-ae1b-11e9-93f6-161600d4e3fc                  1      58d
kube-system    csi-rbd-vol-d20c8fd0-9d69-11e9-93f6-161600d4e3fc                  1      79d
kube-system    csi-rbd-vol-f2dea2b2-ae1c-11e9-93f6-161600d4e3fc                  1      58d

The map is here in the kube-system namespace.
There is 0 configmap in the default namespace.

I've deployed the 1.2.0 version of ceph-csi.

**Comment by Madhu-1** [comment]
are you trying to upgrade from 1.0.0 to 1.2.0? why

**Comment by sbskas** [comment]
Just to try, you mentioned some bugs fixed in next version.

**Comment by Madhu-1** [comment]
please add https://github.com/ceph/ceph-csi/blob/e2890a27ffe7c530295c62de3bf159dbdbc8537e/deploy/cephfs/kubernetes/v1.14%2B/csi-cephfsplugin-provisioner.yaml#L96 to your  deployment template and try to delete PVC ( this is missing in rbd template)

**Comment by Madhu-1** [comment]
updating to 1.2.0 from  1.1.0 can cause issue while deleting pods this is because we have implemented node stage volume in  1.2.0 which does the rbd mapping and unmapping ( earlier this was done in  node publish/unpublish request)

**Comment by Madhu-1** [comment]
@sbskas updating from 1.2.0 requires  node drain ( as we have implemented node staging in v1.2.0)

**Comment by sbskas** [comment]
@Madhu-1 we aren't doing cephfs, only rbd. You mean adding 
 `           - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace`
In the rbdplugin-provisioner and csi-rbdplugin ?
I

**Comment by Madhu-1** [comment]
> @Madhu-1 we aren't doing cephfs, only rbd. You mean adding
> ` - name: POD_NAMESPACE valueFrom: fieldRef: fieldPath: metadata.namespace`
> In the rbdplugin-provisioner and csi-rbdplugin ?

yes please add it to rbd provisioner

**Comment by sbskas** [comment]
Ok, I went back to 1.1.0 since I don't want to debug multiple problem at the same time.
Patched the yaml and recreated the whole thing.
Now I got "missing ID field 'userID' in secrets"

Whch user
`I0920 16:47:19.827060   63397 utils.go:106] GRPC request: {"secrets":"***stripped***","target_path":"/var/lib/kubelet/pods/a564c1c0-dbc0-11e9-aac6-0050568e50c1/volumes/kubernetes.io~csi/pvc-93ad516d-ae1b-11e9-ac6a-0050568e92c4/mount","volume_capability":{"AccessType":{"Mount":{"fs_type":"xfs"}},"access_mode":{"mode":1}},"volume_context":{"adminid":"admin","imageFeatures":"layering","imageFormat":"2","monValueFromSecret":"monitors","pool":"rbd","storage.kubernetes.io/csiProvisionerIdentity":"1559665331581-8081-","userid":"kube"},"volume_id":"csi-rbd-vol-93d0bdcc-ae1b-11e9-93f6-161600d4e3fc"}
E0920 16:47:19.836226   63397 utils.go:109] GRPC error: rpc error: code = Internal desc = missing ID field 'userID' in secrets`

**Comment by sbskas** [comment]
Same thing to mounting the volume.
  Normal   Scheduled    15s   default-scheduler   Successfully assigned monitoring/prometheus-monitoring-k8s-prometheus-prometheus-0 to w2-pic-pp
  Warning  FailedMount  5s    kubelet, w2-pic-pp  MountVolume.SetUp failed for volume "pvc-93ad516d-ae1b-11e9-ac6a-0050568e92c4" : rpc error: code = Internal desc = missing ID field 'userID' in secrets

**Comment by sbskas** [comment]
Everything seems to be in order after the few corrections.
Let me summarize them in the post.
To migrate from 1.0 to 1.1 one has to  :
1- recreate the storageclass with the new format and add 2 secrets for provison and publish
2- Add the POD_NAMESPACE env in the relevant pods (csi-rbdplugin needs this)
3- add the --metadatastorage k8s_configmap in the relevant pods
4- remove the finalizers in the volumeattachements created by 1.0
After this, almost everything works but PV deletion which has to be done by hand.

Is there anything I missed ?

**Comment by Madhu-1** [comment]
And to delete fix unmount issue i think you can try below things.

Remove rootfs mount from daemonset and set containerized=false in argument flags

With this you can fix unmount issue. There is a pr which merged into master just search for it if you need reference

**Comment by kfox1111** [comment]
So, whats the current status of getting from 1.0.x to 1.2.2? There are comments above for getting to 1.1. Can you then successfully get to 1.2.2?

Any movement towards a procedure for migrating old volumes to current ones? I've got a 1.0.x cluster currently with 29 volumes. :/

**Comment by kfox1111** [comment]
FYI, we gave up, parallel installed the newer driver and have been manually moving pv's over from one driver to another as we have time. Ugly but gives us a path forward.

**Comment by humblec** [comment]
@kfox1111 apologies and couldnt help much on this.  however the backward compabitility since current versions are respected. so we should be good from now on :).. Closing this issue for now.
