### ISSUE TITLE
pod delete but globalmount dir not delete 

### ISSUE THREAD

**Issue by jianglingxia** [ceph/ceph-csi#599]
# Describe the bug #
i use the csi driver v1.1.0 and delete the pr  https://github.com/ceph/ceph-csi/pull/400 and merge the pr https://github.com/ceph/ceph-csi/pull/460 then make image and run the csi driver
then create pvc and dynamic create pv and volume and pod running

csi-cephfs-demo-pod-alpile       1/1     Running   0          4m12s   11.11.11.250 
but delete pod the globalmount dir can not delete and log umount failed

[root@node-5:/paasdata/docker/plugins/kubernetes.io/csi/pv/pvc-6ae66519-cad5-11e9-8a97-fa163ebb7dae/globalmount]$ df -h |grep csi
tmpfs                     1.9G   12K  1.9G   1% /paasdata/docker/pods/36886590-cad5-11e9-8a97-fa163ebb7dae/volumes/kubernetes.io~secret/cephfs-csi-nodeplugin-token-zk6db
ceph-fuse                 5.0G     0  5.0G   0% /paasdata/docker/plugins/kubernetes.io/csi/pv/pvc-6ae66519-cad5-11e9-8a97-fa163ebb7dae/globalmount

[root@node-5:/paasdata/docker/plugins/kubernetes.io/csi/pv/pvc-6ae66519-cad5-11e9-8a97-fa163ebb7dae/globalmount]$ docker logs 9ddf839422cc
I0830 03:21:11.293122       1 cephcsi.go:117] Starting driver type: cephfs with name: cephfs.csi.ceph.com
E0907 06:38:34.897165       1 utils.go:109] GRPC error: rpc error: code = Internal desc = an error occurred while running (135) umount [/paasdata/docker/plugins/kubernetes.io/csi/pv/pvc-6ae66519-cad5-11e9-8a97-fa163ebb7dae/globalmount]: exit status 32: umount: /paasdata/docker/plugins/kubernetes.io/csi/pv/pvc-6ae66519-cad5-11e9-8a97-fa163ebb7dae/globalmount: target is busy.
E0907 06:38:35.497723       1 utils.go:109] GRPC error: rpc error: code = Internal desc = an error occurred while running (136) umount [/paasdata/docker/plugins/kubernetes.io/csi/pv/pvc-6ae66519-cad5-11e9-8a97-fa163ebb7dae/globalmount]: exit status 32: umount: /paasdata/docker/plugins/kubernetes.io/csi/pv/pvc-6ae66519-cad5-11e9-8a97-fa163ebb7dae/globalmount: target is busy.
E0907 06:38:36.599790       1 utils.go:109] GRPC error: rpc error: code = Internal desc = an error occurred while running (137) umount [/paasdata/docker/plugins/kubernetes.io/csi/pv/pvc-6ae66519-cad5-11e9-8a97-fa163ebb7dae/globalmount]: exit status 32: umount: /paasdata/docker/plugins/kubernetes.io/csi/pv/pvc-6ae66519-cad5-11e9-8a97-fa163ebb7dae/globalmount: target is busy.

# Environment details #

- Image/version of Ceph CSI driver v1.1.0
- helm chart version
- Kubernetes cluster version  v1.13
- Logs

# Steps to reproduce #

1. Setup details: '...'
1. Deployment to trigger the issue '....'
1. See error

# Actual results #

Describe what happened

# Expected behavior #

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by Madhu-1** [comment]
@jianglingxia this must be fixed in 1.2.0 release

**Comment by humblec** [comment]
@jianglingxia  closing this for now, please feel free to reopen if its not fixed with 1.2.1

**Comment by jianglingxia** [comment]
can you tell me which commit fixed the problem?really thanks

**Comment by Madhu-1** [comment]
@jianglingxia here it is https://github.com/ceph/ceph-csi/pull/510

**Comment by jianglingxia** [comment]
thanks @Madhu-1 
the #510 i see is rbd type volume.but i use cephfs storage,it can fixed also?thanks

**Comment by Madhu-1** [comment]
@jianglingxia we are using cephfs subvolume code to create PVC?

@humblec @ShyamsundarR this is happening with cephfs also

**Comment by jianglingxia** [comment]
the case is i use the release version v1.1.0 then merge the pr:https://github.com/ceph/ceph-csi/pull/460  and delete the fssubvolume function because my ceph server is v12 can not supprot the command and then makefile in k8s v1.13 to create pod with pvc of cephfs,then delete pod can not umount

**Comment by Madhu-1** [comment]
CC @poornimag

**Comment by leojonathanoh** [comment]
also getting this on `cephfs`. Any workaround ?

**Comment by Madhu-1** [comment]
@leojonathanoh you need to provide logs from cephfs daemonset

**Comment by leojonathanoh** [comment]
Sorry I had to make a quick fix to my cluster, so I don't have the `csi-cephfsplugin` pod logs, nor am I seeing this error in its logs anymore because I deleted the pod and restarted some pods consuming `cephfs` `pvc`s. 

I'll post back if i get the error again.


```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: "2019-10-05T09:12:25Z"
  generation: 2
  name: csi-cephfsplugin
  namespace: rook-ceph
  resourceVersion: "16038768"
  selfLink: /apis/extensions/v1beta1/namespaces/rook-ceph/daemonsets/csi-cephfsplugin
  uid: f1a9ef64-d6eb-496d-a932-38c3b5fa77bd
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: csi-cephfsplugin
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: csi-cephfsplugin
        contains: csi-cephfsplugin-metrics
    spec:
      affinity: {}
      containers:
      - args:
        - --v=5
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/csi.sock
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - rm -rf /registration/rook-ceph.cephfs.csi.ceph.com /registration/rook-ceph.cephfs.csi.ceph.com-reg.sock
        name: driver-registrar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /registration
          name: registration-dir
      - args:
        - --nodeid=$(NODE_ID)
        - --type=cephfs
        - --endpoint=$(CSI_ENDPOINT)
        - --v=5
        - --nodeserver=true
        - --drivername=rook-ceph.cephfs.csi.ceph.com
        - --metadatastorage=k8s_configmap
        - --mountcachedir=/mount-cache-dir
        - --pidlimit=-1
        - --metricsport=9091
        - --metricspath=/metrics
        - --enablegrpcmetrics=true
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        image: quay.io/cephcsi/cephcsi:v1.2.1
        imagePullPolicy: IfNotPresent
        name: csi-cephfsplugin
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /var/lib/kubelet/plugins
          mountPropagation: Bidirectional
          name: csi-plugins-dir
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: pods-mount-dir
        - mountPath: /sys
          name: host-sys
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /dev
          name: host-dev
        - mountPath: /mount-cache-dir
          name: mount-cache-dir
        - mountPath: /etc/ceph-csi-config/
          name: ceph-csi-config
        - mountPath: /tmp/csi/keys
          name: keys-tmp-dir
      - args:
        - --type=liveness
        - --endpoint=$(CSI_ENDPOINT)
        - --metricsport=9081
        - --metricspath=/metrics
        - --polltime=60s
        - --timeout=3s
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: quay.io/cephcsi/cephcsi:v1.2.1
        imagePullPolicy: IfNotPresent
        name: liveness-prometheus
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rook-csi-cephfs-plugin-sa
      serviceAccountName: rook-csi-cephfs-plugin-sa
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: node-role.kubernetes.io/worker
        operator: Exists
      - key: node-role.kubernetes.io/gameserver
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/rook-ceph.cephfs.csi.ceph.com/
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: /var/lib/kubelet/plugins
          type: Directory
        name: csi-plugins-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet/pods
          type: Directory
        name: pods-mount-dir
      - hostPath:
          path: /sys
          type: ""
        name: host-sys
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - hostPath:
          path: /dev
          type: ""
        name: host-dev
      - emptyDir: {}
        name: mount-cache-dir
      - configMap:
          defaultMode: 420
          items:
          - key: csi-cluster-config-json
            path: config.json
          name: rook-ceph-csi-config
        name: ceph-csi-config
      - emptyDir:
          medium: Memory
        name: keys-tmp-dir
  templateGeneration: 2
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 4
  desiredNumberScheduled: 4
  numberAvailable: 4
  numberMisscheduled: 0
  numberReady: 4
  observedGeneration: 2
  updatedNumberScheduled: 4
```
