### ISSUE TITLE
Provisioner is kernel ceph only

### ISSUE THREAD

**Issue by clkao** [ceph/ceph-csi#60]
If a storage class has `provisionVolume: true`, the provisioner fails on nodes without kernel ceph support, since `createVolume` has mountKernel hardcoded.  Does it make sense to use the mounter specified by volOptions.Mounter?

**Comment by rootfs** [comment]
good point!

in the long run, i would like to see a cephfs fuse mounter and use it for provisioner

@gman0

**Comment by gman0** [comment]
Thanks for the suggestion, this will get in as a post-0.3.0, meaning the beginning of the next week if everything goes smoothly.
