### ISSUE TITLE
Increase sidecar timeout from 60s to higher value

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#602]
# Describe the bug #

At present, the request timeout of sidecars are at 60s and this is a request to increase this time out value to 150s or higher. The higher timeout value can help to reduce the load of our backend ceph cluster and also can avoid throttling issues at sidecars to an extend.

**Comment by mykaul** [comment]
Is the above PR closing this issue?
@Madhu-1 , @humblec  ?

**Comment by Madhu-1** [comment]
@mykaul this has been updated in rook, people who are using rook to deploy  ceph-csi will get higher timeout values, will updated templates in ceph-csi in 1.2.1 release

**Comment by humblec** [comment]
@mykaul we are yet to receive the test results on increased timeout. so, we will update the template here too and based on the test result we can update and close this.

**Comment by Madhu-1** [comment]
@humblec can you shorten the commit heading message
