### ISSUE TITLE
update helm chart repo to v1.2.0

### ISSUE THREAD

**Issue by HaveFun83** [ceph/ceph-csi#603]
The helm chart repo under https://ceph.github.io/csi-charts still points to the old release version 1.1.0.

Please also update the chart to the new release there.
It also look like the new helm-chart version for v1.2.0 is moved out of the chart repo tree with wrong chart metadata
https://github.com/ceph/ceph-csi/blob/release-v1.2.0/deploy/rbd/kubernetes/v1.14%2B/helm/ceph-csi-rbd/Chart.yaml

Please have a look.
tia

**Comment by wilmardo** [comment]
> It also look like the new helm-chart version for v1.2.0 is moved out of the chart repo tree with wrong chart metadata

What do you mean by this?

The helm charts are undergoing a major change which is scheduled for the next release #570

**Comment by Madhu-1** [comment]
@HaveFun83 we have some issue with CI pushing 1.12.0 helm chats, as we are doing major changes for helm chats, will backport it to v1.2.0

**Comment by HaveFun83** [comment]
> > It also look like the new helm-chart version for v1.2.0 is moved out of the chart repo tree with wrong chart metadata
> 
> What do you mean by this?
> 
> The helm charts are undergoing a major change which is scheduled for the next release #570

The helm chart metadata is wrong
From branch release-1.2.0
```
---
apiVersion: v1
appVersion: "1.0.0"
description: "Container Storage Interface (CSI) driver,
provisioner, snapshotter, and attacher for Ceph RBD"
name: ceph-csi-rbd
version: 0.8.0
keywords:
  - ceph
  - rbd
  - ceph-csi
home: https://github.com/ceph/ceph-csi
sources:
  - https://github.com/ceph/ceph-csi/tree/csi-v1.0/deploy/rbd/helm
icon: https://raw.githubusercontent.com/ceph/ceph-csi/master/assets/ceph-logo.png
```
from branch release-v1.1.0
```
---
apiVersion: v1
appVersion: "1.1.0"
description: "Container Storage Interface (CSI) driver,
provisioner, snapshotter, and attacher for Ceph RBD"
name: ceph-csi-rbd
version: 1.1.0
keywords:
  - ceph
  - rbd
  - ceph-csi
home: https://github.com/ceph/ceph-csi
sources:
  - https://github.com/ceph/ceph-csi/tree/csi-v1.0/deploy/rbd/helm
```

also the directory structure was changed so the chart went out of the repo url https://ceph.github.io/csi-charts

Do you have a timeframe when the backported chart for v1.2.0 will be out?

**Comment by HaveFun83** [comment]
Any news here? yesterday v1.2.1 was released but is now missing again

**Comment by Madhu-1** [comment]
@HaveFun83 sorry for the issue, we  had some issue with pushing the helm charts, I made  a PR to  push helm chats https://github.com/ceph/ceph-csi/pull/663
 
from next release onwards will have helm charts for each release (once PR is merged  will  start pushing canary helm  charts to https://github.com/ceph/csi-charts)

**Comment by Madhu-1** [comment]
@HaveFun83 canary helm charts are available from testing https://github.com/ceph/csi-charts/tree/master/docs

**Comment by humblec** [comment]
@Madhu-1 cant this be closed now ?

**Comment by Madhu-1** [comment]
Closing as this is fixed
