### ISSUE TITLE
Remove support for "imageFormat" V1

### ISSUE THREAD

**Issue by dillaman** [ceph/ceph-csi#607]
librbd prevents the creation of V1 images but still supports opening existing V1 images. Attempting to create a V1 image using the `rbd` CLI will result in the following failure message:

> Format 1 image creation unsupported.

**Comment by Madhu-1** [comment]
@dillaman we need to remove `imageFormat` option from storageclass?

**Comment by dillaman** [comment]
@Madhu-1 If it doesn't break existing storageclass's to remove it, I would say yes. Otherwise, remove it from the examples and ignore it in the CSI driver.
