### ISSUE TITLE
PR list to be backported for v1.2.1 release

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#609]
PR list to be backported for v1.2.1 release
(please update this issue so that we can keep track of PR's)

https://github.com/ceph/ceph-csi/pull/608
https://github.com/ceph/ceph-csi/pull/570

**Comment by humblec** [comment]
Rather we can track the PRs with just label .

**Comment by Madhu-1** [comment]
closing this as per @humblec suggestion we can track PR's with labels
