### ISSUE TITLE
Make use of Travis environment variables in deploy.sh

### ISSUE THREAD

**Issue by wilmardo** [ceph/ceph-csi#610]
# Describe the feature you'd like to have #

Make the deploy.sh smarter so less manual interference is needed to release.
The logic here seems flawed at the moment:
https://github.com/ceph/ceph-csi/blob/master/deploy.sh#L27

We could improve this with the TRAVIS_TAG variable like #570 introduced.

Travis environment files reference:
https://docs.travis-ci.com/user/environment-variables/

# What is the value to the end user? (why is it a priority?) #

Better and faster releases :D

# How will we know we have a good solution? (acceptance criteria) #

Reduce or remove the need to create release PR's like:

https://github.com/ceph/ceph-csi/pull/804

**Comment by humblec** [comment]
@wilmardo iic this issue can be closed. Please feel free to reopen if you think otherwise. +1

**Comment by wilmardo** [comment]
Hmm in my opinion this is still a needed feature. All the reverting and prepping for releases is unneeded since the CI has access to the tag information.
