### ISSUE TITLE
Improve helm documentation

### ISSUE THREAD

**Issue by wilmardo** [ceph/ceph-csi#611]
# Describe the feature you'd like to have #

More documentation for the helm charts to be more uniform with other charts. Followup on #570
Create a readme.md like for example:

https://github.com/helm/charts/tree/master/stable/apm-server

# What is the value to the end user? (why is it a priority?) #

Easier understanding of the Helm charts, more uniform with all the other charts.

# How will we know we have a good solution? (acceptance criteria) #

Nice formatted readme, easy to understand.

**Comment by humblec** [comment]
@wilmardo iic this issue can be closed.  Please feel free to reopen if you think otherwise. :+1:

**Comment by Madhu-1** [comment]
@humblec reopening this as we still need to document the configurable parameters in cephfs and rbd helm charts

**Comment by wilmardo** [comment]
Still not resolved sadly :'(

Might be worth marking this as an easy fix for the hacktoberfest? @Madhu-1

**Comment by Madhu-1** [comment]
> Still not resolved sadly :'(
> 
> Might be worth marking this as an easy fix for the hacktoberfest? @Madhu-1

I think its good to discuss how we can make use  of hacktoberfest to fix easy  fix issues

**Comment by wilmardo** [comment]
@Madhu-1 Here is described how to opt-in to Hacktoberfest:
https://hacktoberfest.digitalocean.com/hacktoberfest-update

Then add the Hacktoberfest label to easy issues and issues that need contributing :)

**Comment by Yuggupta27** [comment]
> @humblec reopening this as we still need to document the configurable parameters in cephfs and rbd helm charts

Since #2236 and #2257 are merged, we can close this issue now.
