### ISSUE TITLE
allowing kernel mount for versions of kernel version < 4.17

### ISSUE THREAD

**Issue by yydzhou** [ceph/ceph-csi#617]
# Describe the feature you'd like to have #
Kernel mount for cephfs on kernel version < 4.17
# What new functionality do you want?
 When the `mounter: kernel` is specified in the storage class, the csi should do their best to use the specified mounter even through this may result in lose some features.  

# What is the value to the end user? (why is it a priority?) #
There are a couple reasons. 
1. The kernel has better performance on latency and throughput, this is important for some latency sensitive applications.
2. The kernel mounting is much more stable as the FUSE has the issue https://github.com/ceph/ceph-csi/issues/554
3. This request is actually to match the default behavior of previous csi version as well as the old external provisioners. There is no quota support for a long time, and existing users are good with it. However, the new version of cephfs-csi changed this behavior (forces use FUSE mount when kernel < 4.17 https://github.com/ceph/ceph-csi/blob/master/pkg/cephfs/volumemounter.go#L73), which results a lot more effort needed for an upgrade.  

In addition, kernel 4.17 is toooo new for production requirement as the current Long time support kernel is 4.14. https://www.kernel.org/category/releases.html. There is 4.19 claimed to be long time support, but its support will end in next year. I think this enforcement should be delayed until there is a real long term support kernel version >= 4.17. 

How would the end user gain value from having this feature?

# How will we know we have a good solution? (acceptance criteria) #

Add a list of criteria that should be met for this feature to be useful

# Additional context #

**Comment by vicaya** [comment]
Quota and snapshot are usually an optional features that are not used by default in many deployments. Hard code 4.17+ for using kernel client seems unreasonable. 4.14 (a LTS release)+ with warnings for missing features, would be a more reasonable default. At a minimum, there should be an option to override default behavior.

**Comment by Madhu-1** [comment]
@humblec can this be fixed before 1.2.1 release?

**Comment by Madhu-1** [comment]
CC @poornimag @ajarr

**Comment by Madhu-1** [comment]
@vicaya @yydzhou please check https://github.com/ceph/ceph-csi/pull/623#issuecomment-532754344

**Comment by yydzhou** [comment]
> @vicaya @yydzhou please check [#623 (comment)](https://github.com/ceph/ceph-csi/pull/623#issuecomment-532754344)

@Madhu-1 and @poornimag  Thanks for your quick response and action.

**Comment by Madhu-1** [comment]
closing as this is fixed
