### ISSUE TITLE
use cephcsi driver v1.1.0 and yaml deploy but container can not running

### ISSUE THREAD

**Issue by jianglingxia** [ceph/ceph-csi#618]
# Describe the bug #
i use the cephcsi driver v1.1.0, and use the example by the :
https://github.com/ceph/ceph-csi/blob/master/deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin-provisioner.yaml
deploy the provisioner and ds but have two containers  can not running,the logs prints:
flag provided but not defined: -controllerserver
[root@paas-controller-11-11-11-94:/home/ubuntu/newimages/tasks]$ kubectl get po   
NAME                                  READY   STATUS             RESTARTS   AGE
ceph-csi-cephfsplugin-8prgz           1/3     CrashLoopBackOff   4          40s
ceph-csi-cephfsplugin-provisioner-0   2/4     CrashLoopBackOff   2          41s
ceph-csi-cephfsplugin-sp5v6           1/3     CrashLoopBackOff   4          41s
ceph-csi-cephfsplugin-z7h2h           1/3     CrashLoopBackOff   4          40s

i found the v1.1.0 code flag have not controllerserver ,i think maybe need to explain it in some docs that the yaml use controllerserver flag must use v1.2.0
# Environment details #

- Image/version of Ceph CSI driver
- helm chart version
- Kubernetes cluster version
- Logs

# Steps to reproduce #

1. Setup details: '...'
1. Deployment to trigger the issue '....'
1. See error

# Actual results #

Describe what happened

# Expected behavior #

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by jianglingxia** [comment]
@Madhu-1
thanks

**Comment by Madhu-1** [comment]
@jianglingxia use https://github.com/ceph/ceph-csi/tree/v1.1.0 branch not the master branch

**Comment by jianglingxia** [comment]
@Madhu-1
can you join the slack ,i call you in threads,thanks
i ocure a problem that choose which  version use the ceph csi driver,really thanks
