### ISSUE TITLE
Disable mkfs.ext4/xfs discard for RBD RXO volumes

### ISSUE THREAD

**Issue by dillaman** [ceph/ceph-csi#621]
# Describe the feature you'd like to have #620 

It's expensive (both in time and IO) to have ext4 or XFS discard a newly created RBD-backed block device when laying down the file system. Either get a patch merged into upstream k8s' `FormatAndMount` API that allows the RBD CSI to specify the no-discard flags to mkfs, or wrap the k8s `FormatAndMount` API call w/ a custom call that (1) calls `GetDiskFormat` to determine if there is a FS on the block device, (2) if not, directly invokes `mkfs`, and then (3) falls back to the original `FormatAndMount` call.   

# What is the value to the end user? (why is it a priority?) #

This will speed up volume creating on RBD-backed block devices since there is no need to zero the already zeroed RBD image.

# How will we know we have a good solution? (acceptance criteria) #

The `mkfs.ext4` call passes `-K` and `mkfs.xfs` calls passes `-E nodiscard` options.

# Additional context #

**Comment by dillaman** [comment]
Also revert https://github.com/ceph/ceph-csi/pull/545 and https://github.com/rook/rook/pull/3601

**Comment by humblec** [comment]
@dillaman I am already working on wrapping the formatAndMount in our driver. so will take that route.
