### ISSUE TITLE
ceph fuse admin socket path too long

### ISSUE THREAD

**Issue by clkao** [ceph/ceph-csi#63]
in csi-cephfsplugin /var/log/ceph/, there are error messages because the per-volume user we created (client.csie-user-$id) is of very long name.  However the mount seems to be working.  Does the broken adminsocket have any negative impact?

`AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: The UNIX domain socket path /var/run/ceph/ceph.share.8ad1c60a-9a28-11e8-93d6-fe356a4c2823-client.csi-user-8ad1c60a-9a28-11e8-93d6-fe356a4c2823.226.94863584092160.asok is too long! The maximum length on this system is 107`

**Comment by gman0** [comment]
Thanks for the info and no, this has no real effect on the driver's functionality - the admin socket is not used anywhere ATM.

Closing

**Comment by strigazi** [comment]
@gman0 For me it blocks mount of volumes to pods.
