### ISSUE TITLE
option to specify format type in node plugin

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#633]
currently, external-provisioner defaults the format type to `ext4`, there is a discussion going on to provide an option in sidecar container https://github.com/kubernetes-csi/external-provisioner/issues/328 .

if sidecar container does not provide an option to specify the format options, in ceph-csi we need to provide a flag to set it

**Comment by nixpanic** [comment]
@Madhu-1 this can be closed? We already support different filesystems, I think?

**Comment by Madhu-1** [comment]
yeah closing this one as we have option to specify the default filesystem in external-provisioner. Thanks for reminding me @nixpanic
