### ISSUE TITLE
Consider options for persisting metadata

### ISSUE THREAD

**Issue by gman0** [ceph/ceph-csi#66]
Currently, both RBD and CephFS CSI plugins suffer from relying on metadata stored locally on nodes - this will cause problems if e.g. the node goes down and the plugin gets relocated, losing the persisted state. This issue is intended to open a discussion and weigh the options to solve this problem.

**Comment by clkao** [comment]
What are the current metadata stored that are supposed to be persistent and are not node-specific, for rbd and cephfs, respectively?  from the linked PR the rbd snapshot info seems to be one of them.

**Comment by gman0** [comment]
Yes, snapshot info and both rbd and cephfs CSI plugins store volume attributes.

**Comment by gman0** [comment]
I'm playing around with having etcd as a metadata store. Is it ok to have it as a dependency @rootfs ?

**Comment by dillaman** [comment]
Note that RBD allows you to associate arbitrary key/value pairs to images via "rbd image-meta get/set".

**Comment by rootfs** [comment]
@gman0 i would like a cli option to persist meta data in kubernetes api server (e.g. as a configmap). This option can disable meta data persist if the driver runs in mesos.

@dillaman thanks for help. this case is a bit tricky since we want to persist both rbd as well as ceph cluster meta data.

**Comment by kfox1111** [comment]
Is this just for snapshotting, or are other uses also affected?

**Comment by JrCs** [comment]
Also if snapshotter container is not start in the same node as provisionner container, trying to create a snapshot result in: Source Volume ID csi-xxx-xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx cannot found cannot found

**Comment by mickymiek** [comment]
Made a [PR](https://github.com/ceph/ceph-csi/pull/102) to address this issue (still WIP), please give me your feedbacks :)

**Comment by mickymiek** [comment]
@gman0 I think this can be closed?

**Comment by gman0** [comment]
Done, closing.
