### ISSUE TITLE
Document and add tests for static cephfs PV definitions

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#669]
With the change in https://github.com/ceph/ceph-csi/issues/382 we got in static PV support for CephFS, and removed the older scheme that made provisioning a no-OP.

The means to use static CephFS PVs with ceph-csi needs to be documented and also test cases added to ensure we do not regress the functionality.

This issue is raised to track the same.

Initial sample yaml that helps create a static-PV and use it in a pod is provided [here](https://gist.github.com/ShyamsundarR/f16d32e3edd5b38df50e90106674a943).

**Comment by Madhu-1** [comment]
we need to add support for rbd also.

**Comment by KipourosV** [comment]
Could you guys add documentation for static pv in external cluster pls?

**Comment by Madhu-1** [comment]
@ShyamsundarR am planning to add support for cephfs volume created with `ceph fs subvolume create` command as we support cephfs from Nautilus (>=v14.2.2) onwards

**Comment by ShyamsundarR** [comment]
> @ShyamsundarR am planning to add support for cephfs volume created with `ceph fs subvolume create` command as we support cephfs from Nautilus (>=v14.2.2) onwards

:+1: but as a side note, it does not really matter how the subvolume was created (IOW, which command was used), for examples in the documentation we can add the above command as a reference.

**Comment by Madhu-1** [comment]
@agarwal-mudit whould you like to take this up?

**Comment by agarwal-mudit** [comment]
> @agarwal-mudit would you like to take this up?

Sure, assign please.

**Comment by Madhu-1** [comment]
you can refer https://github.com/ceph/ceph-csi/blob/master/docs/static-pvc.md. we already have doc for RBD

**Comment by Madhu-1** [comment]
closing as this is fixed in #1059
