### ISSUE TITLE
Plugins are not compatible with ARM64 when running on rook

### ISSUE THREAD

**Issue by Glorf** [ceph/ceph-csi#671]
Originally filled as rook issue: https://github.com/rook/rook/issues/4051

**Comment by Madhu-1** [comment]
got some idea from @travisn here https://github.com/rook/rook/issues/4051#issuecomment-539852395

@nixpanic is it possible to take it up?

**Comment by cyb70289** [comment]
Hi @nixpanic , @Madhu-1,  are you working on this issue? We met with same problem and fixed it with multi arch image, would like to upstream if you are not on it.

**Comment by billimek** [comment]
Related slack thread for this from the rook slack space: https://rook-io.slack.com/archives/CG3HUV94J/p1569616214102700

**Comment by cyb70289** [comment]
Thanks @billimek

**Comment by Madhu-1** [comment]
@cyb70289 waiting for @nixpanic response, if he has not started this one, am more happy to assign this to you

**Comment by nixpanic** [comment]
Thanks @billimek , I have re-assigned this issue to you. Let me know if I should put it in my backlog again.

**Comment by nixpanic** [comment]
Sorry, I should have paid attention while reading, now assigned to @cyb70289 :+1:

**Comment by cyb70289** [comment]
Per my test, quay.io doesn't support multi arch images. Though quay v3.0 release notes say it supports.[1]

To build multi arch image is easy(take my personal dockerhub account as an example):
- on x86 host: build cephcsi image, push to cyb70289/cephcsi-amd64:v1.2.1
- on arm host: build cephcsi image, push to cyb70289/cephcsi-arm64:v1.2.1
- on x86 host: download manifest-tool[2], run "./manifest-tool-linux-amd64 push from-args --platforms linux/amd64,linux/arm64 --template cyb70289/cephcsi-ARCH:v1.2.1 --target cyb70289/cephcsi:v1.2.1"
Now "docker pull cyb70289/cephcsi:v1.2.1" will download x86 or arm image matching host architecture.
On quay.io, this command failed with error "FATA[0022] Couldn't push manifests referenced in our manifest list: Referenced manifest push unsuccessful: response 400: 400 BAD REQUEST".

I plan to add a travis job to build arm64 image(travis supports arm64 now[3]) and automate above steps. But it looks no-go if quay.io doesn't support multi arch images.

[1] https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/red_hat_quay_release_notes/index#multi_architecture_container_image_support
[2] https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-amd64
[3] https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support

**Comment by Madhu-1** [comment]
we have two options here
* Push images to  quay v3 (personally I have not tried this one)
* Switch from quay to dockerhub

@cyb70289 please send a PR with the current implementation, we can think about next step

@nixpanic @ShyamsundarR @humblec ^^

**Comment by billimek** [comment]
It does look like some things at least are leveraging quay for mult-arch images.  Here is the `quay.io/prometheus/prometheus` image, for example:

```shell
➜ docker manifest inspect quay.io/prometheus/prometheus:v2.12.0 | grep architecture
            "architecture": "amd64",
            "architecture": "arm64",
            "architecture": "arm",
```

**Comment by cyb70289** [comment]
Maybe it's  because quay free account is of limited function?

Patch still needs some refinement and team review.
Below link is current build result. A new job runs on arm64 node to build arm64 image. Another new job "Publis-multiarch-image" is to push multi arch image. It fails at pushing multi arch image to quay.io, as described in last comment.
https://travis-ci.org/cyb70289/ceph-csi/builds/605939243

**Comment by cyb70289** [comment]
PR create
https://github.com/ceph/ceph-csi/pull/707

**Comment by hh** [comment]
@cyb70289 / @billimek is there a work around to deploy to arm while we wait for pushed images / CI setup?

**Comment by ttyS0** [comment]
FWIW, I built an `arm64` image for `csi-node-driver-registrar` from https://github.com/kubernetes-csi/node-driver-registrar, and uploaded it to my local docker registry. Then I made a new DaemonSet config for the `cephfs` and `rbd` plugin suffixed with `-arm64` and `nodeSelector`'d to `arm64`. It was just a copy/paste of the existing DaemonSet configs with the `csi-node-driver-registrar` image pointing to the `arm64` image in my local registry and `cephcsi` images changed to the `canary-arm64` variant. 

After that, my RPis are able to mount both RBD and CephFS PVCs. 🎉

**Comment by colek42** [comment]
@ttyS0 would you mind giving us a pointer to that image and DaemonSet config?

**Comment by ttyS0** [comment]
@colek42 

cephfs: https://github.com/ttyS0/kubernetes/blob/master/ceph/csi-cephfsplugin-arm64.yaml
rbd: https://github.com/ttyS0/kubernetes/blob/master/ceph/csi-rbdplugin-arm64.yaml

As far as the csi-node-registrar goes, I cloned the https://github.com/kubernetes-csi/node-driver-registrar repository on an RPi, ran `make` to build the `csi-node-driver-registrar` binary, did a `docker build`, tagged it, and pushed it to my internal registry.

**Comment by cyb70289** [comment]
Planning to add arm64 support to all k8s-csi sidecar images, similar to ceph-csi. Any help is welcomed.

**Comment by colek42** [comment]
@cyb70289 I have a solution on my fork using buildx 
https://github.com/colek42/node-driver-registrar

See the Dockerfile for notes.  It requires Docker v19

**Comment by colek42** [comment]
My multiarch image is located here:  https://hub.docker.com/r/colek42/csi-node-driver-registrar/tags  I will be working on getting this upstreamed, but will start maintining these with some automation if that does not go well.

**Comment by Madhu-1** [comment]
ceph-csi is pushing new arm image here https://quay.io/repository/cephcsi/cephcsi?tab=tags quay.io/cephcsi/cephcsi:v2.0.0-arm64, if any help is required please feel free to reopen it

**Comment by Madhu-1** [comment]
reopening as we are not able to build arm64 images

**Comment by travisn** [comment]
@Madhu-1 Is this a new issue with v2.1.0? I see arm images for other recent versions. Do you have more background on the issue?

**Comment by Madhu-1** [comment]
> @Madhu-1 Is this a new issue with v2.1.0? I see arm images for other recent versions. Do you have more background on the issue?

more info at https://github.com/ceph/ceph-csi/issues/856. we cannot build multi arch images in Travis as we need physical machines to build amd64 and arm64 images

**Comment by Madhu-1** [comment]
closing this as we are providing separate arm64 image for cephcsi
