### ISSUE TITLE
Add documentation to delete stale backend images/omap

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#672]
Add documentation to delete the backend `omap` metadata and backend cephfs and rbd images.

if the PVC is created with storage class which is having the `reclaimPolicy` as `Retain` will not delete the PV object and backend `omap` metadata and backend image. Manual deletion of PV will result in stale `omap` keys, values and also stale cephfs and rbd images.

we need to document the steps to clean up the image metadata and backend images.

**Comment by chenxu1990** [comment]
Should the metadata and the image be deleleted separately ？

**Comment by Madhu-1** [comment]
Yes you need to delete metadata from rados seperately

**Comment by chenxu1990** [comment]
ok I will take the job .

**Comment by Madhu-1** [comment]
Awesome, @chenxu1990 assigning this to you
