### ISSUE TITLE
Add support for smart cloning in rbd

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#675]
below are the sub-tasks to  achieve the smart cloning

* Implement stand-alone snapshot creation more info here (https://github.com/ceph/ceph-csi/pull/467)
* Implement rbd image flattening
*  Implement rbd cloning from a snapshot
* Implement cloning image from another image (combined with above 3 implementations)
*  Enable E2E testing for snapshot
* Add E2E testing for smart cloning

**Comment by zhucan** [comment]
@Madhu-1 I don't understand it that restore from snapshot not use “rbd rollback” but use "rbd clone" and the restore from snapshot not support flatten， why？

**Comment by Madhu-1** [comment]
we will support flatten with the new implementation

**Comment by dillaman** [comment]
> @Madhu-1 I don't understand it that restore from snapshot not use “rbd rollback” but use "rbd clone" and the restore from snapshot not support flatten， why？

@zhucan From the point-of-view of k8s, the "restore" operation is to just create a new PV from the snapshot. Therefore, you *cannot* just rollback (plus it's very inefficient).

**Comment by zhucan** [comment]
@dillaman Thanks， There is plan to do volume clone for ceph-csi?

**Comment by dillaman** [comment]
@zhucan Indeed -- I believe that's what this issue is tracking.

**Comment by zhucan** [comment]
@dillaman Thanks

**Comment by Madhu-1** [comment]
I had a discussion with @dillaman since we are facing [issue](https://github.com/ceph/ceph-csi/pull/693#issuecomment-544950196) with the current approach. we are moving to a new implementation as detailed below
```
# CO create snapshot process
* create temporary RBD snapshot on source volume's RBD image
* RBD clone CO source volume's RBD image's snapshot to new RBD image
* remove temporary RBD snapshot on CO source volume's RBD image

# CO create volume from snapshot process
* serialize work on RBD snapshot image clone
* test RBD snapshot image clone's depth
* if depth over the hard limit (no soft-limit anymore), flatten clone
* create RBD snapshot on RBD snapshot image clone
* create RBD volume image clone from RBD snapshot image clone

# CO create volume from the volume process
* create RBD snapshot image as if running "CO create snapshot" process
* create RBD volume image as if running "CO create volume from snapshot" process
```

**Comment by Madhu-1** [comment]
update snapshot from alpha to beta once we change the design for snapshot and cloning

**Comment by Madhu-1** [comment]
This is fixed now closing this one
