### ISSUE TITLE
Manage RBD image mirroring via StorageClass parameter

### ISSUE THREAD

**Issue by dillaman** [ceph/ceph-csi#676]
# Describe the feature you'd like to have #

Add a new SC 'mirroring' parameter that can be used to annotate that PVs should be mirrored via RBD mirroring. The current values for this parameter can be "off" and "journal" (or similar). When set to "journal", upon PVC creation the exclusive-lock and journaling RBD image features should be enabled. Additionally, the CSI will need to enable mirroring on the newly created RBD image via `rbd mirror image enable <image-spec>`. This will also imply that NBD will need to be used instead of krbd.

# What is the value to the end user? (why is it a priority?) #

How would the end user gain value from having this feature?

# How will we know we have a good solution? (acceptance criteria) #

Add a list of criteria that should be met for this feature to be useful

# Additional context #

**Comment by techhanx** [comment]
Hi. is this issue still on-going? or developing by someone?
If not, I would like to work on it. @dillaman @humblec @Madhu-1 

and I suggest that we can divide this issue to two issues.
1. add rbd image feature: journaling
2. add rbd mirror image enable

**Comment by humblec** [comment]
@WoohyungHan can you please revisit the PR or patch which solve this issue?  we would like to get this in `2.0.0`.

**Comment by WoohyungHan** [comment]
> @WoohyungHan can you please revisit the PR or patch which solve this issue? we would like to get this in `2.0.0`.

sure, I will. @humblec

**Comment by dillaman** [comment]
This requires k8s CSI external-provisioner PR https://github.com/kubernetes-csi/external-provisioner/pull/399

**Comment by dillaman** [comment]
We want to support the new Ceph Octopus snapshot-based mirroring, so the storage class's "mirroring" attribute should really be an enum of "disabled" (default), "journal", or "snapshot". The snapshot-based mirroring should be functional with the existing krbd driver. The journal-based mirroring mode requires rbd-nbd, but that is not yet production ready since we have no upgrade path for it.

**Comment by Madhu-1** [comment]
Moved this out of release-v3.0.0 milestone

**Comment by humblec** [comment]
Considering we have mirroring support available with release v3.3.0. I am closing this one .Please feel free to reopen if required.

**Comment by Madhu-1** [comment]
We may still need this one If someone wants to enable mirroring when creating the PVC. But they need new volume replication after some time to perform failover and failback. Let's keep it open for some time.

**Comment by Rakshith-R** [comment]
> We may still need this one If someone wants to enable mirroring when creating the PVC. But they need new volume replication after some time to perform failover and failback. Let's keep it open for some time.

@Madhu-1 Lets close this since we have feature rich volume replication setup with csi-addons and there does not seem to be anyone who still need this feature ?

**Comment by Madhu-1** [comment]
Yes as we have defined way for mirroring using Volume replication, closing this one.
