### ISSUE TITLE
Unable to Delete Volume without allow * on MGR

### ISSUE THREAD

**Issue by metti-himself** [ceph/ceph-csi#677]
# Describe the bug #
Deleting rbd volume fails without admin rights. Creation works flawless.

# Environment details #

- quay.io/cephcsi/cephcsi:v1.2.0
- k8s 1.16.1 

Provisioner Log:

I1009 12:07:01.243556       1 utils.go:119] ID: 236 GRPC call:
/csi.v1.Controller/DeleteVolume
I1009 12:07:01.243583       1 utils.go:120] ID: 236 GRPC request:
{"secrets":"***stripped***","volume_id":"0001-0024-60884e33-26b2-45ea-85b9-c8e5b55ad3f4-000000000000000c-a08f22d5-ea8c-11e9-ba9e-5e5c8ec95c02"}
I1009 12:07:01.955228       1 controllerserver.go:341] ID: 236 deleting
image csi-vol-a08f22d5-ea8c-11e9-ba9e-5e5c8ec95c02
I1009 12:07:01.955259       1 rbd_util.go:151] ID: 236 rbd: status
csi-vol-a08f22d5-ea8c-11e9-ba9e-5e5c8ec95c02 using mon
x.x.x.x:6789,x.x.x.x:6789,x.x.x.x:6789, pool xxxxxxx
W1009 12:07:02.044594       1 rbd_util.go:173] ID: 236 rbd: no watchers
on csi-vol-a08f22d5-ea8c-11e9-ba9e-5e5c8ec95c02
I1009 12:07:02.044623       1 rbd_util.go:216] ID: 236 rbd: rm
csi-vol-a08f22d5-ea8c-11e9-ba9e-5e5c8ec95c02 using mon
x.x.x.x:6789,x.x.x.x:6789,x.x.x.x:6789, pool xxxxxxx
E1009 12:07:02.566185       1 rbd_util.go:228] ID: 236 failed to delete
rbd image: exit status 13, command output:
E1009 12:07:02.566218       1 controllerserver.go:343] ID: 236 failed to
delete rbd image: xxxxxxx/csi-vol-a08f22d5-ea8c-11e9-ba9e-5e5c8ec95c02
with error: exit status 13
E1009 12:07:02.566247       1 utils.go:123] ID: 236 GRPC error: rpc
error: code = Internal desc = exit status 13

Ceph MGR Log:
2019-10-09 13:24:18.660495 mgr.ceph-mon1 (mgr.4619165) 913633 : audit
[INF] from='client.6767055 -' entity='client.'xxxxxxx
cmd=[{"image_spec":
"xxxxxxx/csi-vol-94a1ed63-ea7a-11e9-ba9e-5e5c8ec95c02", "prefix": "rbd
task add remove", "target": ["mgr", ""]}]:  access denied

# Steps to reproduce #
Create a simple PVC, and delete afterwards

# Actual results #
Volumes inside Kubernetes are removed, but the rbdplugin is trying forever to delete the rbd volume.

# Expected behavior #
Remove rbd volume from ceph pool

# Additional context #
This ceph cluster is not exclusively used for kubernetes, but for many different customers. It is not possible to use the admin account. Why is the creation of images possible without admin id, but deletion is not?

**Comment by dillaman** [comment]
Is this an upgraded cluster? The MGR's caps should have plenty of privledges on a fresh install, but perhaps there was an issue w/ the original MGR release (or you manually adjusted the caps for the MGR)?

**Comment by dillaman** [comment]
... see [1] for correct MGR caps.

[1] https://docs.ceph.com/docs/nautilus/mgr/administrator/#manual-setup

**Comment by Madhu-1** [comment]
credentials are not handled by cephcsi. user has to pass the proper valid credentials which are having the access to do  certain operations, closing this as not a BUG

**Comment by metti-himself** [comment]
ok guys maybe I was not clear enough, the question is why the creation and mounting of images is possible, but the deletion is not. In https://github.com/ceph/ceph-csi/blob/master/pkg/rbd/rbd_util.go#L211 there is a comment above to delete images _if_ Ceph manager base deletion is supported. This is my problem, in this setup I have no MGR access, but I have pool access. so any chance to make this bahavior configurable, if one has no MGR access?

**Comment by dillaman** [comment]
@metti-himself  Fair enough -- it should fall back to the regular (slow) deletion process if you don't have access to the MGR. But, (1) why doesn't your ceph-csi user have access to the MGR? and (2) why would you want RBD image deletions to block other CSI operations as would be the case w/ the fallback? You don't need admin access to talk to the MGR -- you just need "profile rbd" caps.

**Comment by metti-himself** [comment]
@dillaman (1) because the customer will have direct access to this user, and we have safety concerns if the customer user has mgr access. (2) I just need a solution, so that persistent volumes that are created by ceph-csi, also get deleted by ceph-csi. Maybe Iam doing it all wrong possibly, these are the caps for this user:

caps mon = "profile rbd"
caps osd = "profile rbd pool=xxxxxxxx"

Is there anything missing?

**Comment by dillaman** [comment]
OK, this turns out to be an oversight that got through testing because Rook is deploying w/ admin credentials for the CSI. I'll get a new 'caps mgr = "profile rbd [pool=XYZ]"' added, but in the meantime you can update your caps as follows to get unblocked:

`ceph auth caps client.<client id> mon "profile rbd" osd "profile rbd pool=<pool_name>" mgr "allow command 'rbd task add remove' with image_spec prefix '<pool_name>/'" `

**Comment by metti-himself** [comment]
Works like a charm, thank you.
