### ISSUE TITLE
Running E2E with rook-version default value is not working

### ISSUE THREAD

**Issue by WoohyungHan** [ceph/ceph-csi#688]
# Describe the bug #
Running E2E with rook-version 'master' is not working.
Default setup of rook-version is 'master'. If we do not setup specific rook-version(like v1.1.0) the test try to execute with master version. 

# Environment details #
- ceph-csi/master
- rook/master

# Steps to reproduce #
Run 'go test ./e2e/'

# Actual results #
The test is waiting for 'rook-ceph-agent' and timeout.

# Expected behavior #

# Additional context #

**Comment by Madhu-1** [comment]
yes, flex driver is disabled in rook in master, need to add skip wait for agent pod if the rook master is used

**Comment by WoohyungHan** [comment]
@Madhu-1 
I'm not sure that using 'latest' or 'master' is good choice in the code. The meaning of 'latest' can be change over time, but code(commit) is not. how about explicitly set default version which is working in current code?

**Comment by Madhu-1** [comment]
> @Madhu-1
> I'm not sure that using 'latest' or 'master' is good choice in the code. The meaning of 'latest' can be change over time, but code(commit) is not. how about explicitly set default version which is working in current code? and if code is updated, we can update default verison too.

we can change the default value and also if the rook version is less than `v1.1.0` we can skip the check for agent pods

**Comment by WoohyungHan** [comment]
That's so true!

**Comment by Madhu-1** [comment]
> > we can change the default value and also if the rook version is less than v1.1.0 we can skip the check for agent pods
> 
> That's so true!

@WoohyungHan would you like to send a patch?

**Comment by WoohyungHan** [comment]
Sure, I will.
