### ISSUE TITLE
exec “ceph -m xx get pool” hang the process 

### ISSUE THREAD

**Issue by peacocktrain** [ceph/ceph-csi#694]
# Describe the bug #

 EXEC ceph [-m 172.24.16.4:32701,172.24.16.5:31292,172.24.16.6:30502 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs get arsenal-replicated-pool --format=json]

this common hang the process，and the remaining command already exists

# Environment details #

-  csi-cephfsplugin 1.2.1
-  kubernetes 1.6.1
-  the ceph cluster is remote, connected via nodeport

# csi-cephfsplugin log#
I1021 10:07:01.247316       1 cephcsi.go:103] Driver version: v1.2.1 and Git version: ecac134c38c97ac04b2e80395ecbb6231c0ec250
I1021 10:07:01.247656       1 cachepersister.go:45] cache-perister: using kubernetes configmap as metadata cache persister
I1021 10:07:01.248531       1 cephcsi.go:130] Initial PID limit is set to -1
I1021 10:07:01.248575       1 cephcsi.go:139] Reconfigured PID limit to -1 (max)
I1021 10:07:01.248583       1 cephcsi.go:158] Starting driver type: cephfs with name: rook-ceph.cephfs.csi.ceph.com
I1021 10:07:01.249138       1 util.go:48] cephfs: EXEC uname [-r]
I1021 10:07:01.249583       1 volumemounter.go:74] loaded mounter: kernel
I1021 10:07:01.257154       1 volumemounter.go:82] loaded mounter: fuse
I1021 10:07:01.257312       1 mountcache.go:59] mount-cache: name: rook-ceph.cephfs.csi.ceph.com, version: v1.2.1, mountCacheDir: 
I1021 10:07:01.257321       1 driver.go:86] Enabling controller service capability: CREATE_DELETE_VOLUME
I1021 10:07:01.257327       1 driver.go:98] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
I1021 10:07:01.257567       1 server.go:118] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi-provisioner.sock", Net:"unix"}
I1021 10:07:01.797397       1 utils.go:119] ID: 1 GRPC call: /csi.v1.Identity/Probe
I1021 10:07:01.797409       1 utils.go:120] ID: 1 GRPC request: {}
I1021 10:07:01.799164       1 utils.go:125] ID: 1 GRPC response: {}
I1021 10:07:01.801209       1 utils.go:119] ID: 2 GRPC call: /csi.v1.Identity/GetPluginInfo
I1021 10:07:01.801217       1 utils.go:120] ID: 2 GRPC request: {}
I1021 10:07:01.801586       1 identityserver-default.go:37] ID: 2 Using default GetPluginInfo
I1021 10:07:01.801595       1 utils.go:125] ID: 2 GRPC response: {"name":"rook-ceph.cephfs.csi.ceph.com","vendor_version":"v1.2.1"}
I1021 10:07:01.803044       1 utils.go:119] ID: 3 GRPC call: /csi.v1.Identity/GetPluginCapabilities
I1021 10:07:01.803053       1 utils.go:120] ID: 3 GRPC request: {}
I1021 10:07:01.803412       1 utils.go:125] ID: 3 GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}}]}
I1021 10:07:01.806664       1 utils.go:119] ID: 4 GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I1021 10:07:01.806675       1 utils.go:120] ID: 4 GRPC request: {}
I1021 10:07:01.807053       1 controllerserver-default.go:63] ID: 4 Using default ControllerGetCapabilities
I1021 10:07:01.807065       1 utils.go:125] ID: 4 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}}]}
I1021 10:07:02.037499       1 utils.go:119] ID: 5 GRPC call: /csi.v1.Identity/Probe
I1021 10:07:02.037510       1 utils.go:120] ID: 5 GRPC request: {}
I1021 10:07:02.037954       1 utils.go:125] ID: 5 GRPC response: {}
I1021 10:07:02.041651       1 utils.go:119] ID: 6 GRPC call: /csi.v1.Identity/GetPluginInfo
I1021 10:07:02.041661       1 utils.go:120] ID: 6 GRPC request: {}
I1021 10:07:02.042050       1 identityserver-default.go:37] ID: 6 Using default GetPluginInfo
I1021 10:07:02.042062       1 utils.go:125] ID: 6 GRPC response: {"name":"rook-ceph.cephfs.csi.ceph.com","vendor_version":"v1.2.1"}
I1021 10:07:02.043575       1 utils.go:119] ID: 7 GRPC call: /csi.v1.Identity/GetPluginCapabilities
I1021 10:07:02.043583       1 utils.go:120] ID: 7 GRPC request: {}
I1021 10:07:02.043948       1 utils.go:125] ID: 7 GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}}]}
I1021 10:07:02.046079       1 utils.go:119] ID: 8 GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I1021 10:07:02.046090       1 utils.go:120] ID: 8 GRPC request: {}
I1021 10:07:02.046493       1 controllerserver-default.go:63] ID: 8 Using default ControllerGetCapabilities
I1021 10:07:02.046505       1 utils.go:125] ID: 8 GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}}]}
I1021 10:08:06.721698       1 utils.go:119] ID: 9 GRPC call: /csi.v1.Controller/CreateVolume
I1021 10:08:06.721714       1 utils.go:120] ID: 9 GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-68d35777-2f02-4f61-bf39-02e974be2cfa","parameters":{"clusterID":"rook-ceph-2c","fsName":"arsenal-replicated-pool","mounter":"fuse","pool":"arsenal-replicated-pool-data0"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["debug"]}},"access_mode":{"mode":5}}]}
I1021 10:08:06.723537       1 util.go:48] ID: 9 cephfs: EXEC ceph [-m 172.24.16.4:32701,172.24.16.5:31292,172.24.16.6:30502 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs get arsenal-replicated-pool --format=json]
I1021 10:10:37.226299       1 utils.go:119] ID: 10 GRPC call: /csi.v1.Controller/CreateVolume
I1021 10:10:37.226315       1 utils.go:120] ID: 10 GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-68d35777-2f02-4f61-bf39-02e974be2cfa","parameters":{"clusterID":"rook-ceph-2c","fsName":"arsenal-replicated-pool","mounter":"fuse","pool":"arsenal-replicated-pool-data0"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["debug"]}},"access_mode":{"mode":5}}]}
I1021 10:10:37.227840       1 controllerserver.go:82] ID: 10 an operation with the given Volume ID pvc-68d35777-2f02-4f61-bf39-02e974be2cfa already exists
E1021 10:10:37.227861       1 utils.go:123] ID: 10 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-68d35777-2f02-4f61-bf39-02e974be2cfa already exists
I1021 10:10:38.235971       1 utils.go:119] ID: 11 GRPC call: /csi.v1.Controller/CreateVolume
I1021 10:10:38.235986       1 utils.go:120] ID: 11 GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-68d35777-2f02-4f61-bf39-02e974be2cfa","parameters":{"clusterID":"rook-ceph-2c","fsName":"arsenal-replicated-pool","mounter":"fuse","pool":"arsenal-replicated-pool-data0"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["debug"]}},"access_mode":{"mode":5}}]}
I1021 10:10:38.237482       1 controllerserver.go:82] ID: 11 an operation with the given Volume ID pvc-68d35777-2f02-4f61-bf39-02e974be2cfa already exists
E1021 10:10:38.237493       1 utils.go:123] ID: 11 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-68d35777-2f02-4f61-bf39-02e974be2cfa already exists

# csi-provisioner log #
I1021 10:07:01.028559       1 feature_gate.go:226] feature gates: &{map[]}
I1021 10:07:01.028604       1 csi-provisioner.go:98] Version: v1.3.0-0-g27750ab1
I1021 10:07:01.028622       1 csi-provisioner.go:112] Building kube configs for running in cluster...
I1021 10:07:01.035687       1 connection.go:151] Connecting to unix:///csi/csi-provisioner.sock
I1021 10:07:02.036374       1 connection.go:261] Probing CSI driver for readiness
I1021 10:07:02.036394       1 connection.go:180] GRPC call: /csi.v1.Identity/Probe
I1021 10:07:02.036400       1 connection.go:181] GRPC request: {}
I1021 10:07:02.039257       1 connection.go:183] GRPC response: {}
I1021 10:07:02.039728       1 connection.go:184] GRPC error: <nil>
I1021 10:07:02.039737       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I1021 10:07:02.039743       1 connection.go:181] GRPC request: {}
I1021 10:07:02.042564       1 connection.go:183] GRPC response: {"name":"rook-ceph.cephfs.csi.ceph.com","vendor_version":"v1.2.1"}
I1021 10:07:02.043063       1 connection.go:184] GRPC error: <nil>
I1021 10:07:02.043075       1 csi-provisioner.go:152] Detected CSI driver rook-ceph.cephfs.csi.ceph.com
I1021 10:07:02.043084       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I1021 10:07:02.043089       1 connection.go:181] GRPC request: {}
I1021 10:07:02.044761       1 connection.go:183] GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}}]}
I1021 10:07:02.045582       1 connection.go:184] GRPC error: <nil>
I1021 10:07:02.045591       1 connection.go:180] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I1021 10:07:02.045597       1 connection.go:181] GRPC request: {}
I1021 10:07:02.047319       1 connection.go:183] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}}]}
I1021 10:07:02.048169       1 connection.go:184] GRPC error: <nil>
I1021 10:07:02.048660       1 controller.go:621] Using saving PVs to API server in background
I1021 10:07:02.048809       1 leaderelection.go:217] attempting to acquire leader lease  rook-ceph/rook-ceph-cephfs-csi-ceph-com...
I1021 10:07:02.052656       1 leaderelection.go:326] lock is held by csi-cephfsplugin-provisioner-548494c5c5-7lpqw and has not yet expired
I1021 10:07:02.052704       1 leaderelection.go:222] failed to acquire lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:07:02.052745       1 leader_election.go:172] new leader detected, current leader: csi-cephfsplugin-provisioner-548494c5c5-7lpqw
I1021 10:07:12.699003       1 leaderelection.go:326] lock is held by csi-cephfsplugin-provisioner-548494c5c5-7lpqw and has not yet expired
I1021 10:07:12.699018       1 leaderelection.go:222] failed to acquire lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:07:21.693795       1 leaderelection.go:227] successfully acquired lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:07:21.693842       1 leader_election.go:172] new leader detected, current leader: csi-cephfsplugin-provisioner-548494c5c5-j29h9
I1021 10:07:21.693853       1 leader_election.go:165] became leader, starting
I1021 10:07:21.693898       1 controller.go:769] Starting provisioner controller rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-548494c5c5-j29h9_86c5485e-f3ea-11e9-9483-7ef2d7c7c881!
I1021 10:07:21.693931       1 volume_store.go:90] Starting save volume queue
I1021 10:07:21.694164       1 reflector.go:123] Starting reflector *v1.PersistentVolume (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:803
I1021 10:07:21.694186       1 reflector.go:161] Listing and watching *v1.PersistentVolume from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:803
I1021 10:07:21.694169       1 reflector.go:123] Starting reflector *v1.StorageClass (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:806
I1021 10:07:21.694189       1 reflector.go:123] Starting reflector *v1.PersistentVolumeClaim (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:800
I1021 10:07:21.694209       1 reflector.go:161] Listing and watching *v1.PersistentVolumeClaim from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:800
I1021 10:07:21.694215       1 reflector.go:161] Listing and watching *v1.StorageClass from sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:806
I1021 10:07:21.699282       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:07:21.794009       1 shared_informer.go:123] caches populated
I1021 10:07:21.794324       1 controller.go:818] Started provisioner controller rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-548494c5c5-j29h9_86c5485e-f3ea-11e9-9483-7ef2d7c7c881!
I1021 10:07:26.705296       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:07:31.711571       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:07:36.718829       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:07:41.724629       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:07:46.730692       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:07:51.737136       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:07:56.743208       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:08:01.751853       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:08:06.709919       1 controller.go:979] Final error received, removing PVC 68d35777-2f02-4f61-bf39-02e974be2cfa from claims in progress
I1021 10:08:06.709934       1 controller.go:902] Provisioning succeeded, removing PVC 68d35777-2f02-4f61-bf39-02e974be2cfa from claims in progress
I1021 10:08:06.711798       1 controller.go:1196] provision "default/csi-cephfs-pvc-test" class "csi-cephfs-test": started
I1021 10:08:06.714595       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"csi-cephfs-pvc-test", UID:"68d35777-2f02-4f61-bf39-02e974be2cfa", APIVersion:"v1", ResourceVersion:"4917637", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/csi-cephfs-pvc-test"
I1021 10:08:06.714520       1 controller.go:471] CreateVolumeRequest {Name:pvc-68d35777-2f02-4f61-bf39-02e974be2cfa CapacityRange:required_bytes:5368709120  VolumeCapabilities:[mount:<fs_type:"ext4" mount_flags:"debug" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > ] Parameters:map[clusterID:rook-ceph-2c csi.storage.k8s.io/node-stage-secret-name:csi-cephfs-secret csi.storage.k8s.io/node-stage-secret-namespace:rook-ceph csi.storage.k8s.io/provisioner-secret-name:csi-cephfs-secret csi.storage.k8s.io/provisioner-secret-namespace:rook-ceph fsName:arsenal-replicated-pool mounter:fuse pool:arsenal-replicated-pool-data0] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I1021 10:08:06.718263       1 connection.go:180] GRPC call: /csi.v1.Controller/CreateVolume
I1021 10:08:06.718276       1 connection.go:181] GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-68d35777-2f02-4f61-bf39-02e974be2cfa","parameters":{"clusterID":"rook-ceph-2c","fsName":"arsenal-replicated-pool","mounter":"fuse","pool":"arsenal-replicated-pool-data0"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["debug"]}},"access_mode":{"mode":5}}]}
I1021 10:08:06.757625       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:08:11.763710       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:08:16.769830       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:08:21.776493       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:08:26.783444       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:08:31.789511       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:08:36.795842       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:08:41.801695       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:08:46.807783       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:08:51.813790       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:08:56.821559       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:09:01.827383       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:09:06.834648       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:09:11.840438       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:09:16.846273       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:09:21.852299       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:09:26.859301       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:09:31.866471       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:09:36.874348       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:09:41.880421       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:09:46.886628       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:09:51.892541       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:09:56.898611       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:10:01.905168       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:10:06.912461       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:10:11.921108       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:10:16.928873       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:10:21.934759       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:10:26.941193       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:10:31.946932       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:10:36.718403       1 connection.go:183] GRPC response: {}
I1021 10:10:36.718948       1 connection.go:184] GRPC error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
I1021 10:10:36.719006       1 controller.go:979] Final error received, removing PVC 68d35777-2f02-4f61-bf39-02e974be2cfa from claims in progress
W1021 10:10:36.719015       1 controller.go:886] Retrying syncing claim "68d35777-2f02-4f61-bf39-02e974be2cfa", failure 0
E1021 10:10:36.719037       1 controller.go:908] error syncing claim "68d35777-2f02-4f61-bf39-02e974be2cfa": failed to provision volume with StorageClass "csi-cephfs-test": rpc error: code = DeadlineExceeded desc = context deadline exceeded
I1021 10:10:36.719100       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"csi-cephfs-pvc-test", UID:"68d35777-2f02-4f61-bf39-02e974be2cfa", APIVersion:"v1", ResourceVersion:"4917637", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-cephfs-test": rpc error: code = DeadlineExceeded desc = context deadline exceeded
I1021 10:10:36.953353       1 leaderelection.go:258] successfully renewed lease rook-ceph/rook-ceph-cephfs-csi-ceph-com
I1021 10:10:37.219199       1 controller.go:1196] provision "default/csi-cephfs-pvc-test" class "csi-cephfs-test": started
I1021 10:10:37.222021       1 controller.go:471] CreateVolumeRequest {Name:pvc-68d35777-2f02-4f61-bf39-02e974be2cfa CapacityRange:required_bytes:5368709120  VolumeCapabilities:[mount:<fs_type:"ext4" mount_flags:"debug" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > ] Parameters:map[clusterID:rook-ceph-2c csi.storage.k8s.io/node-stage-secret-name:csi-cephfs-secret csi.storage.k8s.io/node-stage-secret-namespace:rook-ceph csi.storage.k8s.io/provisioner-secret-name:csi-cephfs-secret csi.storage.k8s.io/provisioner-secret-namespace:rook-ceph fsName:arsenal-replicated-pool mounter:fuse pool:arsenal-replicated-pool-data0] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I1021 10:10:37.222085       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"csi-cephfs-pvc-test", UID:"68d35777-2f02-4f61-bf39-02e974be2cfa", APIVersion:"v1", ResourceVersion:"4917637", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/csi-cephfs-pvc-test"
I1021 10:10:37.224433       1 connection.go:180] GRPC call: /csi.v1.Controller/CreateVolume
I1021 10:10:37.224445       1 connection.go:181] GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-68d35777-2f02-4f61-bf39-02e974be2cfa","parameters":{"clusterID":"rook-ceph-2c","fsName":"arsenal-replicated-pool","mounter":"fuse","pool":"arsenal-replicated-pool-data0"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["debug"]}},"access_mode":{"mode":5}}]}
I1021 10:10:37.227986       1 connection.go:183] GRPC response: {}
I1021 10:10:37.228399       1 connection.go:184] GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-68d35777-2f02-4f61-bf39-02e974be2cfa already exists
I1021 10:10:37.228439       1 controller.go:979] Final error received, removing PVC 68d35777-2f02-4f61-bf39-02e974be2cfa from claims in progress
W1021 10:10:37.228448       1 controller.go:886] Retrying syncing claim "68d35777-2f02-4f61-bf39-02e974be2cfa", failure 1
E1021 10:10:37.228467       1 controller.go:908] error syncing claim "68d35777-2f02-4f61-bf39-02e974be2cfa": failed to provision volume with StorageClass "csi-cephfs-test": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-68d35777-2f02-4f61-bf39-02e974be2cfa already exists

**Comment by Madhu-1** [comment]
@peacocktrain can you provide the admin caps,  @ajarr PTAL

**Comment by peacocktrain** [comment]
> @peacocktrain can you provide the admin caps, @ajarr PTAL

sorry，It's not a public cloud

**Comment by Madhu-1** [comment]
@peacocktrain is there a way to reproduce this one

cc @joscollin
