### ISSUE TITLE
Automate upgrade testing

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#696]
Add upgrade testing from `v.1.2.x` to `v.2.0.0`, This will help us to find out any breakage or bugs once users are upgraded from `v.1.2.x` to `v.2.0.0`

**Comment by Madhu-1** [comment]
Steps to be as follow

* Deploy cephcsi `v1.2.x`
* Create PVC
* Bind PVC to an app pod
* Create Snapshot
* Upgrade cephcsi to `master/canary` release
* create a snapshot from PVC
* Mount PVC(created by v1.2.x) to another Application Pod
* Delete All application pods
* Delete PVC
* Delete snapshot created by `v.1.2.x`
* Mount New PVC to application Pod
* Delete application Pod
* Delete PVC

**Comment by Madhu-1** [comment]
@Yuggupta27 would you like to take this up?

**Comment by Madhu-1** [comment]
the Upgrade needs to be done from v2.x to master

**Comment by Yuggupta27** [comment]
Sure Madhu, I'll start working on it.
