### ISSUE TITLE
VolumeFailedDelete missing metadata store configuration to proceed with deleting legacy volume ID

### ISSUE THREAD

**Issue by jisnardo** [ceph/ceph-csi#699]
# Describe the bug #

Unable to use old pv created with v1.0.0 in v1.2.1 (ceph csi-rbd)

kksysn -n csi-rbd get all

Deployed ok

```
NAME                                                    READY   STATUS    RESTARTS   AGE
pod/csi-rbd-ceph-csi-rbd-nodeplugin-9nf2z               3/3     Running   0          48m
pod/csi-rbd-ceph-csi-rbd-nodeplugin-nq7wk               3/3     Running   0          48m
pod/csi-rbd-ceph-csi-rbd-nodeplugin-zpl2k               3/3     Running   0          48m
pod/csi-rbd-ceph-csi-rbd-nodeplugin-zx5vj               3/3     Running   0          48m
pod/csi-rbd-ceph-csi-rbd-provisioner-84b4b6466c-96qhm   4/4     Running   0          48m
pod/csi-rbd-ceph-csi-rbd-provisioner-84b4b6466c-rbczc   4/4     Running   0          48m
pod/csi-rbd-ceph-csi-rbd-provisioner-84b4b6466c-zv2zk   4/4     Running   0          48m
pod/tiller-deploy-58d9859c99-hf5fp                      1/1     Running   0          9d

NAME                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/csi-rbd-ceph-csi-rbd-nodeplugin   ClusterIP   10.90.176.156   <none>        8080/TCP,8090/TCP   9d
service/tiller-deploy                     ClusterIP   10.90.73.81     <none>        44134/TCP           9d

NAME                                             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/csi-rbd-ceph-csi-rbd-nodeplugin   4         4         4       4            4           <none>          9d

NAME                                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/csi-rbd-ceph-csi-rbd-provisioner   3/3     3            3           9d
deployment.apps/tiller-deploy                      1/1     1            1           9d

NAME                                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/csi-rbd-ceph-csi-rbd-provisioner-84b4b6466c   3         3         3       9d
replicaset.apps/tiller-deploy-58d9859c99                      1         1         1       9d
replicaset.apps/tiller-deploy-7c7688cd7                       0         0         0       9d
```

# Environment details #

- csi-rbd v1.2.1
- helm chart https://github.com/ceph/ceph-csi/releases/tag/v1.2.1
- ceph-csi/releases/ceph-csi-1.2.1/deploy/rbd/kubernetes/v1.14+
- kubernetes v1.15.0
- Logs csi-provisioner

```
I1028 10:47:05.166907       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-2c6c1f81-4be9-4003-af4b-72781268ed41", UID:"a1abcf06-f3de-444e-97f1-393e37ccaa74", APIVersion:"v1", ResourceVersion:"7104525", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' rpc error: code = InvalidArgument desc = missing metadata store configuration to proceed with deleting legacy volume ID (csi-rbd-vol-f12f45f7-ee0a-11e9-b34d-6ee881143bd5)
```

# Steps to reproduce #

This happens after upgrade to v1.2.1 from v1.0.0

# Actual results #

New pv / pvc are working fine

# Expected behavior #

There is no way to attach old pv

kksysn -n esm get pvc

```
NAME                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
esm-master-esm-master-0   Lost     pvc-190523bc-caae-447d-a527-627a3ea2ba42   0                         csi-rbd        38m
```

```
Events:
  Type     Reason         Age   From                         Message
  ----     ------         ----  ----                         -------
  Warning  ClaimMisbound  38m   persistentvolume-controller  Two claims are bound to the same volume, this one is bound incorrectly
```

# Additional context #

https://github.com/ceph/ceph-csi/issues/659

https://github.com/ceph/ceph-csi/issues/593

https://github.com/ceph/ceph-csi/issues/593#issuecomment-531580588

add metadatastorage flag to the rbd-provisioner statefulset, This is required to delete the old PVC

This solves the problem?

There is no statefulset for rbd-provisioner for v1.2.1 and ceph csi-rbd

Where to place this?

https://github.com/ceph/ceph-csi/issues/593#issuecomment-533598908

this is missing in rbd template

Thanks in advance.

**Comment by Madhu-1** [comment]
statefulset and deployment files of rbd provisioner are identical there is no much difference you need to add `metadatastorage` flag to `csi-rbdplugin` container flags here https://github.com/ceph/ceph-csi/blob/v1.2.1/deploy/rbd/kubernetes/v1.14%2B/csi-rbdplugin-provisioner.yaml#L100

and also you need to add pod namespace here for `csi-rbdplugin` container https://github.com/ceph/ceph-csi/pull/646/files#diff-061bc3ea36d62d0fde7d014e2a66b94aR76

**Comment by jisnardo** [comment]
1) metadatastorage flag should be like this?

- "--metadatastorage"

or like this?

https://github.com/ceph/ceph-csi/issues/119

- "--metadatastorage=k8s_configmap"

https://github.com/ceph/ceph-csi/blob/master/docs/deploy-rbd.md

Default value: empty

Points to where legacy (1.0.0 or older plugin versions) metadata about provisioned volumes are kept, as file or in as k8s configmap (node or k8s_configmap respectively)

Any example would be great.

2) pod namespace should be added to csi-attacher or csi-rbdplugin?

https://github.com/wilmardo/ceph-csi/blob/f7b8778fbab0e84949bd0e9f63d79c375b03c051/deploy/rbd/kubernetes/v1.13/csi-rbdplugin-provisioner.yaml

https://gitlab.cern.ch/cloud/ceph-csi/blob/master/deploy/rbd/kubernetes/v1.14+/csi-rbdplugin-provisioner.yaml

```
- name: csi-attacher
  image: quay.io/k8scsi/csi-attacher:v1.2.0
  args:
    - "--v=5"
    - "--csi-address=$(ADDRESS)"
    - "--leader-election=true"
    - "--leader-election-type=leases"
  env:
    - name: ADDRESS
      value: /csi/csi-provisioner.sock
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
```
Also, in this file does not exist metadatastorage flag

**Comment by jisnardo** [comment]
Upgraded to https://github.com/ceph/ceph-csi/releases/tag/v3.1.1

**Comment by humblec** [comment]
Thanks @jisnardo !! :+1:
