### ISSUE TITLE
[csi-rbd] detach cloned images from snapshots

### ISSUE THREAD

**Issue by sngchlko** [ceph/ceph-csi#70]
If rbd snapshots have child cloned images, we can't remove the snapshots because of protecting the snapshots. We can use `rbd flatten` for detaching cloned images from snapshots or we can consider using RBD clone v2 feature with later versions of Mimic as well.
The short-term plan would be using `rbd flatten` for detaching cloned images from snapshots.

**Comment by rollandf** [comment]
**To Reproduce**
    1. Create PVC
    2. Create VolumeSnapshot from PVC
    3. Create PVC from VolumeSnapshot   
    4. Delete VolumeSnapshot
    5. RBD snapshot is still present in the Ceph Server

**Comment by Madhu-1** [comment]
closing this as this will be covered in https://github.com/ceph/ceph-csi/issues/675
