### ISSUE TITLE
[CephFS] Support volume cloning

### ISSUE THREAD

**Issue by ajarr** [ceph/ceph-csi#701]
# Describe the feature you'd like to have #

CSI volume cloning is beta in k8s v1.16
https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/
https://kubernetes.io/blog/2019/06/21/introducing-volume-cloning-alpha-for-kubernetes/

CephFS CSI driver should be able to support volume cloning similar to the RBD CSI driver.

**Comment by humblec** [comment]
@joscollin Can you please update where we are with this feature ? we are planning to have this in `2.1.0` .

**Comment by humblec** [comment]
Thanks for the update @joscollin :+1: 
Considering the timeline planned this is a good fit for release 2.1.0

**Comment by joscollin** [comment]
@ajarr @humblec Isn't this a duplicate of https://github.com/ceph/ceph-csi/issues/411? If duplicate, please close this ticket.

**Comment by Madhu-1** [comment]
@joscollin this is not duplicate, This is cloning a PVC from PVC not from cloning from a snapshot

**Comment by humblec** [comment]
@joscollin can you update whats the current state of this functionality support ? to make it clear, are we able to clone from volume to volume ?

**Comment by joscollin** [comment]
No, it is not possible now.

**Comment by humblec** [comment]
CephFS Tracker : https://tracker.ceph.com/issues/45290

**Comment by Madhu-1** [comment]
Moving it to release-v3.1.0

**Comment by humblec** [comment]
This can be closed now as #394 is merged and provide the functionality. :+1:
