### ISSUE TITLE
ceph csi provisioner container has /sys/fs/cgroup/cpuacct,cpu: No such file or directory

### ISSUE THREAD

**Issue by jianglingxia** [ceph/ceph-csi#709]
I deploy the cephfs csi driver,but the provisioner of ceph plugin container has some error;
I used the driver v1.2.0 version,thanks for your help:

20c321d309e2        82f4a0ee2b64                                                 "/usr/local/bin/cephc"   6 days ago          Up 6 days                                                                                                             k8s_csi-cephfsplugin_ceph-csi-cephfsplugin-provisioner-0_default_cf5fd73b-fd1f-11e9-96ab-744aa4028226_0

[root@paas-controller-100-100-100-3:/home/ubuntu]$ docker exec -it 20c321d309e2 /bin/sh
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                 837.8G     25.8G    812.0G   3% /
tmpfs                    62.5G         0     62.5G   0% /sys/fs/cgroup
df: /sys/fs/cgroup/cpuacct,cpu: No such file or directory
df: /sys/fs/cgroup/net_prio,net_cls: No such file or directory
tmpfs                    62.5G         0     62.5G   0% /sys/fs/cgroup
/dev/mapper/ncldata-paasdata
                        837.8G     25.8G    812.0G   3% /logs
/dev/mapper/ncldata-paasdata
                        837.8G     25.8G    812.0G   3% /csi
devtmpfs                 62.5G         0     62.5G   0% /dev
tmpfs                    64.0M         0     64.0M   0% /dev/shm
/dev/mapper/ncldata-paasdata
                        837.8G     25.8G    812.0G   3% /dev/termination-log
/dev/mapper/ncl-root    837.3G      5.6G    831.7G   1% /etc/localtime
/dev/mapper/ncldata-paasdata
                        837.8G     25.8G    812.0G   3% /etc/ceph-csi-config
/dev/mapper/ncl-root    837.3G      5.6G    831.7G   1% /lib/modules
/dev/mapper/ncldata-paasdata
                        837.8G     25.8G    812.0G   3% /etc/hosts
/dev/mapper/ncldata-paasdata
                        837.8G     25.8G    812.0G   3% /etc/hostname
/dev/mapper/ncldata-paasdata
                        837.8G     25.8G    812.0G   3% /etc/resolv.conf
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                    62.5G         0     62.5G   0% /tmp/csi/keys
tmpfs                    62.5G     12.0K     62.5G   0% /run/secrets/kubernetes.io/serviceaccount
ceph-fuse                 2.1T      4.3G      2.1T   0% /paasdata/docker/plugins/cephfs.csi.ceph.com/controller

**Comment by jianglingxia** [comment]
@Madhu-1
can review this issue?thanks

**Comment by Madhu-1** [comment]
@jianglingxia can you paste the error message from container

**Comment by jianglingxia** [comment]
the provisioner cephfs plugin  container i command the df -h 
[root@paas-controller-100-100-100-3:/home/ubuntu]$ docker exec -it 2b28f6817f96 /bin/sh
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                 837.8G     26.2G    811.6G   3% /
tmpfs                    62.5G         0     62.5G   0% /sys/fs/cgroup
df: /sys/fs/cgroup/cpuacct,cpu: No such file or directory
df: /sys/fs/cgroup/net_prio,net_cls: No such file or directory


and the daemonset pod cephfs-plugin container is  df -h 

df: /sys/fs/cgroup/net_prio,net_cls: No such file or directory
df: /sys/fs/cgroup/cpuacct,cpu: No such file or directory

**Comment by Madhu-1** [comment]
is this causing any issue during PVC creation or mounting? this is nothing to do with cephfs. `sys` module is shared between the host and container https://github.com/ceph/ceph-csi/blob/v1.2.1/deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin.yaml#L93

**Comment by jianglingxia** [comment]
my yaml use the document 
now my ds container dir ls

/ # cd /sys/fs/cgroup/
/sys/fs/cgroup # ls
blkio             cpu,cpuacct       cpuset            freezer           memory            net_cls,net_prio  perf_event        systemd
cpu               cpuacct           devices           hugetlb           net_cls           net_prio          pids


can you compared with your container?really thanks

**Comment by Madhu-1** [comment]
https://github.com/ceph/ceph-csi/blob/v1.2.1/deploy/cephfs/kubernetes/v1.13/csi-cephfsplugin-provisioner.yaml#L104 provisioner also requires this value

**Comment by jianglingxia** [comment]
yes,my provisioner and ds both use the value,but two container error

**Comment by Madhu-1** [comment]
@jianglingxia we have not seen this issue  till now, no idea  what causing this issue

**Comment by jianglingxia** [comment]
@Madhu-1
cephfs csi driver can run as nonroot use and Provide services？
thanks

**Comment by Madhu-1** [comment]
@jianglingxia what is the use-case? why do you want to run as nonroot user?

**Comment by Madhu-1** [comment]
please open a new feature required so that we can  discuss about  it and closing this issue as this is nothing to do with ceph-csi deployment

**Comment by jianglingxia** [comment]
@ Madhu-1
 the error follow, the community use docker or runc? and if support docker then docker version is ?
my project use docker v1.12.6 and can I delete the hostpath: /sys if deploy the ds and sts ?
df: /sys/fs/cgroup/cpuacct,cpu: No such file or directory
df: /sys/fs/cgroup/net_prio,net_cls: No such file or directory
