### ISSUE TITLE
cephfs csi driver can run as nonroot use and Provide services？

### ISSUE THREAD

**Issue by jianglingxia** [ceph/ceph-csi#714]
# Describe the feature you'd like to have #
now the cephfs csi driver run as root user,can the ds and sts run as nonroot?
What new functionality do you want?
now the cephfs csi driver run as root user,can the ds and sts run as nonroot?
# What is the value to the end user? (why is it a priority?) #

How would the end user gain value from having this feature?

# How will we know we have a good solution? (acceptance criteria) #

Add a list of criteria that should be met for this feature to be useful

# Additional context #

**Comment by Madhu-1** [comment]
@jianglingxia please  Fill all the relevant fields in the feature request template

**Comment by jianglingxia** [comment]
in my project that user think use root user maybe not security，so the community now can support the feature use nonroot run ds and sts to provider cephfs volume create and delete and mount and umount ?
if ds and sts can not run nonroot and why?
really thanks

**Comment by Madhu-1** [comment]
@ajarr ^^

**Comment by ajarr** [comment]
@joscollin ^^

**Comment by joscollin** [comment]
@jianglingxia Can you explain what are `ds` and `sts`? It is possible to create and delete a Volume using a non-root user in CephFS.

**Comment by Madhu-1** [comment]
@joscollin  cephfsplugin `daemonset(ds)` which is responsible for mounting and unmounting cephfs subvolumeto/from  app pod 
  cephfsplugin provisioner `statefulset(sts)` which is responsible for creating/deleting cephfs subvolume

**Comment by joscollin** [comment]
Does any one of these `daemonset(ds)` or `statefulset(sts)` work with a non-root user from your side? Especially `statefulset(sts)`?

**Comment by Madhu-1** [comment]
I have not tested this one, but if we are able to execute ceph and rbd command without root user it should be possible ideally

**Comment by joscollin** [comment]
Yeah those volume/subvolume operations should work with a non-root user. 

@jianglingxia Could you please give us more clarity on this issue?

**Comment by jianglingxia** [comment]
thanks for all of you reply!
yeah,ds provider mount and umount cephfs ,sts provider create and delete cephfs volume
if cephfs command can execute non-root user success then maybe ds and sts can run non-root,
but the community can support it?
or can you give me some advice  that if i modify the ds and yaml ,use PodSecurityPolicy
 runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
? but i not tested
thanks for your advice!

**Comment by joscollin** [comment]
@Madhu-1 ^^

**Comment by Madhu-1** [comment]
@jianglingxia please give a try and let us know the result!

**Comment by jianglingxia** [comment]
/ # cat /etc/passwd
root:x:0:0:root:/root:/bin/ash
storage:x:1000:1000:Linux User,,,:/home/storage:/bin/sh

/ # su storage
/ $ whoami
storage
/ $ ceph-fuse /paasdata/docker/plugins/cephfs.csi.ceph.com/controller -m 100.100.100.140,100.100.100.159,100.100.100.157 -c /etc/ceph/ceph.conf -n client.admi
n --key=AQBmVY1dAAAAABAA57Xt8+lGfYloaNtxRztmhA== -r / -o nonempty
ceph-fuse[817]: starting ceph client
ceph-fuse[817]: ceph mount failed with (1) Operation not permitted

**Comment by joscollin** [comment]
@jianglingxia You may not have permissions. Follow this document [1], Check your keys, check if the user has write access to mountpoint.

[1] https://docs.ceph.com/docs/master/cephfs/fuse/
