### ISSUE TITLE
how to configurate this ceph rbd to become a server for remote client?

### ISSUE THREAD

**Issue by hicker-kin** [ceph/ceph-csi#719]
i want install this ceph rbd and configurate it as a server for remote user?

**Comment by nixpanic** [comment]
ceph-csi are just some tools that acts on requests from a container orchestrator, and allocate or mount an RBD image on a [Ceph](https://ceph.io) cluster. You will need to have a working Ceph cluster before ceph-csi can be used.

If you are running on Kubernetes, you may want to have a look at [Rook](rook.io) to setup your Ceph cluster.

**Comment by Madhu-1** [comment]
as @nixpanic explained. this issue cannot be addressed with ceph-csi. closing this
