### ISSUE TITLE
Store additional metadata about RBD Image owner(PVC name) in RBD Image

### ISSUE THREAD

**Issue by krmayankk** [ceph/ceph-csi#72]
implement the following proposal for csi-rbd and in core kubernetes for rbd provisioner 

https://github.com/kubernetes/community/pull/1790/files

I wrote this proposal and was interested in working on this , but since we are no longer using RBD,  i do not have time to work on this. Putting this here so that someone can take it from here.

**Comment by humblec** [comment]
@krmayankk would you like to send a PR on this ?

**Comment by Madhu-1** [comment]
PVC name can be passed to CSI driver from external-provisioner https://github.com/kubernetes-csi/external-provisioner/pull/399, this can be easily done I believe, we need to decide to add it to metadata or store the pvcname-backend image mapping in omap.

**Comment by cxhuawei** [comment]
I think it is fine to store it in metadata. What is the pros by storing in omap ?  @Madhu-1

**Comment by ShyamsundarR** [comment]
> I think it is fine to store it in metadata. What is the pros by storing in omap ? @Madhu-1

We also have the use case of [RBD-Mirroring](https://github.com/ceph/ceph-csi/issues/676) and would need a similar manner to do this for CephFS subvolumes.

Currently we are thinking along the lines of naming the image with the required [`pvcname-namespace-<uuid>`](https://github.com/ceph/ceph-csi/pull/853) or similar constructs. Leveraging image metadata, would mean leveraging xattrs for subvolumes in the CephFS space (or similar).

The desire would be to create a common manner of accessing the metadata, and a conclusion on the approach is not yet made. We may need more time to decide on this as we work through some of the other issues and features.
