### ISSUE TITLE
e2e not destroy some resources when kubectl namespace is not 'default'

### ISSUE THREAD

**Issue by woohhan** [ceph/ceph-csi#723]
# Describe the bug #
e2e not destroy some resources when kubectl namespace is not 'default'. It caused because some commands are executed by `framework.RunKubectl` but others are executed by `c.CoreV1().ConfigMaps("default").Create(&cm)`. Firstone (RunKubectl) is executed with kubeconfig namespace however second one is not.

# Environment details #
when re-run e2e tests, it failed because of configmap already exists error.

```shell
      Expected
          <*errors.StatusError | 0xc0004e2960>: {
              ErrStatus: {
                  TypeMeta: {Kind: "", APIVersion: ""},
                  ListMeta: {
                      SelfLink: "",
                      ResourceVersion: "",
                      Continue: "",
                      RemainingItemCount: nil,
                  },
                  Status: "Failure",
                  Message: "configmaps \"ceph-csi-config\" already exists",
                  Reason: "AlreadyExists",
                  Details: {
                      Name: "ceph-csi-config",
                      Group: "",
                      Kind: "configmaps",
                      UID: "",
                      Causes: nil,
                      RetryAfterSeconds: 0,
                  },
                  Code: 409,
              },
          }
      to be nil
```

# Steps to reproduce #
1. kubectl config set-context --current --namespace other-namespace
2. running e2e test
3. re-running e2e test

# Actual results #
The e2e test is successfully exited, however some resource is not destroyed correctly.

# Expected behavior #
e2e test runs

# Additional context #
I think We have two choices.
1) Create namespace like 'ceph-csi' and use this in all code
2) just do not use c.CoreV1()...

**Comment by Madhu-1** [comment]
CSI templates are working with the default namespace,  and all the resources are created in default namespace, need to test how e2e behaves with other namespaces (adding a new flag to pass namespace should work

**Comment by WoohyungHan** [comment]
> CSI templates are working with the default namespace, and all the resources are created in default namespace, need to test how e2e behaves with other namespaces (adding a new flag to pass namespace should work)

@Madhu-1 Yes, for now everything works on the default namespace. but some commands are executed with `framework.RunKubectl` command. The ploblem is, some commands are not executed with default namespace. This is caused If we set our kubectl config to use other namespace(kubectl config set-context --current --namespace rook-ceph), from now on, all kubectl command will be executed in rook-ceph namespace. 

this is how to reproduce

1. kubectl config set-context --current --namespace rook-ceph
2. runing e2e test
3. re-runing e2e test

some resources are created with default namespace(`c.CoreV1().ConfigMaps("default").Create(&cm)`) but others not (`framework.RunKubectl`)
