### ISSUE TITLE
Add support ReadOnlyMany for rbd

### ISSUE THREAD

**Issue by D1abloRUS** [ceph/ceph-csi#725]
# Describe the feature you'd like to have #

Add support ReadOnlyMany for rbd

# What is the value to the end user? (why is it a priority?) #

Pods on different nodes can mount ceph rbd volume on read

**Comment by Madhu-1** [comment]
@D1abloRUS can you more information about the use-case?

**Comment by D1abloRUS** [comment]
@Madhu-1 I have data, I need to run several pods on different nodes, and to read this data, without ReadOnlyMany it is impossible

**Comment by troeger** [comment]
@Madhu-1 We operate a Kubernetes cluster for machine learning workload. Some of the training jobs operate on millions of single text files, which currently must be stored on a Ceph file system for concurrent read access. The amount of files puts heavy stress on the MDS daemons, especially when multiple training pods access this data in parallel all the time.

A ReadOnlyMany support for volumes would allow us to store the training data directly on a shared volume. This would remove the MDS daemons from the performance equation.

**Comment by dillaman** [comment]
> A ReadOnlyMany support for volumes would allow us to store the training data directly on a shared volume. This would remove the MDS daemons from the performance equation.

How would you get the data into the ROX RBD-backed filesystem? Would you plan to create a new ROX volume from a snapshot?

**Comment by WoohyungHan** [comment]
If you app use filesystem multiple active MDS daemon would be better. but if the app use block device itself, ROX rbd can be considered.

**Comment by troeger** [comment]
@dillaman We didn't thought about this. The obvious first choice would be a job that fills the volume first. The data then usually persists forever in an unmodified state after this initial copy step.

@WoohyungHan We have that, 4 active MDS daemons and their backups. They still run under full load. Maybe this is only a case for MDS tuning, but without ROX volumes, we simply have no alternative to compare with.

**Comment by PavloZabudskyi** [comment]
When deployment pod is scheduled at node that it lost, it can't be reschedulated at other node without ReadOnlyMany option.

```
wordpress-6bd7cdd99f-7rpxr   0/1     ContainerCreating   0          26m
wordpress-6bd7cdd99f-rpgx2   1/1     Terminating         0          62m
```
```
  Normal   Scheduled           <unknown>             default-scheduler        Successfully assigned wordpress/wordpress-6bd7cdd99f-7rpxr to server1
  Warning  FailedAttachVolume  27m                   attachdetach-controller  Multi-Attach error for volume "pvc-a1225447-1452-43cb-95dd-aa6a50947204" Volume is already used by pod(s) wordpress-6bd7cdd99f-rpgx2
  Warning  FailedMount         3m13s (x10 over 25m)  kubelet, server1         Unable to attach or mount volumes: unmounted volumes=[wordpress-data], unattached volumes=[wordpress-data default-token-dq57z]: timed out waiting for the condition
  Warning  FailedMount         70s (x3 over 23m)     kubelet, server1         Unable to attach or mount volumes: unmounted volumes=[wordpress-data], unattached volumes=[default-token-dq57z wordpress-data]: timed out waiting for the condition
```

PVC uses SC with replica 3, so data isn't lost.

**Comment by golpa** [comment]
Just to add a me too. 

In our use case we have a small set of utility binaries that we'd like to include in a lot of pods. It would be nice to create a volume with all the binaries once and then be able to mount that PVC across our pods as read only.

We tried alternatives such as storing the binaries as ConfigMaps but as the max size of ConfigMaps is too small most of the binaries can't be stored

**Comment by nixpanic** [comment]
#947 is a (work-in-progress) e2e test that creates a PVC with two access-modes: RWO and ROX. After populating the PVC through a single pod, two new pods start and consume the contents.
