### ISSUE TITLE
Add checking for rook rbdpool and cephfilesystem

### ISSUE THREAD

**Issue by woohhan** [ceph/ceph-csi#730]
# Describe the feature you'd like to have #
Currently in the rook deploy script, we only check ceph health. We can add checking rbd pool and cephfilesystem for safety. Thanks for suggestion @Madhu-1 

# What is the value to the end user? (why is it a priority?) #
NONE

# How will we know we have a good solution? (acceptance criteria) #
We can ensure the rook is ready to rbd/cephfs test.

# Additional context #
NONE

**Comment by Madhu-1** [comment]
@WoohyungHan would you like to work on this one? if yes i can assign this to you

**Comment by WoohyungHan** [comment]
@Madhu-1 sure, i will

**Comment by Madhu-1** [comment]
done, Thanks for picking this up
