### ISSUE TITLE
update `kubectl apply` to `kubectl create` in e2e test

### ISSUE THREAD

**Issue by WoohyungHan** [ceph/ceph-csi#731]
# Describe the feature you'd like to have #
We currently use `kubectl apply -f` command but latest kubernetes warn to use `kubectl create -f`.

# What is the value to the end user? (why is it a priority?) #
NONE

# How will we know we have a good solution? (acceptance criteria) #
NONE

# Additional context #
Because `kubectl apply -f` is working when object already exists, but `kubectl create -f` is not. we need to more careful to delete object. 
- Rook cluster role, cluster role binding

Thanks for suggestion :+1:  @Madhu-1

**Comment by Madhu-1** [comment]
@WoohyungHan would you like to work on this one? if yes i can assign this to you

**Comment by WoohyungHan** [comment]
sure, i wilk @Madhu-1

**Comment by Madhu-1** [comment]
done, Thanks for picking this up
