### ISSUE TITLE
attacher.Attach failed: volumeattachments.storage.k8s.io is forbidden

### ISSUE THREAD

**Issue by windayski** [ceph/ceph-csi#734]
# Describe the bug #

I installed the ceph-csi driver and create PVC successfully. But it cannot be attached to a pod with this error in kubelet's log.

```
Dec 09 14:58:06 master1 kubelet[20473]: E1209 14:58:06.803672   20473 csi_attacher.go:93] kubernetes.io/csi: attacher.Attach failed: volumeattachments.storage.k8s.io is forbidden: User "system:node:master1" cannot create resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope: can only get individual resources of this type
```

# Environment details #

- Image/version of Ceph CSI driver v1.2.1
- Kubernetes cluster version: v1.14.3

# Steps to reproduce #

Install ceph-csi driver, create a pvc, attach it to a pod, 
and then Attach failed

# Additional context #

I found an similiar inssue.  https://github.com/LINBIT/linstor-csi/issues/4
If the kubelets starts with --enable-controller-attach-detach=false option, then I failed to attach.
But if the kubelets starts with --enable-controller-attach-detach=true option, then it worked fine.

I am wondering the ceph-csi can only work with enable-controller-attach-detach=true ??

**Comment by Madhu-1** [comment]
@windayski can you provide `kubectl get po` output?

**Comment by Madhu-1** [comment]
which templates you have used for the deployment?

**Comment by Madhu-1** [comment]
we need `enable-controller-attach-detach=true` to take care of RWO issues

**Comment by windayski** [comment]
@Madhu-1 The status of pod is ContainerCreating,

```
csi-rbd-demo-pod                            0/1     ContainerCreating   0          36m
```

And I deployed the csi-rbdplugin follow the guide:  https://github.com/ceph/ceph-csi/blob/master/docs/deploy-rbd.md

I am really a noob.  You said “we need enable-controller-attach-detach=true to take care of RWO issues”， did it mean this is not a bug? And the flag must be enable-controller-attach-detach=true?

**Comment by Madhu-1** [comment]
as `enable-controller-attach-detach` default value is `true` in kubelet, I don't think its a bug, may I know the reason for setting `enable-controller-attach-detach` to false?

one more thing if you are using v1.2.1 please use template from https://github.com/ceph/ceph-csi/tree/v1.2.1

**Comment by windayski** [comment]
@Madhu-1  Thanks for your reply.

Flexvolume plugins are used in some of our clusters.  If we set `enable-controller-attach-detach` to true, the drivers on each nodes cannot get attach/detach call.

**Comment by Madhu-1** [comment]
if you want to set  enable-controller-attach-detach=false try creating CSIObject as mentioned in   https://kubernetes-csi.github.io/docs/csi-driver-object.html

the yaml will look like 
```yaml
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: rbd.csi.ceph.com
spec:
  attachRequired: false --> try both true and false
  podInfoOnMount: false
```

if `attachRequired` is set to false you will end up in issue like https://github.com/rook/rook/pull/4332
