### ISSUE TITLE
Kubernetes sidecar leaders and its impact on controller plugin operations, needs understanding/clarification

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#742]
We now will have 4 side cars performing [leader election](https://github.com/ceph/ceph-csi/blob/8a16f740d68b3f31b1955f81f1a4994aa72fd68b/deploy/rbd/kubernetes/v1.14%2B/csi-rbdplugin-provisioner.yaml#L38-L76), and hence, **to my understanding**, each sidecar can determine in isolation that one of the many (two in the default case) available controller plugin instances are the leader for the said sidecar.

This defeats the controller locks against volumes if different operations will reach different controller plugins. This either needs to be understood better (IOW, the problem does not exist) or we may need to work with kubernetes CSI side cars to see how best to ensure all side car leaders land on the same instance.

For example it could mean the provisioner leader instance is on a different node than the snapshotter instance, and so the locks that we take between `DeleteVolume` and `CreateSnapshot` will not contend and can cause unwanted repercussions.

If this is a problem, we need to find ways to mitigate the issue, or look at how we can influence the various sidecars to a single leader (same lock name maybe?).

**Comment by WoohyungHan** [comment]
+1 very interesting problem. But I think `solving by same lock name` can decrease overall performance. Could we use per volume lock? I think there is no influence multiple sidecars working on individual, different volume.

**Comment by Madhu-1** [comment]
can be fixed by running single CSI sidecar images, more info at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-sig-storage-wg-csi/qZvuOlCME5Y/YzKuurLVBwAJ

**Comment by Madhu-1** [comment]
> +1 very interesting problem. But I think `solving by same lock name` can decrease overall performance. Could we use per volume lock? I think there is no influence multiple sidecars working on individual, different volume.

currently, we are locking per  volume in CSI  container and its in-memory lock, as the lock is in memory and not centralized lock, we can hit the issue like on one provisioner pod we will be deleting the volume and in another provisioner pod we will  be resizing it or cloning from it( possible to hit this issue)

**Comment by ShyamsundarR** [comment]
> > +1 very interesting problem. But I think `solving by same lock name` can decrease overall performance. Could we use per volume lock? I think there is no influence on multiple sidecars working on an individual, different volume.
> 
> per volume based lock in CSI container is what currently doing and its in-memory lock, as the lock is in memory and not centralized lock, we can hit the issue like on one provisioner pod we will be deleting the volume and in another provisioner pod we will be resizing it or cloning from it( possible to hit this issue)

The lock name I was referring to was to force the sidecars to contend for the same [leader lock](https://github.com/kubernetes-csi/csi-lib-utils/blob/3db811614bd14d294eb08069b7ac59bd46f69139/leaderelection/leader_election.go#L66-L69), it was not related to the volume names or ID based locks in the CSI plugin. Clarifying this for @WoohyungHan.

Also, the thought of using the same lock name is just a "thought", without any investigation on the feasibility and limitations of the same.
