### ISSUE TITLE
RBD Encryption improvements that need addressing

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#744]
1) Ensure volume creation is complete before responding with a volume match for a `CreateVolume` request

Comment: https://github.com/ceph/ceph-csi/pull/697/files?file-filters%5B%5D=.go#r356896828

The intention is to note the status of creation and later, either complete the creation if certain steps are missed (like adding the encryption attribute to the image) or garbage collect the image and the reservation, and create afresh.

This provides a defense against any duplicate responses that the CO may have processed, to ensure the controller only responded when an entire `CreateVolume` call is complete.

2) `processEncryptedDevice` should check if device is already encrypted, prior to invoking `encryptDevice` and update encryption parameter on the image.

Comment: https://github.com/ceph/ceph-csi/pull/697/files?file-filters%5B%5D=.go#r355185194

This is to ensure if the plugin fails between calling `EncryptVolume` and `SaveRbdImageEncryptionStatus` in `encryptDevice`, we do not encrypt it again (which will not happen in the current code, as the device format will not be an empty string in `processEncryptedDevice`), but we need to update the `SaveRbdImageEncryptionStatus` on detecting such cases.

3) Optimize checks in `detachRBDImageOrDeviceSpec` to avoid checking for encrypted devices based on the image stash

Comment: https://github.com/ceph/ceph-csi/pull/697/files?file-filters%5B%5D=.go#r355185378

**Comment by vasyl-purchel** [comment]
@ShyamsundarR I'd like to re-iterate on first task here:

current implementation in case of successful volume creation but failed image-meta step will get [here](https://github.com/ceph/ceph-csi/blob/master/pkg/rbd/controllerserver.go#L152-L158)
And before returning successful response it will call `ensureEncryptionMetadataSet` which will update this image-meta key to make sure that image is ready to be used for attach process.

Does this satisfy the requirement?

The only place I can see this to make things bad is if volume was already attached and encrypted and then CreateVolume for the same volume comes in and forces metadata to be updated to `requiredEncryption`, but I don't see how CreateVolume request can come after volume was attached at least once.

**Comment by fanchenxu-ship** [comment]
> @ShyamsundarR I'd like to re-iterate on first task here:
> 
> current implementation in case of successful volume creation but failed image-meta step will get [here](https://github.com/ceph/ceph-csi/blob/master/pkg/rbd/controllerserver.go#L152-L158) And before returning successful response it will call `ensureEncryptionMetadataSet` which will update this image-meta key to make sure that image is ready to be used for attach process.
> 
> Does this satisfy the requirement?
> 
> The only place I can see this to make things bad is if volume was already attached and encrypted and then CreateVolume for the same volume comes in and forces metadata to be updated to `requiredEncryption`, but I don't see how CreateVolume request can come after volume was attached at least once.

hi [vasyl-purchel](https://github.com/vasyl-purchel), can you tell me what is image-meta? and where can i find it ?

**Comment by vasyl-purchel** [comment]
hi @fanchenxu-ship , image-meta is metadata of an rbd image in ceph, so can be found with `rbd image-meta get <image> <key>` command
