### ISSUE TITLE
Honor mount options in NodeStage RPC as well

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#757]
Currently it was decided[1] not to honor mount options in NodeStage RPC request, and we mount the volume with default options.

While discussing regarding the `_netdev` options and what ceph-csi does with mount options with @gnufied, it was brought to my attention that we should honor mount options in the NodeStage request itself.

Opening this issue to add justifications around the same, and to decide and implement honoring mount options during NodeStage request.

[1] Issue discussion:
  - https://github.com/ceph/ceph-csi/pull/576#issuecomment-528030567
  - https://github.com/ceph/ceph-csi/pull/576#issuecomment-528793122

**Comment by humblec** [comment]
@ShyamsundarR closing this for now, as the mount options are respected in the rpc calls.

**Comment by Madhu-1** [comment]
Reopening as mount options are not honored in cephfs NodeStage RPC call

**Comment by Madhu-1** [comment]
```
message NodeStageVolumeRequest {


 // Volume capability describing how the CO intends to use this volume.
  // SP MUST ensure the CO can use the staged volume as described.
  // Otherwise SP MUST return the appropriate gRPC error code.
  // This is a REQUIRED field.
  VolumeCapability volume_capability = 4;
```

The above is  not considered for cephfs.

**Comment by jsafrane** [comment]
I talked to @humblec, the reason that mount opts at NodeStage are not used is that CephFS CSI driver supports both kernel and fuse and there is a fallback mechanism if one of them does not work. So the PV/StorageClass author can't be really sure if the options should be for kernel or fuse driver.

I think that's cluster admin problem - they must make sure that the mount options work, i.e. make sure that the right kernel module is installed or that it's not and fuse is available. For me, NodeStage mount options may be an important mechanism how to [speed up SELinux relabeling](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1710-selinux-relabeling).

**Comment by humblec** [comment]
Thanks @jsafrane for bringing this up :+1: . Considering ceph csi driver also has to respect the generic usage of mount options , this is something we could try to address in upcoming releases. We have to make sure we are not breaking backward compatibility with existing SC params such as "kernelmountoptions...etc". One thought process here is to just append generic mount options to existing array of mount options constructed from the SC. if there is an incompatible mount options the mount may fail, but thats something we could live with considering the fact that, all these registration of the options comes from cluster admin and not from user.  eventually we can start deprecating the sc mounter specific params.

**Comment by Rakshith-R** [comment]
This is in alpha in recent k8s release, We will need to incorporate it. 

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#efficient-selinux-volume-relabeling

**Comment by Madhu-1** [comment]
This in in beta https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#efficient-selinux-volume-relabeling good time to revisit this one

**Comment by Rakshith-R** [comment]
-Moving forward CephCSI will honour MountOptions passed during NodeStage request and will pass it during mounting regardless of the mounter(kernel or ceph fuse) used.

-The existing `kernelMountOptions`  and `fuseMountOptions` in storageclass parameters will be marked deprecated in release 3.9. In release 3.10, these options will no longer be passed while PVC creation happens.

- Pre-existing PVC having `kernelMountOptions`  and `fuseMountOptions`  will still be honoured and passed together with the MountOptions at nodestage request.

- Bind Mounting at nodepublish will no longer receive any additional mount options.

@nixpanic @Madhu-1 Does this sound okay to you ?

**Comment by Madhu-1** [comment]
> -Moving forward CephCSI will honour MountOptions passed during NodeStage request and will pass it during mounting regardless of the mounter(kernel or ceph fuse) used.
> 
> -The existing `kernelMountOptions` and `fuseMountOptions` in storageclass parameters will be marked deprecated in release 3.9. In release 3.10, these options will no longer be passed while PVC creation happens.
> 
> * Pre-existing PVC having `kernelMountOptions`  and `fuseMountOptions`  will still be honoured and passed together with the MountOptions at nodestage request.
> * Bind Mounting at nodepublish will no longer receive any additional mount options.
> 

Do you mean fuseMount and KernelMount options (only for older PVC). if user wants they can still recreate the PV with mount options and csidriver will use it.

> @nixpanic @Madhu-1 Does this sound okay to you ?

**Comment by Rakshith-R** [comment]
> > -Moving forward CephCSI will honour MountOptions passed during NodeStage request and will pass it during mounting regardless of the mounter(kernel or ceph fuse) used.
> > -The existing `kernelMountOptions` and `fuseMountOptions` in storageclass parameters will be marked deprecated in release 3.9. In release 3.10, these options will no longer be passed while PVC creation happens.
> > 
> > * Pre-existing PVC having `kernelMountOptions`  and `fuseMountOptions`  will still be honoured and passed together with the MountOptions at nodestage request.
> > * Bind Mounting at nodepublish will no longer receive any additional mount options.
> 
> Do you mean fuseMount and KernelMount options (only for older PVC). 

I want to keep it backward compatible so that the user will not have to manually edit all the existing older PVs in the cluster.

>if user wants they can still recreate the PV with mount options and csidriver will use it.

If the user has Options specified, then he will have to undergo the tedious process even if he doesn't want to do it.

**Comment by Rakshith-R** [comment]
> -Moving forward CephCSI will honour MountOptions passed during NodeStage request and will pass it during mounting regardless of the mounter(kernel or ceph fuse) used.
> 
> -The existing `kernelMountOptions` and `fuseMountOptions` in storageclass parameters will be marked deprecated in release 3.9. In release 3.10, these options will no longer be passed while PVC creation happens.
> 
> * Pre-existing PVC having `kernelMountOptions`  and `fuseMountOptions`  will still be honoured and passed together with the MountOptions at nodestage request.
> * Bind Mounting at nodepublish will no longer receive any additional mount options.
> 


MountOptions is expected to be passed during both NodeStage(applies for all the pods on node/all containers in pod) and NodePublish(applies for specific containers).

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/csi_mock/csi_selinux_mount.go#L77

Therefore we will not be able to pass cephfs kernel or ceph fuse specific mount options through pv.spec.mountOptions.
We will need to still preserve these options.

#3902 will only be adding pv.Spec.MountOptions to NodeStage request and no other changes will be made.
