### ISSUE TITLE
Add a bot to check commit messages and DCO

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#773]
* Add a bot to check better commit messages which help to review PR's

sample commit message taken from https://eslint.org/docs/developer-guide/contributing/pull-requests#step-2-make-your-changes

```yaml
Tag: Short description

Longer description here if necessary

Tag is one of the following:

Fix - for a bug fix.
Update - either for a backward-compatible enhancement or for a rule change that adds reported problems.
New - implemented a new feature.
Breaking - for a backward-incompatible enhancement or feature.
Docs - changes to documentation only.
Build - changes to build process only.
Upgrade - for a dependency upgrade.
Chore - for refactoring, adding tests, etc. (anything that isn't user-facing).
```
  
* Add a  DCO bot https://github.com/apps/dco
  - This App enforces the Developer Certificate of Origin (DCO) on Pull Requests. It requires all commit messages to contain the Signed-off-by line with an email address that matches the commit author.

**Comment by hswong3i** [comment]
@Madhu-1 so something like this?

* Upgrade: csi-resizer from v0.3.0 to v0.4.0
* Upgrade: csi-node-driver-registrar from v1.1.0 to v1.2.0
* Upgrade: csi-snapshotter from v1.2.1 to v1.2.2
* Upgrade: csi-attacher from v1.2.0 to v2.0.0

**Comment by Madhu-1** [comment]
@hswong3i sounds good, please take care of longer description in commit message

**Comment by hswong3i** [comment]
> @hswong3i sounds good, please take care of longer description in commit message

Yes that had be done, too. Hopefully in recommended format. Please kindly double confirm.

**Comment by Madhu-1** [comment]
@humblec I don't have the permission to add bot to this project, can you please resolve this one?

**Comment by humblec** [comment]
@Madhu-1 let me check

**Comment by humblec** [comment]
The bot is working now !! thanks !

**Comment by Madhu-1** [comment]
@humblec Still need to add commitlint bot https://probot.github.io/apps/commitlint/

**Comment by Madhu-1** [comment]
closing as both bots added now.
