### ISSUE TITLE
Failed to resize an rbd volume,  got error: provided secret is empty

### ISSUE THREAD

**Issue by windayski** [ceph/ceph-csi#783]
# Describe the bug #

I used cephcsi:canary to create an RBD volume,  and edit the size of this pvc. But the resize is failed.
Did I do anything wrong?

I got a message from csi-rbdplugin container as below:

```
I0113 07:54:28.024065       1 connection.go:182] GRPC call: /csi.v1.Controller/ControllerExpandVolume
I0113 07:54:28.024220       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"test", Name:"rbd-pvc-canary", UID:"7f4b53b3-35ce-11ea-ad2f-eeeeeeeeeeee", APIVersion:"v1", ResourceVersion:"83010250", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-7f4b53b3-35ce-11ea-ad2f-eeeeeeeeeeee
I0113 07:54:28.024093       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":16106127360},"volume_id":"0001-0024-12734c43-4005-4aef-96e7-dfff3fcadd93-0000000000000002-8578e604-35ce-11ea-b10e-caaecb73218b"}
I0113 07:54:28.028471       1 connection.go:185] GRPC response: {}
```

output of 
kubectl get pvc rbd-pvc-canary -n test -o yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rbd-csi
  creationTimestamp: "2020-01-13T06:32:40Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: rbd-pvc-canary
  namespace: test
  resourceVersion: "83092524"
  selfLink: /api/v1/namespaces/test/persistentvolumeclaims/rbd-pvc-canary
  uid: 7f4b53b3-35ce-11ea-ad2f-eeeeeeeeeeee
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: csi-rbd
  volumeMode: Filesystem
  volumeName: pvc-7f4b53b3-35ce-11ea-ad2f-eeeeeeeeeeee
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-01-13T10:44:28Z"
    status: "True"
    type: Resizing
  phase: Bound
```

# Environment details #

- Image/version of Ceph CSI driver: canary, master branch
- Kubernetes cluster version: v1.14.3

# Expected behavior #

The pvc resize successfully.

**Comment by Madhu-1** [comment]
you might be missing expand secret https://github.com/ceph/ceph-csi/blob/master/examples/rbd/storageclass.yaml#L32-L33

**Comment by windayski** [comment]
@Madhu-1  Thanks.  I missed the expand secret. But after added that secret in the storageClass, it still didn't work. 
The error logs are same with before.

```
I0114 03:00:06.075480       1 utils.go:157] ID: 47 Req-ID: 0001-0024-12734c43-4005-4aef-96e7-dfff3fcadd93-0000000000000002-d0b1faff-3678-11ea-af5c-eaf28c962a2f GRPC call: /csi.v1.Controller/ControllerExpandVolume
I0114 03:00:06.075511       1 utils.go:158] ID: 47 Req-ID: 0001-0024-12734c43-4005-4aef-96e7-dfff3fcadd93-0000000000000002-d0b1faff-3678-11ea-af5c-eaf28c962a2f GRPC request: {"capacity_range":{"required_bytes":18253611008},"volume_id":"0001-0024-12734c43-4005-4aef-96e7-dfff3fcadd93-0000000000000002-d0b1faff-3678-11ea-af5c-eaf28c962a2f"}
E0114 03:00:06.077476       1 utils.go:161] ID: 47 Req-ID: 0001-0024-12734c43-4005-4aef-96e7-dfff3fcadd93-0000000000000002-d0b1faff-3678-11ea-af5c-eaf28c962a2f GRPC error: rpc error: code = Internal desc = provided secret is empty
```

**Comment by Madhu-1** [comment]
Please provide storageclass and cephcsi image tag you used for testing

**Comment by windayski** [comment]
cephcsi image is built by myself using codes on Master branch.
storageClass:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    displayName: csi-rbd
  name: csi-rbd
parameters:
  clusterID: 12734c43-4005-4aef-96e7-dfff3fcadd93
  imageFormat: "2"
  imageFeatures: layering
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: ceph-secret-csi
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/controller-expand-secret-name: ceph-secret-csi
  csi.storage.k8s.io/controller-expand-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: ceph-secret-csi
  csi.storage.k8s.io/node-stage-secret-namespace: default
  pool: rbdpool
provisioner: rbd-csi
reclaimPolicy: Delete
mountOptions: 
  - discard
volumeBindingMode: Immediate
allowVolumeExpansion: true
```

**Comment by Madhu-1** [comment]
if the provided secret is empty then only you will see the above error, can you please recreate the sc,PVC and then resize it?

**Comment by windayski** [comment]
@Madhu-1  It didn't work. My k8s is v1.14.3, maybe it's too old to support resize?

**Comment by Madhu-1** [comment]
> @Madhu-1 It didn't work. My k8s is v1.14.3, maybe it's too old to support resize?

you need kubernetes 1.16+ to support resize, closing this issue as your kubernetes version is not per requirement see https://github.com/ceph/ceph-csi/blob/master/docs/resize-pvc.md#resize-rbd-pvcs

**Comment by HaojingLu97** [comment]
If I turn on feature gate expandCSIvolume in v1.14 cluster, can I expand ?

**Comment by Madhu-1** [comment]
> If I turn on feature gate expandCSIvolume in v1.14 cluster, can I expand ?

quay.io/k8scsi/csi-resizer:v0.1.0 should work with kube 1.14

**Comment by cl51287** [comment]
@Madhu-1  I used csi-resizer v0.1.0 in kubernetes 1.14, and still got an error "provided secret is empty"

**Comment by Madhu-1** [comment]
For 0.1.0 the secrets in storage class is different please check https://github.com/kubernetes-csi/external-resizer/blob/61904896301627bba78a7ef3f37804a83df9e9e4/pkg/resizer/csi_resizer.go#L40-L41

**Comment by blackliner** [comment]
Had the same issue, I thought I can delete the parameters from the list, assuming they will be provided by default. Nada, you need to provide them, see https://github.com/ceph/ceph-csi/blob/37c8f07ed5ae016f5c3bbe012b59b3fffcc2cc77/examples/rbd/storageclass.yaml#L84-L89
