### ISSUE TITLE
Audit log and follow klog standard while logging

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#795]
we need to audit all logs we are logging and make sure it is as per the standard of klog mentioned in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md

**Comment by cxhuawei** [comment]
Is it means replace all klog.Infof with klog.V(x) ?

**Comment by Madhu-1** [comment]
Need to check above doc and make sure we are doing logging properly

**Comment by cxhuawei** [comment]
ok I would like to work on it as my first issue. : )

**Comment by Madhu-1** [comment]
assigned this one to you, Thank you :+1:

**Comment by Madhu-1** [comment]
fixed in #885 closing
