### ISSUE TITLE
Creating RBD PVC in versions 1.2.1 and 1.2.2 hangs on provisioner request

### ISSUE THREAD

**Issue by shayrybak** [ceph/ceph-csi#803]
# Describe the bug #

I've set up the deployment as instructed in the documents. when creating the pvc I can see in the provisioner logs the grpc request to create the volume is being made but an error is returned.

`I0120 21:23:06.485540       1 controller.go:1196] provision "default/rbd-pvc" class "csi-rbd-sc": started
I0120 21:23:06.495021       1 controller.go:471] CreateVolumeRequest {Name:pvc-0ca2777c-3bcb-11ea-9d99-f4e9d4724596 CapacityRange:required_bytes:1073741824  VolumeCapabilities:[mount:<fs_type:"ext4" mount_flags:"discard" > access_mode:<mode:SINGLE_NODE_WRITER > ] Parameters:map[clusterID:f20220f9-f191-4546-9af3-6fc7b2c0986f csi.storage.k8s.io/fstype:ext4 csi.storage.k8s.io/node-stage-secret-name:csi-rbd-secret csi.storage.k8s.io/node-stage-secret-namespace:default csi.storage.k8s.io/provisioner-secret-name:csi-rbd-secret csi.storage.k8s.io/provisioner-secret-namespace:default imageFeatures:layering imageFormat:2 pool:rbd] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0120 21:23:06.495151       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"rbd-pvc", UID:"0ca2777c-3bcb-11ea-9d99-f4e9d4724596", APIVersion:"v1", ResourceVersion:"83665158", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/rbd-pvc"
I0120 21:23:06.501862       1 connection.go:180] GRPC call: /csi.v1.Controller/CreateVolume
I0120 21:23:06.501876       1 connection.go:181] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-0ca2777c-3bcb-11ea-9d99-f4e9d4724596","parameters":{"clusterID":"f20220f9-f191-4546-9af3-6fc7b2c0986f","imageFeatures":"layering","imageFormat":"2","pool":"rbd"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["discard"]}},"access_mode":{"mode":1}}]}
I0120 21:24:06.501988       1 connection.go:183] GRPC response: {}
I0120 21:24:06.502515       1 connection.go:184] GRPC error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
I0120 21:24:06.502576       1 controller.go:979] Final error received, removing PVC 0ca2777c-3bcb-11ea-9d99-f4e9d4724596 from claims in progress
W0120 21:24:06.502603       1 controller.go:886] Retrying syncing claim "0ca2777c-3bcb-11ea-9d99-f4e9d4724596", failure 0
E0120 21:24:06.502631       1 controller.go:908] error syncing claim "0ca2777c-3bcb-11ea-9d99-f4e9d4724596": failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = DeadlineExceeded desc = context deadline exceeded
I0120 21:24:06.502687       1 controller.go:1196] provision "default/rbd-pvc" class "csi-rbd-sc": started
I0120 21:24:06.502734       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"rbd-pvc", UID:"0ca2777c-3bcb-11ea-9d99-f4e9d4724596", APIVersion:"v1", ResourceVersion:"83665158", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = DeadlineExceeded desc = context deadline exceeded`

I don't see any logs on the ceph end to show the request got to the ceph cluster.

no additional entries in rbdplugin logs.

# Environment details #

- ceph-csi 1.2.1-1.2.2
- Kubernetes cluster version v1.13.4

# Steps to reproduce #

1. Setup details: According to documents for deployment kubernetes templates v1.13

**Comment by Madhu-1** [comment]
@shayrybak still are you facing this issue, if yes can you provide provisioner logs. if the commands hang means there is a communication problem between the plugin-container in the provisioner pod and the ceph cluster.

**Comment by shayrybak** [comment]
Hi @Madhu-1 , Yes we weren't able to get through the issue, the provisioner logs are attached in the description above, there were no other logs in the provisioner/rbd plugin that had any other details even after setting the verbosity higher.

for connectivity. I can reach the monitors from the pod. tested from the liveness-prometheus container, as it has shell access.

**Comment by Madhu-1** [comment]
You need to make sure no rbd,rados,ceph commands are in hang State in rbd-plugin container in provisioner pod

**Comment by vgauzzi** [comment]
Currently facing the same issue

**Comment by humblec** [comment]
@shayrybak @vgauzzi considering 1.2.1 and 1.2.2 is really old and many bug fixes in CSI and also in ceph csi code, this shouldnt be an issue any more. I am closing this issue for now, please feel free to reopen this if you face issues with latest version of ceph csi driver . We are at 3.1.1
