### ISSUE TITLE
 Release v2.1.0 of Ceph CSI driver.

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#806]
- [x] **Define release process**
  - Release doc would be a good start
- [x] **Define release deadlines**
  - Code Freeze : 15-Mar-2020
  - RC : 22-Mar-2020
  - GA : 31-Mar-2020

- [x] **Define/list roadmap for v2.1.0**
  - Proposed contents for v.2.1.0 release

 - [x] Dependency update to kube v1.17 
    `status: Completed`
 -  [x] Support Mountoptions in RBD
   `status: Completed`
 -  [x] Migrate to go mode from  dep
  `status: Completed`
 - [x] Update all sidecars to latest version 
 `status: Completed` 
 - [x] Refactor helm charts
`status: PR under review`
  - [ ] <del> Snapshot/Cloning support for CephFS and RBD.
     #394
     #258
     #701
     #411
     #702
     #675
     #693
     #695 </del>

 `status: Deferred to v3.0.0`

 - [x] Topology Aware Provisioning.
     #440
 `status: PR under review`
  - [x] Native Client ( Go client) Support-
    #449
`Status: CreateVolume support is completed, Delete Volume support is under review`

  - [ ] Locking support for RBD volumes which are RWO
    #578 
  
  
- [x] **Release Team**:
 @Madhu-1
 @humblec 
 
  - The release blockers (issues/PRs) are labeled with `release-2.1.0`.
- [x] **Document features and announce the release.**

**Comment by ntolia** [comment]
@humblec @Madhu-1 Will this release also include the following issues and will Ceph CSI RBD snapshots enter beta in this release?

* https://github.com/ceph/ceph-csi/issues/675 (tagged with the 2.1.0 release label)
* https://github.com/ceph/ceph-csi/pull/693 (linked from #675 but not labeled)

**Comment by humblec** [comment]
@ntolia planning to get these in next feature based release. Unless if there is a concern from community about having features in `minor release` ( `y` release), this should be part of `2.1.0`.

**Comment by ntolia** [comment]
Thanks @humblec. If we truly are following SemVer and not doing breaking changes (snapshots is alpha anyway and can be broken though), I think we should be good, right? Looking forward to `2.1.0`!

**Comment by dillaman** [comment]
> If we truly are following SemVer and not doing breaking changes (snapshots is alpha anyway and can be broken though), I think we should be good, right? Looking forward to `2.1.0`!

Snapshots is beta in k8s v1.17 and cloning is beta in v1.16.

**Comment by ntolia** [comment]
> > If we truly are following SemVer and not doing breaking changes (snapshots is alpha anyway and can be broken though), I think we should be good, right? Looking forward to `2.1.0`!
> 
> Snapshots is beta in k8s v1.17 and cloning is beta in v1.16.

@dillaman What I have found is that there is K8s snapshots support and then Ceph CSI snapshot support. The latter is still in alpha from what I can make out.

**Comment by humblec** [comment]
> Thanks @humblec. If we truly are following SemVer and not doing breaking changes (snapshots is alpha anyway and can be broken though), I think we should be good, right? Looking forward to `2.1.0`!

Yeah, that is ( snapshot is still in `alpha`)  our escape path :) , however couple of things around it  like , having some responsibility for the code we have here, bringing or wiping all the instance of previous spec of snapshots from the code..etc need some thought. figuring out the same meanwhile,

**Comment by humblec** [comment]
> > > If we truly are following SemVer and not doing breaking changes (snapshots is alpha anyway and can be broken though), I think we should be good, right? Looking forward to `2.1.0`!
> > 
> > 
> > Snapshots is beta in k8s v1.17 and cloning is beta in v1.16.
> 
> @dillaman What I have found is that there is K8s snapshots support and then Ceph CSI snapshot support. The latter is still in alpha from what I can make out.

True, thats correct.

**Comment by humblec** [comment]
[Release call update]
There is a GA date change or slip of 2 weeks to accommodate couple of important features or bug fixes.  We are also planning to release `v2.0.1` in between.

**Comment by humblec** [comment]
[Release call update]
The final decision here is to release `v2.1.0` as planned with bug fixes/enhancements ..etc and defer couple of features ( snap/clone) from this release to `v3.0.0` as we are currently revalidating the design/implementation of those features in depth to support some more use cases which have to be supported in near future.

**Comment by hoytk** [comment]
> [Release call update]
> The final decision here is to release `v2.1.0` as planned with bug fixes/enhancements ..etc and defer couple of features ( snap/clone) from this release to `v3.0.0` as we are currently revalidating the design/implementation of those features in depth to support some more use cases which have to be supported in near future.
> 
> @Madhu-1 please add details if I missed any.

@Mandu-1 @humblec Does this mean that 2.1.0 will not be able to create/delete RBD snapshots at all?
Per the struck out list above, looks like there will not be any snapshot support...  Obviously need to know to evaluate the impact to my project.

**Comment by ntolia** [comment]
> [Release call update]
> The final decision here is to release `v2.1.0` as planned with bug fixes/enhancements ..etc and defer couple of features ( snap/clone) from this release to `v3.0.0` as we are currently revalidating the design/implementation of those features in depth to support some more use cases which have to be supported in near future.
> 
> @Madhu-1 please add details if I missed any.

What is the timeline for v3.0.0? And, given the previous slips, is there a risk that these features might not show up in 3.0 too? I understand this is a complex feature and just trying to get a timeline estimate to plan better on our side.

**Comment by Madhu-1** [comment]
> [Release call update]
> The final decision here is to release `v2.1.0` as planned with bug fixes/enhancements ..etc and defer couple of features ( snap/clone) from this release to `v3.0.0` as we are currently revalidating the design/implementation of those features in depth to support some more use cases which have to be supported in near future.
> 
> @Madhu-1 please add details if I missed any.

LGTM

**Comment by Madhu-1** [comment]
> > [Release call update]
> > The final decision here is to release `v2.1.0` as planned with bug fixes/enhancements ..etc and defer couple of features ( snap/clone) from this release to `v3.0.0` as we are currently revalidating the design/implementation of those features in depth to support some more use cases which have to be supported in near future.
> > @Madhu-1 please add details if I missed any.
> 
> What is the timeline for v3.0.0? And, given the previous slips, is there a risk that these features might not show up in 3.0 too? I understand this is a complex feature and just trying to get a timeline estimate to plan better on our side.

as more info about 3.0.0 is here https://github.com/ceph/ceph-csi/issues/865

**Comment by lwj5** [comment]
Will CephFS be going beta as planned?

**Comment by humblec** [comment]
> Will CephFS provisioning be going beta as planned?

Yeah, CephFS provisioning will be be moving to `Beta` with this release.

**Comment by humblec** [comment]
[Release call update from 03-Apr-2020]

We have confirmed the release of `2.1.0` on 8-Apr-2020, unless there is a severity blocker issue which break the existing deployments..etc.  

6 more important PRs to get in. Most of them are in final stage of review, so we should be able to release on time. 

@Madhu-1 please add if I missed any.

**Comment by Madhu-1** [comment]
> [Release call update from 03-Apr-2020]
> 
> We have confirmed the release of `2.1.0` on 8-Apr-2020, unless there is a severity blocker issue which break the existing deployments..etc.
> 
> 6 more important PRs to get in. Most of them are in final stage of review, so we should be able to release on time.
> 
> @Madhu-1 please add if I missed any.

we are good, we have one release blocker issue https://github.com/ceph/ceph-csi/issues/904

**Comment by humblec** [comment]
[Release call update]

Finally we are good to go!  The release is expected to happen 14-Apr-2020 :+1:  , we are on final push .. thanks !

**Comment by Madhu-1** [comment]
closing this issue as the release is out https://github.com/ceph/ceph-csi/releases/tag/v2.1.0

**Comment by humblec** [comment]
Thanks all who helped with this awesome release !! :100:
