### ISSUE TITLE
cephfs pvc fails with "an operation with the given Volume ID already exists"

### ISSUE THREAD

**Issue by Henning-GitHub** [ceph/ceph-csi#812]
# Describe the bug #

When configuring cephfs-csi with the given charts + examples, creating the PVC fails with "an operation with the given Volume ID already exists". The PVC remains in "Pending" state.

# Environment details #

**- Image/version of Ceph CSI driver**
 2.0.0

**- helm chart version**
 2.0.0 (?)

**- Kubernetes cluster version**
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:04Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**- Logs**
I0129 10:16:01.405495       1 utils.go:157] ID: 116 GRPC call: /csi.v1.Identity/Probe
I0129 10:16:01.405595       1 utils.go:158] ID: 116 GRPC request: {}
I0129 10:16:01.407001       1 utils.go:163] ID: 116 GRPC response: {}
I0129 10:16:58.061736       1 utils.go:157] ID: 117 Req-ID: pvc-3bb116cc-4275-11ea-adc7-5254009e0d64 GRPC call: /csi.v1.Controller/CreateVolume
I0129 10:16:58.061778       1 utils.go:158] ID: 117 Req-ID: pvc-3bb116cc-4275-11ea-adc7-5254009e0d64 GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-3bb116cc-4275-11ea-adc7-5254009e0d64","parameters":{"clusterID":"5e529728-2a59-4615-83f8-4f551f6f1785","fsName":"mycephfs"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["debug"]}},"access_mode":{"mode":5}}]}
I0129 10:16:58.063581       1 controllerserver.go:82] ID: 117 Req-ID: pvc-3bb116cc-4275-11ea-adc7-5254009e0d64 an operation with the given Volume ID pvc-3bb116cc-4275-11ea-adc7-5254009e0d64 already exists
E0129 10:16:58.063657       1 utils.go:161] ID: 117 Req-ID: pvc-3bb116cc-4275-11ea-adc7-5254009e0d64 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-3bb116cc-4275-11ea-adc7-5254009e0d64 already exists

# Steps to reproduce #

1. Setup 1.14.9 Kubernetes cluster (1 master + 1 worker node)
2. Setup 14.2.6 Ceph cluster (3 ODSs, 2 mon, 2 mds, 1 cephfs filesystem)
3. Install ceph-csi cephfs via helm using provided charts
4. Configure ceph-csi cephfs via examples (secret.yaml + storageclass.yaml)
5. Try to apply pvc.yaml

# Actual results #

When trying to apply pvc.yaml, it remains in "Pending" state, with error in ceph-csi-cephfs-provisioner logs:
I0129 10:47:58.246314       1 utils.go:157] ID: 154 Req-ID: pvc-3bb116cc-4275-11ea-adc7-5254009e0d64 GRPC call: /csi.v1.Controller/CreateVolume
I0129 10:47:58.246368       1 utils.go:158] ID: 154 Req-ID: pvc-3bb116cc-4275-11ea-adc7-5254009e0d64 GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-3bb116cc-4275-11ea-adc7-5254009e0d64","parameters":{"clusterID":"5e529728-2a59-4615-83f8-4f551f6f1785","fsName":"mycephfs"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["debug"]}},"access_mode":{"mode":5}}]}
I0129 10:47:58.248129       1 controllerserver.go:82] ID: 154 Req-ID: pvc-3bb116cc-4275-11ea-adc7-5254009e0d64 an operation with the given Volume ID pvc-3bb116cc-4275-11ea-adc7-5254009e0d64 already exists
E0129 10:47:58.248159       1 utils.go:161] ID: 154 Req-ID: pvc-3bb116cc-4275-11ea-adc7-5254009e0d64 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-3bb116cc-4275-11ea-adc7-5254009e0d64 already exists

# Expected behavior #

A PVC with in "Bound" state

Any help appreciated, thanks!

**Comment by Madhu-1** [comment]
please provide complete logs of cephfs-plugin-container logs from provisioner pod to check what is the issue and also provide below output from cephfs-plugin container 
```
ps -ef |grep ceph
```
```
ps -ef |grep rados
```

**Comment by Henning-GitHub** [comment]
I put the "kubectl -n ceph-csi-cephfs logs ceph-csi-cephfs-nodeplugin-*  --all-containers" output as 2 text files here:
https://ibm.box.com/s/sxvl6rm4tlre2op34p0adxf5zgv4dzxe


> [root@kansasprod8 /]# ps -ef |grep ceph
root           1       0  0 Jan29 ?        00:00:17 /usr/local/bin/cephcsi --nodeid=kansasprod8 --type=cephfs --nodeserver=true --pidlimit=-1 --metricsport=8091 --metricspath=/metrics --enablegrpcmetrics=true --endpoint=unix:///csi/csi.sock --v=5 --drivername=cephfs.csi.ceph.com --metadatastorage=k8s_configmap --mountcachedir=/mount-cache-dir
root          42      19  0 16:26 pts/1    00:00:00 grep --color=auto ceph
[root@kansasprod8 /]# 

> [root@kansasprod8 /]# ps -ef |grep rados
root          44      19  0 16:26 pts/1    00:00:00 grep --color=auto rados
[root@kansasprod8 /]#

**Comment by Madhu-1** [comment]
> I put the "kubectl -n ceph-csi-cephfs logs ceph-csi-cephfs-nodeplugin-* --all-containers" output as 2 text files here:
> https://ibm.box.com/s/sxvl6rm4tlre2op34p0adxf5zgv4dzxe
> 
this is asking for login which am not intrested in, can you use https://pastebin.centos.org/ to paste your logs
> > [root@kansasprod8 /]# ps -ef |grep ceph
> > root           1       0  0 Jan29 ?        00:00:17 /usr/local/bin/cephcsi --nodeid=kansasprod8 --type=cephfs --nodeserver=true --pidlimit=-1 --metricsport=8091 --metricspath=/metrics --enablegrpcmetrics=true --endpoint=unix:///csi/csi.sock --v=5 --drivername=cephfs.csi.ceph.com --metadatastorage=k8s_configmap --mountcachedir=/mount-cache-dir
> > root          42      19  0 16:26 pts/1    00:00:00 grep --color=auto ceph
> > [root@kansasprod8 /]#
> 
> > [root@kansasprod8 /]# ps -ef |grep rados
> > root          44      19  0 16:26 pts/1    00:00:00 grep --color=auto rados
> > [root@kansasprod8 /]#

**Comment by Henning-GitHub** [comment]
> this is asking for login which am not intrested in, can you use https://pastebin.centos.org/ to paste your  logs

I put them here:  https://paste.centos.org/view/ccaa922c
I deleted the repeating "Probe"-calls, the logs consist mainly of those.

**Comment by Madhu-1** [comment]
@Henning-GitHub i don't see anything related to volumeCreate in logs, can you provide log from provisioner pod which is responsible for cephfs subvolume creation

**Comment by Henning-GitHub** [comment]
@Madhu-1 I hope these are the right ones:
https://paste.centos.org/view/fb19a70f

**Comment by Madhu-1** [comment]
can you provide only cephfs-plugin container logs from provisioner pod also also please check 

```
ps -ef |grep ceph
ps -ef |grep rados
```
from the same container

**Comment by Henning-GitHub** [comment]
@Madhu-1 Here's the csi-cephfsplugin - container log: https://paste.centos.org/view/55bf46f3

Here's the ps output from the csi-cephfsplugin container:
**[root@ceph-csi-cephfs-provisioner-797d6f9797-2ckf7 /]# ps -ef |grep ceph**
root           1       0  0 Jan29 ?        00:01:08 /usr/local/bin/cephcsi --nodeid=kansasprod8 --type=cephfs --controllerserver=true --pidlimit=-1 --metricsport=8091 --metricspath=/metrics --enablegrpcmetrics=true --endpoint=unix:///csi/csi-provisioner.sock --v=5 --drivername=cephfs.csi.ceph.com --metadatastorage=k8s_configmap
root        1176       1  0 07:07 ?        00:00:07 /usr/bin/python2.7 /usr/bin/ceph -m 9.152.148.93:6789,9.152.148.94:6789 --id admin --keyfile=/tmp/csi/keys/keyfile-187473168 -c /etc/ceph/ceph.conf fs get mycephfs --format=json
root        1195       1  0 07:22 ?        00:00:05 /usr/bin/python2.7 /usr/bin/ceph -m 9.152.148.93:6789,9.152.148.94:6789 --id admin --keyfile=/tmp/csi/keys/keyfile-853545775 -c /etc/ceph/ceph.conf fs get mycephfs --format=json
root        1254    1236  0 07:56 pts/1    00:00:00 grep --color=auto ceph


**[root@ceph-csi-cephfs-provisioner-797d6f9797-2ckf7 /]# ps -ef |grep rados**
root        1256    1236  0 07:56 pts/1    00:00:00 grep --color=auto rados
[root@ceph-csi-cephfs-provisioner-797d6f9797-2ckf7 /]#

**Comment by Madhu-1** [comment]
> @Madhu-1 Here's the csi-cephfsplugin - container log: https://paste.centos.org/view/55bf46f3
> 
> Here's the ps output from the csi-cephfsplugin container:
> **[root@ceph-csi-cephfs-provisioner-797d6f9797-2ckf7 /]# ps -ef |grep ceph**
> root 1 0 0 Jan29 ? 00:01:08 /usr/local/bin/cephcsi --nodeid=kansasprod8 --type=cephfs --controllerserver=true --pidlimit=-1 --metricsport=8091 --metricspath=/metrics --enablegrpcmetrics=true --endpoint=unix:///csi/csi-provisioner.sock --v=5 --drivername=cephfs.csi.ceph.com --metadatastorage=k8s_configmap
> root 1176 1 0 07:07 ? 00:00:07 /usr/bin/python2.7 /usr/bin/ceph -m 9.152.148.93:6789,9.152.148.94:6789 --id admin --keyfile=/tmp/csi/keys/keyfile-187473168 -c /etc/ceph/ceph.conf fs get mycephfs --format=json
> root 1195 1 0 07:22 ? 00:00:05 /usr/bin/python2.7 /usr/bin/ceph -m 9.152.148.93:6789,9.152.148.94:6789 --id admin --keyfile=/tmp/csi/keys/keyfile-853545775 -c /etc/ceph/ceph.conf fs get mycephfs --format=json
> root 1254 1236 0 07:56 pts/1 00:00:00 grep --color=auto ceph
> 

you can see above  commands are  hang, is this mon IP rechable from  the container?

> **[root@ceph-csi-cephfs-provisioner-797d6f9797-2ckf7 /]# ps -ef |grep rados**
> root 1256 1236 0 07:56 pts/1 00:00:00 grep --color=auto rados
> [root@ceph-csi-cephfs-provisioner-797d6f9797-2ckf7 /]#

**Comment by Henning-GitHub** [comment]
> is this mon IP rechable from the container?

Seems it's not, I can't ping it from inside the container. I can ping it from outside the container, ie. from the kubernetes master node.

**Comment by Madhu-1** [comment]
it should  be accessible from  inside the container then only it will work

**Comment by Henning-GitHub** [comment]
It's working not, I re-installed the deployment using port 3300 for the monitors (instead of port 6789) in the values.yaml:
    - clusterID: "5e529728-2a59-4615-83f8-4f551f6f1785"
      monitors:
       #- "9.123.123.123:6789"
        - "9.123.123.123:3300"

I'm sorry, I guess I should have known this. Should I close this issue?
