### ISSUE TITLE
Revisit and reduce, requested RBAC rules for kubernetes deployments

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#823]
While debugging a particular setup, it was interesting to note that nodeplugins are given an RBAC that includes ability to "watch", "update" VolumeAttachments. I believe this is not required, and hence on taking a look at the RBAC, I find a few other permissions granted that are not required, for example [these](https://github.com/ceph/ceph-csi/blob/1695c6965dbae56fd04eebbe3efefa9eb227cd64/deploy/rbd/kubernetes/csi-nodeplugin-rbac.yaml#L28-L39).

At a point when config maps were used to store the PV and volume related data by ceph-csi, there were some RBAC rules added, but a lot of these are not required unless volumes with older versions are in use. (possibly not required at all for the nodeplugin as it never consulted the stored config maps)

Ideally the nodeplugin should need no RBAC to work, as kubelet invokes the required CSI calls and updates the required kubernetes objects.

As we have not reviewed the RBAC set, or possibly not kept them updated as the code has moved, opening this issue to,
- Update/cleanup RBAC
- Make parts of RBAC optional (at least in helm), under the case where ceph-csi 1.0 volumes are still in use
- Or, at least add some notes on why certain RBACs are required

**Comment by Madhu-1** [comment]
this is on my pending task list for a long time, let me try to fix it up

**Comment by ShyamsundarR** [comment]
Once RBAC is updated as per PR #827, prior to the next release we would need to,
- Rename (or merge the contents of) the dangling rbac files
- Update e2e/scripts/docs where the above files are referred to
- Add required upgrade documentation/steps to cover the RBAC change if any

**Comment by Madhu-1** [comment]
@ShyamsundarR am closing this one, as this is already covered.
