### ISSUE TITLE
Encrypt each RBD devices using uniquely generated ID in ceph-csi

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#826]
# Describe the feature you'd like to have #

What new functionality do you want?

currently, ceph-csi is supported only vault based encryption to encrypt each rbd device with unique Key, only one kubernetes secret will be used for encryption which will be provided in storage-class.

# What is the value to the end user? (why is it a priority?) #
if ceph-csi can generate its own secret and use it for encrypting the devices, the encryption will be more secure.

How would the end user gain value from having this feature?

# How will we know we have a good solution? (acceptance criteria) #
the ceph-csi can create/get a secret and update the secret with some imageID as key and the value as the unique key, the plugin who is responsible for encrypting and decrypting the rbd image can make use of a secret.

we can mount the secrets to some path in pod spec. but it will slow down the operation as the dynamic update of secrets takes some time to reflect in the pod as kubelet needs to sync the secrets and pod volume mounts.

# Concern:
* ceph-csi need to make sure the secret data is not corrupted when multiple instances are accessing it.
* ceph-csi should not generate the different Keys for single RBD image if it's mounted on different nodes

**Comment by Madhu-1** [comment]
@vasyl-purchel @ShyamsundarR @humblec @dillaman can you please add your thoughts on this one?

**Comment by vasyl-purchel** [comment]
With current setup for the encryption using kms it should be easy to add another provider to use k8s secrets.
Currently we use volumeID as a key for kms so with multiple instances accessing it should not cause problems since we create key once and then we read it for all following operations (the only potential issue is if multiple instances try to mount volume at exactly the same time so first GET request returns no passphrase and all of them will try to write it, and it's up to KMS to ensure you're not overriding the value unintentionally)

For the tests - vault tests already checking that when we create a volume and mount it first time - key is populated in vault and after deleting volume - key is gone also.

**Comment by Madhu-1** [comment]
> With current setup for the encryption using kms it should be easy to add another provider to use k8s secrets.
> Currently we use volumeID as a key for kms so with multiple instances accessing it should not cause problems since we create key once and then we read it for all following operations (the only potential issue is if multiple instances try to mount volume at exactly the same time so first GET request returns no passphrase and all of them will try to write it, and it's up to KMS to ensure you're not overriding the value unintentionally)
> 

as we support RWX PVC  we need to make sure we are not overwriting the keys if the same operations are performed from the different nodes at the same time.

> For the tests - vault tests already checking that when we create a volume and mount it first time - key is populated in vault and after deleting volume - key is gone also.

**Comment by dillaman** [comment]
> currently, ceph-csi is supported only vault based encryption to encrypt each rbd device with unique Key, only one kubernetes secret will be used for encryption which will be provided in storage-class.

That's not quite correct, right? The CSI supports a static per-StorageClass LUKS passphrase or a Vault-managed per-PV passphrase. Is the goal with this future to implement a Vault-like service for managing per-PV LUKS passphrases? If so, I would say that it would be better to just integrate w/ the k8s KMS service directly and not try to build your own KMS.

**Comment by ShyamsundarR** [comment]
> > currently, ceph-csi is supported only vault based encryption to encrypt each rbd device with unique Key, only one kubernetes secret will be used for encryption which will be provided in storage-class.
> 
> That's not quite correct, right? The CSI supports a static per-StorageClass LUKS passphrase or a Vault-managed per-PV passphrase. Is the goal with this future to implement a Vault-like service for managing per-PV LUKS passphrases? If so, I would say that it would be better to just integrate w/ the k8s KMS service directly and not try to build your own KMS.

I agree with @dillaman, if the intention is to create a kubernetes secrets based KMS for per-PV encryption, we should rather integrate with existing solutions and not (re)create our own.

The RWX discussion, and multi-node update/create of the secret does need handling/testing, but not at the cost of building out a KMS (at least till we run out of options or figure out otherwise).

**Comment by Madhu-1** [comment]
> > currently, ceph-csi is supported only vault based encryption to encrypt each rbd device with unique Key, only one kubernetes secret will be used for encryption which will be provided in storage-class.
> 
> That's not quite correct, right? The CSI supports a static per-StorageClass LUKS passphrase or a Vault-managed per-PV passphrase. Is the goal with this future to implement a Vault-like service for managing per-PV LUKS passphrases? If so, I would say that it would be better to just integrate w/ the k8s KMS service directly and not try to build your own KMS.

Yes, that's current, it's a static secret embedded into the node-stage secret. which will be passed to the csi plugin.

@dillaman  kubernetes KMS service is something deployed outside of kubernetes like vault service?

**Comment by dillaman** [comment]
> @dillaman kubernetes KMS service is something deployed outside of kubernetes like vault service?

Right now it's basically a framework to encrypt k8s secrets within the backend etcd db. So the method to integrate with it would be to have the CSI driver create / delete per-PV k8s Secrets.

Of course, I'm not sure what the value-add is with per-PV LUKS passphrases vs a StorageClass passphrase. Any attack vector that could be used to extract the current StorageClass passphrase could most likely be used to extract the per-PV passphrase.

Looking around at other CSI drivers, the Portworx CSI driver provides a way for individual PVCs to point to their own Secrets in arbitrary namespaces for per-PV encryption. Of course, if you wanted to have the CSI driver pull Secrets from another namespace, the storage admin would need to tweak the RBAC rules for the CSI driver. Additionally, it requires custom annotations within the PVC which breaks any idea of keeping the PVCs generic.

All of this talk, however, does bring up the need for rotating the LUKS passphrases in case you have a leak and need to re-key the volumes.

**Comment by vasyl-purchel** [comment]
the only benefit I see to have per-pv passphrase is to reduce chance of attack on this passphrase - i.e. guess it if you have a lot of pvs created from storage class and got access to the volumes itself.

re-encryption is something that is definitely need to be tackled, if there are any examples done in other providers - I'd like to take a look, but don't know when we'll get time to work on it.

currently it is possible to do re-encryption manually in case passphrase compromised - i.e. re-encrypt volume with LUKS and update after the passphrase in vauuult or k8s secrets.
