### ISSUE TITLE
wrong nodeplugin tag version in ceph-csi-rbd chart 2.0.0

### ISSUE THREAD

**Issue by topikachu** [ceph/ceph-csi#829]
# Describe the bug #
Wrong tag `2.0.0` in the chart
https://github.com/ceph/ceph-csi/blob/v2.0.0/charts/ceph-csi-rbd/values.yaml#L107
It should be `v2.0.0`
https://quay.io/repository/cephcsi/cephcsi?tag=latest&tab=tags 
# Environment details #
- helm chart version
2.0.0
- Kubernetes cluster version
1.16
- Logs
`Failed to pull image "quay.io/cephcsi/cephcsi:2.0.0": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/cephcsi/cephcsi:2.0.0 not found: manifest unknown: manifest unknown`

# Steps to reproduce #
Install the chart by default, the pods can't start because of the ImagePullBackOff error
# Actual results #
The pods can't start because of the ImagePullBackOff error

# Expected behavior #
The pods should start by default without chart customization

**Comment by Madhu-1** [comment]
@topikachu this will be fixed in next release, can you please set the image tag to `v2.0.0` while installing helm charts

**Comment by topikachu** [comment]
> @topikachu this will be fixed in next release, can you please set the image tag to `v2.0.0` while installing helm charts

no pr. I install the plugin by a customized values.yaml.

**Comment by Madhu-1** [comment]
fixed in https://github.com/ceph/ceph-csi/pull/869
