### ISSUE TITLE
Unable to deploy rbd plugin containers: missing "ceph-csi-encryption-kms-config" configmap

### ISSUE THREAD

**Issue by Scronkfinkle** [ceph/ceph-csi#834]
# Describe the bug #
While following the installation instructions here: https://docs.ceph.com/docs/master/rbd/rbd-kubernetes/

After running the deployments `csi-rbdplugin.yaml` and `csi-rbdplugin-provisioner.yaml`, my containers get stuck in the "ContainerCreating" state and cannot progress.
```
$ kubectl get pods
NAME                                        READY   STATUS              RESTARTS   AGE
csi-rbdplugin-4msmj                         0/3     ContainerCreating   0          3m32s
csi-rbdplugin-79x7d                         0/3     ContainerCreating   0          3m32s
csi-rbdplugin-j6gzh                         0/3     ContainerCreating   0          3m32s
csi-rbdplugin-provisioner-bbc6b7bfd-bp8lm   0/6     ContainerCreating   0          3m33s
csi-rbdplugin-provisioner-bbc6b7bfd-fr7x9   0/6     ContainerCreating   0          3m33s
csi-rbdplugin-provisioner-bbc6b7bfd-n88xx   0/6     ContainerCreating   0          3m33s
csi-rbdplugin-vn9lr                         0/3     ContainerCreating   0          3m32s
csi-rbdplugin-x22s6                         0/3     ContainerCreating   0          3m32s
```

Inspecting the pods with `kubectl describe` yields the following event log
```
Events:
  Type     Reason       Age               From               Message
  ----     ------       ----              ----               -------
  Normal   Scheduled    <unknown>         default-scheduler  Successfully assigned ceph/csi-rbdplugin-4msmj to node4
  Warning  FailedMount  3s (x8 over 67s)  kubelet, node4    MountVolume.SetUp failed for volume "ceph-csi-encryption-kms-config" : configmap "ceph-csi-encryption-kms-config" not found
```
# Environment details #

I'm using the plugin verisons from the tutorial, which would reference the `master` branch. I pulled all YAML's fresh today.

My k8s cluster is being managed by Rancher. I have created a namespace and project specifically for managing ceph via ceph-csi, and all YAML files with `namespace` fields have been updated from default to point to the ceph namespace.

# Steps to reproduce #

1. Create a new ceph cluster and ensure it is in status `HEALTH_OK`
2. Follow the instructions in the tutorial listed above until it is needed to deploy `csi-rbdplugin.yaml` and `csi-rbdplugin-provisioner.yaml`
3. Download the deployments
4. run them 

# Actual results #
The containers are stuck on `ContainerCreating` and throw the following error in their event logs:
```
  Warning  FailedMount  3s (x8 over 67s)  kubelet, athos4    MountVolume.SetUp failed for volume "ceph-csi-encryption-kms-config" : configmap "ceph-csi-encryption-kms-config" not found
```

# Expected behavior #
The containers are created, and run successfully

**Comment by ShyamsundarR** [comment]
Master branch has one additional config map that it uses for encryption details. Request that you create the following config map in addition for your deployment to work,
- https://github.com/ceph/ceph-csi/blob/master/examples/kms/vault/kms-config.yaml

Also the content of the config map should be empty, delete these lines, https://github.com/ceph/ceph-csi/blob/8163552b814b3acd2ac2143ffe097a389d0d3220/examples/kms/vault/kms-config.yaml#L7-L15

Ensure that the config map is created in the same namespace as the rbd plugins.

**Comment by Scronkfinkle** [comment]
That fixed it, thank you!

**Comment by rowanj** [comment]
the linked doc is still missing this step, though

**Comment by Madhu-1** [comment]
@dillaman still this need fix in ceph document https://docs.ceph.com/docs/master/rbd/rbd-kubernetes/

**Comment by zjcnew** [comment]
Why haven't the fixed in ceph document https://docs.ceph.com/docs/master/rbd/rbd-kubernetes/,This will affect the use of many ceph users!

**Comment by Madhu-1** [comment]
@zjcnew please open a bug in ceph.

**Comment by yangyongzhi7** [comment]
> Why haven't the fixed in ceph document https://docs.ceph.com/docs/master/rbd/rbd-kubernetes/,This will affect the use of many ceph users!

Yes, I am agree with this, I am very confused about this.

**Comment by ethanbergstrom** [comment]
I forked the repo and made several updates to the deployment YAMLs to remove the dependency of an empty encryption configmap, along with moving everything into its own namespace, and some other general cleanup. 

Check it out if you'd like to use those instead, as I found the ones offered in the main repo somewhat messy: https://github.com/ethanbergstrom/ceph-csi/tree/master/deploy/rbd/kubernetes

**Comment by honza801** [comment]
please fix the documentation. don't let more users getting annoyed.

https://docs.ceph.com/en/latest/rbd/rbd-kubernetes/?

thanks...

**Comment by zdover23** [comment]
> please fix the documentation. don't let more users getting annoyed.
> 
> https://docs.ceph.com/en/latest/rbd/rbd-kubernetes/?
> 
> thanks...

I'll fix this up over this coming weekend.

In the future, bring changes like this to my attention and I'll make sure that they're documented.

**Comment by Yuggupta27** [comment]
> > please fix the documentation. don't let more users getting annoyed.
> > https://docs.ceph.com/en/latest/rbd/rbd-kubernetes/?
> > thanks...
> 
> I'll fix this up over this coming weekend.
> 
> In the future, bring changes like this to my attention and I'll make sure that they're documented.

Thanks @zdover23!

**Comment by idryomov** [comment]
https://github.com/ceph/ceph/pull/40905

**Comment by Madhu-1** [comment]
Thanks @idryomov For fixing it :)

**Comment by anomaly256** [comment]
This info is still missing from `docs/deploy-cephfs.md` by the way.  Maybe I'm the only one trying to use cephfs without rbd 😛

**Comment by lijhnihaoa** [comment]
Warning  FailedMount  10s (x7 over 42s)  kubelet            MountVolume.SetUp failed for volume "ceph-config" : configmap "ceph-config" not found

I also deployed according to the documentation. After running` kubectl apply -f csi-rbdplugin-provisioner.yaml`, the POD has been in ContainerCreating.
