### ISSUE TITLE
Unable to use mounter with kernel module for cephfs 

### ISSUE THREAD

**Issue by mr-yaky** [ceph/ceph-csi#838]
Hi all,

I tried to use kernel module option for mounting cephfs to get better read/write performance. I used following `StorageClass`:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2020-02-21T16:28:58Z"
  name: csi-cephfs-sc
  resourceVersion: "105469182"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/csi-cephfs-sc
  uid: a7b27b76-e12d-4228-bf1a-48cdb738d106
mountOptions:
- debug
parameters:
  clusterID: 453a848b-ac95-43df-a3ac-d70014a7a169
  csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
  csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  fsName: cephfs
  mounter: kernel
provisioner: cephfs.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

But after provisioning PV and attaching to the pod I can see that it still uses ceph-fuse somehow:

```
$ kubectl exec -it pod-657bd6cfcd-rgv29 mount  | grep ceph
ceph-fuse on /app/public type fuse.ceph-fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
```
At the beginning I have started with ceph-fuse but then decided switch to kernel module. So, I did following:
- removed all testing POD and PVC which were mounted with ceph-fuse
- removed cephfs StorageClass
- created new StorageClass with `mounter: kernel` inside parameters
- restarted all pods of nodeplugin and provisioner
- created PVC again and run the POD 

Could anyone help with it, please? What I missed ?

# Environment details #

- Image/version of Ceph CSI driver:
```
    Image:         quay.io/cephcsi/cephcsi:v1.2.1
    Image:         quay.io/k8scsi/csi-attacher:v1.2.1
    Image:         quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
    Image:         quay.io/k8scsi/csi-provisioner:v1.3.0
```
- helm chart version: ceph-csi-cephfs-1.3.0-canary
- Kubernetes cluster version: v1.14.6

**Comment by Madhu-1** [comment]
@mr-yaky what is the kernel version? If the kernel version is less than 4.17 the kernel mounter will be disabled by default. If you want to use kernel mounter even if the kernel version is less than 4.17 you need to set  `forcecephkernelclient`  in daemonset template https://github.com/ceph/ceph-csi/blob/master/deploy/cephfs/kubernetes/csi-cephfsplugin.yaml#L63. more info at https://github.com/ceph/ceph-csi/blob/master/docs/deploy-cephfs.md#configuration

**Comment by mr-yaky** [comment]
Hi @Madhu-1,
Yes, I use CentOS 7 with standard kernel version which less than 4.17, you are right.
Ok, understood. I'll try with this fix in daemonset template.

Thank you.

**Comment by Madhu-1** [comment]
closing this one based on the above confirmation.

**Comment by mr-yaky** [comment]
Yes, it works. I just updated to v1.2.2 version because on v1.2.1 it doesn't has the `forcecephkernelclient` option.

**Comment by vvavepacket** [comment]
@mr-yaky 

How do you exactly know if its using fuse or kernel?

If I run your command

`kubectl exec -it pod-657bd6cfcd-rgv29 mount  | grep ceph`

and I dont get any, does it mean its mounted using kernel module instead of fuse?

**Comment by mr-yaky** [comment]
@vvavepacket yes, I checked with the same way and could see the mounted volume with ceph kernel module. Also you can check which kernel modules already loaded on your k8s node. I guess you still on `fuse` one.

**Comment by vvavepacket** [comment]
Sorry I'm new to kernel modules. Do you have the command in hand to know which kernel modules are already loaded in a k8s node?


Also what does it say if the volume is mounted using kernel module? Mine says just ext4, no traces of ceph or fuse wording
