### ISSUE TITLE
supporting specify DFS path in creating dynamic cephfs PVC. 

### ISSUE THREAD

**Issue by yydzhou** [ceph/ceph-csi#841]
Currently, pv or volume path in DFS (cephfs in this case) is automatically created during the PV and volume creation. However, this design/implementation prevents from creating a volume on an existing/specified path to accessing any existing data. 

This feature is actually very useful in real environment. 
1. To create a PV to share existing data.
2. To easily save and reuse the data generated/saved via created pv. 
3. To support re-deployment of applications without losing data. For example. An upgrade of a chart is not available but old data is desired in re-deployment.

Actually, in development environment. redeploying of a chart or application is very common on a shared cluster. But the dataset is big and it's better to be reused, like training data, or generated logs. In this case, using a specified path for creating volume can avoid ingesting data on each re-deployment. And old logs is still accessible even if the application is redeployed.

**Comment by Madhu-1** [comment]
@yydzhou how this is different from static PV support https://github.com/ceph/ceph-csi/issues/669

for me both are the same, in that case, let me know can we close this one?

**Comment by yydzhou** [comment]
> @yydzhou how this is different from static PV support #669
> 
> for me both are the same, in that case, let me know can we close this one?

Hi @Madhu-1 The static pv works. But it needs more manual work. I can still see a couple of benefits if this is supported within the dynamic manner. 
    1. the path prefix needs to be supported in storageclass in this case. The static pv, however, does not has a simply way to enforce user to setup path prefix. User can get full access to the cephfs once they have the info of setup the static pv, which is too much to me.  This is a critical issue that prevents us from using the static pv in a shared cluster. 
    2. static pv requires users to create pvc and pv, respectively. Instead of just create pvc. 
    3. Too much info needs to be provided to users in order to setup static pv. 
    4. There is still no official doc for static pv yet. I guess no tests coverage neither.

Please read the first reason carefully and let me know if I missed some way of fixing this issue. Otherwise, static pv is not ready for production or shared cluster. 

Actually, an alternative way of solving this problem would be generating the path of the pv/volume based on the namespace and name of the pvc, which is also unique in a cluster but would be always same over redeployment.  I don't know which way you guys prefer.

**Comment by Madhu-1** [comment]
cc @joscollin @ShyamsundarR
