### ISSUE TITLE
Cross-compiling does not work with cgo, breaks deploy.sh pushing different architectures

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#856]
# Describe the bug #

The Travis CI configuration runs `deploy.sh` once changes are merged into master. This script builds and pushes new container images to a registry.

When go-ceph is used, cgo is needed to compile the executable(s). Cross-compiling with cgo is not supported, so `deploy.sh` fails to compile arm64 executables.

# Possible Solutions #

a. There might need to be multiple `deploy` scripts so that each container can get built on its real architecture.

b. Have quay.io and/or dockerhub build the containers natively, on the architectures they support. Have them trigger on a Dockerfile once the master branch gets updated (easy with Quay.io, no idea of Dockerhub). 

c. Build container images in a different CI that supports multiple architectures and push the images to the registry.

d. ....

**Comment by Madhu-1** [comment]
This is a blocker for next release-v2.0.1 also, we need to find a way to fix this one

**Comment by Madhu-1** [comment]
Adding logs for reference when i tried locally
```
]make image-cephcsi 
cephcsi image settings: quay.io/cephcsi/cephcsi version canary
if [ ! -d ./vendor ]; then dep ensure -vendor-only; fi
GOOS=linux GOARCH=arm64 go build -a -ldflags ' -X github.com/ceph/ceph-csi/pkg/util.GitCommit=b4e6504e9b6cf0e9920deb5b230061c22adf5b1b -X github.com/ceph/ceph-csi/pkg/util.DriverVersion=canary' -o  _output/cephcsi ./cmd/
# runtime/cgo
gcc_arm64.S: Assembler messages:
gcc_arm64.S:27: Error: no such instruction: `stp x19,x20,[sp,'
gcc_arm64.S:28: Error: no such instruction: `stp x21,x22,[sp,'
gcc_arm64.S:29: Error: no such instruction: `stp x23,x24,[sp,'
gcc_arm64.S:30: Error: no such instruction: `stp x25,x26,[sp,'
gcc_arm64.S:31: Error: no such instruction: `stp x27,x28,[sp,'
gcc_arm64.S:32: Error: no such instruction: `stp x29,x30,[sp,'
gcc_arm64.S:33: Error: too many memory references for `mov'
gcc_arm64.S:35: Error: too many memory references for `mov'
gcc_arm64.S:36: Error: too many memory references for `mov'
gcc_arm64.S:37: Error: too many memory references for `mov'
gcc_arm64.S:39: Error: no such instruction: `blr x20'
gcc_arm64.S:40: Error: no such instruction: `blr x19'
gcc_arm64.S:42: Error: no such instruction: `ldp x29,x30,[sp],'
gcc_arm64.S:43: Error: no such instruction: `ldp x27,x28,[sp],'
gcc_arm64.S:44: Error: no such instruction: `ldp x25,x26,[sp],'
gcc_arm64.S:45: Error: no such instruction: `ldp x23,x24,[sp],'
gcc_arm64.S:46: Error: no such instruction: `ldp x21,x22,[sp],'
gcc_arm64.S:47: Error: no such instruction: `ldp x19,x20,[sp],'
make: *** [Makefile:61: cephcsi] Error 2
```

**Comment by Madhu-1** [comment]
removing this as a blocker from v2.0.1 as go-ceph is not backported to v2.0.0 branch
