### ISSUE TITLE
RBD image deletion fallback when CephMgr fails to create a task

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#863]
# Describe the feature you'd like to have #

Should there be a fallback when deleting an RBD image in the background with CephMgr fails?
If so, are there specific errors that should not have this behaviour?

# What is the value to the end user? (why is it a priority?) #

In case CephMgr is (temporary) not available, deletion would still work without the provisioner having to retry the full operation later.

# Additional context #

- [comment with idea](https://github.com/ceph/ceph-csi/pull/860#pullrequestreview-375038241)
- [example change](https://github.com/nixpanic/ceph-csi/commit/25cc20783e89a6dc89f9cdc528590c30e0cc7b00)

**Comment by dillaman** [comment]
The MGR is (generally) installed as an HA service, so I would hope any issues would be transient. That said, since there already exists a code path to revert to an inline "rbd rm" if the tasks are not supported, I wouldn't be against this proposal.

**Comment by ShyamsundarR** [comment]
The CO (k8s) attempts retries on deletion failures, this would in turn retry in a typically exponential back-off manner.

Inline image deletion takes time proportional to the size of the image, which is where the MGR task was added/used to do this out of band.

So if the manager task is facing transient errors I would recommend we retry based on the next delete request, than use in-line deletion, as the expectation on delete is constant, IOW, it is never in-line. The constant expectation helps deal with troubleshooting delete issues, to look at one alternative than 2, or to determine that an in-line deletion is in progress.

Also, the in-line deletion is a fall back for ceph versions that do not support it, and would eventually be removed. This also helps keep the delete workflow constant for older ceph versions.

So, IMHO have one way to delete, which is based on the ceph version.

**Comment by nixpanic** [comment]
#858 is a problem that seems to occur, and the image is not deleted. In this case a fallback would have prevented the 'image leak'.
