### ISSUE TITLE
 Release v3.0.0 of Ceph CSI driver

### ISSUE THREAD

**Issue by humblec** [ceph/ceph-csi#865]
- [x] **Define release process**
  - Release doc would be a good start
- [x] **Define release deadlines**
  - Code Freeze : 18-Jul-2020
  - RC : 23-Jul-2020
  - GA : 29-Jul-2020
- [x] **Define/list roadmap for v3.0.0**
  - Proposed contents for v3.0.0 release
  - The release blockers (issues/PRs) are attached to [the `release-3.0.0` milestone](https://github.com/ceph/ceph-csi/milestone/3)

  - [x] Snapshot/Cloning support for CephFS and RBD.
     #394 ( Additional Details : https://github.com/ceph/ceph-csi/pull/394#issuecomment-663356855)
     #258
     #701
     #411
     #702
     #675
     #693
     #695 

  
  
- [x] **Release Team**:
 @Madhu-1
 @humblec 

- [x] **Document features and announce the release.**

**Comment by humblec** [comment]
[Release call update] [planning]

Eventhough snap and clone is the main theme, we will be enhancing `go ceph` adoption and also topology aware provisioning with this release.

**Comment by ferdelatejera** [comment]
Is this Ceph CSI driver still on track for 6/30? I noted at the top of the issue these deadlines:

Code Freeze : 20 -Jun-2020
RC : 25-Jun-2020
GA : 30-Jun-2020

**Comment by humblec** [comment]
> Is this Ceph CSI driver still on track for 6/30? I noted at the top of the issue these deadlines:
> 
> Code Freeze : 20 -Jun-2020
> RC : 25-Jun-2020
> GA : 30-Jun-2020

@ferdelatejera yes, that's the current ETA for the release. If any change, it will be populated/updated here.

**Comment by ferdelatejera** [comment]
Hi, where we can take Ceph CSI driver?

**Comment by HackerDotCN** [comment]
v3.x version is abandoned ? I just find v4.x in tags

**Comment by Madhu-1** [comment]
Can you point me to 4.x tagged images link?

**Comment by ferdelatejera** [comment]
> > Is this Ceph CSI driver still on track for 6/30? I noted at the top of the issue these deadlines:
> > Code Freeze : 20 -Jun-2020
> > RC : 25-Jun-2020
> > GA : 30-Jun-2020
> 
> @ferdelatejera yes, that's the current ETA for the release. If any change, it will be populated/updated here.

Hi, so the GA targeted for 30-Jun was pushed? I see that the ticked suddenly changed the target dates.

**Comment by humblec** [comment]
> > > Is this Ceph CSI driver still on track for 6/30? I noted at the top of the issue these deadlines:
> > > Code Freeze : 20 -Jun-2020
> > > RC : 25-Jun-2020
> > > GA : 30-Jun-2020
> > 
> > 
> > @ferdelatejera yes, that's the current ETA for the release. If any change, it will be populated/updated here.
> 
> Hi, so the GA targeted for 30-Jun was pushed? I see that the ticked suddenly changed the target dates.

Yeah, we had to push it for 3/4 weeks to get and use  CephFS release ( `14.2.10 & 15.2.2`) out  which support some must have fixes or enhancements to support cephfs snapshot and clone functionality.  As they are released now, we are on track for new GA date which is of this month end.

**Comment by humblec** [comment]
**[Release Call Update]**
Due to missing support and difficulty to enable lastest `Ceph master and v15` in our Travis  E2E CI we are deferring CephFS **snapshot create, delete, restore and smart cloning support from v3.0.0** even though its working and tested manually against master version of Ceph. It will be the first item for **v3.1.0** release which is going to happen in next couple of weeks time or in parity with `Ceph Nautilus 14.2.11` release.  CSI `3.0.0` will happen as planned and it will be consumed by `Rook 1.4`.  Please refer the discussion over CephFS snapshot PR for more details. 
https://github.com/ceph/ceph-csi/pull/394#issuecomment-663356855

@Madhu-1 anything else to add here?

**Comment by Madhu-1** [comment]
> **[Release Call Update]**
> Due to missing support and difficulty to enable lastest `Ceph master and v15` in our Travis E2E CI we are deferring CephFS **snapshot create, delete, restore and smart cloning support from v3.0.0** even though its working and tested manually against master version of Ceph. It will be the first item for **v3.1.0** release which is going to happen in next couple of weeks time or in parity with `Ceph Nautilus 14.2.11` release. CSI `3.0.0` will happen as planned and it will be consumed by `Rook 1.4`. Please refer the discussion over CephFS snapshot PR for more details.
> [#394 (comment)](https://github.com/ceph/ceph-csi/pull/394#issuecomment-663356855)
> 
> @Madhu-1 anything else to add here?

Thanks for the update @humblec we are good.

**Comment by Madhu-1** [comment]
ceph-csi v3.0.0 is released, more info at https://github.com/ceph/ceph-csi/releases/tag/v3.0.0, Image is available in https://quay.io/repository/cephcsi/cephcsi?tab=tags and kubernetes templates are available at  https://github.com/ceph/ceph-csi/tree/v3.0.0
