### ISSUE TITLE
make test failed

### ISSUE THREAD

**Issue by cxhuawei** [ceph/ceph-csi#872]
# Describe the bug #

 I pull the code of master branch, when I run 'make test', it failed with err logs

# Environment details #

system: macos

# Steps to reproduce #

1、go get -d github.com/ceph/ceph-csi
2、make test 

# Actual results #

# github.com/ceph/go-ceph/rados
../../../../pkg/mod/github.com/ceph/go-ceph@v0.2.0/rados/conn.go:5:11: fatal error: 'rados/librados.h' file not found
 #include <rados/librados.h>
          ^~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by Madhu-1** [comment]
@nixpanic can you please update development documentation related to this?

**Comment by nixpanic** [comment]
@cxhuawei can you make sure to install the Ceph development headers? Packages are called like `librbd-devel`, `libcephfs-devel` on Fedora. Other Linux distributions may have different names.

**Comment by chenxu1990** [comment]
> @cxhuawei can you make sure to install the Ceph development headers? Packages are called like `librbd-devel`, `libcephfs-devel` on Fedora. Other Linux distributions may have different names.

Packages are called `librados2-devel` and `librbd1-devel` on CentOS 7 , but I have not found packages on macos : )

**Comment by nixpanic** [comment]
On Sun, Mar 22, 2020 at 07:52:58PM -0700, chenxu wrote:
> > @cxhuawei can you make sure to install the Ceph development headers? Packages are called like `librbd-devel`, `libcephfs-devel` on Fedora. Other Linux distributions may have different names.
> 
> Packages are called `librados2-devel` and `librbd1-devel` on CentOS 7 , but I have not found packages on macos : )

It will only be possible to build on MacOS if the Ceph client libraries
are available for the OS. I do not have any experience with MacOS, but I
could not find any references that they exist...

If it is possible to run Linux containers on MacOS, it should be
possible to have the build done inside a container. That is planned to
get done through PR #385 (or a replacement of it).
