### ISSUE TITLE
when used rbd volume the type rbd-nbd better or kernel rbd better?

### ISSUE THREAD

**Issue by jianglingxia** [ceph/ceph-csi#880]
# Describe the bug #
the csi driver support the rbd-nbd and kernel rbd，the rbd-nbd mount has the problem: the client mount will be disturbed ( same as fuse deamon) if node plugin is restarted. 
expect the problem，have some any other problem? and use rbd-nbd better or kernel rbd better?
thanks 

# Environment details #

- Image/version of Ceph CSI driver:v2.0.0
- helm chart version
- Kubernetes cluster version:v1.17
- Logs

# Steps to reproduce #

1. Setup details: '...'
1. Deployment to trigger the issue '....'
1. See error

# Actual results #

Describe what happened

# Expected behavior #

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by jianglingxia** [comment]
@humblec   @Madhu-1 
thanks

**Comment by jianglingxia** [comment]
the commuity will plan which mount type in the future?

**Comment by Madhu-1** [comment]
This is not a ceph-csi specific question I would suggest you connect to ceph mailing list https://ceph.io/irc/

we currently have an issue with NBD when the driver container as it loses all the mounts

in ceph-csi, we have plan to support both krbd and nbd 

cc @dillaman
