### ISSUE TITLE
Add support for CSI metrics kubernetes sidecar is exposing

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#881]
currently, in ceph-csi we are exposing the GRPC metrics, now Kubernetes sidecar is providing an option to expose the GRPC metrics from each sidecar container. we should drop the current support of exposing our own metrics  and start supporting the sidecar metrics

**Comment by Madhu-1** [comment]
@agarwal-mudit would you like to take this up?

**Comment by agarwal-mudit** [comment]
Sure, please assign.

**Comment by Madhu-1** [comment]
@agarwal-mudit do we need it in release-3.0.0 milestone? or can we move it outside

**Comment by agarwal-mudit** [comment]
We can move, I missed working on this and now it would be difficult to meet the timelines because it might need more testing. Will fix it in next release.

**Comment by Madhu-1** [comment]
> We can move, I missed working on this and now it would be difficult to meet the timelines because it might need more testing. Will fix it in next release.

Thanks, @agarwal-mudit moving it out of release-v3.0.0 milestone

**Comment by Madhu-1** [comment]
We already deprecated the grpc metrics in cephcsi, I think now we can remove it. This will also solve the issue of port conflict when cephcsi is used with hostnetworking enabled.

cc @nixpanic
