### ISSUE TITLE
Remove support for PVC created by v1.0.0 CSI driver

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#882]
currently, we have support for the mounting and deleting the PVC created by v1.0.0 CSI driver. we need to drop the support for the same.

we are yet to decide in which release we are deprecating and removing it

**Comment by gman0** [comment]
Please do keep a way to mount a CephFS volume by specifying monitor addresses and a root path (in `NodeStageVolume`/`NodePublishVolume`). We're relying on this functionality.

**Comment by Madhu-1** [comment]
> Please do keep a way to mount a CephFS volume by specifying monitor addresses and a root path (in `NodeStageVolume`/`NodePublishVolume`). We're relying on this functionality.

do you mean CephFS subvolume? we have an option to specify `rootPath` https://github.com/ceph/ceph-csi/blob/master/pkg/cephfs/volumeoptions.go#L344 in static PVC.
Am I missing something? can you please elaborate more

**Comment by gman0** [comment]
@Madhu-1 as far as I understand, removing support for v1 volumes means removing this:

https://github.com/ceph/ceph-csi/blob/58765e27a0f1c92062e5468cf97cbdb2c444ec9e/pkg/cephfs/nodeserver.go#L101-L106

There are cases where populating the [CSI config file](https://github.com/ceph/ceph-csi/blob/58765e27a0f1c92062e5468cf97cbdb2c444ec9e/pkg/util/csiconfig.go#L49) is difficult e.g. when Ceph clusters are managed externally and we don't know the list of monitor IPs beforehand. The CephFS subvolume might be provisioned from an external source and CephFS CSI node plugin should still be able to mount this volume into a workload.

I'd like to ask you guys to leave a way to pass in the `rootPath` you've mentioned _and_ [list of monitors](https://github.com/ceph/ceph-csi/blob/58765e27a0f1c92062e5468cf97cbdb2c444ec9e/pkg/cephfs/volumeoptions.go#L269-L272) via the NodeStageVolume volume context, bypassing the cluster ID -> monitors mapping.

**Comment by ShyamsundarR** [comment]
> There are cases where populating the [CSI config file](https://github.com/ceph/ceph-csi/blob/58765e27a0f1c92062e5468cf97cbdb2c444ec9e/pkg/util/csiconfig.go#L49) is difficult e.g. when Ceph clusters are managed externally and we don't know the list of monitor IPs beforehand. The CephFS subvolume might be provisioned from an external source and CephFS CSI node plugin should still be able to mount this volume into a workload.

@gman0 the nodeplugins also mount the CSI config file, and hence contain the required MON addresses to use.

Mentioning the MONs in the StorageClass needs to be done for all StorageClass's in use and further needs to be updated when MONs change. Instead, specifying this once in the CSI config, would enable global updates at a single point. (this is when considering external clusters as well).

Also, StorageClass is not editable, and hence to update MONs the admin would need to recreate the StorageClass with the new MON addresses.

The config map in kubernetes is also periodically updated, and hence does not need a restart of the nodeplugin (or the provisioner) to take in new values.

IMO, leveraging the CSI config for external clusters is preferred given the above.

**Comment by gman0** [comment]
@ShyamsundarR 

> Also, StorageClass is not editable, and hence to update MONs the admin would need to recreate the StorageClass with the new MON addresses.
>
> The config map in kubernetes is also periodically updated, and hence does not need a restart of the nodeplugin (or the provisioner) to take in new values.
> 
> IMO, leveraging the CSI config for external clusters is preferred given the above.

I understand why it's done like this and I agree with the way it's handled for those use-cases.

> the nodeplugins also mount the CSI config file, and hence contain the required MON addresses to use.
> 
> Mentioning the MONs in the StorageClass needs to be done for all StorageClass's in use and further needs to be updated when MONs change. Instead, specifying this once in the CSI config, would enable global updates at a single point. (this is when considering external clusters as well).

In the use-case I mentioned, the source of truth for monitor IPs is OpenStack Manila / Cinder, so the ConfigMap is left empty.

A 3rd party CSI plugin provisions a CephFS volume using the Manila service. When mounting the volume, we're given:
* mon IPs
* root path
* cephx ID and key

Those are then passed to csi-cephfs Node Plugin via:
* `Node{Stage,Publish}VolumeRequest.volume_context`
* `Node{Stage,Publish}VolumeRequest.secrets`

csi-cephfs's StorageClass plays no role here, because the provisioning is done elsewhere. I'm totally fine with this being removed from recognized StorageClass parameters, since we're only considering the node plugin at this point.

Is there any way a stable interface with the node plugin could be maintained, so that the values of `monitors`, `rootPath` (and of course `userID`,  `userKey`) are honored when mounting? When present, they'd override the values from the config file.

I am more than happy to work on a PR, if you agree!

**Comment by ShyamsundarR** [comment]
> csi-cephfs's StorageClass plays no role here, because the provisioning is done elsewhere. I'm totally fine with this being removed from recognized StorageClass parameters, since we're only considering the node plugin at this point.

Understood.

> 
> Is there any way a stable interface with the node plugin could be maintained, so that the values of `monitors`, `rootPath` (and of course `userID`, `userKey`) are honored when mounting? When present, they'd override the values from the config file.

@Madhu-1 thoughts? I am fine with request made by @gman0 given the context and restrictions as above.

**Comment by Madhu-1** [comment]
opened #1226 to remove the support but keeping the support request from @gman0 for cephfs mounting.

**Comment by strigazi** [comment]
@gman0 does this mean after #1226 manila-csi won't be able to use ceph-csi?

**Comment by gman0** [comment]
@strigazi no, we're making sure it will keep working :)
