### ISSUE TITLE
export ceph rbd driver field

### ISSUE THREAD

**Issue by yuquan-wang** [ceph/ceph-csi#903]
# Describe the feature you'd like to have #
I'm developing my own ceph csi plugin based on this project, I want to access those unexported fields defined in driver.go like following

```
type Driver struct {
	cd *csicommon.CSIDriver // can we make it public or add get method to export it?

	ids *IdentityServer // same as above
	ns  *NodeServer // same as above
	cs  *ControllerServer // same as above
}
```
By the way, i'm also using ebs-driver, which i can use `driver.publishVolume()` for my own logic

If you don't mind, I can contribute a PR for this issue.

# What new functionality do you want? #
access to unexported fields so that we can make our own plugin based on this project

# What is the value to the end user? (why is it a priority?) #
enable user to develop their own plugin

# How would the end user gain value from having this feature? #
obviously user can make their own logic for csi

**Comment by nixpanic** [comment]
Could you explain why you want your own variation of ceph-csi? We're happy to get more features and other enhancements included in this project. Have you considered contributing your changes?

**Comment by yuquan-wang** [comment]
Sure, so we have the special usage to let all applications in one node to share a pv, that's the reason we may need variation of ceph-csi and create our own storage class for use.
Not sure if it is common usage or not, if it is, we'd like to contribute.

**Comment by Madhu-1** [comment]
> Sure, so we have the special usage to let all applications in one node to share a pv, that's the reason we may need variation of ceph-csi and create our own storage class for use.
> Not sure if it is common usage or not, if it is, we'd like to contribute.

If I understood the use-case correctly I think it should be possible with current driver itself, as you can attach a PVC to all applications, whichever comes on the same node will share the PVC. 

am I missing something?

**Comment by yuquan-wang** [comment]
@Madhu-1  thanks for reply, "attach a PVC to all applications" didn't meet our requirement, reason as follow:
1.  PVC has namespace, we can not let all application under different namespace share one PVC
2.  Application may have several instances, then all of them may refer to same pv, that's not what we want in our case, what we want is application share pv in same node, but pv between nodes should be different.

**Comment by Madhu-1** [comment]
@humblec @nixpanic @ShyamsundarR do you have any comments?

**Comment by humblec** [comment]
@yuquan-wang let me try to understand this scenario some more better. Some comments inline. 

> 
>     1. PVC has namespace, we can not let all application under different namespace share one PVC
> 
>     2. Application may have several instances, then all of them may refer to same pv, that's not what we want in our case, what we want is application share pv in same node, but pv between nodes should be different.

 When you say the application may have several instances and also you want seperate PVs , Isnt it the use case for deploying an application with statefulset deployment model or so?

**Comment by yuquan-wang** [comment]
@humblec  yes, we are using statefulset for our application,  but that's not enough. I can explain it more detailly.

We have application A want to run in every node to provide some basic service, also we have other applications(we call it B, C and D) may run with A in same node, then A will share pv with B,C,D, no matter what happened(like instance reschedule), in that node, pv requested by B, C, D will always be the same one as A. A will be read write and B(C, D) will be read only.

**Comment by nixpanic** [comment]
From what I understand what is written, I think it is possible with (partial) static provisioning? Is the following an options for you (thinking out loud here)?

1. request a PVC
1. once the PVC is Bound, inspect it and detect the PV
1. use the PV for static provisioning a PVC for pods B, C and D

The sharing by itself (partially RWO/RWX and partially ROX) does seem dangerous. The PVC does not guarantee data consistency between the operations that write/update and read. It still needs a strict workflow in order to prevent B, C and D from reading incomplete data (unfinished writes).

Also note [this quote from the kubernetes docs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes):

> **Important!** A volume can only be mounted using one access mode at a time, even if it supports many. For example, a GCEPersistentDisk can be mounted as ReadWriteOnce by a single node or ReadOnlyMany by many nodes, but not at the same time.

What you describe seems a pretty unique use-case. Maybe there are better and more secure (data consistency) ways to achieve what you are doing...

**Comment by yuquan-wang** [comment]
Hi, @nixpanic  the option you described is what we want to do based on ceph-csi, first A request a PVC and bound with PV, then we record the mapping of volumeId and NodeId, when B,C and D request PVC, then we just find right volume to bound to PVC.
We want to achieve above logic, but currently unable to do it because in driver those fields are private, thus we can not make use in our project.

About the security(data consistency) issue, I'll discuss that with my team member.

**Comment by yuquan-wang** [comment]
@nixpanic 
I just discussed security(data consistency) issue with my team mate, we don't think that would be a problem in our case, because we only care one PV is shared in same node.

About the option you described: (partial) static provision, which is actually not practical I think in our case(Because we don't know which node application B will go to, then how could we know which pv should bound to requested pvc, note we may have different pvcs for application A)

I agree that our use-case is a pretty unique use-case, so we plan to develop our own csi plugin based on this project. May i get a direction on if we could support this ticket?

**Comment by yuquan-wang** [comment]
Is there any update on this issue?

**Comment by Madhu-1** [comment]
@nixpanic @humblec any thought on exposing the structure?

**Comment by nixpanic** [comment]
On Fri, Apr 03, 2020 at 05:22:42AM -0700, Madhu Rajanna wrote:
> @nixpanic @humblec any thought on exposing the structure?

I do not know if we can commit to keeping a stable API for things like
this... Even the API in the `pkg/` directory is not considered stable
for use outside of this project.

Would we want to include such a feature in this project, eventually? Or,
maybe maintain it in a seperate branch? I am concerned that we
unintentionally break the diverged provisioner at one point.

**Comment by Madhu-1** [comment]
> On Fri, Apr 03, 2020 at 05:22:42AM -0700, Madhu Rajanna wrote: @nixpanic @humblec any thought on exposing the structure?
> I do not know if we can commit to keeping a stable API for things like this... Even the API in the `pkg/` directory is not considered stable for use outside of this project. Would we want to include such a feature in this project, eventually? Or, maybe maintain it in a seperate branch? I am concerned that we unintentionally break the diverged provisioner at one point.

+1 we cannot maintain keep the API's stable.
