### ISSUE TITLE
when csi-plugin need exit and restart for upgrade or painc, pod will recive  error msg that 'Transport endpoint is not connected',

### ISSUE THREAD

**Issue by huaizong** [ceph/ceph-csi#91]
when csi-plugin exit and restart for upgrade or painc, pod will recive  error msg that 'Transport endpoint is not connected', is cephfs-csi plan to support remount history mounted path when 
csi-plugin start

```
df: ‘/var/lib/kubelet/pods/d132d662-d1d1-11e8-8297-28d24488ad30/volumes/kubernetes.io~csi/pvc-d123868ad1d111e8/mount’: Transport endpoint is not connected
```

**Comment by gman0** [comment]
Please attach the plugin logs.

**Comment by huaizong** [comment]
what i mean is that may be ceph-csi need a feature that can mounted history mounted path,

**Comment by rootfs** [comment]
mountpath is given by kubelet. if the pod is deleted, the mountpoint will be gone too.

**Comment by huaizong** [comment]
> mountpath is given by kubelet. if the pod is deleted, the mountpoint will be gone too.

 if we need upgrade ceph-csi now, we need to taint all node all drain all pod that used ceph-csi plugin ,  so if the ceph-csi plugin support  remount last mounted path,  may be ceph-csi plugin can support rolling update

**Comment by rootfs** [comment]
yes, drain the node before update. It is not the best solution but gives you some protection

**Comment by Madhu-1** [comment]
@rootfs do we need to do something in the code to fix this issue? if not can we close this one?

**Comment by rootfs** [comment]
@Madhu-1 would you add a upgrade process in readme? for cephfs mount, drain the node before upgrade. I believe this process applies to other FUSE mount drivers too.

**Comment by huaizong** [comment]
@rootfs  as mentioned in #217 if csi plugin exit unexpect,  the pod use cephfs pv can not auto recovery until  pod  be killed and reschedule.  i think this is may be a problem.  may be it can do more thing to remount  the old path  so when pod may be auto recovery  when  exit and  restart ,  the old mount path can use
