### ISSUE TITLE
use csi rbd driver v2.0.1 but pv and volume can not dynamic create report an operation with the given Volume ID already exists

### ISSUE THREAD

**Issue by jianglingxia** [ceph/ceph-csi#911]
# Describe the bug #
the csi rbd driver running like this :
`
csi-rbdplugin-gv7bf                                   3/3     Running   0          3h34m   193.101.0.89      <none>           <none>
csi-rbdplugin-provisioner-6f796969c7-26h78            6/6     Running   0          3h35m   193.101.0.86      <none>           <none>
csi-rbdplugin-provisioner-6f796969c7-5wttl            6/6     Running   0          3h35m   193.101.0.87      <none>           <none>
csi-rbdplugin-provisioner-6f796969c7-rdn58            6/6     Running   0          3h35m   193.101.0.85        <none>           <none>
csi-rbdplugin-xlf5g                                   3/3     Running   0          3h34m   193.101.0.88
`
the storageclass is 
`csi-rbd-sc            ceph1.rbd.csi.ceph.com      Delete          Immediate           true                   27m`
but create pvc then the pv and volume can not dynamic created

the csi-rbd-porivisioner logs 
`I0403 16:39:18.872687       1 utils.go:157] ID: 333 Req-ID: pvc-3c168a99-2b3d-41bd-9ab8-a577c4da0d85 GRPC call: /csi.v1.Controller/CreateVolume
I0403 16:39:18.872699       1 utils.go:158] ID: 333 Req-ID: pvc-3c168a99-2b3d-41bd-9ab8-a577c4da0d85 GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-3c168a99-2b3d-41bd-9ab8-a577c4da0d85","parameters":{"clusterID":"ba6bf412-5c49-11ea-a93b-84139f316b05","imageFeatures":"layering","mounter":"rbd-nbd","pool":"rbd"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["discard"]}},"access_mode":{"mode":1}}]}
I0403 16:39:18.874339       1 rbd_util.go:487] ID: 333 Req-ID: pvc-3c168a99-2b3d-41bd-9ab8-a577c4da0d85 setting disableInUseChecks on rbd volume to: false
I0403 16:39:18.874359       1 controllerserver.go:138] ID: 333 Req-ID: pvc-3c168a99-2b3d-41bd-9ab8-a577c4da0d85 an operation with the given Volume ID pvc-3c168a99-2b3d-41bd-9ab8-a577c4da0d85 already exists
E0403 16:39:18.874378       1 utils.go:161] ID: 333 Req-ID: pvc-3c168a99-2b3d-41bd-9ab8-a577c4da0d85 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-3c168a99-2b3d-41bd-9ab8-a577c4da0d85 already exists
`

# Environment details #
kubernetes v1.17
Server Version: 17.03.3
- Image/version of Ceph CSI driver
- helm chart version
- Kubernetes cluster version
- Logs

# Steps to reproduce #

1. Setup details: '...'
1. Deployment to trigger the issue '....'
1. See error

# Actual results #

Describe what happened

# Expected behavior #

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by Madhu-1** [comment]
please provide csi-rbdplugin container logs from provisioner pod

note:  rbd-nbd is not completely supported now, please use kernel rbd for now

**Comment by jianglingxia** [comment]
but the krbd need the kernel version high,my kernel version is 3.10

the csi-rbdplugin provisioner is 

`I0403 16:53:06.966654       1 utils.go:157] ID: 357 Req-ID: pvc-ff331283-c579-4740-a7b1-f71d4cf3336e GRPC call: /csi.v1.Controller/CreateVolume
I0403 16:53:06.966662       1 utils.go:158] ID: 357 Req-ID: pvc-ff331283-c579-4740-a7b1-f71d4cf3336e GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-ff331283-c579-4740-a7b1-f71d4cf3336e","parameters":{"clusterID":"ba6bf412-5c49-11ea-a93b-84139f316b05","dataPool":"cephrbd-mate","imageFeatures":"layering","mounter":"rbd-nbd","pool":"rbdpool"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["discard"]}},"access_mode":{"mode":1}}]}
I0403 16:53:06.968281       1 rbd_util.go:487] ID: 357 Req-ID: pvc-ff331283-c579-4740-a7b1-f71d4cf3336e setting disableInUseChecks on rbd volume to: false
I0403 16:53:06.968300       1 controllerserver.go:138] ID: 357 Req-ID: pvc-ff331283-c579-4740-a7b1-f71d4cf3336e an operation with the given Volume ID pvc-ff331283-c579-4740-a7b1-f71d4cf3336e already exists
E0403 16:53:06.968322       1 utils.go:161] ID: 357 Req-ID: pvc-ff331283-c579-4740-a7b1-f71d4cf3336e GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-ff331283-c579-4740-a7b1-f71d4cf3336e already exists
I0403 16:53:16.956966       1 utils.go:157] ID: 358 Req-ID: pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f GRPC call: /csi.v1.Controller/CreateVolume
I0403 16:53:16.956974       1 utils.go:158] ID: 358 Req-ID: pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f","parameters":{"clusterID":"ba6bf412-5c49-11ea-a93b-84139f316b05","dataPool":"cephrbd-mate","imageFeatures":"layering","mounter":"rbd-nbd","pool":"rbdpool"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["discard"]}},"access_mode":{"mode":1}}]}
I0403 16:53:16.958625       1 rbd_util.go:487] ID: 358 Req-ID: pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f setting disableInUseChecks on rbd volume to: false
I0403 16:53:16.958642       1 controllerserver.go:138] ID: 358 Req-ID: pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f an operation with the given Volume ID pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f already exists
E0403 16:53:16.958663       1 utils.go:161] ID: 358 Req-ID: pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f already exists
`
and the sidecar provisioner is 

`I0403 16:55:24.021883       1 connection.go:184] GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f already exists
I0403 16:55:24.021914       1 controller.go:1023] Temporary error received, adding PVC 8cb1df34-c20d-426c-8301-f7a7acc2a71f to claims in progress
W0403 16:55:24.021926       1 controller.go:887] Retrying syncing claim "8cb1df34-c20d-426c-8301-f7a7acc2a71f", failure 8
E0403 16:55:24.021947       1 controller.go:910] error syncing claim "8cb1df34-c20d-426c-8301-f7a7acc2a71f": failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f already exists
I0403 16:55:24.021966       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"rbd-pvc-1", UID:"8cb1df34-c20d-426c-8301-f7a7acc2a71f", APIVersion:"v1", ResourceVersion:"1474557", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f already exists
I0403 16:55:26.810481       1 leaderelection.go:282] successfully renewed lease default/ceph1-rbd-csi-ceph-com
I0403 16:55:31.815771       1 leaderelection.go:282] successfully renewed lease default/ceph1-rbd-csi-ceph-com
I0403 16:55:36.820298       1 leaderelection.go:282] successfully renewed lease default/ceph1-rbd-csi-ceph-com
`

**Comment by Madhu-1** [comment]
@jianglingxia i need complete csi-rbdplugin logs to analyze it

**Comment by jianglingxia** [comment]
[Uploading ceph1_deploy_rbd_provisioner.txt…]()

**Comment by jianglingxia** [comment]
can you see it ? i will later try it really thanks

**Comment by jianglingxia** [comment]
@Madhu-1   really sorry that my network maybe some error can not attach files

the pvc is pending logs are : failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f already exists

the rbd plugin log is: 
controllerserver.go:138] ID: 7706 Req-ID: pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f an operation with the given Volume ID pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f already exists

i see the code report is create volume function 

	// Existence and conflict checks
	if acquired := cs.VolumeLocks.TryAcquire(req.GetName()); !acquired {
		klog.Infof(util.Log(ctx, util.VolumeOperationAlreadyExistsFmt), req.GetName())
		return nil, status.Errorf(codes.Aborted, util.VolumeOperationAlreadyExistsFmt, req.GetName())
	}

is the leader election error or need some switch to open? really thanks

**Comment by Madhu-1** [comment]
this is nothing to do with leader election. we will through this error when there is an ongoing operation for the same PVC.  maybe some commands are struck inside the csi-rbdplugin container need to identify that first. if you can provide the logs I can take a look at it also please check no pending or struck commands on container, 

execute below commands in csi-rbdplugin container
`ps -ef |grep rados`
`ps -ef |grep rbd`
`ps -ef |grep ceph`

**Comment by jianglingxia** [comment]
execute you provider the commands i below the csi-rbdplugin in deployment pod 

and i have two minion  2 deployment in one minion and 1 deployment in another minion

really thanks for you


sh-4.2# ps -ef |grep rados
root      5652     1  0 10:56 ?        00:00:00 rados -m 100.100.100.201,100.100.100.202 --id admin --keyfile=/tmp/csi/keys/keyfile-052893503 -c /etc/ceph/ceph.conf -p rbdpool getomapval csi.volumes.default csi.volume.pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f /tmp/omap-get-245919122
root      5668     1  0 11:10 ?        00:00:00 rados -m 100.100.100.201,100.100.100.202 --id admin --keyfile=/tmp/csi/keys/keyfile-747153677 -c /etc/ceph/ceph.conf -p rbdpool getomapval csi.volumes.default csi.volume.pvc-ff331283-c579-4740-a7b1-f71d4cf3336e /tmp/omap-get-171450120
root      5694     1  0 11:33 ?        00:00:00 rados -m 100.100.100.201,100.100.100.202 --id admin --keyfile=/tmp/csi/keys/keyfile-822324047 -c /etc/ceph/ceph.conf -p rbdpool getomapval csi.volumes.default csi.volume.pvc-438521bc-d1bc-409e-be51-a17a6d1c0782 /tmp/omap-get-475306082
root      5712  5704  0 11:36 pts/4    00:00:00 grep rados

sh-4.2# ps -ef |grep rbd
root         1     0  0 Apr03 ?        00:00:49 /usr/local/bin/cephcsi --nodeid=193.101.0.11 --type=rbd --controllerserver=true --endpoint=unix:///csi/csi-provisioner.sock --v=5 --logtostderr=false --log_file=/logs/ceph1_deploy_rbd_plugin.log --drivername=ceph1.rbd.csi.ceph.com --pluginpath=/paasdata/docker/plugins/ceph1rbd --pidlimit=-1 --metricsport=8090 --metricspath=/metrics --enablegrpcmetrics=false
root      5652     1  0 10:56 ?        00:00:00 rados -m 100.100.100.201,100.100.100.202 --id admin --keyfile=/tmp/csi/keys/keyfile-052893503 -c /etc/ceph/ceph.conf -p rbdpool getomapval csi.volumes.default csi.volume.pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f /tmp/omap-get-245919122
root      5668     1  0 11:10 ?        00:00:00 rados -m 100.100.100.201,100.100.100.202 --id admin --keyfile=/tmp/csi/keys/keyfile-747153677 -c /etc/ceph/ceph.conf -p rbdpool getomapval csi.volumes.default csi.volume.pvc-ff331283-c579-4740-a7b1-f71d4cf3336e /tmp/omap-get-171450120
root      5694     1  0 11:33 ?        00:00:00 rados -m 100.100.100.201,100.100.100.202 --id admin --keyfile=/tmp/csi/keys/keyfile-822324047 -c /etc/ceph/ceph.conf -p rbdpool getomapval csi.volumes.default csi.volume.pvc-438521bc-d1bc-409e-be51-a17a6d1c0782 /tmp/omap-get-475306082
root      5716  5704  0 11:37 pts/4    00:00:00 grep rbd


sh-4.2# ps -ef |grep ceph
root         1     0  0 Apr03 ?        00:00:49 /usr/local/bin/cephcsi --nodeid=193.101.0.11 --type=rbd --controllerserver=true --endpoint=unix:///csi/csi-provisioner.sock --v=5 --logtostderr=false --log_file=/logs/ceph1_deploy_rbd_plugin.log --drivername=ceph1.rbd.csi.ceph.com --pluginpath=/paasdata/docker/plugins/ceph1rbd --pidlimit=-1 --metricsport=8090 --metricspath=/metrics --enablegrpcmetrics=false
root      5652     1  0 10:56 ?        00:00:00 rados -m 100.100.100.201,100.100.100.202 --id admin --keyfile=/tmp/csi/keys/keyfile-052893503 -c /etc/ceph/ceph.conf -p rbdpool getomapval csi.volumes.default csi.volume.pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f /tmp/omap-get-245919122
root      5668     1  0 11:10 ?        00:00:00 rados -m 100.100.100.201,100.100.100.202 --id admin --keyfile=/tmp/csi/keys/keyfile-747153677 -c /etc/ceph/ceph.conf -p rbdpool getomapval csi.volumes.default csi.volume.pvc-ff331283-c579-4740-a7b1-f71d4cf3336e /tmp/omap-get-171450120
root      5694     1  0 11:33 ?        00:00:00 rados -m 100.100.100.201,100.100.100.202 --id admin --keyfile=/tmp/csi/keys/keyfile-822324047 -c /etc/ceph/ceph.conf -p rbdpool getomapval csi.volumes.default csi.volume.pvc-438521bc-d1bc-409e-be51-a17a6d1c0782 /tmp/omap-get-475306082
root      5718  5704  0 11:37 pts/4    00:00:00 grep ceph


the provisioner log is 

I0407 11:40:27.899519       1 connection.go:184] GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-438521bc-d1bc-409e-be51-a17a6d1c0782 already exists
I0407 11:40:27.899568       1 controller.go:1023] Temporary error received, adding PVC 438521bc-d1bc-409e-be51-a17a6d1c0782 to claims in progress
W0407 11:40:27.899584       1 controller.go:887] Retrying syncing claim "438521bc-d1bc-409e-be51-a17a6d1c0782", failure 9
E0407 11:40:27.899602       1 controller.go:910] error syncing claim "438521bc-d1bc-409e-be51-a17a6d1c0782": failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-438521bc-d1bc-409e-be51-a17a6d1c0782 already exists
I0407 11:40:27.899664       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"rbd-pvc-1", UID:"438521bc-d1bc-409e-be51-a17a6d1c0782", APIVersion:"v1", ResourceVersion:"2106965", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-rbd-sc": rpc error: code = Aborted desc = an operation with the given Volume ID pvc-438521bc-d1bc-409e-be51-a17a6d1c0782 already exists
I0407 11:40:32.198445       1 leaderelection.go:282] successfully renewed lease default/ceph1-rbd-csi-ceph-com

**Comment by jianglingxia** [comment]
maybe the log can give ours some information 

the rbd-plugin logs:

E0407 11:46:59.059338       1 cephcmds.go:186] ID: 7828 Req-ID: pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f failed getting omap value for key (csi.volume.pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f) from omap (csi.volumes.default) in pool (rbdpool): (an error (exit status 1) occurred while running rados args: [-m 100.100.100.201,100.100.100.202 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf -p rbdpool getomapval csi.volumes.default csi.volume.pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f /tmp/omap-get-245919122])
E0407 11:46:59.059455       1 utils.go:161] ID: 7828 Req-ID: pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f GRPC error: rpc error: code = Internal desc = error (an error (exit status 1) occurred while running rados args: [-m 100.100.100.201,100.100.100.202 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf -p rbdpool getomapval csi.volumes.default csi.volume.pvc-8cb1df34-c20d-426c-8301-f7a7acc2a71f /tmp/omap-get-245919122]) occurred, command output streams is ( failed to fetch mon config (--no-mon-config to skip)

**Comment by Madhu-1** [comment]
>root 5668 1 0 11:10 ? 00:00:00 rados -m 100.100.100.201,100.100.100.202 --id admin --keyfile=/tmp/csi/keys/keyfile-747153677 -c /etc/ceph/ceph.conf -p rbdpool getomapval csi.volumes.default csi.volume.pvc-ff331283-c579-4740-a7b1-f71d4cf3336e /tmp/omap-get-171450120

are you missing the Monitor port number?

**Comment by jianglingxia** [comment]
my ceph cluster use the default monitor port 6789, the rados command need the port number?
i readd the port number and recreate the pvc look the result then report you ,thanks for you 

before the cephfs command  i not use the port can exec sussess：
EXEC ceph -m 100.100.100.148,100.100.100.154,100.100.100.156 --id admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs dump --format=json

**Comment by Madhu-1** [comment]
please check are you able to execute rados commands from the csi-rbdplugin container

**Comment by jianglingxia** [comment]
rados -h command ok,but  exec the command below error,why can not exec the rados command?is there something wrong?
rados lspools report error is:

sh-4.2# rados lspools
unable to get monitor info from DNS SRV with service name: ceph-mon
2020-04-07 14:04:17.272 7ff2ee3bb880 -1 failed for service _ceph-mon._tcp
2020-04-07 14:04:17.273 7ff2ee3bb880 -1 monclient: get_monmap_and_config cannot identify monitors to contact
failed to fetch mon config (--no-mon-config to skip)


sh-4.2# rados df
unable to get monitor info from DNS SRV with service name: ceph-mon
2020-04-07 14:06:11.119 7fba8781f880 -1 failed for service _ceph-mon._tcp
2020-04-07 14:06:11.119 7fba8781f880 -1 monclient: get_monmap_and_config cannot identify monitors to contact
failed to fetch mon config (--no-mon-config to skip)

**Comment by Madhu-1** [comment]
please provide monitor and user and secretkey info while executing rados commands

**Comment by jianglingxia** [comment]
i exec this follow command and rados stunk,can you check it the command error ? or something wrong? really thanks 
sh-4.2# cd /tmp/csi/keys/
sh-4.2# ls
keyfile-684370561  keyfile-907711299  keyfile-918822446
sh-4.2# cat keyfile-907711299
AQDun1xeAAAAABAApsnXHz0DPzg+UrLfWOrxHA==sh-4.2# cat keyfile-918822446
AQDun1xeAAAAABAApsnXHz0DPzg+UrLfWOrxHA==sh-4.2# cat keyfile-684370561
AQDun1xeAAAAABAApsnXHz0DPzg+UrLfWOrxHA==sh-4.2# 
sh-4.2# 
sh-4.2# 
sh-4.2# 
sh-4.2# 
sh-4.2# rados -m 100.100.100.201:6789,100.100.100.202:6789 --id admin --keyfile=/tmp/csi/keys/keyfile-907711299 -c /etc/ceph/ceph.conf -p rbdpool 
^C
sh-4.2# 
sh-4.2# 
sh-4.2# 
sh-4.2# 
sh-4.2# rados -m 100.100.100.201:6789,100.100.100.202:6789 --id admin --keyfile=/tmp/csi/keys/keyfile-907711299 -c /etc/ceph/ceph.conf lspools

**Comment by Madhu-1** [comment]
Yes above commands are correct, looks to be a network issue. check firewall setting if you have enabled it

**Comment by jianglingxia** [comment]
why in my csi-rbdplugin container can not exec the command,i use same command to ceph cluster can fine

you see the firewall is minion or my container ? can you see more information ? really thanks 

the ceph cluster is 
[root@host-10-62-40-148 ceph]# rados -m 100.100.100.201:6789,100.100.100.202:6789 --id admin --key=AQDun1xeAAAAABAApsnXHz0DPzg+UrLfWOrxHA== -c /etc/ceph/ceph.conf lspools
CinderPool-1
CinderPool-2
CinderPool-3
nfs-meta
cephrbd-mate
rbdpool

[root@host-10-62-40-148 ceph]# rados -m 100.100.100.201:6789,100.100.100.202:6789 --id admin --key=AQDun1xeAAAAABAApsnXHz0DPzg+UrLfWOrxHA== -c /etc/ceph/ceph.conf df 
POOL_NAME    USED    OBJECTS CLONES COPIES MISSING_ON_PRIMARY UNFOUND DEGRADED RD_OPS   RD      WR_OPS   WR      
CinderPool-1  156GiB   40489      0  40489                  0       0        0 15439510  142GiB 37988954  775GiB

**Comment by Madhu-1** [comment]
check with minion(Node)  i dont see any issue with container

**Comment by jianglingxia** [comment]
i found my minion can ping the monitor but my rbd-plugin container can not ping monitor 
i will remodify it then depoly it,if ok then i will report the result to you, really thanks

**Comment by jianglingxia** [comment]
> please provide csi-rbdplugin container logs from provisioner pod
> 
> note: rbd-nbd is not completely supported now, please use kernel rbd for now

-->you note the rbd-nbd function not completely support,compare to krbd the rbd-nbd now not support which function?really thanks

@Madhu-1  i have resolve the network problem then can dynamic create rbd volume and pv 
[root@paas-controller-103-11-0-0:/home/ubuntu/jjj/rbd]$ kubectl get pvc -w             
NAME        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
rbd-pvc-1   Bound    pvc-c3568799-e247-40d0-8e42-11a4b76364f5   1Gi        RWO            csi-rbd-sc     3s

the volume in ceph cluster :
[root@host-ceph]# rbd ls rbdpool
csi-vol-887d5fcc-78a2-11ea-ae56-0679a86b5326

**Comment by Madhu-1** [comment]
all mount points will disappear if the csi-rbdplugin restarts if you are using rbd-nbd
