### ISSUE TITLE
ceph-rbd does not support "Many Nodes Read-Only" access mode

### ISSUE THREAD

**Issue by Born2Bake** [ceph/ceph-csi#914]
# Describe the bug #
Hi,
Using ceph-csi-rbd provisioner, I cant use Many Nodes Read-Only rbd volumes. Containers are crashed specifying that they cant attach volume cause its already attached. However, if I create storage class old fashioned way and connect to my ceph cluster, I can create volume and it can be attached to many nodes ro. Old fashion way of rbd storage class: https://pastebin.com/BuT8wBDr

Thank you

# Environment details #

- Image/version of Ceph CSI driver: latest
- helm chart version
- Kubernetes cluster version: 1.17
- Logs

**Comment by Madhu-1** [comment]
closing this as deplicate of https://github.com/ceph/ceph-csi/issues/725
