### ISSUE TITLE
Move helm version to 3.x in install-helm.sh

### ISSUE THREAD

**Issue by ShyamsundarR** [ceph/ceph-csi#920]
Helm v3 no longer requires any in cluster components (like tiller) and makes it quite easy to use as a deployment mechanism (no kubernetes components need to be deployed). I suggest that we shift to the same to make the script easier to maintain.

For helm v3 the install command for any chart needs to change like so,

```
-    "${HELM}" install "${SCRIPT_DIR}"/../charts/ceph-csi-cephfs --name ${CEPHFS_CHART_NAME} --namespace ${NAMESPACE} --set provisioner.fullnameOverride=csi-cephfsplugin-provisioner --set nodeplugin.fullnameOverride=csi-cephfsplugin --set configMapName=ceph-csi-config --set provisioner.podSecurityPolicy.enabled=true --set nodeplugin.podSecurityPolicy.enabled=true
+    "${HELM}" install --namespace ${NAMESPACE} --set provisioner.fullnameOverride=csi-cephfsplugin-provisioner --set nodeplugin.fullnameOverride=csi-cephfsplugin --set configMapName=ceph-csi-config --set provisioner.podSecurityPolicy.enabled=true --set nodeplugin.podSecurityPolicy.enabled=true ${CEPHFS_CHART_NAME} "${SCRIPT_DIR}"/../charts/ceph-csi-cephfs
```

IOW, no `--name` parameter and also the chart path and name move to the end of the CLI.

I would suggest that we change the script to require v3 as the minimum and not write code to support both, as the intent is to keep the code simpler with this change.

**Comment by Madhu-1** [comment]
Sure it's nice to have thanks @ShyamsundarR
