### ISSUE TITLE
How can I expand PVC? Please help me 

### ISSUE THREAD

**Issue by luhailiang0527** [ceph/ceph-csi#923]
information:
[root@lu csi]# kubectl get sc,pvc,pv
NAME                                     PROVISIONER        RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
storageclass.storage.k8s.io/csi-rbd-sc   rbd.csi.ceph.com   Delete          Immediate           true                   20m

NAME                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/rbd-pvc   Bound    pvc-aa59999c-bd55-44d5-ba19-80d6f8bec547   1Gi        RWO            csi-rbd-sc     20m

NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM             STORAGECLASS   REASON   AGE
persistentvolume/pvc-aa59999c-bd55-44d5-ba19-80d6f8bec547   1Gi        RWO            Delete           Bound    default/rbd-pvc   csi-rbd-sc              20m

when i kubectl edit pvc do change 1G to 2G,but no success,I found it by checking kubectl describe pvc:

  Normal   ExternalProvisioning   17m                  persistentvolume-controller                                                                      waiting for a volume to be created, either by external provisioner "rbd.csi.ceph.com" or manually created by system administrator
  Normal   Provisioning           17m                  rbd.csi.ceph.com_csi-rbdplugin-provisioner-59957d9fc-2xkkh_73fd7fd5-4001-4ab7-a6d3-38f619b79886  External provisioner is provisioning volume for claim "default/rbd-pvc"
  Normal   ProvisioningSucceeded  17m                  rbd.csi.ceph.com_csi-rbdplugin-provisioner-59957d9fc-2xkkh_73fd7fd5-4001-4ab7-a6d3-38f619b79886  Successfully provisioned volume pvc-aa59999c-bd55-44d5-ba19-80d6f8bec547
  Warning  ExternalExpanding      16m                  volume_expand                                                                                    Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   Resizing               3m5s (x12 over 16m)  external-resizer rbd.csi.ceph.com                                                                External resizer is resizing volume pvc-aa59999c-bd55-44d5-ba19-80d6f8bec547
  Warning  VolumeResizeFailed     3m5s (x12 over 16m)  external-resizer rbd.csi.ceph.com                                                                resize volume pvc-aa59999c-bd55-44d5-ba19-80d6f8bec547 failed: rpc error: code = Internal desc = provided secret is empty

**Comment by Madhu-1** [comment]
do you have controller expand secrets in your storageclass? if no please add it to your storage class and recreate it and create a new PVC and try to resize it

**Comment by Madhu-1** [comment]
closing this as not a issue

**Comment by luhailiang0527** [comment]
@Madhu-1  thank you very much for this issue. and i also have a problem,How to migrate PV，PVC created by different storageclasses，Details are as follows：
**source storageclass**
NAME   PROVISIONER    RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
slow   ceph.com/rbd   Retain          Immediate           true                   27d
**destination storageclass**
NAME   PROVISIONER  RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-rbd-sc   rbd.csi.ceph.com   Delete          Immediate           true                   3d17h
