### ISSUE TITLE
After upgrade, the resize capability is not working for the existing PV/PVC

### ISSUE THREAD

**Issue by yanchicago** [ceph/ceph-csi#935]
# Describe the bug #

After upgrade to ceph-csi 2.0.1, the resize feature only applies to a new PVC not the existing PVC. 

# Environment details #

- Image/version of Ceph CSI driver: cephcsi:v2.0.1, csi-resizer:v0.4.0
- helm chart version
- Kubernetes cluster version:  v1.16.4
- Logs

# Steps to reproduce 

1. Setup details: '...'
1. Deployment to trigger the issue '....'
1. See error

Note: It could be an enhancement?

1). Deployed rook ceph 1.1.7
2). Upgrade rook ceph cluster to 1.2.7
3). Force replace the existing storage class with additional parameters:  "allowVolumeExpansion: true
" and "csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner".
4). Try "resize" an existing PVC of a statefulset, the operation failed with below error in csi-resizer pod.
Note: For the newly created PVC
```
I0413 18:03:23.398029       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"rook-ceph", Name:"my-block-testrookblk-0", UID:"6c444e06-1442-4018-bc45-30f39cc9e1a5", APIVersion:"v1", ResourceVersion:"76782351", FieldPath:""}): type: 'Warning' reason: 'VolumeResizeFailed' resize volume pvc-6c444e06-1442-4018-bc45-30f39cc9e1a5 failed: rpc error: code = Internal desc = provided secret is empty
```

# Actual results #

Describe what happened
The size of PVC stays as the same. 

# Expected behavior #

The size of PVC should be changed to the requested size provided by "resize"

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior
There're two existing similar problems. 
https://github.com/ceph/ceph-csi/issues/783
https://github.com/ceph/ceph-csi/issues/923

**Comment by Madhu-1** [comment]
I already created a kubernetes issue for the same https://github.com/kubernetes/kubernetes/issues/88622

**Comment by Madhu-1** [comment]
This is not something can be done in cephcsi directly, this has to be fixed in kubernetes closing this one
