### ISSUE TITLE
protect against concurrent gRPC calls

### ISSUE THREAD

**Issue by pohly** [ceph/ceph-csi#94]
gRPC executes each method call in its own goroutine. Therefore access to global data structures must be protected against concurrent access and long-running operations (like volume provisioning) must ensure that the same operation doesn't get triggered twice.

**Comment by pohly** [comment]
https://github.com/ceph/ceph-csi/pull/92 tries to solve some of this, but probably won't be complete, hence this issue.

**Comment by Madhu-1** [comment]
this is fixed in #443
