### ISSUE TITLE
simplify volume and snapshot ID

### ISSUE THREAD

**Issue by pohly** [ceph/ceph-csi#95]
The following comment isn't correct, as confirmed by the CSI developers on Slack:
```
// Generating Volume Name and Volume ID, as according to CSI spec they MUST be different
```
https://github.com/ceph/ceph-csi/blob/188cdd1d683dbfcca7c376112c2216fd77b78339/pkg/rbd/controllerserver.go#L85-L90

The spec says they MAY be different, not MUST.

Perhaps simplify the code by using the volume name also as ID?

The same probably applies to snapshots.

**Comment by gman0** [comment]
[RPC Interactions](https://github.com/container-storage-interface/spec/blob/master/spec.md#rpc-interactions):
> It is worth noting that the plugin-generated volume_id is a REQUIRED field for the DeleteVolume RPC, as opposed to the CO-generated volume name that is REQUIRED for the CreateVolume RPC: these fields MAY NOT contain the same value. 

Maybe I'm misunderstanding (this line is indeed a bit confusing) but it really does sound like they are supposed to be different.

**Comment by Madhu-1** [comment]
the req.Name() is  a mandatory parameter . so we won't be constructing our own volume name
as this is not going to happen. closing this one
