### ISSUE TITLE
cephcsi v2.1.0 helm charts are not release

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#959]
cephcsi helm charts for release v2.1.0 is not present in https://github.com/ceph/csi-charts, we have only 2.0.1 as of now.

**Comment by Madhu-1** [comment]
CC @humblec

**Comment by Madhu-1** [comment]
@humblec @nixpanic how about doing a minor release today to get updated missing helm charts?

**Comment by humblec** [comment]
Is this something we missed @Madhu-1 at time of `2.1.0` ?

**Comment by humblec** [comment]
IMO, Instead of doing a minor release just for this, lets do it with maybe with some more fixes..etc with delay.

**Comment by Madhu-1** [comment]
This is due to the failed arm64 building during a release, as the deployment got failed when building the arm64 image it exited

**Comment by nixpanic** [comment]
Is it possible to manually push the charts and fix the automated push for the next release? That would be my preference.

**Comment by Madhu-1** [comment]
> Is it possible to manually push the charts and fix the automated push for the next release? That would be my preference.

i don't have the access. only @humblec is having. @humblec can you push helm charts for 2.1.0 release?

**Comment by humblec** [comment]
Sure. .will do.

**Comment by humblec** [comment]
> Sure. .will do.

It should be resolved now. v2.1.0 charts are available here for both rbd and cephfs.  https://github.com/ceph/csi-charts

**Comment by nixpanic** [comment]
@humblec should those also get tagged in the csi-charts repository? It seems there are no tags now, but that might be a good enhancement so that pointing to a release is easy.

**Comment by humblec** [comment]
> @humblec should those also get tagged in the csi-charts repository? It seems there are no tags now, but that might be a good enhancement so that pointing to a release is easy.

Yeah, make sense and its available now :+1:  @nixpanic

**Comment by Madhu-1** [comment]
this is fixed now
