### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by pohly** [ceph/ceph-csi#96]
Can a new release of ceph-csi be released? Looks like master has accumulated a good number of fixes (PR #92, PR #84, PR #89) and features (PR #79), so perhaps a 0.4 is justified or even required (0.3 is not working for me)?

**Comment by rootfs** [comment]
we need some release engineering here :) 
currently the release tag is tied up to the csi spec, we need a branching mechanism instead.

**Comment by rootfs** [comment]
btw, merged code is always built into the container image.

**Comment by pohly** [comment]
Huamin Chen <notifications@github.com> writes:
> btw, merged code is always built into the container image.

Right, I had forgotten that v0.3.0 gets continuously updated. Good, so I
can already use a prebuild image :-)

Or bad, depending on how you look at it - it would be better to tag
releases and then build images for each fixed release.

**Comment by kfox1111** [comment]
+1. I didn't realize v0.3.0 image was rebuilt. so I could have version skew on my clusters...

**Comment by Madhu-1** [comment]
master is based on v1.1.0 spec we have done the v1.1.0 couple of days back, and we won't be maintaining v0.3 anymore. closing this one
