### ISSUE TITLE
Update Prepare.sh in centos CI branch

### ISSUE THREAD

**Issue by Madhu-1** [ceph/ceph-csi#968]
Update the `prepare.sh` script in [ci/centos](https://github.com/ceph/ceph-csi/blob/ci/centos/prepare.sh) to pull the latest pull request (PR)  which is required for centos CI integration with cephcsi project.

**Comment by Madhu-1** [comment]
cc @Yuggupta27

**Comment by nixpanic** [comment]
The `prepare.sh` script is executed in the [Jenkins Pipeline `make-containerized-build.groovy`](https://github.com/ceph/ceph-csi/blob/ci/centos/make-containerized-build.groovy) and receives several parameters. The script does currently not interpret or handle any parameters at all.

Ideally the `prepare.sh` script uses a parameter `--ref=pulls/123/head` that points to the PR or branch that needs to get cloned/checkedout. The [Samba nightly build script](https://github.com/gluster/centosci/blob/master/jobs/scripts/nightly-samba-builds/nightly-samba-builds.sh#L32) does something similar, see the usage of `ghprbPullId` (as an environment variable there, not paramater as we want in `prepare.sh`).

**Comment by Yuggupta27** [comment]
Okay, I'll keep that in mind! Thanks

**Comment by Madhu-1** [comment]
closing this as #997 is merged
