### ISSUE TITLE
failed to open log file in /var/log/pods/

### ISSUE THREAD

**Issue by mobilesfinks** [ceph/ceph-csi#969]
# Describe the bug #

On 1 of 5 nodes pod cannot start
In log of csi-rbdplugin container i see
```
failed to open log file "/var/log/pods/default_ceph-csi-rbd-nodeplugin-%some_pod_hash%/csi-rbdplugin/###.log": open /var/log/pods/default_ceph-csi-rbd-nodeplugin-%some_pod_hash%/csi-rbdplugin/###.log: no such file or directory
```
%some_pod_hash% - some hash, change when recreate container
###.log - number that correlates with the number of pod restarts

As i can see all settings on all nodes look the same

# Environment details #

- Image/version of Ceph CSI driver:  quay.io/cephcsi/cephcsi:v2.1.0
- helm chart version: ceph-csi-rbd-2.1.0-canary
- Kubernetes cluster version: v1.15.3
- Logs: look above

# Steps to reproduce #

1. just deploy 

Cant understand why this problem only on one node (named kuber-node01) and not on other. Other pods work fine

**Comment by Madhu-1** [comment]
Seeing this issue for the first time. this should be the kubernetes issue. not specific to CSI

**Comment by mobilesfinks** [comment]
May be it is k8s problem
But maybe there will be some thoughts what options and where to look?

**Comment by mobilesfinks** [comment]
i see problem on worker node. 
There are no overlayfs mounts on it - I suspect something with a docker
I think the question can be closed, indeed the matter is in kubernetes

**Comment by Madhu-1** [comment]
closing as its a CO issue

**Comment by mobilesfinks** [comment]
All problem was dissapear when i manually remove options MountPropagation from 2 volumeMounts
https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml#L126
https://github.com/ceph/ceph-csi/blob/master/charts/ceph-csi-rbd/templates/nodeplugin-daemonset.yaml#L129

Found this solution in https://github.com/kubernetes/kubernetes/issues/61058#issuecomment-372517213
