### ISSUE TITLE
Improve code quality and adhere better to Golang standards

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#975]
# Describe the feature you'd like to have #

[Go Report Card](https://goreportcard.com/report/github.com/ceph/ceph-csi) shows nice statistics about the code quality of the project. There are a few sections that do not reach 100%. This can easily be addressed, after which the configuration for the tests configuration in `scripts/golangci.yml` and similar can be updated.

# What is the value to the end user? (why is it a priority?) #

Higher code quality, more Go standardization and easier to understand code (less complex).

# How will we know we have a good solution? (acceptance criteria) #

All sections on the Go Report Card should list 100% and the tests in the repository should enforce this as much as possible.

**Comment by Yuggupta27** [comment]
Thanks. On it!

**Comment by nixpanic** [comment]
> /assign @Yuggupta27

We do not have a bot that handles these requests. Done manually now.

I have just sent a PR for one of the parts, see #977. Reviews welcome :love_you_gesture:
