### ISSUE TITLE
makefile target 'go-lint-text' is poorly named

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/ceph-csi#979]
# Describe the bug #

Running `make containerized-test` is failing for me. While attempting to debug the failure I focused a bit on the name reported by the make failure. 
```
make: *** [Makefile:67: go-lint-text] Error 123
make: *** [Makefile:85: containerized-test] Error 2
```

However, it turns out the failure had nothing to do with changes I made to go code and rather was a failure of shellcheck. Since the script `lint-text.sh` does not check Go language code at all I'd like to suggest renaming the makefile target to something a bit more accurate.

While I'm complaining about the naming-of-things, "lint-text" is not quite accurate either, I'd hesitate to call shell scripts "text".

Suggestions:
"lint-extras" or "lint-non-go"

Or perhaps it would be even clearer if the linting of shell scripts was split from the liniting of yaml and markdown files?

# Steps to reproduce #

Run `make containerized-test CONTAINER_CMD=podman` and it fails every time for me, both on master and my working branch.

**Comment by nixpanic** [comment]
I would prefer to have different targets for each test, `make containerized-test TARGET=...` can then e used to run a single target to make developing/fixing/debugging faster.
