### ISSUE TITLE
Can't get example working: GRPC error: <nil>

### ISSUE THREAD

**Issue by CompileNix** [ceph/ceph-csi#98]
I was following the readme from `examples/README.md`.
The problem happens after `kubectl create -f pvc.yaml`
The Persistent Volume Claim `rbd-pvc` hangs in the `pending` state.

I noticed that the csi-rbdplugin-provisioner and csi-rbdplugin-attacher pod are not able to reach anything in the cluster, local network or internet but the csi-rbdplugin pod can reach the k8s dns server, all ceph mon's and hosts on the internet. other pods on the same k8s nodes have no network problems, too.

Here are the logs:
[logs-from-csi-provisioner-in-csi-rbdplugin-provisioner-0.txt](https://github.com/ceph/ceph-csi/files/2555403/logs-from-csi-provisioner-in-csi-rbdplugin-provisioner-0.txt)
[logs-from-csi-rbdplugin-attacher-in-csi-rbdplugin-attacher-0.txt](https://github.com/ceph/ceph-csi/files/2555404/logs-from-csi-rbdplugin-attacher-in-csi-rbdplugin-attacher-0.txt)
[logs-from-driver-registrar-in-csi-rbdplugin-8zkw6.txt](https://github.com/ceph/ceph-csi/files/2555405/logs-from-driver-registrar-in-csi-rbdplugin-8zkw6.txt)

**Comment by compilenix** [comment]
the network problem was on my end and had nothing to do with ceph-csi.

it's still not working and the logs are looking the same as uploaded.

**Comment by rootfs** [comment]
at least the ceph keyring doesn't look right to me in the provisioner log, there was an extra trailing `\n`
`AQDi4QVa4oKkKRAAjNMW7IzhwfqSDFWyW2jaxQ==\n`

Please recreate the secret with 
`echo -n AQDi4QVa4oKkKRAAjNMW7IzhwfqSDFWyW2jaxQ==|base64`

**Comment by rootfs** [comment]
please also attach the driver log from container csi-rbdplugin here https://github.com/ceph/ceph-csi/blob/master/deploy/rbd/kubernetes/csi-rbdplugin.yaml#L41

**Comment by compilenix** [comment]
Thanks, i've recreated the secret, this part looks fine now.
A pvc can't be created, yet.

Here are the current logs:
[logs-from-csi-provisioner-in-csi-rbdplugin-provisioner-0(1).txt](https://github.com/ceph/ceph-csi/files/2559398/logs-from-csi-provisioner-in-csi-rbdplugin-provisioner-0.1.txt)
[logs-from-csi-rbdplugin-attacher-in-csi-rbdplugin-attacher-0(1).txt](https://github.com/ceph/ceph-csi/files/2559399/logs-from-csi-rbdplugin-attacher-in-csi-rbdplugin-attacher-0.1.txt)
[logs-from-driver-registrar-in-csi-rbdplugin-kqdsj.txt](https://github.com/ceph/ceph-csi/files/2559400/logs-from-driver-registrar-in-csi-rbdplugin-kqdsj.txt)
[logs-from-csi-rbdplugin-in-csi-rbdplugin-kqdsj.txt](https://github.com/ceph/ceph-csi/files/2559401/logs-from-csi-rbdplugin-in-csi-rbdplugin-kqdsj.txt)

**Comment by rootfs** [comment]
this is where rbd got stuck, 
```
rbd: status pvc-6fa0d2c1e2d811e8 using mon pve2.wbig-wg.net:6789,pve3.wbig-wg.net:6789,pve6.wbig-wg.net:6789, pool test id kubernetes key AQAWDeJbnPREOhAASSyoGW8YmZPM49ct5AQlvQ==
```

can you check on your rbd driver container, if 
`rbd status --pool test -m pve2.wbig-wg.net:6789,pve3.wbig-wg.net:6789,pve6.wbig-wg.net:6789 --id kubernetes --key=AQAWDeJbnPREOhAASSyoGW8YmZPM49ct5AQlvQ== pvc-6fa0d2c1e2d811e8` works?

**Comment by compilenix** [comment]
```
2018-11-08 14:00:32.896988 7f1f2467ad40 -1 did not load config file, using default settings.
2018-11-08 14:00:32.901703 7f1f2467ad40 -1 Errors while parsing config file!
2018-11-08 14:00:32.901718 7f1f2467ad40 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory
2018-11-08 14:00:32.901720 7f1f2467ad40 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory
2018-11-08 14:00:32.901721 7f1f2467ad40 -1 parse_file: cannot open ceph.conf: (2) No such file or directory
2018-11-08 14:00:32.902992 7f1f2467ad40 -1 Errors while parsing config file!
2018-11-08 14:00:32.903005 7f1f2467ad40 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory
2018-11-08 14:00:32.903007 7f1f2467ad40 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory
2018-11-08 14:00:32.903007 7f1f2467ad40 -1 parse_file: cannot open ceph.conf: (2) No such file or directory
2018-11-08 14:00:32.946054 7f1f2467ad40 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.kubernetes.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
```

and 

```
ls -la /etc/ceph/
total 12
drwxr-xr-x 2 root root 4096 Oct 26 14:08 .
drwxr-xr-x 1 root root 4096 Nov  7 21:58 ..
-rw-r--r-- 1 root root   92 May 21 11:32 rbdmap
```

**Comment by compilenix** [comment]
I also tried the following:
```
# rbd du --pool test -m pve2.wbig-wg.net:6789,pve3.wbig-wg.net:6789,pve6.wbig-wg.net:6789 --id kubernetes --key=AQAWDeJbnPREOhAASSyoGW8YmZPM49ct5AQlvQ==
```

the output is the same and the command does hang / not complete.

**Comment by compilenix** [comment]
Ahh i found that the ceph monitor does listen on a seperate ip address and not to any address (as i assumed). the cli test from the container works now.

i'll try this by updating the config that the pod's use and report here again.

**Comment by rootfs** [comment]
cool!
