### ISSUE TITLE
How to migrate PV，PVC created by different storageclasses

### ISSUE THREAD

**Issue by luhailiang0527** [ceph/ceph-csi#989]
@Madhu-1 thank you very much for this issue. and i also have a problem,How to migrate PV，PVC created by different storageclasses，Details are as follows：
source storageclass
NAME PROVISIONER RECLAIMPOLICY VOLUMEBINDINGMODE ALLOWVOLUMEEXPANSION AGE
slow ceph.com/rbd Retain Immediate true 27d
destination storageclass
NAME PROVISIONER RECLAIMPOLICY VOLUMEBINDINGMODE ALLOWVOLUMEEXPANSION AGE
csi-rbd-sc rbd.csi.ceph.com Delete Immediate true 3d17h

**Comment by Madhu-1** [comment]
@luhailiang0527 I don't think it's possible as the PV object is immutable you cannot edit the driver name and other details in PV object.

**Comment by luhailiang0527** [comment]
@Madhu-1  Is there a solution to such a problem，Is there any other way based on what you know

**Comment by Madhu-1** [comment]
nothing am aware of, one thing I can thinkis using static PVC to mount older rbd images.

**Comment by luhailiang0527** [comment]
@Madhu-1  thank you  you can help me analysis this，Is it a solution to the problem https://github.com/redhat-cop/openshift-toolkit/tree/108586d05bf9e85854801509359e7b09dd05f08f/storage/pv-migrator

**Comment by Madhu-1** [comment]
closing this one as this is outside of cephcsi.
