### ISSUE TITLE
RADOS permission error during Cephfs PVC creation

### ISSUE THREAD

**Issue by ragingpastry** [ceph/ceph-csi#996]
# Describe the bug #

I have deployed ceph-csi in my cluster using the manifest files provided in this repository. I am unable to provision a new volume when submitting a PVC. I received the error:

[errno 1] RADOS permission error (error connecting to the cluster)

# Environment details #
Images:
```
quay.io/k8scsi/csi-provisioner:v1.4.0
quay.io/k8scsi/csi-snapshotter:v1.2.2
quay.io/k8scsi/csi-attacher:v2.1.1
quay.io/k8scsi/csi-resizer:v0.5.0
quay.io/cephcsi/cephcsi:v2.1.
```
logs
```
W0428 20:50:53.370713       1 controller.go:887] Retrying syncing claim "788fe221-76b4-4be7-892e-9ca1ff49c707", failure 30
E0428 20:50:53.370848       1 controller.go:910] error syncing claim "788fe221-76b4-4be7-892e-9ca1ff49c707": failed to provision volume with StorageClass "csi-cephfs-sc": rpc error: code = InvalidArgument desc = an error occurred while running (796) ceph [-m x.x.x:6789,x.x.x.x:6789,x.x.x.x:6789 --id client.admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs get test --format=json]: exit status 1: [errno 1] RADOS permission error (error connecting to the cluster)
I0428 20:50:53.371441       1 event.go:255] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"csi-cephfs-pvc", UID:"788fe221-76b4-4be7-892e-9ca1ff49c707", APIVersion:"v1", ResourceVersion:"2382752", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "csi-cephfs-sc": rpc error: code = InvalidArgument desc = an error occurred while running (796) ceph [-m x.x.x.x:6789,x.x.x.x:6789,x.x.x.x:6789 --id client.admin --keyfile=***stripped*** -c /etc/ceph/ceph.conf fs get test --format=json]: exit status 1: [errno 1] RADOS permission error (error connecting to the cluster)
```

# Steps to reproduce #

1. Deploy ceph-csi cephfs
1. Create new PVC
1. See error

# Actual results #

Unable to provision a new volume

# Expected behavior #

Able to provision a new volume

# Additional context #

For example:

Any existing bug report which describe about the similar issue/behavior

**Comment by Madhu-1** [comment]
the log clearly says that this is a permission issue, can you please check you are using valid credentials and the user is having required permission to access the cluster.

**Comment by Madhu-1** [comment]
closing this one as this is a permission issue, hope nothing can be done on cephcsi side other than documenting the capabilities which will be covered in #360
