### ISSUE TITLE
make util.clusterInfo usable outside of the util package

### ISSUE THREAD

**Issue by nixpanic** [ceph/ceph-csi#998]
Functions like `getClusterInformation()` should probably return a `util.ClusterInfo` struct, instead of the single members.

This requires the current `util.clusterInfo` from to be renamed to `util.ClusterInfo` so that `internal/cephfs/volumeoptions.go` can use it. Also the copies in `e2e/utils.go` can then be removed.

**Comment by Madhu-1** [comment]
@Yuggupta27 let me know if you take it up.

**Comment by nixpanic** [comment]
> /assign @Yuggupta27

This does not work until we have a bot that handles these requests. After @Yuggupta27 responds in this issue, we can manually assign him.

**Comment by Yuggupta27** [comment]
Thanks! I'm on it👍
